readthedocs/readthedocs.org

- onebox_requirements.txt
pip will complain about the duplication with the error:
Double requirement given: pyquery (from -r onebox_requirements.txt
(line 6)) (already in pyquery==1.2.2 (from -r pip_requirements.txt
(line 47)), name='pyquery')
> Remove pyquery as it is already in the pip_requirements

- media/css/core.css
- readthedocs/builds/models.py
- readthedocs/projects/backends/views.py
- readthedocs/projects/models.py
- readthedocs/projects/urls/private.py
- readthedocs/projects/urls/public.py
- readthedocs/projects/views/base.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/base.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/templates/core/project_details.html
- readthedocs/templates/projects/onboard_detail.html
- readthedocs/templates/projects/onboard_import.html
- readthedocs/templates/projects/project_dashboard_base.html
This adds some messaging for the first project import, but only for the first 5 builds. This also adds a demo project import, which is currently our template project, which is imported with one click. Some guidance is added for the following scenarios on the project detail page:
* Project has no builds (should never be the case, but added anyways)
* Project is building, please wait
* Project has a failing build, link to FAQ for now
* Project has a passing build, set up a webhook
In the future, this should track user input, so onboarding can be closed -- though it isn't intrusive messaging right now either.
On the dashboard page, onboard messaging prompts the user to import a new project, or import the demo project. Clicking this button will attempt to import the project for the current …
> Add some project import onboarding for first project/builds

- readthedocs/settings/base.py
When attempting to install readthedocs from scratch, installation fails because the migrations in `builds` depend on migrations from `projects`.  While these dependencies can be explicitly modelled in newer versions of South, they are implicitly modelled in older versions via app ordering.
This commit fixes the installation, but a better solution might be to update to the latest South and model this dependency explicitly.
> Place `projects` before `builds` in INSTALLED_APPS

- readthedocs/templates/mkdocs/readthedocs/searchbox.html
MkDocs 0.11 [disabled the searchbox](https://github.com/tomchristie/mkdocs/commit/349515f98a0aad1a13c76f6435503776fcf5b2bf), pending implementation of client-side search in mkdocs. This makes ReadTheDocs search a bit less usable.
This commit adds a searchbox.html to the custom theme, which is identical to the upstream version before it was commented out. I've tested on a local readthedocs copy.
Fixes https://github.com/rtfd/readthedocs.org/issues/1074.
> Un-disable the mkdocs searchbox

- readthedocs/search/utils.py
I've got a Markdown ReadTheDocs site, with 'use_directory_urls' set to false (as a workaround for https://github.com/rtfd/readthedocs.org/issues/1101). This breaks the search - the results go to a path like Configuring_an_Application_Server/**index.html.html** (see https://readthedocs.org/elasticsearch/?q=example&check_keywords=yes&area=default&project=clearwater&version=latest&type=file).
This patch should fix that. I've done some very basic testing - I have a local copy of readthedocs running, and I confirmed that before this change I got a log like:
`[07/Feb/2015 12:19:36] INFO [projects.tasks:663] (Search Index) Sending Data: cw-rtd [index.html Clearwater_Elastic_Scaling/index.html All_in_one_Images/index.html ...`
and afterwards like:
`[07/Feb/2015 12:23:43] INFO [projects.tasks:663] …
> Strip trailing '.html' from paths before searching

- readthedocs/core/templatetags/core_tags.py
- readthedocs/rtd_tests/tests/test_core_tags.py
Even after #1147 was merged, and even after a rebuild of my docs, I'm still seeing the problem where search links come up as "page.html.html" (e.g. https://readthedocs.org/elasticsearch/?q=example&check_keywords=yes&area=default&project=clearwater&version=latest&type=file).
I've done a bit more digging, and found another likely culprit - this PR prevents the `doc_url` tag (used in the elastic_search.html template) from adding an extra trailing .html as well.
> More stripping of '.html. suffix on URLs

- pip_requirements.txt
This pull request upgrades RTD to use the latest stable version of [`pip`](https://pypi.python.org/pypi/pip). The older version has trouble installing certain packages. In particular, a useful test case is:
```
pip install -e hg+https://bitbucket.org/espd/sphinx-contrib#egg=sphinxcontrib_aafig&subdirectory=aafig
```
I discovered this when trying to use [aafig](https://pypi.python.org/pypi/sphinxcontrib-aafig/1.0) in my documentation. The version that is currently published on PyPI is broken, but [there is a pull request to fix it](https://bitbucket.org/birkenfeld/sphinx-contrib/pull-request/64), which has not yet been merged. I wasn't able to use this fork in my project dependencies, however, because `pip` 1.5.6 was unable to install it. [Here's an example of a failing …
> Upgrade pip to 6.0.8

- readthedocs/projects/tasks.py
- requirements/pip.txt
Mkdocs, version 0.11.1, contains a bug concerning trailing slashes when
you navigate down the page tree. 0.12.1 fixes that issue and resolves #1229
> Update mkdocs version due to bug in 0.11.1.

- docs/sponsors.rst
- readthedocs/restapi/templates/restapi/footer.html
- update name and URL from gittip to gratipay
- On sponsors.rst, update only URL and not the Sphinx reference. I am not certain how to update all of the .po files that use the reference, whether in this repo or via Transifex. Please advise. See https://github.com/rtfd/readthedocs.org/search?l=pot&p=1&q=gittip&utf8=%E2%9C%93
> update name and URL from gittip to gratipay

- readthedocs/doc_builder/backends/sphinx.py
...instead of the alphabetically first.
There may be lots of pdf files lying around in the build directory
(embedded graphics in pdf format). Just serving the alphabetically
first will almost-always choose the wrong file.
The final compiled pdf depends on the other ones, hence it is
always the newest.
> pdf glob matching: Serve the newest file

- README.rst
Existing links points to an outdated subdomain (which maybe should be changed to a redirect to the new one).
> Fix main "docs about RTD" link to the current one

- readthedocs/templates/mkdocs/readthedocs/base.html
As of the development version of MkDocs, the template is used to build a few extra templates like the 404.html page. While these may not be used on ReadTheDocs, they will still be built.
On these pages, the context is very similar, but there is no current page as that object represents a Markdown file.
I assume this is used by the ReadTheDocs JavaScript, is there something sensible I can set it to for these sorts of pages?
> Only use the current_page if it is available in the MkDocs template

- readthedocs/projects/migrations/0044_make_repositoryurl_longer.py
- readthedocs/projects/models.py
100 was too small. We can easily end up with long urls when using private repositories and we need to add credentials within that url.
> Increasing repository url field size to 255

- readthedocs/templates/base.html
read-the-docs.readthedocs.org seems to be a stub with just the index page; docs.readthedocs.org has all the content.
> Fix link from UI to RTD docs

- docs/install.rst
The docs contained a mistyped command `pip-install`.
> Fixing typo in install docs 'pip-install' -> 'pip install'.

- readthedocs/rtd_tests/tests/test_builds.py
Mocking `os.path.exists´ in `rtd_tests.test_builds.BuildTests.test_build` in order to simulate a successfull project checkout including the conf.py file defined in the Project model.
That should fix the currently broken build, see https://travis-ci.org/rtfd/readthedocs.org/builds/62574036
I'm not sure if that is the way to go as it more or less silences the issue that the `Project` model touches the filesystem. The filesystem access should be encapsulated somehow so that it can easily be switched out. But that might be a bigger task. Better to fix the mocks now to get the builds back to green :)
> Mocking os.path.exists in test_builds.BuildTests.test_build

- runtests.sh
Forcing tests to be run with LANG=C. Otherwise the tests might fail if a non english locale is active.
The problem is that system messages change. And it seems that the tests rely on those messages to be english. If I'm using `LANG=de_DE.UTF-8`, the test suite fails with:
```
(readthedocs.org) gregor@layka ~/projects/readthedocs.org (git)-[master] % ./runtests.sh 
================================================================= test session starts ==================================================================
platform linux2 -- Python 2.7.9 -- py-1.4.27 -- pytest-2.7.1
rootdir: /home/gregor/projects/readthedocs.org, inifile: 
plugins: django
collected 210 items 
rtd_tests/tests/test_404.py .......
rtd_tests/tests/test_api.py ........
rtd_tests/tests/test_backend.py ...... …
```
> Forcing tests to be run with LANG=C

- readthedocs/vcs_support/backends/github.py
- readthedocs/vcs_support/backends/launchpad.py
- readthedocs/vcs_support/base.py
- readthedocs/vcs_support/test.py
placing standard libraries first. stdlibs, third party libs, django libs, rtd libs.
> [trivial] vcs_support: organize imports

- docs/install.rst
This PR specifies the major Python version number for local installs so nobody else needs to ask. Thanks!
> Specify Python 2.7 in local install doc

- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/projects/tasks.py
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/search_views.py
- readthedocs/search/indexes.py
- requirements/pip.txt
- Many thanks to @robhudson, who wrote the original 0.90 -> 1.0+ ElasticSearch query code.
- Updating pip elasticsearch requirement to 1.5.0 for the new server.
- Refactor argument order to match new API.
- Updated to boost relevance in a Elasticsearch >= 1.0 way
- Removing score script and adding in field_value_factor per @robhudson's insight.
- Adding default project_scale and page_scale values.
- Found the source of the 400 error on _bulk, and noted.
> Elasticsearch 1.5.0 Upgrade, including:

- readthedocs/projects/tasks.py
Fixes gh-1263, failure to create Python 3 virtualenvs (I hope)
The problem appears to be that `virtualenv -p python3` re-executes its own file in site-packages as a script under Python 3. Because the directory containing a script is prepended to `sys.path`, the contents of Python 2 site-packages are then on sys.path for Python 3. [python-future](http://python-future.org/) is installed in Python 2, providing certain standard library modules under their Python 3 names. So when it tries to import copyreg, it finds the compatibility module for Python 2 instead of the standard Python 3 module, making future fail with the error:
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is …
> Use python -m to create virtualenvs

- readthedocs/projects/tasks.py
We're reporting a lot of PDF builds as failed. Implement this hueristic, so we can report success properly.
> Hack pdf success

- readthedocs/projects/tasks.py
This fixes applying our theme CSS after user-supplied CSS. We still add our custom embed at the end, but the theme CSS at the front.
> Upgrade sphinx ext

- requirements/deploy.txt
This comment was targeted at pyquery which was removed removed from this
file in d8b5adc. It's now in requirements/pip.txt.
> Remove outdated comment

- readthedocs/projects/tasks.py
- requirements/pip.txt
Requires release of readthedox-sphinx-ext 0.5.4 first:
refs rtfd/readthedocs-sphinx-ext#10
fixes #1337
> Bump readthedocs-sphinx-ext version to 0.5.4

- readthedocs/projects/models.py
It results in nicer styling in the project's admin page if an appropriate markup is used in the help text strings.
For example:
> Add <code> markup in helptexts where applicable

- readthedocs/builds/constants.py
- readthedocs/core/management/commands/update_repos.py
- readthedocs/core/management/commands/update_versions.py
- readthedocs/doc_builder/loader.py
- readthedocs/projects/constants.py
- readthedocs/projects/forms.py
- readthedocs/projects/migrations/0045_add_format_build_options.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
As propsed in #1154 we should have the ability to disable pdf and epub builds.
This pull request implements the requested feature.
> Adding option to disable pdf/epub builds for sphinx based projects.

- readthedocs/projects/tasks.py
- requirements/pip.txt
This is primarilly a bug fix release. It would have been a 0.13.4 but we
*dropped* two requirements that caused problems and felt that was
sufficient reason to release a 0.14 version.
Fixes #1373
> Upgrade MkDocs to 0.14

- .travis.yml
- requirements/pip.txt
As mentioned in #1369 the 2.5b4 version of bzr can make problems as it is not available on PyPI. The 2.6 version however is. I assume it's save to upgrade to the newer version based on this line from the [release notes](http://doc.bazaar.canonical.com/bzr.2.6/en/whats-new/whats-new-in-2.6.html):
> Bazaar 2.6.0 is fully compatible both locally and on the network with 2.0, 2.1, 2.2, 2.3, 2.4 and 2.5, and can read and write repositories generated by all previous versions.
I also removed the `--allow-external` and `--allow-unverified` flags from requirements files as they might introduce security risks. The installation still works as the Travis builds will show.
> Updating bzr to 2.6 and removing --allow-unverified flag from requirements

- readthedocs/templates/projects/project_version_list.html
Ya. It's all in the heading and fixes #1353
> Fixed #1353 -- Removing broken (Help) link from versions page.

- readthedocs/templates/core/project_detail_right.html
Make the repository URL that appears along the right side of the project
page a clickable URL using Django's urlize filter. This filter will only
make a clickable link if the repository URL is a valid HTTP address.
Closes #379
> feat(project): Make repo URL a clickable URL.

- readthedocs/builds/migrations/0024_fix_slugs_with_leading_placeholders.py
- readthedocs/builds/version_slug.py
- readthedocs/rtd_tests/tests/test_version_slug.py
There is another issue with slugs that was raised in #1176. The current implementation turns uppercase letters into dashes so that `SomeChar-charclass` as branch name results in `-ome-har-charclass` as slug. However our regex in the URLs don't allow leading dashes.
This PR changes the algorithm to strip punctuation from the generated slug. It includes a migration to fix the currently broken slugs. I tested locally that pypy's version page works after applying it.
> Fix slug generation for uppercase branch names

- readthedocs/projects/utils.py
Closes #1403 
This fixes an issue installing sphinx and setting the virtualenv when the env variable `PYTHONHOME` exists. Currently there is a check for `PYTHONPATH`, but not for `PYTHONHOME`.
> fix(sphinx):adding check for PYTHONHOME

- readthedocs/settings/base.py
I think it is a good practice to wrap every request in a transaction. I think we already have lots of places in the codebase that do not explicitly run in a transaction which makes it possible that a requests aborts in the middle (for example in case of an exception) and leaves the DB in an inconsistent state as we might have already processed some, but not all incoming data.
The [django documentation states](https://docs.djangoproject.com/en/1.7/topics/db/transactions/#tying-transactions-to-http-requests) that this might impact performance a bit depending on the used database.
So I'm not sure if that really is the perfect option for readthedocs, but I think we make everything a little more predictable that way :)
> Use ATOMIC_REQUESTS=True to wrap every django request in a database transaction

- readthedocs/core/utils.py
It was in there but was actually never used anywhere in the history of the project:
```
(readthedocs.org) gregor@layka ~/projects/readthedocs.org (git)-[master] % git log -Smake_latest -p
commit b7ac78737f73f7d998d1234e3eb9e5fdd8539276
Author: Eric Holscher <eric@ericholscher.com>
Date:   Tue May 13 18:00:35 2014 -0700
Add basic make_latest util
diff --git a/readthedocs/core/utils.py b/readthedocs/core/utils.py
index 3aa81c6..4bba334 100644
--- a/readthedocs/core/utils.py
+++ b/readthedocs/core/utils.py
@@ -105,3 +105,21 @@ def run_on_app_servers(command):
else:
ret = os.system(command)
return ret
+
+def make_latest(project):
+    """
+    Useful for correcting versions with no latest, using the database.
+
+    >>> no_latest = Project.objects.exclude(versions__slug__in=['latest'])
+ …
```
> Removing unused core.utils.make_latest

- readthedocs/builds/version_slug.py
- readthedocs/rtd_tests/tests/test_version_slug.py
The version slug regex was previously not allowing single char slugs. This PR fixes that and is adding appropriate tests.
Closes #1405.
> Allow single char version slugs.

- readthedocs/projects/tasks.py
We updated the virtualenv in requirements/pip.txt for #1426. However that
did only touch the virtualenv of readthedocs, not the ones of the builds. So
updating it with this change.
Fixes #1428.
> Update virtualenv and setuptools in doc build envs

- readthedocs/projects/models.py
- readthedocs/rtd_tests/mocks/paths.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/rtd_tests/tests/test_project.py
As reported in #1425 we don't hide the PDF builds yet when the `enable_pdf_build` option is set (same for epub). This pull request fixes it and includes tests for it.
Fixes #1425.
> Disable link to pdf/epub builds in footer if appropriate

- readthedocs/projects/management/commands/import_project_from_live.py
Hi, I created the `import_project_from_live` command for easier debugging of readthedocs.org support tickets. When project's experience unusual behaviour in the admin, its useful to install the project locally to test the builds etc.
It's using the public API to retrieve the live data.
> Adding import_project_from_live command for debugging

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/mocks/mock_api.py
- readthedocs/rtd_tests/tests/test_celery.py
This is a follow up to #1458 as I noticed a bug in there. The following code introduced a bug:
```
if api is None:
api = api.client.api
api = api_v1
```
`api` is a parameter in the function. When not given it is `None`, and
it shadows the module import for `api.client`. Therefore it will raise an
exception ...
Sorry. This PR fixes that.
> Fix usage of `api` variable in update_imported_docs

- .travis.yml
- docs/tests.rst
- prospector.yml
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- tox.ini
This is a example of some improved linting and testing configuration, thoughts are welcome.
This is an example of linting using [Prospector][prospector], which is a wrapper around a number of tools -- including flake8 and pylint. It includes a configuration that will set a low bar to getting back to linting code, and is configurable by strictness profile -- which is something we can increase when we start to clean things up more.
Output of a run here:
https://travis-ci.org/rtfd/readthedocs.org/builds/71619840
This also starts to use tox, as suggested by @destroyerofbuilds, which seems like an easy way to at least combine our testing, linting, and doc creation test commands into one tool, instead of one-off shell scripts. It makes for more reproducible tests as well, handling virtualenv …
> Linting and starting to use Tox

- docs/custom_installs/local_rtd_vm.rst
The rst parser was incorrectly interpreting broken URLs:
[http://\[VM](#) IP ADDRESS]:8000/admin
vs
`http://[VM IP ADDRESS]:8000/admin`
> Encapsulated text in backticks to fix formatting

- docs/contribute.rst
- docs/index.rst
- docs/issue-labels.rst
This PR documents and summarizes our approach at triaging open tickets.
It's open for discussion. See here for the current formatted version: https://github.com/rtfd/readthedocs.org/blob/triaging-docs/docs/contribute.rst
> Add triaging documentation to contribution guide

- readthedocs/settings/onebox.py
- readthedocs/settings/postgres.py
- readthedocs/settings/sqlite.py
- readthedocs/settings/test.py
- tox.ini
If you use local_settings.py for development, tox will currently try to use
those settings. This disregards local_settings inside settings.test and friends
so that there is no chance for overlap.
> Add tox setting to disregard local_settings.py

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_project_views.py
This will make it so that we default to using Sphinx, since we now have support for Commonmark in Sphinx.
> Default to Sphinx docs

- docs/custom_installs/local_rtd_vm.rst
- docs/i18n.rst
The location of the manage.py file changed with #1496. Accommodate that in the
docs as well.
> Fix reference to path to manage.py in documentation

- readthedocs/core/views.py
- readthedocs/rtd_tests/tests/test_views.py
I broke it in c5bed3d4 :( Now I'm fixing it and adding tests.
Was revealed by pylint.
> Fix undeclared variable in core.views.random_page

- readthedocs/projects/tasks.py
It seems to be broken since https://github.com/rtfd/readthedocs.org/commit/0f045f35d8105292576d064329a99174c0ff28c8
I haven't run the code myself but it's obviously missing the `project` variable. It's like that since Oct 2014, which makes me think if that feature is still supported?
It was revealed by Pylint :dragon:
> Fix missing variable in project.tasks.webhook_notification

- readthedocs/projects/utils.py
It's broken, not used in the project and superseded by oauth.utils.github_paginate.
> Remove unused projects.utils.github_paginate

- readthedocs/gold/forms.py
- readthedocs/gold/views.py
This method was added in 1.8 and can replace our custom CardForm.addError method.
> Use Django's builtin Form.add_error instead of custom addError

- requirements/deploy.txt
- requirements/pip.txt
They were only in requirements/deploy.txt but were required in a few places
in the codebase. That means that developers can come into a situation were
they end up missing these libraries even when they installed all dependencies
according to the docs.
> Move dnspython and launchpadlib into requirements/pip.txt

- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_subproject.py
- readthedocs/rtd_tests/tests/test_views.py
- requirements/pip.txt
Currently you didn't need to be a admin in the subproject to add it as a
project. That way your project could end up as a subproject in project you
don't know about without you being asked for permission.
That has lead to situations were you added a subproject by accident but were
not able to remove it again from your own project since removing it required
admin permissions on the subproject. This PR removes the "am I admin" on the
subproject when removing it.
I added the django-dynamic-fixture library for easy fixture generation. I know
we already have bambooboy for this in the project. But I have issues with this
library. I will propose something related to that later.
Fixes #1122.
Fixes #1341.
> Require admin status in project to add it as a subproject

- readthedocs/settings/postgres.py
allauth redirects to GitHub for the social login using a HTTP URL by default.
However the GitHub app is setup to expect a HTTPS URL. So we need to instruct
allauth to use one as well.
Fixes #1520.
> Set ACCOUNT_DEFAULT_HTTP_PROTOCOL to 'http' in production

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Currently the conf.py.tmpl will overwrite the `source_parsers['.md']` setting if
it is set. Check if it already set and leave it alone if so.
Fixes #1527.
> Make source_parsers['.md'] configurable in conf.py

- readthedocs/doc_builder/backends/sphinx.py
Otherwise it defaults to being in the output,
and gets copied to the webheads,
bloating disk usage.
> Specify doctree location in Sphinx build

- readthedocs/core/views.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
- readthedocs/urls.py
Add a dedicated GitLab webhook end-point for push events on a
GitLab-hosted project.
The GitLab webhook end-point must be separate from GitHub as the
contents of GitLab's POST message, resulting from a push event, has
different payload data than what is found in an equivalent GitHub POST.
Closes #1442
> feat(webhook): Add GitLab webhook end-point.

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
This fixes #994, where the 127 character limit on shebang line lengths was
triggering failures of commands inside virtualenvs that had long names or
long branch names. This PR adds some path environment variable handling to
allow for shorter commands, and makes all python script call wrapped by a
call to the virtual env symlinked python binary.
This depends on the pending pull request #1524, for adding docker
containerization and should be rebased after that PR is merged.
> Call python scripts as argument to virtualenv python command

- docs/install.rst
The `./manage.py migrate` was instructed to be run in a wrong directory. And it stated that it will prompt you to create a superuser. However since Django 1.7, it doesn't so the docs now also contain instructions to add a superuser `createsuperuser`.
Fixes #1566.
> Fix install developer docs

- readthedocs/core/views.py
Documentation may also include SVG images, so they should be
treated the same as PNG and JPG files.
> Add exclude for SVG files

- readthedocs/projects/search_indexes.py
- requirements/pip.txt
Also fix pyquery part as it no longer raises an exception
on not finding it's query in the document.
This should fix some issues I've found when deploying RTD myself.
> Upgrade haystack to work with Django 1.8

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/mocks/mock_api.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/templates/projects/email/build_failed.html
- readthedocs/templates/projects/email/build_failed.txt
Also adds the error for global failure into the email. This should only ever be
a line or two, so shouldn't drown out the email
> Fix email notifications on build failures

- readthedocs/projects/tasks.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_project_views.py
Currently we only did that on the server where the project deletion was triggered.
Related #1579.
> Remove project artifacts from all web servers on project delete

- readthedocs/doc_builder/environments.py
- readthedocs/projects/migrations/0004_add_project_container_image.py
- readthedocs/projects/models.py
This allows for multiple container images, with varying support for resource
intensive tooling/etc.
> Add per-project, admin-only container image configuration

- prospector.yml
- readthedocs/builds/models.py
- readthedocs/comments/views.py
- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/base.py
- readthedocs/projects/admin.py
- readthedocs/projects/backends/views.py
- readthedocs/projects/constants.py
- readthedocs/projects/exceptions.py
- readthedocs/projects/feeds.py
- readthedocs/projects/filters.py
- readthedocs/projects/forms.py
- readthedocs/projects/management/commands/import_project_from_live.py
- readthedocs/projects/models.py
- readthedocs/projects/search_indexes.py
- readthedocs/projects/signals.py
- readthedocs/projects/symlinks.py
- readthedocs/projects/tasks.py
- readthedocs/projects/templatetags/projects_tags.py
- readthedocs/projects/urls/private.py
- readthedocs/projects/urls/public.py
- readthedocs/projects/utils.py
- readthedocs/projects/version_handling.py
- readthedocs/projects/views/base.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/search/parse_json.py
- readthedocs/search/utils.py
This lints project code to medium strictness and conforms to pep257. This uses
some additional options to reduce false errors, which I'll add in a separate PR.
This should pass our normal linting without a problem, except the minor change
to unused variable name regex.
This adds `__` to the default list of `_` and `dummy*` for unused arguments. I
prefer the default of `_`, but that overlaps with the translation helper `_()`.
I'd be happy to rethink a scheme here.
Fixes #1472, refs #1474
> Lint project code

- docs/faq.rst
The added paragraph documents how to reference a python package in the repository that you want to have installed during a documentation build.
Fixes #1567.
> Add docs on how to use install local python packages with pip during build

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/constants.py
- readthedocs/doc_builder/environments.py
This could be all of rtd.org checkout as well. Without this mount, sphinx will
not inject the context data into the output docs, and will pass without failure.
> Add mount for missing template path in docker container creation

- readthedocs/projects/migrations/0005_sync_project_model.py
These fields have minor updates:
* documentation_type now defaults to 'sphinx' instead of auto
* docstring updates on use_virtualenv and single_version attributes
> Add missing project migrations

- docs/builds.rst
- docs/getting_started.rst
As MkDocs doesn't support automatic PDF generation, selecting the
Mkdocs documentation type means that you can't enable PDF builds.  Where
Mkdocs or markdown is mentioned in the docs, this is more explicit.  Related to issue #1635 .
> Make explicit: no Mkdocs automatic PDF generation.

- readthedocs/projects/views/public.py
The badges provided by readthedocs.org are created using shields.io, using a redirect. We did not have the Cache-Control set on those redirects which might make GitHub cache the badges too aggressively when they are used in a README file.
The https://github.com/github/markup/issues/224 issue explains that we need to set the Cache-Control and ETag header to disable caching for the badges. However we are not serving the badges, but redirecting, so we just need to try out whether a Cache-Control header on the redirect has any effect. I did a quick google search but was not able to find if it's valid to set ETag headers on a redirect. I think it's nonsense as the body of a redirect response is usually empty.
Related #1612
> Set Cache-Control: no-cache for redirects to badges

- readthedocs/builds/models.py
- readthedocs/projects/models.py
The original implementation replaced "/conf.py" with an empty string, where it
only wanted to return the directory name of the conf.py file. This resulted in
problems when "/conf.py" was part of the directory name!
Fixes #1553.
> Fix logic in Project.conf_dir

- readthedocs/builds/constants.py
- readthedocs/builds/models.py
- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/privacy/backend.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_supported.py
- readthedocs/rtd_tests/tests/test_version_commit_name.py
The two places were solving the same problem but with different results. That is undesired and resulted in invalid behaviour. The commit_name property unifies those now and has tests to make sure it works the way intended.
The problem with this on-first-sight-easy problem is that we currently do store different things in "identifier", "slug", "verbose_name" fields depending if its a branch or tag, if it's a special version (like stable, latest) etc. The cleanest solution would be to refactor the Version model to expose those information more easily and store branch_name, tag_name, explicitly.
One problem of this manifested in #1637
> Replace Version.get_vcs_slug() and Version.remote_slug with Version.commit_name

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
We had some tickets in the past resulting from users that didn't realize that Sphinx options might get overridden with the code that gets appended to the conf.py before every build (for example #1622, #885).
This PR includes the resulting conf.py as part of the build log in the users project panel and therefore increases the visibility a lot. I assume this will reduce confusion about what happens with the conf.py in the future.
It looks like this:
> Show rendered conf.py file in build logs

- readthedocs/templates/sphinx/layout.html
Previously the canonical url for the `genindex.html` were broken because the `index.html` bit was stripped.
Fixes #1114.
> Fix generation of canonical_page when it ends on "index"

- requirements/pip.txt
It isn't on pip anymore? We're not using it as a library anyways. This should be a system level dependency if it isn't already.
> Drop bzr from requirements

- readthedocs/builds/models.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/rtd_tests/tests/test_version_model.py
Move project's assign view permission logic and handling for `view_version` into set_user_permissions method.
That was previously handled in a few different places. We now unify it and testing. Also we remove the `view_project` permission correctly when a user is removed from the project.
Fixes #943.
> Correctly handling view_project/view_version permissions on user add/remove

- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/projects/tasks.py
The command was obviously broken as explained in #1641. This PR fixes the outstanding bugs and added a simple check whether the passed in project slug actually exists.
I have tested it until elasticsearch is actually involved, no further since I don't have a working elasticsearch setup.
Please note that the semantics changed very slightly as the now used `update_search` does not pass the `delete=False` flag to `index_search_request` as the previous code in the management command did. Please consider this during review.
In my understanding the same logig used for the actual search index updates on the server via `update_search` should also work for a manual reindex.
Fixes #1641.
> Refactor and fix reindex_elasticsearch management command

- readthedocs/api/base.py
- readthedocs/builds/models.py
- readthedocs/builds/views.py
- readthedocs/core/context_processors.py
- readthedocs/privacy/backend.py
- readthedocs/privacy/loader.py
- readthedocs/restapi/templates/restapi/footer.html
- readthedocs/restapi/views/footer_views.py
- readthedocs/rtd_tests/tests/test_privacy.py
- readthedocs/templates/builds/build_list.html
- readthedocs/templates/core/project_details.html
- readthedocs/templates/core/project_downloads.html
- readthedocs/templates/projects/project_version_list.html
This adds a specific Build manager that checks the privacy level of the Version, so that we can show the proper list of builds.
Also adds some saner handling to default empty states in the templates, and removes the `*args` and `**kwargs` arguments to the templates, as this was not necessary.
> Add a BuildManager & proper UI around filtered out builds

- docs/settings.rst
- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
This will be the domain that public documentation is served,
if it is different than private.
This allows for auth handling on private domains,
while allowing public docs to be cookie-free.
> Add support for public domain.

- readthedocs/core/resolver.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_resolver.py
Previously we were defaulting to the project privacy,
which led to broken privacy guessing on `latest` versions.
> Handle proper resolution of privacy level on versions.

- readthedocs/urls.py
Just a new syntax for handling static. Leftover from my Windows fixes. BTW, rtfd development version is now working on on this platform.
> Use modern URL scheme for localhost static

- readthedocs/projects/migrations/0007_migrate_canonical_data.py
- readthedocs/projects/migrations/0010_migrate_domain_data.py
- readthedocs/projects/models.py
- readthedocs/redirects/admin.py
- readthedocs/vcs_support/backends/bzr.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/backends/svn.py
it does not make RTD run completely on Py3 of course, far from it, but it's a first step.
> Make some part of the codebase single source

- readthedocs/doc_builder/environments.py
Adds environment variable called RTD_VERSION_SLUG to identify selected version in conf.py.
See #1096 for more details.
> Added RTD_VERSION_SLUG environment variable.

- readthedocs/restapi/views/footer_views.py
This fixes an issue where the 'you're not on the latest version' links to a private version.
> Only consider public versions on compare

- readthedocs/api/base.py
- readthedocs/builds/views.py
- readthedocs/projects/utils.py
- readthedocs/settings/onebox.py
- readthedocs/settings/sqlite.py
- requirements/deploy.txt
- requirements/pip.txt
Redis will be split up into calls to redis cache server and redis celery
server.  Instead of calling the intermediate object in settings, use existing
configuration for these two databases.
This bumps the version number for redis_cache, as it's far behind, as well as
the version for redis.
> Alter direct calls to redis using intermediate redis settings

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This was forcing `_static` to the static paths variable previously. This will
optionally include the path instead.
Refs #1776
> Check for _static path in confpy overrides

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
This moves the pip cache to a project-local path, so that it persists into new docker containers.
Fixes #1783
> Add explicit pip cache path to pip install calls and models

- readthedocs/comments/views.py
- readthedocs/restapi/views/core_views.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/restapi/views/model_views.py
- readthedocs/restapi/views/search_views.py
- readthedocs/restapi/views/task_views.py
Allow jsonp on the footer views, but remove it & browsable API from everywhere else, since we aren't using them.
> Remove jsonp and browsable api renderers

- readthedocs/projects/tasks.py
There was a silly bug that was checking for YAML config prior to code checkout.
This worked when there was already a cached checkout on disk,
but obviously doesn't respect the config on a fresh build
> Move config check until after checkout.

- docs/faq.rst
Added to FAQ about the C modules the need to remove the C-dependent libraries from setup so that the project can be properly installed in the RTD.
> Updated documentation with respect to the issue #1908

- docs/webhooks.rst
If case-sensitivity is not observed when entering the URL during the setup of your RTD project, then the project will appear to work correctly, however automatic updates on GitHub changes will not work correctly.
> URLs in ReadTheDocs are case-sensitive

- readthedocs/doc_builder/environments.py
Was causing some build failures on the linting step. This is one easy way to fix it. This assumes the comparison to `True` as opposed to using `__nonzero__` is important.
> STY: Fix PEP8 - E712 linting error (fixes tests)

- readthedocs/doc_builder/environments.py
This change supports a specific version for the Docker API I don't feel like
researching at the moment.
> Support >1.5 API change to volumes

- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_doc_building.py
This adds:
* A Local environment for checkout & config reading (Host)
* A Build environment for pip/conda & doc building (Docker)
* Refactors how we pass Bash environments around 
* Cleans up the python environment to use internal state
> Do a small builder refactor.

- readthedocs/core/utils/__init__.py
- readthedocs/doc_builder/environments.py
- readthedocs/projects/migrations/0013_add-container-limits.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
This allows for setting different limits on projects in docker containers, as
well as project level build queues for future use.
> Add project level settings for containers and queues

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/templates/sphinx/conf.py.conf
This was done to make it easier to support random projects with MD files being built on RTD.
This isn't a good priority,
and should only be included in the conf.py file we generate for those projects,
not the build file for all projects.
> Remove our injection of recommonmark into builds.

- readthedocs/core/middleware.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/settings/base.py
This will vastly reduce the number of sessions we have to store.
> Disable session creation on footer views.

- readthedocs/doc_builder/python_environments.py
> Use environment file for initial conda env creation.

- readthedocs/doc_builder/python_environments.py
Remove the `==1.0.1` version constraint when installing mock through conda.
Only newer versions of mock have been compiled with Python 3.5 (see issue #1962).
> Remove 1.0.1 version requirement for mock from the conda install.

- readthedocs/core/views.py
- readthedocs/oauth/models.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
This allows us to catch capitalization differences in what the post-commit hook is sending, and what the user entered as the repo URL.
> Use iendswith for repo lookups on hooks

- docs/yaml-config.rst
- readthedocs/doc_builder/config.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
- requirements/pip.txt
This allows folks to configure which formats get built.
We currently force `json` and `html` builders,
as we use these for search & web serving respectively.
> Add support for `formats` in the YAML config.

- docs/development/buildenvironments.rst
Found a spelling mistake - `alloted` > `allotted`
> Typo fix in docs

- docs/custom_installs/local_rtd_vm.rst
This is correctly present in the developer installation instructions.
> Add missing createsuperuser in local VM instructions

- readthedocs/core/urls.py
Hi,
It's a small detail, but I came across a misspelled variable name (user_buils_fallback) in the urls.py file and I thought it would be worth fixing before it became a problem for someone else.
> Fixed typo in fallbacks url

- readthedocs/doc_builder/python_environments.py
This refs #1843, where the setuptools version is not handling `setup.cfg`
options gracefully.
I don't believe this should cause any problems, but haven't tested this
thoroughly yet.
> Bump setuptools to latest

- readthedocs/doc_builder/backends/mkdocs.py
* Fix for https://github.com/rtfd/readthedocs.org/issues/2015
* Changes `'version': self.version.verbose_name`, to `'version': self.version.slug,` in `readthedocs/doc_builder/backends/mkdocs.py`
> #2015 Fix ReadTheDocs footer not loading for mkdocs

- docs/install.rst
This commit aims to solve the problems encountered in issue #1867 revolving around frustrations with getting an on-premises server started and working.
I've done the following:
* cleaned up the "step flow"...This now reads a lot more sane
* added the step around `collectstatic` to ensure static assets are copied
* inserted stanza warning about port assignment for builds to work successfully.
> cleanup, add collectstatic, and blurb about builds

- readthedocs/doc_builder/python_environments.py
Notably this adds support for the async / await syntax in Python 3.5+.
Fix #1865.
> Bump Pygments versions.

- gulpfile.js
- readthedocs/projects/forms.py
- readthedocs/projects/migrations/0014_add_project_allow_promos.py
- readthedocs/projects/models.py
- readthedocs/projects/static-src/projects/css/admin.less
- readthedocs/projects/static/projects/css/admin.css
- readthedocs/projects/urls/private.py
- readthedocs/projects/views/private.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/templates/projects/project_advertising.html
- readthedocs/templates/projects/project_edit_base.html
This adds a per-project advertising opt-out form, with some guidance on supporting
Read the Docs if you oppose advertising. It links to several pages explaining more
about the advertising spot, how to opt-out of ads, and a backup option to just
remove ads altogether if you don't want to support the project.
> Add a per-project advertising opt-out, and form page for preference

- docs/yaml-config.rst
- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/python_environments.py
Allows users to specify that `pip install .` should be used instead of `setup.py install`.
closes #2011
Feel free to close if this should be moved to the new readthedocs-build.
> Add python.pip_install option

- readthedocs/core/middleware.py
- readthedocs/rtd_tests/tests/test_domains.py
We were previously automatically creating Domain objects when you pointed a domain at us.
This was a backwards compat feature to catch domains that were configured using the old DNS method.
We have had this long enough to catch any major user,
so we should remove this and only have them be explicitly created.
> Remove domain autocreation.

- docs/versions.rst
> Fix minor grammar problem

- readthedocs/search/lib.py
This uses an annoying pattern because the project relationship manager doesn't know about privacy levels. We should look into cascading the managers onto querysets as with https://docs.djangoproject.com/en/1.9/topics/db/managers/#create-manager-with-queryset-methods
> Add proper privacy filtering to subproject queries

- docs/webhooks.rst
Bitbucket split its "Hooks" page into two pages -- "Services" and "WebHooks".  The former appears to be where one finds ReadTheDocs.
> Update Bitbucket integration instructions

- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/utils.py
- readthedocs/projects/signals.py
- readthedocs/projects/views/private.py
This fixes an error where we would say it failed
when the web hook was already set (status 200).
Also passes the response along to the attach_webhook caller,
so it can be smarter about error messages/logic.
> Refactor GitHub web hook logic.

- readthedocs/privacy/backend.py
- readthedocs/rtd_tests/tests/test_privacy.py
This allows them to be chained,
vastly simplifying out query structure in many places
> Build out proper querysets for managers.

- docs/faq.rst
Before, the example used `os.environ.get('READTHEDOCS', None)`, but this
is equivalent to `os.environ.get('READTHEDOCS')`.
> Removes redundant example code and adds text roles

- readthedocs/donate/__init__.py
- readthedocs/donate/apps.py
- readthedocs/donate/signals.py
- readthedocs/donate/tests.py
- readthedocs/gold/apps.py
- readthedocs/restapi/signals.py
- readthedocs/restapi/views/footer_views.py
With the new signal, we can move the messy logic around Promo insertion into a signal handler. This keeps the footer views nicely container, and allows us to hook into the footer in other places if we want.
Also added a few tests to make sure the logic is correct.
> Add a signal in the footer that gets info about footer response.

- readthedocs/donate/admin.py
- readthedocs/donate/migrations/0004_rebase-impressions-on-base.py
- readthedocs/donate/models.py
- readthedocs/donate/signals.py
- readthedocs/donate/tests.py
- readthedocs/donate/views.py
- readthedocs/projects/admin.py
This allows us to keep track of independent attrs on impressions.
This initially tracks impresisons per-project,
as well as per-promo.
> Break Impression modeling up into seperate models

- docs/theme.rst
It seems RTD has fixed this, my `conf.py` imports `sphinx_rtd_theme` unconditionally and [it works fine](http://hypernode-docs.readthedocs.org/en/latest/).
> Remove obsolete instructions for sphinx_rtd_theme

- docs/webhooks.rst
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
We didn't have these before. Fixes #2090 
This also cleans up the use of fixture data in these tests, instead of relying on a fixture.
> Add basic tests for BitBucket

- readthedocs/core/views.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
We were failing to build the repo when a user has `git@github.com:user/repo` as the repo, but we’re matching against `github.com/user/repo` in the post-commit hook. This fixes to the webhook to support both SSH & HTTP style URL's.
> Fix post-commit hook not working for private repos

- readthedocs/core/symlink.py
- readthedocs/privacy/backend.py
- readthedocs/privacy/loader.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
This builds out a separate `private_*` symlink structure for all private projects. This runs both Public & Private symlinks for each project, as it might have versions that have both privacy levels.
> Add private symlink structure.

- readthedocs/core/admin.py
- readthedocs/core/forms.py
- readthedocs/core/tasks.py
- readthedocs/core/utils/__init__.py
- readthedocs/core/views.py
- readthedocs/templates/core/email/common.html
- readthedocs/templates/core/email/common.txt
- readthedocs/templates/core/send_email_form.html
This adds a generic option for sending emails to users. The form view will
accept a queryset returning users and will display an email form asking for
subject and body input. Currently, nothing is templated, it is only passed in to
the base email template as a string.
This also breaks out sending email into a task, as more than a 100 outbound
emails could timeout the send request.
Note: this is a hotfix PR into `rel` and will require manual merge back into `master` as well.
> Add admin action for sending user emails

- readthedocs/templates/core/project_detail_right.html
This is old and misleading.
Folks should generally just be using the GitHub & BitBucket hooks.
> Remove the Post Commit Hook bit on project detail.

- readthedocs/core/utils/__init__.py
I don't believe there was a good reason for using `request.get_host`. This drops
that for `PRODUCTION_DOMAIN` settings, forcing https as well.
> Reference PRODUCTION_DOMAIN for uri passed to email templates

- readthedocs/core/utils/__init__.py
- readthedocs/projects/migrations/0016_build-queue-name.py
We shouldn't be as clever about build queue names. I got tripped up wondering
why builds weren't triggering on the build queue I specified. This migrates
projects to drop the build- prefix, updating projects that expect an implied
prefix.
> Drop implied prefix on project build queue name

- requirements/pip.txt
I'm seeing some problems with pip 8.0.2 where pip explodes spectacularly with nested requirements.txt files. Pip complains that there is a double definition of a requirement:
```
Double requirement given: coverage==3.7.1 (from -r requirements/tests.txt (line 4)) (already in coverage==3.7.1 (from -r requirements/tests.txt (line 4)), name='coverage')
```
This is fixed in later versions of Pip. Thus, I'm proposing this pull request to update pip and the related virtualenv requirements.
Substantially similar to #1979.
> Update pip and venv

- readthedocs/redirects/models.py
- readthedocs/rtd_tests/tests/test_redirects.py
We recently switched from a Sphinx HTMLDir-style layout to Sphinx HTML. The redirect we have in place handles links of the form http://clearwater.readthedocs.io/en/stable/Clearwater_SNMP_Statistics/, but not http://clearwater.readthedocs.io/en/stable/Clearwater_SNMP_Statistics/index.html (which used to work, and we have a lot of now-broken links in that format).
This PR makes the latter style of link redirect correctly. I was worried that it would affect links like http://clearwater.readthedocs.io/en/stable/index.html (redirecting to http://clearwater.readthedocs.io/en/stable.html), but I checked and get_redirect_response is only called from the 404 handler at https://github.com/rtfd/readthedocs.org/blob/a3e5cf3134c5db089d30451fdd89f77a2ad354a1/readthedocs/core/views/__init__.py#L123, so …
> Redirect .../index.html links from Sphinx HTMLDir

- requirements/pip.txt
Inclusion broke install on Windows 10. Tested after removal.
> Mercurial no longer needed

- prospector.yml
- readthedocs/api/utils.py
- readthedocs/core/forms.py
- readthedocs/core/management/commands/archive.py
- readthedocs/core/management/commands/clean_builds.py
- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/core/management/commands/sync_builds.py
- readthedocs/core/management/commands/update_api.py
- readthedocs/core/management/commands/update_repos.py
- readthedocs/core/management/commands/update_versions.py
- readthedocs/core/middleware.py
- readthedocs/core/mixins.py
- readthedocs/core/models.py
- readthedocs/core/symlink.py
- readthedocs/core/templatetags/core_tags.py
- readthedocs/core/utils/__init__.py
- readthedocs/core/utils/tasks/public.py
- readthedocs/core/utils/tasks/retrieve.py
- readthedocs/core/views/__init__.py
- readthedocs/core/views/hooks.py
- readthedocs/core/views/serve.py
Improves #1474 for all files in core/
> pep257ifys core and api

- readthedocs/core/views/serve.py
- readthedocs/rtd_tests/tests/test_subprojects.py
This allows URL's in Python to use aliases for subprojects properly
> Fix subproject slug lookup with alias.

- readthedocs/projects/tasks.py
This lead to the `Text File Busy` errors,
because we were trying to create the virtualenv while another process was running.
Instead of this throwing a "version locked" error and retrying,
it was just failing because it was never checking for a lock properly.
Fixes #2229
> This fixes a bug where we weren't locking the Python env.

- requirements/pip.txt
Currently, /api/v1/file/search/ is not working because
of https://github.com/django-haystack/django-haystack/issues/908
See https://github.com/rtfd/readthedocs.org/issues/2264 for a
complaint about the broken endpoint.
The problem has already been fixed in https://github.com/django-haystack/django-haystack/commit/49564861e432ec3c4b8d13d3d4ce8eda763d1308
I have just upgraded django-haystack and django-tastypie
dependencies to fix the problem.
> Fix AttributeError error at /api/v1/file/search/

- readthedocs/api/client.py
- readthedocs/restapi/client.py
This also cleans up the api v1 client to match the implementation by api v2.
A session is added to the Slumber API to handle an explicit hostname on the
request. This is useful for local development and staging, where the API
host name might not match the host name the web server or application instance
is designated to listen for. For example, when requests for API should go to
http://localhost, but the application expects http://readthedocs.org
> Add session configuration to API clients

- readthedocs/doc_builder/python_environments.py
Currently, when building the virtualenv base for a project, virtualenv
will always try to download the latest packages (pip, setuptools..),
this may cause problem if the building requires a specific version of
package like pip==8.1.1, and the installed version may be > 8.1.1.
This patch adds an option --no-download in the virtualenv base build
command.
> Don't download when building the base virtualenv

- readthedocs/bookmarks/urls.py
- readthedocs/builds/urls.py
- readthedocs/comments/urls.py
- readthedocs/core/urls/__init__.py
- readthedocs/core/urls/single_version.py
- readthedocs/donate/urls.py
- readthedocs/gold/urls.py
- readthedocs/profiles/urls/private.py
- readthedocs/profiles/urls/public.py
- readthedocs/projects/urls/private.py
- readthedocs/projects/urls/public.py
- readthedocs/restapi/urls.py
- readthedocs/urls.py
* patterns() has been deprecated
* Passing 'path.to.view.function' to url() has also
been deprecated
> Remove deprecated usages of URL features

- readthedocs/core/utils/__init__.py
- readthedocs/rtd_tests/tests/test_core_utils.py
- requirements/pip.txt
Also, this bumps celery to latest in 3.1 series. No dependency there though.
Fixes #2299
> Make update_docs task timeout a bit greater than the container build time

- readthedocs/builds/signals.py
- readthedocs/projects/tasks.py
This will be used to accumulate stats on finished build state. There is already
a projects.signals.after_build, but I'm not 100% it isn't being used, and passing
the version, as the signal expects, doesn't make sense if we are inspecting builds
> Add build complete signal

- readthedocs/projects/admin.py
- readthedocs/projects/forms.py
- readthedocs/projects/migrations/0017_add_domain_https.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_domains.py
This is an admin only option to designate a domain that has a custom SSL
certificate installed on the production stack.
> Add field for domain https

- readthedocs/projects/views/mixins.py
- readthedocs/rtd_tests/tests/test_project_views.py
As we overhaul the project admin dashboard, a good amount of code can be cleaned
up by using a CBV rather than repeating the view code like is currently used. I
had a need for this outside this code base, but implemented it here instead.
Views would look like:
class DomainMixin(ProjectRelationMixin):
model = Domain
lookup_url_kwarg = 'pk'
class ListDomainView(DomainMixin, ListView):
pass
class DetailDomainView(DomainMixin, DetailView):
pass
Views would then have access to a `project` and `domains` in template context
data.
> Add a mixin class for dashboard views on models with project relations

- readthedocs/donate/templates/donate/list.html
- readthedocs/donate/templates/donate/progress.html
Currently we still have our old fundraiser on the donate page.
We should make this evergreen,
and allow folks to donate at any time.
> Update donate page with timeless info

- readthedocs/core/tasks.py
Email task needs a timeout, as there were some cases where celery caused the
task to hang.
> Add timeout to email task

- docs/yaml-config.rst
- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_config_wrapper.py
- requirements/pip.txt
Depends on: https://github.com/rtfd/readthedocs-build/pull/16.
Also closes #173.
> Add support for Pip's extra dependencies in YAML config.

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
This also adds the proper import failure to the exception that gets shown to the user.
This also removes the ``report_build_success``, which seems redundant and not necessary.
> Properly check for a cloning failure and report error.

- readthedocs/doc_builder/backends/mkdocs.py
RE: https://github.com/rtfd/readthedocs.org/commit/f81c62c2cbb42507330a66746da2b8f4df8cf4fd
>  Move readthedocs-doc-embed to static path for collection
>
> This also adds a symlink from the existing media path to the statically
> collected file to avoid breaking the existing rtd-sphinx-ext includes.
RE: #2369
> Fix 'readthedocs-embed.js'

- readthedocs/core/signals.py
- readthedocs/core/views/hooks.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/restapi/urls.py
- readthedocs/restapi/views/integrations.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
Fixes #2424
* Adds new API endpoint for webhook consumption
* Adds webhook signals for future use
* Cleans up old webhook implementations
* Fixes old Bitbucket webhook implementation
* Sets new webhooks to point to API endpoint
* Removes GitHub service creation by naming the webhook 'web' -- 'readthedocs' created
an RTD service on GitHub
* Updates Gitlab fixture data with example from API
* Drops `request.POST['payload']` from all old webhooks, not sure what it was
* Made tests actually send JSON to webhook views
> Refactor webhooks, add modern webhooks, and fix issues with Bitbucket

- readthedocs/core/adapters.py
- readthedocs/core/tasks.py
- readthedocs/notifications/storages.py
- readthedocs/settings/base.py
- readthedocs/templates/account/email/email_confirmation_message.html
- readthedocs/templates/account/email/email_confirmation_message.txt
- readthedocs/templates/account/email/email_confirmation_signup_message.html
- readthedocs/templates/account/email/email_confirmation_signup_message.txt
- readthedocs/templates/account/email/email_confirmation_subject.txt
- readthedocs/templates/account/email/password_key_reset_message.html
- readthedocs/templates/account/email/password_key_reset_message.txt
- readthedocs/templates/account/email/password_key_reset_subject.txt
This fixes a bug with the notification system on logged out users and overrides
the allauth email templates. The base emails are very generic, aren't themed like
the rest of our emails, and had very generic copy.
> Fix signup issues and brand allauth emails

- readthedocs/templates/projects/project_import.html
Allow for button centering and separation
Before
After
> Fix template structure around import page

- docs/yaml-config.rst
- requirements/pip.txt
> Document support of .readthedocs.yml

- docs/yaml-config.rst
Surround ".readthedocs.yml" with double backticks, to show leading dot.  Same for the original filename.
> Amend #2442

- readthedocs/notifications/backends.py
- readthedocs/rtd_tests/tests/test_notifications.py
It would help if the notification went to the correct user.
> Fix bug with on site notification

- readthedocs/core/management/commands/import_github_language.py
- readthedocs/donate/migrations/0008_add-programming-language-filter.py
- readthedocs/donate/models.py
- readthedocs/donate/signals.py
- readthedocs/donate/tests.py
This builds a basic management command that will set
a projects language to the most used one in GitHub.
I'm guessing this will need a bit more expansion into a similar model as the Country stuff. Currently we just have a binary y/n -- but I think folks in the future will want to do "Show this to Python, This to JS, and this to everyone else" which isn't currently well supported here.
> Import a project's programming language from GitHub.

- requirements/pip.txt
The new 1.0 series is incompatible, and I've opened #2498 for this purpose.
Meanwhile, as the current master is broken because of this, the version should be pinned - I guess it's sort of bad practice to use the `master` branch anyways, am thinking it's possibly also an outdated decision now.
This fixes #2495 and #2490
> Pin django-filter

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
If a filename is `something_index.html`, `resolve_path` was stripping out the
`index.html` due to an incorrect substring lookup. Instead, look for either a
URL path separator or a beginning of line.
> Fix bug with path resolution

- readthedocs/vcs_support/backends/git.py
> Add more details to git clone errors

- readthedocs/core/utils/__init__.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_core_utils.py
This adds a function that wraps the django core `slugify`, replacing multiple
non-alpha characters with `-`.
> Add slugify fork that allows for dns safe slugging

- .gitmodules
The submodule `docs/_themes/sphinx_rtd_theme` appears to be unused. I spent quite a bit of time trying to test a fix for the sphinx_rtd_theme (snide/sphinx_rtd_theme#342) only to find out the submodule was a red herring, so I'd like to see it removed to prevent any future confusion.
```
The submodule was only relevant for a short time and its continued
existance is a distraction for new contributors.
See: snide/sphinx_rtd_theme#342
Using git-blame, I was able to pinpoint which commit introduced the
submodule, but I wanted to be certain that it was no longer in use. So, I
manually inspected parts of the source code, ran `git grep ...`,
reviewed open and closed issues, and PRs, but found nothing conclusive
about its existence. Ultimately, git-log is what gave me the most
confidence that it …
```
> Remove submodule docs/_themes/sphinx_rtd_theme

- readthedocs/doc_builder/backends/sphinx.py
In a previous commit, an __init__ method was added to HtmlBuilder and to
HtmlDirBuilder, however the SingleHtmlBuilder was unmodified. Since
SingleHtmlBuilder inherits from HtmlBuilder, HtmlBuilder.init is
executed which sets the instance variable "sphinx_builder" to either
"readthedocs" or "readthedocs-comments".
This instance variable from HtmlBuilder makes it impossible to get the
correct value from SingleHtmlBuilder's class variable "shpinx_builder"
"readthedocssinglehtml".
The fix is to implement the __init__ method for SingleHtmlBuilder and
set self.sphinx_builder accurately.
> SingleHtmlBuilder; impl __init__ to fix singlehtml

- readthedocs/builds/filters.py
- readthedocs/projects/filters.py
- readthedocs/templates/builds/build_list.html
- readthedocs/templates/core/build_list_detailed.html
- readthedocs/templates/core/filter_list.html
- readthedocs/templates/core/project_details.html
- readthedocs/templates/core/version_list.html
- readthedocs/templates/filter.html
- readthedocs/templates/projects/project_dashboard_base.html
- readthedocs/templates/projects/project_version_list.html
- requirements/pip.txt
Hi all, this should (hopefully) resolve all of the django-filter issues, migrating you to the upcoming 1.0 release. 
should fix #2490, fix #2495, fix #2498, supersede/resolve #2499
> Upgrade django filter

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Use `version.get_absolute_url` instead of constructing a relative URL.
I traced the code back to `readthedocs.core.resolver` (https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/resolver.py#L132-L145), as I understand it, using `get_absolute_path` should work fine in all cases (`readthedocs.org/docs/<project>/<lang>/<version>/`, or `<project>.readthedocs.io/<lang>/<version>`, or `<project_domain>/<lang>/<version>/`, but I'll defer to the experts (and CI unit tests).
```
Replaced the relative URL construction for document versions with
`version.get_absolute_url`.
```
> conf.py.tmpl; Use absolute URL for doc versions

- readthedocs/notifications/backends.py
- readthedocs/notifications/storages.py
- readthedocs/rtd_tests/tests/test_notifications.py
Instead of using the messages.add method directly, add message for the
message notification backend using the storage adapter directly. This also
removes the limitation on the storage backend that requires a request.user
is authenticated, as we are likely going to be mostly adding messages
through celery or other request-less mechanisms.
> Alter usage of message extends

- readthedocs/projects/migrations/0018_fix-translation-model.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_project.py
Deletes here shouldn't cascade to the child translation project.
> Stop cascading delete on translation deletion

- docs/builds.rst
These might come in handy, and since people are relying on them already
it's well worth documenting them.
> Document the environment variables set during builds

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/environments.py
- readthedocs/rtd_tests/mocks/mock_api.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_doc_building.py
This change ensures that the build status is always set to FINISHED even in the event that an unexpected exception is encountered during the build (this could be something like `yaml.safe_load` encountering an invalid YAML file).
This change also ensures that `update_build` is never called from a BuildEnvironment, and is instead only invoked from the task.
> Update build status even on exception

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This reverts commit 95bc81d2fa4c92279ab2ca6f795124d9689f1dab.
This commit introduced a bug with our builders, as the builders do not have
access to our database. The methods used in this commit rely on the database,
and must be added to the api return instead.
This was added with #2536
> Revert "conf.py.tmpl; Use absolute URL for doc versions"

- readthedocs/builds/models.py
- readthedocs/projects/version_handling.py
- readthedocs/rtd_tests/tests/test_version_commit_name.py
This fixes rendering of /projects/$proj/versions/ when a branch name contains a character which cannot be expressed in ascii.
The test here is very low-level compared the primary symptom; should I be adding something higher level as well?
> Let identifier_friendly cope with unicode in identifiers

- docs/dmca/index.rst
- docs/index.rst
This is an explicit procedure for handling takedown requests. This idea is
modeled after GitHub's procedure:
* https://github.com/github/dmca
* https://help.github.com/articles/dmca-takedown-policy/
> Add doc on DMCA takedown process

- docs/webhooks.rst
While configuring the GitHub integration, I found that the docs were slightly misleading as they didn't match the user interface presented by GitHub. These two minor changes correct that condition.
> Update GitHub integration docs to match experience.

- readthedocs/builds/models.py
re_sha is only used once so the overhead of calling
re.compile() implicitly is minimal which means we
can simplify the code by using re.match() instead.
> Use re.match() to simplify Version.identifier_friendly

- readthedocs/builds/models.py
- readthedocs/core/symlink.py
- readthedocs/core/utils/extend.py
- readthedocs/privacy/backend.py
- readthedocs/privacy/loader.py
- readthedocs/rtd_tests/tests/test_extend.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
This allows for override of the symlinking classes, as we need to be able to
override how public and private symlinks are determined. Test coverage is expanded greatly on symlinking here:
* Dropped pattern of testing for command execution and singular symlinks for testing filesystem snapshot
* Symlinks are built under isolated tempdirs now
* All testcases test public/private privacy
* Privacy level on project/versions is explicit now
Our extension pattern was tuned up and simplified here, the django lazy object didn't allow for passing of classmethods.
This also moves the Version manager into a Version queryset + manager pattern, as we need to be able to chain queries from the managers, which isn't possible without a queryset object. This is a pattern we should adopt on the remaining …
> Changes and fixes to symlinking and serving

- readthedocs/doc_builder/backends/sphinx.py
This was causing users with invalid conf.py file settings
to get an "unknown error" message.
This was the traceback that was fixed:
```
Feb  7 20:55:41 build01 readthedocs/readthedocs.doc_builder.environments[32422]: ERROR (Build) [flowframework:latest] Conf File Missing. Please make sure you have a conf.py in your project. [readthedocs.doc_builder.environments:306]
File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 170, in run
outcomes = self.build_docs()
File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 331, in build_docs
outcomes['html'] = self.build_docs_html()
File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 348, in build_docs_html
html_builder.append_conf() …
```
> Fix issue where we can't find conf.py and raise bad error.

- readthedocs/builds/views.py
- readthedocs/templates/builds/build_list.html
- readthedocs/templates/core/build_list_detailed.html
A change in the Django Filter project made it so the previous method didn't work.
We aren't currently using the filters,
so we should probably remove them for simplicity,
but this fixes the main issue.
> Fix pagination of Builds on build list page.

- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/constants.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_config_wrapper.py
- readthedocs/settings/base.py
- requirements/pip.txt
* Pass in build env python limitations to config
* Exposes parsing error to user on build output
Requires rtfd/readthedocs-build#21
> Pass build env python limits to config object

- docs/yaml-config.rst
- readthedocs/settings/base.py
Adds info for new build images.
> Update docs on python version

- docs/install.rst
Points the `dashboard` link to the just installed readthedocs instance instead of going to the production URL (readthedocs.org/dashboard)
> Link to the localhost instance of the dashboard

- readthedocs/doc_builder/python_environments.py
- requirements/pip.txt
I did some basic builds locally that looked and worked fine,
and we have a lot of users using 1.5 in requirements files.
We don't have a great way to stress test this,
but I think we should definitely push it out as a default.
I didn't touch the conda defaults because it doesn't update as quickly as pypi.
> Upgrade Sphinx version and theme.

- readthedocs/doc_builder/python_environments.py
This change aligns the required `setuptools` to the version already available on the system. This avoid unnecessary downgrades of `setuptools` during environment setup.
Here is a real-life example of a downgrade on one of my project: https://readthedocs.org/projects/meta-package-manager/builds/5079681/
Also note that the build above is failing because of the presence of a marker specifying the Python version compatibility: https://github.com/kdeldycke/meta-package-manager/blob/1863a4457892a052aa53c1e2a2ae08bf3f7814c4/setup.py#L48 . This additional fragment is not recognized by the old `setuptools` 20.1.1 while the proposed 28.8.0 is going to fix this issue as well.
> Update setuptools version.

- readthedocs/doc_builder/python_environments.py
- requirements/pip.txt
> Also upgrade recommonmark to get autostructify transform

- package.json
Looks like the repo moved from https://github.com/phestermcs/vinyl-source-stream to https://github.com/hughsk/vinyl-source-stream
Fixes #2687
> Fix github link for vinyl-source-stream

- docs/install.rst
Closes #2281 
Related to #1060 
* added a note regarding `elasticsearch` installation for full search support
* added a note to mention about how to install `postgresql` and `redis`.
* removed two extra whitespaces
* move homebrew link together with the others
Let me know what else is missing here of if you want to write this in another way :)
> Install docs improved

- readthedocs/donate/admin.py
- readthedocs/donate/forms.py
- readthedocs/donate/models.py
- readthedocs/donate/templates/donate/ethicalads-success.html
- readthedocs/donate/templates/donate/ethicalads.html
- readthedocs/donate/templates/donate/promo_detail.html
- readthedocs/donate/urls.py
- readthedocs/donate/views.py
This also adds the ability to see reports on specific promos.
Also gives a place to see how they display and test them before shipping them live.
> Add a way for sponsors to pay without asking for logos etc.

- readthedocs/doc_builder/backends/mkdocs.py
- Fix for #1917
- Test locally following the directions here http://docs.readthedocs.org/en/latest/install.html#installing-read-the-docs
- Not sure where / if to add a unit test for this change
> (#1917) Fixing Flyout Links for MkDocs Projects

- readthedocs/projects/tasks.py
When the celery soft_time_limit is reached the celery exception is catched and the build is reported as failed to be shown as an error message to the user.
This bug was found when looking at #2697
> Handle celery.exceptions.SoftTimeLimitExceeded

- LICENSE.mit
- docs/alternate_domains.rst
- docs/api.rst
- docs/builds.rst
- docs/conf.py
- docs/contribute.rst
- docs/faq.rst
Lots of little updates that fix various doc bugs we had outstanding.
> A few doc updates to address bugs

- readthedocs/doc_builder/backends/sphinx.py
Instead of showing just "cat conf.py" now we show "cat docs/conf.py" as a relative path starting from the checkout path (repository directory).
Refs #2735
> Show the relative path of conf.py file used

- media/javascript/rtd.js
- readthedocs/core/resolver.py
- readthedocs/core/signals.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/projects/version_handling.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_sync_versions.py
- readthedocs/search/utils.py
Fix errors caused by calling `dict` on a Response.
This errors in all the cases I tested (202, 400), so I'm not sure what the
original intent was. This gives users 500's on project import if GH import
fails, so probably a pretty high priority to fix.
--
Fix CORS requests not having ORIGIN
--
Fix unicode handling in resolver
We should probably upgrade to Python 3 to remove all these issues, but this
at least will fix this one.
--
Validate the JSON file we're trying to load works.
This fixes errors on search indexing of files that don't fit the format.
This was triggering on eg. `searchindex.json` in the JSON builders
--
Remove the call to our API from old projects.
This stops a large number of requests from old pages. It depends on v1 of
our API and it broken.
> This merges all the bugfix PR's I had into one.

- readthedocs/core/symlink.py
- readthedocs/core/utils/__init__.py
I wonder if this is something we should have locking around?
I think we're hitting a case where multiple builds or celery runs on the webs
are causing a race condition in the symlinking code.
I'm guessing we'll still be hitting issues until we build locking code around this,
because it's pretty stateful. This is not a great fix, but at least stops the builds failing in these cases, I believe.
> Fix symlinking race condition

- readthedocs/projects/tasks.py
Don't raise OSError on errors -- this happens when we try and delete files/dirs that don't exist.
> Another bundle of Sentry bugfixes

- readthedocs/doc_builder/python_environments.py
> Allow pillow to float version in conda builds

- prospector-more.yml
- prospector.yml
- readthedocs/constants.py
- readthedocs/integrations/models.py
- readthedocs/wsgi.py
- tox.ini
This increases prospector base profile to medium strictness, enables pep257,
and adds some additional pylint rules to filter out docstring related failures.
This limits docstrings to methods/classes less than 10 lines, which should be
readable already. Docstrings wouldn't hurt in this case of course, but we won't
require them on everything.
> Example of increased strictness on linting

- readthedocs/privacy/backends/syncers.py
- readthedocs/profiles/views.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/private.py
> Docstring/PEP 257 fixes for the P* apps

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/base.py
- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/constants.py
- readthedocs/doc_builder/environments.py
> Docstring/PEP 257 fixes for the docs_builder app

- deploy/flask-redirects.py
- readthedocs/bookmarks/admin.py
- readthedocs/bookmarks/views.py
- readthedocs/oauth/services/base.py
- readthedocs/privacy/backend.py
- readthedocs/redirects/models.py
- readthedocs/rtd_tests/base.py
- readthedocs/rtd_tests/mocks/environment.py
- readthedocs/rtd_tests/mocks/paths.py
- readthedocs/search/views.py
- readthedocs/vcs_support/utils.py
A bit more of #1474.
After this, there are only a few left – at which point we’ll be able to close that issue, and turn on linting for new patches.
> Assorted docstring/PEP 257 fixes

- readthedocs/doc_builder/python_environments.py
Addresses #2708 by using a version of our extension that supports more than one
version of Sphinx.
Refs #1895
Refs #1850
Refs #2755
> Bump readthedocs-sphinx-ext to 0.5.5 to resolve search issues

- prospector-more.yml
These removed lines are either for directories which no longer exist in the codebase, or which don't contain python files.
> reduce ignore-paths in prospector config

- docs/install.rst
Add a warning to install.rst that installation currently requires Python 2.7 and not Python 3.
> Add warning to use Python 2.7 in install docs (closes #2865)

- prospector-more.yml
- readthedocs/oauth/admin.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/utils.py
Mostly style fixes and added comments.
One fix is a functional bugfix, to correctly fall back to resp.content if resp.json() raise a ValueError.
> Fix lint errors for oauth app

- readthedocs/oauth/services/__init__.py
- readthedocs/privacy/loader.py
- readthedocs/projects/backends/views.py
> Replace extension pattern with updated version, resolves #2618

- prospector-more.yml
- readthedocs/rtd_tests/base.py
- readthedocs/rtd_tests/mocks/environment.py
- readthedocs/rtd_tests/mocks/mock_api.py
- readthedocs/rtd_tests/mocks/paths.py
- readthedocs/rtd_tests/utils.py
* Docstrings
* Lazy logging
* Unused variables
> Linting fixes for rtd_test module.

- prospector-more.yml
- readthedocs/notifications/__init__.py
- readthedocs/notifications/apps.py
- readthedocs/notifications/backends.py
- readthedocs/notifications/forms.py
- readthedocs/notifications/notification.py
- readthedocs/notifications/storages.py
- readthedocs/notifications/views.py
- readthedocs/rtd_tests/tests/test_notifications.py
* Add module docstrings.
* Rename `object` named arg to `context_object` in `Notification.__init__()` to avoid shadowing `object`
* Eliminate some unused imports
* add `__all__` in `__init__.py` to indicate imports are intended to be re-exposed
> Fix lint issues for notifications app

- docs/conda.rst
- readthedocs/doc_builder/python_environments.py
Do not pin required packages for Read The Docs but make sure they are installed once the environment is created using the `environment.yml` from the user's repository.
I tried building `poliastro` project (https://github.com/poliastro/poliastro) in my local instance and it worked. This project used python 3.6 which was incompatible with our old setup.
Related to #2566 #2584 #2589
> Removed pinned versions from conda environments

- readthedocs/projects/tasks.py
LockTimeout happens when there are more than one build trigger almost at the same time.
This is a fix "hotfix" for #1654.
By "hotfix" I mean that we should solve this problem in a different way at the end. Maybe by creating a RETRY status for this Build instance while they are waiting to be re-triggered and use the same context. Besides, this FAILED build shouldn't be shown to the user and they shouldn't keep registered in the user interface (history of buildings).
> Avoid user notifications when LockTimeout is received

- readthedocs/rtd_tests/base.py
- readthedocs/rtd_tests/tests/test_middleware.py
- readthedocs/settings/test.py
- requirements/pip.txt
- requirements/testing.txt
- tox.ini
Be ware that running tests in parallel may cause tests to flake. 
This commit does not make parallel test the default it only makes it possible.
usage
-----
tox -- -n 4
Benchmarking
------------
using the following command ( on my old laptop...)
`time tox -e py27 -- -n 6 --ignore=rtd_tests/tests/test_celery.py`
w/o xdist: 1 min 24 seconds
2 processes: 53 seconds
3 processes: 44 seconds
4 processes: 40 seconds
5 processes: 40 seconds (tests flake)
6 processes: 43 seconds (tests flake)
~ 2x speedup!
> make tests parallelizable (multi processing) using pytest-xdist

- readthedocs/settings/base.py
I'm removing this one since it's not used and makes confusion when trying to enable logging :)
> LOG_DEBUG setting is not used at all

- readthedocs/projects/views/private.py
This means a user can deactivate their stable version,
and we shouldn't keep trying to update it.
> Set machine to False when a user edits a version.

- readthedocs/core/views/hooks.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
For some reason, bitbucket is sending a webhook with incomplete
data ('commits' is the empty list), and we need it to process the
webhook.
This commit adds a new validation for the 'commits' data (branches
variable inside RTD) before start the building process.
https://sentry.io/read-the-docs/readthedocs-org/issues/235650096/
> Fixed issue with bitbucket webhook when it's not valid

- prospector-more.yml
- readthedocs/search/indexes.py
- readthedocs/search/lib.py
- readthedocs/search/parse_json.py
- readthedocs/search/signals.py
- readthedocs/search/utils.py
- readthedocs/search/views.py
Easiest to review changeset-by-changeset. This includes general docstrings, lazy logging, etc. but also refactors a few chunks of code to have fewer branches and locals.
> Fixup linting issues in the search module

- readthedocs/settings/base.py
- requirements/pip.txt
django-secure was merged into Django 1.8, and since rtd.org uses Django 1.9, migrating to using the built-in checks reduces the dependency list and avoids any problems between newer versions of Django and django-secure.
* https://github.com/carljm/django-secure
* https://docs.djangoproject.com/en/1.8/releases/1.8/#security-enhancements
---
I was looking at the list of dependencies in #2819, noticed that django-secure was a package listed as "not compatible", then went digging in its repo and discovered it was deprecated.
> Remove the dependency on django-secure

- prospector-more.yml
- readthedocs/restapi/client.py
- readthedocs/restapi/permissions.py
- readthedocs/restapi/serializers.py
- readthedocs/restapi/signals.py
- readthedocs/restapi/urls.py
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/core_views.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/restapi/views/integrations.py
- readthedocs/restapi/views/model_views.py
- readthedocs/restapi/views/search_views.py
- readthedocs/restapi/views/task_views.py
This cherry picks #2890 linting changes and leaves the refactoring. We can
address that as a separate piece of work, as it seems there might be some more
back and forth on that PR.
> Fix linting problems with restapi application

- readthedocs/core/utils/extend.py
- readthedocs/rtd_tests/tests/test_extend.py
Classmethods weren't resolving to the intended class correctly.
> Fix classmethod pass through on settings extend classes

- readthedocs/projects/views/public.py
using the never_cache decorator should set `Expires` to now
> fix for #1612

- tox.ini
This stops multiple envs from running on the py27/py36 test envs
> Remove extra envs from python version run with tox-travis

- readthedocs/projects/forms.py
- readthedocs/templates/core/project_bar.html
Clean up handling of translation syncing.
This makes sure we properly run all the post-save logic on the parent on translation,
also it adds a UI element to the page to show that subprojects are in fact, subprojects.
> Clean up handling of translation syncing.

- readthedocs/templates/core/email/base.html
Prior to this change when a user opens a RTD email the header may be very thin and then suddenly
expand as the image loads the email content lowers. This caused me to click the header instead of
the email confirmation link
> Add email header affordance

- readthedocs/doc_builder/python_environments.py
Addresses #2975 
Currently, `mkdocs` is not available in the default conda channel (anaconda). It is available in the `conda-forge` channel.
There are two possible ways to add `mkdocs` into the core conda build environment:
- `conda install -c conda-forge mkdocs` which if done I would recommend installing all the core conda packages from conda-forge
- Alternatively, install `mkdocs` into the core conda build environment using `pip`.
I've gone ahead and created a PR for the second approach since it does not add additional code just moves the `mkdocs` package from one list to another.
> Use pip to install mkdocs for base conda build env

- readthedocs/builds/syncers.py
- readthedocs/donate/signals.py
- readthedocs/projects/tasks.py
- requirements/pip.txt
A few changes that were caught on deploy.
> Deploy hotfixes

- readthedocs/doc_builder/backends/mkdocs.py
In the case of a unicode string without a unicode character, YAML adds a tag to
ensure the text is read as unicode, ie:
In [1]: import yaml
In [2]: yaml.dump(u'surprise!')
Out[2]: "!!python/unicode 'surprise!'\n"
This forces only literals are output to the YAML config, by using `safe_dump`
instead of `dump`
> Remove YAML unicode tags from Mkdocs config

- readthedocs/core/signals.py
- readthedocs/core/templatetags/core_tags.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/forms.py
- readthedocs/projects/migrations/0010_migrate_domain_data.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
- readthedocs/vcs_support/backends/bzr.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/backends/svn.py
Patching `sys.modules`, while clever, fucks with downstream libraries. I ran
into problems with `urllib` being patched to return bytes, where a middleware
was expecting `str`. Instead, we'll be less aggressive with patching here.
This also cleans up some import ordering -- my refactoring tooling automates
this.
> Remove future standard library monkey patching

- readthedocs/oauth/utils.py
This apparently changed at some point. This was triggered when no accounts were
connected and a project import was attempted. Webhook setup would try to emit a
warning message for the provider.
> Fix call to allauth adapter

- readthedocs/doc_builder/python_environments.py
This should address https://github.com/rtfd/readthedocs.org/issues/2975#issuecomment-311700338
@agjohnson - I'm not familiar with the mkdocs builds. Is ``sphinx`` and ``sphinx_rtd_theme`` required to be installed when the document type is mkdocs? If not, I can add a similar check for those dependencies.
> Install either mkdocs or sphinx depending on document type

- readthedocs/donate/models.py
- readthedocs/gold/templates/gold/projects.html
- readthedocs/gold/templates/gold/subscription_detail.html
- readthedocs/redirects/models.py
- readthedocs/templates/account/email/email_confirmation_message.html
- readthedocs/templates/account/email/email_confirmation_message.txt
- readthedocs/templates/account/email/password_reset_key_message.html
- readthedocs/templates/account/email/password_reset_key_message.txt
- readthedocs/templates/base.html
- readthedocs/templates/core/email/base.html
- readthedocs/templates/core/header.html
- readthedocs/templates/core/home-header.html
- readthedocs/templates/core/project_bar_base.html
- readthedocs/templates/core/project_details.html
- readthedocs/templates/error_header.html
- readthedocs/templates/notifications/send_notification_form.html
- readthedocs/templates/projects/project_dashboard_base.html
- readthedocs/templates/projects/project_import.html
I guess all of this goes towards #1455 but there's probably still a lot to be done.
Actually found this one while completing the French translation in Transifex :D
*EDIT* : added another commit for a translation specific problem. I'll probably fix the other things I see here (until someone does a review, at which point the PR will be frozen)
*EDIT again* : just so you know, I've finished translating all the French keys, so this PR should be final
*EDIT again again* : I removed `trans` and `blocktrans` tags around the project/brand name "Read the Docs", because my intimate guess is that there's no reason for this to have been translated in the first place. (Imagine people in an international conference trying to understand they're talking about the same service with different names). I …
> Many i18n improvements

- readthedocs/projects/views/public.py
Pass on the `maxAge` query parameter when redirecting to the badge image
from Shields.io. This should help with GitHub's unwanted badge caching.
The default is 1 day.
> Support badge `maxAge` (fix #3000 and #1612)

- .travis.yml
Travis CI has switched from Ubuntu Precise to Trusty as part of some environment changes: https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
This broke building RTD on Travis CI due to `bower` and `gulp` command-line commands not being available.
This PR adds them back and fixes #3019.
> Fix Travis CI build on Ubuntu Trusty

- readthedocs/restapi/templates/restapi/footer.html
When using a custom readthedocs server, the search box in the documentation footer link to readthedocs.org website instead of the production domain host.
Using ``settings.PRODUCTION_DOMAIN`` fix the problem.
> Remove hardcoded readthedocs.org URL

- readthedocs/core/symlink.py
- readthedocs/projects/utils.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
Previously, this was executing a command using a shell, but without properly
escaping the input. This instead passes a list in to Popen, to ensure escape is
working properly.
> Fix bug with symlink creation

- .gitignore
- readthedocs/templates/account/email/password_reset_key_message.html
- readthedocs/templates/account/email/password_reset_key_message.txt
TIL linebreaks will prevent `{% trans %}` tags from being parsed.
> Fix {% trans %} tags in password reset email. Fixes #3036.

- readthedocs/core/urls/subdomain.py
- readthedocs/urls.py
Django 1.10 doesn't like using patterns('', ...) and instead
wants the use of a list. It also no longer wants the string path
to a callable and instead wants the callable itself.
> Fixes py27 django 1.10 dep warnings in core subdomain urls.

- .gitattributes
Documenting desired line endings/will help prevent windows developers don't accidentally push code with windows line endings.
> Enforcing linux line endings

- docs/getting_started.rst
Default settings in conf.py has `make html` put the output into _build/html and https://github.com/github/gitignore/blob/master/Python.gitignore defaults to ignoring docs/_build/ so the `sphinx-autobuild` command example should output to the same ignored spot.
> Update Getting Started so autobuild matches manual build

- readthedocs/api/base.py
If a project contains a number in its slug (ex: e2e-tests), the API /api/v1/version/e2e-test/latest/build/ raises an exception.
The regular expression wasn't expecting any number for the project slug
> Fix version V1 api for projects with numbers

- docs/subprojects.rst
Clarify usage around subprojects, how they can be used, and other features.
> Add some docs on subprojects

- .gitattributes
The `.gitattributes` file from #3053 caused some issues on a clean clone of the repository for me. These issues involved modifying the line endings of binary files and manifested themselves in the form of binary files showing as modified in `git status` with warnings like:
warning: CRLF will be replaced by LF in deploy/wheels/Jinja2-2.7.1-py2-none-any.whl.
At first I was very confused as I would think CRLF endings were only for Windows users. However, I realized that binary files could contain CRLFs. When I looked at the `.gitattributes` file, it denotes everything as text with Unix line endings. Based on [github's useful docs on the subject](https://help.github.com/articles/dealing-with-line-endings/), I think that documenting binary files will clear this up.
**STEPS TO REPRODUCE**
For …
> Document binary files for no line ending changes

- requirements/pip.txt
[DefusedXML](https://pypi.python.org/pypi/defusedxml) is [required by tastypie](http://django-tastypie.readthedocs.io/en/v0.13.1/#format-support) to support XML serialization.
I believe fixing this will fix the Internal Server Error on https://readthedocs.org/api/v1/ (at least hitting that with the browser and no special headers) as it does for me locally.
> Add a tastypie XML requirement

- readthedocs/donate/views.py
Removes the 404s from double clicks and views. Instead, they will just redirect as they should although they will not count toward the ad stats.
Fixes #2799.
> Do not 404 on double clicks and views

- pytest.ini
- readthedocs/donate/tests.py
The goal of this PR is to make the tests run and pass. These can be run as follows:
python manage.py test readthedocs.donate --settings=readthedocs.settings.test
It doesn't look like these tests have been run in a while so perhaps a larger discussion is warranted around do we need these tests at all or should they live with the CI tests in `rtd_tests`.
Here are some specifics fixes:
- fixed import error
- removed the footer tests which seem invalid with the v2 api
- fixed method names and numbers of params type issues
- fixed a few tests logically
> Make manage.py test work for the donate app

- README.rst
This fixes a link in the README, and adds a period to conform to formatting elsewhere.
> docs(README.rst): Fix license link, add period

- readthedocs/settings/dev.py
Following #1415, remove this deprecated settings. That seems to have been wiped out by b1221a65770f1919ffff5cb02bd54f06e9c2b400 but turned up again.
It is unused in the project, so it seems safe to remove that.
> Remove unused NGINX_X_ACCEL_REDIRECT

- readthedocs/core/views/hooks.py
- readthedocs/templates/projects/integration_list.html
This PR corrects a typo (intergrations -> integrations) in UI text, as well as in documentation that refers to the name of Python classes.
I'm assuming the text in `readthedocs/locale/*/LC_MESSAGES/django.po` is automatically collected and updated. If not, this text needs to be updated as well.
> Typo: intergrations -> integrations

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/signals.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
For instances where we need to extend context data to templates, a signal and
extendable template works for now. Eventually, we'll want this to instead be a
single step, with more properly structured data for the context.
> Add additional signals around sphinx context data

- readthedocs/core/admin.py
- readthedocs/projects/admin.py
- readthedocs/projects/utils.py
- readthedocs/rtd_tests/tests/projects/test_admin_actions.py
This adds actions for:
* Mark project owner as banned
* Remove project and files on web server
Closes #2762
> Add some basic spam removal features to admin

- readthedocs/projects/tasks.py
- readthedocs/restapi/views/model_views.py
This updates the syncing tasks to execute in a guaranteed fashion. Before this
change, it was possible for broadcast tasks and symlink deletion tasks to
execute concurrently. This changes all the broadcast task calls into function
calls from a singular broadcast task.
In more detail:
* The `finish_build` task was executed as a task from the webs, and kicked off
broadcast tasks to update files. Instead, Version update operations were move
to the build process, through the API. The webs only the one broadcast task
* Version API was given the same APIRestrictedPermission as other end points, it
can now be updated by staff
> Refactor project documentation syncing tasks

- readthedocs/templates/base.html
If a user clicks on the GitHub link while resetting their password the password reset token is leaked in the Referer header.
> Add rel="noopener noreferrer" in order to prevent leaking the password reset token.

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
I use rope to automate import order cleanup, but keep forgetting to implement
this outside a feature branch.
> Fix import order on a few files in readthedocs.projects

- readthedocs/core/signals.py
- readthedocs/rtd_tests/tests/test_middleware.py
We weren't correctly setting CORS headers when querying the documentation search
API from a subproject on and parent project domain. In this case, we were
querying with a project lookup for the subproject, and no domain was assigned to
this project.
This alters the query to find a domain associated with either the project you
are querying, or the parent project of a project you are querying.
> Fix issue with CORS headers on subproject projects

- readthedocs/donate/templates/donate/list.html
This pull request updates the sustainability metrics to agree with:
- https://blog.readthedocs.com/read-the-docs-2016-stats/
- http://www.seethestats.com/site/readthedocs.org
There are a few metrics I couldn't easily ascertain such as how many servers exist and how many terabytes of docs are served.
> Update sustainability metrics

- readthedocs/core/forms.py
- readthedocs/profiles/urls/private.py
- readthedocs/profiles/views.py
- readthedocs/templates/profiles/base_profile_edit.html
- readthedocs/templates/profiles/private/delete_account.html
This will add an option in user settings to let them delete their own account. They need to type their username in the field to confirm the delete so that they do not do it mistakenly. Moroevoer, rather than completely removing the account, we can make the account as `is_active=False` so they can not login anymore.
@ericholscher @agjohnson r?
cc: @RichardLitt
> [Fix #3120] Enable users to delete their own account

- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/restapi/serializers.py
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/mocks/mock_api.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_config_wrapper.py
- readthedocs/settings/dev.py
- readthedocs/vcs_support/base.py
Forked from #3051
- Replace references to api_v1 in projects/tasks.py
- Replace `__unicode__` with `__str__` in comments.admin.py
- Remove mocks of `projects.tasks.api_v1`
> Remove apiv1 from our internal usage.

- readthedocs/templates/base.html
Link to the advertise with us page from the footer instead of the ethical ads page. This contains a hardcoded fallback link in case the page isn't available locally.
> Link to the advertising page from the footer

- docs/ethical-advertising.rst
- Copy updates
- Makes the form fields the same as on https://readthedocs.org/sustainability/advertising/
- Link back to the advertising page for marketers
**UPDATED SCREEN**
For comparison, the existing ethical ads page is [here](http://docs.readthedocs.io/en/latest/ethical-advertising.html).
> Copy and form updates to the ethical ads page

- readthedocs/builds/syncers.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/projects/test_admin_actions.py
- readthedocs/search/parse_json.py
- readthedocs/search/utils.py
- readthedocs/settings/base.py
- readthedocs/settings/dev.py
This is rebased on top of the existing search cleanup, since it was touching similar code.
> Do some initial file syncing error handling cleanup

- readthedocs/builds/models.py
- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/core/management/commands/set_metadata.py
- readthedocs/core/views/hooks.py
- readthedocs/doc_builder/environments.py
- readthedocs/oauth/services/github.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/projects/utils.py
- readthedocs/search/utils.py
- readthedocs/vcs_support/utils.py
This should reduce some noise, and clean up how we're calling logs.
> Clean up logging around exceptions

- docs/index.rst
This is to make architecture the top link after changelog
and installation instructions. Also moves API to the bottom,
because it stands out of the reading flow, which is:
- see if the development thing you think about is already done
- launch installation if you're going to fix anything
- (or) read about archtecture
- about testing, probably installation is ready
- how to sync docs
- standards, etc.
- components (should be linked from archtecture)
- everything else
- leave API pages open
> Rearrange development docs ToC

- docs/faq.rst
- readthedocs/__init__.py
- readthedocs/core/management/commands/update_api.py
- readthedocs/core/management/commands/update_repos.py
- readthedocs/core/management/commands/update_versions.py
- readthedocs/core/tasks.py
- readthedocs/core/utils/__init__.py
- readthedocs/core/utils/tasks/retrieve.py
- readthedocs/oauth/tasks.py
- readthedocs/projects/__init__.py
- readthedocs/projects/apps.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/projects/test_admin_actions.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_core_utils.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/settings/base.py
- readthedocs/worker.py
- requirements/pip.txt
* Use modern celery
* Drop djcelery
* New pattern for starting celery
* Bump redis to 2.10.6 to avoid startup bug, change autodiscover call
> Use new Celery, use new application pattern

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
- readthedocs/restapi/client.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/settings/base.py
- readthedocs/settings/dev.py
> Improve error reporting to users

- readthedocs/builds/views.py
- readthedocs/projects/views/public.py
- readthedocs/templates/builds/build_list.html
- readthedocs/templates/core/project_details.html
- readthedocs/templates/projects/onboard_detail.html
Avoid "This endpoint is deprecated" raised when hitting and old
endpoint with security issues.
Now, each view that shows a form with the "Build" button uses the
BuildTriggerMixin to handle the POST request and trigger the new build.
Closes #3253
> Use CSRF token on forms to trigger a new builds

- readthedocs/oauth/__init__.py
- readthedocs/oauth/apps.py
- readthedocs/oauth/tasks.py
- readthedocs/restapi/views/task_views.py
This was not caught on celery 4 upgrade
> Fix missing sync repo task

- readthedocs/doc_builder/python_environments.py
With PEP 517, projects may no longer even have one in the future.
> Allow installation of the project without a setup.py

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
* As per the sentry docs, metadata is passed in via extra['data'] argument to
log.* -- still unclear if this is searchable
* We weren't actually logging unhandled build exceptions on the build
environments
> More fixes for logging -> Sentry

- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
When the body is encoded, a mix of bytes and unicode happens and it
fails at this line
https://github.com/requests/requests-oauthlib/blob/c472e6bf0468f1bd52b70a64e9aac92bee41c491/requests_oauthlib/oauth2_session.py#L285
(Pdb) body
u'grant_type=refresh_token&allow_redirects=True&refresh_token=b%27z9BSRKqf2QD4pcDhqj%27&client_id=CLIENT_ID&client_secret=CLIENT_SECRET'
(note those weird `%27` in the string)
Closes #2993 
Closes #2992
> Do not convert to bytes the `refresh_token`

- .gitignore
- contrib/readme.rst
- contrib/supervisord.conf
Useful for running a development instance really quickly.
Doesn't yet support:
* ipdb/pdb, but still supports rdb
* color log output
> Add supervisord contrib example

- readthedocs/doc_builder/environments.py
Easy way to reproduce this error:
1. Import a project that compiles lxml (Read the Docs, for example)
2. The `pip` command will be killed and Docker won't return a specific
status code, it will just return 1
3. In these cases, the `Killed` word will probably appear in the last
15 lines
----
If I increase the DOCKER_LIMITS memory in my local instance I don't get this error.
> Extra way to check OOM of a command ran inside Docker

- .gitignore
- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
When an exception happens and it's handled by __exit__ our Build in
the database is not updated and it stay in 'Installing' forever. So,
when something bad happens we force a call to `update_build` with the
FINISHED state
Attempt to fix #3285
> Update build from database at __exit__

- readthedocs/core/views/__init__.py
https://docs.djangoproject.com/en/1.9/ref/views/#django.views.defaults.server_error
This bug was introduced at https://github.com/rtfd/readthedocs.org/commit/5e0f4c0d0796476c4da9aabffca1d57fea806f57#diff-f37089595920e35da08a9395c370515eR107
> Remove invalid attribute `exception`

- readthedocs/projects/models.py
Avoid downloading over and over again the pip packages when you are
developing over a slow internet connection.
> Add GLOBAL_PIP_CACHE setting

- readthedocs/projects/tasks.py
Use the `update_build` method that handles most of the cases but fill
the `failure` with a unhandled exception in case it was risen.
Related to #3292
> Update Build state at the end of UpdateDocsTask.run

- readthedocs/core/management/commands/update_repos.py
- readthedocs/projects/management/commands/import_project_from_live.py
* record the build
* exclude attributes from API response
* call UpdateDocsTask with `build_id` to avoid failing
> Minor improves to `import_project_from_live` management command

- readthedocs/doc_builder/environments.py
`pk` exists only for Builds that are retrieved from the database, but
when it's retrieved using the API, the `id` must be used.
Using the `id` is compatible with both instances.
Related to #2963
> Use `id` attribute instead of `pk` for build

- readthedocs/rtd_tests/tests/test_privacy.py
- readthedocs/templates/builds/build_list.html
- readthedocs/templates/core/project_details.html
> Do not show Build button when user is not project admin

- readthedocs/templates/core/project_details.html
The bug was introduced at
https://github.com/rtfd/readthedocs.org/pull/2944/files#diff-9a10ae0511ab8eb72096c4a0510a364eL38
Since the {% blocktrans %} was removed, the `slug` name was
undefined. Besides, there is no need to translate the slug, so the
first one was also removed
Fixes #3187
> Show the proper version in the project dashboard

- requirements/testing.txt
This should fix:
- https://travis-ci.org/rtfd/readthedocs.org/builds/308558295?utm_source=github_status&utm_medium=notification
```
pluggy.PluginValidationError: Plugin 'xdist' could not be loaded: (py 1.4.34 (/home/travis/build/rtfd/readthedocs.org/.tox/py27/lib/python2.7/site-packages), Requirement.parse('py>=1.5.0'), set(['pytest']))!
ERROR: InvocationError: '/home/travis/build/rtfd/readthedocs.org/.tox/py27/bin/py.test'
```
> Update CI requeriments

- .style.yapf
Keep this format:
```
def run(arg, arg, arg, arg,
arg, arg, arg):
pass
```
> Do not split before first argument

- readthedocs/projects/models.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_sync_versions.py
This previously used the `machine` tag that was turned off when a user de-activated the version,
but never turned back on when they re-activated it.
This changes to just use the `active` flag on the Version,
so we will update the stable version if the existing one is `active`,
and not if it isn't,
which makes _way_ more sense.
Refs #3268
> Change stable version switching to respect `active`

- .pre-commit-config.yaml
To continue with #3264 , I added `prospector` to the pre-commit hooks
> Add prospector as a pre-commit hook

- readthedocs/oauth/services/base.py
Because of a python quirk, we are currently returning an empty list during
pagination against oauth proviers. The quirk breaks down to this:
```python
def foo():
try:
return 'duck'
except Exception:
return 'duck'
finally:
return 'goose'
assert foo() == 'goose'
```
I didn't realize `finally` behaved in this manner with respect to `return`, so
hey, The More You Know™
> Fix python usage around oauth pagination

- docs/issue-labels.rst
This was brought up in https://github.com/rtfd/readthedocs.org/issues/2775, and will be useful to add along with the `bug` label.
Once this has been merged, we can create the label accordingly.
Note: I mistakenly opened this PR automatically from my CLI with old text. I have since edited it. Sorry about that.
> Add `Needed: replication` label

- readthedocs/doc_builder/backends/mkdocs.py
The mkdocs search builder was not passing its return code back up,
which meant `search=False`,
which means that the JSON files weren't syncing or being indexed.
> Fix mkdocs search.

- readthedocs/builds/static/builds/css/detail.css
- readthedocs/core/views/__init__.py
- readthedocs/templates/builds/build_detail.html
- readthedocs/templates/wipe_version.html
This is a basic start to trying to be more helpful to users.
> Suggest wiping your environment to folks with bad build outcomes.

- .style.yapf
This reverts commit 1b38e92ae7056e60631f6c777d99db1e8d2a60d1.
It turns out this causes more problems with line continuations
> Revert "Do not split before first argument (#3333)"

- readthedocs/projects/models.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_sync_versions.py
This reverts commit 0d9c3fefb1ea8a64272bfeff42cb37b8122ae335, reversing
changes made to 73b693ce4dd408e6a9f2812a8b7aaa9b9d205c7a.
> Revert "Merge pull request #3336 from rtfd/use-active-for-stable"

- CHANGELOG.rst
- contrib/changelog.hbs
- docs/changelog.rst
- package.json
- readthedocs/__init__.py
- readthedocs/core/templatetags/core_tags.py
- readthedocs/templates/base.html
- setup.cfg
- setup.py
- tasks.py
First, update the version in our setup.cfg and changelog:
invoke prepare <version>
Then, hand edit and commit, added any release notes, etc. Tag manually or:
invoke release <version>
Finally, push up your changes.
This:
* Uses setup.cfg instead of setup.py
* Parses setup.cfg for version
* Updates setup.cfg on release prepare task
* Show our release version in our footer
* Uses invoke for task execution
* Uses a node library to hit GitHub and fetch the changelog
* Imports this into our existing changelog
> Add changelog and changelog automation

- readthedocs/doc_builder/python_environments.py
Feature flag shows no noticeable bump in failure rate, so this seems pretty
solid now.
> Upgrade to latest Sphinx

- docs/tests.rst
- requirements/testing.txt
I just add a note about mercurial to solve #3320.
> Add note about mercurial on tests

- readthedocs/projects/tasks.py
This will let us force a CNAME in the base-level `foo.rtd.org` redirect case.
Refs #1916
> Pass more data into the redirects.

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/restapi/views/footer_views.py
This is because of #3311,
I notice that we are sending the `verbose_name` for the version slug.
We don't actually _have_ the version slug in the doc page,
so we need to start including that as well.
> Search for slug with case insensivitiy.

- readthedocs/settings/base.py
- readthedocs/templates/base.html
- requirements/pip.txt
> Remove copyright application

- readthedocs/templates/builds/build_detail.html
This added extraneous spacing to the build page.
> Don't display the build suggestions div if there are no suggestions

- readthedocs/projects/tasks.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/rtd_tests/tests/test_project.py
This is an initial idea to solve these kind of issues and avoid user confusions:
* Fixes #2795
* Fixes #3308 
* Fixes #3126
* Fixes #3230
* Related #2471
Here is an example on how this will look like
> Simple task to finish inactive builds

- tasks.py
Run gh-changelog with full path, in case env does not have node set up.
> Update prerelease invoke command to call with explicit path

- tasks.py
* Get the last modified date from git, not local file as normally expected
* Make sure we're on master to run
* Don't do reset to master on release
> Update changelog more consistently

- docs/abandoned-projects.rst
I went to look up our new policy and got confused :)
"Maintainers" is a term I attribute to project maintainers, not the core team of
Read the Docs. Because we refer to "core team" regularly, I updated that here.
This also alters the style of the lists to be less formal legal structure and
adds a couple pieces of reST that fit better.
> Update style and copy on abandonment docs

- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/rtd_tests/tests/test_oauth.py
- readthedocs/settings/base.py
> Use default avatar for User/Orgs in OAuth services

- .travis.yml
This should fix the double-building of travis.
via https://stackoverflow.com/questions/31882306/how-to-configure-travis-ci-to-build-pull-requests-merges-to-master-w-o-redunda
> Only build travis push builds on master.

- requirements/deploy.txt
Old version is breaking on my mac.
> Upgrade psycopg2

- readthedocs/api/base.py
- readthedocs/bookmarks/views.py
- readthedocs/comments/views.py
- readthedocs/core/views/__init__.py
- readthedocs/core/views/serve.py
- readthedocs/gold/views.py
- readthedocs/profiles/views.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
- readthedocs/search/views.py
- readthedocs/settings/base.py
This PR removes almost all the WARNING messages when running tests:
- migrate `render_to_response` to `render` from Django
- use `prepend_urls` instead `override_urls` from tastypie
There are two more warnings:
1. Tastypie uses an old method from Django, but we can't upgrade (even from 0.13.0 to 0.13.3) because there are some tests that do not pass (I could take a look at this in another PR)
```
readthedocs/rtd_tests/tests/test_api.py::APITests::test_make_project
/home/humitos/rtfd/code/readthedocs.org/.tox/py27/lib/python2.7/site-packages/tastypie/resources.py:2116: RemovedInDjango110Warning: 'get_all_field_names is an unofficial API that has been deprecated. You may be able to replace it with 'get_fields()'
field_names = self._meta.object_class._meta.get_all_field_names()
```
2. Linaro …
> Remove warnings from code

- readthedocs/projects/exceptions.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_project.py
I'm using BuildEnvironmentError for now, but we should use
ProjectConfigurationError once the PR got merged: https://github.com/rtfd/readthedocs.org/pull/3310
Closes #2963
> Show proper error to user when conf.py is not found

- readthedocs/templates/builds/build_detail.html
On a build detail page, link the version detail page that it's being built if the user is the admin of the project, otherwise just show the slug as usual.
Related to #3417
> Link to version detail page from build detail page

- readthedocs/vcs_support/backends/git.py
A better version of #3238 that fixes #1637, #1820 etc. thanks to responses from git ML.
https://public-inbox.org/git/CAPkN8x+MELCnttE+xptKzYXsYPWqbiE59LABrwNBhFroayc+wQ@mail.gmail.com/
Annotated tags in Git are special. GitHub is unable to find commit corresponding to tag hash, because annotated tags are pointing to tag meta data and need to be dereferenced first.
> Fix Edit links if version is referenced by annotated tag

- readthedocs/vcs_support/backends/git.py
Ref: https://github.com/rtfd/readthedocs.org/pull/3302#issuecomment-353451031
> Do not use double quotes on git command with --format option

- readthedocs/core/management/commands/symlink.py
- readthedocs/restapi/views/footer_views.py
Also has some updates to `symlink` command, so we can properly rebuild web05 without running out of memory.
> Hack in a fix for missing version slug deploy that went out a while back

- readthedocs/templates/builds/build_detail.html
> Don't show "build ideas" to unprivileged users

- docs/getting_started.rst
The existing link was broken. The URL has been updated to the correct one.
> Broken link URL changed fixes #3442

- readthedocs/doc_builder/config.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_doc_building.py
Initial drawing of ideas on how to implement #3190
> Check versions used to create the venv and auto-wipe

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/restapi/serializers.py
- readthedocs/rtd_tests/tests/test_api.py
This adds the programming language of a given project to the API response as well as puts it into the `READTHEDOCS_DATA` global in the `readthedocs-data.js` file in the generated docs output.
> Add programming language to API/READTHEDOCS_DATA

- docs/contribute.rst
- docs/issue-labels.rst
We use the name "Good First issue", not "Good first bug". I think we should also add a link to the issues, like this: rtfd/readthedocs.org/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Good+First+Issue%22+.
_No idea why my PR tool isn't working. Sorry if an initial email seemed different._
> Docs: Rename "Good First Bug" to "Good First Issue"

- readthedocs/builds/models.py
- readthedocs/builds/utils.py
- readthedocs/projects/constants.py
- readthedocs/rtd_tests/tests/test_repo_parsing.py
Fix #1788 
This happens when a project name contains `.git` in the middle of the name, like `some.github`, `hello.git.hello`.
For the record:
- If you create a repo like `name.git` in GitHub, the name changes to `name`.
- GitLab don't allow to create a repo that ends on `.git'
- Bitbucket allow to create a repo like `name.git`, but the clone url is fine.
I want to add some tests to this, but I don't know where to add them.
> Fix regex for getting project and user

- docs/gsoc.rst
This is our initial attempt to build a set of projects for GSOC.
It isn't an exhaustive list,
and could use more ideas!
> Add GSOC 2018 page

- media/css/readthedocs-doc-embed.css
This should be merged after https://github.com/rtfd/sphinx_rtd_theme/pull/380 and we use a new release of the theme.
> Remove RTD Theme workaround

- readthedocs/settings/base.py
This is a basic change that only applies in dev regarding the default cache. This makes caching actually work in development in case anything around caching needs to be verified.
https://docs.djangoproject.com/en/1.8/topics/cache/
> Convert default dev cache to local memory

- readthedocs/doc_builder/templates/doc_builder/include.js.tmpl
This attaches data to our Google Analytics pageviews and events to allow some nice aggregation. The data is not attached to any user analytics settings.
The data includes data about the project and the docs build:
* project name
* version
* language (eg. "en", "fr")
* theme ("readthedocs", "alabaster")
* programming language
* builder (always "mkdocs" here)
There will be a separate PR in https://github.com/rtfd/readthedocs-sphinx-ext for handling the same for sphinx. Hopefully this all gets replaced in the future by doing analytics with a server side include rather than a generated file in the documentation build output.
> Send custom dimensions for mkdocs

- prospector.yml
- readthedocs/api/utils.py
- readthedocs/builds/forms.py
- readthedocs/core/management/commands/clean_builds.py
- readthedocs/core/views/serve.py
- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/notifications/storages.py
- readthedocs/oauth/models.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/base.py
- readthedocs/search/utils.py
- readthedocs/vcs_support/utils.py
- requirements/lint.txt
- requirements/testing.txt
The new pylint has a couple of new features that makes our linting to fail. So, I fixed them as I think it's correct.
> Fix Travis lint issue

- .pre-commit-config.yaml
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/model_views.py
The idea of this PR is to not mix the style with the login from #3559 so it's easier to review.
> Style using pre-commit

- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/git.py
> Allow git tags with `/` in the name and properly slugify

- readthedocs/oauth/models.py
- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/rtd_tests/tests/test_oauth.py
When the DEFAULT_PRIVACY_LEVEL is ``private`` we allow to import
public _and_ private repositories from Bitbucket service.
This handles an issue under `.com`, https://github.com/readthedocs/readthedocs-corporate/issues/225
> Allow to import public repositories on corporate site

- docs/guides/remove-edit-buttons.rst
We don't have a great option for this currently. It should be a theme option,
but for now, here's the hack that removes all of the buttons.
> Add docs on removing edit button

- requirements/pip.txt
This is related to a production issue with the older requests version.
> Upgrade requests version

- readthedocs/builds/static/builds/css/detail.css
This problem is due to the `::-webkit-scrollbar` override specifying a scrollbar height and then trying to hide it with a negative margin.
Removing only the negative margin (as in #2350) results in the scrollbar still being allocated 15px extra. Instead removing both the negative margin and the extra scrollbar sizing of webkit of these brings the two browsers into parity. The only difference is that the scrollbar is visible on Firefox (there's no FF equivalent of `::-webkit-scrollbar`) but that doesn't impact the usability much.
- Fixes #2261
- Replaces #2630
(Chrome 63 in the foreground with Firefox Developer Edition 59 in the background)
> Fix for build screen in firefox

- media/css/core.css
- readthedocs/core/views/__init__.py
- readthedocs/templates/base.html
- readthedocs/templates/core/widesearchbar.html
- readthedocs/templates/homepage.html
This PR reworks the homepage with the hope that it makes getting started with RTD easier. Here's a summary:
- Call to action to get started
- Break up large blocks of text
- Remove recent projects (featured projects is still supported)
> Rework homepage

- docs/versions.rst
Closes #3528 
Please let me know if the English is fine :)
> Docs about preference for tags over branches

- package.json
Gulp is incompatible with the latest release of less.
See https://travis-ci.org/rtfd/readthedocs.org/builds/340312177
2.7.3 is the previous stable
https://github.com/less/less.js/blob/HEAD/CHANGELOG.md#273
> Pin less to latest compatible version

- .pre-commit-config.yaml
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_api.py
> Use DRF 3.1 `pagination_class`

- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
This allow us to have permanent pip cache between different builds /
projects to work faster locally and under slow internet connections.
Closes #3553
> Mount `pip_cache_path` in Docker container

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_subprojects.py
> Don't allow to create a subproject of a project itself 

- docs/builds.rst
- readthedocs/core/management/commands/pull.py
- readthedocs/core/views/hooks.py
- readthedocs/doc_builder/environments.py
- readthedocs/projects/apps.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- readthedocs/vcs_support/backends/bzr.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/backends/hg.py
- readthedocs/vcs_support/backends/svn.py
- readthedocs/vcs_support/base.py
I've been taking a look at the code and I found some consideration that we need to take a look:
1. `BaseVCS` class has it owns `run` method that works in a similar way than `BuildEnvironment.run`
* the `log_tmpl` string differs
* it adds some configurations automatically, like the `cwd` path
1. All commands ran by `BaseVCS` are not logged as a `BuildCommand`
1. `BuildCommand` needs to be instantiated with `build_env` to make be able to `.save()`/record the command for the current `Build` object.
1. `build_env` could be `LocalEnvironment` or `DockerEnvironment`
Depending on how much we want to refactor, a minimalistic _solution_ would involve:
1. pass `setup_env` to `update_imported_docs`
1. pass this env to `version_repo.checkout`
1. under `checkout` consider use if that `env` if not …
> Log `git checkout` and expose to users

- readthedocs/doc_builder/templates/doc_builder/include.js.tmpl
- readthedocs/templates/base.html
For RTD's analytics purposes, we never need IP addresses more granular than this.
https://support.google.com/analytics/answer/2763052?hl=en
> Anonymize IP addresses for Google Analytics

- readthedocs/api/utils.py
This URL results in a 500 error in production:
http://readthedocs.org/api/v1/file/search/?format=json&q=virtualenvwrapper
This PR fixes that error. I know the API v1 is in some stage of deprecation but this will at least fix the error.
> Fix a 500 when searching for files with API v1

- readthedocs/projects/tasks.py
This solves an issue in the .com site that we are experimenting.
Although I couldn't get the error report in .org Sentry, I'm not receiving the email on FAILED builds in my .org account either. So, I think this PR will also fix the problem here.
> NOTE: by sending the objects as dictionaries we can continue using the templates as they are. Antoher approach could be sending all that data in separate fields like `version_verbose_name` or `project_name` and adapting the templates to this.
Ref: https://github.com/readthedocs/readthedocs-corporate-ops/issues/77
> Send proper context to celery email notification task

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_build_notifications.py
Add test and fixes bug introduced in #3653
> Tests for build notifications

- readthedocs/builds/models.py
- readthedocs/core/views/serve.py
- readthedocs/projects/tasks.py
This is clogging up our Sentry instance,
causing us to go over our free allotment.
> Remove error logging that isn't an error.

- readthedocs/settings/base.py
This was looking for setting DEFAULT_PRIVACY_LEVEL, which wasn't set by default
in our settings.
> Fix issue with missing setting in oauth SyncRepo task

- readthedocs/projects/tasks.py
It exists in subclasses, but we should refactor it out anyways.
Closes #3655
> Hotfix for adding logging call back into project sync task

- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/utils.py
- readthedocs/vcs_support/backends/git.py
> Check for submodules

- requirements/pip.txt
Upgrade this package to be more prepared for Python3 and Django 2.0
Related #3666
> Upgrade django-taggit to 0.22.2

- readthedocs/core/templates/core/ko_form_field.html
Update common knockout form field template to add argument to skip errorlist
display through knockout observables.
> Add argument to skip errorlist through knockout on common form

- readthedocs/doc_builder/environments.py
Now that we are changing/upgrading Docker images, this will help us to know which image we are using to build the documentation.
Also, I'm logging in the proper place `create_container` method instead of in the `__enter__` that could not create the container if it's already created.
> Log in the proper place and add the image name used

- readthedocs/templates/core/project_detail_right.html
Fix #2085 
With http protocol
With git protocol
> Check for http protocol before urlize

- readthedocs/vcs_support/backends/git.py
This is causing the build to be marked as FAILED when the repository
has no branches.
> Always record the git branch command as success

- readthedocs/projects/models.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- requirements/testing.txt
> Project updated when subproject modified

- tox.ini
I was trying to run `tox -e coverage` but were missing dependencies from `requirements/testing.txt` (like pytest-django).
> Fix tox env for coverage

- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- requirements/pip.txt
These ones were not upgraded since they are incompatible:
* django
* docker-py
* celery
* elasticsearch
* pyelasticsearch
This is just a way to run all the test with this environment and also to discuss with other people if this is something we really want.
Closes #1893
> Upgrade all packages using `pur` tool

- .gitignore
- readthedocs/core/views/__init__.py
Fixes https://github.com/readthedocs/readthedocs-corporate/issues/237
> Allow members of "Admin" Team to wipe version envs

- requirements/lint.txt
I think this is a bug on pylint-django https://github.com/PyCQA/pylint-django/issues/117#issuecomment-371689024
I tried with `pylint==1.8.2` but didn't solve the problem.
> Pin astroid to fix linter issue on travis

- .isort.cfg
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/base.py
> Autolint cleanup for #3821

- readthedocs/doc_builder/environments.py
When we record the command as SUCCESS (exit_code=0) we also need to
update the current instance of BuildCommand because `self.exit_code`
is used to calculate BuildEnvironment.successful. The later is part of
the decision of `update_on_success`, and as the command was marked as
failed, we were updating the status.
This looked as a random failure, but it was happening always that any
of the `record_as_success` command failed, but it wasn't easy to see
it because it the jQuery request has to be done exactly after the
Build was marked as FAILED and before the next command was executed,
since the state was changed immediately to "Building"
Fixes #3644
> Update instance and model when `record_as_success`

- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/base.py
This adds a project feature that allows for a project to specify that they would
like to skip submodule installation. Currently we are forcing all submodules to
be checked out, so this fails on private submodules.
Refs https://github.com/rtfd/readthedocs-build/issues/30
Based on #3822 for autolint cleanup
> Add temporary method for skipping submodule checkout

- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
> Save docker image hash to consider when auto wiping the environment

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- readthedocs/settings/base.py
This is an initial implementation of this task to remove orpahn symlinks, which should be ran periodically every 1h aprox.
In the ticket, I also suggested that the `Edit` action doesn't make sense to me and should be reconsidered.
Finally, if we consider to remove the `Edit` action, this task should be run just once and should be enough.
Closes #3493
> Task to remove orphan symlinks

- readthedocs/builds/static/builds/css/detail.css
- readthedocs/templates/builds/build_detail.html
This PR is related to #3398 and #2469
For now, I trying to solve this:
> If we're on a build, use the build version for the view docs link! This gets me every time
I think the `View Docs` button must remain the same on all the _project area_, otherwise it would be confusing.
I don't know much css, so any feedback is more than welcome :).
**Here is how it looks right now**
**And how it will looks like after merging**
**This is still _very_ WIP, so any feedback and suggestion is welcome!**
> Show link to docs on a build

- readthedocs/projects/constants.py
- readthedocs/rtd_tests/tests/test_repo_parsing.py
I just realized that on #3501 I forgot to test a bitbucket repo as a logout user.
When you are login, the clone url is
But when you are log out look like this
This ends with `.git`
Sorry for the bug :(
> Fix regex for public bitbucket repo

- readthedocs/rtd_tests/utils.py
Fixes 2 "line too long" errors in the linting tests.
> Fix linting errors in tests

- tox.ini
For example:
```bash
tox -av 
default environments:
py27     -> run test suite for the application with python2.7
py36     -> run test suite for the application with python3.6
lint     -> run linter (prospector) to ensure the source code corresponds to our coding standards
docs     -> build readthedocs documentation
additional environments:
coverage -> run test suite with code coverage for the application with /usr/bin/python
eslint   -> run the JavaScript linter (requires gulp installed)
```
> add description for tox tasks

- readthedocs/core/validators.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/utils.py
- readthedocs/vcs_support/backends/git.py
* Add conditional logic for submodule relative urls
* Break down logic a bit more
* Add test case for relative url submodule
* Broke test case for invalid url submodule
Fixes #3857
> Fix up some of the logic around repo and submodule URLs

- readthedocs/vcs_support/backends/git.py
- requirements/pip.txt
> Use gitpython to find a commit reference

- media/css/readthedocs-doc-embed.css
> Fix an Alabaster ad positioning issue

- requirements/testing.txt
This was causing errors running tests with py36 and pdb set_trace
> Drop pdbpp from testing requirements

- readthedocs/settings/base.py
- requirements/pip.txt
This PR will install the new django-celery-beat package and use its scheduler for persistent tasks.
This change involves installing this new package `django-celery-beat` (from `pip.txt`) and also remove the old `djcelery` if it's still installed. Besides, we need to run `migrate` on deploy.
> Use new django celery beat scheduler

- readthedocs/projects/tasks.py
The logic didn't change here, but since it on error (Sentry) it was reporting `docker=False` it was confusing when debugging.
> Use a proper default for `docker` attribute on UpdateDocsTask

- readthedocs/builds/models.py
- readthedocs/builds/syncers.py
- readthedocs/core/management/commands/clean_builds.py
- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/core/signals.py
- readthedocs/core/views/hooks.py
- readthedocs/doc_builder/environments.py
- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/payments/forms.py
- readthedocs/projects/search_indexes.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/base.py
- readthedocs/projects/views/private.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_privacy.py
- readthedocs/rtd_tests/utils.py
- readthedocs/search/parse_json.py
- readthedocs/search/utils.py
- readthedocs/vcs_support/utils.py
Log only what we need as ERROR when it's something that we need/want to take a look that something could be a bug/issue.
There are some ERROR that were replaced by WARNING since they are some failures but that we don't need to take a look and the message shown to the user should be enough for them.
Check #3898 for style changes
> Organize logging levels

- readthedocs/doc_builder/python_environments.py
Avoid failing when using LocalBuildEnvironment. This was trying to access a specific value defined only in DockerBuildEnvironment and it doesn't make sense to have them in other environments.
> Save Docker image data in JSON file only for DockerBuildEnvironment

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
The canonical domain was not searching as deep as we support. We support
translations nested in subprojects, and vice versa, this was previously only
searching for translation or subproject, so no nesting at all.
The path was also a similar problem, but instead of a heavy refactor that reused
the canonical domain lookup, I just altered the logic a little here. The pattern
was required to support both superproject as a translation project and
subproject as a translation project.
> This fixes two bugs apparent in nesting of translations in subprojects

- .github/ISSUE_TEMPLATE.md
Maybe this helps people to put the RTD URL instead of the github or any other kind of URL related to the project that they are reporting.
> Mention RTD in the Project URL of the issue template

- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
If the user delete the RTD webhook integration for whatever reason from the project under the external service (GitHub, etc) when the Resync button is pressed we re-create / setup the webhook as it was never existed.
This behaviour already existed, but it worth to mention it:
> If the user modifies the webhook in the external service (changing the URL for example), when Resync button is pressed, we update it with the proper URL.
Closes #3931
> Resync webhooks from Admin

- readthedocs/projects/forms.py
There is no changes in the logic, just make these two forms extendable from Corporate site since we need to change some logic regarding the Organizations permissions.
> Allow extend Translation and Subproject form logic from corporate

- readthedocs/oauth/utils.py
When a project is imported manually, if the user has a valid social account we setup a webhook for this project.
If the user goes to Integrations and try to resync, we handle that properly (use the Project.remote_repository only when available, otherwise use the accounts registered for that service even if they are not associated with that project)
Closes https://github.com/readthedocs/readthedocs-corporate/issues/297
> Resync valid webhook for project manually imported

- media/css/readthedocs-doc-embed.css
This is a fix in case content on the page causes the `<body>` width to exceed the viewport width.
`vw` is understood by basically every browser visiting our site (IE9+, Chrome, FF, Safari) except Opera Mini. For this case, 100% is used as a fallback. https://caniuse.com/#search=vw
Here's the issue I'm trying to fix:
> Fixed footer ad width fix

- media/css/core.css
- readthedocs/templates/core/project_details.html
Going over the changes:
`.quiet` was removed because it was already defined elsewhere, which didn't make much sense. The line of duplication is line 46.
`#content #project_description` was simplified to just `#project_description`.
I also made the decision to make the `margin-bottom` a `margin-top` because it does nothing otherwise. An example in practice is [godot](https://readthedocs.org/projects/godot/). And if you are to look at the HTML file, its going to end up rendered at the bottom. Essentially, it's useless and I think it was meant for it to be a top margin such that there would be appropriate spacing.
I also adjusted the template in `project_details.html` such that it removed the extra id and needless div, and would not leave an empty div in case of there not being a …
> Make adjustments to Projects page

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This PR shows an adblock admonition in the browser developer console. While I don't think this will convert many hearts and minds, I believe it is a good first step.
> Show an adblock admonition in the dev console

- docs/guides/build-notifications.rst
> Documentation for build notifications using webhooks.

- readthedocs/core/tasks.py
- readthedocs/core/utils/__init__.py
- readthedocs/settings/base.py
Set up a scheduled task every Sunday night at 23:59 to delete all expired Persistent Messages.
> [#2967] Scheduled tasks for cleaning up messages

- readthedocs/settings/base.py
- requirements/pip.txt
There are some issues with timezone for the `DatabaseScheduler`, so we fallback to the default one (celery.beat.PersistentScheduler) which is simpler --doesn't allow us to change the scheduled task from the admin, but we don't need that.
In case we need this again, we can come back when those issues are already fixed and revert this commit.
> Remove django-celery-beat and use the default scheduler

- readthedocs/settings/test.py
The import path for the local_settings should be relative to the
test module and not absolute otherwise the import will fail.
> Fixup DJANGO_SETTINGS_SKIP_LOCAL in tests

- readthedocs/redirects/models.py
- readthedocs/templates/projects/project_redirects.html
Fix #2431
Now the from and to URLS are shown
> Show URLS for exact redirect

- docs/install.rst
This is a quick edit to give people more information as they come into this.
> Document creation of slumber user

- docs/advertising-details.rst
- docs/ethical-advertising.rst
- docs/index.rst
- media/javascript/readthedocs-analytics.js
We get a fair amount of inquiries regarding advertising. These usually take the form of one of:
* Request for details around ad targeting
* Questions (occasionally outrage) around "we don't track you" and analytics
The goal of this PR is to cover these as much as possible.
I didn't cover the data retention and data sharing associated with advertising but I want to wait until we have a privacy policy (#2602) in place to do that. It might happen in the privacy policy rather than in these docs.
Fixes #3952 (mostly)
> Add advertising details docs

- readthedocs/doc_builder/templates/doc_builder/data.js.tmpl
`mkdocs_page_input_path` isn't available on all pages.
> Doc builder template should check for mkdocs_page_input_path before using it

- readthedocs/doc_builder/backends/mkdocs.py
The vast majority of docs built with mkdocs are in fact the `readthedocs` theme. However, some aren't. Here are some counter-examples:
- https://crafttweaker.readthedocs.io/en/latest/
- https://mcforge.readthedocs.io/en/latest/
> Correctly report mkdocs theme name

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
This is an invalid db state since this relationship is not possible, but there are some old project that has this relationship and we want to avoid breaking the code for this cases.
> Make `resolve_domain` work when a project is subproject of itself

- requirements/pip.txt
```
$ pur --skip django-tastypie,django,docker-py,elasticsearch,pyelasticsearch,commonmark,stripe,djangorestframework,mkdocs,django-allauth
Updated pip: 9.0.3 -> 10.0.0
Updated virtualenv: 15.1.0 -> 15.2.0
Updated Sphinx: 1.7.0 -> 1.7.2
Updated sphinx-rtd-theme: 0.2.5b1 -> 0.3.0
New version for readthedocs-build found (2.0.9), but current spec prohibits updating: readthedocs-build<2.1
Updated django-haystack: 2.7.0 -> 2.8.1
Updated django-extensions: 2.0.0 -> 2.0.6
Updated django-vanilla-views: 1.0.4 -> 1.0.5
Updated lxml: 4.1.1 -> 4.2.1
Updated httplib2: 0.10.3 -> 0.11.3
Updated GitPython: 2.1.8 -> 2.1.9
Updated pytz: 2018.3 -> 2018.4
Updated docker: 3.1.3 -> 3.2.1
Updated sphinxcontrib-httpdomain: 1.6.0 -> 1.6.1
Updated packaging: 16.8 -> 17.1
All requirements up-to-date.
```
> Use pur to upgrade python packages

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_celery.py
Move task steps to an isolated class, instead of possibly sharing state in
between tasks. This bug is not consistently reproduceable, but one consistent
way to reproduce is to drop to ``rdb`` on the UpdateDocsTask run method.
Previously, if you did this while running 2 celery processes, and triggered 2
builds, you could witness state changing on the task instance. By moving state
to a separate class that is instantiated on each task execution, this completely
avoids shared state in these tasks.
> Don't share state in build task

- readthedocs/doc_builder/python_environments.py
More info/questions in the issue itself.
Closes #3963
> Use latest setuptools (39.0.1) by default on build process

- readthedocs/redirects/models.py
- readthedocs/rtd_tests/tests/test_redirects.py
Exact redirects depend on the full path being set against, so that you can do things like redirect versions. This was broken in a previous refactor.
> Fix exact redirects.

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
Ref: https://sentry.io/read-the-docs/readthedocs-org/issues/533028643/
> Resolve domain when a project is a translation of itself

- readthedocs/projects/tasks.py
There is no `self.retry` on the task step class, this exists on the task.
This also fixes a bug where we weren't handling the lock on the python step as
well.
We discussed a better pattern to use here would be to rely on celery on_failure
and on_retry event methods more. This would simplify logic here greatly.
> Give TaskStep class knowledge of the underlying task

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
Remove previous fixes that were trying to catch specific cases, apply a general
solution that tests if we're in a loop.
> Fix recursion problem more generally

- readthedocs/rtd_tests/tests/test_subprojects.py
I saw this while looking into another issue. When I run the tests only on this file `tox -e py36 readthedocs/rtd_tests/tests/test_subprojects.py` tests fail because of the order, weird that this never fails when running the full suite of tests.
> Don't check order on assertQuerysetEqual on tests for subprojects

- readthedocs/settings/dev.py
This changes our default to allowing users to login w/out verifying their pw,
but still sending the password to them via email.
I think this is better for dev,
so folks don't need to verify a fake email when just playing around locally.
> Make email verification optional for dev

- media/css/core.css
- readthedocs/settings/base.py
- readthedocs/templates/account/login.html
- readthedocs/templates/account/signup.html
- readthedocs/templates/socialaccount/snippets/provider_list.html
While this was technically supported if you knew the URLs, this adds formal support for logging in and signing up with our providers (currently GitHub, BitBucket, and GitLab).
Let's say your user account already is connected to GitHub because you actually use Read the Docs with your GitHub account. The "Sign in with GitHub" button will just work for you. You can still use your old username and password if you like.
If your GitHub account is not connected to anything and you click the "Sign in with GitHub", you will authenticate with GitHub, and then you will get a confirmation screen where you tie your GitHub account and email to a new Read the Docs username (see screenshot below). After confirming, you'll be logged in. The first and last name may be populated from the provider if …
> Support sign in and sign up with GH/GL/BB

- readthedocs/builds/views.py
- readthedocs/templates/builds/build_list.html
This piece of UI was never updated to fit somewhere more cohesive in the UI and
I feel is a strange thing to expose directly to users. I think a better
application for this is in an eventual status page. A status page is not a
priority atm though.
> Remove build queue length warning on build list page

- readthedocs/doc_builder/backends/mkdocs.py
Read the Docs has implemented some privacy enhancements for authors who opt to enable Google Analytics on their projects. This change enables those for MkDocs projects.
For example, the mkdocs project (a documentation project that uses mkdocs itself) specifies their own [Google Analytics code in their `mkdocs.yml`](https://github.com/mkdocs/mkdocs/blob/5ee6600/mkdocs.yml#L36). When MkDocs builds the docs, the Google analytics snippet is injected directly into the output. However, Read the Docs already supports user GA analytics codes and has enabled some improvements around there such as anonymizing visitor IPs. Without this change, MkDocs projects bypass these protections which can result in reduced privacy or possibly double counting in analytics (if the analytics code is specified in …
> MkDocs projects use RTD's analytics privacy improvements

- readthedocs/api/base.py
`sync_versions` have methods that doesn't exists like `_sync_versions` and `_delete_versions`, so it always was throwing an exception. This was used internally only, and now we use the `sync_versions` from the apiv2.
Some comments about this https://github.com/rtfd/readthedocs.org/issues/3887#issuecomment-378029743
> Remove dead code from api v1

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- requirements/pip.txt
Since the feature flag is `sphinx<2`, I didn't touch it.
Closes #4015
> Bump sphinx default version to 1.7.4

- readthedocs/oauth/services/gitlab.py
- readthedocs/rtd_tests/tests/test_oauth.py
When we import a Project manually we don't have a RemoteRepository associated with that Project, so we use the old technique of getting the username and repo names from the URL using `get_gitlab_username_repo` function.
This case (Manual Import) won't support custom Gitlab installations in the future with this code.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/265
> Allow import Gitlab repo manually and set a webhook automatically

- docs/design/yaml-file.rst
I'm publishing the first draft, there are a some things that will need more work/review.
Related https://github.com/rtfd/readthedocs-build/issues/29, https://github.com/rtfd/readthedocs-build/issues/30, https://github.com/rtfd/readthedocs-build/issues/3, https://github.com/rtfd/readthedocs.org/issues/3806, https://github.com/rtfd/readthedocs.org/pull/3685, https://github.com/rtfd/readthedocs.org/issues/2904, https://github.com/rtfd/readthedocs.org/issues/2813
> Design docs for the yaml file

- readthedocs/profiles/urls/public.py
- readthedocs/rtd_tests/tests/test_urls.py
- readthedocs/rtd_tests/tests/test_views.py
This PR Fixes #2953. I have added the `+` character to the username set. Rest all characters `letters` , `numbers`, `-` and `_` were already doing fine with the URL.
> Fixes #2953 - Url resolved with special characters

- readthedocs/templates/account/login.html
When a private page is accessed by a non logged in user, the user is redirected to the login view. If the user uses the traditional login, after this the user will be redirected to the page that was trying to access.
If the user uses the social login, it was redirected to /. This PR fixes that to behaves in the same way than regular login.
> Use next field to redirect user when login is done by social

- readthedocs/core/static-src/core/js/doc-embed/constants.js
- readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This PR enables ads on the `readthedocs` theme for projects using Markdown.
Before merging, we should probably notify users of the mkdocs theme.
**NOTE:** #3920 should probably be merged first as some themes are incorrectly identified as the `readthedocs` theme. It isn't strictly critical as it is unlikely that the ad injection selectors will match on a custom theme and so it will likely just result in API calls that don't result in an ad being displayed.
**SCREENSHOTS**
> Enable ads on the readthedocs mkdocs theme

- readthedocs/projects/tasks.py
When the `project.documentation_type` is set to `auto` we are protecting ourselves by updating it at build time to `sphinx`. At this point we also update our project memory instance, but we were missing to update the project memory instance that lives inside the version memory instance.
Closes #3980
> Update the `documentation_type` when it's set to 'auto'

- docs/settings.rst
- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
- readthedocs/settings/base.py
This PR adds an option `PUBLIC_DOMAIN_USES_HTTPS` which if set will make all "view docs" links and everywhere that uses the resolver (eg. the version selector menu) default to HTTPS for `*.readthedocs.io`domains. We know there is a valid certificate for these and so our generated links should use HTTPS.
This is step 1/5 on on getting to HTTPS everywhere:
https://github.com/rtfd/readthedocs.org/issues/3282#issuecomment-369509347
> Subdomains use HTTPS if settings specify

- readthedocs/settings/base.py
The warning was
> The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default
TEMPLATES dict: TEMPLATE_DEBUG.
And we already have the debug option there
https://github.com/rtfd/readthedocs.org/blob/b05c82acc69e492533da9b7e3e40fef2456af6de/readthedocs/settings/base.py#L176
Also, there is a warning about Guardian
> Guardian authentication backend is not hooked. You can add this in settings as eg: `AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend')`.
I think that setting is used in production, right?
> Remove Django deprecation warning

- readthedocs/projects/tasks.py
When we set the `has_valid_clone` in the Project instance that we are using for the current Build, we also need to update the project instance that lives inside the Version instance.
Similar to #4080
> Set valid clone in project instance inside the version object also

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
This will use the latest theme across the whole site unless people are pinned to a specific version. I believe this is sufficiently stable to roll out to a wider audience. While 0.3.0 had a number of issues, the biggest complaint we are seeing in 0.3.1 is the lack of highlighting (surprising since that never worked from the dawn of history until a week ago).
https://sphinx-rtd-theme.readthedocs.io/en/latest/changelog.html#v0-3-1
Fixes #4072
Fixes #4050
> Use the latest theme version in the default builder

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/base.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
Closes #3799 
Was a little hard to figure out testing here, I think we don't have tests for the other builders :thinking:
> Don't sync _static dir for search builder

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_project_forms.py
> Additional validation when changing the project language

- docs/ethical-advertising.rst
- docs/support.rst
- readthedocs/core/context_processors.py
- readthedocs/core/forms.py
- readthedocs/gold/templates/gold/subscription_form.html
- readthedocs/profiles/urls/private.py
- readthedocs/profiles/views.py
- readthedocs/templates/profiles/base_profile_edit.html
- readthedocs/templates/profiles/private/advertising_profile.html
- readthedocs/templates/projects/project_advertising.html
- readthedocs/templates/projects/project_edit_base.html
- readthedocs/templates/support.html
In general, the goal of this PR is to update some of our marketing and documentation to better reflect the reality at Read the Docs.
Here's an overview of the changes:
- Make it more obvious that becoming a Gold Member removes advertising
- Try to standardize on the terminology "Gold Member" rather than "buying gold" or anything else.
- Explain about RTD advertising in the user profile where users can go community-only, donate, or otherwise opt-out/-in
- When `settings.USE_PROMOS = False`, remove the links to manage advertising.
One change I did not do but am considering is to allow staying logged-in longer than 2 weeks. This becomes somewhat important when users are becoming a Gold Member to skip ads. Having people log in every two weeks seems suboptimal.
> Update Gold Member marketing

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This fix #3715
The problem is because of the `sphinx_tabs.tabs` extension, which somehow collides with the rtd extension. If the rtd extension is put before the tabs extension on the list of extensions the problem is solved.
I'm not sure if there are other implications with this change, or isn't really relevant for others users that don't use the tabs extension to have the rtd extension to the end or beginning.
> Put the rtd extension to the beginning of the list

- .coveragerc
- tox.ini
This ignores the files from the migration folders, so we have a better coverage report. In the future would be nice to integrate coverage into the CI pipeline.
> Ignore migrations from coverage report

- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
log.exception should not be used outside exception handlers
> oauth/services: don't abuse log.exception

- readthedocs/oauth/services/base.py
the else code was dead code as the code in the try block already
returned. Instead return an empty list when it is needed.
> oauth/services: correct error handling in paginate

- readthedocs/restapi/serializers.py
- readthedocs/rtd_tests/tests/test_api.py
This is needed to be able to update the `has_valid_clone` field from the UpdateDocsTask when a build is triggered but also it's good information to have over the API.
Closes #4106
> Add `has_valid_clone` and `has_valid_webhook` to ProjectAdminSerializer

- readthedocs/vcs_support/backends/hg.py
Without the quiet mode, the current revision of the branch is also
displayed which breaks parse_branches.
> Use quiet mode to retrieve branches from mercurial

- readthedocs/templates/core/project_detail_right.html
patches #3694: renamed owners to maintainers, until a differentiation is established between an owner and a maintainer at model level.
> Ticket #3694: rename owners to maintainers

- readthedocs/core/symlink.py
Fixes https://github.com/rtfd/readthedocs.org/issues/3665
> Refactor to replace old logging to avoid mangling

- docs/install.rst
This is required to fix Edit button on annotated tags
https://github.com/rtfd/readthedocs.org/pull/3441 (reverted fix)
> Update Git on prod

- readthedocs/core/static-src/core/js/doc-embed/version-compare.js
- readthedocs/restapi/views/footer_views.py
- readthedocs/rtd_tests/tests/test_footer.py
This closes #2357 
A time ago travis failed, so this #3402 was proposed. Now while looking at #2357 I think we only need to return a single value (a version only have a single unique slug).
The js, didn't break because of some weird js implicit cast.
```js
var currentURL = window.location.pathname.replace('rtfd', ['hi'])
console.log(currentURL)
// This works!
```
But as mentioned on the spec, must be a string not a list https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace.
Note: Thanks @lethosor for his initial work on this https://github.com/lethosor/readthedocs.org/commit/7d84130471885905a3f663324af602b7be1f7f64
> Consistent version format

- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/utils.py
- readthedocs/vcs_support/backends/git.py
- tox.ini
Fix #1820
It has been previous attempts to fix the issue with annotated tags (#3302).
I'm using git python to get the tags, I tested this with a local repo with annotated and lightweight tags and it works as expected :).
I'm little worried about pyhon2 here since we need to use `str` to get the info. I did two builds using py2 (one with tags and other with no tags) and works as expected.
Refs #3839
> Use gitpython for tags

- readthedocs/core/views/serve.py
- readthedocs/templates/401.html
- readthedocs/templates/404.html
- readthedocs/templates/500.html
- readthedocs/templates/base.html
This marks docs pages served by Django as CSRF exempt. This should prevent a CSRF cookie from being set (it does in dev at least).
> No CSRF cookie for docs pages

- docs/conf.py
- docs/contribute.rst
- docs/design.rst
- docs/ethical-advertising.rst
- docs/faq.rst
- docs/getting_started.rst
- docs/install.rst
- docs/issue-labels.rst
- docs/privacy-policy.rst
- docs/security.rst
- docs/webhooks.rst
I just did a grep to find those links and also to make sure they aren't used in other parts. There are still some links that are used externally (like the yaml file I think) or are out of the scope like the changelog (but I think we can still have those links, going to investigate later).
Closes #4140
> Use autosectionlabel extension

- docs/_static/dmca/takedown-template.txt
- docs/dmca/index.rst
Includes a helpful DMCA template to speed along requests. This is based on [GitHub's DMCA requests](https://github.com/github/dmca).
> Include a DMCA request template

- media/css/core.css
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/templates/base.html
This reworks the footer specifically to:
- Add an email newsletter signup form. Back in 2014 ([see WayBack Machine](https://web.archive.org/web/20140415000000/http://readthedocs.org:80/)) we had an email newsletter in the footer. It got way too much spam signups and would have cost us money to continue to use it. Our email newsletter is now "double opt-in" meaning not only do users have to type in an email address but they have to confirm their email address by receiving an email and clicking a confirm to sign up to the list. This should drastically reduce the spam signups and increase quality overall.
- Balances the 3 footer columns a bit better
- Centers the social media/github icons
- The version number is on its own line. Previously this wrapped slightly awkwardly.
From a browser …
> Small footer rework

- docs/conf.py
- readthedocs/settings/dev.py
- tox.ini
Also remove static path file.
This also fixes a bug that was causing logging to not be happening in Sphinx. This now properly shows errors, so that we can fix them.
> Remove CSS override that doesn't exist.

- docs/guides/build-using-too-many-resources.rst
- package.json
This writes up a simple guide for improving resource usage in your docs.
Refs #3220
> Add another guide around fixing memory usage.

- media/css/core.css
This PR removes the outline reset for the main site. 
This is needed to improve accessibility of the site. Outline is much needed for a lot of keyboard-only users and should not be removed. It's only allowed to be reset if you actually restyle it. 
Read more: http://www.outlinenone.com/
> Remove outline reset to bring back outline

- media/css/core.css
- readthedocs/templates/projects/projectrelationship_list.html
> Add "edit" and "view docs" buttons to subproject list

- docs/api/projects.rst
- docs/privacy-policy.rst
- docs/team.rst
- readthedocs/builds/managers.py
- readthedocs/builds/models.py
- readthedocs/core/utils/extend.py
- readthedocs/core/views/hooks.py
- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
- readthedocs/projects/views/mixins.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
Related to https://github.com/rtfd/readthedocs.org/pull/4166
> Fix some warnings on docs

- readthedocs/core/static-src/core/js/doc-embed/search.js
A comparison was previously relying on type coercion, and when linting fixes
changed this to an exact comparison operator, this comparison started failing.
> Fix issues with search javascript

- readthedocs/rtd_tests/tests/test_privacy_urls.py
We have two issues. First we were checking always against the
default status_code and not the one we expected, second we can't
assume that integration id is always 1 but update urls with the
current id.
Fix #3957
> tests: fixup url tests in test_privacy_urls

- fabfile.py
Split the i18n helpers in two:
- one to update the source language (english) translation in
transifex
- one to get the update translations and compile them
This has been done so hopefully the translatable strings can
be updated more frequently and translators don't waste time
translating strings removed.
While at it add force options to tx pull as for some reason it
changed default behaviour to not override already available
translations which means to do nothing by default.
> fabfile: update i18n helpers

- media/css/readthedocs-doc-embed.css
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
- Politely nag people to whitelist
- Link to our "ads for open source" docs
> Ad block nag to urge people to whitelist

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- requirements/pip.txt
This does a few smaller changes to mkdocs:
* Updates mkdocs to the latest version 0.17.3
* `cat mkdocs.yml` so it appears in the build logs like `conf.py`. This should make issues with MkDocs easier to debug.
In the 0.17.0 version of MkDocs, there were some [changes to how themes are configured](http://www.mkdocs.org/about/release-notes/#theme-customization-1164). Essentially previously, there was a `theme` setting and a `theme_dir` setting in the `mkdocs.yml`. Now there is a `theme` setting which is a dict with `name`, `custom_dir`, and other settings. We need to support both of these in the event they are building with an older version of mkdocs by pinning it in their requirements.
Should fix #3991.
> Update mkdocs to the latest

- readthedocs/projects/tasks.py
- requirements/deploy.txt
- requirements/lint.txt
> Remove maxcdn reqs

- readthedocs/templates/core/project_details.html
- readthedocs/templates/core/project_downloads.html
- readthedocs/templates/projects/integration_list.html
- readthedocs/templates/projects/project_version_list.html
I just noted that the `Versions` section looks different to the others.
**Here is how it looks right now**
**And how it will look like after merging**
> Wrap versions' list to look more consistent

- requirements/pip.txt
$ pur --skip django-tastypie,django,docker-py,elasticsearch,pyelasticsearch,commonmark,stripe,djangorestframework,mkdocs,django-allauth
Closes #4125
> Upgrade packages with pur

- docs/guides/run-elasticsearch-local.rst
- docs/install.rst
With reference to #3803 and in replacement of #3852 .
I have created a new PR because of following reasons:
1. I had pushed the changes to master branch previously. 
2. In order to sync the master branch of forked repo to the RTD repo, I had git pushed hard (i know that is not a good practice but that was the only way I could think of). This automatically closed the previous PR.
3. Unintentional files edited by other users were reflected to the previous PR (i've no idea how)
> Written guide for elasticsearch local

- docs/badges.rst
The [badge examples in our docs](https://docs.readthedocs.io/en/latest/badges.html#status-badges) are 404-ing until this is merged.
This doesn't appear to affect badges people are actually using. Just the docs.
> These links weren't correct after #3632

- docs/advertising-details.rst
- docs/guides/google-analytics.rst
- docs/privacy-policy.rst
The changes for adding autosectionlabel (#4146) didn't apply to the Do Not Track PR (#4046) as they were merged around the same time.
This simply applies the same style.
As this is just a formatting change, there's no need to change the date on the privacy policy.
> Use autosectionlabel in the privacy policy

- readthedocs/builds/views.py
The code that determines whether to display the "trigger build" form [uses one set of logic](https://github.com/rtfd/readthedocs.org/blob/4ab5f75/readthedocs/templates/builds/build_list.html#L29) while the code that actually makes the build happen uses another.
This change makes them use the same logic.
> Allow staff to trigger project builds

- docs/getting_started.rst
Hello,
This is my first `readthedocs.org` pull request! 🎉 
I updated the YouTube screencast URL because YouTube uses a new sharing URL:
--[Suriyaa Sundararuban](https://about.suriyaa.tk/)
> Use the latest YouTube share URL

- readthedocs/core/utils/tasks/public.py
- readthedocs/restapi/views/task_views.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_celery.py
When the task raises an exception there is no way to have a custom result under ``AsyncResult.info``, it will be always the Exception that was risen from inside the task.
Because of that, when the task raises an Exception we are handling it inside the ``run`` method and we add the exception's message into our custom result *without marking* the task as FAILURE.
Celery docs: http://docs.celeryproject.org/en/latest/reference/celery.result.html#celery.result.AsyncResult.info
Workaround to #4077
> Now, if you revoke the RTD app in your Github service, you will see a nice error message
> Handle raising exceptions from PublicTask

- docs/issue-labels.rst
A few things I've wanted as I do PM, plus some changes for later automation via
probot:
* Drop `Enhancement` -- it vaguely implies "new feature"
* Instead use `Feature` for new **accepted** and on our roadmap features
* If an issue doesn't describe a bug, and is not a new feature, it's likely an
Improvement. The distinction here is `Feature` is a new feature, `Bug`
has higher priority than `Improvement`
* `Needed: more information` is a way to track issues that require a reply and
can be closed if we don't get that reply. Currently, we use this in some
places as a way to describe issues that we need to collect more ideas on --
a good substitute is `Needed: design decision`
* Also add `Status: stale` for issue automation
* Drop unused statuses for closed issues
* Drop PR: ready as this is …
> Updates to our triage guidelines

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
Replacement of https://github.com/rtfd/readthedocs.org/pull/4213 Depends on https://github.com/rtfd/readthedocs-sphinx-ext/pull/43 Closes https://github.com/rtfd/readthedocs.org/issues/3393
I need to add some tests and test manually.
> Add feature to build json with html in the same build

- readthedocs/core/static-src/core/js/doc-embed/constants.js
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This changes the prioritization of ads requested from the client.
- Lower priority of sidebar placement if it would be below the fold
- The above will automatically increase the priority of footer ads relatively
- Increase the priority of a mobile text-only ad when on mobile
These priority changes only affect the choice of an ad within a flight of ads from the same advertiser. The flight will still be chosen based on the targeting criteria and probabilistically on how many clicks/views are needed to fill the ad buy.
> Prioritize ads based on content

- readthedocs/config/find.py
- readthedocs/config/parser.py
- readthedocs/config/tests/test_find.py
- readthedocs/config/tests/test_parser.py
- readthedocs/config/tests/test_utils.py
- readthedocs/config/tests/utils.py
I'm not sure if I'm doing this in the proper way, hopefully it's a start.
> Move parser tests from rtd-build repo

- requirements/pip.txt
> Downgrade docker to 3.1.3 because of timeouts in EXEC call

- README.rst
It looks like they moved off of pocoo.org and onto their own domain, so figured it would be best to follow.
> Update the sphinx-doc.org links in README

- docs/faq.rst
- docs/guides/index.rst
- docs/guides/specifying-dependencies.rst
The original PR got confused about files changes. I cherry picked these from the
history. Hopefully this is most of the changes
Closes #3636
> Add guide for requirements from #3636

- readthedocs/projects/views/public.py
Instead of request.is_secure use settings.PUBLIC_DOMAIN_USES_HTTPS
to find out if we should serve the badge under https or not.
That matches what the resolver is doing and works here.
> projects: serve badge with same protocol as site

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- Fixed breaking change in pip 10.0.0b1 (2018-03-31)
- "--use-wheel" was removed fro pip's cli
> Fixed breaking change in pip 10.0.0b1 (2018-03-31)

- docs/advertising/ad-blocking.rst
- docs/advertising/advertising-details.rst
- docs/advertising/ethical-advertising.rst
- docs/advertising/index.rst
- docs/index.rst
- docs/privacy-policy.rst
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
- Creates a good page for the ad block nag to link to
- Document about going ad-free
- Some advertisers have asked about this
- Stats on ad blocking are interesting - we should publish ours
This moves the `ethical-advertising.rst` and `advertising-details.rst` documents into an `advertising/` folder. After merging this, we should setup redirects.
> Add a page detailing ad blocking

- readthedocs/core/utils/__init__.py
I introduced a bug when doing the rework of trigger_build and prepare_build.
This PR skip the build properly when `Project.skip=True` keeping the same behavior.
> Fix triggering a build for a skipped project

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
It contains a lot of bug fixes http://www.sphinx-doc.org/en/master/changes.html#release-1-7-5-released-may-29-2018
Closes #4208
> Update default sphinx version

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
This reverts commit b6de0c4a52ec082e068bda7dae828ec326e951d8, reversing
changes made to 08beab1f9def7c201845fea894880f7b13da9140.
Ref #4206
This breaks because packages with no binary fail to install. This doesn't seem
to be the functionality that we want. `--use-wheel` used a wheel and backed
down to source packages
> Revert "Merge pull request #4206 from FlorianKuckelkorn/fix/pip-breaking-change"

- readthedocs/config/tests/test_validation.py
- readthedocs/config/validation.py
- readthedocs/rtd_tests/tests/test_build_config.py
- requirements/testing.txt
> Move config module from rtd-build repo

- docs/api/v2.rst
- readthedocs/restapi/views/model_views.py
- readthedocs/settings/base.py
- requirements/pip.txt
This allows the API to be filtered in order to make it more usable. For example:
/api/v2/project/?slug=pip               # retrieve just the Pip project (matches slug exactly or not at all)
/api/v2/version/?project__slug=pip      # retrieve versions for Pip
/api/v2/build/?project__slug=pip        # retrieve builds for Pip
This is built on top of #4274 which documents the API. Only commits starting with https://github.com/rtfd/readthedocs.org/commit/e93d9ed2b0c9cb50a8a0048855fb7a83a0c55716 need to be reviewed separately.
This reverses the changes in #2635 and #2903 and re-introduces `django-filter`. It uses some very limited filters where there are definitely indexes (slug) so performance should be decent.
> API filtering improvements

- readthedocs/search/documents.py
- readthedocs/search/tests/test_views.py
- readthedocs/templates/search/elastic_search.html
#4211 made the search case insensitive. This PR adds tests for it so it does not get broken while implementing #4266 
This fix #2328 #2013 
@ericholscher r?
> [Fix #2328 #2013] Refresh search index and test for case insensitive search

- readthedocs/templates/401.html
- readthedocs/templates/404.html
- readthedocs/templates/500.html
- readthedocs/templates/base.html
This block is override in error pages to be none and do not show notifications on these pages.
Related work in corporate site https://github.com/rtfd/readthedocs-corporate/pull/356
> Wrap notifications HTML code into a block

- readthedocs/doc_builder/backends/sphinx.py
The idea is to put emphasis on the fact that conf.py.tmpl is key as extension point for people running the platform.
> doc_builder: clarify sphinx backend append_conf docstring

- readthedocs/profiles/views.py
- readthedocs/settings/base.py
- readthedocs/templates/profiles/private/advertising_profile.html
- Makes it more obvious that a user won't see ads when they are a donor
- Give donors an easy way to stay logged in for longer (3 months)
> Allow staying logged in for longer

- docs/webhooks.rst
Fix for Issue #4282; docs-only change.
> Remove self-referencing links for webhooks docs

- docs/development/standards.rst
- package.json
This makes a few changes to how our static assets are built that fixes some version incompatibility issues.
* Run `gulp` through an NPM script which ensures that the version from `node_modules/.bin/` is used
* Upgrade vinyl and gulp-uglify
After pulling these changes, you'll need to run 
$ npm install               # updates dependencies
$ npm run build             # outputs compiled files
After running this, `git status` should show the following as modified (at least):
modified:   readthedocs/builds/static/builds/js/detail.js
modified:   readthedocs/core/static/core/js/readthedocs-doc-embed.js
modified:   readthedocs/core/static/core/js/site.js
modified:   readthedocs/gold/static/gold/js/gold.js
modified:   readthedocs/projects/static/projects/js/import.js
modified: …
> Fix issues building static assets

- conftest.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_config_wrapper.py
- readthedocs/rtd_tests/tests/test_core_tags.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
- readthedocs/rtd_tests/tests/test_domains.py
- readthedocs/rtd_tests/tests/test_middleware.py
- readthedocs/rtd_tests/tests/test_notifications.py
- readthedocs/rtd_tests/tests/test_oauth.py
- readthedocs/rtd_tests/tests/test_post_commit_hooks.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_project_forms.py
- readthedocs/rtd_tests/utils.py
- readthedocs/search/tests/test_views.py
This PR allows us to import the community test suite under the corporate test suite and extend them as well as skip some test cases that are specific for the community site and we don't need in the corporate project.
Related https://github.com/readthedocs/readthedocs-corporate/pull/329
Related https://github.com/readthedocs/readthedocs-corporate/pull/330
> Make tests extensible from corporate site

- readthedocs/core/management/commands/clean_builds.py
- readthedocs/core/management/commands/reindex_elasticsearch.py
- readthedocs/core/management/commands/update_repos.py
Adding arguments via `option_list` was deprecated in django 1.8 and it is removed en django `1.10`
https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#django.core.management.BaseCommand.option_list
Raised in https://github.com/rtfd/readthedocs.org/pull/4319#issuecomment-401957275
> Fix deprecations in management commands

- .travis.yml
- tox.ini
Gulp doesn't need to be globally installed or the PATH tweaked in order to run `eslint` tests. The NPM scripts will use the correct gulp installed as part of `npm install`.
> Use "npm run lint" from tox

- conftest.py
- readthedocs/restapi/urls.py
- readthedocs/search/api.py
- readthedocs/search/documents.py
- readthedocs/search/faceted_search.py
- readthedocs/search/filters.py
- readthedocs/search/pagination.py
- readthedocs/search/serializers.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/utils.py
- readthedocs/search/views.py
- readthedocs/urls.py
This is the first etaration of making a API for Documentation Search. Its not finalized yet and the work is not finished yet.
Need more work on highlighting as well as test.
Needed to do some refactor to keep it DRY.
@ericholscher Can you look for a slight review?
> [fix #4265] Port Document search API for Elasticsearch 6.x

- docs/versions.rst
We don't take into account if the version is active. And we can't do that, this would break existing projects that only have `stable` and `latest` activated.
Closes #4305
> Calrify docs about how rtd select the stable version

- readthedocs/core/management/commands/update_repos.py
This fix an error introduced in https://github.com/rtfd/readthedocs.org/pull/4321/files#r200705086
From django:
> Now that management commands use argparse for argument parsing, all arguments are passed in **options by default, unless you name your positional arguments to args (compatibility mode). You are encouraged to exclusively use **options for new commands.
This is the only command that I found using `args`, so the others should be fine.
> Fix error in command

- readthedocs/projects/views/public.py
Without a protocol users can't copy/paste the badge generated code anymore. Fixes #4337.
Is there a better solution?
Reverts rtfd/readthedocs.org#4228
> Revert "projects: serve badge with same protocol as site"

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/projects/models.py
This adds a feature flag (default off) that changes how `html_context` variables are clobbered in `conf.py`. By default, we clobber whatever the user may have in `html_context` if it matches variable names set by Read the Docs. This changes the setting to respect what a user may have and only overwrite if the user didn't set anything.
> Do not overwrite sphinx context variables feature

- readthedocs/analytics/utils.py
This is a workaround for a [bug in the GA measurement protocol](https://issuetracker.google.com/issues/35353093). Specifically it causes events to only show up in real-time reports and not regular reports.
As a result of this workaround, there will be no handling of session data and all users will be treated as "new" as opposed to returning. Another possible workaround is to use the [`cid` parameter](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid) which would involve constructing a deterministic UUID.
> Remove the UID from the GA measurement protocol

- readthedocs/core/static-src/core/js/doc-embed/search.js
This fixes #4265 
I have ported the existing search javascript in order to work with the new Restful search API. The API   has been implemented in #4309.
@ericholscher @davidfischer r?
> [Fix #4265] Porting frontend docsearch to work with new API

- readthedocs/rtd_tests/tests/test_config_integration.py
Use `__init__.py` instead of `urls.py` since the init file is more likely to exist than the other one.
This is required to import these tests into the corporate site where the `urls.py` doesn't exist and all these tests fail because of that.
> Adapt YAML config integration tests

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
This helps us to filter different kind of random/unhandled errors by tags and make debugging easier.
> More tags when logging errors to Sentry

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/projects/models.py
- readthedocs/restapi/serializers.py
- readthedocs/rtd_tests/tests/test_api.py
There was an issue with the previous fix in https://github.com/rtfd/readthedocs.org/pull/4329 which resulted in builders trying to access the database (`project.gold_owners.exists` makes a query). The builders don't have access to the database so this was a problem. Instead, this returns a `show_advertising` field on the API which checks both `project.ad_free` and `project.gold_owners.exists`.
The end result is that ad-free projects -- whether marked ad-free at the database level or because they have a Gold sponsor -- should not show the ad-block nag.
Fixes #4218
> Do not access database from builds to check ad-free

- readthedocs/doc_builder/config.py
- readthedocs/rtd_tests/tests/test_doc_building.py
This was introduced in #4298. I can't replicate this locally (I think this is something to do with the builds being executed in another server). But debugging this I think I found the problem.
Before #4298 the `requirements_file` wasn't validated, but now it is. For the validation, we use the dir name of the `source_file`. This was `''` (empty/cwd). To fix this I'm passing the full `source_file` as the checkout path of the build.
This only affects people using the web interface to set the requirements file.
As workaround users can use a configuration file to set the `requirements_file` setting
Fix #4378
> Set full `source_file` path for default configuration

- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_api.py
This correctly initializes and tests the APIProject proxy model with respect to ad-free projects.
- Correctly set ad-free status based on data in the API response
- Adds a pretty minimal test for initializing the APIProject proxy models
Related to #4387
This has been edited...
> Fix a proxy model bug related to ad-free

- readthedocs/analytics/utils.py
This almost reverts #4347 but is slightly different as it sends a client ID instead of a user ID.
Google's [documentation](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid) says that the client ID should be a UUID but in my testing and in Google's own JavaScript implementation this works without that being the case.
> Add client ID to Google Analytics requests

- docs/advertising/ad-blocking.rst
Links to specific steps to allow Read the Docs ads on specific ad blockers.
Fixes #4405.
> Add steps for individual ad blockers

- readthedocs/__init__.py
- readthedocs/analytics/tasks.py
Allow to use the `get_version` util by passing a path to a standard `setup.cfg` file instead of guess it as a relative path from current `__file__`.
> Make `get_version` usable from a specified path

- docs/getting_started.rst
All of docs.writethedocs.org gives access denied, but the content can be found at www.writethedocs.org
Someone with contacts at writethedocs.org should recommend they redirect docs to www in addition though; there's probably lots of other links out there.
> Fix broken link

- readthedocs/settings/base.py
- readthedocs/settings/dev.py
- readthedocs/ssh/__init__.py
- readthedocs/ssh/apps.py
- readthedocs/ssh/migrations/0001_initial.py
- readthedocs/ssh/models.py
- requirements/pip.txt
FIELD_ENCRYPTION_KEY could be a list to support key rotation. This commit adds one as example, but the production value is stored in a private repository.
Based on #4303
> Encrypt SSHKey.private_key database field

- readthedocs/core/management/commands/update_repos.py
Fixes a bug introduced in https://github.com/rtfd/readthedocs.org/pull/4345#discussion_r202524210
> Check for 'options' in update_repos command

- readthedocs/projects/views/public.py
- readthedocs/templates/search/elastic_project_search.html
This was missed from our intial stage while we port our search infra to Elasticsearch 6.x
Its similar to the File Search that we ported in #4211
Its needed to be merged before we deploy new search to production.
This fixes #4407. @ericholscher r?
> [Fix #4407] Port Project Search for Elasticsearch 6.x

- docs/api/v1.rst
- readthedocs/api/base.py
This PR cleans up a few fields that should not be in our API. It is a backwards incompatible change to the API but I believe a good one. Nobody should be accessing this data.
> API v1 cleanup

- docs/api/v2.rst
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_api.py
This allows making an API requests like:
* http://localhost:8000/api/v2/version/?project__slug=pip&active=true
* http://localhost:8000/api/v2/version/?project__slug=pip&active=false
I believe performance should be ok given this is just a boolean field.
> Allow filtering versions by active

- readthedocs/api/client.py
- readthedocs/restapi/client.py
- requirements/pip.txt
This allows us to use a production internal loadbalancer without forcing
`readthedocs.org` resolves to the internal loadbalancer.
> Add SNI support for API HTTPS endpoint

- docs/alternate_domains.rst
This updates our documentation with mentions that we provision SSL certificates and the Cloudflare limitation users encountered in #4395.
> Update alt domains docs with SSL

- readthedocs/core/resolver.py
- readthedocs/projects/admin.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_resolver.py
- readthedocs/templates/projects/domain_form.html
This allows users to mark a domain as HTTPS and then all links to its documentation will be HTTPS links instead of HTTP links.
Personally I don't love these changes to the resolver but I believe the resolver needs a larger refactor for performance reasons anyway (https://github.com/rtfd/readthedocs.org/issues/3712). If there's a better way to add this functionality without adding more SQL queries and degrading performance of a very performance sensitive bit of code, please let me know or feel free to add to this.
Fixes https://github.com/rtfd/readthedocs.org/issues/2236
> Allow enforcing HTTPS for custom domains

- readthedocs/api/client.py
- readthedocs/restapi/client.py
We made a mistake using `HostHeaderSSLAdapter` even when the connection wasn't HTTPS (in dev, that is). This causes problems connecting to the API.
Fixes #4494
> Only use HostHeaderSSLAdapter for SSL/HTTPS connections

- docs/alternate_domains.rst
The SSL certificate issuing takes about one hour in this case according to comment in #2652.
> Document expected delay on CNAME change and need for CAA

- readthedocs/core/static-src/core/js/doc-embed/constants.js
- readthedocs/core/static-src/core/js/doc-embed/footer.js
- readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
- readthedocs/core/static-src/core/js/doc-embed/sphinx.js
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This will allow showing ads on "alabaster-like" themes which includes the pallets themes. It also no longer handles celery as a special case but as another "alabaster-like" theme.
To test on pallets themes you can:
- Create a local project from the repo https://github.com/pallets/flask/tree/rtd (use `rtd` branch and Python3)
- Build the docs
- Load the docs and verify that ads are present (assuming you have the ad code)
> Support ads on pallets themes

- docs/alternate_domains.rst
- readthedocs/templates/projects/domain_list.html
For some users with older custom domain setups (eg. CNAME to `readthedocs.org`), we were not able to issue a certificate for them. While the request to issue certificates retries for a long time, it has been a couple weeks now and they have timed out.
My goal with this PR is to notify those users that they need to re-request a certificate -- by saving the domain object -- in order to get one. Likewise, after #4483 we show the status of the domain on the domain edit screen and I want users to see that which might help uncover issues (eg. CAA, incorrect setup, time out).
Lastly, since things have changed I added a link to the docs from the domain edit screen. This should be removed in the near future (October-ish).
> Custom domain clarifications

- media/css/badge_only.css
- media/css/sphinx_rtd_theme.css
- media/font/fontawesome_webfont.eot
- media/font/fontawesome_webfont.svg
- media/font/fontawesome_webfont.ttf
- media/font/fontawesome_webfont.woff
- media/fonts
- media/javascript/jquery/jquery-2.0.3.min.js
- media/javascript/jquery/jquery-migrate-1.2.1.min.js
- media/javascript/jquery/jquery-ui-1.8.24.custom.min.js
- media/javascript/readthedocs-doc-embed.js
- media/javascript/underscore.js
- readthedocs/core/static.py
- readthedocs/settings/base.py
This doesn't change the STATICFILES_ROOT yet, in an attempt to avoid making any
breaking changes. This is a port of #4489 that we'll merge before azure
migration
> Use collectstatic on `media/`, without collecting user files

- requirements/pip.txt
Note! These packages occupy the same namespace. You might need to uninstall
`mimeparse` and reinstall `python-mimeparse`.
Refs #3570 
The old package `mimeparse` is not py3 compatible, but `django-mailgun` brings in it's own dependency of `python-mimeparse`, which is py3 compatible. This might not affect our RS cluster, but does affect our Azure cluster. Actions required on our Azure cluster were to manually remove `mimeparse` and install `python-mimeparse`, as these packages are forks and provide the same namespace. We aren't upgrading the `django-mailgun` package here though, so might not be required for RS deployments.
> Replace old mimeparse package with python-mimeparse

- readthedocs/templates/projects/project_edit.html
While at it use context instead of a comment for translation
context on another string.
> templates: mark missing string for translation on project edit

- .travis.yml
The CI process is a little slow, even sometimes it fails because of timeout downloading node packages. A downside of this change: we need to remember to clear the cache if there is a change in js dependencies (which is not so common).
> Cache node_modules to speed up CI

- readthedocs/templates/core/project_list_featured.html
- readthedocs/templates/homepage.html
This is similar to #4524,
where resolving a ton of URL's for versions is time consuming.
This caches the features projects list on the homepage.
> Performance improvement: cache version listing on the homepage

- docs/advertising/ethical-advertising.rst
This actually didn't change how the ads work. It just clarifies disabling them on a per-project basis.
> Slight clarification on turning off ads for a project

- readthedocs/templates/base.html
Due to changes in our `collectstatic` since the original sponsor images PR #4424, the paths were not correct. Also, don't start `{% static %}` with a `/` character.
Related to #4489, #4502.
> Fix the sponsor image paths

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This improves our ad block detection to avoid any false positives that would show the ad block nag.
When the ad fails to load, we add an element which we can detect whether it is visible.
Fixes #4402.
> Improved ad block detection

- requirements/deploy.txt
This is prod only, and is out of date. This dependency is handled by our
provisioning.
> Remove mailgun from our dependencies

- readthedocs/core/static.py
- readthedocs/settings/base.py
Reverts rtfd/readthedocs.org#4520
I believe this is in fact still required, as otherwise we get static collect of `media/{epub,pdf,json,htmlzip}`
> Revert "Remove SelectiveFileSystemFolder finder workaround"

- CHANGELOG.rst
We had a quick fix in place for our changelog for 2.6.3 due to a bug in the changelog script. This adds the missing changelog entries.
> Fix changelog for 2.6.3

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/rtd_tests/tests/test_doc_builder.py
- readthedocs/settings/base.py
- readthedocs/templates/core/email/base.html
This PR cleans up a few areas that were using `MEDIA_URL` but really should be using `STATIC_URL` after #4489. The old URL will work but will result in a redirect which slows things down and results in an extra hit.
> Use the STATIC_URL for static files to avoid redirection

- docs/builds.rst
Describe each docker image used to build the docs
ref to https://github.com/rtfd/readthedocs.org/pull/4419#discussion_r204810381
> Update docs about build process

- docs/builds.rst
This PR should resolve #4507. As per #4231, builds fail with mkdocs when markdown files are not in a `doc` or `docs` directory. The `mkdocs.yml` could either be in the root or in the `docs` directory, as per https://www.mkdocs.org/about/release-notes/#stricter-directory-validation and my own testing within my own project. 
I was able to solve this issue by moving my `mkdocs.yml` and relevant markdown files to a `docs` directory. I also tested this with a `doc` directory, see this closed [PR](https://github.com/AumitLeon/module_starter_cli/pull/32) in my project. I think it makes sense to have the docs reflect this so future users know to have their files in the correct directory.  
Of course, this doesn't solve the issue of builds failing when files are at the root, but users should be …
> Update information on mkdocs build process

- readthedocs/projects/tasks.py
If an exception is raised before run_setup has been called we try to update the setup_env that is not here.
```
File "/readthedocs/projects/tasks.py", line 313, in run
self.version = self.get_version(self.project, version_pk)
File "/readthedocs/projects/tasks.py", line 84, in get_version
version_data = api_v2.version(version_pk).get()
File "/lib/python3.5/site-packages/slumber/__init__.py", line 155, in get
resp = self._request("GET", params=kwargs)
File "/lib/python3.5/site-packages/slumber/__init__.py", line 101, in _request
raise exception_class("Client Error %s: %s" % (resp.status_code, url), response=resp, content=resp.content)
slumber.exceptions.HttpNotFoundError: Client Error 404: http://localhost:8002/api/v2/version/868/
During handling of the …
```
> projects: don't explode trying to update UpdateDocsTaskStep state

- readthedocs/gold/templates/gold/projects.html
- readthedocs/gold/templates/gold/subscription_confirm_delete.html
- readthedocs/gold/templates/gold/subscription_detail.html
- readthedocs/gold/templates/gold/subscription_form.html
- readthedocs/templates/account/login.html
- readthedocs/templates/builds/build_detail.html
- readthedocs/templates/core/project_bar_base.html
- readthedocs/templates/core/project_detail_right.html
- readthedocs/templates/homepage.html
- readthedocs/templates/notifications/send_notification_form.html
- readthedocs/templates/profiles/private/advertising_profile.html
- readthedocs/templates/projects/import_basics.html
- readthedocs/templates/projects/import_extra.html
- readthedocs/templates/projects/integration_generic_webhook_detail.html
- readthedocs/templates/projects/integration_webhook_detail.html
- readthedocs/templates/projects/onboard_detail.html
- readthedocs/templates/projects/onboard_import.html
- readthedocs/templates/projects/project_advertising.html
- readthedocs/templates/projects/project_dashboard_base.html
- readthedocs/templates/projects/project_import.html
- readthedocs/templates/security.html
- readthedocs/templates/socialaccount/connections.html
- readthedocs/templates/socialaccount/snippets/provider_list.html
- readthedocs/templates/wipe_version.html
Following what @ewjoachim said in #4471,
> Now I think most of these problems are pretty much stemming from the usage of blocktrans without trimmed, and that makes the translation quite more complex to write. There are some other issues, though.
I updated all our templates to add `trimmed` to all multilines `blocktrans` tag.
~~This PR should be merged before #4478 I suppose, so we don't override the resources twice.~~
> Add `trimmed` to all multilines `blocktrans` tags

- docs/i18n.rst
Update our docs to suggest the usage of `trimmed` option when using `blocktrans` in templates.
Django docs: https://docs.djangoproject.com/en/1.9/topics/i18n/translation/#blocktrans-template-tag
> Example and note with usage of trimmed option in blocktrans

- docs/guides/build-using-too-many-resources.rst
Depends on https://github.com/rtfd/readthedocs.org/issues/4418
Related to https://github.com/rtfd/readthedocs.org/issues/4362#issuecomment-404766625
> More tips about how to reduce resources usage

- readthedocs/core/utils/__init__.py
- readthedocs/rtd_tests/tests/test_core_utils.py
In #4033, I introduce a bug when using Celery signatures.
From Celery's docs at http://docs.celeryproject.org/en/latest/reference/celery.html#celery.signature
> the .s() shortcut does not allow you to specify execution options but there’s a chaning .set method that returns the signature
So, instead of dealing with multiple `.set()`, I'm just using the `.signature()` method of the task which is more explicit.
Ref: https://github.com/rtfd/readthedocs-ops/pull/392#issuecomment-414816823
> Route task to proper queue

- docs/user-defined-redirects.rst
- readthedocs/projects/forms.py
- readthedocs/redirects/models.py
- readthedocs/rtd_tests/tests/test_redirects.py
- readthedocs/templates/projects/project_redirects.html
In #3965 we added the ability to use the `full_path` but it was added only to the first case and it wasn't considered in the case when `$rest` keyword was used.
With these changes we can "deprecate a whole sub-path" by writing a Exact Redirect like this:
``` text
/en/obsolete-version/$rest ->
/en/newest-version/
```
and all links pointing to the `obsolete-version` at any sub-path will be redirected to the newest docs.
Closes #4029
Closes #2444
Closes #3794
> Fix Exact Redirect to work properly when using $rest keyword

- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/exceptions.py
- readthedocs/projects/tasks.py
There are some exceptions risen while building documentation that are considered an ERROR from the Build perspective, but for our application are just a WARNING and shouldn't be logged as ERROR (sent to Sentry).
It's not an ERROR in our application but a WARNING that the user's documentation couldn't be built.
This will help us to find Sentry more useful than it's right now as we are getting close to have logged only things that need human/dev attention.
> NOTE: this is the most important commit https://github.com/rtfd/readthedocs.org/pull/4495/commits/1dd850a4e276b4849f45ebe3eabdc17e61be0cc9, the first one is a minimum refactor and the last one introduces some style changes
Closes: #4109
> Mark some BuildEnvironmentError exceptions as Warning and do not log them

- docs/.tx/config
Sync resources from repository (e.g. created/deleted reST doc files) with Transifex configuration.
```
$ tx config mapping-bulk \
--project readthedocs-docs \
--file-extension '.pot' \
--source-file-dir locale/pot \
--source-lang en \
--type PO \
--expression 'locale/<lang>/LC_MESSAGES/{filepath}/{filename}.po' \
--execute
```
After running this command, I searched and replaced `_locale_pot_` by `` (none) to respect the pattern that was used for the resources names. The command, ends with a resource name like:
[readthedocs-docs._locale_pot_embed]
which is replaced to
[readthedocs-docs.embed]
If this PR is approved, we need to run the following command to sync the resources into Transifex:
$ tx push --source
Transifex Docs: https://docs.transifex.com/client/config#configuring-multiple-local …
> Update Transifex resources for our documentation

- docs/yaml-config.rst
> Document python.use_system_site_packages option

- readthedocs/doc_builder/environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
PostgreSQL doesn't support NULL (\x00) characters on TextFields.
Django 2.0 introduces a new validator that doesn't allow NULL characters to reach the database:
https://code.djangoproject.com/ticket/28201
This commit just replaces the NULL characters of the stdout and stder from the command ran by '' (empty string) to avoid conflicts when saving them into the database.
Closes #3900
> Sanitize BuildCommand.output by removing NULL characters

- docs/builds.rst
This is a docs only change to recommend specifying the version of mkdocs or sphinx used.
> Add a note about specifying the version of build tools

- docs/faq.rst
rst doesn't support nested elements, it renders in a weird way
> Fix nested syntax in docs

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
> Fix incorrect reraise

- requirements/deploy.txt
This might be the cause of our random celery disconnects.
Refs https://github.com/celery/celery/issues/2606#issuecomment-413274023
> Remove hiredis

- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/rtd_tests/tests/test_project_views.py
- Serves badges directly without a redirect
- Attaches the cache control header directly to the response as GitHub doesn't respect the cache-control headers on a redirect. GitHub only respects the cache-control header on the 2xx response.
- A bit of code simplification
This solves an issue that arose because the badges need to be explicitly not cached or have a very short cache TTL. When no cache-control headers are present (as on [this badge](https://assets.readthedocs.org/static/projects/badges/passing-flat.svg) for example), sometimes other intermediaries -- github in this case -- cache it too long. This PR keeps the cache rules and the response together in the code so this problem doesn't arise again like it did previously in https://github.com/rtfd/readthedocs.org/issues/3323. …
> Serve badges directly from local filesystem

- readthedocs/vcs_support/backends/git.py
Maybe this is not the best solution ever since we may be skipping other cases also since I'm catching the `ValueError` exception (too general) but initially we want to skip them, log and continue building.
Closes #4440
> Skip tags that point to blob objects instead of commits

- readthedocs/config/tests/test_config.py
- readthedocs/config/tests/test_parser.py
The problem was already fixed with the refactor, but anyway I want to add these tests.
Closes #2813
> Port https://github.com/rtfd/readthedocs-build/pull/38/

- readthedocs/config/tests/test_config.py
Ref to https://github.com/rtfd/readthedocs.org/pull/4461#discussion_r213152317
So, this was caused because the PR was outdated, makes me think if we could do better to prevent this. What about requiring the PRs to be updated before merging to master? Now GitHub supports a button to update the PR from the web, so the process isn't slow, but we will need to wait to the tests to pass again with the new merge, for simple PRs this can be a little overkill, but in general, I think this is a sane check
> Update tests failing on master

- readthedocs/core/signals.py
- readthedocs/core/tests/test_signals.py
Fixes #4576 
The query was limiting the users before annotation because of django's backward relation query. the Documentation of django does not provide much information about it, but I have gone through the differentiate of the sql query and found the root cause.
I have also added tests for this so it should not happen again. I should have written the tests when I implemented the feature in #3214.
@agjohnson @humitos r?
> [Fix #4576] Do not delete projects which have multiple users

- readthedocs/config/tests/test_config.py
It has https://github.com/rtfd/readthedocs.org/pull/4584# as base, close #4586
> Tests for yaml file regex

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
Otherwise it found files like:
.hg/store/data/readthedocs.yml.i
Closes #4583
> Add start and termination to YAML file regex

- readthedocs/templates/homepage.html
Previously it was using the first language that hit the page to cache.
Fixes #4582
> Respect user language when caching homepage

- readthedocs/doc_builder/environments.py
In #4552 I fixed this for LocalBuildEnvironment but I forget to do exactly the same for Docker. This is what this commit does.
Closes #3900
> Sanitize command output when running under DockerBuildEnvironment

- readthedocs/core/views/serve.py
- readthedocs/rtd_tests/tests/test_redirects.py
When a version exists and is inactive, we return 404 instead of 401 so our redirect system can be used for these versions.
We only return 401 when the reader has no permission to read the version (active and private).
Closes #4598
> Return 404 for inactive versions and allow redirects on them

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- readthedocs/rtd_tests/tests/test_resolver.py
Argument ``require_https_domain`` added to force the resolver to use https URLs with PUBLIC_DOMAIN when the Domain is not https.
I found this while running tests on Corporate site since we don't serve documentation over plain HTTP there. So, we need a way to force the https protocol even when the project has a Domain object (but https=False). In this case, we force to use our PUBLIC_DOMAIN URL over HTTPS.
> Force resolver to use PUBLIC_DOMAIN over HTTPS if not Domain.https

- .travis.yml
- readthedocs/builds/models.py
- readthedocs/core/resolver.py
- readthedocs/core/views/hooks.py
- readthedocs/core/views/serve.py
- readthedocs/doc_builder/base.py
- readthedocs/doc_builder/environments.py
- readthedocs/gold/forms.py
- readthedocs/notifications/notification.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/projects/validators.py
- readthedocs/projects/version_handling.py
- readthedocs/projects/views/public.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/wsgi.py
- requirements/deploy.txt
- requirements/lint.txt
- requirements/pip.txt
- requirements/testing.txt
As usual, upgrade all python packages from all requirements.
Just to know where we are regarding package versions and consider upgrade them if all test and manual QA pass.
``` shell
for reqs in `ls requirements`;
do pur --skip django-tastypie,django,docker,elasticsearch,pyelasticsearch,commonmark,stripe,djangorestframework,mkdocs,django-allauth --requirement requirements/$reqs; 
done
```
> Upgrade all packages using pur

- readthedocs/gold/forms.py
This PR fixes a bug that could result in a user having multiple gold subscriptions.
I am also going to go back through our gold subscriptions and find any users that have more than 1 subscription as that is likely an error.
Fixes #4595
Fixes #4503
> Fixes an issue with duplicate gold subscriptions

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This fixes an issue with the ad nag where a project is sponsored and the user runs an ad blocker. We know whether a project is ad-free when we build it and we should never show the nag on a sponsored project.
This partially resolves the nag issue in #4595 (I purposefully worded this to not auto-close that issue).
#4329 did not quite correctly fix this issue.
> Fix ad block nag project issue

- docs/guides/remove-edit-buttons.rst
This is not a real solution, but currently this is the only way of doing this.
Related: #4544
> Docs for hidding "On ..." section from versions menu

- docs/contribute.rst
Refs to https://github.com/rtfd/readthedocs.org/issues/2673#issuecomment-398149984 and https://github.com/rtfd/readthedocs.org/pull/4180/
> Update docs to match the new triague guidelines

- readthedocs/restapi/views/model_views.py
- readthedocs/restapi/views/task_views.py
We are catching exceptions of type `Exception`, which no always have the `message` attribute (python3 at least).
```python
e = Exception('Bu!')
assert not hasattr(e, 'message')
```
> Use str to get the exception message

- readthedocs/restapi/urls.py
We already have logic that checks for readthedocsext import availability
when adding to INSTALLED_APPS, so checking here for import availability
isn't correct. For instance, on the readthedocsinc side, we remove
`readthedocsext.donate` from INSTALLED_APPS inherited from
settings.base, but urls.py would import the module, add the URLs (for
packages that aren't in INSTALLED_APPS anymore), and things broke.
> Make restapi URL additions conditional

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
We were assuming this path before, which defaulted to the path you
executed django from on the host machine. The cwd was used in commands
run on inside Docker however. On Linux dev environments, this path is
most likely missing.
By specifying paths, we will get paths that have been created inside the
container.
> Add cwd to subprocess calls

- readthedocs/projects/tasks.py
- readthedocs/search/management/commands/reindex_elasticsearch.py
- readthedocs/search/tasks.py
- readthedocs/search/utils.py
@ericholscher It should fix the search indexing!
> fixing the indexing

- readthedocs/config/config.py
> Use validate_dict for more accurate error messages
