docs/builds.rst

Fix incorrect reference to Sphinx in Mkdocs section

Sphinx => Mkdocs

---

readthedocs/projects/tasks.py

```shell
$ python ./manage.py update_repos
```
Works better now. :+1:

Add back update_repos_pull

---

.gitignore
MANIFEST.in

added MANIFEST and update .gitignore

added MANIFEST and update .gitignore

---

docs/builds.rst
docs/locale/da/LC_MESSAGES/api/projects.po
docs/locale/da/LC_MESSAGES/builds.po
docs/locale/en/LC_MESSAGES/api/projects.po
docs/locale/en/LC_MESSAGES/builds.po
docs/locale/es/LC_MESSAGES/api/projects.po
docs/locale/es/LC_MESSAGES/builds.po
docs/locale/fa/LC_MESSAGES/api/projects.po
docs/locale/fa/LC_MESSAGES/builds.po
docs/locale/it/LC_MESSAGES/api/projects.po
docs/locale/it/LC_MESSAGES/builds.po
docs/locale/ja/LC_MESSAGES/api/projects.po
docs/locale/ja/LC_MESSAGES/builds.po
docs/locale/nb/LC_MESSAGES/api/projects.po
docs/locale/nb/LC_MESSAGES/builds.po
docs/locale/pt_BR/LC_MESSAGES/api/projects.po
docs/locale/pt_BR/LC_MESSAGES/builds.po
readthedocs/projects/models.py

I tried to leave those instances alone where the capitalization would affect the build process (variable names, make targets, etc.). Please let me know if there's anything else I can do :)

Fix LaTeX capitalization where appropriate

---

docs/api.rst

make code python3 compatible,
Update auth kwarg of slumber to work with latest version.
-- 
I know there is API v2 in progress, I just think it is worth updating that in the meantime. 
Some pointer on how to use API v2 would be appreciated too.

Some update to API v1 docs.

---

requirements/pip.txt

Submitting a change to the URL for the bamboo_boy module based on the discussion in #1245

Fixing Git URL for bamboo_boy requirement

---

readthedocs/projects/tasks.py
requirements/pip.txt

Refs #1187, refs #1214, refs #1164

Pin Sphinx to v1.3.1

---

readthedocs/projects/tasks.py

I have performed a slight `setup_environment` task refactoring to improve the readability of code and simplify the change of requirements in the future.

A slight refactoring of "setup_environment" task

---

readthedocs/projects/tasks.py
requirements/pip.txt

Bump MkDocs to 0.13.3

---

readthedocs/doc_builder/backends/mkdocs.py

This might fix #1294, I am not sure how to get to a point of testing it locally since it seems to be happening due to some broken artifacts remaining that I don't have.
Either way, at worst it will just remove a bunch of stale files across MkDocs that are not used.

Perform clean builds with MkDocs

---

media/css/core.css
readthedocs/templates/search/elastic_search.html

Add Elastic as a sponsor.

---

readthedocs/core/middleware.py
readthedocs/rtd_tests/tests/test_middleware.py

This should fix issue [1366](https://github.com/rtfd/readthedocs.org/issues/1366)

lowercase domain name in middleware.py

---

readthedocs/builds/constants.py
readthedocs/builds/models.py
readthedocs/builds/utils.py
readthedocs/core/management/commands/clean_builds.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/privacy/backend.py
readthedocs/projects/signals.py

Fixing "edit on github" links for stable version builds.

---

docs/getting_started.rst

Spelling correction

---

readthedocs/builds/migrations/0025_add_indexes.py
readthedocs/builds/models.py

This is a query that we see a lot of database contention on, it should have
indexes to speed up lookups.
ACHTUNG!
This migration will cause a reindex on a large table, be prepared for database downtime as this alter will be blocking.

Add indexes to builds table

---

readthedocs/core/templatetags/core_tags.py
readthedocs/projects/models.py
readthedocs/templates/core/project_detail_right.html

I believe this will create the relative link we want to see.  #1009

Fix language links on cname projects

---

docs/custom_installs/local_rtd_vm.rst
fabfile-development.py

Forgot to update these bits in #1420

Update syncdb mentions in codebase to be migrate

---

gulpfile.js

Change gulpfile execution of django project

---

gulpfile.js

Watch all js/css in static-src, not just entry points

Fix gulpfile watch logic issue

---

docs/api/bookmarks.rst
docs/api/builds.rst
docs/api/core.rst
docs/api/doc_builder.rst
docs/api/projects.rst
docs/api/vcs_support.rst
docs/conf.py

Accommodating changes from #1496 in the API documentation.

Change docs import path and prefix APIs with readthedocs namespace

---

readthedocs/core/subdomain_urls.py

Related to #1496.
Revealed by pylint.

Fix "from urls import ..." -> "from readthedocs.urls import ..."

---

readthedocs/projects/tasks.py

The reason for this is that old versions which had PDF builds in the past and
for which the PDF builds have been disabled will keep the stale PDF of old
builds lying around. We need to delete the artifacts if they exist and are
disabled for the current build.
Addresses https://github.com/rtfd/readthedocs.org/pull/1431#issuecomment-120998189

Delete pdf/epub artifacts when their build is disabled

---

readthedocs/core/management/commands/pull.py
readthedocs/core/views.py
readthedocs/urls.py

We already have proper monitoring in place and don't need those anymore.
Fixes #1515.

Remove celery debugging/montioring views

---

readthedocs/cdn/purge.py
readthedocs/projects/admin.py
readthedocs/projects/migrations/0003_project_cdn_enabled.py
readthedocs/projects/models.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/files/test.html
readthedocs/rtd_tests/tests/test_imported_file.py

This is to enable CDN on projects on Read the Docs.

Track md5 of ImportedFiles

---

gulpfile.js
readthedocs/core/static-src/core/js/autocomplete.js
readthedocs/core/static/core/js/autocomplete.js
readthedocs/gold/forms.py
readthedocs/gold/models.py
readthedocs/gold/templates/gold/projects.html
readthedocs/gold/templates/gold/register.html
readthedocs/gold/urls.py
readthedocs/gold/views.py
readthedocs/rtd_tests/tests/test_gold.py

This is the basic UI required for allowing Gold users
to bless projects with special features.
This will be required for CDN, Analytics,
and other things that would destroy our servers if
we enabled them for all our traffic.

Add views/forms for adding & editing Gold projects

---

readthedocs/core/management/commands/archive.py
readthedocs/core/utils/__init__.py
readthedocs/doc_builder/backends/mkdocs.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/restapi/views/footer_views.py

This is new in Django 1.8: https://docs.djangoproject.com/en/1.8/releases/1.8/#cleanup-of-the-django-template-namespace

Just straight dicts, not Context’s for django Templates

---

readthedocs/projects/views/public.py

Remove unused media_url_prefix from project_downloads template context

---

README.rst
readthedocs/projects/views/public.py

Link to documentation from badge instead to project page

---

readthedocs/core/views.py
readthedocs/redirects/utils.py
readthedocs/rtd_tests/tests/test_redirects.py
readthedocs/rtd_tests/tests/test_redirects_utils.py

#1025 mentions that the redirects do change the domain. IMO the domain and language and version should stay the same.

Keep domain when redirecting

---

readthedocs/builds/views.py
readthedocs/templates/builds/build_detail.html

Drop initial build detail output serialization in favor of API

---

readthedocs/core/middleware.py
readthedocs/rtd_tests/tests/test_middleware.py

Fixed issue with PRODUCTION_DOMAIN having more than 2 url parts

---

readthedocs/projects/tasks.py

This ensures cleanup of ssh keys/agents on private repositories

Ensure after_vcs signal is called even after cloning fails

---

requirements/deploy.txt
requirements/pip.txt

redis/hiredis is not available on Windows

Move hiredis cache to deploy configuration

---

media/robots.txt

fix(robotstxt): Remove invalid Allow property from robots.txt.

---

readthedocs/core/views.py

Move logic to queryset, only should projects with successful last builds

Tune front page query

---

readthedocs/core/models.py
readthedocs/projects/views/base.py
readthedocs/rtd_tests/base.py
readthedocs/rtd_tests/tests/test_project_views.py
readthedocs/settings/base.py
requirements/pip.txt
tox.ini

This fixes some logic around middleware and profiles. Adds some deeper testing
using request factory tests.

Add lookups for users with missing profiles to middleware

---

docs/alternate_domains.rst

Yes, this is a single-character pull request. :)

Fix grammar mistake

---

docs/api.rst
docs/conf.py
requirements/pip.txt

Includes updates to our docs to make them compatible with 1.4

Upgrade docs to Sphinx 1.3.4

---

readthedocs/doc_builder/python_environments.py
requirements/pip.txt

refs #1853, https://github.com/sphinx-doc/sphinx/issues/2189

bump sphinx to 1.3.4

---

readthedocs/doc_builder/python_environments.py
requirements/pip.txt

Fixes #1966 
This just requires testing at this point.

Bump Sphinx to 1.3.5

---

readthedocs/templates/projects/onboard_detail.html

Fixed issue with invalid URL pattern when subdomains are enabled

---

readthedocs/builds/models.py
readthedocs/core/symlink.py
readthedocs/privacy/backend.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_builds.py

This makes symlinks take effect when privacy level on version changes.

Symlink projects on version change.

---

docs/alternate_domains.rst

I'm not an expert in this. Let me know if this should be done in another way.

Documentation. SSL forwarding config for Nginx

---

readthedocs/donate/admin.py
readthedocs/donate/migrations/0005_add-geo-filters.py
readthedocs/donate/migrations/0006_add-geo-data.py
readthedocs/donate/migrations/0007_add-impression-totals.py
readthedocs/donate/models.py
readthedocs/donate/signals.py
readthedocs/donate/tests.py
readthedocs/projects/admin.py
readthedocs/settings/base.py
requirements/pip.txt

This adds the ability to filter by geo's on the promos. Currently just supports country-level filtering. 
This also adds probability-based filtering of promo display. Ones that have more to display today will be displayed at a higher rate than those that don't.

Add geo filtering & probability display.

---

docs/install.rst

This addition is in regarding to #2062: add explanation about python3 for RTD installation.

Add annotation about python3

---

readthedocs/builds/version_slug.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_urls.py

Also handle URL's that don't map properly.

Include upper case URL's in reverse.

---

docs/custom_installs/local_rtd_vm.rst

some additions to get through the installation on debian jessie

Additions to Doc: Local VM Install

---

readthedocs/templates/profiles/base_profile_edit.html

Used for overrides in child templates

Add block around profile nav for overriding

---

readthedocs/core/admin.py

Adds three filters to user projects: project with active versions, project with
built versions, and project with recent builds (in the last year)

Add user admin project filtering

---

readthedocs/settings/base.py

Also removes some random old commented out stuff from settings.

Re-enable django_extensions always.

---

README.rst
docs/alternate_domains.rst
docs/api.rst
docs/automatic-redirects.rst
docs/canonical.rst
docs/conf.py
docs/faq.rst
docs/i18n.rst
docs/localization.rst
docs/single_version.rst
docs/tests.rst
docs/versions.rst

readthedocs.org -> readthedocs.io

Update docs :fireworks:

---

docs/guides/build-notifications.rst
docs/guides/google-analytics.rst
docs/guides/index.rst

This is mainly so that these instructions are more searchable.
It's discoverable in the interface,
but a lot of users never discover it.

Add a guides section with a few basic things.

---

media/css/core.css
readthedocs/templates/base.html

I have added better spacing for the change languages button at the bottom of the home page.
Previous:
Changed:
Its Minor change :smile:. And I really Like RTD.

Better spacing for the button of change language

---

docs/install.rst

Didn't get these on previous pull request

Rest of "generify commands"

---

docs/install.rst

Generify commands so they work on all platforms

---

readthedocs/templates/projects/project_import.html

Add proper GET args to allauth import

---

docs/yaml-config.rst

Was reading the YAML config documentation and ended up fixing some style and layout.

Update YAML config file doc style.

---

media/javascript/analytics.js

Delete unused media/javascript/analytics.js

---

readthedocs/projects/views/private.py
readthedocs/rtd_tests/tests/test_project_views.py

Set Project.tags m2m field when creating a new project

---

readthedocs/doc_builder/backends/mkdocs.py

Don't use a hardcoded domain name in media_url

---

docs/user-defined-redirects.rst

Add details on how to use exact redirects.

Add documentation for Exact Redirects

---

readthedocs/rtd_tests/tests/test_comments.py

Before patch: 42.19 seconds
After patch: 31.37 seconds

Speed up test_comments by using setUpTestData

---

readthedocs/projects/views/public.py

Delete redundant _badge_return() helper

---

readthedocs/rtd_tests/tests/test_footer.py

Before patch: 27.83 seconds
After patch: 25.73 seconds

Refactor test_footer to use DRF infrastructure

---

readthedocs/core/resolver.py
readthedocs/rtd_tests/tests/test_redirects.py

Don't append '.html' to URLs containing fragments

---

readthedocs/donate/models.py
readthedocs/donate/views.py

This allows us to show promos with out an image

Don't put in an image_url if it doesn't exist

---

readthedocs/templates/base.html

Update Django Dash Link

---

readthedocs/doc_builder/backends/mkdocs.py

RE: https://github.com/rtfd/readthedocs.org/issues/2210
RE: https://github.com/rtfd/readthedocs.org/pull/2369

Fix 'media_url'

---

docs/ethical-advertising.rst
docs/index.rst
readthedocs/projects/filters.py

We have views on how to do advertising. Let's write them up.

Add initial stab at a basic ethical advertising page

---

readthedocs/core/views/__init__.py
readthedocs/templates/core/send_email_form.html

This makes the view able to handle non-User objects, for use in messaging users through the admin
on related objects.

Make admin email view more extendable, allow non-User querysets

---

readthedocs/notifications/notification.py
readthedocs/rtd_tests/tests/test_notifications.py

This adds context data for constructing full URIs.

Add prefix URI for notifications in context data

---

docs/getting_started.rst

This blog post really helped me decide between Markdown and reStructuredText. So I think it is really helpful to have here. Sorry for white space noise, my $EDITOR did it.

Add blog post to note.

---

readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py

We're getting non 200/201 responses from GitHub and aren't logging any
information on the failure.

Add debugging to webhook output

---

docs/privacy.rst

I _think_ this content does not have any meaning there and it’s safe to remove it? Or am I missing something?

remove dummy content

---

readthedocs/donate/admin.py

This will make it a bit simpler to change promos from live,
or set larger/smaller impressions on them.

Allow editing of promo attributes in list view

---

docs/vcs.rst

Details for how to integrate with GitHub, Bitbucket or Gitlab.

VCS Integration explained

---

docs/faq.rst

Add a mention to a useful plugin for comments in your documentation.

Mention sphinxcontrib-disqus in the FAQ

---

docs/faq.rst

Fix Google PyGuide link

---

README.rst
docs/index.rst

```console
$ host mercurial.selenic.com
Host mercurial.selenic.com not found: 3(NXDOMAIN)
```

Update Mercurial homepage URL

---

docs/conf.py
docs/development/buildenvironments.rst
docs/doc_extensions.py
docs/settings.rst

Update docker docs

---

docs/index.rst
docs/subprojects.rst

This could be expanded,
but we should at least have a top-level page for it.

Add proper subproject doc page.

---

docs/Makefile
docs/ethical-advertising.rst

This adds a bit more flare into the copy,
and hopefully is easier to scan and understand.

Update the copy on ethical ads.

---

readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/base.py
readthedocs/vcs_support/utils.py

Docstring/PEP 257 fixes for the vcs_support app

---

prospector.yml
readthedocs/bookmarks/views.py
readthedocs/builds/version_slug.py
readthedocs/doc_builder/base.py
readthedocs/privacy/backend.py

Finish PEP 257 cleanup and enable linting in CI

---

requirements/pip.txt

Just removed a dependency which is no longer used.

remove doc2dash

---

prospector-more.yml
readthedocs/vcs_support/backends/__init__.py
readthedocs/vcs_support/backends/bzr.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/backends/svn.py
readthedocs/vcs_support/base.py
readthedocs/vcs_support/utils.py

* Docstrings
* Rename unused vars to `_`
* Delay logging formatting
* Catch a specific exception <- Would love a second set of eyes here

Resolve linting issues in the vcs_support app.

---

prospector-more.yml
readthedocs/settings/dev.py

Resolving linting issues in the settings module.

---

prospector-more.yml
readthedocs/payments/forms.py

Fix lint issues for payments app

---

prospector-more.yml
readthedocs/projects/forms.py
readthedocs/projects/models.py
readthedocs/projects/tasks.py
readthedocs/projects/views/base.py
readthedocs/projects/views/private.py
readthedocs/projects/views/public.py

Due to this lint error:
```
too-many-locals / Too many local variables (16/15) (col 4)
```
...I have attempted to split `UpdateDocsTask.run` into two pieces. Please review carefully.

Fix lint issues for readthedocs.projects app

---

readthedocs/settings/base.py
readthedocs/settings/dev.py

Drop additional unused log files and move logging to the console in development

Fix up development logging

---

requirements/lint.txt

There is currently an issue with 0.12.6 and pydocstyle

Pin prospector to previous minor release

---

readthedocs/doc_builder/python_environments.py

Change - to _ in theme name

---

docs/dmca/index.rst

https://github.com/rtfd/readthedocs.org/issues/3015

Correct typo in DMCA docs

---

readthedocs/templates/core/header.html

This is a simple HTML fix to remove a nested `<ul>`.

Fix a minor HTML issue - ul can't be a child of ul

---

readthedocs/projects/forms.py

Feature.feature -> Feature.feature_id was missed here

Add missing changes to field name in admin

---

docs/guides/adding-custom-css.rst

Just adds a short guide. There might be a better place for this sort of content
later.

Add some docs on adding custom CSS

---

readthedocs/templates/homepage.html

Mention advertisers and sponsors on the homepage in the "supported by" section.

Mention ads and sponsors on the homepage

---

docs/contribute.rst

point to good first issue

---

readthedocs/doc_builder/python_environments.py

This is the latest version included in our feature flag. Moves testing version
to 39.x series

Upgrade setuptools to 37.0.0

---

readthedocs/templates/builds/build_detail.html

* Fix silly template line breaks

Some small fixes:

---

docs/faq.rst

Document why sometimes your docs 404 after a successful build.

---

readthedocs/restapi/views/footer_views.py

Looks like a PR was merged early.

Fix lint error

---

docs/install.rst

This PR resolves #3423 
Adding CentOS/RHEL dependencies
Adding git requirement

Adding to Install Docs

---

readthedocs/settings/base.py

https://docs.djangoproject.com/en/1.11/ref/templates/upgrading/#the-templates-settings

Remove TEMPLATE_LOADERS since it's the default

---

media/css/readthedocs-doc-embed.css

This change is mostly around making our ads more visible and accessible.

Promo contrast improvements

---

readthedocs/templates/homepage.html

I'm not sure how this slipped through. Normally I HTML validate all my submissions but I must have missed it.

Fix an unclosed tag

---

docs/open-source-philosophy.rst

I tried to make a sentence flow and sound a little nicer.

Grammar correction

---

AUTHORS.rst

#3506  
@RichardLitt @ericholscher please review

Updated AUTHORS.rst

---

readthedocs/vcs_support/backends/svn.py

This is a fix for the PR #3520 after testing it with a SVN repository and a successful build.
I didn't found issues with hg, bzr or git... Yet! :)

Fix SVN initialization for command logging

---

readthedocs/core/utils/__init__.py
readthedocs/settings/base.py
readthedocs/worker.py
tox.ini

Entry point to be able to override the Celery App from the corporate site.

Ability to override the creation of the Celery App

---

readthedocs/templates/projects/project_dashboard.html

Added the missing `</div>` tag on L27

Fixed #3701: added closing tag for div element

---

readthedocs/restapi/urls.py

Imports a sustainability API from the Read the Docs extensions.

Add a sustainability API

---

docs/business/sharing.rst

Improve the documentation with the new flow for *secret links* and *password*.
I remove a WARNING note since it doesn't work as the note said. We probably need to implement that, anyway :)

Improve "Sharing" docs

---

requirements/pip.txt

Refs https://github.com/docker/docker-py/issues/1968

Bump docker -> 3.1.3

---

readthedocs/rtd_tests/tests/test_project.py

tests: mock test_conf_file_not_found filesystem access

---

readthedocs/core/views/serve.py

We weren't doing anything with the query result

Resolve subproject correctly in the case of single version

---

readthedocs/restapi/utils.py

Just a code I saw while testing other issue p:
Faster lookup for the key o(n) vs o(1)

Little improve on sync_versions

---

readthedocs/core/templatetags/core_tags.py
readthedocs/rtd_tests/tests/test_core_tags.py

Handle errors from publish_parts

---

.eslintrc
.flake8
.gitmodules
.isort.cfg
.pep8
.pre-commit-config.yaml
.style.yapf
prospector.yml

This may require git submodule sync locally

Drop readthedocs- prefix to submodule

---

readthedocs/oauth/services/gitlab.py

Keep compatibility (order) with the other services
Related https://github.com/readthedocs/readthedocs-corporate/issues/297

Fix attribute order call

---

README.rst

This resolves issue #3832.
I'm not sure how well worded "When prompted on GitHub, give access to your account" is as it can come off as too invasive (when it really isn't), but it can be interpreted the other.

Update quickstart from README

---

readthedocs/templates/projects/integration_webhook_detail.html
readthedocs/templates/projects/onboard_detail.html
readthedocs/templates/projects/onboard_import.html
readthedocs/templates/projects/project_dashboard_base.html
readthedocs/templates/projects/project_users.html

Found them by inspection or with some random grepping.

templates: mark a few more strings for translations

---

readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_notifications.py

These fixes 50% of the tests failure that i see here. Refs #3957

Fix some tests with postgres

---

requirements/pip.txt

Downgrade docker to 3.1.3

---

CHANGELOG.rst
setup.cfg

Creating this PR since I don't `master` is a protected branch and I don't have permission to just push to it.

Release 2.3.10

---

readthedocs/projects/utils.py

I came across this as i was searching for more redis calls. We aren't using this
and I doubt we are ever going to run varnish again.

Remove old varnish purge utility function

---

readthedocs/rtd_tests/tests/test_api.py

Tests for view docs api response

---

readthedocs/templates/search/elastic_project_search.html

Notice this while removing haystack
`view-source:https://readthedocs.org/projects/docs/search/` line 260

Fix unbalanced div

---

docs/open-source-philosophy.rst

Followup to aea2ed879de2ce4fee10f512c0783dba7ecf4a5b.

Update link to license in philosophy document

---

readthedocs/projects/admin.py

This PR gives an easy way to see the feature flags that apply to a project.

Display feature flags in the admin

---

readthedocs/core/signals.py

Just a minor refactor to not iterates when it's not needed and break the loop when the first URL is found.

Minimum refactor to decide_if_cors

---

readthedocs/projects/models.py

Fixed broken link

---

docs/privacy-policy.rst

The only difference was the DNT rollout

Update the privacy policy date

---

readthedocs/templates/base.html

#4170 - Link the version in the footer to the changelog

---

docs/custom_installs/elasticsearch.rst
readthedocs/core/management/commands/provision_elasticsearch.py

This will aid automatic bootstrapping of RTD and improve maintainability of this approach.

Add provision_elasticsearch command

---

CHANGELOG.rst
setup.cfg

Release 2.5.2

---

readthedocs/doc_builder/python_environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

Fix our use of `--use-wheel` in pip.

---

readthedocs/builds/querysets.py
readthedocs/projects/querysets.py

Gettings pks straight from the db should be faster than getting the full row content, constructing the django model and construct a new list with the pk.

Do less work in querysets

---

docs/conf.py

Issue from updating theme to latest.

Docs: Let Theme Choose Pygments Theme

---

docs/design/theme-context.rst

I have come across this document as did one of the Flask/Pallets maintainers and I just want to note that it isn't implemented yet.

Warning about theme context implementation status

---

docs/advertising/ethical-advertising.rst

I've gotten a few inquiries lately and I just wanted to have some documented details around the community ad qualifications. These are already the rules of thumb I'm using but it's worth discussing and firming up these qualifications.

Add some details around community ad qualifications

---

docs/business/sharing.rst

Fix reST structure

---

docs/yaml-config.rst

Very minor English correction

---

docs/i18n.rst

Simple note to have it documented as a first step. We should incorporate this in our deploy process, though.
Comes from https://github.com/rtfd/readthedocs.org/pull/4476#issuecomment-410822657

Note with the developer flow to update our app translations

---

requirements/pip.txt

See https://github.com/alex/django-taggit/blob/e7ec6577e6ab2077d5cf829dfd676be876baea0c/CHANGELOG.txt#L6

Downgrade django-taggit

---

docs/faq.rst

Ref https://github.com/rtfd/readthedocs.org/pull/4505#issuecomment-418270476

Add change versions slug to faq

---

readthedocs/search/documents.py

This reverts commit 51c109b59633aed1372ea41d7a9907ef337ed9cd.

Revert "auto refresh false"

---

requirements/pip.txt

Remove unused package nilsimsa

---

readthedocs/redirects/admin.py

I found myself in the redirect admin for the 2nd time this week and there were a few improvements that would make my life a bit easier looking at that data.

Minor redirect admin improvements

---

readthedocs/restapi/urls.py
readthedocs/restapi/views/core_views.py

Remove /embed API endpoint

---

README.rst

Let's show off our coverage
It looks like this

Add codecov badge

---

readthedocs/gold/forms.py

Add help_text in the form for adopting a project

---

docs/design.rst
readthedocs/templates/base.html

Final Result
Related Issue: #3594

Add 'Branding' under the 'Business Info' section and 'Guidelines' on 'Design Docs'

---

docs/design.rst

Remove 'Sphinx Template Changes' From Docs

---

readthedocs/core/symlink.py

Sentry issue https://sentry.io/read-the-docs/readthedocs-org/issues/235949674/

Don't rmtree symlink

---

docs/faq.rst

Link update on FAQ page

---

docs/docs.rst

Ref https://github.com/rtfd/readthedocs.org/pull/5067#discussion_r245147694

Update docs about contributing to docs

---

docs/commercial/sharing.rst

Not sure actually, feel free to close if it's ok as is.

Fix little typo

---

tasks.py

Related to https://github.com/rtfd/common/pull/27 and #5059

Declare and improve invoke tasks

---

readthedocs/vcs_support/backends/git.py

Refs https://github.com/rtfd/readthedocs.org/issues/5114

Check that the repo exists before trying to get a git commit

---

docs/conf.py
docs/faq.rst
requirements/local-docs-build.txt

Closes https://github.com/rtfd/common/pull/29

Upgrade recommonmark to latest and fix integration

---

readthedocs/rtd_tests/tests/test_celery.py

Fix tests on master

---

.github/mergeable.yml

Looks like it was always failing, but it didn't report the error (now
it does, that's why it's failing)

Fix mergeable bot

---

docs/guides/feature-flags.rst
readthedocs/config/config.py
readthedocs/config/tests/test_config.py
readthedocs/doc_builder/config.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_config_integration.py

We are accepting v2 for all projects now

Remove feature flag for v2

---

docs/team.rst

I suppose that Santos should be at least in the Development Team.

Add Santos to the development team

---

media/css/readthedocs-doc-embed.css

- Add the ability to have badges to highlight a tech stack
- Remove underlines on links

Tweak some ad styles

---

CHANGELOG.rst
setup.cfg

This includes a search refactor, removal of DNS support for Domain's, YAML v2 being released, and updates to our default Docker images.

Release 3.2.0

---

docs/conf.py

I missed this in my other PR: #5130

Install sphinx-notfound-page for building 404.html custom page

---

CHANGELOG.rst
setup.cfg

Release 3.2.1

---

requirements/docs-lint.txt
requirements/local-docs-build.txt
requirements/pip.txt
requirements/testing.txt

Python requirements updated via `inv packages.upgrade`

Update all Python dependencies

---

.pyup.yml

The configuration file that I missed at #5272

pyup YAML configuration file

---

docs/webhooks.rst

Also mention to leave Secrets field blank.

clarify github integration needs https:// prepended

---

readthedocs/rtd_tests/tests/test_middleware.py

Some tests require the session and auth middleware.
The auth middleware inject the AnonymousUser.
It helps to pass some tests in the corporate site to update a
dependency

Fake auth middleware in tests

---

.pyup.yml

pyup.yml syntax fixed

---

readthedocs/core/static-src/core/js/doc-embed/search.js

Support old jquery where responseJSON doesn't exist

---

CHANGELOG.rst
docs/security.rst

Close #5264 and it fixes a broken link too

Use autosectionlabel for docs in security

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_project_forms.py

Rstrip repo url

---

docs/tests.rst

Update documentation on running test for python environment

---

readthedocs/rtd_tests/tests/test_doc_serving.py

Just a little comment found it while fixing the test in .com

Fix comment

---

readthedocs/sphinx_domains/admin.py

This was really slow and causing the listing page to timeout

Don't show projects in Sphinx Domain Admin sidebar

---

docs/versions.rst

Document that people can create a version named stable

---

readthedocs/restapi/urls.py
readthedocs/sphinx_domains/api.py

https://www.django-rest-framework.org/api-guide/filtering/

Fix warnings in code

---

docs/config-file/v2.rst

Closes https://github.com/rtfd/readthedocs.org/issues/5428

Remove invalid example from v2.rst

---

readthedocs/core/models.py

Removed unused constant from core.models

---

readthedocs/restapi/templates/restapi/footer.html
readthedocs/templates/account/signup.html
readthedocs/templates/homepage.html
readthedocs/templates/profiles/private/advertising_profile.html
readthedocs/templates/projects/domain_list.html
readthedocs/templates/projects/email/build_failed.html
readthedocs/templates/projects/email/build_failed.txt
readthedocs/templates/projects/integration_webhook_detail.html
readthedocs/templates/projects/notifications/deprecated_build_webhook_email.html
readthedocs/templates/projects/notifications/deprecated_build_webhook_site.html
readthedocs/templates/projects/notifications/deprecated_github_webhook_email.html
readthedocs/templates/projects/notifications/deprecated_github_webhook_site.html
readthedocs/templates/projects/notifications/resource_usage_email.html
readthedocs/templates/projects/onboard_detail.html
readthedocs/templates/projects/onboard_import.html
readthedocs/templates/projects/project_advertising.html
readthedocs/templates/projects/project_dashboard_base.html
readthedocs/templates/security.html
readthedocs/templates/security.txt
readthedocs/templates/support.html

Update links to point to `stable` version.

---

.travis.yml

https://blog.travis-ci.com/2018-11-08-xenial-release
I tried to update this a time ago, but the ES installation failed, hope now it works :)

Use Ubuntu xenial on travis

---

.gitignore

gitignore dev.db-journal file #5463

---

docs/features.rst

Remove Haystack reference in Docs

---

readthedocs/builds/views.py

Build List Screen Performance Issue Fix.

---

readthedocs/templates/core/header.html

Remove Header Login button from login page

---

readthedocs/doc_builder/constants.py
readthedocs/doc_builder/environments.py

We used to inject a specific template for mkdocs
projects, we don't do this anymore.

Remove unused volume from docker

---

docs/development/buildenvironments.rst

Note for Docker image size in Docker instructions

---

readthedocs/config/models.py
readthedocs/notifications/notification.py
readthedocs/restapi/views/model_views.py

This is a followup of #5650
ref: #5517

pylint fix for notifications, restapi and config

---

readthedocs/core/views/__init__.py
readthedocs/rtd_tests/tests/test_doc_serving.py

Serve custom 404 pages from Django

---

docs/commercial/index.rst
docs/support.rst

Eventually this page may go away and be replaced with some landing pages on readthedocs.com. Until then I wanted to just highlight some key features for both users and search engines to find.
See: #5726

Small commercial hosting page rework

---

readthedocs/projects/admin.py

This is a useful filter when using the Django Admin.

Filter by projects with no banned users

---

readthedocs/doc_builder/backends/sphinx.py

Just a small update to clarify how we are using latexmk.
Refs #5744

Clarify latexmk option usage

---

docs/index.rst

Design docs were missing from the toctree

Fix design docs missing from toctree

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/doc_builder/exceptions.py
readthedocs/rtd_tests/tests/test_doc_builder.py

Validate dict when parsing the mkdocs.yml file

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/doc_builder/backends/sphinx.py

Before removing this, we want to collect some info
to communicate this change to users.
Related #5609

Add logging in magic methods

---

docs/features/sitemaps.rst

As #5724 is merged we need to update the docs to reflect that change :)

Update docs with sitemap sort order change

---

docs/advertising/ethical-advertising.rst

- We had a lingering reference to opting out of all ads without talking to us. I think this change clears up those docs.
- I also discuss the benefits of our commercial plans

Update docs around opt-out of ads

---

readthedocs/projects/management/commands/import_project_from_live.py

Currently it writes to stderr, but the code keeps running and
there is an unbound error for `project_data`

Raise CommandError when there isn't data from the api

---

readthedocs/rtd_tests/tests/test_project_views.py

With #5841 it was discovered an untested code
https://codecov.io/gh/rtfd/readthedocs.org/pull/5841/changes
this adds a proper test, actually I wasn't sure how to test this :)

Add test for remote repo form

---

readthedocs/projects/admin.py

This is similar to #5848, but helps with different models in the admin.

Improve performance of the HTMLFile and ImportedFile admin

---

readthedocs/builds/models.py
readthedocs/projects/forms.py
readthedocs/projects/models.py

Remove calls to assign from django guardian

---

readthedocs/api/v2/views/integrations.py
readthedocs/core/views/hooks.py
readthedocs/projects/models.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_backend.py
readthedocs/rtd_tests/tests/test_footer.py
readthedocs/rtd_tests/tests/test_version_commit_name.py
readthedocs/vcs_support/backends/bzr.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/backends/svn.py
readthedocs/vcs_support/base.py

This PR will refine the Webhook Data handling, parsing and also Writing tests for All the PR Building functionality.
We need to also Handle `closed` `pull_request` event.

Refine Webhook data handling for PR Builder

---

readthedocs/builds/models.py

Use only when retrieving the config attr

---

readthedocs/api/v2/views/integrations.py
readthedocs/builds/querysets.py
readthedocs/builds/storage.py
readthedocs/builds/syncers.py
readthedocs/core/templatetags/core_tags.py
readthedocs/core/views/__init__.py
readthedocs/oauth/querysets.py
readthedocs/projects/models.py
readthedocs/projects/querysets.py
readthedocs/projects/tasks.py
readthedocs/projects/views/public.py
readthedocs/search/utils.py
readthedocs/search/views.py
readthedocs/vcs_support/backends/bzr.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/backends/svn.py

Cherry Pick this commit https://github.com/readthedocs/readthedocs.org/pull/5857/commits/83d21accdcc2a1b335ca745002699985dbf0a2d9 to fix linting issues.

Lint (pep257: D415)

---

readthedocs/projects/models.py

I grep all the Read the Docs repositories that I have locally and I didn't find any place where these are used. I'm removing them.

These Project's methods are not used

---

readthedocs/projects/models.py

remove the usage of six

---

readthedocs/projects/exceptions.py

Improve error message for invalid submodule URLs

---

readthedocs/rtd_tests/tests/test_managers.py

this is a continuation of #5981

More explicit tests for build managers

---

readthedocs/core/views/__init__.py
readthedocs/rtd_tests/tests/test_views.py
readthedocs/templates/homepage.html

This query is causing a lot of load, currently.

Remove project count on homepage

---

readthedocs/projects/fixtures/test_auth.json

Ref https://github.com/readthedocs/readthedocs.org/issues/5875.
I didn't find any migration model.

Remove django-guardian model

---

readthedocs/oauth/services/gitlab.py

ref: https://github.com/readthedocs/readthedocs.org/issues/6052

Update GitLab Webhook creating to enable merge request events

---

docs/advertising/advertising-details.rst

- Remove theme specific section - ads are coming to all themes!
- Fixed footer ads are no longer mobile-only

Update ad details docs

---

readthedocs/core/urls/__init__.py
readthedocs/core/views/__init__.py
readthedocs/core/views/serve.py
readthedocs/rtd_tests/tests/test_views.py

- Remove /random (it always 500s)
- Fix a small issue with doc redirects

Fix lingering 500 issues

---

docs/custom_installs/index.rst

Mention we don't support custom installs any time.

Remove paid support callout

---

docs/faq.rst

This should probably use intersphinx, but keeping it small for now.

Fix link to html_extra_path

---

docs/faq.rst

closes https://github.com/readthedocs/readthedocs.org/issues/6247

Add note about specifying dependencies

---

readthedocs/projects/urls/public.py
readthedocs/rtd_tests/tests/test_privacy_urls.py

closes https://github.com/readthedocs/readthedocs.org/issues/6249

Redirect /projects/ URL to /dashboard/

---

readthedocs/projects/admin.py

I find myself looking for this a lot

Add pub_date to project admin

---

readthedocs/api/v2/templates/restapi/footer.html

Fixes https://github.com/readthedocs/readthedocs.org/issues/3561.

Added missing i18n for footer api

---

readthedocs/templates/account/signup.html
readthedocs/templates/base.html

- From the login page
- From the site footer

Link to the terms of service

---

readthedocs/rtd_tests/tests/test_privacy_urls.py

Rename test name

---

readthedocs/projects/models.py

Small refactor to avoid making multiple queries to get the default_version for each link.

Refactor get_downloads to make one query for default_version

---

docs/guides/autobuild-docs-for-pull-requests.rst

Make the docs a bit more clearer about what the issues are users might hit.

Update troubleshooting steps for PR builder

---

requirements/pip.txt

See https://www.djangoproject.com/weblog/2019/dec/18/security-releases/

Upgrade Django due a security issue

---

readthedocs/proxito/views/serve.py

We need this because when the URL returned by `storage.url` contains
querystring we are appending it to the end otherwise and arguments get
wrong.

Add 'index.html' to the path before using storage.url(path)

---

dockerfiles/entrypoints/celery.sh

Small fix to trigger the command properly when using watchmedo.

Fix celery auto-reload command

---

.travis.yml
scripts/travis/install_node.sh

Matrix isn't used anymore in travis, it's just an alias for jobs now
https://github.com/travis-ci/docs-travis-ci-com/issues/2557

Only install node on eslint step on travis

---

dockerfiles/Dockerfile

We mention these tools in the guide #6517

Add netcat and telnet for celery debugging with rdb

---

docs/advertising/ethical-advertising.rst
docs/intro/getting-started-with-sphinx.rst
docs/story.rst

Add www to the broken link

---

readthedocs/api/v2/views/footer_views.py

This is to allow us to override it in .com

Use settings override in footer

---

docs/guides/autobuild-docs-for-pull-requests.rst

closes https://github.com/readthedocs/readthedocs.org/issues/6542

Add GitHub OAuth App Permission issue to PR Builder Troubleshooting docs

---

docker-compose.override.yml
readthedocs/settings/docker_compose.py
tasks.py

I introduce this bug in #6539.

Mount proper shared docker volume

---

readthedocs/proxito/middleware.py

only serve x-rtd-slug project if it exists

---

readthedocs/doc_builder/environments.py

We don't need these on sentry
https://sentry.io/organizations/read-the-docs/issues/1482725089/?project=148442&query=is%3Aunresolved

Don't error when killing/removing non-existent cotainer

---

readthedocs/doc_builder/environments.py

Ref https://sentry.io/organizations/read-the-docs/issues/1482636579/?project=148442&query=is%3Aunresolved

Create unique container per sync

---

readthedocs/doc_builder/environments.py

Ref https://sentry.io/organizations/read-the-docs/issues/1482635921/?project=148442&query=is%3Aunresolved

Check for None before assignment

---

readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_build_notifications.py

closes: https://github.com/readthedocs/readthedocs.org/issues/6631

Content-type header added to webhook notifications

---

readthedocs/settings/docker_compose.py

This mostly applies in the admin for large projects where there are lots of inline forms with many fields.

Increase the number of POST fields in development

---

readthedocs/projects/admin.py

This applies on the inline on the Project details screen

Limit versions shown in the Django admin inline

---

dockerfiles/nginx/web.conf
readthedocs/settings/docker_compose.py

These changes were just small tweaks I made to the settings while working on #6708. These changes make it easier to override values like `PRODUCTION_DOMAIN` when necessary.

Docker settings improvements

---

readthedocs/projects/version_handling.py

Small improvement to help with projects with lot of versions.

Sort vesions in-place to help performance

---

readthedocs/projects/version_handling.py

`.iterator()` will help a little on projects with lot of versions.

Use .iterator when sorting versions

---

docs/conf.py

This reverts commit 8ef6e4aa7430c7d6ddefeaf0d92c940e34e349d1, reversing
changes made to 9d44e5ca5969d8deaf414650c3a21c48d4b109f7.
It broke the builds on RTD, so reverting.

Revert "Merge pull request #6739 from readthedocs/agj/docs-tos-pdf"

---

dockerfiles/nginx/proxito.conf
readthedocs/proxito/views/serve.py

Properly proxy the Proxito headers via nginx/sendfile

---

dockerfiles/nginx/proxito.conf

@proxito404 does not exist, we have defined @notfoundcallback here.

Call proper handler

---

readthedocs/notifications/notification.py

This is needed to refactor .com

Allow to override app from where to read templates

---

readthedocs/profiles/views.py

This is needed to change the behavior of this view on .com

Allow to override ProfileDetail view

---

readthedocs/projects/tasks.py

Properly call sync_callback when there aren't any MULTIPLE_APP_SERVERS settings

---

requirements/pip.txt

This includes https://github.com/AliLozano/django-messages-extends/pull/29
Fixes https://github.com/readthedocs/readthedocs.org/issues/6753

Update messages-extends to latest version

---

readthedocs/proxito/tests/test_full.py

Be explicit with PUBLIC_DOMAIN setting

---

readthedocs/projects/views/public.py

Allow to override project detail view

---

docs/webhooks.rst

Ref https://github.com/readthedocs/readthedocs.org/issues/6824#issuecomment-604578367

Add checking the github oauth app in the troubleshooting page

---

docs/guides/searching-with-readthedocs.rst

This feature is enabled by default now

Remove note about search analytics being beta

---

docs/development/search.rst

This is very common the first time search ins run

Add troubleshooting section for dev search docs

---

readthedocs/proxito/views/mixins.py
readthedocs/proxito/views/serve.py

This should make our logs much less noisey in prod,
now that we've debugged most of our prod issues.

Reduce proxito logging

---

readthedocs/settings/base.py
readthedocs/settings/test.py

We are settings this limits dynamically in https://github.com/readthedocs/readthedocs.org/pull/6879

Remove DOCKER_LIMITS

---

docs/guides/feature-flags.rst

Keep pointing people to contact us when it's a specific request.

Contact us via email for Feature Flags

---

readthedocs/profiles/urls/private.py
readthedocs/profiles/views.py
readthedocs/rtd_tests/tests/test_privacy_urls.py

Allow to override sign in and sign out views

---

docs/doc_extensions.py

Found in a CI traceback for another PR.

Emit a better error if no feature flag is found

---

readthedocs/settings/base.py

Add CDN to the installed apps

---

readthedocs/builds/tasks.py
readthedocs/builds/tests.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_oauth.py

This should be the default now

Remove CELERY_ROUTER flag

---

docs/commercial/sharing.rst

This needs a PR from .com to be merged first

Document about next when using a secret link

---

docs/api/index.rst

Currently you need to scroll a lot

List apiv3 first

---

readthedocs/search/views.py

This logic is the same as the previous one,
but it iterates over the valid facets only.

Search: iterate over valid facets only

---

readthedocs/projects/models.py

Changed the var names to make them more clear

Sphinx Search: don't skip indexing if one file fails

---

readthedocs/search/tasks.py
readthedocs/search/tests/test_search_tasks.py

Now that we are saving the number of results,
this is useful to see what content is missing from the docs.

Search: record queries with 0 results

---

readthedocs/doc_builder/backends/sphinx.py
readthedocs/projects/models.py

Use "-j auto" on sphinx-build command to build in parallel

---

readthedocs/projects/views/private.py

This reverts commit 204bc4398e60ec40a4476df79824dc8b33782c84, reversing
changes made to 0d7901eba9a213fb93a41259fd471219516e380b.

Revert "Merge pull request #7101 from readthedocs/show-last-total"

---

readthedocs/profiles/views.py

Do not Pre-populate username field for account delete

---

readthedocs/search/signals.py
readthedocs/search/tests/test_signals.py
readthedocs/templates/search/elastic_search.html

I'm also adding some tests bc we didn't have them.

Project search: Show original description when there isn't highlight

---

requirements/docker.txt

`inv docker.up` is failing without this requirement

Install `argh` for Docker environment

---

CHANGELOG.rst
setup.cfg

Release 5.1.2

---

readthedocs/projects/tasks.py

Rename API endpoint call

---

readthedocs/search/api.py
readthedocs/search/tests/test_api.py

Search: fix pagination

---

readthedocs/doc_builder/python_environments.py

The latest Sphinx flag will now mean actually using the latest Sphinx.

Feature flag for using latest Sphinx

---

requirements/pip.txt

https://pypi.org/project/appdirs/

Remove unused dep

---

readthedocs/core/templatetags/core_tags.py
readthedocs/rtd_tests/tests/test_core_tags.py

Re-add the rst filter that got removed

---

readthedocs/oauth/management/commands/reconnect_remoterepositories.py

If the user disconnects their account, we remove all the RemoteRepository
objects for that user and the `Project.remote_repository` ends being NULL.
This script is useful to find all the Project that are disconnected from the
RemoteRepository for a specific Organization and helps us to know if it's safe
to reconnect them.

Script to re-connect RemoteRepository

---

.readthedocs.yml

This can be merged after the next release is live

Docs: set ranking for some pages

---

docs/intro/getting-started-with-sphinx.rst

Use the privacy embed for YouTube

---

readthedocs/templates/projects/project_import.html

re-worded text on top of "Import a Repository"

---

docs/intro/getting-started-with-mkdocs.rst
docs/intro/getting-started-with-sphinx.rst
docs/intro/import-guide.rst

- Center images
- Use intersphinx
- Warning about pinning sphinx as we warn in mkdocs

Docs: little improvements on getting start docs

---

docs/guides/cross-referencing-with-sphinx.rst

A few suggestions to clean up language and make it easier to follow! Feel free to take whatever of this you'd like!

general improvements to cross-references guide

---

readthedocs/builds/tasks.py

We are not logging the project name

Task router: improve logging

---

readthedocs/api/v2/views/integrations.py

ref https://sentry.io/organizations/read-the-docs/issues/1840238779/?project=161479&referrer=alert_email

GitLab webhook: don't fail on invalid payload

---

readthedocs/analytics/tests.py

This should fix the tests in .com

Test: set privacy level explicitly

---

readthedocs/search/documents.py
readthedocs/search/faceted_search.py
readthedocs/search/management/commands/reindex_elasticsearch.py
readthedocs/search/serializers.py
readthedocs/search/tasks.py
readthedocs/search/utils.py
readthedocs/settings/base.py
requirements/pip.txt

Reverts readthedocs/readthedocs.org#7408 till we contact users using an old version of our extension https://github.com/readthedocs/readthedocs-sphinx-search

Revert "ES: update dependencies"

---

readthedocs/organizations/__init__.py
readthedocs/organizations/apps.py
readthedocs/organizations/signals.py

Copy/paste + some update to make the linter happy

Organizations: move signals

---

docs/advertising/ethical-advertising.rst
readthedocs/templates/base.html
readthedocs/templates/homepage.html

- Don't rely on the redirects if possible
- Add UTM codes
- Highlight EthicalAds.io in ethical ads docs

Update links to advertising

---

docs/api/v3.rst
readthedocs/api/v3/filters.py

closes https://github.com/readthedocs/readthedocs.org/issues/7363

APIv3 Version list slug filter added

---

readthedocs/settings/base.py

This reverts commit da5f0628b741122c9597ea4b35a10b1988007df2.

Revert "New docker image for builders: 8.0"

---

readthedocs/core/static-src/core/js/doc-embed/sponsorship.js

ref https://github.com/readthedocs/readthedocs.org/pull/7493/

Tests: fix eslint

---

readthedocs/analytics/models.py

Include month-ago day to traffic data

---

readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_version.py

We need to check for the main_project of the translation.

Downloads: fix translation of a subproject

---

dockerfiles/Dockerfile
readthedocs/settings/base.py
readthedocs/settings/docker_compose.py

This also requires changes to common:
* readthedocs/common#51
* readthedocs/common#73

Add settings and docker configuration for working with new theme

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_subprojects.py

Fixes https://github.com/readthedocs/readthedocs.org/issues/7229

Subprojects: fix form

---

readthedocs/doc_builder/python_environments.py

I'm not removing the feature,
as it can be used in the future.

Builds: always install latest version of our sphinx extension

---

CHANGELOG.rst
setup.cfg

Release 5.6.1

---

readthedocs/search/views.py

We were only applying the feature flag for the API.

Search: respect feature flag in dashboard search

---

readthedocs/rtd_tests/tests/test_notifications.py

The same as #7628 for another test case that I missed :(

Check only for override settings (part 2)

---

readthedocs/rtd_tests/base.py
readthedocs/rtd_tests/tests/test_build_forms.py
readthedocs/rtd_tests/tests/test_privacy_urls.py
readthedocs/rtd_tests/tests/test_project.py
readthedocs/rtd_tests/tests/test_project_views.py
readthedocs/rtd_tests/tests/test_sync_versions.py
readthedocs/rtd_tests/tests/test_views.py

Final take, same as
https://github.com/readthedocs/readthedocs.org/pull/7677.
Everything should be fast now!

Tests: mock trigger_build

---

readthedocs/projects/querysets.py

A project could sit in the middle and be excluded

FeatureQuerySet: make check for date inclusive

---

readthedocs/api/v2/views/model_views.py
readthedocs/oauth/services/base.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/oauth/utils.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_celery.py
readthedocs/rtd_tests/tests/test_oauth_sync.py

This PR will change references to the old modeling

Update parts of code that were using the old RemoteRepository model fields

---

readthedocs/builds/apps.py

Required to autoscale builders.

Register StopBuilder task to be executed by builders

---

docs/builds.rst

This matches them with reality :)

Update build concurrency numbers for Business

---

readthedocs/projects/models.py

Forgot to list it here, I had to create it manually from the shell.

List SYNC_VERSIONS_USING_A_TASK flag in the admin

---

readthedocs/payments/forms.py

I hope this helps to track down an issue we are having with subscriptions.

Log Stripe Resource fallback creation in Stripe

---

docs/api/v3.rst
readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/mixins.py
readthedocs/api/v3/tests/test_projects.py

closes https://github.com/readthedocs/readthedocs.org/issues/7811

Add Option to Enable External Builds Through Project Update API

---

docs/versions.rst

Ref https://github.com/readthedocs/readthedocs.org/issues/7810

Docs: mention the version warning is for sphinx only

---

readthedocs/storage/mixins.py
readthedocs/storage/s3_storage.py

Bring `S3PrivateBucketMixin` into community code so we can share more code with
commercial and between our community classes as well.

Use S3 from community

---

requirements/docker.txt

ref https://github.com/readthedocs/readthedocs.org/pull/7941/files#r580840504

Downgrade jedi

---

readthedocs/oauth/management/commands/load_project_remote_repo_relation.py

This is the second PR for dumping/loading Project and RemoteRepository Relationship data.
Data dump PR: https://github.com/readthedocs/readthedocs.org/pull/7957
This PR adds a management command to load the project -> RemoteRepository relationship data from a json file which is created by #7957.
ref: #7806

Add management command to Load Project and RemoteRepository Relationship from JSON file

---

readthedocs/api/v2/proxied_urls.py

Embed: change proxied urls

---

docs/guides/conda.rst

Hi all! 👋🏽 This is my first substantive contribution to the Read the Docs documentation, and I hope it marks the beginning of a beautiful friendship 😃 
In this pull request I update the Conda guide adding some examples on how to create an `environment.yml`, discussion about conda channels, information on how to include pip packages in the conda environment, tips for compiling C, C++, FORTRAN or Node.js extensions, and some conda-specific troubleshooting steps.
As @ericholscher noted, this has some overlap with https://github.com/readthedocs/readthedocs.org/pull/7888/. I already left a comment there about the pinning of core dependencies.
<details>
<a href="https://gist.github.com/astrojuanlu/90c9c87457a86802d18469eeb435bc98">These are the notes I took while investigating the topic</a>. …

Update guide on conda support

---

readthedocs/templates/base.html

We probably need to change these links up a little,
but this should be good for now.

refactor footer, add jobs & status page

---

docs/Makefile
docs/_static/js/expand_tabs.js

Our little hack doesn't work with the current version.

Docs: update expand_tabs to work with the latest version of sphinx-tabs

---

readthedocs/search/management/commands/reindex_elasticsearch.py

We have triggered this by mistake in the default queue,
after that is done there isn't a way to cancel it.

Search: make --queue required for management command

---

readthedocs/core/views/__init__.py
readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_full.py
readthedocs/proxito/urls.py

This is just a simple health check that confirms 
that proxito is still up and responding to requests.

Add proxito healthcheck

---

readthedocs/analytics/models.py
readthedocs/projects/views/private.py

Top 10 seems pretty limited.
I'd love to expand this to make the UI on the dashboard better,
but this should hopefully make it a bit more obviously useful at this point.

Make pageviews analytics show top 25 pages

---

readthedocs/templates/account/email.html
readthedocs/templates/base.html
readthedocs/templates/projects/project_traffic_analytics.html
readthedocs/templates/projects/projects_search_analytics.html

We were putting a blank script tag at the bottom of every page,
this now includes the script in the block.
This is a small cleanup,
but we also need this change on the .com as well.

Standardize footerjs code

---

docs/guides/feature-flags.rst
readthedocs/doc_builder/backends/sphinx.py
readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_doc_building.py

These have been enabled by default in all projects (.org and .com) for a while now.

Clean some feature flags

---

readthedocs/api/v2/views/model_views.py
readthedocs/projects/models.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_celery.py
readthedocs/rtd_tests/tests/test_sync_versions.py

We are using this as default for both sites now

Sync versions: always use a task

---

docs/advertising/ad-blocking.rst

Clarify ad-free conditions

---

readthedocs/oauth/services/base.py

Ref https://sentry.io/organizations/read-the-docs/issues/2314850739/?environment=production&project=161479

OAuth: avoid undefined var

---

readthedocs/oauth/tasks.py

Ref https://sentry.io/organizations/read-the-docs/issues/2322520998/?environment=production&project=148442

OAuth: protection against deleted objects

---

docs/config-file/v1.rst
docs/config-file/v2.rst
readthedocs/templates/projects/project_advanced_settings_helptext.html

Close https://github.com/readthedocs/readthedocs.org/issues/8092

Config file: improve docs and help text

---

docs/commercial/single-sign-on.rst

I noticed a few issues with capitalization and quote usage. There is some
restructuring that might make directions and language more clear, but I just
wanted to grab the superficial issues for now.

Fix a few style and grammar issues with SSO docs

---

readthedocs/builds/apps.py

Import the metric task required to be ran by celery beat.

Metrics: run metrics task every 30 minutes

---

docs/commercial/single-sign-on.rst

Warn users a bit more about having this remove their RTD team perms

Clean up SSO docs

---

readthedocs/projects/querysets.py
readthedocs/rtd_tests/tests/test_project_querysets.py

This removes two overrides from .com!

QuerySets: bring project querysets more closer to .com

---

readthedocs/search/management/commands/reindex_elasticsearch.py

Just to avoid any mistakes while running these commands.

Search: ask for confirmation when running reindex_elasticsearch

---

readthedocs/organizations/managers.py
readthedocs/organizations/querysets.py

This is always evaluated to False,
we don't set this to true in our code (.com as well).

QuerySets: remove include_all

---

readthedocs/api/v2/views/footer_views.py

Some I found while solving another problem.

Footer: remove unused context vars

---

docs/guides/index.rst

This will show all the guides on the guide index page https://docs.readthedocs.io/en/latest/guides/index.html

Increase guide depth

---

readthedocs/core/utils/__init__.py
readthedocs/rtd_tests/tests/test_core_utils.py

Closes https://github.com/readthedocs/readthedocs.org/issues/7573

Slugify: don't generate slugs with trailing `-`

---

docs/development/design/embed-api.rst

Minor change to render the document properly.

Design doc: fix render api endpoints

---

docs/intro/getting-started-with-sphinx.rst

This adds a link to the MyST tutorial on Sphinx,
so we don't just leave users with nothing to continue on in this section.

Build out the MyST section of the getting started

---

docs/config-file/v2.rst
readthedocs/config/config.py
readthedocs/config/tests/test_config.py
readthedocs/doc_builder/config.py
readthedocs/rtd_tests/tests/test_config_integration.py
readthedocs/rtd_tests/tests/test_doc_building.py
readthedocs/settings/base.py

This is on top of https://github.com/readthedocs/readthedocs.org/pull/8328

Config file: use string for python.version

---

readthedocs/audit/models.py

Mainly for .com where we perform login/logout on subdomains.

Audit: attach project from the request if available

---

readthedocs/oauth/admin.py

closes https://github.com/readthedocs/readthedocs.org/issues/8412

Added Search and Filters for `RemoteRepository` and `RemoteOrganization` admin list page

---

readthedocs/templates/support/index.html

Well, it can be changed, but don't make it too obvious.

Support form: don't allow to change the email

---

readthedocs/templates/projects/project_version_states_help_text.html

Found this while writing #8473.

Fix link to version states documentation

---

docs/privacy-policy.rst
media/css/core.css
readthedocs/templates/base.html

Companion to https://github.com/readthedocs/blog/pull/128.

Change newsletter form

---

readthedocs/audit/admin.py

Include information about the organization

Audit: update admin

---

requirements/docs.txt

Mainly to address https://github.com/readthedocs/readthedocs-sphinx-search/issues/92

Upgrade readthedocs-sphinx-search

---

readthedocs/projects/admin.py

This code is commented and is not required anymore since it's for Ads.

Cleanup: remove old code

---

readthedocs/core/admin.py
readthedocs/projects/admin.py

This is so an historical record is created when banning users

Admin: don't use update to ban users

---

docs/subprojects.rst

Ref https://github.com/readthedocs/readthedocs.org/issues/8678

Docs: update docs about search on subprojects

---

requirements/pip.txt

It's too soon to upgrade,
ref https://github.com/readthedocs/readthedocs.org/pull/8680#discussion_r751257848

Downgrade redis

---

requirements/pip.txt

awscli isn't compatible with pyyaml>=5.5.

Downgrade pyyaml

---

docs/config-file/v2.rst

See https://github.com/readthedocs/readthedocs.org/issues/8679.

Clarify how to pin the Sphinx version

---

readthedocs/projects/admin.py

Thanks @astrojuanlu for reporting this bug :)
The threshold limits were inverted.

spam: fix admin filter

---

docs/conf.py
docs/guides/authors.rst
docs/guides/migrate-rest-myst.md
requirements/docs.txt

And of course, it's written in MyST 😃 
cc @choldgraf and @chrisjsewell since this makes numerous references to myst-parser and rst-to-myst.

Add guide to migrate from reST to MyST

---

readthedocs/proxito/tests/base.py

This is to fix some tests on .com

Tests: set privacy level explicitly

---

readthedocs/oauth/tasks.py
readthedocs/rtd_tests/tests/test_oauth_tasks.py

Ref https://sentry.io/organizations/read-the-docs/issues/2835481040/?environment=production&project=161479&referrer=alert_email

Fix call to sync_remote_repositories

---

readthedocs/settings/base.py

Update mambaforge to latest version

---

readthedocs/rtd_tests/tests/test_automation_rule_views.py
readthedocs/rtd_tests/tests/test_project_views.py

Explicit settings for some tests

---

docs/_static/css/custom.css
docs/_templates/ethicalads.html

This shows off a new feature of our advertising client on our own docs. It basically works the same as before except the feature is built-in.

Use ad client stickybox feature on RTD's own docs

---

readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/test_projects.py

Ref https://sentry.io/organizations/read-the-docs/issues/2900424846/?environment=production&project=148442&referrer=alert_email

API v3: check if the name generates a valid slug

---

readthedocs/settings/base.py
readthedocs/subscriptions/apps.py
readthedocs/subscriptions/forms.py
readthedocs/subscriptions/signals.py
readthedocs/subscriptions/templates/subscriptions/subscription_detail.html
readthedocs/subscriptions/tests/test_models.py
readthedocs/subscriptions/tests/test_views.py
readthedocs/subscriptions/urls.py
readthedocs/subscriptions/views.py
readthedocs/urls.py

In .com we are linking to the pricing page from the help text of the form, since we don't have a pricing page on .org I'm just making it redirect to the homepage, maybe we could redirect to the .com pricing page?

Subscriptions: move views 

---

docs/conf.py

I'm enabling the "don't override sphinx context" feature flag for our project.

Docs: fix edit on links

---

docs/dev/issue-labels.rst
docs/user/gsoc.rst
docs/user/guides/conda.rst
docs/user/integrations.rst
docs/user/open-source-philosophy.rst
docs/user/pull-requests.rst

Just fixed a couple common ones I saw today:
* Pull request is not a proper noun
* Open source is not capitalized
* I also converted some mock definition lists to actual definition lists

Fix more casing issues

---

readthedocs/core/utils/__init__.py

This comment was suggested in
https://github.com/readthedocs/readthedocs.org/pull/8917#discussion_r806318973
but the PR was already merged.

Comment: add comment from PR review

---

readthedocs/core/utils/__init__.py
readthedocs/projects/constants.py
readthedocs/rtd_tests/tests/test_core_utils.py
readthedocs/settings/base.py

This feature never worked properly, so I'm removing this code.

Celery: remove queue priority

---

readthedocs/integrations/admin.py

* Add search on http exchanges
* Link correctly from integration -> http exchange admin

Fix a couple integration admin bugs

---

docs/user/subprojects.rst

It's good to have a place where to link to users about this in our docs.
Also, normalized some titles to sentence-case.

Docs: warn about custom domains on subprojects

---

readthedocs/vcs_support/base.py

When canceling a build immediately after it's triggered the message was `None`
because we were raising a `RepositoryError` exception and Celery wasn't handling
it as it was a build cancelled.
By catching this exception on the VCS commands and re-raising `BuildCancelled`
again, `on_failure` method from Celery will handle it properly.

Build: cancel error message

---

readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/test_projects.py

Extend `ProjectCreateSerializer` to validate if there is a `RemoteRepository`
match for the project's repository created.
If it's not found (matching `ssh_url`, `clone_url` and `html_url`) we call a
validation function that will act depending on the platform:
- community: won't raise any exception and just won't connect the `Project` to a
`RemoteRepository`. This is the current behavior and this PR keeps it the same
- commercial: if the organization has VCS SSO enabled and we didn't find a
`RemoteRepository` it will raise a `ValidationError` communicating the user
that we weren't able to import the `Project`
This is the first step on making SSO UX a little nicer and avoid ending up with
disconnected `Project` -> `RemoteRepository` and loosing access to them.

API: validate `RemoteRepository` when creating a `Project`

---

readthedocs/projects/tests/mockers.py
readthedocs/projects/tests/test_build_tasks.py

Tests: fix mock.patch order

---

docs/user/advertising/ethical-advertising.rst

Update the community ads application link

---

README.rst

Copyright date

---

docs/dev/guides/gvisor.rst
docs/dev/guides/index.rst
docs/dev/index.rst
readthedocs/doc_builder/environments.py
readthedocs/projects/models.py

Also quick dev doc on setup.
Code change is in commit 1def3f85b
Linting is in commit f616b7f9f
Closes #9065

Add gVisor runtime option for build containers

---

docs/dev/guides/gvisor.rst

This is probably just for me to remember next time I re-install my OS.

Docs: add notes about gvisor on Fedora

---

docs/user/user-defined-redirects.rst

In response to someone asking how to do this on Twitter

Cleanup Redirects docs

---

readthedocs/projects/tasks/mixins.py
readthedocs/rtd_tests/tests/test_backend.py
readthedocs/vcs_support/backends/git.py

Fixes https://github.com/readthedocs/readthedocs.org/issues/9111

git: respect SKIP_SYNC_* flags when using lsremote

---

readthedocs/doc_builder/director.py
readthedocs/doc_builder/environments.py

Closes https://github.com/readthedocs/readthedocs.org/issues/9103

Build: use gvisor for projects using build.jobs

---

readthedocs/projects/tasks/builds.py

We have the build id from the start, let's log everything that happens on the task with it, we are also no logging anything if the task fails

Build: log more data

---

readthedocs/projects/tasks/search.py

Closes https://github.com/readthedocs/readthedocs.org/pull/9136

Rebase of #9136

---

docs/dev/server-side-search.rst
docs/user/faq.rst
readthedocs/embed/tests/data/sphinx/latest/index.html
readthedocs/embed/tests/data/sphinx/latest/index.json
readthedocs/embed/tests/test_api.py
readthedocs/oauth/notifications.py
readthedocs/projects/fixtures/test_data.json

Had a user quote the notification with the wrong branding,
and figured I'd fix all of it.

Fix RTD branding in the code

---

docs/user/custom_domains.rst

This is a useful feature of RTD that I didn't know existed. This is a small PR to try and boost the visibility of sub-projects by using a keyword that I think others might search for "sub-folders" and adding a note to the custom domain section.

Note sub-folders with a single domain.

---

readthedocs/projects/tests/test_domain_views.py

We still need to ignore a couple on .com.

Fix tests on .com

---

docs/user/integrations.rst

Docs: gitlab integration update

---

readthedocs/rtd_tests/fixtures/spec/v2/schema.json

My editor keeps raising warnings about this...
Closes https://github.com/readthedocs/readthedocs.org/issues/9115

Update json schema

---

docs/user/team.rst

Various references to this page are fixed in #9302

Update the team page

---

readthedocs/gold/views.py

ref https://github.com/readthedocs/readthedocs.org/pull/9320#discussion_r896413138

Gold: log if the subscription has more than one item

---

readthedocs/builds/tasks.py
readthedocs/proxito/middleware.py
readthedocs/proxito/views/utils.py

Reduce logging level on some logs that are not that relevant anymore.

Logging: reduce log verbosity

---

.readthedocs.yml
docs/user/_static/dmca/takedown-template.txt
docs/user/dmca/archive/2022-06-07.rst
docs/user/dmca/index.rst

This project has been manually removed by the user.

Add DMCA takedown request for project dicom-standard

---

.github/CODEOWNERS

Add frontend team codeowners rules

---

readthedocs/projects/tasks/builds.py

Ref https://sentry.io/organizations/read-the-docs/issues/3422620605/?alert_rule_id=229005&alert_timestamp=1657709758585&alert_type=email&environment=production&project=148442&referrer=alert_email

Build: check for self.data.version being None

---

readthedocs/audit/models.py
readthedocs/audit/tests/test_models.py

Closes https://github.com/readthedocs/readthedocs.org/issues/9315

Audit logs: truncate browser

---

readthedocs/doc_builder/director.py
readthedocs/projects/tests/mockers.py
readthedocs/projects/tests/test_build_tasks.py

----------
:books: Documentation preview :books:: https://docs--9454.org.readthedocs.build/en/9454/

Build: use correct build environment for build.commands

---

readthedocs/projects/models.py
readthedocs/projects/tasks/search.py
readthedocs/search/documents.py
readthedocs/search/parsers.py

In case this is needed for https://github.com/readthedocs/readthedocs.org/pull/9482
----
:books: Documentation preview :books:: https://docs--9483.org.readthedocs.build/en/9483/

Disable sphinx domains

---

requirements/docs.in
requirements/docs.txt

----
:books: Documentation preview :books:: https://docs--9501.org.readthedocs.build/en/9501/
----
:books: Documentation preview :books:: https://dev--9501.org.readthedocs.build/en/9501/

sphinxcontrib-video was added incorrectly

---

.circleci/config.yml
docs/.rstcheck.cfg
requirements/docs.in
tox.ini

Fixes #9475 
----
:books: Documentation preview :books:: https://docs--9505.org.readthedocs.build/en/9505/
----
:books: Documentation preview :books:: https://dev--9505.org.readthedocs.build/en/9505/

Removes rstcheck

---

.github/workflows/pr-preview-links.yaml

So they appear like one list instead of being stacked.
Hopefully this looks like what I have in mind...
----
:books: Documentation preview :books:: https://docs--9495.org.readthedocs.build/en/9495/
----
:books: Documentation preview :books:: https://dev--9495.org.readthedocs.build/en/9495/

Update template from documentation preview

---

.github/workflows/pr-preview-links.yaml

Avoid the GH Action to break when running due to unescaped characters.

Preview: escape characters

---

readthedocs/core/static-src/core/js/doc-embed/utils.js

Forgot to push these changes
ref https://github.com/readthedocs/readthedocs.org/pull/9515/files#r952983739
---
- User's documentation (`docs`): https://docs--9547.org.readthedocs.build/en/9547/
- Developer's documentation (`dev`): https://dev--9547.org.readthedocs.build/en/9547/

Embedded js: update docstring

---

readthedocs/proxito/tests/handler_404_urls.py
readthedocs/proxito/tests/test_old_redirects.py

Ref https://github.com/readthedocs/readthedocs.org/pull/9557
---
- User's documentation (`docs`): https://docs--9559.org.readthedocs.build/en/9559/
- Developer's documentation (`dev`): https://dev--9559.org.readthedocs.build/en/9559/

Proxito: unskip test

---

readthedocs/search/api.py

Small refactor, to make it easy to re-use with API v3.
---
- User's documentation (`docs`): https://docs--9613.org.readthedocs.build/en/9613/
- Developer's documentation (`dev`): https://dev--9613.org.readthedocs.build/en/9613/

Search: refactor API view

---

docs/dev/design/better-doc-urls-handling.rst
docs/dev/design/theme-context.rst
docs/dev/install.rst
docs/user/advertising/ad-customization.rst
docs/user/config-file/v1.rst
docs/user/environment-variables.rst
docs/user/guides/cross-referencing-with-sphinx.rst
docs/user/guides/intersphinx.rst
docs/user/guides/jupyter.rst
docs/user/guides/pdf-non-ascii-languages.rst
docs/user/intro/getting-started-with-sphinx.rst

Related Issue: https://github.com/readthedocs/readthedocs.org/issues/9502
Related PR: https://github.com/readthedocs/common/pull/156
---
- User's documentation (`docs`): https://docs--9672.org.readthedocs.build/en/9672/
- Developer's documentation (`dev`): https://dev--9672.org.readthedocs.build/en/9672/

Run `blacken-docs` precommit hook on all files

---

readthedocs/organizations/views/private.py

Fix typo in private.py

---

docs/user/tutorial/index.rst

---
- User's documentation (`docs`): https://docs--9761.org.readthedocs.build/en/9761/
- Developer's documentation (`dev`): https://dev--9761.org.readthedocs.build/en/9761/

A few text updates

---

readthedocs/settings/base.py

Required by https://github.com/readthedocs/readthedocs-corporate/pull/1511

Settings: define default MailerLite setting

---

docs/conf.py

Refs https://github.com/sphinx-doc/sphinx/issues/3214
---
- User's documentation (`docs`): https://docs--9812.org.readthedocs.build/en/9812/
- Developer's documentation (`dev`): https://dev--9812.org.readthedocs.build/en/9812/

Disable Sphinx mimetype errors on epub

---

docs/user/security-log.rst

---
- User's documentation (`docs`): https://docs--9811.org.readthedocs.build/en/9811/
- Developer's documentation (`dev`): https://dev--9811.org.readthedocs.build/en/9811/

Docs: Update security log wording

---

docs/user/legal/dpa/subprocessors.rst

---
- User's documentation (`docs`): https://docs--9846.org.readthedocs.build/en/9846/
- Developer's documentation (`dev`): https://dev--9846.org.readthedocs.build/en/9846/

Remove intercom from our DPA list

---

docs/user/faq.rst

---
- User's documentation (`docs`): https://docs--9919.org.readthedocs.build/en/9919/
- Developer's documentation (`dev`): https://dev--9919.org.readthedocs.build/en/9919/

Docs: FAQ title/question tweak

---

readthedocs/core/logs.py

`record.exc_info` is always `None` for some reason. The only reference to record.exc_info I was able to find on structlog is
https://github.com/hynek/structlog/blob/bcfc7f9e60640c150bffbdaeed6328e582f93d1e/src/structlog/stdlib.py#L308-L325, but I wasn't able to find where that is explicitly used, and in all structlog handlers they take the current exception from the event dict, so..
Closes https://github.com/readthedocs/readthedocs-ops/issues/1262
You can test this locally by adding `NewRelicProcessor()` to any processor, like to `LOGGING.formatters.key_value.processors` (settings/base.py), and log anything with `exc_info=True` or call `log.exception`.

Logs: fix exception logging

---

readthedocs/subscriptions/templates/subscriptions/subscription_detail.html
readthedocs/templates/projects/project_advertising.html
readthedocs/templates/projects/project_import.html
readthedocs/templates/projects/project_notifications.html

Surfaced from Transifex notes from translators :tada:

Translations: a few copy issues and translator requests

---

readthedocs/projects/tasks/utils.py

This is just to give us more context when debugging.

Logging: log slugs when at least one of their builds was finished

---

readthedocs/proxito/views/decorators.py

Query for alias and child__slug in one query

Proxito: save one queryset

---

readthedocs/builds/admin.py

Tried to find something for a user, and couldn't search!

Allow searching & filtering VersionAutomationRuleAdmin

---

readthedocs/proxito/views/serve.py

These views need only the project from the unresolved domain, they don't capture a project slug from the URL or anything related.

Proxito: make use un project from unresolved_domain in some views

---

readthedocs/proxito/views/serve.py

- We aren't capturing `project_slug` nor `version_slug` in this view, so I just removed them.
- Make use of the unresolved domain to get the current project,
but we also allow subproject page redirects, so we use the subproject if present.
- In the old functions, we were setting the `path_project_slug` attribute in the request,
this is used in the middleware.

Proxito: use unresolved domain on page redirect view

---

docker-compose.override.yml

It will run Celery beat locally.
Closes #10003

Submodule: update common

---

requirements/deploy.in
requirements/deploy.txt

This reverts commit 5f49b1e4a1ba0c5699579018b93e3ac7b5783f03.

Revert "Requirements: unpin `newrelic` (#10041)"

---

readthedocs/builds/tasks.py
readthedocs/templates/projects/email/build_failed.html
readthedocs/templates/projects/email/build_failed.txt

This updates the links and copy,
to make it a bit nicer.

Make fancy new build failed email

---

readthedocs/subscriptions/signals.py
readthedocs/subscriptions/tests/test_signals.py
readthedocs/subscriptions/utils.py

This is useful in lots of places.

Subscriptions: Set organization name in Stripe

---

readthedocs/analytics/tasks.py

Similar to https://github.com/readthedocs/readthedocs.org/pull/10077

Celery: consider only `PageView` from the last 3 months

---

readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py

An update to https://github.com/readthedocs/readthedocs.org/pull/10022

Catch the base OAuth2Error error, not a custom one

---

docs/user/config-file/v2.rst

---
- User's documentation (`docs`): https://docs--10091.org.readthedocs.build/en/10091/
- Developer's documentation (`dev`): https://dev--10091.org.readthedocs.build/en/10091/

Docs: Update documentation for search.ignore

---

readthedocs/templates/base.html

Use Plausible for dashboard's analytics.
Closes #9604

Analytics: add Plausible to our dashboard

---

docs/user/user-defined-redirects.rst

---
- User's documentation (`docs`): https://docs--10093.org.readthedocs.build/en/10093/
- Developer's documentation (`dev`): https://dev--10093.org.readthedocs.build/en/10093/

Docs: Move a reference and remove an empty paranthesis

---

readthedocs/proxito/tests/test_full.py

Explicitly set the options we are testing on.

Fix .com tests

---

readthedocs/telemetry/tasks.py

Fixes https://read-the-docs.sentry.io/issues/3965191784

Telemetry: typo on Celery task

---

.readthedocs.yml

We have over 400+ errors on them 🙃

Disable PDF builds for now

---

readthedocs/proxito/tests/test_old_redirects.py

This is only available in the new implementation.
Closes https://github.com/readthedocs/readthedocs.org/issues/7552

Redirects: test redirects with projects prefix

---

readthedocs/api/v2/views/proxied.py
readthedocs/api/v3/permissions.py
readthedocs/embed/tests/test_api.py
readthedocs/embed/v3/tests/test_internal_pages.py
readthedocs/embed/v3/views.py
readthedocs/embed/views.py
readthedocs/proxito/tests/test_full.py
readthedocs/proxito/views/mixins.py
readthedocs/rtd_tests/tests/test_middleware.py

Remove some overrides on .com by doing the feature check in .org.

Migrate more feature checks

---

readthedocs/api/v3/tests/mixins.py

API V3: make tests explicit

---

readthedocs/proxito/tests/test_hosting.py

Tests: set production domain explicitly

---

readthedocs/proxito/tests/test_hosting.py

Test explicitly without organizations

---

readthedocs/projects/models.py

* Add prefix to all features labels
* Order alphabetically

Backend: Make Features ordered in a nice way

---

readthedocs/proxito/tests/test_middleware.py

.com tests will probably be fixed with this.

Fix typo in tests

---

.github/ISSUE_TEMPLATE/feature.md

Took some inspiration from pip https://github.com/pypa/pip/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml :)
Closes https://github.com/readthedocs/readthedocs.org/issues/9612

GitHub: add feature request template

---

readthedocs/rtd_tests/tests/test_resolver.py

This commit 02f3e213bf85e1fae1b244117f9e10c6b39f40b9 has what changed

Fix resolver tests on .com

---

readthedocs/search/tests/test_views.py
readthedocs/search/views.py

Fixes https://github.com/readthedocs/readthedocs.org/issues/9969

Search: fix when searching an empty query

---

requirements/deploy.txt
requirements/docker.txt
requirements/pip.in
requirements/pip.txt
requirements/testing.txt

We are hitting an error with socket timeout on production when running long commands.
See https://github.com/docker/docker-py/pull/3125

Requirements: upgrade Docker

---

requirements/docs.in
requirements/docs.txt

Verification of https://github.com/readthedocs/sphinx_rtd_theme/pull/1484

Bump sphinx-rtd-theme to 1.2.2

---

readthedocs/projects/tasks/builds.py

    Add the api_client into the sync_repo task

---

.github/workflows/pip-tools.yaml
tasks.py

When there is the need to add a new dependency,
we have to update each file one by one,
instead of doing that, I'm creating an invoke task.

Add helper task to update dependencies

---

readthedocs/proxito/views/hosting.py

This matches the query executed on FooterAPI.
It will also helps with the performance of the query.
Closes #10429

Addons: improve "active and built Versions" query

---

docs/dev/install.rst

---
- User's documentation (`docs`): https://docs--10476.org.readthedocs.build/en/10476/
- Developer's documentation (`dev`): https://dev--10476.org.readthedocs.build/en/10476/

Docs: typos

---

readthedocs/organizations/filters.py
readthedocs/organizations/views/private.py

This was copied from the project filters and project views. There will
be some more fields to filter on in the future, but just adding it now
to have the elements available to the templates.

Add organization listing filter

---

dockerfiles/Dockerfile

Follows https://github.com/readthedocs/readthedocs-corporate/pull/1630

Development: minor updates to `Dockerfile`

---

readthedocs/api/v2/serializers.py
readthedocs/projects/models.py
readthedocs/proxito/middleware.py
readthedocs/proxito/views/serve.py
readthedocs/rtd_tests/tests/test_backend.py

This reverts commit 1d923d439772c9c1993c848d66cfd83d6b31f7a8.
This introduced a huge performance regression somehow...

Revert "Proxito: test new implementation more broadly (#10599)"

---

readthedocs/locale/ar/LC_MESSAGES/django.po
readthedocs/locale/ca/LC_MESSAGES/django.po
readthedocs/locale/de/LC_MESSAGES/django.po
readthedocs/locale/en/LC_MESSAGES/django.po
readthedocs/locale/es/LC_MESSAGES/django.po
readthedocs/locale/eu/LC_MESSAGES/django.po
readthedocs/locale/fr/LC_MESSAGES/django.po
readthedocs/locale/gl/LC_MESSAGES/django.po
readthedocs/locale/he/LC_MESSAGES/django.po
readthedocs/locale/hu/LC_MESSAGES/django.po
readthedocs/locale/id_ID/LC_MESSAGES/django.po
readthedocs/locale/it/LC_MESSAGES/django.po
readthedocs/locale/ja/LC_MESSAGES/django.po
readthedocs/locale/ko_KR/LC_MESSAGES/django.po
readthedocs/locale/lt/LC_MESSAGES/django.po
readthedocs/locale/nb/LC_MESSAGES/django.po
readthedocs/locale/nl/LC_MESSAGES/django.po
readthedocs/locale/nl_NL/LC_MESSAGES/django.po
readthedocs/locale/pl/LC_MESSAGES/django.po
readthedocs/locale/pt_BR/LC_MESSAGES/django.po
readthedocs/locale/ru/LC_MESSAGES/django.po
readthedocs/locale/sk/LC_MESSAGES/django.po
readthedocs/locale/tr/LC_MESSAGES/django.po
readthedocs/locale/uk/LC_MESSAGES/django.po
readthedocs/locale/vi_VN/LC_MESSAGES/django.po
readthedocs/locale/zh_CN/LC_MESSAGES/django.po
readthedocs/locale/zh_TW/LC_MESSAGES/django.po

Hopefully, this fixes the problem we have in prod with German translation.

Translations: update them all

---

readthedocs/builds/admin.py

these aren't included by default in django

Automation rules: show dates in admin

---

requirements/docs.in
requirements/docs.txt
requirements/testing.txt

- latest Sphinx version available
- 2.0.0rc2 of our theme
- latest `sphinx-notfound-page` release

Requirements: update docs dependencies

---

readthedocs/projects/tasks/search.py
readthedocs/rtd_tests/tests/test_imported_file.py

The storage is located in another path :/

Build indexing: fix indexing of external versions

---

docs/user/guides/setup-single-sign-on-google-email.rst

Ref https://github.com/readthedocs/readthedocs-corporate/pull/1595/
---
- User's documentation (`docs`): https://docs--10774.org.readthedocs.build/en/10774/
- Developer's documentation (`dev`): https://dev--10774.org.readthedocs.build/en/10774/

SSO: update Google Workspace integration docs

---

readthedocs/projects/tasks/builds.py

Ref https://github.com/readthedocs/meta/discussions/129

Build: log directory size to be uploaded

---

readthedocs/api/v2/tasks.py
readthedocs/api/v2/test/test_tasks.py
readthedocs/settings/base.py

Closes https://github.com/readthedocs/readthedocs.org/issues/10764

BuildAPIKey: remove old revoked/expired keys

---

readthedocs/projects/tasks/builds.py

ref https://read-the-docs.sentry.io/issues/4473316150/?project=148442&query=is%3Aunresolved&referrer=issue-stream&stream_index=8

Use get to access build dictionary

---

readthedocs/proxito/views/hosting.py

Solves https://github.com/readthedocs/readthedocs.org/pull/10821#discussion_r1362378808

Addons: expand db query to get the `type` as well

---

.github/workflows/main.yml

Ref https://github.com/readthedocs/readthedocs-corporate/pull/1680/

CI: update circleci API call

---

docs/user/reference/sitemaps.rst

---
- User's documentation (`docs`): https://docs--10899.org.readthedocs.build/en/10899/
- Developer's documentation (`dev`): https://dev--10899.org.readthedocs.build/en/10899/

Mention custom sitemap via robots.txt

---

requirements/deploy.txt
requirements/docker.txt
requirements/pip.in
requirements/pip.txt
requirements/testing.txt

Related to
* https://read-the-docs.sentry.io/issues/4678167578/events/6d1222c116d64d73b58270612486b07d/
* https://github.com/WeblateOrg/weblate/issues/7775
* https://github.com/WeblateOrg/weblate/commit/9e651805573acc0251f34a417decf22c36783161

Requirements: pin `django-ipware<6`

---

readthedocs/proxito/tests/test_hosting.py
readthedocs/proxito/views/hosting.py

Closes https://github.com/readthedocs/addons/issues/218

Addons: get translation from main project

---

readthedocs/api/v2/views/integrations.py
readthedocs/rtd_tests/tests/test_api.py

Ref https://blog.readthedocs.com/security-update-on-incoming-webhooks/

Integrations: hardcode deprecation date for incoming webhooks without a secret

---

readthedocs/projects/tasks/builds.py

Sentry issue: https://read-the-docs.sentry.io/issues/4838646997/

Notifications: add missing `format_values`

---

readthedocs/core/unresolver.py
readthedocs/proxito/middleware.py
readthedocs/settings/base.py

- Weird variation of our domain
- Weird variation of our hostname
- Adding custom response HTTP header
- Elastic POST requests
- Celery missed heartbit

Logging: reduce not useful lines

---

readthedocs/templates/errors/base.html

Related https://github.com/readthedocs/readthedocs-corporate/issues/1711

Analytics: remove them from 404 pages

---

readthedocs/proxito/views/mixins.py

Looks like forgot to run the whole test suite locally for https://github.com/readthedocs/readthedocs.org/commit/be4990b98bb8c8746d0dfe730edc831222c66eed.
I run the whole test suite for the main app, not for proxito :(
Tests are all green now.

Redirects: check if path is None and fix merge of query params

---

docs/user/user-defined-redirects.rst

---
- User's documentation (`docs`): https://docs--11078.org.readthedocs.build/en/11078/
- Developer's documentation (`dev`): https://dev--11078.org.readthedocs.build/en/11078/

Docs: fix redirects example

---

readthedocs/doc_builder/director.py

Related https://github.com/readthedocs/readthedocs.org/pull/11081

Build: check for pre-compiled `build.tools` when using `ubuntu-lts-latest`

---

readthedocs/api/v3/tests/test_organizations.py
readthedocs/api/v3/views.py

closes https://github.com/readthedocs/readthedocs.org/issues/11110

API V3: Only return notifications for a given organization

---

docs/dev/migrations.rst

It seems the rendering was broken, had a ` - #.` when it should be only `#.`. This PR should fix the rendering.
See the original at https://dev.readthedocs.io/en/latest/migrations.html
---
- User's documentation (`docs`): https://docs--11123.org.readthedocs.build/en/11123/
- Developer's documentation (`dev`): https://dev--11123.org.readthedocs.build/en/11123/

Docs: update bullet/item list display

---

docs/user/guides/build/webhooks.rst

---
- User's documentation (`docs`): https://docs--11099.org.readthedocs.build/en/11099/
- Developer's documentation (`dev`): https://dev--11099.org.readthedocs.build/en/11099/

Added a troubleshooting section for webhook

---

readthedocs/projects/views/private.py

This is a single line change and hundreds of lines of linting changes :upside_down_face: 
Relevant commit:
- 383b1765e

Add missing context variable

---

readthedocs/analytics/proxied_api.py
readthedocs/config/config.py
readthedocs/config/tests/test_config.py
readthedocs/doc_builder/environments.py
readthedocs/doc_builder/exceptions.py
readthedocs/rtd_tests/tests/test_doc_builder.py

```
$ gh pr list --json number -L 100 | jq '.[].number' | xargs -I{} gh pr view {} --json files --jq '.files.[].path' | sort | uniq > pr-files.txt
$ git ls-files | grep -v -f pr-files.txt | grep '.py$' | xargs black
```

Lint: more files

---

readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/responses/projects-detail.json
readthedocs/api/v3/tests/responses/projects-list.json
readthedocs/api/v3/tests/responses/projects-list_POST.json
readthedocs/api/v3/tests/responses/projects-subprojects-detail.json
readthedocs/api/v3/tests/responses/projects-subprojects-list.json
readthedocs/api/v3/tests/responses/projects-subprojects-list_POST.json
readthedocs/api/v3/tests/responses/projects-superproject.json
readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json
readthedocs/api/v3/tests/responses/remoterepositories-list.json

APIv3: add `_links.notifications` to `Project` resource

---

docs/user/commercial/single-sign-on.rst
docs/user/guides/setup-single-sign-on-google-email.rst

To better reflect the current state of Google SSO.
ref https://github.com/readthedocs/readthedocs-corporate/issues/1704
---
- User's documentation (`docs`): https://docs--11191.org.readthedocs.build/en/11191/
- Developer's documentation (`dev`): https://dev--11191.org.readthedocs.build/en/11191/

Docs: Update Google SSO docs

---

readthedocs/notifications/messages.py

Related https://github.com/readthedocs/readthedocs.org/issues/11131

Notifications: show "Maxium concurrency limit reached" as `WARNING`

---

readthedocs/api/v2/serializers.py
readthedocs/notifications/querysets.py
readthedocs/rtd_tests/tests/test_api.py

Notifications: de-duplicate them when using APIv2 from builders

---

readthedocs/core/forms.py

Fix bugs with support form

---

readthedocs/projects/tasks/builds.py
readthedocs/projects/tests/mockers.py
readthedocs/projects/tests/test_build_tasks.py

Build: always reset the build before building

---

readthedocs/settings/base.py

See https://github.com/rsinger86/drf-flex-fields?tab=readme-ov-file#customization and https://readthedocs.slack.com/archives/C04SS8XNB6K/p1710794095896149.

API: don't allow expanding recursively

---

readthedocs/config/tests/test_yaml_loader.py
readthedocs/doc_builder/backends/mkdocs.py

This reverts commit 791643f452b872fc985f158a7051f38a65f5f6ce.

Revert "Cleanup: delete `yaml_load_safely` (#11285)"

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--11334.org.readthedocs.build/en/11334/
- Developer's documentation (`dev`): https://dev--11334.org.readthedocs.build/en/11334/

Release 10.25.0

---

readthedocs/projects/views/private.py

If projects is 0, first() will return None.

Beta: fix dashboard when user doesn't have projects

---

readthedocs/proxito/tests/test_hosting.py

Tests: set privacy level to public explicitly

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--11378.org.readthedocs.build/en/11378/
- Developer's documentation (`dev`): https://dev--11378.org.readthedocs.build/en/11378/

Release 10.27.0

---

docker-compose.override.yml
dockerfiles/docker-compose-assets.yml

Version is no longer needed, ref https://github.com/readthedocs/common/pull/215.

Update docker compose files

---

readthedocs/core/middleware.py
readthedocs/rtd_tests/tests/test_middleware.py
readthedocs/settings/base.py
readthedocs/settings/proxito/base.py

Ref https://read-the-docs.sentry.io/issues/5420149653/?project=148442&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=5

Use literal `None` in session cookie samesite setting

---

readthedocs/projects/constants.py
readthedocs/proxito/tests/test_full.py

Proxito: allow serving `zh` (deprecated) language code

---

readthedocs/proxito/views/serve.py
readthedocs/rtd_tests/tests/test_footer.py

Fixes https://github.com/readthedocs/readthedocs.org/issues/11338

Be more defensive in redirect code

---

readthedocs/gold/tests/test_views.py
readthedocs/gold/views.py

Ref https://github.com/readthedocs/ext-theme/issues/407

CSP: Allow inline scripts in gold subscription view

---

readthedocs/gold/tests/test_views.py
readthedocs/gold/views.py

This is breaking our gold view on the org site (no beta). This is since we don't have script-src defined on .com, and when applying the extra rules, we are defining it with just that value.

CSP: apply extra CSP rules only when ext-theme is enabled

---

readthedocs/core/templatetags/readthedocs/socialaccounts.py

ref:
- https://github.com/readthedocs/readthedocs-corporate/issues/1019

Social accounts: Add filter to check if a social account can be disconnected

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--11515.org.readthedocs.build/en/11515/
- Developer's documentation (`dev`): https://dev--11515.org.readthedocs.build/en/11515/

Release 11.4.0

---

docs/user/advertising/advertising-details.rst
docs/user/guides/content/index.rst
docs/user/legal/dpa/subprocessors.rst
docs/user/privacy-policy.rst
docs/user/reference/analytics.rst
readthedocs/analytics/tasks.py
readthedocs/analytics/utils.py
readthedocs/proxito/views/mixins.py

Closes https://github.com/readthedocs/addons/issues/10
---
- User's documentation (`docs`): https://docs--11532.org.readthedocs.build/en/11532/
- Developer's documentation (`dev`): https://dev--11532.org.readthedocs.build/en/11532/

Analytics: remove GA

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--11537.org.readthedocs.build/en/11537/
- Developer's documentation (`dev`): https://dev--11537.org.readthedocs.build/en/11537/

Release 11.5.0

---

docs/user/localization.rst

---
- User's documentation (`docs`): https://docs--11538.org.readthedocs.build/en/11538/
- Developer's documentation (`dev`): https://dev--11538.org.readthedocs.build/en/11538/

Update i18n docs for Sphinx

---

readthedocs/projects/tasks/search.py
readthedocs/search/tests/test_utils.py

This is needed for https://github.com/readthedocs/readthedocs-ext/pull/559

Search: add function to re-index a project

---

readthedocs/organizations/views/base.py
readthedocs/organizations/views/private.py

Missed these in my last PR doing success messages.

Add success messages for Organization views

---

requirements/docs.in
requirements/docs.txt

We are testing the latest `rc` of our theme.

Use theme 3.0.0rc2 (version/language selector)

---

readthedocs/projects/views/private.py

Add project: check YAML file for specific branch

---

readthedocs/projects/views/private.py

Just saw this while I was trying to fix the ordering of projects

Only use django-filters filtering on project dashboard

---

readthedocs/search/tests/test_faceted_search.py

Similar to https://github.com/readthedocs/readthedocs.org/pull/11640/

ES: fix another flaky test

---

readthedocs/subscriptions/constants.py

Closes https://github.com/readthedocs/readthedocs.org/issues/11414

Subscription: better feature description

---

dockerfiles/nginx/proxito.conf.template

Refs https://github.com/readthedocs/readthedocs.org/pull/11680

Fix second Content Type header

---

readthedocs/rtd_tests/tests/test_core_utils.py

This test was timing out because a mock was missing.

Tests: fix slow test

---

docs/user/guides/management/2fa.rst
docs/user/guides/management/index.rst

Ref https://github.com/readthedocs/ext-theme/pull/512
---
- User's documentation (`docs`): https://docs--11716.org.readthedocs.build/en/11716/
- Developer's documentation (`dev`): https://dev--11716.org.readthedocs.build/en/11716/

Docs: document 2fa

---

dockerfiles/nginx/proxito.conf.template
docs/dev/install.rst

Required by https://github.com/readthedocs/common/pull/237

Use addons JavaScript file from Docker container

---

readthedocs/settings/base.py

Closes https://github.com/readthedocs/readthedocs-ops/issues/1569

Allauth: disable account enumeration protection

---

readthedocs/config/config.py
readthedocs/config/models.py
readthedocs/config/utils.py

We aren't using the whole power of pydantic, but it's a good start.

Config file: use pydantic for all config models

---

readthedocs/config/notifications.py

Noticed this polling the notification HTML tags we're depending on

Fix bug with notification HTML

---

readthedocs/doc_builder/director.py
readthedocs/projects/tests/test_build_tasks.py

This is required for Cargo builds,
as I hit here:
https://app.readthedocs.org/projects/test-builds/builds/26564308/

Add Rust reshim

---

readthedocs/organizations/templates/organizations/organization_choose.html
readthedocs/organizations/tests/test_views.py

Matches https://github.com/readthedocs/ext-theme/pull/549/
This also needs https://github.com/readthedocs/ext-theme/pull/552

Fix ext-theme tests

---

readthedocs/templates/socialaccount/snippets/provider_list.html

Closes https://github.com/readthedocs/readthedocs-ops/issues/1580, requires https://github.com/readthedocs/ext-theme/pull/555

Social accounts: link Bitbucket to new dashboard

---

docs/user/examples.rst
docs/user/intro/antora.rst
docs/user/intro/doctools.rst

---
- User's documentation (`docs`): https://docs--11947.org.readthedocs.build/en/11947/
- Developer's documentation (`dev`): https://dev--11947.org.readthedocs.build/en/11947/

Add Antora docs page

---

docs/user/guides/importing-private-repositories.rst

Fixes https://github.com/readthedocs/readthedocs.org/issues/9426
---
- User's documentation (`docs`): https://docs--11966.org.readthedocs.build/en/11966/
- Developer's documentation (`dev`): https://dev--11966.org.readthedocs.build/en/11966/

Add a warning about VCS SSO to import guide

---

readthedocs/projects/admin.py

This reverts commit 9b1e784ef14fe82ae5ac0652f65d7a63bba065e0.
Not sure why this broke..

Revert "Show slug on AddonsConfigAdmin (#11974)"

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_project_forms.py

Discussion
https://github.com/readthedocs/readthedocs.org/pull/11977#discussion_r1945729636

File Tree Diff: normalize ignore files

---

readthedocs/projects/views/private.py

missed this one, looks like we don't have test for this code...

Import: fix session

---

readthedocs/settings/docker_compose.py

Increase docker memory limit

---

.github/workflows/pr-preview-links.yaml
docs/conf.py

- **Update PR links to use single-version**
- **Use string**
- **WHy won't it run**
- **Small docs change to =test**
---
- User's documentation (`docs`): https://docs--12028.org.readthedocs.build/en/12028/
- Developer's documentation (`dev`): https://dev--12028.org.readthedocs.build/en/12028/

update pr links

---

readthedocs/settings/base.py
readthedocs/settings/docker_compose.py
readthedocs/storage/__init__.py
readthedocs/storage/s3_storage.py

We are not using this storage backend anymore,
we should delete the buckets as well.

Storage: remove build environment storage

---

readthedocs/doc_builder/director.py
readthedocs/projects/models.py
readthedocs/projects/tasks/builds.py
readthedocs/rtd_tests/tests/test_backend.py
readthedocs/rtd_tests/utils.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/base.py

Closes https://github.com/readthedocs/readthedocs.org/issues/11955

VCS: pass a version object to git provider

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--12125.org.readthedocs.build/12125/
- Developer's documentation (`dev`): https://dev--12125.org.readthedocs.build/12125/

Release 12.0.5

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--12170.org.readthedocs.build/12170/

Release 13.1.1

---

docs/user/intro/doctools.rst

---
- User's documentation (`docs`): https://docs--12180.org.readthedocs.build/12180/
- Developer's documentation (`dev`): https://dev--12180.org.readthedocs.build/12180/

Update 'built in' info

---

docs/user/faq.rst

Closes #11239
Add a note about redirects. :)
---
- User's documentation (`docs`): https://docs--12184.org.readthedocs.build/12184/
- Developer's documentation (`dev`): https://dev--12184.org.readthedocs.build/12184/

Update faq about changing project slugs

---

readthedocs/projects/forms.py
readthedocs/projects/models.py

This is also going to be used in the templates

Project: add is_github_app_project helper method

---

readthedocs/payments/tests/utils.py

Required by https://github.com/readthedocs/readthedocs-corporate/pull/2002

Tests: call `super().setUp()`

---

readthedocs/subscriptions/event_handlers.py
readthedocs/subscriptions/tests/test_event_handlers.py

Fixes https://read-the-docs.sentry.io/issues/6636343464/

Gold: `subscription` is the subscription id as string

---

readthedocs/payments/tests/test_utils.py
readthedocs/payments/utils.py

ref https://read-the-docs.sentry.io/issues/6642606768/?project=161479&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

Subscriptions: fix canceling subscription

---

CHANGELOG.rst
docs/conf.py
package.json
readthedocs/__init__.py
setup.cfg

---
- User's documentation (`docs`): https://docs--12252.org.readthedocs.build/12252/
- Developer's documentation (`dev`): https://dev--12252.org.readthedocs.build/12252/

Release 13.5.0

---

docs/user/environment-variables.rst
docs/user/explanation/configuration-file.rst
docs/user/guides/set-up-single-sign-on-saml.rst

- Fix style filename
- Matches on "pull request"
- Fix suggestions on SSO
- Apply some fixes introduced last PR
---
- User's documentation (`docs`): https://docs--12260.org.readthedocs.build/12260/
- Developer's documentation (`dev`): https://dev--12260.org.readthedocs.build/12260/

Try some more vale fixes

---

readthedocs/settings/base.py
readthedocs/settings/docker_compose.py
readthedocs/settings/test.py

Attempt to fix https://github.com/readthedocs/readthedocs-ops/issues/1650

Use hashed static files

---

readthedocs/notifications/messages.py

Missed this one in https://github.com/readthedocs/readthedocs.org/pull/12282

Fix blog post link

---

readthedocs/organizations/forms.py
readthedocs/organizations/tests/test_forms.py

Required by https://github.com/readthedocs/ext-theme/issues/25

Organizations: show the `slug` field on creation

---

readthedocs/core/templatetags/readthedocs/socialaccounts.py

ref https://github.com/readthedocs/ext-theme/pull/631

Add user_has_github_app_account templatetag

---

readthedocs/doc_builder/environments.py
readthedocs/projects/models.py

Closes https://github.com/readthedocs/readthedocs.org/issues/12293

Remove API_LARGE_DATA feature flag

---

readthedocs/vcs_support/backends/git.py

Ref:
- https://read-the-docs.sentry.io/issues/6721034615/events/c4bd08bbaad24af685d07138eda098df/?project=161479
- https://read-the-docs.sentry.io/issues/6721034615/events/5f3d77782eb747dda25dbbff11524637/?project=161479

Add more known errors to the SSH check

---

readthedocs/api/v3/serializers.py
readthedocs/proxito/tests/test_hosting.py
readthedocs/proxito/views/hosting.py

~10ms off
I also found an optimization for the projects API, but will do that in a separate PR.

Addons: improve performance of translations

---

readthedocs/projects/models.py

These flags are not used in the code anymore.

Project: remove old/deprecated feature flags

---

readthedocs/projects/models.py

Use attributes instead of putting the data into the message.

Small log line fix

---

requirements/deploy.txt
requirements/docker.txt
requirements/pip.in
requirements/pip.txt
requirements/testing.txt

Ref https://github.com/readthedocs/readthedocs-corporate/pull/2031

Upgrade django-allauth

---

readthedocs/core/templatetags/privacy_tags.py

This is already done in the query iself
https://github.com/readthedocs/readthedocs.org/pull/12385

Profile: don't duplicate annotation in queryset

---

readthedocs/oauth/services/base.py

ref https://read-the-docs.sentry.io/issues/6837961607/?alert_rule_id=229005&alert_timestamp=1756241038110&alert_type=email&environment=production&notification_uuid=257d21bb-47d7-4fb3-9057-b7136b51998b&project=148442&referrer=alert_email

Git services: check for 403 status code

---

docs/user/guides/private-submodules.rst
docs/user/guides/pull-requests.rst
docs/user/intro/add-project.rst
docs/user/reference/git-integration.rst

Mostly extracted from https://github.com/readthedocs/readthedocs.org/pull/12114
Closes https://github.com/readthedocs/readthedocs.org/issues/12129

Docs: update docs to mention GitHub app

---

readthedocs/projects/tasks/utils.py

Just to avoid breaking builds while deploying tomorrow

Avoid breaking change on task signature
