- media/css/readthedocs-doc-embed.css
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
* A few visual tweaks
* Adds a box with a background color around the ad so as to separate it from other content.
* Links are always underlined.
* Text in footer ads is a bit smaller
* Slightly increases the padding around the ad container
* The "sponsored" and "ads served ethically" text is blended a bit with the background so it emphasizes the actual ad. It is also always centered even on footer ads (previously it was right aligned).
* Adds a dark theme for ads that looks good on the RTD theme but could be used elsewhere if needed.
Note: this doesn't change any of the CSS classes for of our ads. Ad blockers will continue to work as normal. This means we shouldn't need to contact our partners at Eyeo/AdblockPlus with respect to "acceptable ads".
> Make ads more obvious that they are ads

- requirements/docs-lint.txt
Sphinx 1.8 was released today, somehow is incompatible with rstcheck see https://travis-ci.org/rtfd/readthedocs.org/builds/427828516?utm_source=github_status&utm_medium=notification
> Pin sphinx to a compatible version

- docs/alternate_domains.rst
- docs/faq.rst
- docs/features.rst
- docs/localization.rst
- docs/symlinks.rst
CNAME refers to a DNS construct, not an RTD construct. Referring to these as
"custom domain" instead makes this information easier to understand/find.
Also includes some random cleanup of copy around the CNAME -> custom domain
changes.
> Change mentions of "CNAME" -> custom domain

- requirements/pip.txt
Close #4640 
I opened https://github.com/rtfd/readthedocs.org/issues/4643 to track the celery upgrade
> Downgrade celery

- docs/api/v1.rst
- docs/builds.rst
- docs/design/yaml-file.rst
- docs/gsoc.rst
- docs/guides/manage-translations.rst
- readthedocs/config/tests/test_utils.py
- readthedocs/core/symlink.py
- readthedocs/notifications/storages.py
- readthedocs/notifications/views.py
- readthedocs/restapi/utils.py
- readthedocs/restapi/views/task_views.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- readthedocs/vcs_support/backends/git.py
Trying [codespell](https://github.com/codespell-project/codespell), man that tool is awesome
> Fix some typos in docs and code

- media/css/readthedocs-doc-embed.css
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This adds the options for projects to opt-in to have an ad placement in a specific spot on their docs by adding a `<div id="ethical-ad-placement"></div>` in a specific place.
- For projects where we have a revenue share in place -- something I'm trying to grow -- this allows them to put the ads in a better spot and make more money.
- This puts projects in control of where ads go.
- Allow specifying different ad types (eg. text-only, footer ads, etc.). I envision doing this by adding `data-ad-type` attributes on the `<div>`. Currently this only does left-navigation ads.
> Create an explicit ad placement

- docs/privacy-policy.rst
This is just a typo and doesn't warrant a date update on the privacy policy as the substance hasn't changed.
> Fix a typo in the privacy policy

- readthedocs/projects/tasks.py
It got removed a bit early and if we don't set an outcome, search files
aren't synced correctly.
Refs #4638
> Put search step back into project build task

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
This is on top of https://github.com/rtfd/readthedocs.org/pull/4482, it should be merged after.
New changes are from 3f311ef 
Ref https://github.com/rtfd/readthedocs.org/issues/4219
> Implement mkdocs key from v2 config

- readthedocs/rtd_tests/tests/test_config_integration.py
Previous tests were mocking the `load_config` function, now we are testing it for real
Related to https://github.com/rtfd/readthedocs.org/pull/4379
> More robusts tests for requirements_file and conda_file

- readthedocs/search/tests/conftest.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/tests/test_faceted_search.py
- readthedocs/search/tests/test_views.py
- readthedocs/settings/test.py
This needs additional work to then also fix the travis tests.
> Remove search autosync from tests so local tests work

- readthedocs/search/parse_json.py
- readthedocs/search/tasks.py
This makes sure we’re using ID’s from the same queryset,
otherwise we end up indexing the wrong objects.
> Fix the queryset used in chunking

- readthedocs/search/documents.py
- readthedocs/search/management/commands/reindex_elasticsearch.py
Also try and fix a bug with queue selection around reindexing.
> Fix bug where we were not indexing Sphinx HTMLDir projects

- readthedocs/search/documents.py
- readthedocs/settings/base.py
https://www.elastic.co/guide/en/elasticsearch/reference/current/_basic_concepts.html#getting-started-shards-and-replicas
https://www.elastic.co/guide/en/elasticsearch/guide/current/replica-shards.html#img-three-nodes
We need to change the `replica` dynamically
you can run following command in django shell to change the replica
```python
from readthedocs.search.documents import page_conf, page_index
page_index.put_settings(page_conf['settings'])
```
> Tuning elasticsearch shard and replica

- media/css/readthedocs-doc-embed.css
#4628 shrank the size marginally of footer ads and now I think they are too small. I think the text can safely be the same size as the sidebar ads and most of the rest of the document (14px).
> Increase footer ad text size

- readthedocs/projects/tasks.py
This PR used to have a test case but it wasn't accurate. I decided to remove it and leave this small piece of code untested (send an email on unhandled failures). It shouldn't be terrible and it does fix an issue that our customer are having at the moment.
We can improve this later when a re-work is done around the `UpdateDocsTask` and how all the steps of this task are managed.
> Send notifications when generic/unhandled failures

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
While replicating #3515, I noticed that the other "edit" link (at the float version menu) was wrong https://github.com/rtfd/readthedocs.org/issues/3515#issuecomment-358110500
Fixes #1917
> Use relative path for docroot on mkdocs

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
> Fix broken url on sphinx projects

- readthedocs/search/tests/test_api.py
- requirements/lint.txt
Since we import this file from Corporate site without defining this URL name, this blow up. By defining it inside the __init__ method we workaround this.
> Define the doc_search reverse URL from inside the __init__ on test

- readthedocs/core/management/commands/update_repos.py
- readthedocs/projects/management/commands/import_project_from_live.py
> Remove -r option from update_repos command

- readthedocs/core/utils/tasks/__init__.py
- readthedocs/core/utils/tasks/public.py
- readthedocs/core/utils/tasks/retrieve.py
- readthedocs/oauth/apps.py
- readthedocs/oauth/tasks.py
- readthedocs/restapi/views/task_views.py
- readthedocs/rtd_tests/tests/test_celery.py
~Still wip, I need to update some docstrings~, but I already tested it, and it works :)
Fix #3974 and ref to #3973
> Refactor PublicTask into a decorator task

- docs/index.rst
- docs/roadmap.rst
This formalized publicly some of our discussions around roadmap and issue
priority.
Fixes #4233
> Add docs on our roadmap process

- readthedocs/core/middleware.py
This happens a ton,
and isn't valuable at all to keep around.
> Reduce the logging we do on CNAME 404

- requirements/lint.txt
Read the Docs corporate site still uses Python 2.
Reference: https://github.com/rtfd/readthedocs-corporate/pull/395
> Lint requirement file for py2

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
Close #4455 
~~I only need to add some docs. And maybe refactor a little~~.
> Strict validation in configuration file (v2 only)

- readthedocs/builds/syncers.py
We get a ton of these,
but never look at them.
I don't really know if we can fix this,
but lets stop spamming Sentry
> Remove logging verbosity on syncer failure

- readthedocs/rtd_tests/fixtures/spec/v2/schema.yml
- readthedocs/rtd_tests/tests/test_build_config.py
> Extend install option from config file (v2, schema only)

- readthedocs/templates/base.html
I've seen that the link for PagerDuy in the footer section was wrong.
This pull request will fix it ;)
> Fixed link of PagerDuty

- readthedocs/rtd_tests/tests/test_project_symlinks.py
There was a [change](https://github.com/rtfd/readthedocs.org/commit/ef6a05916c440916fba9755388b36ba95e98b0e4#diff-31a1317fe6aaf4de559c18d25fd89323L68) which causes the symlink test suite to fail on OSX.
The problem is caused by:
* `tempfile.mkdtemp` returns a path under `/var/folders`
* By default on OSX `/var` is a symlink to `/private/var`
* As a result, `os.path.realpath(TEMP_SITE_ROOT) != TEMP_SITE_ROOT` and the expected paths don't match [here](https://github.com/rtfd/readthedocs.org/blob/9d6aabb760d870288494d3ef665323a11912dbe4/readthedocs/rtd_tests/tests/test_project_symlinks.py#L42)
I'm running OSX 10.13.16.
> Fixes an OSX issue with the test suite

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
When building a project, if it tooks more than `REPO_LOCK_SECONDS` and while building after that time another build is triggered for the same Version and the same builder takes the task the lock will be considered "old" and remove and taken by the new build.
This will end up in a collision when accessing the files and it could raise an exception like `IOError: [Errno 26] Text file busy`. Also, it could fail with another unexpected reasons.
This PR increases the `max_lock_age` to the same value assigned for the project to end the build in order:
* custom container time limit or,
* `settings.DOCKER_LIMITS['time']` or,
* `settings.REPO_LOCK_SECONDS` or,
* 30 seconds
Related to #1609
> Use Docker time limit for max lock age

- docs/builds.rst
- docs/guides/mkdocs-old-versions.rst
Guide to help users that weren't pinning a version of `mkdocs` but were relying on `mkdocs==0.15`. Since we upgrade our default version installed, they will find that their docs are not building anymore.
This guide helps them to keep building their docs on Read the Docs showing the workarounds needed.
I'm not really happy with the document and how it's written but I think it communicates what we need.
Related to #4041 and #4556
> Guide explaining how to keep compatibility with mkdocs

- readthedocs/projects/forms.py
This is required to hide the `Always use HTTPS` field in Corporate site.
> Allow to extend the DomainForm from outside

- readthedocs/core/utils/__init__.py
I think that this commit introduced the problem: https://github.com/rtfd/readthedocs.org/pull/2765/commits/0432ee8f0c897a9f60a7d8813275924f9e12487c (this is the PR: https://github.com/rtfd/readthedocs.org/pull/2765)
The problem is that it's always re-raising the exception, even if the problem is the one that we checking in the `if`. I think this has generated 4.2k Sentry logs: https://sentry.io/read-the-docs/readthedocs-org/issues/628363742/?query=is:unresolved
> Do not re-raise the exception if the one that we are checking

- readthedocs/core/utils/__init__.py
- readthedocs/restapi/urls.py
- readthedocs/restapi/views/core_views.py
This isn't used or documented, it was added here https://github.com/rtfd/readthedocs.org/commit/3cada1dcf8ee5435aaa01a4899a16e44939743f1
This should be merged after #4730
Related https://github.com/rtfd/readthedocs.org/issues/1991#issuecomment-424875197
> Remove /cname endpoint

- readthedocs/builds/syncers.py
It doesn't love that a new positional argument was added in a subclass. I'm not sure if there's a better way to make this work in our lint setup.
> Make storage syncers extend from a base class

- readthedocs/core/middleware.py
Ref https://github.com/rtfd/readthedocs.org/pull/4730#issuecomment-430226642
> Upgrade logs from debug on middleware

- docs/design/index.rst
This still doesn't link them from anywhere,
but at least you can browse them at `/design/`.
> Add an index page to our design docs.

- readthedocs/projects/forms.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_project_forms.py
Very small PR that to avoid importing invalid project names.
> Validate the slug generated is valid before importing a project

- .codecov.yml
- .coveragerc
- requirements/testing.txt
- tox.ini
Our coverage is good, and I would love to maintain it like that. The coverage report is 0% on management commands (not sure if we care to have tests for that)
What change? Almost nothing, devs can still run normal tests, as usual. The only thing is that Travis will fail if the coverage goes down 79% (our current coverage).
We can increase the coverage later, but keeping it >=79% is a good first step.
If you want to check the coverage locally, you'll need to run tox like this `tox -e py36,coverage`
> Run coverage on travis

- readthedocs/core/views/hooks.py
Although this endpoint is deprecated, we still receive request on it and many of them are invalid and do not contains the branch name or similar. This is logging a lot under Sentry and kill our quota.
> Do not log as error a webhook with an invalid branch name

- readthedocs/core/fixtures/eric.json
- readthedocs/core/middleware.py
- readthedocs/projects/fixtures/test_data.json
- readthedocs/settings/base.py
- requirements/pip.txt
Closes #4174 
Things we need to check:
> Update to Django 1.10

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/doc_builder/config.py
fix #4388 and also no~fi x #4401~
> Remove hardcoded constant from config module

- docs/guides/mkdocs-old-versions.rst
Today I realize that it's better to PIN this "just in case" that leave it there.
If we pin the `markdown` we can still use the old way to define extensions. Yay!
> Pin missing dependency for the MkDocs guide compatibility

- readthedocs/core/views/__init__.py
- readthedocs/gold/models.py
- readthedocs/integrations/models.py
Remove unused function and update usage of `old_div` to `//` instead.
> Cleanup old code (remove old_div)

- readthedocs/core/migrations/0005_migrate-old-passwords.py
We apparently can't use `set_unusable_password` in a migration. So instead, we will just use its [equivalent](https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/base_user.py#L120-L122).
> Migrate old passwords without "set_unusable_password"

- readthedocs/config/find.py
- readthedocs/config/tests/test_config.py
- readthedocs/config/tests/test_find.py
> Remove logic around finding config file inside directories

- readthedocs/__init__.py
Do not import all the Celery app (which import the Django settings) when it's not needed.
Required by https://github.com/rtfd/readthedocs-ops/pull/431
> Do not import the Celery worker when running the Django app

- readthedocs/core/static-src/core/js/doc-embed/sphinx.js
Fix for jQuery call 
```
Uncaught ReferenceError: jquery is not defined
at Object.init (readthedocs-doc-embed.js:formatted:1676)
at HTMLDocument.<anonymous> (readthedocs-doc-embed.js:formatted:1859)
at j (jquery.min.js:formatted:1462)
```
> Fix for jQuery in doc-embed call

- readthedocs/restapi/client.py
- readthedocs/rtd_tests/tests/test_restapi_client.py
The DRF parser expect a file-like object containing bytes while
we are passing it a unicode string. The outcome of this is
slumber serialization not working and returning plain bytes
instead of deserialized data.
The fix is trivial and it's just using slumber code for
parsing instead of providing our own.
For reference after making slumber dump exceptions instead of
swallowing them here's the root cause:
```
Traceback (most recent call last): [celery.redirected:235]
File "/venv/lib/python3.5/site-packages/slumber/__init__.py", line 134, in _try_to_serialize_response
return stype.loads(resp.content.decode(encoding)) [celery.redirected:235]
File "/home/readthedocs/restapi/client.py", line 28, in loads
return JSONParser().parse(data) [celery.redirected:235]
File …
```
> restapi/client: don't use DRF parser for parsing

- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_api.py
- requirements/pip.txt
Added filter fields to api/v2/build/ endpoint to filter according to the commit hashes (Using filter backends).
> [Fixed #872] Filter Builds according to commit

- contrib/add-project.py
To address #2725, in this commit, I've put together a script that creates a RTD project based on a GitHub repo checkout. It makes some assumptions, but attempts to provide flexibility for any user to use.
It currently requires Python 3.6+ and several 3rd party libraries (declared in the script). It can be invoked with `rwt -- scripts/add-project.py` (pass `--help` to test invocation without execution).
I'm hoping this script can be included for publication, reference, and possible iterative improvement.
Please let me know if there's anything more you would like to see to include this work in the project.
> Script for creating a project

- docs/.rstcheck.cfg
- docs/conf.py
- docs/install.rst
- requirements/pip.txt
This is my second attend to improve the installation guide (first one #3614), I have take some notes from https://github.com/rtfd/readthedocs.org/pull/3614#issuecomment-365842034, https://github.com/rtfd/readthedocs.org/pull/3614#issuecomment-365844940, https://github.com/rtfd/readthedocs.org/pull/3488#issuecomment-366087951.
I try to reduce the _trying to teach how to use_ for _provide useful links_ and be a little more _lineal_ on the steps. And remove lots of _notes_ that are really necessary, but give the impression of be optional.
Please let me know any issues with the English :)
Closes #2246
> Improve installation guide

- readthedocs/core/views/__init__.py
- readthedocs/rtd_tests/tests/test_redirects.py
> Avoid infinite redirection

- readthedocs/gold/forms.py
- readthedocs/gold/views.py
- readthedocs/rtd_tests/tests/test_gold.py
Related Issue: #4777 
Final Result:
> Make form for adopting project a choice field

- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_project_forms.py
Fixes #4844 
More background on #1170
So, previously this wasn't so important, users could just change the `default_branch` to whatever they want (master in this case). But, with https://github.com/rtfd/readthedocs.org/pull/4710 they can't do that anymore and the only solution is to recreate the project.
I know this isn't a common case (changing VCS), but if the user chooses by mistake the wrong VCS when creating the project, then the user is in trouble.
> Allow to change project's VCS

- readthedocs/core/middleware.py
- readthedocs/rtd_tests/tests/test_middleware.py
> Raise 404 at SubdomainMiddleware if the project does not exist.

- readthedocs/projects/tasks.py
Instead of LockTimeout exception we are raising VersionLockedError instead. This change introduced a bug that notification started being sent again when a Version was locked and this was really annoying.
> Do not send notification on VersionLockedError

- readthedocs/projects/migrations/0030_change-max-length-project-slug.py
- readthedocs/projects/models.py
This updates the just-merged migration to handle name as well
> Shorten project name to match slug length

- .readthedocs.yml
- tox.ini
We'll need to activate the `ALLOW_V2_CONFIG_FILE` flag on the project
> Start testing config v2 on our project

- readthedocs/builds/models.py
- readthedocs/restapi/templates/restapi/footer.html
- readthedocs/rtd_tests/tests/test_footer.py
When the version is a tag, user's can't edit that version, only branches can be edited.
Currently, on the rtd theme we only generate the view link (the text says edit, but it's a view link).
As mention here https://github.com/rtfd/readthedocs.org/issues/1820#issuecomment-434887315, there is some code that was never used https://github.com/rtfd/readthedocs.org/blob/0f5d979c221da7140138359fc06660ebec6fff9b/readthedocs/doc_builder/backends/sphinx.py#L127-L132
As we don't use that on the theme, I think it can be removed (or maybe make it available to the theme?). IMO, we are fine deleting that code, the theme does a good job showing only the view link (users can figure out how to edit on each platform).
Close #1820
> Hide "edit on" when the version is a tag

- readthedocs/projects/tasks.py
> Change 'VerisionLockedTimeout' to 'VersionLockedError' in comment.

- readthedocs/doc_builder/exceptions.py
Now that we move the config file to the rtd code, and that we do all the validation stuff inside the config module, this message isn't correct, because a user can build their project using only the config from the web admin, but internally we use the config module for some validations.
Fix #4401
> Generic message for parser error of config file

- readthedocs/builds/views.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_views.py
Fixes #4359.
Also sorted imports on running pre-commit hook and some minor modifications to comply with flake8.
> Redirect to build detail post manual build

- readthedocs/doc_builder/python_environments.py
Turns out we do support shell expansions in the CWD :)
Closes #4808
> Use $HOME as CWD for virtualenv creation

- readthedocs/projects/models.py
Related https://sentry.io/read-the-docs/readthedocs-org/issues/754432613/?query=is:unresolved
> Check if latest exists before updating identifier

- readthedocs/settings/base.py
RTD is using django-guardian (version: 1.4.9).
`ANONYMOUS_USER_ID` is deprecated ([changelog](https://django-guardian.readthedocs.io/en/stable/develop/changes.html#release-1-4-2-mar-09-2016)) in `1.4.2`
According to the new configurable variables, we should use `ANONYMOUS_USER_NAME`, whose default value is already set to `"AnonymousUser"` (Read [here](https://django-guardian.readthedocs.io/en/stable/configuration.html#anonymous-user-name)). So, I think that there is no need to set it again in our `settings/base.py`
> Update django-guardian settings

- readthedocs/settings/base.py
> Disable django.security.DisallowedHost from logging

- readthedocs/config/config.py
- readthedocs/config/parser.py
- readthedocs/config/tests/test_config.py
- readthedocs/config/tests/test_parser.py
- readthedocs/doc_builder/config.py
- readthedocs/rtd_tests/tests/test_config_integration.py
> Remove support for multiple configurations in one file

- readthedocs/search/documents.py
- readthedocs/settings/base.py
- readthedocs/settings/test.py
As we will have 3 nodes, I think this conguration is good enough for our use case.
Moreover, the index will be sorted according to `project`. so I hope it will be faster.
Overall, I think it will mitigate the timeout issue that we were facing.
@ericholscher r?
> Tuning Elasticsearch for search improvements

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/bzr.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/backends/hg.py
- readthedocs/vcs_support/backends/svn.py
So, I can see that the update commands of the other VCS' do the same that the first part of checkout. And we don't use `update` in any part of the code.
Closes #4259
And half fixes (#4890), right now users without a `master` branch are blocked and can't do anything to build their docs (previously users could put any text on the `default branch`, but now it's a select field).
With this change, the first build will fail, but now they can select another version as `default branch`.
Still wip, a lot tests will break probably and I neeed to do the same with the other VCS'
> Separate update and checkout steps

- readthedocs/builds/version_slug.py
The queryset gets evaluated here, we don't need the whole objects
https://docs.djangoproject.com/en/2.1/ref/models/querysets/#when-querysets-are-evaluated
> Use .exists in queryset

- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/vcs_support/backends/git.py
Use `gitpython` to get repository branches instead of our custom/hacky csv parser.
With this change, we loose the output from `git branch -r` command shown to the user under the build output.
These changes need more QA:
- repo with Unicode branch imported properly in RTD running Py2 _and_ Py3
- docs for that specific branch are serving without problem (may be affected by #1410)
NOTE: this PR also changes how the branches are parsed and I'm not 100% sure that removing the `origin/` from its name is enough and exactly the same that we were doing before
Ref: #2997 #4052
Fixes: #3060
> Support git unicode branches

- readthedocs/core/symlink.py
- readthedocs/projects/utils.py
Close #3540
I did a couple of builds and everything looks good.
> Remove repeated and dead code

- readthedocs/core/forms.py
- readthedocs/rtd_tests/tests/test_profile_views.py
> Validate profile form fields

- pytest.ini
- readthedocs/api/utils.py
- readthedocs/builds/querysets.py
- readthedocs/core/utils/tasks/permission_checks.py
- readthedocs/notifications/storages.py
- readthedocs/oauth/querysets.py
- readthedocs/projects/querysets.py
- readthedocs/projects/views/public.py
- readthedocs/restapi/serializers.py
- readthedocs/restapi/urls.py
- readthedocs/restapi/views/integrations.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/base.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/rtd_tests/tests/test_subprojects.py
- readthedocs/search/views.py
Adapt some parts of the code to remove warnings and ignore Django 2.0 and external dependencies warnings also.
We do not control external dependencies warnings and we can't upgrade them. We rely on them to update their code before we migrate to Django 2.0. Before migrating to Django 2.0 we will need to remove this `ignore` filters and run all the tests to check what dependencies are still not compatible. In the meantime, we remove all this garbage from the summary output.
> Adapt code to remove and ignore warnings

- readthedocs/vcs_support/backends/git.py
Close #1888 
Tested this locally with a couple of projects, and I didn't find any problems. I also experiment with this outside rtd. The only downside I can see is people using an extension that needs to read the git history. So, this still needs a decision:
1) Merge as it is
2) Add a feature flag and test some projects before
3) Make this a project option, so users can enable/disable it (we can have this on by default)
> Shallow git clone

- requirements/pip.txt
See https://github.com/sebleier/django-redis-cache/pull/162 and https://stackoverflow.com/questions/53331405/django-compress-error-invalid-input-of-type-cachekey
> Pin redis to the current stable and compatible version

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
> Install latest version of pip

- media/css/core.css
Django-storages has a [bug](https://github.com/jschneier/django-storages/issues/609) in the AzureStorage that has problems with `?` and `=` in URLs. This gets triggered when these files are post-processed with Django's [ManifestFilesMixin](https://docs.djangoproject.com/en/2.1/ref/contrib/staticfiles/#manifestfilesmixin)
> Workaround for a django-storages bug

- docs/yaml-config.rst
This removes the `-e` option from [yaml config documentation](https://docs.readthedocs.io/en/latest/yaml-config.html) which states that pip install is run in editable mode
Closes #4944
> Remove -e option

- readthedocs/settings/test.py
- readthedocs/vcs_support/backends/git.py
We don't care about branches local to us.
This causes bugs where a local and remote branch have the same name,
and we sync `stable` in and endless loop.
Fixes #4980
> Only use remote branches for our syncing.

- readthedocs/core/signals.py
- readthedocs/rtd_tests/tests/test_middleware.py
Currently, if any documentation project tries to use our APIv2 from a custom domain by doing an AJAX request, it will be blocked because of CORS.
This PR adds a new checking for this by allowing CORS on all the URLs that start with `/api/v2/` and the HTTP_ORIGIN header is a known Domain in our platform.
Raised at https://github.com/humitos/sphinx-version-warning/issues/23
> Allow all /api/v2/ CORS if the Domain is known

- readthedocs/builds/views.py
- readthedocs/core/middleware.py
- readthedocs/gold/views.py
- readthedocs/integrations/admin.py
- readthedocs/oauth/models.py
- readthedocs/oauth/notifications.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/profiles/views.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/base.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
- readthedocs/restapi/views/task_views.py
- readthedocs/rtd_tests/tests/projects/test_admin_actions.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_gold.py
- readthedocs/rtd_tests/tests/test_middleware.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/rtd_tests/tests/test_profile_views.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/rtd_tests/tests/test_sync_versions.py
- readthedocs/rtd_tests/tests/test_urls.py
- readthedocs/rtd_tests/tests/test_views.py
- readthedocs/search/tests/test_views.py
**django.core.urlresolvers** module is deprecated in Django 1.10 ([Misc. updates of Django 1.10](https://docs.djangoproject.com/en/dev/releases/1.10/#id3)) and is completely removed in Django 2.0 ([Deprecation removed in 2.0](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-0)).
Also, I didn't find docs for **django.urls.base** but I have verified that **[get_urlconf()](https://github.com/django/django/blob/2ea1e0e58d3e0afffda4308a45e6c96693f3a7c9/django/urls/base.py#L143)** and **[set_urlconf()](https://github.com/django/django/blob/2ea1e0e58d3e0afffda4308a45e6c96693f3a7c9/django/urls/base.py#L131)** are present in **django.urls.base**
> Remove deprecated imports from "urlresolvers"

- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/settings/test.py
- readthedocs/vcs_support/backends/git.py
> Remove `LOCAL_GIT_BRANCHES` from settings

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This is a tweak to increase the sidebar ad priority (vs footer ad priority) if the sidebar isn't long. Essentially, this change will prioritize showing a sidebar ad if the sidebar ad would be visible.
> Tweak sidebar ad priority

- readthedocs/vcs_support/backends/git.py
> Replace git status and git submodules status for gitpython

- readthedocs/builds/views.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/querysets.py
- readthedocs/projects/views/private.py
- readthedocs/restapi/views/integrations.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_core_utils.py
- readthedocs/rtd_tests/tests/test_project_querysets.py
Allow to make the check extensible from output by defining an `is_active` method in the QuerySet. Besides, returns a proper HTTP status code and message when the project is disabled and the build is triggered via a webhook.
Also, this commit fixes different places where the `None` returned when `project.skip` was failing.
Needed by https://github.com/rtfd/readthedocs-corporate/issues/154
Closes #4257
> Skip builds when project is not active

- readthedocs/search/documents.py
- readthedocs/search/signals.py
- readthedocs/settings/base.py
- readthedocs/settings/test.py
This will index the project asynchronously. So though the elasticsearch is not available, the project creation will work.
> index project asynchronously

- readthedocs/doc_builder/environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
Closes #4957 
Need to point out that it took me some attempts to trigger the memory issue, so, in the last picture I wasn't able to capture the full output, but in some previous tests the output was bigger
> Keep command output when it's killed

- readthedocs/core/views/__init__.py
- readthedocs/templates/wipe_version.html
There is no reason to CSRF exempt this view since it's accessed via a form with POST action from the dashboard.
Related: https://github.com/rtfd/readthedocs-corporate-ops/pull/127
> Make wipe view not CSRF exempt

- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/git.py
This adds a project feature that allows us to use a standard clone and
fetch rather than the shallow clone/fetch introduced in #4939.
Eventually we should move this to the web UI, but doing so requires some
work to make sure, for example, that git options are only show when
'Project.repo_type' is 'git'.
Closes #5031
> Add temporary method for disabling shallow cloning (#5031)

- readthedocs/settings/base.py
- readthedocs/settings/dev.py
This is of very low priority.
But this warning pops up everytime in the build
Fixes #4861
> Disable django guardian warning

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/mocks/environment.py
- readthedocs/rtd_tests/tests/test_builds.py
These aren't used anywhere, as we always depend on the config (or project) for this decisions.
I'm also removing the `HTML_ONLY_PROJECTS` setting, I guess that was acting as a feature flag a long time ago when users couldn't disable epub and pdf by themselves?
> Remove localmendia and search parameters

- readthedocs/rtd_tests/tests/test_backend_svn.py
- readthedocs/vcs_support/backends/svn.py
> Remove trailing slashes on svn checkout

- readthedocs/builds/models.py
- readthedocs/core/models.py
**django.db.models.permalink()** is deprecated 4-5 years ago ([ticket #18974](https://code.djangoproject.com/ticket/18974)) and it is now completely removed in Django 2.1 ([Deprecation Timeline for Django 2.1](django.db.models.permalink()))
> Remove deprecated "models.permalink"

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_forms.py
> Add validation for tags of length greater than 100 characters

- readthedocs/projects/exceptions.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/rtd_tests/utils.py
- readthedocs/vcs_support/backends/git.py
Now we are showing which submodules need to be fixed.
Related to #4043
> More hints for invalid submodules

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_forms.py
> Change default_branch value from Version.slug to Version.identifier

- readthedocs/projects/tasks.py
- readthedocs/settings/base.py
Related Issues - #4978, #3856, #4590,
> Reduce logging to sentry

- requirements/docs-lint.txt
- requirements/lint.txt
- requirements/pip.txt
- requirements/testing.txt
```
$ for reqs in `ls requirements`; \
do pur --skip redis,commonmark,django,docker,celery,gitpython,elasticsearch,pyelasticsearch,mercurial --requirement requirements/$reqs; \
done
```
> Upgrade all packages with pur

- docs/webhooks.rst
- readthedocs/projects/notifications.py
- readthedocs/templates/projects/notifications/deprecated_webhook_endpoint_email.html
- readthedocs/templates/projects/notifications/deprecated_webhook_endpoint_site.html
> Update copy on notifications for github services deprecation

- readthedocs/gold/templates/gold/subscription_form.html
1. Fixes the indentation of some `<p>` tags.
2. On line 72, `</h3>` was the required closing tag, but `</h2>` was there.
3. There was missing `</div>`. It was leading to the whitespace after the footer in https://readthedocs.org/accounts/gold/subscription/
> Template improvements in "gold/subscription_form.html"

- docs/.rstcheck.cfg
- docs/_static/css/sphinx_prompt_css.css
- docs/api/v2.rst
- docs/conf.py
- docs/contribute.rst
- docs/custom_installs/elasticsearch.rst
- docs/custom_installs/local_rtd_vm.rst
- docs/guides/manage-translations.rst
- docs/i18n.rst
- docs/intro/getting-started-with-mkdocs.rst
- docs/intro/getting-started-with-sphinx.rst
- docs/yaml-config.rst
- requirements/pip.txt
> Make $ unselectable in docs

- readthedocs/templates/error_header.html
We are using the same 404.html template for 404 errors when serving documentation (.io) and also on our platform (.org).
The Login/Logout button only shows the proper word when the 404 page comes from .org, but it always says "Login" when we hit .io 404 pages.
As this is only confusing and there is not value added here, I'm removing it completely.
> Remove header nav (Login/Logout button) on 404 pages

- readthedocs/templates/404.html
This sections was not used.
See https://github.com/rtfd/readthedocs.org/issues/2551#issuecomment-267758066 and https://github.com/rtfd/readthedocs.org/issues/2551#issuecomment-398188563 for more context.
> Remove unused suggestion block from 404 pages

- readthedocs/core/views/serve.py
- readthedocs/rtd_tests/tests/test_doc_serving.py
Filepath can contains non-ASCII characters, so we need to convert to a valid URI before setting it as X-Accel-Redirec NGINX header because only ASCII characters are supported.
References,
* https://docs.djangoproject.com/en/1.11/ref/unicode/#uri-and-iri-handling
* https://github.com/benoitc/gunicorn/issues/1448
Closes https://github.com/rtfd/readthedocs-corporate/issues/409
> **NOTE**: I didn't test this locally because I don't have the setup needed (gunicorn + nginx) properly configured. So, we will need to be careful when deploying this into production.
One example of what this fixes is,
```
In [1]: from django.utils.encoding import iri_to_uri                                                                                                                                          
In [2]: …
```
> Convert an IRI path to URI before setting as NGINX header

- .github/config.yml
- .github/no-response.yml
- .github/stale.yml
This PR adds config files for [Stale](https://probot.github.io/apps/stale/) and [No Response](https://probot.github.io/apps/no-response/) and [todo](https://probot.github.io/apps/todo/)
This bot will
1. check for issues that has no activity for 45 days
1. post a comment communicating this issue is becoming stale
1. tag the issue as `Status: stale`
After 7 days the issue was tagged as `Status: stale` if there was no activity, it will be closed.
> NOTE: `Accepted`, `Needed: design decision` and `Status: blocked` are exempt of this flow. They won't be closed.
This bot will
1. check for issues marked as `Needed: more information`
1. if the issue was tagged more than 14 days ago the bot will close it
This bot will create an issue every time that we push a `# TODO:` in our code with the message …
> Install ProBot

- readthedocs/oauth/services/github.py
This is a work in progress PR.
All of our integrations are not handling these error codes: 401, 403 and 404. All of them are being logged as errors in our application. This PR handle them to log as info instead of an error (via the else: clause).
Also, this code may need to be repeated across all the integrations and twice on each. So, maybe it's possible to refactor this all together: https://github.com/rtfd/readthedocs-corporate/issues/372
> Handle 401, 403 and 404 status codes when hitting GitHub for webhook

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_celery.py
Fixes #4840 
This test checks that no notification is sent if the Version is locked.
> Add test case for send_notifications on VersionLockedError

- readthedocs/projects/signals.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/private.py
We have had a few issues where domains have taken a long time to issue SSL certificates (example https://github.com/rtfd/readthedocs.org/issues/4736#issuecomment-450508657). Cloudflare -- who provides our SSL certs for custom domains -- automatically retries verification requests but they have an exponential backoff and then they stop retrying after a couple weeks. That means that if you add your domain to RTD and then don't fix your DNS for a day or two, it can take days to verify your domain. Users could of course remove the domain from RTD and re-add it but few people seem to do that.
This PR fires a task which fires signals which are handled in the cloudflare code (not in the readthedocs.org repo) to automatically retry verification whenever somebody visits the domain list screen …
> Fire a signal for domain verification (eg. for SSL)

- .gitignore
- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
We are executing python commands like
`python /path/to/bin/command`
Sometimes it gives a non-deterministic behaviour.
Like using pip from the virtualenv in the first build
and using pip from the global installation other times.
Commands like sphinx-build and mkdocs have an `console_scripts` entry
point and shouldn't be a problem.
Now we are running the commands like `/path/to/bin/virtualenv/python -m pip install ...`, which gives a deterministic behaviour in every build.
I notice this problem while implementing https://github.com/rtfd/readthedocs.org/issues/5006.
When calling the `pyhton /path/to/pip list` command it gives an error (https://github.com/pypa/pip/issues/5373), and when calling `/path/to/pip list` it lists only the local packages, and in the second build `/path/to/pip list` …
> Use python from virtualenv's bin directory when executing commands

- readthedocs/projects/querysets.py
- readthedocs/rtd_tests/tests/test_project_querysets.py
If any owner of the project is banned, we skip building this project.
> Do not build projects from banned users

- readthedocs/doc_builder/python_environments.py
- readthedocs/rtd_tests/tests/test_doc_building.py
Same issue as #5107 
Just tested it, and the problem is present here too. But it's less likely to break here since we only use pip to install our requirements.
> Use the python path from virtualenv in Conda

- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
This is a new simple feature flag to allow us to put some projects under `readthedocs/build:testing` image so we can start testing `5.0rc1` in some sampled projects.
I decided to use `:testing` so now we can tag `5.0rc1` as `testing`
docker tag readthedocs/build:5.0rc1 readthedocs/build:testing
and later (in months) we can re-tag it to `6.0rc1` for example just by running another docker command in the builders without modifying Python code.
I'd like to merge this soon and deploy it so we can start our new release process.
Closes #5106
> Feature flag to use `readthedocs/build:testing` image

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/exceptions.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
Make sure that the values we will manipulate from the mkdocs.yml filethe co rrect type we need them to be. If we found a problem with them, we report a proper message to user to debug it by themselves.
> Validate mkdocs.yml config on values that we manipulate

- docs/faq.rst
- readthedocs/core/urls/subdomain.py
- readthedocs/core/views/serve.py
- readthedocs/rtd_tests/tests/test_doc_serving.py
My idea behind supporting this is,
1. check for a user's custom `robots.txt` file
1. if it does exist, serve it ~~by appending our own at the end~~
* ~~we need to disallow `/sustainability/click/`~~ (check https://github.com/rtfd/readthedocs.org/pull/5086#issuecomment-453139437)
1. if it does not exist, just ~~returns 404~~ allow all the agents and pages
If we agree on this, we will need to remove our NGINX rules from [here](https://github.com/rtfd/readthedocs-ops/blob/cbdc68eef9e8bbf9ba3db5f048955b2192fdc710/salt/base/nginx/sites/readthedocs-site.conf#L37-L40) and [here](https://github.com/rtfd/readthedocs-ops/blob/cbdc68eef9e8bbf9ba3db5f048955b2192fdc710/salt/base/nginx/sites/readthedocs-subdomain.conf#L22-L25) and [here](https://github.com/rtfd/readthedocs-ops/blob/cbdc68eef9e8bbf9ba3db …
> Support custom robots.txt

- .github/mergeable.yml
Install ProBot Mergeable Bot to help us with PR that are (not) ready to be merged yet.
> Configuration file for ProBot Mergeable Bot

- requirements/lint.txt
- requirements/pip.txt
pip install -r requirements.txt on a clean installation
doesn't install all the requirements.
This wasn't detected by travis because we install from
requirements/testing.txt pyyaml was a dependency of yamale.
> Fix requirements for local installation

- requirements/local-docs-build.txt
Our docs are currently not building because they depend on
the RTD app being installed properly to import strings.
This fixes the local-docs-build.txt file to include the proper requirements
> Fix local-docs-build requirements

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/rtd_tests/files/conf.py
- readthedocs/templates/sphinx/conf.py.conf
These were breaking builds:
``ConfigError: There is a syntax error in your configuration file: from __future__ imports must occur at the beginning of the file (conf.py, line 45)``
These configs were working fine on Python 2 and 3 builds previously,
I don't think they need to be changed.
Reverts https://github.com/rtfd/readthedocs.org/commit/06b07cc6ffd3aa64ec84442e0821f4a9425b5ac4#diff-6a827604d651f579d03b359bbcd495e3R16
Fix #5148
> Fix Sphinx conf.py inserts

- readthedocs/core/views/serve.py
I was following the guide at  `https://docs.readthedocs.io/en/latest/custom_installs/local_rtd_vm.html`
It was failing on `./manage.py migrate` with `SyntaxError: invalid syntax on line 62`
Removing comma helped locally
> SyntaxError caused by comma in python3

- CHANGELOG.rst
- setup.cfg
> Release 3.1.0

- docs/development/search.rst
The `S` of `Signals` was in capital. It should be in small letter.
> Small docs fix

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Sphinx >= 1.8 supports a dictionary for `source_suffix`:
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix
Once merged and deploy, this build should pass: https://readthedocs.org/projects/test-builds/builds/8459471/
I tested this locally and that project builds properly.
> Allow source_suffix to be a dictionary

- .github/mergeable.yml
V1 is deprecated, and I wasn't able to find the docs for v1 anyway
> Update mergeable settings to v2

- readthedocs/restapi/views/model_views.py
- requirements/deploy.txt
- requirements/lint.txt
- requirements/pip.txt
Upgrade all the packages, including (to note):
and removing py2 compatibility for linting.
> Upgrade all packages removing py2 compatibility

- media/css/core.css
- readthedocs/templates/core/badge_markup.html
- readthedocs/templates/core/project_detail_right.html
> Change badge style

- .github/mergeable.yml
This just causes every PR to fail, which is terrible UX.
> Remove approvals requirement from mergable

- readthedocs/templates/projects/notifications/deprecated_github_webhook_email.html
- readthedocs/templates/projects/notifications/deprecated_github_webhook_site.html
Our next notification will be after the GitHub cutoff. We will continue
to look at projects in the feature flag to see which ones now have an
integration configured. Two more notification rounds is probably
warranted.
> Update project notification copy to past tense

- readthedocs/rtd_tests/tests/test_middleware.py
We don't use the full middleware cycle,
so we don't have a `request.user`.
This fixes the tests failing in the corporate site
> Inject user to middleware tests

- .github/mergeable.yml
Fail to merge PRs with label `Status: blocked`.
> Do not allow to merge 'Status: blocked' PRs

- docs/guides/build-using-too-many-resources.rst
Current link is not correct `https://github.com/conda/conda/issues/5003>`
> Fix conda issue link

- docs/gsoc.rst
This adds a new idea for PR building.
We should also add other ideas that we've had,
especially if they are ~3-6 months out on the roadmap
> Update our GSOC page for 2019

- readthedocs/search/management/commands/reindex_elasticsearch.py
- readthedocs/search/tasks.py
This is a bit of a hack, but it will work for now.
> Support passing an explicit `index_name` for search indexing

- readthedocs/builds/models.py
- readthedocs/core/models.py
- readthedocs/gold/models.py
- readthedocs/integrations/models.py
- readthedocs/oauth/models.py
- readthedocs/projects/models.py
- readthedocs/redirects/models.py
We do not support py2 anymore.
> Remove py2 compatibility

- readthedocs/config/config.py
- readthedocs/search/documents.py
This was causing issues excluding some valid user documentation pages
> Remove excluding files on search.

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
`dict_keys` can be accessed via indexing, so make a list.
> Make our SUFFIX default selection py2/3 compatible

- readthedocs/core/symlink.py
- readthedocs/doc_builder/base.py
- readthedocs/doc_builder/environments.py
- readthedocs/vcs_support/utils.py
This should make it easier to follow along with builds. If you need the additional logging, you can always do `tail -F logs/debug.log`.
> Change some info logging to debug to clean up build output

- docs/conf.py
Our docs version is out of date (2.7), so this moves towards automating
this version. The version is displayed in intersphinx links and in the
title of the page. I didn't use the `readthedocs.__init__` method to
avoid an import into our docs.
> Automate docs version from our setup.cfg

- readthedocs/search/signals.py
This was causing an issue where we were trying to delete a project that didn’t exist, so it wasn’t getting removed from the index properly. It should be done in process, otherwise it’s a race condition.
> Don’t delay search delete on project delete

- docs/security.rst
Add note about the security issue fixed by #5143. This is in line with our security docs: https://docs.readthedocs.io/en/latest/security.html
> Add note about security issue

- requirements/lint.txt
- requirements/pip.txt
- requirements/testing.txt
This bot will help up to keep our dependencies up to date. This is
similar to what we were doing with pur manually.
https://pyup.io/
This PR fixes #5271 to make pyup behaves as we need.
> Setup and configure pyup.io

- docs/builds.rst
Changed version references to :latest tag and linked containers repository for details on software installed into the containers used for documentation builds.
> Change version references to :latest tag

- readthedocs/builds/admin.py
- readthedocs/projects/admin.py
This gets around not having admin access to build a project, and makes
rebuilding an arbitrary version a site admin feature.
> Add admin actions for building versions

- readthedocs/projects/views/private.py
This is to fix a case in the corporate site
> Allow to override trigger_build from demo project

- readthedocs/projects/migrations/0039_change-default-python-interpreter.py
This fixes the travis error which is due to conflicting names of migration files.
> Fix error of travis (rename migration file)

- requirements/testing.txt
This actually breaks our tests in the corporate site
> Downgrade pytest-django

- readthedocs/search/api.py
- readthedocs/search/documents.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/utils.py
There were some edge cases where the `public` queryset method on Project’s and Version’s could return an empty list. This lead to not properly filtering the queryset in the docsearch API. Properly raise an exception in this case, so that we don’t return search results that aren’t properly filtered.
> Fix an issue where we were not properly filtering projects

- readthedocs/settings/base.py
- readthedocs/urls.py
- Adds a setting that can be checked if the RTD extensions are available
- If the extensions are available, they can control their own URL structure
> Allow extensions to control URL structure

- readthedocs/restapi/views/integrations.py
Fix a bug we've had where:
* The `WebhookView` is doing Basic Auth on the user, and then setting it properly on the request
* The `APIWebhookView` then is doing Session Auth, and doing CSRF checks on it, because that requst has a valid user
A fix is to remove all the auth methods from the "parent" view,
which this PR does. 
* Replaces #5009
* Fixes #4986
> Add basic auth to the generic webhook API.

- readthedocs/builds/version_slug.py
- readthedocs/rtd_tests/tests/test_version_slug.py
- requirements/pip.txt
Our regex were replacing "all invalid chars by `-`" which I think it's not a very good pattern because we ended up with slugs like `d-----branch---a` (multiple dashes together).
This implementation only replaces `/`, `%`, `!` and `?` with dashes to keep the behavior written in tests. I think that `/` is a good one to replace because it's a common way to separate words, but I'm not sold with the rest ones.
Besides, this PR uses `unicode-slugify` which work better with unicode project names using it's "best" ASCII representation.
Closes #1410
> Use unicode-slugify to generate Version.slug

- readthedocs/projects/tasks.py
This PR,
- fixes the issue when calling `setup_vcs` and it raises an exception without stopping the build process
- removes `BuildEnvironmentWarning` from `Task.throws` argument in tasks that is not needed
- adds more "expected" exceptions for our `update_docs` tasks to not log them in Sentry as ERROR
- fixes a docstring
- applies `pre-commit`
Closes #5114 
Closes #3856 
Closes #4978 
Related #5073 
Related #5115
> Logging exceptions rework

- docs/tests.rst
Mention that ES is needed to run tox with search tests.
> Warning note about running ES locally for tests

- readthedocs/core/management/commands/clean_builds.py
Currently, the `clean_builds` command crashes with a "ValueError: 'int'
is not callable" exception.
> Fix "clean_builds" command argument parsing

- media/css/core.css
- readthedocs/builds/models.py
- readthedocs/core/templatetags/core_tags.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/templates/core/build_list_detailed.html
This commit adds alert icon to build list if the build.state == 'triggered'  and build.date > 5 mins ago.
This fixes #4036
> #4036 Updated build list to include an alert state

- readthedocs/projects/tasks.py
We are catching all exceptions here,
but we are depending on self.project and self.version
be correctly returned from the api.
This doesn't always happen, and it's raising another error.
We should catch more specific errors, but we are not seeing those errors bc of this error (hope that makes sense :eyes: )
Sentry issue https://sentry.io/organizations/read-the-docs/issues/754905187/?project=148442&referrer=RegressionActivityEmail&statsPeriod=14d
> Don't depend on specific data when catching exception

- docs/settings.rst
This was removed in https://github.com/rtfd/readthedocs.org/pull/4740#discussion_r224526805
> Remove unused setting

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
Some people are migrating from pip to conda,
but they were using a v1 config,
then when migrating they are using the conda option from v2 (which is called `conda.environment`)
We are not validating this, but using conda.file is mandatory
when using the conda option in v1 (or rtd will fail without any reason).
Close #5322
Close #5228
> Require conda.file when using conda in v1

- readthedocs/oauth/utils.py
If the try..except block fails and there is not
results, we end up with `updated` undefined.
Sentry issue https://sentry.io/organizations/read-the-docs/issues/902366698/?project=148442&referrer=alert_email&statsPeriod=14d
> Initialize local variable before using it

- docs/gsoc.rst
This also adds more of a callout about not emailing us.
Last year we got flooded with questions.
> Update GSOC page to mention we're accepted.

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
This Code Improves the Insertion of media files on `mkdocs.py`. By adding this we wont end up inserting our media files twice, which can happen in some cases.
closes #5340
> improvement on inserting mkdocs media

- readthedocs/core/utils/__init__.py
- readthedocs/urls.py
> Remove deprecated code

- readthedocs/search/tasks.py
This makes it so we're explicitly checking for one being passed
so when an empty list is passed it fails.
> Fix search bug when an empty list of objects_id was passed

- readthedocs/restapi/views/footer_views.py
This doesn't remove documentation_type completely from
the footer, but makes it more clear what we are really using.
We don't use `readthedocssinglehtml` as proven in https://github.com/rtfd/readthedocs-sphinx-ext/pull/58
We don't set `page` for mkdocs projects: https://github.com/rtfd/readthedocs.org/blob/f1c15d4f22af0ba7ebf762df1d49f7c28e8d01e5/readthedocs/doc_builder/backends/mkdocs.py#L207-L207
Ref #4638
> Cleanup a little of documentation_type from footer

- readthedocs/projects/tasks.py
The anchor can contain `#` characters.
We only need to split from the first one.
Sentry issue https://sentry.io/organizations/read-the-docs/issues/910935991/?project=148442&referrer=alert_email&statsPeriod=14d
If we keep having this weird cases, we should consider using urlparser.
I'll try to write tests for this new feature soon.
> Protect against anchors with #

- .codecov.yml
- .travis.yml
I only want to keep this page updated https://codecov.io/gh/rtfd/readthedocs.org, not activate the PR checks :)
> Try to put back codecov integration

- readthedocs/projects/models.py
This is because HTMLDir can generate a file from two different places:
* foo.rst
* foo/index.rst
Both lead to `foo/index.html`
fixes https://github.com/rtfd/readthedocs.org/issues/5368
> Check for two paths for each file

- readthedocs/builds/syncers.py
Currently we're seeing ~15 of these fail each hour,
because of an issue we're having with Azure.
Let's not fail builds on this situation.
Refs https://sentry.io/organizations/read-the-docs/issues/910584724/?project=148442&query=is%3Aunresolved&statsPeriod=14d&utc=false
> Be more defensive with our storage uploading

- readthedocs/doc_builder/python_environments.py
Currently we use sphinx 1.7,
we already have some projects building with 1.8 (with feature flag)
and with custom requirements.
We also have fixed/adapted some of our code to support the
new version.
I'm also updating the projects with a feature flag to use 2.0
when it's available.
Release history https://pypi.org/project/Sphinx/#history
> Start building with sphinx 1.8

- requirements/pip.txt
Fixes: #5101 
Checked `pip.txt` and removed un-needed python dependencies.
> Removed un-needed python dependencies

- docs/builds.rst
- Removed a code example section that does not reflects what exactly happens anymore
- Replace the mention to options from the Admin UI for the config V2 file
- More specific on the limits
> Minimum upgrade of the builds docs

- conftest.py
- readthedocs/rtd_tests/tests/test_core_tags.py
As i wasn't able to pass the request Fixture to the `setUp()` method I have Done it Like this Please Let Me know if There is a better implementation.
closes #5300
> Remove pytest warnings

- readthedocs/templates/core/project_list_detailed.html
- readthedocs/templates/core/project_list_featured.html
I'll continue @ericholscher's work here
It looks like this
> Remove view docs dropdown

- docs/faq.rst
We currently don't allow users to change the slug. Although, we accept requests for changing the slug of a version (which also breaks the Internet). So, we are following the same pattern for project slug that will affect the URL where the docs are served.
Requesting this by creating an issue does not guarantee that the project slug will be changed, though.
> Communicate the project slug can be changed by requesting it

- docs/install.rst
Fixes #5408 
The clone step in the installation guide is updated to include submodules.
> Update installation guide to include submodules

- docs/.rstcheck.cfg
- docs/api/index.rst
- docs/api/v3.rst
- docs/design/apiv3.rst
- docs/index.rst
Initial ideas to discuss the implementation of APIv3.
This is a **work in progress** PR that only has some pieces of the documentation with the idea to start a discussion around the general proposal.
Closes #4286
> Implementation of APIv3

- readthedocs/templates/base.html
> Fix inconsistency in footer links

- readthedocs/doc_builder/python_environments.py
Changelogs are in each commit.
I didn't update the mock lib, I don't know what changed. They removed their changelog after 1.0.1 https://github.com/testing-cabal/mock/commit/18c9bbd7e67055041260ae905891dee74586409c#diff-1034dffc22980f2f99ec5765e88235fd
Also, I'm not even sure if we need pillow at all
> Update internal requirements

- readthedocs/doc_builder/backends/sphinx.py
We were hiding the real error
from the user
Related https://github.com/rtfd/readthedocs.org/issues/4745#issuecomment-470754025
> Fix reraise of exception

- readthedocs/core/utils/__init__.py
- readthedocs/rtd_tests/tests/test_core_utils.py
> Trigger build on default branch when saving a project

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_forms.py
If there are no active versions of a project, an error is raised when `Advanced Settings` page is accessed.
> Make 'default_version` field as readonly if no active versions are found.

- readthedocs/projects/tasks.py
Remove some repetition to make it more clear.
I'm doing this to make it more clear what we are moving, so we can save space in the builders by not copying the artifacts in two locations as we do now.
> Refactor move_files

- docs/intro/getting-started-with-sphinx.rst
We are installing the latest version of sphinx in the guide, we need to use this method to add markdown support
https://github.com/rtfd/recommonmark#getting-started
> Update docs for building with markdown

- readthedocs/core/permissions.py
- readthedocs/projects/views/public.py
This page was timing out due to permission checks `{% if request.user|is_admin:project %}` performed in a loop of all versions for a project with ~1k versions. That permission check was generating a database query per version (2 actually). This changes the view such that users for a project are cached and the permission check won't hit the database again.
Fixes #5458
> Optimize the version list screen

- readthedocs/config/validation.py
This was basically used to check if something was inside a dictionary,
but we ended up using another method for this.
> Remove unused validator

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_symlinks.py
This is an initial proposal for #5413 
This only affects the order of the current settings, we can create real groups modifying the template, using two forms or using https://django-crispy-forms.readthedocs.io/en/latest/layouts.html
For now, I would like to get reviewed the order/group of these options, and if someone has an opinion about the best way of having separate groups using the adobe suggestions.
> Regroup settings

- readthedocs/projects/models.py
- readthedocs/restapi/views/model_views.py
- readthedocs/rtd_tests/tests/test_sync_versions.py
> Always update the commit of the stable version

- readthedocs/settings/dev.py
- readthedocs/urls.py
- requirements/pip.txt
In the past few days I have found a few performance issues that could have been caught easier with Django Debug Toolbar (#5451 and #5460). I propose we enable it in development.
> Enable Django Debug Toolbar in development

- readthedocs/doc_builder/python_environments.py
When readthedocs pip installs a previously installed core component the previous version doesn't get fully uninstalled. This is caused by the `--ignore-installed` flag and the results can be disastrous: https://stackoverflow.com/a/51916623
> Fix pip installs

- readthedocs/doc_builder/python_environments.py
the 40.x releases has a lot of bugfixes and compatibility changes
to support the latest version of pip, which we install by default now.
Changelog https://setuptools.readthedocs.io/en/latest/history.html#v40-8-0
Closes #5436
> Update version of setuptools

- readthedocs/projects/views/private.py
- readthedocs/templates/projects/project_dashboard_base.html
> Dashboard screen performance fix

- docs/config-file/v2.rst
- readthedocs/templates/projects/import_basics.html
- Doesn't remove the advanced settings from the form
- Adds a commented, copy/pastable YAML file into the docs
Fixes #5414
Closes #5444.
> Promote the YAML config

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
> Typo on conf.py.tmpl

- readthedocs/core/views/__init__.py
- readthedocs/rtd_tests/tests/test_views.py
> Make /random/ path work

- docs/advertising/ethical-advertising.rst
My goal is to streamline the process for applying for community ads. Rather than an open ended email, I want to get applications that are immediately actionable.
I'm not sure how people feel about Google Forms, but they seem like a good fit here.
> Add an application form for community ads

- readthedocs/builds/models.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/templates/core/project_downloads.html
Fixes #5497
We just need to rely if the epub/pdf exists, we already do this with the localmedia download.
> Don't depend of enabled pdf/epub to show downloads 

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
We don't support xindy yet.
Closes #5503
Related #5476
> Force Sphinx to not use xindy

- readthedocs/projects/tasks.py
The comment mostly explains it,
but the delete objects code does another query:
https://github.com/rtfd/readthedocs.org/blob/3340364802a8cdcc5f4145fbde2a5dd4f7087771/readthedocs/search/tasks.py#L59-L62
This should now fix search deletion.
>     Fix bug that caused search objects not to delete

- readthedocs/builds/models.py
- readthedocs/builds/version_slug.py
- readthedocs/core/utils/__init__.py
- readthedocs/doc_builder/environments.py
- readthedocs/projects/exceptions.py
- readthedocs/projects/tasks.py
- readthedocs/search/tasks.py
Closes #5433 
Following `grep` command was used to find the `assert` statements
```
grep -irn "assert" readthedocs.org/ --exclude-dir={user_builds,.tox,htmlcov,media,logs,static,rtd_tests,tests,docs,locale,templates} --exclude="*.pyc" --exclude="tests.py"
```
> Remove asserts from code.

- readthedocs/core/utils/__init__.py
- readthedocs/projects/exceptions.py
- readthedocs/projects/tasks.py
- readthedocs/search/tasks.py
Ref: https://github.com/rtfd/readthedocs.org/pull/5452#discussion_r267412964
> Use ValueError instead of InvalidParamsException

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/doc_builder/config.py
Create a config file for the user only when we
don't have one and don't hide the syntax error
to the user.
Fixes #5506
Fixes #5439
The error is show like this
> Catch specific exception for config not found

- readthedocs/builds/models.py
- readthedocs/restapi/views/footer_views.py
- readthedocs/rtd_tests/tests/test_repo_parsing.py
Currently we depend on
https://github.com/mkdocs/mkdocs/blob/d101522aa197aaa212f1424180d693dd5d497875/mkdocs/themes/readthedocs/base.html#L35-L40
which is only available in the rtd theme.
For non-rtd themes we are generating a link like `https://github.com/mkdocs/mkdocs/blob/master/docs/.md`
I'm proposing the solution of just linking to the docsdir `https://github.com/mkdocs/mkdocs/blob/master/docs/`
Another option is just to link to the repo, and only show the `view on` link :)
What do you think?
Also, looks like we can refactor this code, let me know if you feel like something that can be done here or we can create an issue later.
> Link to the docdir of the remote repo in non-rtd themes for mkdocs

- docs/guides/pdf-non-ascii-languages.rst
- improves grammar and narrative for clarity and brevity
- moves a link closer to its paragraph
- explicitly cites Unicode characters as a potential build failure
- s/configurations/settings (a configuration is a collection of settings)
> Tidy up grammar, promote Unicode characters

- docs/install.rst
Previously, this text was displayed verbatim and without formatting
> Fix formatting for CentOS/RHEL installs

- docs/conf.py
This avoids the insecure initial load of port 80 (http://) just to get redirected to https.  This also speeds up the builds of the docs by a tiny fraction.
> Use HTTPS for intersphinx mappings

- docs/webhooks.rst
This does a small cleanup on the GitHub webhook docs by reordering the instructions in the order which fields are shown to the user on GitHub (reducing jumping around) but also explains the initial "ping" process that GitHub does.  It was confusing to see RTD respond with `{"detail":"Unhandled webhook event"}` to a ping, when in fact this is working-as-expected.
> Add to and reorder GitHub webhook docs

- .github/CONTRIBUTING.rst
- docs/contribute.rst
- docs/docs.rst
This makes a few improvements to the documentation for Read the Docs itself:
* Better explains how to perform a local install for working on the docs
* Explains there's a separate page for guidelines for docs on the contributing page
* Updates the URL in GitHub's contributing doc to use https + new readthedocs.io domain
>  Update contributing docs for RTD's own docs

- readthedocs/builds/models.py
- readthedocs/config/config.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/templates/builds/build_detail.html
Add a "build idea" to the build detail screen (only for project maintainers) to guide them to using the `.readthedocs.yml` configuration file. The message shows regardless of whether the build was successful or not but doesn't show if the build used the v2 YAML file.
On a semi-related note, I know we support the YAML file being named `\.?readthedocs.ya?ml` but I think we should recommend one particular way even if we support multiple. I'm propose we recommend `.readthedocs.yml`. Opinions?
Fixes #5500
> Guide users to the YAML config from the build detail page

- docs/install.rst
Added a note in the developer guide which asks the developer to use python version 3.6.7 instead of python 3.6.8 which would use a higher version of sqlite3 giving rise to issur #5477
> Added note warning about using sqlite 3.26.0 in development

- readthedocs/projects/forms.py
- readthedocs/settings/base.py
- readthedocs/templates/projects/project_advanced.html
- readthedocs/templates/projects/project_advanced_settings_helptext.html
- requirements/pip.txt
This is a continuation of #5459
Closes #5413 
It looks like this
I'm not sure about the texts, so any help is welcome.
> Regroup advanced settings

- readthedocs/projects/forms.py
- readthedocs/templates/projects/project_advanced.html
Turns out, that crispy already renders all the forms tags
Save button looks the same
> Fix advanced settings form

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_forms.py
`verbose_name` is unique in each project, because we only have one remote.
`identifier` includes origin for branches and also it can point to the
same commit in tags.
Fixes #5518
> Fix extra origin in urls

- readthedocs/doc_builder/backends/mkdocs.py
There are some cases were rtd uses the old installed version of mkdocs
instead of the one installed by the user, like in
https://github.com/rtfd/readthedocs.org/issues/5532#issuecomment-476308877
Which gives an error because it's using a yaml file
supported only in new mkdocs versions.
This is similar to https://github.com/rtfd/readthedocs.org/pull/5107
> Call mkdocs using -m

- readthedocs/core/views/serve.py
- readthedocs/rtd_tests/tests/test_doc_serving.py
> Sitemap assumes that all versions are translated Fix.

- readthedocs/core/resolver.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_footer.py
Currently, the number of database queries in the footer API depends on the number of versions of the project in question. This optimizes the API to always be a constant number of queries.
This PR partially fixes #3712 in that it fixes the major performance issues with the resolver when generating a number of URLs for different versions of the same project. Currently `project.ordered_active_versions` is only used by the footer API but anywhere else looking to generate URLs for a list of versions could use that function to get the same performance benefits.
The test case does seem a little bit brittle but I'm not sure what the best way to improve that is.
> Optimize database performance of the footer API

- readthedocs/doc_builder/backends/mkdocs.py
Currently we are expecting that all mkdocs projects have their docs in
their root, but we generate the artifacts relative to their yaml file,
we do the same for sphinx.
https://github.com/rtfd/readthedocs.org/blob/d8a6c24013b7089074b302e7c04edd7998fe90ce/readthedocs/doc_builder/backends/sphinx.py#L42-L51
Fix https://github.com/rtfd/readthedocs.org/issues/5532#issuecomment-476316702
Closes #5559
> Allow build mkdocs outside root

- media/css/readthedocs-doc-embed.css
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This allows (but doesn't mandate) fixed footer text-only advertisements. The plan is to roll these out as a test to see if users react to them (do they perform? do users hate them?).
- For starters, we'll roll them out on our docs only followed by community ads
- As they expand perhaps they can target themes that previously didn't have ads or on docs where ads are either all the way at the bottom of the page (never viewed) or have a long sidebar (again, the ad isn't viewed)
> Non mobile fixed footer ads

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
Firefox handles `<a href="javascript:">` links differently.
> Fix for Firefox to close the ad correctly

- readthedocs/templates/core/project_downloads.html
In #5502 we refactored the function
but we used to depend on `pretty` to change the name of the key from
`html` to `htmlzip`, we use `html` in the footer and in the theme.
So, it's safe to change the value in the template.
See https://github.com/rtfd/readthedocs.org/pull/5502/files#r272787188
> Use downloads.html in template

- docs/advertising/ethical-advertising.rst
- docs/advertising/index.rst
- docs/index.rst
- docs/install.rst
- docs/intro/getting-started-with-mkdocs.rst
- docs/intro/getting-started-with-sphinx.rst
- docs/intro/import-guide.rst
Initially my goal here is to just have slightly better blurbs on search engine result pages (SERPs).
> Add meta descriptions to top documentation

- media/css/core.css
- readthedocs/templates/projects/project_translations.html
This Improves the design of `Admin -> Translations` page.
closes #3708 
----------------------------------
> Improve project translation listing Design under admin tab

- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_doc_building.py
> Update ``readthedocs-environment.json`` file when env vars are added/deleted

- docs/config-file/v2.rst
The note mentions that PDF\EPub is not supported when using Mkdocs
> Added note in YAML docs

- readthedocs/templates/projects/domain_form.html
- readthedocs/templates/projects/domain_list.html
- Use domain details instead of "edit" - more obvious
- Use "save domain" instead of "submit" for the form
- Show that the cert will revalidate when saved
> UX improvements around SSL certificates

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_project_forms.py
> "Default branch: latest" does not exist Fix.

- readthedocs/projects/urls/public.py
- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/rtd_tests/tests/test_project_views.py
This is a PR related to data cleanup. It redirects all requests to `/project/<project_slug>/*` where `project_slug` contains an underscore to a version of the project slug with a `-`.
* We currently have 7 projects with a `_` in them. New projects already can't have an underscore in their slug. We should modify the offending project slugs.
* Technically, this won't redirect projects with a slug starting or ending with a `_` but I think that's ok.
Related to: #5633
> Redirect project slugs with underscores

- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/gitlab.py
Instead of doing it Like this I propose having a method (`create_webhook`) to handle webhook creation for Github, Gitlab and Bitbucket. The method might contain something like this:
https://github.com/rtfd/readthedocs.org/blob/b356689f26f380c38dcec828fd256d17b86ec849/readthedocs/oauth/services/bitbucket.py#L233-L249
closes #5092
> Handle 401, 403 and 404  when setting up webhooks

- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/doc_builder/base.py
- readthedocs/doc_builder/exceptions.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
> Validate docs dir before writing custom js

- requirements/pip.txt
`docker` is upgraded in production `build03` and it's not reporting errors. It seems it's safe to merge this and include in the next deploy.
Closes #3999
> Upgrade docker python package to latest release

- readthedocs/search/documents.py
- readthedocs/search/management/commands/reindex_elasticsearch.py
- readthedocs/search/tasks.py
- readthedocs/search/views.py
This is a followup of #5650
ref: #5517
> pylint fix for readthedocs.search

- readthedocs/projects/constants.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
This is a followup of #5650
ref: #5517
> pylint fix for readthedocs.projects

- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/constants.py
This is a followup of #5650
ref: #5517
> pylint fix for readthedocs.doc_builder

- readthedocs/analytics/tests.py
- readthedocs/analytics/utils.py
- readthedocs/core/middleware.py
- readthedocs/settings/base.py
> Remove ProxyMiddleware

- readthedocs/core/middleware.py
- readthedocs/core/symlink.py
- readthedocs/core/views/hooks.py
- readthedocs/core/views/serve.py
- readthedocs/projects/constants.py
If this way works then I'll continue with the other apps.
ref: #5517
> pylint fix for readthedocs.core

- docs/install.rst
> Warning about using sqlite 3.26.0 for development

- readthedocs/settings/base.py
Configures the Django security middleware and the `XFrameOptionsMiddleware` which sets 3 headers on our HTTP responses served by Django.
* The [XSS_FILTER](https://docs.djangoproject.com/en/1.11/ref/middleware/#x-xss-protection) option will cause browsers that support it to implement a very basic XSS protection mechanism. Our site is probably not vulnerable to something this would prevent, but this is a best practice and may help prevent some future attacks against us
* The [NOSNIFF](https://docs.djangoproject.com/en/1.11/ref/middleware/#x-content-type-options-nosniff) option helps prevent user uploaded files from being interpreted by a content type other than what the server sends. We don't serve any user uploaded files currently from Django (we do in nginx and we do in RTD corporate) so …
> Configure the security middleware

- readthedocs/core/templatetags/privacy_tags.py
- readthedocs/projects/models.py
- readthedocs/templates/core/project_list_detailed.html
> Profile page performance issue Fix

- readthedocs/gold/models.py
- readthedocs/gold/templates/gold/projects.html
- readthedocs/gold/templates/gold/subscription_detail.html
- readthedocs/gold/views.py
- readthedocs/rtd_tests/tests/test_gold.py
- readthedocs/templates/projects/project_advertising.html
- new gold users can no longer sponsor projects
- applies to gold users created after 2019-05-01
> Gold project sponsorship changes

- readthedocs/settings/base.py
- readthedocs/settings/dev.py
Define some simple validators to use when creating a new user or
changing the password.
https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#module-django.contrib.auth.password_validation
Closes #5551
> Enable auth validate passwords

- docs/guides/feature-flags.rst
- docs/guides/pdf-non-ascii-languages.rst
- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/environments.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/projects/models.py
- readthedocs/rtd_tests/tests/test_builds.py
- Checks for the Sphinx version installed in the user virtualenv to decide if `latexmk` or `pdflatex` should be called to build the PDF.
- Removes the USE_PDF_LATEXMK feature flag since it's not needed anymore.
Closes #5655
> Use latexmk if Sphinx > 1.6

- readthedocs/projects/tasks.py
Currently we are acquiring 3 locks.
We should only have 2 (we can't have only one because of #5672)
Basically I'm removing the locks from `setup_python_env` and `build_docs` to only acquire the lock in a central place (`run_build`)
> Simplify lock acquire

- docs/team.rst
This should hopefully cut down on the number of personal emails we get.
> Explicitly mention a support email

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/settings/base.py
Changes on this PR:
* Use `4.0` as `stable` and `5.0` as `latest` for our Docker images
* Allow to specify `pypy3.5` as Python version (see #5658)
* Adapt tests relying in Python `3.5` to use `3.6` or `3.7` ~~since `3.5` is not supported anymore~~
Required by https://github.com/rtfd/readthedocs-docker-images/pull/103.
> Support Docker 5.0 image

- docs/install.rst
Closes https://github.com/rtfd/readthedocs.org/issues/5550
> Specify python3 in installation instructions.

- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/templates/projects/project_delete.html
> Notify the user when deleting a superproject

- readthedocs/config/tests/test_validation.py
Identity is not the same thing as equality in Python.  In this instance, we want the latter.
Use ==/!= to compare str, bytes, and int literals.
$ __python__
```python
>>> result = 'choic'
>>> result += 'e'
>>> result == 'choice'
True
>>> result is 'choice'
False
```
> Identity is not the same thing as equality in Python

- readthedocs/doc_builder/backends/sphinx.py
This option helps latexmk to do not wait for a user input if any of latex commands fail. We are already using it when building with `pdflatex` and now I'm adding it to the `latexmk` flow.
> Use nonstopmode for latexmk

- .github/FUNDING.yml
Adding this file will create a "sponsor" button on the GitHub UI for our repository next to "watch/unwatch". This button will open a modal which links to our external sustainability page (see screenshot).
There are a lot of possibilities here but before we spend any real time on it I'm interested to see if we get any engagement.
See:
* https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/
* https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository
> Create a funding file

- docs/canonical.rst
Use fabric to show the HTML block for consistency with the rest of the page.
> Canonical consistency example

- readthedocs/projects/tasks.py
Currently we have a lot of nested try..exception blocks.
We only need one, we are duplicating the same error handling.
Also, we are already do checks to avoid ending with undefined variables.
I refactored to run `run_build` after `run_setup` in the same try...exc block. The exception handling is the same, so it came be removed.
> Simplify update docs task

- docs/guides/feature-flags.rst
1. added some flags that could be interesting for users
1. remove flags that can be achieved by the user themselves (config file, requirements)
1. remove invalid flag
> Update feature flags exposed to user in docs

- readthedocs/templates/projects/project_version_detail.html
- readthedocs/templates/projects/project_version_list.html
Instead of showing the "Clean" button next to a version in the "Inactive Versions" listing, this button is moved to the detail page with an explanation about what it does.
Changed from,
to,
This change is made because we found that multiple buttons in a row breaks in other languages when translated (because of margin/padding). Also, this button is [not shown at all in the corporate site](https://github.com/rtfd/readthedocs-corporate/issues/534) and it should be --but we don't want to show it in the listing.
> Move version "Clean" button to details page

- media/css/readthedocs-doc-embed.css
- Using transparency was a mistake especially when the sidebar color can be changed
- This color is 10% lighter than the default background color on the RTD theme which is what the transparency attempted to accomplish.
- Fixes: #5563
> Fix the sidebar ad color

- readthedocs/builds/models.py
- readthedocs/builds/storage.py
- readthedocs/builds/syncers.py
- readthedocs/projects/constants.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_project_views.py
Since #5549 was merged (although it is not yet deployed) a few issues emerged. This is an attempt to fix them:
- Delete from storage when a project or version is deleted (Fixes #5691)
- Project delete now handled in a method on the model (`Project.delete()`)
- Define media type constants (next step: use them everywhere)
- A few places still using default storage instead of `RTD_BUILD_MEDIA_STORAGE`
> Storage updates

- requirements/pip.txt
Celery can install kombu>=4.2.0
https://github.com/celery/celery/blob/v4.1.1/requirements/default.txt#L3
But kombu>4.3.0 requires redis>=3.2
https://github.com/celery/kombu/blob/v4.5.0/requirements/extras/redis.txt#L1
> Pin kombu to 4.3.0

- readthedocs/doc_builder/backends/mkdocs.py
After https://github.com/rtfd/readthedocs.org/pull/5377/
The code calling the config module is in charge of getting the full
path.
> Fix mkdocs relpath

- readthedocs/search/documents.py
- readthedocs/search/faceted_search.py
- readthedocs/search/tasks.py
This creates a new connection on every request,
hopefully working around the issues with the connection pool.
This will go out on 1 web and see if it resolves the issues at all.
This is branched from `rel`, which seems to have caused some weirdness :/
> Try to fix Elastic connection pooling issues

- readthedocs/core/management/commands/update_repos.py
- readthedocs/core/management/commands/update_versions.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_core_utils.py
Currently we are using a mix of project_pk and version_pk.
But we only need a version_pk, the project
can be obtained from the version.
The default version is set at https://github.com/stsewd/readthedocs.org/blob/90211a2828dd874d4209caa4204eec806fdbc431/readthedocs/core/utils/__init__.py#L93-L95
> Use version_pk to trigger builds

- readthedocs/projects/tasks.py
This lock was being shared by sync_repo and build_docs,
I'm moving it to the top of the tasks instead.
This was taken from https://github.com/rtfd/readthedocs.org/pull/5680/files#r284946925
I'm doing this in a separate PR so it's easy to review and this is useful for the whole project
> Call lock per task

- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/vcs_support/utils.py
Two PRs got merged and one modified the behaviour that the
other one was depending on.
This was giving an error in the lock creation
because the base dir wasn't created yet.
The rest of tests something I forgot to change project_pk -> version_pk
(I did a grep, didn't find more)
> Fix tests on master

- readthedocs/api/v3/tests/test_projects.py
While running `tox -e py36` was getting fludded with pytest warnings like this:
```
readthedocs/api/v3/tests/test_projects.py::APIEndpointTests::test_unauthed_others_projects_detail
/home/saad/dev/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField User.date_joined received a naive datetime (2019-04-29 10:00:00) while time zone support is active.
RuntimeWarning)
/home/saad/dev/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1451: RuntimeWarning: DateTimeField Project.pub_date received a naive datetime (2019-04-29 10:00:00) while time zone support is active.
RuntimeWarning)
/home/saad/dev/readthedocs.org/.tox/py36/lib/python3.6/site-packages/django/db/models/fields/__init__.py …
```
> Pytest Timezone Warning Fixed

- readthedocs/templates/projects/onboard_detail.html
Ref: https://github.com/rtfd/readthedocs.org/issues/5427
Please let me know if I have made any mistake.
Thank You.
> Add link to in-progress build from dashboard.

- docs/builds.rst
- docs/faq.rst
- docs/guides/build-using-too-many-resources.rst
- docs/support.rst
With the aim of keeping the issue tracker related to code issues,
and have a more control over specific request.
We are moving admin-only actionable request to email.
I found these places only, not sure if anything else is missing or if we are pointing to the correct email :)
> Move community support to email

- readthedocs/projects/views/private.py
- readthedocs/templates/projects/domain_form.html
- readthedocs/templates/projects/domain_list.html
- Add a reminder about the exact CNAME value for a domain if the domain is pending
- Be more explicit in what custom domains do in the domain list view
> Domain UI improvements

- requirements/pip.txt
django-textclassifier doesn't have pinned deps
https://github.com/agjohnson/django-textclassifier/blob/v1.0/setup.py
An update in nltk broke the package
https://github.com/nltk/nltk/issues/2312
> Pin textclassifier dependencies

- docs/intro/getting-started-with-sphinx.rst
- docs/intro/import-guide.rst
It's great to have a Github issue outlining how to work around an issue in the startup documentation ( see #2569), but it looks bad when this hasn't been integrated back into the documentation (for about 5 months when there was a breaking change), as ReadTheDocs is all about the docs - especially docs for starting/intro tutorials.
As per #2569 this PR specifies the missing step to get docs building correctly first time in RTD, without having to search for answers to build failures.
> fix sphinx startup guide to not to fail on rtd build as per #2569

- readthedocs/doc_builder/python_environments.py
As discussed in #5545, the `--force-reinstall` causes a lot of issues for Conda builds,
whereby some packages (for example `docutils`) cannot be uninstalled by pip.
A more comprehensive solution may be to include additional options in the `.readthedocs.yaml`,
to control the flags used when pip installing.
But, at least as an intermediary solution, I see no drawbacks in using `--upgrade --upgrade-strategy eager` to achieve the same objective, of ensuring dependencies are up-to-date (but without unnecessary uninstall/reinstall of dependencies).
> Use `--upgrade` instead of `--force-reinstall` for pip installs

- readthedocs/projects/tasks.py
> Get version from the api

- docs/design/pr-builder.rst
This is the initial design Doc for the PR Builder. I would like to get some feedback and Guidance on this to carry on the project.
closes #5700
reference issue #5684
> Pull Request Builder Design Doc

- readthedocs/search/views.py
search can end up unbound if there isn't a valid facet
Fix https://sentry.io/organizations/read-the-docs/issues/1054512234/?project=148442&query=is%3Aunresolved
> Fix unbound var in search view

- contrib/Dockerfile
- contrib/docker_build.sh
- contrib/readme.rst
- docs/development/buildenvironments.rst
- readthedocs/settings/dev.py
This is necessary as permissions are all incorrect on the paths that are
shared between the host system and the Docker build container.
Closes #2692
> Add a contrib Dockerfile for local build image on Linux

- readthedocs/projects/tasks.py
- readthedocs/search/signals.py
- readthedocs/search/utils.py
> Move search functions

- readthedocs/core/middleware.py
- readthedocs/rtd_tests/tests/test_footer.py
Instead of forcing to be an empty dict `{}`, we force it to be a real SessionBase object which it's what Django uses internally. This avoid issues where other pieces expects the `SessionBase`.
Django docs: https://docs.djangoproject.com/en/1.11/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase
> Use a real SessionBase object on FooterNoSessionMiddleware

- readthedocs/api/v3/mixins.py
Doing `if queryset` as this does actually evaluates the queryset which can be quite expensive. Rather than doing that, this will just return it. If the project slug is invalid, it should have already 404ed and returning an empty list in the other case seems reasonable. You could see this in the Django Debug Toolbar query tab.
More generally, there is a lot of multi-inheritance in the APIv3 and maybe we could do something to simplify it.
I removed the comment 
In actuality, this method is called by `NestedViewSetMixin.get_queryset` and not the other way around.
> Optimize requests to APIv3

- readthedocs/core/urls/subdomain.py
- readthedocs/core/views/serve.py
Currently, Read the Docs Community does not have this problem because we serve directly from NGINX without passing through Django to get the `X-Accel-Redirect` header in its response.
Although, on Corporate we are returning an infinite redirect when accessing `/projects/subproject/` URL when subproject is a Single Version project.
- We have a `redirect_project_slug` view that is called when hitting `/projects/subproject/` to redirect to its default lang/version --this does not apply on single version subproject
- This redirect URL is only registered on `urls/subdomain.py` file (and not on `urls/single_version.py`), which should not be called when accessing a single version project is hit
- Our `SingleVersionMiddleware` (which overrides the `request.urlconf`) is not detecting that we are …
> Support single version subprojects URLs to serve from Django

- readthedocs/templates/projects/project_advertising.html
- Remove the forms to contribute to Read the Docs. We don't really get any contributions this way
- Build value for the commercial product a bit more
- More prominent get in touch for alternatives
- Remove mentions of gold. Gold doesn't remove ads from projects anymore. However, projects can get in touch.
> Project advertising page/form update

- readthedocs/projects/forms.py
- readthedocs/rtd_tests/tests/test_domains.py
When the user clicks on a Domain object to edit it, we don't allow to change the `domain` field since it does not make sense. In case there was a mistake, the domain needs to be re-created.
> Disable changing domain when editing the object

- readthedocs/core/views/__init__.py
- readthedocs/projects/managers.py
- readthedocs/projects/models.py
- readthedocs/projects/querysets.py
- readthedocs/rtd_tests/tests/test_doc_serving.py
- readthedocs/rtd_tests/tests/test_managers.py
- readthedocs/search/documents.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/tests/test_documents.py
This is a continuation from #5750
> Remove PR Versions from Elasticsearch Indexing and HTMLFile Queryset Added

- readthedocs/builds/views.py
- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/rtd_tests/tests/test_views.py
this is mainly for testing and the UI/UX might change for the listings.
ref: #5807
> Remove internal filtering from Version and Build listing

- docs/guides/custom-404-page.rst
Communicate to the users that adding a `404.html` in their root directory of the docs, will make Read the Docs to find it and serve it when a 404 happens
Also, suggest the usage of the `sphinx-notfound-page` extension.
> Guide about custom 404 pages

- readthedocs/rtd_tests/tests/test_redirects.py
This is most like a little hack to make
the tests of the new feature in .com pass.
Why tests are passing after this changes?
First, we don't need to patch anything, by default
those files don't exist.
Now, here is the interesting part.
When a version exists (in this case `0.8.1`)
the serve_docs function (from .com)
tries to verify that the current user has permissions over that
version first, this gives a 401 response.
Accessing to a unexisting version, it gives 404,
which is needed to trigger the redirect
> Refactor redirect tests

- docs/development/design/apiv3.rst
This commit,
* describes main Goals/Non-Goals
* includes implementation plan based on stages
* updates the document mentioning what's already implemented (Version 1)
* proposes a plan for iteration 2, 3 and 4
* ~~mentions open questions for further discussion~~
* includes potential feature out of the current roadmap
> Re-work around design document for APIv3

- readthedocs/builds/querysets.py
- readthedocs/projects/querysets.py
We set these permissions when we save a project or a version
https://github.com/rtfd/readthedocs.org/blob/1ee57dec16f352d14ca17c1bcd8877a9a88a8f0a/readthedocs/projects/models.py#L424-L425
https://github.com/rtfd/readthedocs.org/blob/1ee57dec16f352d14ca17c1bcd8877a9a88a8f0a/readthedocs/builds/models.py#L249-L250
We set them to all the owners of a project,
we already know all projects of an user with `user.projects`.
For now I'm just removing guardian from the querysets,
in another PR I'm going to remove the dep of guardian
~This also removes the use of `distinct` (this generates problems when trying to do another or `|`)~ (This failed, I'm keeping distinct :/)
- self.all() - This doesn't look like it's going to return duplicated results
- self.filter() - this is filtering for selected pk's …
> Remove django guardian from querysets

- pytest.ini
- readthedocs/builds/admin.py
- readthedocs/projects/admin.py
- readthedocs/settings/base.py
- requirements/pip.txt
What do I like more than deleting code? deleting a dependency :)
The only change on the admin is that the `Object permissions` tab is removed
> Remove django guardian

- docs/advertising/ethical-advertising.rst
Some email clients that aren't gmail apparently don't handle this well as I've gotten a couple emails with the actual subject "Alternatives+to+advertising" instead of "Alternatives to advertising".
> Fix spaces in email subject link

- readthedocs/api/v3/permissions.py
- readthedocs/api/v3/serializers.py
- readthedocs/api/v3/tests/responses/projects-list_POST.json
- readthedocs/api/v3/tests/test_projects.py
- readthedocs/api/v3/views.py
- readthedocs/core/utils/__init__.py
- readthedocs/projects/views/mixins.py
- readthedocs/projects/views/private.py
- readthedocs/settings/base.py
This PR allows `POST` at `/api/v3/projects` to Import a Project.
It follows the same idea that importing from the Dashboard:
1. Create the Project object
1. Assign the user who makes the request as maintainer
1. Send `project_import` Django signal
1. Trigger an initial build 
> Note that I had to refactor the function that trigger the initial build to be able to call the same logic from two different places.
> APIv3 "Import Project" endpoint

- docs/guides/adding-custom-css.rst
- docs/guides/custom-404-page.rst
- docs/guides/index.rst
- docs/guides/mkdocs-old-versions.rst
- docs/guides/pdf-non-ascii-languages.rst
- Significant improvements to the custom CSS/JS guide
- Broke out the guides into Read the Docs and Sphinx/MkDocs guides
- Small grammatical and copy improvements
I'll probably do more work on more of the guides slowly but surely. The key things to improve on are to make sure that the right words that people would search in google for are present on the page and it make sure to explain why in addition to how.
Here's the [current guides page](https://docs.readthedocs.io/en/stable/guides/index.html) for comparison.
> Rework on documentation guides

- readthedocs/projects/querysets.py
- readthedocs/rtd_tests/tests/test_doc_building.py
- readthedocs/rtd_tests/tests/test_project_querysets.py
- readthedocs/rtd_tests/tests/test_version_querysets.py
Related #5872
I could reproduce having duplicates in the project's querysets, but not in the versions' querysets.
You can test this by removing the distinct() call in the querysets. This is only to make sure the other PR doesn't break anything.
> Add tests for version and project querysets

- readthedocs/builds/constants.py
- readthedocs/builds/models.py
- readthedocs/core/utils/__init__.py
- readthedocs/doc_builder/environments.py
- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/github.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_oauth.py
- readthedocs/rtd_tests/tests/test_projects_tasks.py
Sending build status `pending` and `suncess` or `failed` using GitHub Status API.
Will extend this for other services in the future (e.g: gitlab, bitbucket)
**TODO:**
> Send Build Status Report Using GitHub Status API

- readthedocs/core/utils/__init__.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_projects_tasks.py
This breaks in celery when we will ship to prod.
> Pass the build_pk to the task instead of the build object itself

- docs/guides/feature-flags.rst
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/models.py
Behind a Feature flag, we can decide if we want to update the version of ``conda`` from the system to its latest version available.
This allow us to use a new release of ``conda`` that is not released under Miniconda yet, but also to not upgrade the Docker image just because of a new release of Miniconda.
(the overhead added is around 60 seconds in total --but they say that the new resolver is way faster... so :1st_place_medal: )
> We can test this for a while under a feature flag, and then we can decide if it worth to enable it by default.
> Update conda at startup

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_projects_tasks.py
after merging #5904. there were some tests failing as we needed to update them according to the new code.
> Github Status reporting Test fix

- readthedocs/builds/admin.py
This lets us view the configs for debugging. Make it pretty too:
> Add config to Build and Version admin

- readthedocs/search/faceted_search.py
Related: #5235 
This method works in local but I am not sure that whether this is correct way or not.
> Fix count value of docsearch REST api

- readthedocs/api/v3/serializers.py
- readthedocs/api/v3/tests/responses/projects-detail.json
- readthedocs/api/v3/tests/responses/projects-list.json
- readthedocs/api/v3/tests/responses/projects-subprojects-list.json
- readthedocs/api/v3/tests/responses/projects-superproject.json
- readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json
* Move `urls.project_homepage` to the root of the Project object
* Add Project, Builds, Versions and Documentation (all URLs under Read the Docs) in `urls`
These changes make the object detail more clear, although I'm not sold on the name `urls` --I'd like to have something more related to "Read the Docs URLs" or "URLs under Read the Docs platform". Any suggestion here?
Besides the above concern, I'd like to rename `project_homepage` to just `homepage` (once I get a better name for `urls`) since it's a field of the project itself.
> APIv3 refactor some fields

- readthedocs/projects/exceptions.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/git.py
Currently we show a generic message.
Related: https://github.com/readthedocs/readthedocs.org/issues/4371
This can be removed when https://github.com/gitpython-developers/GitPython/pull/818/
gets merged.
> Better msg when gitpython fails

- readthedocs/api/v2/views/integrations.py
- readthedocs/builds/constants.py
- readthedocs/builds/models.py
- readthedocs/builds/views.py
- readthedocs/core/views/hooks.py
- readthedocs/oauth/services/github.py
- readthedocs/projects/constants.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/rtd_tests/tests/test_oauth.py
- readthedocs/templates/builds/build_detail.html
- readthedocs/vcs_support/backends/git.py
This PR Will work on improving the code for PR builder by updating the code suggested in code reviews
> Refine PR Builder Code

- docs/builds.rst
- readthedocs/doc_builder/environments.py
This was requested by a user since they can't get it via conf.py,
because we inject our logic after their conf.py data.
> Add READTHEDOCS_LANGUAGE to the environment during builds

- readthedocs/doc_builder/python_environments.py
This will be the release with the upgrades for our search deploy,
so we need to wait until that code is deployed on RTD before we start installing it.
Refs https://github.com/readthedocs/readthedocs-sphinx-ext/pull/73
> Bump the Sphinx extension to 1.0

- readthedocs/doc_builder/python_environments.py
Without a cwd with permissions, it fails with the error:
```
/bin/sh: 1: cd: can't cd to /home/docs/checkouts/readthedocs.org/readthedocs
```
> Long live to Feature Flags!
> Use a cwd where the user has access inside the container

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
Not sure how I missed this.
This should cause us to have proper env vars in builds
I've tested it locally and it looks :100: on `test-builds`.
> Missed a couple places to set READTHEDOCS_LANGUAGE

- readthedocs/search/api.py
- readthedocs/search/utils.py
- readthedocs/search/views.py
I have moved the sorting logic to `search.utils`.
> Hotfix: Return empty dict when no highlight dict is present

- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This will add a warning banner to external version docs.
To use this we need to add this in the requirements as its not merged
`git+https://github.com/saadmk11/readthedocs-sphinx-ext/@external-version-warning`
Sphinx Extension PR: https://github.com/readthedocs/readthedocs-sphinx-ext/pull/72
> Add check for external version in conf.py.tmpl for warning banner

- readthedocs/projects/tasks.py
This has to be done before deleting ImportedFiles and not with a cascade,
because multiple Domain's can reference a specific HTMLFile.
> Explicitly delete SphinxDomain objects from previous versions

- readthedocs/builds/constants.py
This will improve the mobile view as mobile view of github does not show the name of the service.
> update build status message for github

- readthedocs/templates/projects/project_import.html
> Point users to commercial solution for their private repositories

- docs/api/v3.rst
- docs/config-file/v1.rst
- docs/development/design/in-doc-search-ui.rst
- docs/development/docs.rst
- docs/development/search.rst
- docs/roadmap.rst
- readthedocs/api/v2/views/integrations.py
- readthedocs/api/v3/views.py
- readthedocs/builds/admin.py
- readthedocs/builds/managers.py
- readthedocs/builds/models.py
- readthedocs/config/tests/test_config.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
- readthedocs/projects/admin.py
- readthedocs/projects/querysets.py
- readthedocs/rtd_tests/fixtures/spec/v2/schema.yml
- readthedocs/rtd_tests/tests/test_managers.py
- readthedocs/vcs_support/backends/git.py
Fix typos across **readthedocs.org repository**
**Fixed files**
```
readthedocs.org/docs/api/v3.rst:358:28: "sucessfully" is a misspelling of "successfully"
readthedocs.org/docs/config-file/v1.rst:10:50: "avaliable" is a misspelling of "available"
readthedocs.org/docs/development/design/in-doc-search-ui.rst:50:33: "explaing" is a misspelling of "explaining"
readthedocs.org/docs/development/docs.rst:9:71: "enviroment" is a misspelling of "environment"
readthedocs.org/docs/development/search.rst:42:27: "devided" is a misspelling of "divided"
readthedocs.org/docs/roadmap.rst:48:16: "verison" is a misspelling of "version"
readthedocs.org/readthedocs/api/v2/views/integrations.py:116:20: "overriden" is a misspelling of "overridden"
readthedocs.org/readthedocs/api/v3/views.py:104:33: "attribue" …
```
> Fix typos across readthedocs.org repository

- readthedocs/projects/tasks.py
We should not check if the version is external inside the task. we should check it before we call the task. this will reduce the number of unnecessary celery tasks called.
> update external version check for notification task

- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/rtd_tests/tests/test_views.py
This makes these tests pass in the corporate site, we are relying in the default value (public), but in the corporate site this is private.
> More explicit setup for tests

- readthedocs/profiles/urls/private.py
- readthedocs/profiles/views.py
- readthedocs/templates/profiles/base_profile_edit.html
- readthedocs/templates/profiles/private/token_list.html
Some comments here:
- Currently we support one Token per User (it's a OneToOne relation on the model that comes with DRF) --although, the Django view it's a ListView
- I added this token under the user's settings since it's where I think it makes the most sense
- Once we support Scoped Tokens, we can refactor this page to show them all here mentioning their limitations/allowed permissions.
- In case the Scoped Tokens would be Project-based, we can add a similar page under Project's Admin.
I'm not sold on this page and I accept comments and probably a complete re-work or re-structure (*)
(*) my other idea was to just add a message like: "Hey there! We are testing our APIv3 and you were given early access to help us with your feedback. Here you have the token to start testing it out: …
> Show APIv3 Token under Profile settings

- readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
- Request community only ads on themes where we don't support regular ads
- This should not be merged until the relevant server side changes are merge in https://github.com/readthedocs/readthedocs-ext/pull/247
> Community only ads for more themes

- docs/guides/feature-flags.rst
- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/models.py
We run 3 steps when a project depends on conda.
1. create the whole environment based on user's YAML file
2. run `conda install` with our own dependencies
3. run `pip install` with some of our dependencies that are not
published on conda repositories.
This commit changes this to make it in just one step (at environment
creation). To do this, it appends our own requirements to the
`environment.yml` file under `dependencies` and `dependencies.pip`
config (see https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually)
It also shows the resulting `environment.yml` in the build output.
This behavior is added behind a feature flag so we can test it first.
This allow users to be able to pin their dependencies as they want
without us …
> Append core requirements to Conda environment file

- readthedocs/doc_builder/python_environments.py
It seems that in the last minute refactor of #5956 I deleted an important line that adds our conda core dependencies to the environment.yml file.
Now we are only adding our pip core dependencies, which is half of the work needed.
> Missing list.extend line when appending conda dependencies

- readthedocs/projects/tasks.py
This makes it include submodule cloning.
This is mainly to include the SSH agent during submodule cloning on the corporate site.
> Expand the scope between `before_vcs` and `after_vcs`

- docs/development/settings.rst
- readthedocs/builds/models.py
- readthedocs/settings/base.py
- readthedocs/settings/dev.py
This allows us to properly set a new domain in production for the external version hosting.
It's a bit hacky for now,
mostly because we don't have a way to specify HTML or PDF versions of the external versions.
We will need to think more about the UX around multiple types,
but that's also an existing issue with our current doc builds (we only link to HTML).
> Update get_absolute_url for External Versions

- readthedocs/projects/version_handling.py
- readthedocs/rtd_tests/tests/projects/test_version_sorting.py
* Handle `.x` in version sorting (eg. `1.0.x` or `2.x`). A few projects use this in their branch names like Pallets and Django.
* Added tests for version sorting
Fixes: https://github.com/readthedocs/readthedocs.org/issues/6010
> Handle .x in version sorting

- docs/advertising/ethical-advertising.rst
- docs/advertising/index.rst
- docs/builds.rst
- docs/commercial/custom_domains.rst
- docs/commercial/index.rst
- docs/commercial/organizations.rst
- docs/commercial/sharing.rst
- docs/custom_domains.rst
- docs/custom_installs/index.rst
- docs/index.rst
- docs/intro/import-guide.rst
- docs/privacy.rst
- docs/support.rst
- This PR exclusively updates docs
- Link to the RTD for Business docs from relevant pages (eg. "Need commercial support? See RTD.com")
- I did only a very minor update to the privacy levels docs which probably need a more major overhaul to explain what RTD for Business offers there relative to the community site. This is on the roadmap already, I believe.
> Link to Read the Docs for Business docs from relevant sections

- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_celery.py
> Fix issues around remote repository for sending Build status reports

- docs/privacy-policy.rst
- readthedocs/gold/templates/gold/subscription_form.html
- readthedocs/templates/base.html
- readthedocs/templates/projects/project_advertising.html
- readthedocs/templates/support.html
This is a text-only change. It essentially updates a few places and standardizes on the verbiage "Read the Docs for Business" for readthedocs.com.
> Use Read the Docs for Business everywhere

- readthedocs/builds/models.py
We should not delete the external version files from the storage so that the links sent through GitHub Status API still work.
> Do not delete media storage files for external version

- readthedocs/builds/models.py
- readthedocs/rtd_tests/tests/test_version.py
- readthedocs/templates/builds/build_detail.html
We should not show wipe version message on the build details page for external versions as we disabled wipe version functionality for external versions.
https://github.com/readthedocs/readthedocs.org/blob/93bcf8d19c367e1088893a4902b15a05d1ad190f/readthedocs/core/views/__init__.py#L74-L79
> Do not show wipe version message on build details page for External versions

- readthedocs/builds/models.py
- readthedocs/oauth/notifications.py
- readthedocs/projects/constants.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_celery.py
> Send site notification on Build status reporting failure and follow DRY

- readthedocs/projects/forms.py
The translation was not being saved before adding to the parent project.
This surfaced an issue when the database is different, like in the case
where we use a database router to send read/write operations to
different databases.
> Fix issue with save on translation form

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
Mostly this just affected Pylons projects as they specify precisely where the ad on their themes should go but their theme is neither the RTD theme nor Alabaster.
> Fix around community ads with an explicit ad placement

- readthedocs/projects/tasks.py
We should be more careful checking for it.
> When called via SyncRepositoryTaskStep this doesn't exist

- readthedocs/projects/templatetags/projects_tags.py
- readthedocs/projects/version_handling.py
- readthedocs/rtd_tests/tests/projects/test_version_sorting.py
- readthedocs/vcs_support/backends/__init__.py
Ref https://github.com/readthedocs/readthedocs.org/issues/6010#issuecomment-519340989
> Sort versions taking into consideration the vcs type

- docs/guides/conda.rst
Just remove the warning note since it's not in beta anymore.
> Remove warning about beta state of conda support

- readthedocs/analytics/tests.py
- readthedocs/analytics/utils.py
It's unclear to me whether our production proxies would ever include an IPv6 with port. In the errors I'm seeing in prod, I don't see that. X-Forwarded-For is not exactly a standard so there isn't something to look up here.
> IPv6 in X-Forwarded-For fix

- readthedocs/analytics/tasks.py
- readthedocs/analytics/utils.py
- readthedocs/projects/views/public.py
While data will be sampled, this will give us an idea of how frequently media (zips, PDFs, ePubs) are downloaded.
> Send media downloads to analytics

- readthedocs/api/v2/views/integrations.py
- readthedocs/builds/constants.py
- readthedocs/builds/models.py
- readthedocs/projects/constants.py
- readthedocs/rtd_tests/tests/test_api.py
- readthedocs/rtd_tests/tests/test_builds.py
- readthedocs/rtd_tests/tests/test_project.py
- readthedocs/rtd_tests/tests/test_version.py
- readthedocs/vcs_support/backends/git.py
ref: https://github.com/readthedocs/readthedocs.org/issues/6052
> PR Builder GitLab Integration

- readthedocs/oauth/services/base.py
- readthedocs/oauth/services/bitbucket.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/oauth/tasks.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_project_views.py
- readthedocs/templates/projects/integration_webhook_detail.html
A lot of work needs to be done and a lot of cases needs to be handled before its ready for review. :)
closes https://github.com/readthedocs/readthedocs.org/issues/3932
related to the first step of #6052
> Auto Sync and Re-Sync for Manually Created Integrations

- docs/advertising/ad-blocking.rst
- docs/advertising/ethical-advertising.rst
- docs/advertising/index.rst
- docs/privacy-policy.rst
- media/css/core.css
- readthedocs/gold/__init__.py
- readthedocs/gold/admin.py
- readthedocs/gold/apps.py
- readthedocs/gold/models.py
- readthedocs/gold/templates/gold/projects.html
- readthedocs/gold/templates/gold/subscription_confirm_delete.html
- readthedocs/gold/templates/gold/subscription_detail.html
- readthedocs/gold/templates/gold/subscription_form.html
- readthedocs/gold/views.py
- readthedocs/rtd_tests/tests/test_gold.py
- readthedocs/templates/profiles/base_profile_edit.html
- readthedocs/templates/profiles/private/advertising_profile.html
- readthedocs/templates/projects/project_advertising.html
- readthedocs/templates/projects/project_dashboard.html
- readthedocs/templates/support.html
- Be clear about this in the docs and gold app
- Re-enable the gold member screen to designate gold projects for all members
- $5/mo for personal or small biz and $50 for corporate
This mostly reverts #5628. The areas where I would most like feedback are in `subscription_detail.html`, `projects.html`, and `subscription_form.html`.
* There is absolutely nothing stopping a corporate OSS project from becoming a $5/mo member and removing ads. Only the text says they are supposed to pay more.
* While it isn't a big concern, we weren't quite as clear about gold removing all ads before although the screen totally did that in the past. It is possible that projects where we generate more than $5/mo in advertising suddenly go ad-free resulting in less revenue.
> Gold makes projects ad-free again

- readthedocs/core/middleware.py
When running in development with `USE_SUBDOMAIN=True` and
`PRODUCTION_DOMAIN=dev.readthedocs.io:8000` we receive an error when
accessing the docs.
This allows this case to succeed,
skip these checks and serve the docs properly.
> Avoid returning invalid domain when using USE_SUBDOMAIN=True in dev

- docs/conf.py
As far as I can tell, neither the Python Intersphinx mapping nor the Django one are used in our docs. We are planning an upcoming Intersphinx guide and/or blog so this should be helpful for that.
> Update intersphinx mapping with canonical sources

- readthedocs/api/v2/urls.py
- readthedocs/api/v2/views/footer_views.py
- readthedocs/rtd_tests/tests/test_footer.py
This is going to help us to extend this view more easily
from the corporate site.
Logic is the same, just code was moved.
>  Refactor footer_html view to class

- readthedocs/core/admin.py
This lets us actually load the admin page in prod :)
> Use raw_id_fields in the TokenAdmin

- readthedocs/projects/tasks.py
- readthedocs/settings/base.py
This is the next phase in testing smaller disks on our build servers. It
makes the `CLEAN_AFTER_BUILD` feature flag into a server-wide setting,
allowing us to test the artifact-less build server on our normal build
queue.
> Add setting for always cleaning the build post-build

- readthedocs/api/v2/permissions.py
- readthedocs/api/v2/views/footer_views.py
- readthedocs/projects/models.py
This allow us to override the authorization from the corporate site.
Everything that makes use of `request.user` now can be overridden :)
> Move out authorization from FooterHTML view

- readthedocs/vcs_support/base.py
Turns out we are logging this manually
https://github.com/readthedocs/readthedocs.org/blob/00ab116ec09e75b74c20c1abdc7b9a9a47d9e673/readthedocs/projects/tasks.py#L254-L265
Closes #4590
> Don't log BuildEnvironmentWarning as error

- readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This mostly reverts #5973 and allows paid advertising on all themes.
> Fixed footer ads supported on all themes

- readthedocs/builds/urls.py
- readthedocs/builds/views.py
- readthedocs/core/views/hooks.py
- readthedocs/projects/urls/private.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/rtd_tests/tests/test_views.py
Some general cleanup.
We could just remove the old redirects if we want to.
Related #5856
> Clean up views

- docs/commercial/sharing.rst
This is to reflect changes on .com
Also, I put a note that password and HTTP header are on beta currently.
I wanted to add an example using `requests` additionally to the one using `curl`. What do you think?
> Update docs for sharing

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/public.py
- readthedocs/search/parse_json.py
Storage is now required. By default, storage uses local storage on the filesystem so it doesn't have to be some cloud storage.
> Remove if storage blocks

- docs/connected-accounts.rst
This is a documentation only pull request that just documents why we ask for the permissions from GitHub, Bitbucket, and GitLab. We've had a few questions about this in the past.
There is a meta question of whether this is the right place for this information. Another question is whether we should link to this from the login and signup screens so users are prepared for permission prompts.
> Document connected account permissions

- readthedocs/builds/storage.py
Edit: closely mirror the logic to get the production media path:
https://github.com/readthedocs/readthedocs.org/blob/557c875fa4d74e1cb69146e005375595f80adf91/readthedocs/projects/models.py#L584-L598
> Customize default build media storage for the FS

- docs/faq.rst
I've seen a lot of confusion,
users use the old solution instead of the recommended one.
> Only use the sphinx way to mock

- readthedocs/builds/views.py
- readthedocs/projects/views/public.py
Build list page `Build Version` form lists the active versions of a project only, but the `BuildTriggerMixin` does not limit the versions to active only.
> Only Build Active Versions from Build List Page Form

- readthedocs/rtd_tests/tests/test_search_json_parsing.py
This is to fix tests on .com.
This test broke with the new changes on #6215
> Override production media artifacts on test

- readthedocs/api/v3/serializers.py
> moved expandable_fields to meta class

- readthedocs/api/v2/urls.py
- readthedocs/api/v2/views/model_views.py
This was throwing an exception (it doesn't have a serializer)
> Remove dead code

- readthedocs/projects/urls/private.py
- readthedocs/projects/views/private.py
> Refactor views ProjectUsers

- docs/index.rst
- docs/privacy-policy.rst
- docs/terms-of-service.rst
**As this changes the terms of service for Read the Docs, it should not be merged without approval of either @agjohnson, @ericholscher, or both**
This PR adds a terms of service for Read the Docs, Read the Docs for Business, and Documentation Sites. It updates the Privacy Policy to link to the terms.
* I wrote the terms with the intention that they apply to Read the Docs for Business
* I followed [sentence case](https://docs.readthedocs.io/en/stable/development/docs.html#titles) for non-H1 headings except when a term was from the definitions section
* These terms were heavily influenced (see: borrowed or lifted) from [GitHub's CC-0 licensed site policies](https://github.com/github/site-policy/)
* GitHub's terms had a whole sub-document on serving legal notice. Since we don't have that in …
> Add terms of service

- readthedocs/doc_builder/python_environments.py
Avoid caching `pip` packages if we are using CLEAN_AFTER_BUILD.
This PR decide when to use `--cache-dir` or `--no-cache-dir` based on this setting.
@stsewd what do you think about this? If you think it's OK, I will fix the tests tomorrow.
Related https://github.com/readthedocs/readthedocs.org/pull/6236#issuecomment-537597611
> Do not use --cache-dir for pip if CLEAN_AFTER_BUILD is enabled

- readthedocs/projects/urls/public.py
- readthedocs/projects/views/public.py
Fixes #6221
I am relatively new to development with Django but to remove the publicly accessible `/projects` path, only a small amount of removals seemed to be required.
I did not remove the [ProjectIndex](https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/projects/views/public.py#L40 ) class, as it seems that the tags functionality is dependant on it. If you're happy for the tags to go, I will be happy to update my PR.
I did not remove the [project_urls](https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/urls.py#L56-L58) section, as clicking on a project as a logged in user takes you to a `/projects/<project_name>` route.
Please let me know how I did in meeting your expectations …
> remove /projects/

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
closes https://github.com/readthedocs/readthedocs.org/issues/4966
> Make raw_config private

- readthedocs/projects/views/public.py
- readthedocs/templates/projects/project_version_list.html
Update the version listview screen with the following:
- No more than 100 inactive versions
- Filter inactive versions by name
- Fixes #6070
> Improve the version listview

- readthedocs/projects/views/public.py
- readthedocs/rtd_tests/tests/test_project_views.py
- Refactored the badge view into a class-based view
- Private versions require a token. This PR also adds the token to the badge examples/directions in the dashboard for private versions. This PR doesn't do anything for protected versions. Should it?
- Token is generated from the project_slug and the secret key which has a few implications:
* A token can't be invalidated without changing the project slug or secret key. If somebody leaks their token, it's basically leaked. All it leaks is the status of the build, but it does leak information. 
* The token is *not* based on the version so leaking the token for a project would leak the existence of *all* versions for that project. However, this makes changing the badge to show a different version as easy as changing the `?version=latest` …
> Allow project badges for private version

- docs/Makefile
- docs/api/v3.rst
Some fields are not used.
I'm brining some changes from https://github.com/readthedocs/readthedocs.org/pull/6169
to avoid merge conflicts.
> Update doccs version detail (api v3)

- requirements/pip.txt
> Downgrade django-storges.

- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_privacy_urls.py
- readthedocs/templates/projects/project_translations.html
- readthedocs/templates/projects/project_version_detail.html
closes: https://github.com/readthedocs/readthedocs.org/issues/6189
> Allow only post requests for delete views

- readthedocs/templates/projects/project_version_list.html
Previously it would hide the UI when users search
for a term with no matching versions
> Fix inactive version list not showing when no resuts returned

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
closes https://github.com/readthedocs/readthedocs.org/issues/4914
> Add Better error message for lists in config file

- readthedocs/api/v3/serializers.py
Fix a small issue that we noticed when deploying.
Accessing the subproject list returns a 500: https://readthedocs.org/api/v3/projects/test-builds/subprojects/
> Default to None when using the Serializer as Form for BrowsableAPI

- readthedocs/api/v3/serializers.py
- readthedocs/api/v3/tests/test_subprojects.py
- readthedocs/rtd_tests/tests/test_subprojects.py
fixes: https://github.com/readthedocs/readthedocs.org/issues/6271
> API V3 Subproject Creation Bug fix

- readthedocs/api/v2/templates/restapi/footer.html
> Fix footer

- readthedocs/projects/views/public.py
- readthedocs/templates/projects/project_list.html
Hello people,
This pull request fixes issue #6250.
Thanks,
Jafer
Fixes #6250
> Removed unused code from view and template (#6250)

- readthedocs/builds/storage.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_build_storage.py
We use `rsync` for our _normal_ storage, but for blob storage we are just doing a copy.
Full explanation at https://github.com/readthedocs/readthedocs.org/pull/6186#issuecomment-542496770
This is _heavily borrowed_ from a snippet from @davidfischer  :)
Fixes #6069
Closes #6186
> Use sync instead of copy for blob storage

- .travis.yml
- docs/development/front-end.rst
- docs/development/install.rst
- tox.ini
> Fix eslint

- requirements/pip.txt
1.7.2 fixes an issue on Azure with filenames that contain spaces.
Closes #6328 
Needs https://github.com/readthedocs/readthedocs-ext/pull/266
> Upgrade django-storages

- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/settings/base.py
This is basically the same as https://github.com/readthedocs/readthedocs.org/pull/6327, with tests fixed.
Users get python 3.8 only if they have `python: 3` as version (not if they have `python: 3.x`) or aren't using a configuration file and have `python3` set on the web UI.
https://github.com/readthedocs/readthedocs-docker-images/pull/111 is needed.
> Support 6.0rc1 build image

- docs/gsoc.rst
Closes #6156 
Added previous year gsoc project to the gsoc.rst file
> added previous year gsoc projects

- readthedocs/search/tasks.py
> Changing created to modified time

- readthedocs/builds/models.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_build_forms.py
- readthedocs/search/utils.py
Currently, we are not removing files from storage when a version is deactivated. And we are not removing indexes from ES when a project/version is deleted or a version is deactivated.
Have to refactor `remove_indexed_files` to accept a slug instead of an instance, so we avoid having to make a query.
> Remove files from storage and delete indexes from ES when no longer needed

- readthedocs/search/api.py
- readthedocs/search/tests/test_api.py
Return an empty response instead.
Related sentry issue https://sentry.io/organizations/read-the-docs/issues/902771096/?project=148442&query=is%3Aunresolved++search
> Don't error on non existing version

- readthedocs/builds/models.py
- requirements/pip.txt
The regex module is compatible with the re module (VERSION0 flag).
It is also faster.
```python
>>> import re
>>> import regex
>>> import timeit
>>> pattert = "(a+)+b"
>>> input = "a" * 25
>>> timeit.timeit(lambda: re.search(pattern, input), number=10)
32.332445038000515
>>> timeit.timeit(lambda: regex.search(pattern, input, flags=regex.VERSION0), number=10)
0.003861578001306043
>>> input = "a" * 10000
>>> regex.search(pattern, input, flags=regex.VERSION0, timeout=5)
File "<stdin>", line 1, in <module>
File "/home/stsewd/.pyenv/versions/readthedocs.org/lib/python3.6/site-packages/regex/regex.py", line 266, in search
concurrent, partial, timeout)
TimeoutError: regex timed out
```
I put the timeout to 15, maybe we can drop it to 5?
> Protection against ReDoS

- readthedocs/core/static-src/core/js/doc-embed/footer.js
- readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
This allows us to respect the ``api_host`` that might be configured
in pre-built documentation.
Previously these would all default to ``readthedocs.org``,
which isn't great for local dev or custom installs.
> Change the default of proxied_api_host to api_host

- readthedocs/api/v2/views/footer_views.py
- readthedocs/builds/models.py
- readthedocs/rtd_tests/tests/test_footer.py
We use the `get_absolute_url` in other parts of the code
where it makes sense to link to the dashboard.
So I'm adding an additional parameter.
Closes #6137
> Dont link to dashboard from footer

- readthedocs/api/v2/views/footer_views.py
- readthedocs/builds/models.py
- readthedocs/rtd_tests/tests/test_footer.py
This is a better approach for https://github.com/readthedocs/readthedocs.org/pull/6353
> Don't compare inactive or non build versions

- readthedocs/rtd_tests/tests/test_footer.py
This setting is the one used in production as `True`. So, this helps us to make the tests closer to prod but also to make them pass on corporate where we force `require_https` in the resolver.
> Force PUBLIC_DOMAIN_USES_HTTPS on version compare tests

- .github/workflows/main.yml
Secrets are set in https://github.com/readthedocs/readthedocs.org/settings/secrets only users with write access can see/edit them 
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets
Docs from circle
https://circleci.com/docs/2.0/api-job-trigger/
> Use github actions to trigger tests in corporate

- readthedocs/api/v3/serializers.py
Looked into other APIv3 forms But there is no form that has a project ChoiceField.
closes: https://github.com/readthedocs/readthedocs.org/issues/6372
> Show only users projects in the APIv3 browseable form

- readthedocs/api/v2/views/footer_views.py
- readthedocs/rtd_tests/tests/test_api_version_compare.py
- readthedocs/rtd_tests/tests/test_footer.py
We added a setting about whether to show this to the user or not,
but always calculated the data regardless of the setting.
@humitos does this break your extension, or is it respecting this setting also?
> Small optimization to not compute the highest version when it isn't displayed

- readthedocs/search/utils.py
Each method returns a new object,
it doesn't modify the current one
> Fix search indexing

- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views.py
This lets us just return a redirect if the file exists. This matches the
existing nginx behavior, except it actually appends the index filename
instead of just a slash.
I'm not sure which is better, but this is more explicit which feels good.
> Redirect index files in proxito instead of serving

- readthedocs/proxito/tests/base.py
- readthedocs/proxito/tests/test_full.py
This is needed to fix tests in the corporate site
where all versions are private by default.
Some tests expect them to be public.
> Set privacy level explicitly

- readthedocs/proxito/views/serve.py
This is useful in commercial site to override `allowed_user` method to the required auth checks and decide if the file should be served to the user or not.
In the community site, this method should always return `True` since all projects/versions are public.
This is all the code changes required in the community site. Feel free to suggest a better pattern or better names for the methods.
This PR is based on #6396
> Allow to extend El Proxito views from commercial

- docker-compose.yml
I missed the `--location` argument on Azurite container to persist data after the container is removed. This PR adds that argument and make data to be persistent.
> Use /data inside Azurite container to persist data

- docker/Dockerfile
Minor fix to use WORKDIR instead of `cd` into the previous RUN command.
> Use WORKDIR to cd into a directory in Dockerfile

- media/css/core.css
- readthedocs/projects/static-src/projects/css/admin.less
- readthedocs/projects/static/projects/css/admin.css
- readthedocs/templates/builds/versionautomationrule_list.html
Remove hard coded values in HTML for font awesome and override the
values with CSS instead.
The problem with how the underlying PR is written is that normally all of this is done with CSS, the values are not hard coded in the HTML. We can't override this on commercial styling as easy when we hardcode the value into HTML. This is a better example of how to do CSS, classes on the module and module elements, and how to add a font awesome icon to a button.
> Fix CSS and how we were handling html in automation rule UI

- docs/commercial/sharing.rst
Mention that the token can be used in basic authorization
I'll try to write a guide using this with intersphinx :)
> Update docs on sharing

- docs/api/v3.rst
Only "Project Update" is updated. I didn't find more cases where we need to expand our docs to show all the available fields.
Closes #6385
> Add more supported field to APIv3 docs

- readthedocs/api/v3/serializers.py
- readthedocs/api/v3/tests/test_subprojects.py
- readthedocs/projects/forms.py
- readthedocs/projects/models.py
ref: https://github.com/readthedocs/readthedocs.org/pull/6275#issuecomment-541553493
> Refactor Subproject validation to use it for Forms and API

- readthedocs/proxito/tests/base.py
This middleware is required to run the tests in Corporate because the `allowed_user` method uses `request.user` to make the decision.
I'm not sure if there is a better way to do this by overriding one of this setting in the corporate site. We have been skipping these kind of tests, but I think El Proxito is important in corporate and it's better to run these tests as well.
> Add AuthenticationMiddleware to El Proxito tests

- media/css/core.css
- readthedocs/gold/forms.py
- readthedocs/gold/templates/gold/projects.html
- readthedocs/gold/urls.py
- readthedocs/gold/views.py
closes #5856
Changed a bit of the template otherwise had to do hack like this: https://github.com/readthedocs/readthedocs.org/pull/6242#discussion_r331109950
> Refactor Gold Views

- readthedocs/core/management/commands/update_repos.py
Use `trigger_build` (that will use Celery if enabled) when importing a Project (import_project_from_live) or updating documentation (update_repos) via manage commands.
> Use trigger_build for update_repos command

- readthedocs/builds/models.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/rtd_tests/tests/test_version.py
This change allows us to query the database instead of the file system or remote storage to get whether a version has a download of a specific type.
Currently, we rely on the presence of a file existing at a certain filesystem or storage path to determine whether media/downloads are available. As we move toward storage being an abstraction on top of the filesystem where it is possibly remote (eg. Cloud storage) we don't want to have to query remote storage to know whether a version has a PDF.
Instead, we started caching whether a version has builds of a specific type (eg. a PDF, ePub) and storing it on the `Version` model. After we started storing that data, a script was run to store the results for all previously built versions.
This builds on work in …
> Use media availability instead of querying the filesystem

- readthedocs/redirects/querysets.py
This queryset introduced a bug where a from_url of 5 characters would
produce and exception.
> Partial revert of 81768fc7 (#6398)

- readthedocs/rtd_tests/tests/test_version.py
This fixes tests in .com where it's readthedocs.com instead.
> Override production domain explicitly

- readthedocs/builds/admin.py
Right now we just see empty rules when a project is using predefined matches
> Show predefined match on automation rules admin

- docker-compose.yml
- docker/Dockerfile
- readthedocs/settings/docker_compose.py
- readthedocs/storage/azure_storage.py
- readthedocs/storage/base.py
- readthedocs/storage/mixins.py
- requirements/pip.txt
This commit allow us to build and run all the Read the Docs stack without depending on readthedocs-ext repository allowing anyone to launch "docker-compose up"
> Bring Azure storage backend classes to this repository

- readthedocs/doc_builder/python_environments.py
- readthedocs/projects/tasks.py
This avoid exposing potential secrets when a PR is opened.
> Do not expose env variables on external versions

- readthedocs/doc_builder/environments.py
- readthedocs/projects/models.py
- readthedocs/settings/base.py
This is not working anymore and it can be superseded by a docker container with devpi instead (see #6340).
> Remove global pip cache

- readthedocs/core/management/commands/update_repos.py
I'm not quite sure why we have the else statement here isn't `slugs` a required argument here?
closes https://github.com/readthedocs/readthedocs.org/issues/6427
> Fix logic to build internal/external versions on update_repos management command

- docs/guides/build-notifications.rst
- readthedocs/core/utils/__init__.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_build_notifications.py
~~I did not add support for build status API of GitHub, Gitlab etc. as those need a different approach than what we currently have. We need to send the `sha` of the commit with the URL as the their docs Suggests.~~
~~ie: `POST /repos/:owner/:repo/statuses/:sha`
[Github Build Status API Docs](https://developer.github.com/v3/repos/statuses/#create-a-status) Gitlab also has a similar implementation. 
We need  some `Design Decisions` for adding support for this. We can add some kind of module to handle the status APIs.~~
We are sending PR Build Status reports using GitHub Status API https://github.com/readthedocs/readthedocs.org/pull/5865 and planning to extend to other providers.
closes #2251
> Extend webhook notifications with build status

- docs/guides/feature-flags.rst
- readthedocs/projects/models.py
- readthedocs/projects/views/private.py
- readthedocs/rtd_tests/tests/test_views.py
This pull request references the issue [#6349](https://github.com/readthedocs/readthedocs.org/pull/6349).
Changes : 
- Removed SEARCH_ANALYTICS flag from feature-flags
- Removed SEARCH_ANALYTICS property from the Feature class under project/models.py
- Removed 'Enable search analytics' tuple from the Feature object.
Closes https://github.com/readthedocs/readthedocs.org/issues/6217
> Fixed remove_search_analytics issue

- readthedocs/templates/projects/project_edit_base.html
This will let users easily find the current version editing UI,
and be the place we'll eventually move it after a refactor.
> Add an "Edit Versions" listing to the Admin menu

- docker-compose-search.yml
- Disable check for allocation which is not needed on development
- Set a better name to the node
This avoid the cluster going read-only mode because not "enough" space on disk,
```
search_1     | [2019-12-05T16:38:02,390][WARN ][o.e.c.r.a.DiskThresholdMonitor] [1qOjoH7] flood stage disk watermark [95%] exceeded on [1qOjoH7qRX2hXuMCo80xOg][1qOjoH7][/usr/share/elasticsearch/data/nodes/0] free: 4.2gb[4.7%], all indices on this node will be marked read-only
```
> Better ES settings on docker-compose

- docker-compose.yml
- dockerfiles/entrypoints/build.sh
- dockerfiles/entrypoints/celery.sh
- dockerfiles/entrypoints/proxito.sh
- dockerfiles/entrypoints/web.sh
- dockerfiles/tasks.py
This stops containers from auto-reloading.
> Add DOCKER_NORELOAD to compose settings

- readthedocs/projects/signals.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_celery.py
- readthedocs/rtd_tests/tests/test_config_integration.py
Currently, when `sync_repository_task` gets triggered we use a `LocalEnvironment` as environment.
We want to be explicit about respecting the docker setting in all places where we do a clone (needed for https://github.com/readthedocs/readthedocs.org/pull/6436).
Also, it's really confusing depending on the order of calls to have `self.setup_env` and `self.build_env` set. Wasn't able to remove completely `self.setup_env`, we still use it outside the function that creates the environment.
I've moved/modified the signals to be run just before the first command and send the current environment to execute over the ssh commands. 
~I still need to test this locally and see if it doesn't break anything else.~
> Be explicit when using setup_env

- dockerfiles/nginx/proxito.conf
- readthedocs/proxito/tests/base.py
- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views/serve.py
- readthedocs/rtd_tests/storage.py
- readthedocs/settings/test.py
Isolate fixes from https://github.com/readthedocs/readthedocs.org/pull/6419/commits/6c2b187969bcf7837ed26f5f6511bfd0e7bab106#diff-fd3394188d8793947a3ccbb4924994a1R99 
With this change, we pass the full URL back to NGINX who will proxy it as is to the storage.
This fixes currently 404 in production for test-builds documentation for all versions.
> Use django storage to build URL returned by El Proxito

- readthedocs/api/v2/views/integrations.py
- readthedocs/rtd_tests/tests/test_api.py
This fixes https://github.com/readthedocs/readthedocs.org/issues/6464
> Handle GitHub Push events with `deleted: true` in the JSON

- docker-compose.yml
Use an en variable to call the proper Celery app in .org/.com
> Use CELERY_APP_NAME to call the proper celery app

- readthedocs/projects/tag_utils.py
It is possible to get an empty tag by putting the following into the tag string `a,!`. Mostly spam projects have done this. This change will ensure empty tags aren't saved.
Current functionality:
```
>>> from readthedocs.projects.tag_utils import rtd_parse_tags
>>> rtd_parse_tags('a,!')
['', 'a']  # After this change the result will be ['a']
```
> Don't allow empty tags

- docs/config-file/v2.rst
- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/rtd_tests/fixtures/spec/v2/schema.yml
- readthedocs/rtd_tests/tests/test_config_integration.py
fixes #6038 
This fixes the issue of Sphinx make target called dirhtml but also make it conistent with RTD
> Added "dirhtml" target

- readthedocs/templates/projects/projects_search_analytics.html
This patch removes the check of `show_analytics` variable in
`templates/projects/project_search_analytics.html` which were expected after
fixing #6447
> Fixes #6510 -- Removed the `show_analytics` checks from the template

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
We don't record this step, so we don't have a `build`
Also, added protection against None. We default project, version and build to None,
but in some parts we assume there aren't None.
> Don't pass build to environment when doing a sync

- docs/guides/index.rst
- docs/guides/intersphinx.rst
This guide is about how to use intersphinx in general and how to use it in rtd (subprojects, translations, etc) and also with private projects in the commercial site.
> Guide: Intersphinx in Read the Docs

- docs/development/standards.rst
Update the guide to mention docker-compose setup.
I'm interested in @ericholscher review to know if I'm missing some of the commands or workflows that we have been using so far.
On the other hand, I'd like @davidfischer to take a look at this to know if this guide is enough for now to jump into this environment setup.
> Core team development standards guide

- readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
Not sure whether this broken URL exists elsewhere in the system as well - it appears, for instance, behind the "ads served ethically" slogan in the ads at https://qwikidata.readthedocs.io/en/stable/readme.html .
> Fixing a broken link

- readthedocs/proxito/views/serve.py
This is an artifact of our old redirects code:
```
(Pdb) l
59         match = re.match(
60             r'^/(?P<language>%s)/(?P<version_slug>[^/]+)(?P<path>/.*)$' % LANGUAGES_REGEX,
61             path,
62         )
63         import pdb; pdb.set_trace()
64  ->     if match:
65             language = match.groupdict()['language']
66             version_slug = match.groupdict()['version_slug']
67             path = match.groupdict()['path']
68             return language, version_slug, path
69         return None, None, path
(Pdb) match.groups()
('en', 'latest', '/foo.html')
(Pdb)
```
In particular, the regex was capturing the language as `everything up to /`, which then left the `/` always in the filename.
> Fix proxito redirects breaking without a /

- readthedocs/settings/docker_compose.py
We can't depend on DEBUG + INTERNAL_IPS (default check) because the IP of the docker container is dynamic.
> Show debug toolbar when running docker compose

- docs/development/i18n.rst
This commit changes the bad link to fabfile.py to tasks.py file in Internationalization page.
Fixes #6525.
> Update Transifex Integration details in Internationalization page.

- contrib/changelog.hbs
We use this from https://github.com/readthedocs/common/blob/master/changelog.hbs
https://github.com/readthedocs/common/blob/87d335397b26cf9f276003892e12172f6cce08b3/tasks.py#L80-L84
> Remove unused file

- docs/config-file/v2.rst
This patch adds few notes and warnings in the configuration file documentation,
which will warn the user if he/she is using conda enviroment to setup the docs.
Fixes #5388
> Fixes #5388 -- Added Documentation for constraint while using Conda

- readthedocs/projects/views/public.py
- readthedocs/proxito/views/mixins.py
- readthedocs/proxito/views/serve.py
This is the same logic as in the Proxito views,
it just extends it to the downloads.
> Use our standard auth mixin for proxito downloads

- readthedocs/core/utils/general.py
- readthedocs/projects/tasks.py
We are not deleting this directory, here is where PIP caches its
packages.
https://github.com/readthedocs/readthedocs.org/blob/c3001be7a3ef41ebc181c194805f86fed6a009c8/readthedocs/projects/models.py#L673-L677
Users can still get the old (buggy) PIP version because of this.
But why wiping worked for a lot of people?
Because after wiping, we recreate the virtual environment and looks like
PIP  doesn't use the packages from the cache.
But in the next build, when reusing the virtual environment, it will use
the packages from the cache.
ref https://github.com/readthedocs/readthedocs.org/issues/6554#issuecomment-577363191
> Delete .cache dir on wipe

- dockerfiles/settings/proxito.py
I introduce this on #6488 
When el Proxito renders a 404 it fails trying to show the debug toolbar.
> Disable django debug toolbar in El Proxito

- docs/guides/index.rst
There are guides that are about customizing other aspects as well.
> Remove 'build environment' from guides

- readthedocs/doc_builder/python_environments.py
For those finding this on GitHub, this is the step to reproduce thanks to @agjohnson:
```
rm -rf tmp/a
python3.7 -mvirtualenv --system-site-packages --no-download /tmp/a
/tmp/a/bin/python -m pip install --upgrade --cache-dir /tmp/a.cache pip
python3.7 -mvirtualenv --system-site-packages --no-download /tmp/a
/tmp/a/bin/python -m pip install --upgrade --cache-dir /tmp/a.cache pip
```
Example running in our docker container:
```
-> docker run --rm -it readthedocs/build:5.0 /bin/bash
docs@ae7bd8db6007:/$ set -x
docs@ae7bd8db6007:/$
docs@ae7bd8db6007:/$ rm -rf tmp/a
+ rm -rf tmp/a
docs@ae7bd8db6007:/$ python3.7 -mvirtualenv --system-site-packages --no-download /tmp/a
+ python3.7 -mvirtualenv --system-site-packages --no-download /tmp/a
Using base prefix '/home/docs/.pyenv/versions/3.7.3'
New …
```
> Fix issue with pip 20.0 breaking on install

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
This is kind of the same we hit with a local env
https://github.com/readthedocs/readthedocs.org/pull/6503
> Don't assume build isn't None in a docker build env

- dockerfiles/Dockerfile
Using the same path as the one it's mounted later allows us to change
the code and re-load the app with the changes.
> Use proper path to download/install readthedocs-ext

- requirements/pip.txt
This reverts commit 5939bca415b5fac3ec12ff6fb9557b38b3be84bd.
We noticed a lot of strange issues, including Celery dying without an
error, using the upgraded packages and even 4.4.0. Reverting back to
something that works for now.
> Revert "Update celery requirements to its latest version"

- readthedocs/proxito/tests/test_old_redirects.py
- readthedocs/proxito/views/mixins.py
We need to use `build_absolute_uri` here because we want to compare
the full URL (including domain), but the path has to be replaced with
what's in `proxito_path`.
> Avoid infinite redirect on El Proxito on 404

- readthedocs/proxito/middleware.py
- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views/serve.py
- readthedocs/proxito/views/utils.py
This fixes PR serving for single-version projects on proxito.
> Add check for a single_version project having a version_slug for PR builds

- readthedocs/api/v2/adapters.py
- readthedocs/api/v2/client.py
We have experienced some issues for long/infinite waiting time from
builders when hitting the API. Using a timeout is a way to protect
ourselves. We are already using a Retry pattern as well as another way
to protect from a network blip.
> Use timeout on internal API calls

- readthedocs/projects/tasks.py
If the api fails, self.project and self.version are going to be None
and error when logging to sentry
> More protection against None

- docs/api/v3.rst
- media/css/core.css
> Changed documentation of Api v3

- readthedocs/api/v2/views/integrations.py
- readthedocs/core/views/hooks.py
- readthedocs/rtd_tests/tests/test_api.py
When triggering `sync_respository_task` respect the `project.build_queue` and `project.skip` as we do when triggering a build.
> Respect `project.build_queue` and `project.skip` when triggering `sync_repository_task`

- readthedocs/rtd_tests/tests/test_footer.py
This is needed to reuse these tests for the proxied footer html
- All calls to get are replaced for .render() so it can be overridden
(`HTTP_HOST=self.host`).
- The url isn't hardcoded
- For some reason if the class is inherited, the fixtures don't work.
So I just used django_dynamic_fixture.
Ref https://github.com/readthedocs/readthedocs.org/pull/6630
> Make footer tests reusable

- readthedocs/api/v2/templates/restapi/footer.html
In proxito/serve app we don't have access to the urlconf from the main
app. So we need to hardcode the urls, since this template is used in
both apps (main and proxito).
This is needed for https://github.com/readthedocs/readthedocs.org/pull/6630
> Don't depend on urls from the main app on the footer template

- readthedocs/vcs_support/backends/git.py
This optimization only really improves things when there are 1000s of tags.
> Cache tags -> commits for performance

- readthedocs/settings/base.py
Copied from -ops repo to have it as a base setting since it's important for all the environments.
> Enable CELERY_ACKS_LATE

- .travis.yml
- CHANGELOG.rst
- docs/conf.py
- scripts/travis/run_tests.sh
- tox.ini
Since it is hard for big documentations to keep all links up with changes in a project, it's a good idea to check the links are working, to prevent broken links as in #6525 and #6541.
Luckily `sphinx` has this feature built in, so I added it to the test suite.
To prevent the test suite from false positive breaking,  i.e. if a website is temporarily down, I made the test [allow_failures](https://docs.travis-ci.com/user/customizing-the-build/#rows-that-are-allowed-to-fail) in the travis build matrix.
I also added some url patterns to be ignored by the test, since they are only an example case, are local development only or test false positive since the ref is generated by javascript.
> Add linkcheck test for the docs

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/settings/base.py
Instead of always picking the latest minor version when the user just put '2' or '3' in their YAML file, we use a default Python version per Docker image.
This allows us to upgrade our Docker images (`latest` or `stable`) introducing new versions of Python (like `3.8`) without forcing users without specifying a Python version to use the new Python version.
We can easily change the `default_version` in our `latest` or `stable` image when we the new Python version gets more stable and we know we won't affect too many users with the change.
> We can release a `6.0` (plus `testing`) Docker image from current `master` after this gets merged and deployed. We need to create another PR to add this value into the Docker setting, though. See #6654 
Related #6324
> Default python version per Docker image

- readthedocs/config/tests/test_config.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/settings/base.py
- Update our Docker settings to support `6.0` and `testing` images in our YAML file.
- Tag 5.0 as stable
- Tag 6.0 as latest
Edit: this PR includes changes from #6653 so be careful when merging.
> New docker release (6.0 and testing)

- requirements/testing.txt
- tox.ini
This is to allow us to ignore the exit code from pytest when
no tests were collected, when using the -k option, for example.
> Add pytest-custom_exit_code

- readthedocs/conftest.py
- readthedocs/rtd_tests/tests/test_core_tags.py
This is to make some tests pass in .com.
We only uses subdomains on .com,  this setting is always http for .org.
> Always run CoreTagsTests with http

- readthedocs/core/resolver.py
- readthedocs/rtd_tests/tests/test_resolver.py
Parity with production but also allow to run these tests in corporate.
> Use PUBLIC_DOMAIN_USES_HTTPS for resolver tests

- readthedocs/projects/views/public.py
This was causing an issue on .com.
The `allowed_user` functionality works with logged in docs users,
whereas the `public()` queryset method doesn't.
> Remove re-authing of users on downloads.

- readthedocs/config/tests/test_config.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/settings/base.py
This will stop them from validating in the config,
since we are removing them from the build servers.
We have never supported or documented the support for pinning to a specific version,
so I think this should be safe.
> Remove old docker settings

- dockerfiles/nginx/web.conf
- readthedocs/settings/docker_compose.py
Without this change anything that called `request.build_absolute_uri` made a URI of the form `http://web:8000/...` instead of `http://community.dev.readthedocs.io/...`.
This prevented the connected accounts (github, bitbucket, gitlab) from working correctly.
> Use x-forwarded-host in local docker environment

- readthedocs/settings/base.py
- readthedocs/settings/proxito.py
- requirements/pip.txt
[Content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) is a security measure that sites can opt into by sending a configurable HTTP header. When a site is really locked down, this can prevent most XSS attacks by restricting inline JS completely or restricting the origins where scripts may be loaded from or send data to.
Getting there will be hard and this is just a very first step in that process. This change:
- Enables CSP in report-only mode. It will not actually block anything. Violations will be noted to the browser console. In prod, violations can be reported to Sentry if `CSP_REPORT_URI` is configured (the reporting is done by the browser, not some task in our code).
- If CSP were not in report-only mode, the current settings …
> Enable content security policy in report-only mode

- docker-compose.override.yml
I was getting 5xx errors from azurite every other load of a static asset
file. I found this issue and added a fix that was mentioned:
https://github.com/Azure/Azurite/issues/337
I can not reccomend this fix and I did not try to spend any time
understanding Azurite.
> Add azurite --loose option

- readthedocs/builds/views.py
- readthedocs/projects/views/private.py
- readthedocs/projects/views/public.py
I don’t quite know why this was here,
but it definitely broke and this fixes it.
> Remove overriding of object_list in ListView

- docker-compose.override.yml
The goal is to avoid having incompatible versions on different people's development machines. Also, sometimes the storage database is incompatible between versions. If you have an older database from [before Azurite 3.3](https://github.com/Azure/Azurite/releases/tag/v3.3.0-preview), this change will probably be incompatible with your existing data and you'll have to remove it:
```
docker container ls -a | grep -i azurit    # get the container ID
docker container rm <container ID>
docker volume rm community_storage_data
```
The above commands will require you to recreate the static files (`inv docker.up --init`) and your build documentation will no longer be present in local dev and will have to be rebuilt.
> Pin the version of Azurite for docker-compose development

- readthedocs/settings/docker_compose.py
- Only do this when it isn't specified
- While `host.docker.internal` does resolve on a Mac, this isn't helpful because `platform.system() == 'Linux'` when inside docker on a Mac.
> Figure out the host IP when using Docker

- readthedocs/doc_builder/backends/sphinx.py
Injecting versions on the sphinx context isn't that crucial,
since we use the footer_api to get them.
ref https://github.com/readthedocs/readthedocs.org/issues/6712#issuecomment-592154048
> Don't fail a build on api timing out

- readthedocs/core/middleware.py
- readthedocs/rtd_tests/tests/test_footer.py
- readthedocs/rtd_tests/tests/test_middleware.py
- readthedocs/settings/base.py
In Django 2.2, the default SameSite value for cookies became `SameSite=Lax`. This causes cookies to not be sent with cross-domain XHRs (eg. from `*.readthedocs.io` to `readthedocs.org`). We could not set this attribute at all by setting `SESSION_COOKIE_SAMESITE = None` but starting soon Chrome is going to treat unset SameSite the same as `SameSite=Lax`. Chrome wants you to explicitly set `SameSite=None` to get the old cross-site behavior.
There are two problems with this. Firstly, [some browsers completely reject cookies with `SameSite=None`](https://www.chromium.org/updates/same-site/incompatible-clients) and secondly, Django<3.1 doesn't support setting `SameSite=None` out of the box (`SESSION_COOKIE_SAMESITE = None` means `SameSite` is unset rather than set to `None`).
The workaround is …
> Workaround SameSite cookies

- readthedocs/builds/models.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
We can control this on a per-project basis. Once we remove symlinking
and Syncers, this can go away entirely.
> Add feature flag to just completely skip sync and symlink operations

- readthedocs/search/tests/conftest.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/tests/test_faceted_search.py
- readthedocs/search/tests/test_views.py
This is to allow us to run some of them in .com
> Be explicit on privacy level for search tests

- .travis.yml
- docs/development/search.rst
- docs/development/tests.rst
- readthedocs/settings/base.py
- readthedocs/settings/docker_compose.py
This works on travis and docker compose without any change on the
settings
> Make easy to run search tests in docker compose

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
This helps us lower load on specific projects that have a lot of these and aren’t using them.
> Add feature flag for branch & tag syncing to API.

- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
We have a new `testing` image now that we can recommend to users when they need something extra that it's now in our current image, but will be available in the following image.
This allow us to not have to do work manually (like modifying `container_image` in the db), clearly communicate to the user that they are using something that it's not released yet and also allow them to opt-in/out when they want.
> Allow user to set `build.image: testing` in the config file

- readthedocs/doc_builder/backends/sphinx.py
- readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This is the actual error returned,
request wraps https://urllib3.readthedocs.io/en/latest/reference/#urllib3.exceptions.TimeoutError
inside ConnectionError https://2.python-requests.org/en/master/_modules/requests/exceptions/
Related https://github.com/readthedocs/readthedocs.org/pull/6719/
> Catch ConnectionError from request on api timing out

- readthedocs/doc_builder/python_environments.py
This is now the default, and it is removed in newer versions of `venv`.
> Don't call virtualenv with `--no-site-packages`

- readthedocs/api/v2/templates/restapi/footer.html
We are extending this block from corporate code to show an extra section in the flyout menu.
> New block on footer template to override from corporate

- docs/development/standards.rst
There is no need to pull all the images when developing locally. So, we recommend to just use `--only-latest` on the guide.
> Pull only latest image for development

- docs/conf.py
Unfortunately, RTD doesn't support this output because it's a secondary
file. You have to generate this file locally, and you have to also
disable `-W` option, as there are warnings that fail the build,
unrelated to this change.
> Add TOS PDF output

- readthedocs/proxito/views/serve.py
When request method is HEAD we can't use ``storage.url`` because the signature calculated will consider GET as method. `django-storages` does not support passing the HTTP method into ``storage.url`` yet. Because of this, the response won't be exactly the same between GET and HEAD since we are not passing the headers returned by the storage itself.
We just use `storage.exists` and return 200 with an empty body or raise 404.
> Use `storage.exists` on HEAD method

- readthedocs/settings/proxito/base.py
This makes proxito mixin match production for .com/.org
in the areas where we are overriding the same things.
> Expand the logic in our proxito mixin.

- readthedocs/api/v2/permissions.py
- readthedocs/search/api.py
- readthedocs/search/tests/test_api.py
- readthedocs/search/utils.py
This is the same as https://github.com/readthedocs/readthedocs.org/pull/6133
but for the search view.
This allows us to override `get_all_projects` in .com
to filter projects using the auth backends.
And make use of the permission class from .com that makes use of the
auth backends.
This doesn't break the current search endpoint in .com
since it filters the versions using `public(user=self.request.user)`
A change is that now when a project or version doesn't exist, a 404 is raised, and we allow search on PR versions.
This is required to proxy search on .com
> Refactor search view to make use of permission_classes

- requirements/pip.txt
- This version isn't released yet
- This is needed to delete these permanent messages in Django 2.2
> Use the hotfixed version of django-messages-extends

- readthedocs/builds/storage.py
- readthedocs/proxito/views/serve.py
- readthedocs/storage/azure_storage.py
- requirements/pip.txt
This PR upgrades django-storages to a not yet released version to support HEAD method when generating storage URLs that are private (include signed tokens).
I checked the changelog and there is nothing breaking as far as I can tell. All the tests that I did locally using Azurite worked properly.
Note that I'm removing `azure-storage-blob` and `azure-storage-common` from our pinned versions because those are correctly specified on django-storage dependencies as `azure-storage-blob >=1.3.1,<12.0.0`.
I'm interesting on merging this sooner than later, so we can have a week or similar of testing locally before deploying it. Best way to test this is to pull down the PR, re-generate the docker image completely (without cache: `inv docker.build`) and do some storage related operations (build, …
> Upgrade django-storages to support URLs with more http methods

- readthedocs/builds/models.py
- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
We don't need this logic anymore,
since the SKIP_TAGS feature flag solves this with less code overhead
> Revert "Add feature flag to just completely skip sync and symlink operations (#6689)"

- readthedocs/api/v2/views/footer_views.py
- readthedocs/config/config.py
- readthedocs/config/tests/test_config.py
- readthedocs/rtd_tests/tests/test_config_integration.py
- readthedocs/rtd_tests/tests/test_footer.py
Closes #4638 (last use of `project.documentation_type` here)
Fixes #5254
> Check for /index on pages' slug

- readthedocs/proxito/views/mixins.py
This makes it cleaner and users don't care about them.
> Remove GET args from the path passed via proxito header

- readthedocs/projects/tasks.py
Small fix to avoid adding the `.cache` directory if it does not exists. This is the case of project using `conda` to build their docs.
> Skip .cache directory for cached builds if it does not exist

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
We are creating one Setup Environment and another Build Environment.
Once each of them is created they define the `start_time` which is UTC
now. Then they use the `start_time` to calculate the `length` of the
build each time the build object is updated via the API.
Since the Build Environment calls again UTC now, we override the old
`start_time` and we loose track of the timing for the Setup
Environment (close repository, among others).
This commit saves the original `start_time` and passes it to the Build
Environment so it continues calculating the difference for the
`length` considering the Setup Environment times as well.
Related to #6793
> Do not reset the build start time when running build env

- readthedocs/proxito/views/serve.py
I found that when the version being accessed is the same as the default version of the project, we are checking twice for the existence of the same files.
> Check 404 page once when slug and default_version is the same

- readthedocs/projects/tasks.py
Instead of downloading the file into a temporary file (`storage.open`
and then `.read`) to save the file into another temporary file (our
loop reading by chunks) we just use the `storage.open` response as the
input of the `tarfile.open` function and extract it from there.
Related to #6793
> Use storage.open API correctly for tar files (build cached envs)

- readthedocs/proxito/views/serve.py
This is also why tests are failing randomly, a set doesn't keep the
order.
> Respect order when serving 404 (version -> default_version)

- readthedocs/builds/constants.py
- readthedocs/projects/tasks.py
Now, it will show "Uploading" before start performing the upload of build artifacts to the storage.
> NOTE: this PR is branched off of https://github.com/readthedocs/readthedocs.org/pull/6800. So, we will want to merge this one there or change base to master once the other one is merged.
This PR is missing the migration that will just add a new choice in the field.
> Show "Uploading" build state when uploading artifacts into storage

- requirements/pip.txt
We already have the 0.6.0 version installed from pypi,
so pip doesn't try to reinstall the package.
> Force to reinstall package

- dockerfiles/Dockerfile
- requirements/docker.txt
watchman is the replacement of pyinotify and it's the recommended way on Linux and MacOS.
https://docs.djangoproject.com/en/2.2/ref/django-admin/#runserver
Django will automatically detect that this is installed and use watchman instead of pyinotify, showing this log in the terminal:
```
django.utils.autoreload:597[20]: INFO Watching for file changes with WatchmanReloader
```
This change could help to reduce the CPU usage when running docker-compose locally.
This is a continuation of the work done in #6812.
> Use watchman when calling `runserver` in local development

- docs/guides/build-using-too-many-resources.rst
This PR,
- removes the mention about system site-packages because we don't really support them
- it's impossible to know what versions are installed in the images
- those packages do not generate any problem related to build resources
- if we want to go in that direction, we may want to install `torch`, `tensorflow`, etc. See #6742 
- add a new section about `sphinx-autoapi` that we have been recommending it on many different issues already, and it makes sense just to have it documented there as well
> Update guide about building consuming too much resources

- readthedocs/projects/tasks.py
This was used when being chained to pass the prior result,
we don't need it anymore.
> Fix silly issue with sync_callback

- readthedocs/core/tasks.py
We are using this internally and we haven't receiving emails in the
last month or so. I suppose this started happening after the Django
2.2 migration.
> Allow receiving `None` for `template_html` when sending emails

- readthedocs/doc_builder/python_environments.py
Saving these files in the tarfile will push/pull on every build and
it's useless because if we are saving the environment already, these
packages will be already installed there. So, there is no need to keep
them in the tarfile to not use them after all.
> Do not save pip cache when using CACHED_ENVIRONMENT

- readthedocs/projects/tasks.py
It could happen that the person that has imported the project does not
have permissions anymore to send Build Status to the social
service (e.g. GitHub).
In that case, we were just skipping the report to the service
completely.
On the other hand, if the project didn't have a RemoreRepository, we
were trying using all the mantainers' accounts to report the status.
This commit uses the same re-trying code, but also when the first
attempt using the account of the user that imported the repository,
failed.
Closes #6686
> Report build status in a smarter way

- CHANGELOG.rst
- setup.cfg
> Release 4.1.2

- readthedocs/doc_builder/environments.py
- readthedocs/projects/tasks.py
`RepositoryError` and `ProjectConfigurationError` are user errors that
we should not log as ERROR, but as WARNING instead.
Also, the `throws` list is removed here since all these exceptions
happen inside the Build Environment who already manage them in the
`__exit__` method and so, they are never seen by the task.
> Add more exceptions as WARNING log level

- readthedocs/settings/base.py
- readthedocs/settings/docker_compose.py
This should guard against the adserver responding slowly in production.
> Add an advertising API timeout

- readthedocs/core/resolver.py
We only check for superprojects if the project isn't a translation.
This reduces a query
Ref https://github.com/readthedocs/readthedocs.org/issues/6455
> Don't do extra query if the project is a translation

- readthedocs/builds/models.py
- readthedocs/core/resolver.py
- readthedocs/core/views/serve.py
- readthedocs/projects/models.py
- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views/serve.py
- readthedocs/rtd_tests/tests/test_doc_serving.py
- readthedocs/rtd_tests/tests/test_resolver.py
This isn't used in any part of the code or to change the behavior from the resolver (checked in .com too) and is using an extra query
Related to https://github.com/readthedocs/readthedocs.org/issues/6455
> Remove private argument from resolver

- readthedocs/projects/views/private.py
- readthedocs/templates/projects/projectrelationship_list.html
This together with:
- https://github.com/readthedocs/readthedocs.org/pull/6867
- https://github.com/readthedocs/readthedocs.org/pull/6865
- https://github.com/readthedocs/readthedocs.org/pull/6864
reduces a lot of queries and without changing the current UI.
This is a benchmark using the django debug toolbar:
Before: 138 queries with 7 subprojects, 17 queries per each additional subproject
With all the changes: 28 queries with 7 subprojects, 1 query per each additional subproject
Fixes https://github.com/readthedocs/readthedocs.org/issues/6455
> Don't do unnecessary queries when listing subprojects

- readthedocs/projects/tasks.py
This was breaking on keys that look like `'rst:directive:option'`.
Fixes https://sentry.io/organizations/read-the-docs/issues/1146171783/?project=148442&query=is%3Aunresolved
> Fix issue with sphinx domain types with `:` in them:

- readthedocs/builds/constants.py
- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
- readthedocs/settings/base.py
We had the same one on .org/.com and it was overwriting each other.
> Make the status name in CI configurable via setting

- readthedocs/projects/signals.py
- readthedocs/projects/tasks.py
- readthedocs/proxito/views/mixins.py
This lets us purge the CDN more easily.
This requires a version in the files_changed signal.
> Add CloudFlare Cache tags support

- readthedocs/doc_builder/constants.py
This assumes 1-builder per server.
It is still able to be overwritten by settings,
so to have this take effect we need to set:
```
DOCKER_LIMITS = None
```
> Allocate docker limits based on server size.

- readthedocs/storage/azure_storage.py
We have been experimenting some issues with Azure Blob storage. Our current timeout is the django-storages default (20 secs). We want to reduce it to ~2s, but without breaking the code and start returning 500. So, we log the error and return False.
> On Azure .exists blob timeout, log the exception and return False

- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views/serve.py
There is only one catch, the second argument can't start with `/`
(an exception is raised).
And it strips any starting slash from the first argument
(isn't a valid storage path).
Everything else works as expected, even `storage.join('foo', '//bar//foo/') == 'foo/bar/foo/'`.
And we are already using this function in other parts of the code.
> Safely join storage paths

- readthedocs/oauth/services/github.py
- readthedocs/oauth/services/gitlab.py
We have cases where the same repo has multiple projects on RTD,
so we can support multiple builds that are happening for the same commit.
This is probably not the best design so we'll want to think more about this,
but I think showing them all for now at least makes sense.
> Include the project slug in the PR context

- readthedocs/oauth/services/github.py
- readthedocs/rtd_tests/tests/test_oauth.py
This should help us debug issues a bit better.
> Improve logging around status setting on PR builds

- readthedocs/config/parser.py
- readthedocs/config/tests/test_yaml_loader.py
- readthedocs/config/utils.py
- readthedocs/doc_builder/backends/mkdocs.py
- readthedocs/rtd_tests/tests/test_doc_builder.py
Use a custom YAML loader to ignore all the unknown tags. This allow us to
support YAML files that have custom tags that are irrelevant for Read the Docs)
but are required for MkDocs to build the documentation properly.
Close: #6889
> Load YAML files safely

- readthedocs/settings/base.py
- readthedocs/settings/dev.py
In normal settings only log INFO and above,
but in dev we should log DEBUG to console.
This should only output RTD debug messages though,
because others are only logging INFO and above via the logger.
> Only output debug logging from RTD app

- docker-compose.override.yml
- readthedocs/storage/azure_storage.py
We have been having some issues with Azure's API and long timeouts. So, we are
going to try hitting the storage directly with a HEAD request hoping that it
will with better performance.
> Use requests.head to query storage.exists

- docs/custom_domains.rst
I think this note distracts more than it helps. There are 7 projects on .org with a `_` in the slug and 4 on .com. Most of these are *our* projects as well. It isn't possible to create a new project with an underscore.
> Remove note about underscore in domain

- readthedocs/settings/docker_compose.py
Now we are not proxying the Storage request via NGINX anymore, all the internal
communication between containers should be done using the containers
host (e.g. `storage:10000`).
This is required for example by the Embed API that hits the storage from the web
container, which does not work anymore hitting `community.dev.readthedocs.io`
since we removed the NGINX proxy rule.
> Do not override the domain of Azure Storage

- dockerfiles/Dockerfile
- requirements/docker.txt
This is only useful if you are running runserver on the host
> If you’re using Linux or MacOS and install both pywatchman and the
> Watchman service, kernel signals will be used to autoreload the server
> Revert usage of watchman

- docs/guides/searching-with-readthedocs.rst
Signed-off-by: Zac Dover <zac.dover@gmail.com>
> Made syntactical improvments and fixed some vocabulary issues.

- docker-compose.override.yml
- readthedocs/storage/azure_storage.py
This reverts commit 9c062ecea31196e3715835827c389fa7b22495f7.
It seems that Azure has fixed their problem already and the API is working
better now. Besides, using requests.head here is hitting
buildmedia.readthedocs.org and that's not good.
> Revert "Use requests.head to query storage.exists"

- readthedocs/api/v3/serializers.py
- readthedocs/api/v3/tests/test_projects.py
Given the name of the project, calculate its potential slug and check there is
no project matching that slug already at serializer validation.
Closes #6947
> Return 400 when importing an already existing project

- readthedocs/api/v2/serializers.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_api.py
Use this value to know max concurrent builds per-project. There was a bug that
we weren't sending this value in the serializer and it was always None.
Besides, it adds some useful logging to know what's happening.
> Return max_concurrent_builds in ProjectAdminSerializer

- readthedocs/proxito/tests/handler_404_urls.py
- readthedocs/proxito/tests/test_full.py
- readthedocs/proxito/views/mixins.py
- readthedocs/proxito/views/serve.py
> Include query params in 404 redirects

- dockerfiles/nginx/proxito.conf
- readthedocs/proxito/middleware.py
- readthedocs/proxito/tests/base.py
- readthedocs/proxito/tests/test_middleware.py
- readthedocs/proxito/tests/test_redirects.py
- readthedocs/proxito/views/mixins.py
- readthedocs/proxito/views/serve.py
- Do HTTP -> HTTPS redirects if `domain.https`
- Redirect public domain to canonical CNAME if `domain.canonical`
- ~~Redirect CNAME -> public domain (or another canonical domain) if the requested custom domain is not canonical~~
- Set additional data on the `X-RTD-Redirect` header whether the redirect is to canonicalize, a system redirect, or a user redirect
If this is merged, #6882 can be closed as it won't be needed. This is an alternative that uses the same code from the resolver to perform the redirect to the appropriate domain.
Fixes: https://github.com/readthedocs/readthedocs.org/issues/4641
I don't think the HTTP -> HTTPS redirect is a concern. Users who set `domain.https` will be happy with the change and users who didn't won't see a change.
~~The canonicalizing domain change is a …
> Canonicalize domains and redirect in proxito

- readthedocs/core/utils/__init__.py
- readthedocs/core/views/hooks.py
Logging these 2 tasks _before executing them_ allows us to know immediately which project could be causing a spike on the celery queues. We can parse the logs and count how many tasks of each per project are waiting to be processed as well.
> Log build/sync tasks when triggered

- readthedocs/projects/tasks.py
When SIGTERM is received by the process that is building a build, we only log a
message instead of passing it to the child processes (`pip` running inside the
Docker container, for example).
Otherwise, the `pip` process also receives the SIGTERM and it kills itself,
producing a `exit_status != 0`, registering this as a BuildCommand and making
the whole build to fail. After that, celery "stops gracefully" with a failed build.
This is useful combined with supervisor to make our builders to stop gracefully
in this scenario:
1. supervisorctl stop build
2. celery receives the SIGTERM and logs the warning message
3. supervisor waits for `stopwaitsecs` before sending SIGKILL
> Stop builders gracefully on SIGTERM

- docs/custom_domains.rst
I tested this process end-to-end and was able to add an ALIAS record on namecheap's DNS, Cloudflare issued the SSL cert, and RTD served it without issue.
> Docs on supporting root domains

- readthedocs/projects/views/private.py
- readthedocs/templates/projects/project_dashboard_base.html
A project search for the .com use-case only returns projects already in the dashboard,
so it makes little sense there.
This changes it so that the search bar actually searches files first,
which is almost certainly what people want most of the time.
We could also consider changing the default search on the frontpage of the .org to search files,
but I'm not quite sure that is as important.
> Change the dashboard search to default to searching files

- readthedocs/vcs_support/backends/git.py
> Try to fix annotated tags

- docs/custom_domains.rst
This change moves the CAA record note out of the Cloudflare note. Users of any DNS provider can configure CAA records which prevent us/Cloudflare from issuing SSL certificates.
I also noted that if somebody has a CAA record for the root domain that it also applies to the subdomain.
> CAA records are not only for users of Cloudflare DNS

- readthedocs/builds/models.py
- readthedocs/oauth/services/github.py
- readthedocs/projects/constants.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_oauth.py
This was causing an issue with consumers of the GITHUB_REGEX.
We were calling `rstrip` in some client code,
but others were getting the `/`.
This fixes the actual regexs to properly not return the trailing /.
> Fix the trailing slash in our repo regexs

- readthedocs/api/v2/views/integrations.py
I found this code very hard to follow when trying to understand if we were triggering a sync version twice. I tried to refactor it trying to return immediately we know that we have all the data required to make a decision about "what type of GitHub event we received" trying to minimize the context in needed in the head.
The only special case is the PUSH event with `created`/`deleted` attribute that it's sent together with a CREATE/DELETE event.
> It's easier to review this code in a side-by-side diff.
> Refactor how we handle GitHub webhook events

- readthedocs/doc_builder/constants.py
- readthedocs/projects/models.py
* Add another level of automatic docker limit configuration for AWS. This is a
bit of a hack, as the memory limits are different on AWS, but the time should
still be 3600s by default.
* Fix usage of settings.DOCKER_LIMIT that was missed
> More fixes for automatic Docker limits

- docs/builds.rst
This is the smallest amount of work to mention this.
However, I think that this whole page needs some work. I'll see if I can start doing that in another PR, but I think it worth to mention this somewhere in the meanwhile.
> Mention concurrent builds limitation in "Build Process"

- readthedocs/projects/tasks.py
This should make it more obvious what our builders are doing
> Log sync_repository_task when we run it

- readthedocs/projects/models.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_backend.py
- readthedocs/vcs_support/backends/git.py
- readthedocs/vcs_support/base.py
When a webhook is received we synchronize the branches/tags to create new
versions under Read the Docs. For this process we do a full clone of the
repository and iterate over the branches/tags.
As this process of cloning the repository just for updating versions could be
expensive, this commit adds the ability to use `ls-remote` on Git VCS just to
query the repository for its branches/tags without performing a full clone.
Closes #6508
> Optimization on `sync_versions` to use ls-remote on Git VCS

- readthedocs/projects/tasks.py
This will let us do a couple things:
* Make the embed API work in PR previews
* Allow us to start indexing search for PRs once we want that feature-set
> Start storing JSON data for PR builds

- docs/guides/autobuild-docs-for-pull-requests.rst
In my case webhook worked fine, but RTD could neither update the webhook, nor could provide PR status update.  GitHub service was told to be connected, but there were no OAuth App listed for RTD.  Disconnect/Connect resolved the issue.
> Add a note if build status is not being reported

- readthedocs/settings/base.py
We use 0 here because some things still put a task in the queue with no priority
I don't fully understand why, but this seems to solve it.
> Add Priority 0 to Celery

- readthedocs/core/unresolver.py
- readthedocs/rtd_tests/tests/test_unresolver.py
- readthedocs/settings/docker_compose.py
Turn a URL into the component parts that our views would use to process them.
Look at the tests for an example.
> Add an unresolver similar to our resolver

- readthedocs/builds/tasks.py
This will return None at the end, I guess that's ok? I think if it returns None the default queue is used, right?
> Task Router: check for None

- readthedocs/builds/admin.py
Also display more useful data in the detail
> Clean up build admin to make list display match search

- readthedocs/doc_builder/constants.py
- readthedocs/settings/base.py
This setting was moved to a constant, which was harder to override and
replicated a lot of the same logic we had for settings. We hit a number
of issues around the DOCKER_LIMITS setting existing, and these constants
not being used, etc.
This hard codes a memory limit, which would be used for dev
environments outside Docker, and perhaps tests. Limits are 1g memory
and 600s build time -- up from 200m memory limit that is too small.
Production guessing of memory/time will be in ops settings now.
Refs #6983
> Move docker limits back to setting

- readthedocs/core/utils/__init__.py
- readthedocs/projects/tasks.py
- readthedocs/rtd_tests/tests/test_core_utils.py
- readthedocs/rtd_tests/tests/test_project.py
This is not correctly getting a default time limit since we moved the
docker limit configuration to a dynamic one.
> Use a high time limit for celery build task

- readthedocs/rtd_tests/tests/test_views.py
- readthedocs/templates/homepage.html
Currently the `if` block actually evaluates the queryset,
causing it never to actually cache the query that we want it to cache.
> Fix the caching of featured projects

- readthedocs/builds/admin.py
This is much more useful than the name, which isn't unique.
> Show project slug in Version admin
