readthedocs/readthedocs.org

readthedocs/search/documents.py
readthedocs/search/tests/test_faceted_search.py
readthedocs/search/tests/test_xss.py

This was only being used for testing.

Search Document: remove unused class methods

---

readthedocs/search/api.py
readthedocs/search/faceted_search.py
readthedocs/search/views.py

Currently, we can pass filters as keywords (if they match a valid
filter) or in the `filters` keyword.
The original model FacetedSearch allows to pass filter only using the
filfilters keyword.
All places were refactored so we always pass the filters in the filters
arg.

RTDFacetedSearch: pass filters in one way only

---

readthedocs/projects/tasks.py

This was removed in https://github.com/readthedocs/readthedocs.org/pull/7044,
and it's needed to properly link to the PR builds and update their status.

Fix PR builds being marked built

---

readthedocs/search/api.py
readthedocs/search/tests/test_faceted_search.py
readthedocs/search/tests/test_xss.py

Looks like user and filter_by_user are still
needed in .com for filtering results in the dashboard (#6341).
But it can be removed from tests.

Search: Little refactor

---

readthedocs/api/v3/tests/test_versions.py
readthedocs/builds/querysets.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_footer.py

Should fix https://github.com/readthedocs/readthedocs.org/issues/6971
This also assumes the latest version has `built=True`, which I'm not sure is the case in production.

Hide unbuilt versions in footer flyout

---

docs/choosing-a-site.rst
docs/index.rst
readthedocs/api/v2/utils.py

This is an initial attempt,
but I think it’s important to document this.
We get a lot of questions so it seems obvious we need to explain it better.

Add a page about choosing between .com/.org

---

docs/custom_domains.rst

Document HSTS support

---

readthedocs/proxito/tests/base.py
readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_core_utils.py
readthedocs/rtd_tests/tests/test_privacy_urls.py
requirements/testing.txt

Closes https://github.com/readthedocs/readthedocs.org/issues/6886
Latest pyup dependency update - https://github.com/readthedocs/readthedocs.org/pull/7012
There were a couple of tests failing locally that looked unrelated to the django-dynamic-fixure upgrade:
- ~~test_privacy_urls.py~~ (fixed)
- ~~test_core_utils.py~~ (fixed)

Fix tests ahead of django-dynamic-fixture update

---

readthedocs/api/v2/views/footer_views.py

Mkdocs is also a htmldir doctype.
Fix https://github.com/readthedocs/readthedocs.org/issues/7087

Footer: Check for mkdocs doctype too

---

readthedocs/api/v2/views/footer_views.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_footer.py
readthedocs/settings/base.py
readthedocs/templates/projects/project_traffic_analytics.html

This is so we can disable it if needed based on DB load.

Add a setting for storing pageviews

---

docs/guides/embedding-content.rst

Mention that can be used a Sphinx reference to avoid changes in title breaking
the EmbedAPI content referenced.

Add a tip in EmbedAPI to use Sphinx reference in section

---

docs/api/v2.rst

I added the documentation under https://docs.readthedocs.io/en/stable/api/v2.html. However, we have a note at the top saying that it's deprecated and you should use APIv3, but APIv3 does not have this endpoint yet.
It's probably fine for now to have it here, but we will need to migrate it to APIv3 at some point.
https://docs--7095.org.readthedocs.build/en/7095/api/v2.html

Document Embed APIv2 endpoint

---

readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_builds.py

We should let tools know that we don't want ANSI escaped colors in
the output.
Closes #6883

Pass the NO_COLOR env var to builder

---

readthedocs/search/parse_json.py
readthedocs/search/tests/data/sphinx/in/page.html

Fixes https://github.com/readthedocs/readthedocs.org/issues/7119

Search: don't index permalinks

---

readthedocs/projects/tasks.py

This signal is used to clear the CDN,
so we want it to happen as soon a possible.

Move changes_files to before search indexing

---

readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_middleware.py

This also fixes a flaky test.
We hit this before proxito too
https://github.com/readthedocs/readthedocs.org/blob/8ebded69160f495c56e2966da90bad3be2dc9f5f/readthedocs/core/middleware.py#L132-L136

Proxito middleware: reset to original urlconf after request

---

readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_middleware.py

Turns out, it was the cache.
If your computer is fast enough,
the same project slug is updated in the same second.
The cache is done at the django level, so not much we can do about it from outside.
With milliseconds hopefully is hard to hit.
Also, set_urlconf to None and to the current urlconf is already done automatically in django 2.2
https://github.com/django/django/blob/stable/2.2.x/django/core/handlers/base.py#L94-L95
https://github.com/django/django/blob/stable/2.2.x/django/core/handlers/base.py#L166

Fix flaky test

---

readthedocs/search/faceted_search.py

We were using the default tag for results from projects (em),
but we use the spam tag to highlight results.
This moves the common highlight options to the parent class.

Search: highlight results from projects

---

readthedocs/projects/tasks.py

This should make our web queue not backup as much.
We should also set `web-extra` to not process this queue,
so we can be sure we're processing tasks off `web` more timely.

Reindex search on the `reindex` queue

---

readthedocs/analytics/apps.py
readthedocs/analytics/signals.py
readthedocs/analytics/tasks.py
readthedocs/analytics/tests.py
readthedocs/api/v2/views/footer_views.py
readthedocs/rtd_tests/tests/test_footer.py

Sending a task per pageview quickly overwhelmed our tasks queues. Instead, this uses a signal we are already sending. Currently, this will result in no more queries than normal unless the project has the Feature flag `STORE_PAGEVIEWS`. However, if the project has that set, there will be 2 additional queries.

Store pageviews via signals, not tasks

---

readthedocs/proxito/middleware.py

This isn't actually useful,
and happens on any 404 page for a non-existing domain.

Reduce logging in proxito middleware so it isn't in Sentry

---

readthedocs/settings/base.py

4Gb servers:
- total memory: 3417
- memory limit: 2700
- time limit (using memory limit): 700
- time limit (using total memory): 900 (15 minutes)
8Gb servers:
- total memory: 7935
- memory limit: 7200
- time limit (using memory limit): 1800
- time limit (using total memory): 2000 (33 minutes)
These numbers are more similar to what we communicate in
https://docs.readthedocs.io/en/stable/builds.html. We are giving an increase of
3 extra minutes in Read the Docs for Business instead of 4 minutes less in Read
the Docs Community.
```
>>> round(3417 - 750, -2)
2700
>>> round(2700 * 0.25, -2)
700.0
>>> round(3417 * 0.25, -2)
900.0
>>> round(7935 - 750, -2)
7200
>>> round(7200 * 0.25, -2)
1800.0
>>> round(7935 * 0.25, -2)
2000.0
```

Use total_memory to calculate "time" Docker limit

---

readthedocs/search/parsers.py

This is a step further for indexing html files from any
static site generator.
Changes:
- Don't remove anchors in `_parse_content`, we already remove those in a more general way in `_parse_section_title`, and I came around a page that actually had `¶` in its content.
- Make `_parse_sections` work with any `h` headers (additionally to div sections) (not all themes wrap its section's title in a div).
- Use a more general way to remove irrelevant nodes (like navigation only content)
Note: this doesn't change the results for our current parsers for sphinx or mkdocs (well, maybe we will be indexing more content if we were missing some sections in sphinx).

Search: more general parser for html

---

readthedocs/search/parsers.py

This is on top of https://github.com/readthedocs/readthedocs.org/pull/7204/
If we have a structure like
- parent
- content
- content
- h1
- content
- content
- h2
- content
And we start indexing from `parent`,
we will index all children in the first step,
and then index each header later. This is, duplicating content.
This is solved by checking for a section till 1 level.
In this example, the first parsing will stop when finding the first h1,
not duplicating content. Later it will index the next nodes as usual.
Also, we can increase the depth check when parsing all sections, that way we don't rely anymore on the div used by sphinx to enclose a section, and avoid indexing duplicated content if other themes don't follow the same structure.
A real example of this is …

 Search: recursively parse sections

---

readthedocs/projects/models.py
readthedocs/search/parsers.py
readthedocs/search/tests/data/mkdocs/in/gitbook/index.html
readthedocs/search/tests/data/mkdocs/in/material/index.html
readthedocs/search/tests/data/mkdocs/in/mkdocs-1.1/404.html
readthedocs/search/tests/data/mkdocs/in/mkdocs-1.1/configuration.html
readthedocs/search/tests/data/mkdocs/in/mkdocs-1.1/index.html
readthedocs/search/tests/data/mkdocs/in/mkdocs-1.1/no-main-header.html
readthedocs/search/tests/data/mkdocs/in/mkdocs-1.1/no-title.html
readthedocs/search/tests/data/mkdocs/in/readthedocs-1.1/404.html
readthedocs/search/tests/data/mkdocs/in/readthedocs-1.1/index.html
readthedocs/search/tests/data/mkdocs/in/readthedocs-1.1/versions.html
readthedocs/search/tests/data/mkdocs/in/windmill/index.html
readthedocs/search/tests/data/mkdocs/out/gitbook.json
readthedocs/search/tests/data/mkdocs/out/material.json
readthedocs/search/tests/data/mkdocs/out/mkdocs-1.1.json
readthedocs/search/tests/data/mkdocs/out/readthedocs-1.1.json
readthedocs/search/tests/data/mkdocs/out/windmill.json
readthedocs/search/tests/test_parsers.py

This is on top of https://github.com/readthedocs/readthedocs.org/pull/7207
It's under a feature flag currently,
since I would like to test this with sphinx later.
Tested with all themes available in
https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes
I did a search in all of them to check that sections are correctly indexed,
and that irrelevant content isn't indexed.
I wasn't able to build these,
but I checked the html, and it's very similar to the default mkdocs theme,
so it should work.
- https://github.com/michaeltlombardi/mkdocs-psinder
- https://github.com/byrnereese/mkdocs-bootstrap4
- https://github.com/daizutabi/mkdocs-ivory
These themes don't expose search,
but the content is indexed, and we show results in the dashboard.
- https://gitlab.com/lramage/mkdocs-bootstrap386
- …

Search: index from html files for mkdocs projects

---

readthedocs/builds/tasks.py
readthedocs/builds/tests/test_celery_task_router.py

This seems to cause a lot more builds in build:large,
which costs more and often has lower concurrency.
This should hopefully spread our load of long builds,
causing less latency on these tasks.

Remove task routing for long tasks to build:large

---

readthedocs/search/faceted_search.py

A small change, big improvements in results

Search: tweak fuzziness

---

docs/custom_domains.rst

- Note that CAA records are usually at the root
- They don't *have* to be at the root but you can't have a CNAME and CAA record for the same subdomain

Update CAA docs

---

readthedocs/core/permissions.py
readthedocs/oauth/services/github.py
readthedocs/organizations/models.py

Changes on this PR:
- user is part of an organization if there is at least one `Project` imported under that `Organization` that it's linked to a `RemoteRepository` the user owns and the organization has `SSOIntegration` enabled
- `Organization.members` and `Organization.users` methods were moved to `AdminPermission.members`
> Note that `.members` and `.users` return exactly the same users
- delete `RemoteRepository` instances when syncing GitHub (only those instances that are not tied to a `Project`) (Fixes, partially, #2412)

Modifications required to implement GitHub SSO in commercial

---

docs/guides/autobuild-docs-for-pull-requests.rst

In https://github.com/readthedocs/readthedocs.org/issues/7240 there was some confusion about what the build limitations were for PR builds. @humitos mentioned that they're the same as for regular builds, so this adds a sentence to cross-link that page.

cross-linking build limitations for pr builds

---

readthedocs/api/v2/views/integrations.py

This should help us debug what is causing this task to fire so much.

Add additional logging for sync_repository task

---

.readthedocs.yml

We are marking as deprecated v2 as well.

Tweak priority a little more

---

readthedocs/projects/migrations/0057_add_page_rank.py
readthedocs/projects/models.py
readthedocs/search/tests/test_api.py

This migration is taking too long to run, maybe related to the default
value, since django does that manually.

Don't default on the migration

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_domains.py

closes https://github.com/readthedocs/readthedocs.org/issues/7216

Don't allow Domain name matching production domain to be created

---

docs/config-file/v2.rst
readthedocs/doc_builder/backends/sphinx.py
readthedocs/rtd_tests/tests/test_config_integration.py

The option was added in sphinx 1.8,
and we only add it if the user sets `fail_on_warning: true`.
https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going
Closes https://github.com/readthedocs/readthedocs.org/issues/7240

Sphinx: add --keep-going when fail_on_warning is true

---

readthedocs/projects/views/public.py
readthedocs/templates/core/project_bar.html
readthedocs/templates/core/project_detail_right.html
readthedocs/templates/core/project_details.html
readthedocs/templates/projects/onboard_detail.html
readthedocs/templates/projects/project_version_list.html

This has a lot of effect in corporate,
where the check for is_admin is more complex.

Templates: optimize permissions check

---

readthedocs/projects/urls/public.py

- Assumption: There should not be a project named "tags"
- Longer term this opens up a discussion about banned project names
Currently https://readthedocs.org/projects/tags/search/ gives a 404. It should return a list of projects for this tag. It does this because the [URL route here](https://github.com/readthedocs/readthedocs.org/blob/8726eec2d8b5e3d2ecc157d07ee203f95429cfdb/readthedocs/projects/urls/public.py#L62) is looked at first.

Fix a case where "tags" is interpreted as a project slug

---

readthedocs/projects/views/mixins.py
readthedocs/projects/views/public.py
readthedocs/templates/core/project_bar.html
readthedocs/templates/core/project_details.html

The main one is to first check if there are subprojects
before calling the resolver (4 queries less!)

Dashboard: little optimization

---

readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

We use the _build/ directory for all builders.
Some users may not have that directory excluded,
leading to some extra copy operations.
Fixes https://github.com/readthedocs/readthedocs.org/issues/7200

Sphinx: always exclude the build directory

---

readthedocs/api/v3/views.py

This is required to be able to use the APIv3 from the dashboard in the new templates we are creating.
@agjohnson is this enough for the work you need at the moment?
> I'm not documenting this yet so we start using it internally, but after that we should change the documentation a little.

Enable SessionAuthentication on APIv3 endpoints

---

docs/guides/feature-flags.rst
readthedocs/doc_builder/base.py
readthedocs/projects/models.py

When Read the Docs detects that your project doesn't have an ``index.md`` or
``README.rst``, it auto-generates one for you with instructions about how to
proceed. This behavior may be a problem for some users and they will want to
disable it.
This is happening for example when building with MkDocs and setting
```
theme:
static_templates:
- index.html
```
Since there is no `index.md`, Read the Docs will create one from our template
and it will override the `index.html` the user wants to show.
Related to #2483

Feature to disable auto-generated index.md/README.rst files

---

readthedocs/proxito/views/serve.py

The TTL on the cache_page call of 12 hours exceeds the expiration of the
S3 presign URL expiration TTL. I believe the default here is the
`AWS_QUERYSTRING_EXPIRE` setting, default 3600s:
https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#settings
Going beyond expiration on the presign URL results in a broken response
to the user, so not something we can safely keep cached.
12 hours is likely far too agressive here anyways. We could likely drop
this to a sub-5m TTL. If this is cached because it's an expensive view,
an hour seems like a good compromise for now.

Reduce robots.txt cache TTL

---

readthedocs/doc_builder/python_environments.py

Argument list for "python -m virtualenv" without empty strings

---

.readthedocs.yml

We don’t want users finding these generally.

Lower rank for custom install docs.

---

docs/server-side-search.rst

Had a user confused about this, thinking that searching on any subproject will include results from all other subprojects

Docs: make it more clear search on subprojects

---

readthedocs/api/v2/views/footer_views.py
readthedocs/builds/models.py
readthedocs/rtd_tests/tests/test_footer.py

Fixes https://github.com/readthedocs/readthedocs.org/issues/7218

Footer: don't show the version warning for external version

---

dockerfiles/nginx/proxito.conf
readthedocs/core/middleware.py
readthedocs/settings/base.py
readthedocs/settings/proxito/base.py

This sets a [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) with the value of `strict-origin-when-cross-origin` for the RTD dashboard. Proxito (which serves documentation sites) will use `no-referrer-when-downgrade` so that API calls from docs sites to readthedocs.org will report the referrer.
Setting the setting `SECURE_REFERRER_POLICY=None` will turn off the middleware.
I didn't use the existing [django-referrer-policy](https://github.com/ubernostrum/django-referrer-policy) module because this new middleware is setup so that it can just be removed when we upgrade to Django 3. Referrer policy is a built-in feature of Django's SecurityMiddleware (which we use) in Django 3. The django-referrer-policy uses a different setting name than what …

Add a middleware for referrer policy

---

docs/commercial/single-sign-on.rst

- Mention that we support GitLab and Bitbucket as well
- Remove "SSO with your company email address" and mention Google SSO instead
- Owners can mark a Team to auto-join
- Add "GSuite" word so it appears in results
- Add section to revoke user's access to project
- Revoke access to all the projects / Disable GSuite account

Update Single Sign On documentation with latest features/changes

---

readthedocs/projects/views/private.py

Django's template system is not great at dealing with raw iterables. I had to
use a list here in the new interface.

Convert zip to list for templates

---

readthedocs/core/views/hooks.py
readthedocs/projects/models.py

I'm not set up to test this immediately, so can't verify if this works
or if it solves the problem we're seeing.

Add feature flag to just skip the sync version task entirely

---

readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_oauth.py

Ref https://github.com/readthedocs/readthedocs.org/issues/7370

External providers: better logging for GitLab

---

readthedocs/builds/tasks.py

Just a little refactor (both tasks pass the version_pk as the first
parameter), and docstring updated.
Don't think this is related to https://github.com/readthedocs/readthedocs.org/issues/7360... but maybe? I couldn't find anything else related to that problem :/

Task router: small changes

---

readthedocs/api/v2/utils.py

According to django's docs, using count/exists will
do one query and another one when fetching the results.
So is better to just fetch the results if you are going to
fetch the results anyway.
And here doing two queries means sending a loooooong query twice.

Sync versions: little optimization when deleting versions

---

docs/faq.rst

As pointed out in #7345, using the `pip` install method will aggressively update packages, even if they were pinned. In some cases, adding the package to `sys.path` is not enough (e.g. when using `setuptools_scm`), so installing is still necessary. This can be done by putting `-e <path>` into the environment (`conda`) / requirements file (at least for `conda` the editable install seems to be necessary).
As suggested in that issue, this adds a faq entry to document that trick.
- closes #7345

document installing into a environment with pinned dependencies

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py

This will help us find bugs before is installed by default in all builds (october) 
Related to https://github.com/readthedocs/readthedocs.org/issues/7362

Pip: test new resolver

---

docs/guides/deprecating-content.rst
docs/guides/platform.rst

Preview at https://docs--7333.org.readthedocs.build/en/7333/guides/deprecating-content.html

Guide: deprecating content

---

readthedocs/api/v2/adapters.py
readthedocs/api/v2/client.py

POST isn't idempotent and can trigger some expensive operations
several times (like sync_versions).

API client: don't retry on POST

---

readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/responses/projects-builds-detail.json
readthedocs/api/v3/tests/responses/projects-detail.json
readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json

closes https://github.com/readthedocs/readthedocs.org/issues/7361

build_url added to all API v3 build endpoints

---

docs/guides/adding-custom-css.rst

Fix typo in docs/guides/adding-custom-css.rst

---

requirements/pip.txt

Today was a security release of Django. It does not really affect us because
it's Python 3.7+ and we are in 3.6, but good to upgrade anyways.
https://www.djangoproject.com/weblog/2020/sep/01/security-releases/

Upgrade Django to 2.2.16

---

readthedocs/builds/tasks.py

Instead trunctaing the last part of the command, we truncate the beggining of
it. This allows to understand what's happening if the command fails (e.g. LaTeX
step, https://readthedocs.org/projects/platformio/builds/11763095/) with more context to be able to solve it.

Truncate the beggining of the commands' output

---

readthedocs/organizations/forms.py
readthedocs/organizations/tests/test_forms.py
readthedocs/organizations/tests/test_models.py

Copy/paste mostly. Changed some docstrings and var names to make the linter happy. And also added a SettingsOverrideObject

Organizations: move forms

---

readthedocs/oauth/services/base.py

Currently this will delete all repositories and left
only the ones from the current provider being sync.

Remote repository: filter by account before deleting

---

readthedocs/api/v2/client.py

Reverts https://github.com/readthedocs/readthedocs.org/pull/7383/

Revert "Don't retry on POST"

---

readthedocs/core/utils/__init__.py

Instead of checking for "any other build for this verion in TRIGGRERED state" we
also add the filter for builds triggered in the previous 5 minutes. This allows
us to avoid false positives for builds that failed for any reason and didn't
update their state, ending up on blocked builds for that version (all the builds
were marked as DUPLICATED in that case).
Adding this date condition, we reduce the risk of hitting this problem to 5
minutes only.
If the build takes more than 5 minutes to complete, users could end up with
builds building exacly the same version (and commit); but this is how it works
right now without this DEDUPLICATE_BUILDS feature. So, I think it's still an
improvement to avoid builds triggered in flood.

Mark a build as DUPLICATED (same version) only it's close in time

---

readthedocs/oauth/services/base.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/rtd_tests/tests/test_oauth_sync.py
requirements/testing.txt

~~We were using the naked response from GitHub to exclude `RemoteOrganization`~~
~~objects and delete the ones where the user don't have permissions anymore.~~
~~However, we need the organization details instead that comes with the `name`~~
~~attribute which is the one that we use to create the `RemoteOrganization` object.~~
I refactored this code to always return a list of `RemoteRepository` and `RemoteOrganization` from the `sync_repositories` and `sync_organizations` methods on each service to avoid using the wrong field name, as we were doing.
Closes #7381

Grab the correct name of RemoteOrganization to use in the query

---

docs/config-file/v2.rst

In YAML, scalars cannot start with a `*` as this character is an indicator character ( https://yaml.org/spec/1.2/spec.html#id2772075 , rule [14]) used for denoting aliases ( https://yaml.org/spec/1.2/spec.html#id2786196 ). Therefore this key needs to be quoted.

correct invalid YAML

---

readthedocs/templates/socialaccount/connections.html

This will inform about,
- account without password
- account without verified email address
We override the `connections.html` file from `django-allauth` and we lost this
chunk of template code in the middle.
Python code:
https://github.com/pennersr/django-allauth/blob/c19a212c6ee786af1bb8bc1b07eb2aa8e2bf531b/allauth/socialaccount/adapter.py#L123-L139
Template code:
https://github.com/pennersr/django-allauth/blob/c19a212c6ee786af1bb8bc1b07eb2aa8e2bf531b/allauth/templates/socialaccount/connections.html#L18-L20

Show "Connected Services" form errors to the user

---

requirements/pip.txt

We are using this in https://github.com/readthedocs/readthedocs.org/blob/23fb8046828b8d4855c90a2d8ecc0eb720ccb578/readthedocs/search/tasks.py#L3
but we don't have this dependency explicitly in our requirements.

Add dependency explicitly (dateutil)

---

readthedocs/doc_builder/environments.py

The other PR was when archiving the builds, not the ones we show to the user
Ref https://github.com/readthedocs/readthedocs.org/pull/7449

Truncate output at the start for large commands

---

readthedocs/oauth/services/gitlab.py
readthedocs/rtd_tests/tests/test_oauth.py

When syncing `RemoteRepository` in GitLab we were only checking if the user was
the owner of the project, but we weren't checking for permissions given by
belonging to a group.
This commit makes usage of 40 (maintainer) and 50 (owner) permission levels to
check these permissions granted by being part of a group.
Closes #7475

Use `permissions` (project and group) for `RemoteRepository.admin` on GitLab

---

readthedocs/doc_builder/python_environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

Sphinx declares that dependency in the latest version https://github.com/sphinx-doc/sphinx/blob/bec30596a8f7487cad23df532bf02d1b29024dbc/setup.py#L25
and since 1.0 https://github.com/sphinx-doc/sphinx/blob/690fc257e9a539a4c193ba8efe5587f7c102785c/setup.py#L47
ref https://github.com/readthedocs/readthedocs.org/issues/7480
fixes https://github.com/readthedocs/readthedocs.org/issues/7492

Don't install pygments

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/doc_builder/base.py

There are a lot of places where we are using `checkout_path` to refer to the cwd of the project, declare this at the base class instead of duplicating it everywhere.

Builders: little refactor

---

readthedocs/settings/base.py

Enable image 8.0 with Python 3.9 support and Ubuntu 20.04 LTS.
Labelled images now are,
- stable -> 6.0
- latest -> 7.0
- testing -> 8.0
Defaults Python versions are kept the same (2.7 and 3.7).
Requires: https://github.com/readthedocs/readthedocs-docker-images/pull/137

New docker image for builders: 8.0

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_domains.py

- Allow to save the same domain with canonical=true
- Don't save domains like `domain.com/foo`

Domain: fix form

---

readthedocs/projects/forms.py
readthedocs/projects/validators.py
readthedocs/rtd_tests/tests/test_domains.py

This form was even accepting spaces...
Based on the regex from https://api.cloudflare.com/
(`pattern: ^([a-zA-Z0-9][\-a-zA-Z0-9]*\.)+[\-a-zA-Z0-9]{2,20}$`)
Closes https://github.com/readthedocs/readthedocs.org/issues/1707

Domains: more robust form

---

docs/intro/getting-started-with-mkdocs.rst
docs/intro/getting-started-with-sphinx.rst

This should stop people from overwriting existings docs,
based on user feedback.

Add a reference to the Import guide at the start of Getting started

---

docs/guides/specifying-dependencies.rst

When asked how to pin a dependency I link to this page, and often I get a question on how the requirements file looks like.
ref https://github.com/readthedocs/readthedocs.org/issues/7556#issuecomment-708241335

Docs: show example of a requirements.txt file

---

.travis.yml

We need this before updating to 7.x. No changes were required, everything just works :)
We need to merge https://github.com/readthedocs/common/pull/72 too.
ref https://github.com/readthedocs/readthedocs.org/issues/5620
We need to update to this version in the admin panel of ES. We don't need to reindex for this operation

Update ES to 6.8.12

---

docs/api/v2.rst

APIv2 is still available, we still use it for application operations,
and APIv3 is not quite ready as a replacement for a lot of applications.
I think the docs should reflect that, even if we want new users using
APIv3.

Undeprecate APIv2 in docs

---

readthedocs/api/v2/views/model_views.py

This is used by new theme to perform search as you type directly against
the api response. API v2 is used here as we don't have this modeled at
all in APIv3 yet.

Add remoterepo query param

---

readthedocs/notifications/notification.py
readthedocs/rtd_tests/tests/test_notifications.py

This fixes an issue where we were sending emails with `Contact us at {{
SUPPORT_EMAIL }}` but the support email variable was not set and the result was
an empty email.
Using our own `readthedocs_processor` here we are passing all the same variables
to the notification that to all the Django templates, avoiding this kind of confusions.

Add our `readthedocs_processor` data to our notifications

---

readthedocs/doc_builder/python_environments.py

The default of sphinx theme `<0.5.0` is not compatible with Sphinx 2+,
it results in a large number of display issues if you don't set the
html4 writer as the default.

Default to sphinx theme 0.5.0 when defaulting to latest sphinx

---

readthedocs/search/faceted_search.py
readthedocs/search/tests/test_api.py

This makes use of the wildcard query when a single term is given, users can still have exact results by using the `"word"` syntax. This is under a feature flag.
Examples, having indexed the following "foo", "foo.bar", "bar.foo" "network", "two".
- Searching for `foo` will return `foo`, `foo.bar` and `bar.foo` (before this it would return only `foo`)
- Searching for `two` will return `two` and `network` (here exact matches have more priority) (before this it would return only `two`)
- Searching for `"two"` will return `two` (same as before)
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-wildcard-query.html
Based on https://github.com/readthedocs/readthedocs.org/pull/7568

Search: better results for single terms

---

readthedocs/search/documents.py
readthedocs/search/faceted_search.py

We were iterating over operators each time and repeating the same fields to get the highlight. I did this mainly to introduce a new improvement for partial results, so ended up splitting this into two PRs so the change is more easy to understand.

Search: refactor query objects

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py

Just in case the new version of pip breaks too many projects,
we can downgrade easily.

Add feature flag to not install the latest version of pip

---

readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_headers.py
readthedocs/proxito/views/utils.py

Currently, when accessing a subproject (eg. `edx-guide-for-students` being
subproject of `edx`) we are generating `Cache-Tag: edx,edx-latest`. Then, when
a build for `edx-guide-for-students` on version `latest` succeeds, we are purging
the cache tags `edx-guide-for-students-latest`.
This commit makes the `Cache-Tag` generated for subprojects to use the
subproject's slug instead of the parent's/superproject's slug and matching the
cache tag that we are purging when the build succeeds.
Besides, it fixes the `X-RTD-Project` header as well, since it was using the
same parent's/superproject's slug as value.
Fixes #7590

Use correct Cache-Tag (CDN) and X-RTD-Project header on subprojects

---

readthedocs/core/admin.py

These filters allow us to know if we are communicating important messages to organizations/users in an easy way.

Allow search and filter in Django Admin for Message model

---

readthedocs/rtd_tests/tests/test_notifications.py

Since we are using this tests in -corporate as well, we need to check only for
settings wee are override in the test to avoid passing in .org and failing in .com

Check only override settings

---

readthedocs/doc_builder/environments.py

We are already catching other similar exceptions here, log them and continuing
with the build. However, there is now another similar exception
`requests.exceptions.ReadTimeout` that's causing some builds to fail.
This commit catchs this exceptions and makes the build to behave in the same way
as we are doing with similar exceptions.
Related https://github.com/readthedocs/readthedocs.org/issues/7583#issuecomment-718246665

Catch `requests.exceptions.ReadTimeout` when removing container

---

readthedocs/settings/base.py

We have noticed some strange behavior when trying to `create_container` and
`remove_container` using the Docker API. For some reason we started getting
ReadTimeout and I'm supposing that our Docker daemon has been restarted (because
of OOM) or in a dumb state.
This commit increases from 750 to 1000 Mb of RAM memory reserved for our
application and OS processes.
The user will get 7000Mb instead of 7200Mb in build-large instances and
in build-default instances they will get 2400 intead of 2700Mb.
Reference: https://github.com/readthedocs/readthedocs.org/issues/7583#issuecomment-718702683

Reserve 1Gb for Application Memory

---

readthedocs/search/faceted_search.py
readthedocs/search/serializers.py

This should hopefully make search a little faster,
we don't make use of these fields in the serializer.
The big ones are sections and domains,
we will be fetching all of them per each page,
instead of just the ones that matched.
Also fixed a bug, we were omitting the description from the project in
the serializer.
ref #7349

Search: exclude some fields from source results

---

readthedocs/rtd_tests/tests/test_automation_rules.py
readthedocs/rtd_tests/tests/test_project_views.py
readthedocs/rtd_tests/tests/test_sync_versions.py

Otherwise trigger_build would try to call the API,
and then keep trying till it times out.
In these tests we don't need to run trigger_build. This was more noticeable in the automation rules tests, bc they are a lot and almost each tests call to trigger build :D. Probably there are other tests that are hitting this code, but those were the ones I found so far

Tests: mock trigger build to speed up tests

---

readthedocs/projects/views/public.py

Excluding spam projects from the tag index page really slows it down. This involves a project-project self join and then joining against users and the user profile. Each of these tables is a few 100k records. In the worst case, this page can take ~2s to load which can be very bad when the page is crawled repeatedly.
This PR simply removes filtering out spam projects which is the expensive part of this query.
* **PRO:** Speeds the page up drastically without getting rid of it. This page is one of the main ways for projects to get indexed by search engines. It also helps link projects to similar projects. In my tests, this sped things up by over an order of magnitude even in cases where the returned result didn't change from the spam filtering.
* **CON:** Spam projects might show up in the …

Speed up the tag index page

---

readthedocs/rtd_tests/tests/test_sync_versions.py

One test is failing because the project doesn't belong to an
organization. Now that we have those models here, I think we should
create the organization here instead of allowing it to fail.

Tests: create an organization when running in .com

---

readthedocs/api/v3/tests/test_builds.py
readthedocs/api/v3/tests/test_projects.py

Noticed these slow tests today.
Otherwise it will keep retrying till it times out.
Similar to https://github.com/readthedocs/readthedocs.org/pull/7661

Tests: mock update_docs_task to speed up tests

---

readthedocs/search/api.py
readthedocs/search/serializers.py
readthedocs/search/tests/test_api.py
readthedocs/search/views.py

Mainly this was done to allow us support searching on
different versions of subprojects.
Currently, we assume we search the same version for all subprojects.
- _get_all_projects_data and _get_all_projects
were merged into just one method.
And instead of returning a list of projects we return a dictionary of project slugs mapped to a VersionData object.
- There is some duplication in .com.
`_has_permission` and `_get_subproject_versions_queryset`
are overridden in .com.
- ProjectData was renamed to VersionData since it has more attributes
related to a version than a project.

Search: refactor api view

---

readthedocs/doc_builder/python_environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

Our config file depends on `six` package to check `string_types`, so we need to
make sure we have it installed as a core requirement.
We were pinning `sphinx<2` which depends on `six`. Now, all the projects using
`USE_LATEST_SPHINX` will install just `sphinx` (currently 3.3.1) which does not
depends on `six` anymore and all they builds will fail.
> `USE_LATEST_SPHINX` is marked for all future projects. So, new projects are hitting this issue currently. I de-activate this feature for new projects while we solve and deploy this.
> We could remove this dependency completely by copying the relevant lines from `six`, but I think it's safer to use `six` while we support Python 2 & 3 together. To remove it, we would need to confirm that we are not requiring six anywhere else as well.
Closes …

Install six as core requirement for builds

---

readthedocs/search/api.py
readthedocs/search/tests/conftest.py

This wasn't causing any problems in production because we already filter by active versions only, but better be safe.

Search: filter only active and built versions from subprojects

---

readthedocs/oauth/services/bitbucket.py
readthedocs/rtd_tests/tests/test_oauth.py

For some reason the API sometimes doesn't have a mainbranch,
and it doesn't have an empty dict but None as value...

Bitbucket: mainbranch can be None

---

readthedocs/search/documents.py

Big documents will take some time (and memory) to find and highlight results.
Using a term vector will reduce this computation,
but it will increase the size of the index.
We have a lot of free space, so we are fine.
This was working before for big documents because there wasn't a limit
by default https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_limiting_the_length_of_an_analyzed_text_during_highlighting
I added this only to fields that can be big, the other text fields don't think will get much from this change, but let me know if you want me to put this on all text fields.

Search: use with_positions_offsets term vector for some fields

---

readthedocs/core/management/commands/collectstatic.py
readthedocs/core/signals.py
readthedocs/settings/base.py

Define these two signals and send them pre_ and post_ collectstatic command is
executed. The `collectstatic` command is overwritten to be able to send these
signals.

Define `pre/post_collectstatic` signals and send them

---

docs/guides/autobuild-docs-for-pull-requests.rst
readthedocs/api/v2/views/integrations.py
readthedocs/builds/models.py
readthedocs/builds/tasks.py
readthedocs/builds/tests/test_tasks.py
readthedocs/core/views/hooks.py
readthedocs/oauth/services/base.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_celery.py
readthedocs/settings/base.py

Currently, we are deleting external versions
when they are closed, but their docs remain in storage.
With this change we mark them as inactive instead.
Later a task will delete all external versions that are inactive
and their last activity was from 3 months ago.
The task is run once every day (not sure if this should run more frequently).
Before being deleted the status is updated to link to the build page
instead (the build will be deleted currently, but I'm changing that in
another PR).
Ref https://github.com/readthedocs/readthedocs.org/issues/7674

External versions: delete after 3 months of being merged/closed

---

readthedocs/projects/views/private.py
readthedocs/templates/projects/includes/feature_disabled.html
readthedocs/templates/projects/project_traffic_analytics.html
readthedocs/templates/projects/projects_search_analytics.html

We need this for .com mainly.
close https://github.com/readthedocs/readthedocs.org/issues/7689

Extra features: allow to display them conditionally

---

.circleci/config.yml
readthedocs/search/faceted_search.py
requirements/pip.txt

The only change was:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#hits-total-now-object-search-response
We don't need to re-index, the index is compatible between 6.x and 7.x.
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html
We need to update common https://github.com/readthedocs/common/pull/74
Closes #5620

Search: update to ES 7.x

---

readthedocs/search/parsers.py

ES 7.x has this number as default for nested objects.
It gives an error if we try to index more than that.
Closes https://github.com/readthedocs/readthedocs.org/issues/7735

Search: limit number of sections and domains to 10K

---

readthedocs/projects/views/private.py

Currently we are showing the data even if the feature isn't enabled.
This is noticeable on .com mainly.

Traffic analytics: don't pass context if the feature isn't enabled

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py

This is already default in the latest version of pip.
Not sure if leave the method.

Features: remove USE_NEW_PIP_RESOLVER

---

readthedocs/oauth/services/gitlab.py
readthedocs/rtd_tests/tests/test_oauth.py

For GitLab we use
``repo.full_name = fields['name_with_namespace'] # ("Maksudul Haque / test")``
for ``full_name`` and not
``repo.full_name = fields['path_with_namespace'] # ("saadmk11/test")``
Here ``fields['path_with_namespace']`` is more appropriate for the ``full_name`` field as it looks similar to the other VCS providers (GitHub, BitBucket) ``full_name`` field value.

Use "path_with_namespace" for GitLab RemoteRepository full_name Field

---

readthedocs/builds/apps.py

Register the task to shutdown the builders by themselves.
Required by: https://github.com/readthedocs/readthedocs-ext/pull/368

Register ShutdownBuilder task

---

readthedocs/api/v2/utils.py
readthedocs/rtd_tests/tests/test_sync_versions.py

We weren't hitting this before bc we were excluding active versions.
But now, external versions can also be inactive.
Close https://github.com/readthedocs/readthedocs.org/issues/7738

Version sync: exclude external versions when deleting

---

readthedocs/analytics/proxied_api.py
readthedocs/api/v2/views/footer_views.py
readthedocs/search/api.py

I'm not sure why I didn't use this before :shrug:,
it works just fine for methods, the cache is per instance, so all good.
Maybe because I tried to cache something else that wasn't hashable in
some of this code before? don't know

Use lru_cache for caching methods

---

readthedocs/builds/apps.py

This task needs to be registered on upstart so celery worker can run it when it
receives it.

Register AutoscaleBuildersTask

---

readthedocs/oauth/services/gitlab.py

ref: https://github.com/readthedocs/readthedocs.org/issues/7743

Set The Right Permissions on GitLab OAuth RemoteRepository

---

readthedocs/doc_builder/environments.py
readthedocs/settings/base.py

Sometimes it might be necessary to add additional binds to the build
container, e.g. to add SSH keys for the docs user to clone private
repositories or for caches. These additional binds can be specified
as field in settings:
DOCKER_ADDITIONAL_BINDS = {
'/home/docs/.ssh': {
'bind': '/home/docs/.ssh',
'mode': 'ro',
}
}

Allow to add additional binds to Docker build container

---

readthedocs/doc_builder/python_environments.py

Mamba 0.1.0 is the latest version that supports Python2 (which is our default in
the conda environment --as we use miniconda2) while the current stable version
is 0.7.6
Using the older version of mamba is causing different resolution issues and
making the build to fail.
Environment still can be created with python2 or python3 versions.
See https://github.com/mamba-org/mamba/issues/640 for more context.

Use Python3.7 on conda base environment when using mamba

---

readthedocs/projects/signals.py
readthedocs/projects/tasks.py
readthedocs/projects/views/private.py

This happens in a periodic task every five minutes now.
There are other PRs to delete more code in -corp and -ext.

Remove domain verify signal and task

---

tasks.py

There is a small typo in tasks.py.
Should read `translations` rather than `tanslations`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, tanslations -> translations

---

readthedocs/projects/forms.py
readthedocs/projects/views/private.py
readthedocs/rtd_tests/tests/test_project_views.py

The initial data is set at the class level,
this means it doesn't survive for the next form.
I'm using the same method the wizard uses to store information per
session.
This doesn't mean the data is always set as default after saving,
it means the default values are going to be set when the user
is in the advanced form.
So, due to that I have moved the default_branch field to the
basic form, this way the form will always have the default branch.
Close https://github.com/readthedocs/readthedocs.org/issues/7697
:mage_man:

Import page: fix wizard form

---

readthedocs/projects/tasks.py

We can't query over `user__projects=` since in .com User objects are not related
directly to Project but instead they are related via an intermediate model
called Team or via SSO.
Use `user__in=AdminPermission.members(project)` instead, where `AdminPermission`
is overloaded in .com to behaves as we need here.
Closes this comment: https://github.com/readthedocs/readthedocs.org/pull/7728#issuecomment-739977236

Change query on `send_build_status` task for compatibility with .com

---

docs/guides/canonical.rst
readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

Fixes https://github.com/readthedocs/readthedocs-sphinx-ext/issues/83

Sphinx: use html_baseurl for setting the canonical URL

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/rtd_tests/tests/test_doc_builder.py

This value has been the default since the start of the project
https://github.com/mkdocs/mkdocs/blob/0.13.0/mkdocs/config/defaults.py#L44
We should respect that default value,
(we should actually don't edit it at all https://github.com/readthedocs/readthedocs.org/issues/2483).
So, instead of trying to guess the docs dir always,
only try to guess it if the user doesn't have mkdocs.yaml file.
This should avoid any backwards incompatibility and avoid weird bugs to
new users till we completely remove all magic.
Closes https://github.com/readthedocs/readthedocs.org/issues/7539

Mkdocs: default to "docs" for docs_dir

---

readthedocs/api/v2/views/footer_views.py
readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_headers.py

I wasn't able to add the cache tag in the proxito middleware,
since it makes use of ``path_project_slug``,
that is is sets only on the serve views.
I added the project and version tag as well,
so it gets cleared when the project/version is purged.

Footer: add cache tags

---

docs/config-file/v2.rst

- Make it easy for mkdocs users to copy/pasta the config without needing to uncomment and delete the sphinx stuff
- When editing the search.ignore key, you need to add the defaults as well or you can be indexing content you don't want like the 404 or search page

Docs: make it easy to copy/pasta examples

---

readthedocs/doc_builder/backends/sphinx.py
readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
readthedocs/rtd_tests/tests/test_doc_builder.py

This is to allow us to link to the PR and to the build
from the docs using our external_version_warning extension.
ref https://github.com/readthedocs/readthedocs-sphinx-ext/pull/95/

PR preview: pass PR and build urls to sphinx context

---

readthedocs/rtd_tests/tests/test_doc_builder.py

Tests: make PRODUCTION_DOMAIN explicit

---

docker-compose.override.yml

We are currently using v4.0.14 on Azure.

Match Redis version with production

---

readthedocs/builds/querysets.py

Instead of querying the whole table, we filter builds up to 5 hours ago when
looking for concurrent builds.
The query goes from ~4s (in the worst case) to ~6ms with this filter.
Closes #7822

Speed up concurrent builds by limited to 5 hours ago

---

readthedocs/doc_builder/backends/sphinx.py
readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

version.vcs_url shouldn't have access to the db for external versions. The value was being evaluated for all aversions

Fix conf.py for external versions

---

readthedocs/analytics/proxied_api.py
readthedocs/analytics/tests.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/projects/models.py
readthedocs/projects/views/private.py
readthedocs/rtd_tests/tests/test_builds.py
readthedocs/rtd_tests/tests/test_footer.py

These features have been enabled on a large sample for a while now, and I also enabled them in all projects since last last week (~12 days ago).
The only problem found was with Sphinx itself https://github.com/readthedocs/readthedocs.org/issues/7816, but iit's all good now.
We use the subscription to decide if page views should be enabled in .com.

Remove some feature flags

---

readthedocs/payments/utils.py

Call `log.exception` instead of just `pass` to log these errors and know what's
happening in production.

Log Stripe errors when trying to delete customer/subscription

---

readthedocs/metrics/tasks.py

Override default base -ext metrics to add `build-large` queries.
This file is missing from PR https://github.com/readthedocs/readthedocs.org/pull/7817

Metric tasks for community

---

readthedocs/settings/base.py

Allow users to build with latest release of Python.
Requires: https://github.com/readthedocs/readthedocs-docker-images/pull/159

Add support for Python 3.9 on "testing" Docker image

---

readthedocs/projects/tasks.py

This helps us to know in which queue the build is limited and have better metrics.

Save builder when the build is concurrency limited

---

readthedocs/builds/forms.py
readthedocs/builds/signals.py

This is useful to know when to purge the footer.
With ext#404 we now purge the footer from all versions when we purge a version as well.
So this is the only missing place left to purge the footer.

Add version_changed signal

---

docs/api/v3.rst

The description of the end point should have `(str:project_slug)`, not "pip"

Doc fix: two endpoints had 'pip' for the project_slug

---

readthedocs/storage/s3_storage.py

This is how we have them in .com.

Set storage for BuildCommand and BuildEnvironment as private

---

docs/custom_domains.rst

I just set up a CNAME record in Cloudflare pointing to `readthedocs.io` and it got an SSL certificate for the custom domain so this seems to no longer be a problem.

Cloudflare to Cloudflare CNAME Records

---

docker-compose.override.yml

This is the current version on AWS for Community.

Upgrade Redis version to match production

---

readthedocs/api/v2/views/model_views.py
readthedocs/builds/models.py
readthedocs/builds/tasks.py
readthedocs/core/utils/general.py
readthedocs/projects/models.py
readthedocs/projects/tasks.py
readthedocs/projects/views/public.py
readthedocs/proxito/tests/base.py
readthedocs/proxito/views/mixins.py
readthedocs/proxito/views/serve.py
readthedocs/search/parsers.py
readthedocs/storage/__init__.py
readthedocs/storage/s3_storage.py

Some storage backends (notably S3) have extra startup times for the first connection to the backend (~50ms) which means that the storage object has to be reused for the best performance. This reuses them by making our storage instances into lazy loaded module level variables exactly like Django does with `staticfiles_storage`.
This is an alternative to #7905.
After the Azure -> AWS migration, we noticed that an extremely common piece of code which proxied requests to RTD to the appropriate file in cloud storage was taking much longer than before: ~60ms instead of ~10ms. Because this code is called on every request to docs or a build media file in RTD, it is called high tens to low hundreds of times per second in production and this caused us to need 3-4x the number of instances as normal. …

Make storage classes into module level vars

---

readthedocs/builds/tasks.py
readthedocs/builds/tests/test_celery_task_router.py

Currently, every time a PR is triggered to be built we are building it under our
build:large queue. This is because we have no data about this version and we
build them on build:large.
This commit checks where the last build was built when a PR is triggered to be
built and use that queue to build the PR.
Closes https://github.com/readthedocs/readthedocs.org/issues/7815

Router PRs builds to last queue where a build was executed

---

docs/config-file/index.rst
docs/config-file/v1.rst
docs/config-file/v2.rst
docs/intro/import-guide.rst

Why `.readthedocs.yaml`?
- Configuration files usually start with a `.` so they are hidden in
unix like systems.
- `.yaml` is the official and recommended extension for yaml files.
We could go a little further and use a feature flag to stop finding
the other ones.
ref https://github.com/readthedocs/readthedocs.org/issues/7915

Use only one variant of the config file

---

readthedocs/search/management/commands/reindex_elasticsearch.py
readthedocs/settings/base.py

This is almost a re-rewrite from the previous command.
- Don't be shy with the chunk size and go up to 500 (so we create fewer tasks)
- Improve a little the code to improve memory issues with large tables
- Apply tasks immediately instead of use chord and friends (chord will evaluate everything at the end and cause memory issues with large tables)
- Dive the re-index into 3 stages:
- Re-index into a temporal index (here we get the timestamp that was used for the re-index)
- Change the  temporal index to be the main one.
- Execute the command again with `--update-from` to re-index projects that were changed between the re-index.
I have tested this locally.

Search: improve re-index management command

---

readthedocs/settings/docker_compose.py

By default on local docker environment we were usign `test` user for SLUMBER
API. However, this user is not created at `--init` and it has to be created
manually.
To avoid this extra step, we are defining `admin` user for SLUMBER which is
created automatically on init.

Use `admin` user for SLUMBER API on local environment

---

requirements/docker.txt

Same as https://github.com/readthedocs/readthedocs-ops/pull/855/

Pin jedi dependency to avoid breaking ipython

---

readthedocs/api/v2/mixins.py
readthedocs/api/v2/views/footer_views.py
readthedocs/search/api.py
readthedocs/search/tests/test_proxied_api.py

So, there is one catch, search from the main project should be purged when one of the versions from its subprojects change (this can be done by adding one extra query when purging versions).
And... we are also losing some data from search analytics here, so not really sure if we want to cache search after all, or maybe just cache for a shorter time.

Search: add cache tags

---

readthedocs/builds/tasks.py
readthedocs/builds/tests/test_celery_task_router.py

When a build for an external version is triggered, we find the the last build
for the default version and use the same queue for this version.
This should make the build to always succeed when it's merged into the default
version since it's using the same build queue.
I thought this was fixed originally in
https://github.com/readthedocs/readthedocs.org/pull/7912/ but that PR was wrong.

Route external versions to the queue were default version was built

---

readthedocs/builds/utils.py
requirements/pip.txt

We are receiving "Acquire on closed pool" error randomly after running instances
for more than ~1 day and calling `self.app.control.cancel_consumer` from our
task that kills VM instances.
This seems to be a known problem in 3.x Celery verions but some users reported
that it's still present in <4.4.
- https://github.com/celery/celery/issues/4410#issuecomment-505728049
- https://stackoverflow.com/questions/36789805/celery-kombu-fails-after-self-connections-acquire
- https://github.com/celery/celery/issues/1839
Celery released 5.x on September, so I'm upgrading to it directly as a test. If
everything keep working together, we can leave it. Otherwise, we can go back to
latest 4.4.x series: 4.4.7.
Sentry issue on production: https://sentry.io/organizations/read-the-docs/issues/2101960715/?proje …

Upgrade Celery and friends to latest versions

---

docs/intro/getting-started-with-sphinx.rst

Myst is a more maintained and feature complete version of markdown for Sphinx.
Updated `getting-started-with-sphinx.rst` and added Myst instalation
guide under `using-markdown-with-sphinx` section.
Closes https://github.com/readthedocs/readthedocs.org/issues/7937

Docs: Adds Myst to the getting started with sphinx

---

readthedocs/settings/base.py

The cached template loader is now the default. It will speed up situations where `{% include %}` is called in a loop.
https://docs.djangoproject.com/en/2.2/ref/templates/api/#template-loaders

Enable the cached template loader

---

readthedocs/projects/management/commands/dump_project_remote_repo_relation.py

This is one of two PR's for dumping/loading Project and RemoteRepository Relationship data.
This PR adds a management command to dump the project -> RemoteRepository relationship data in a json file. So, that It can be loaded by another command to update the relationship for the new tables.
ref: https://github.com/readthedocs/readthedocs.org/issues/7806

Add Management Command to Dump Project and RemoteRepository Relationship in JSON format

---

docs/development/settings.rst
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_imported_file.py
readthedocs/settings/base.py

The current implementation tries to read the file from PRODUCTION_DOMAIN
using HTTP scheme. If PRODUCTION_DOMAIN requires authentication or HTTPS
scheme the request fails.
The new implementation allows to set a different host to be used for
reading the object file in the settings.
Otherwise it uses the old implementation to access PRODUCTION_DOMAIN using
HTTP. Usage in settings:
RTD_INTERSPHINX_URL = 'http://localhost'

Allow to use a different url for intersphinx object file download

---

.readthedocs.yml

This page is confusing users. We don't really support this way of running a
local instance anymore and it's having problems with orjson.
I'm downgrading its search ranking for now, but we should probably kill it completely.
See #7958

Lower rank of development/install.html

---

readthedocs/embed/views.py

Some users may be sending doc as /doc instead of just doc

Embed: fix join

---

readthedocs/builds/tasks.py

Builds: register tasks to delete inactive external versions

---

dockerfiles/Dockerfile

This is required to have a fully compatible client with the new features from
v12, which is the one that we are using on our docker setup, but also in
production.
As a example, the following command fails with the old client:
```
psql (10.15 (Ubuntu 10.15-0ubuntu0.18.04.1), server 12.5 (Debian 12.5-1.pgdg100+1))
WARNING: psql major version 10, server major version 12.
Some psql features might not work.
Type "help" for help.
docs_db=# \d oauth_remoterepository
ERROR:  column c.relhasoids does not exist
LINE 1: ...riggers, c.relrowsecurity, c.relforcerowsecurity, c.relhasoi...
```
(note the differences between client and server versions)
We will need to update this also in our production images (cc @ericholscher we may need this to run DB queries from `dbshell` for the constraints)
Required …

Upgrade `postgres-client` to v12 in Docker image

---

readthedocs/builds/tasks.py

This was failing if the previous default version build didn't have a `builder`.
This happened on failed or cancelled builds.

Fix build routing

---

docs/development/standards.rst

- remove mention that this guide is not good for contributors; they should be
using this setup instead of the old one
- add `git clone` step that automatically clone the `common` submodule
- tip for dettach an attached session
- remove mention to `master` branch; we build from checked out branch now

Update development/standards guide

---

readthedocs/search/api.py
readthedocs/search/serializers.py
readthedocs/search/tests/test_api.py
readthedocs/search/views.py

Since we did a re-index, we can use this value from the page instead
of querying from the db, now all results will have correct urls for the
given doctype :)
Closes https://github.com/readthedocs/readthedocs.org/issues/7762

Search: use doctype from indexed pages instead of the db

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py

Current version is 1.1, this was pinned as we used to just keep updating them manually and time passed and this wasn't updated. This also matches my lies in https://github.com/readthedocs/readthedocs.org/pull/7859 :D

Install latest mkdocs by default as we do with sphinx

---

dockerfiles/docker-compose-assets.yml
docs/development/front-end.rst
docs/development/standards.rst
gulpfile.js

Currently to build assets we need to install nodejs locally, install all the
node packages locally and call `npm ci && bower update && npm run build`. This
has some downsides due that all of this commands are not ran inside the docker
container:
- we need to have all the Python requirements installed locally
- `manage.py collectstatic` is run in the host machine
- all the static files are not copied to the S3 storage backend
- we don't know what version of `nodejs` is the valid one
To avoid all of these issues, this commit creates a new invoke task:
inv docker.buildassets
which pins the version of node used, runs all the node commands in an isolated
docker container and finally runs `manage.py collectstatic --noinput` inside the
`web` container, which will copy all the new assets to the …

Use independent Docker image to build assets

---

docs/intro/getting-started-with-sphinx.rst

Replaces `myst-parser` -> `myst_parser` in `conf.py`

Fixes typo in getting-started-with-sphinx:

---

readthedocs/oauth/admin.py
readthedocs/oauth/models.py

ref: https://github.com/orgs/readthedocs/projects/74#card-56545525

Add __str__ to RemoteRepositoryRelation and RemoteOrganizationRelation and Use raw_id_fields in Admin

---

readthedocs/embed/tests/test_api.py
readthedocs/embed/views.py

- Validate that the correct arguments are given
- Don't return http requests from the parser
- Always update doc from path (in case path is given by the url)
- Hit the API to test things

Embed: validate query arguments

---

dockerfiles/Dockerfile

Otherwise the installation fails in the postgresql step.

Dockerfile: install lsb_release

---

readthedocs/oauth/management/commands/sync_vcs_data.py

* Add `--logged-in-days-ago` argument to resync only users who logged in some days ago
* Add `--skip-revoked-users` argument to avoid resyncing users we already known they revoked our access token

RemoteRepository: Improvements to `sync_vcs_data.py` script

---

readthedocs/api/v2/proxied_urls.py
readthedocs/api/v2/views/proxied.py
readthedocs/rtd_tests/tests/test_imported_file.py

And fix tests in .com.
Currently we are using the same view for the normal api and the proxied
api. This isn't correct as we don't have the auth backends in the
normal view. There is a change in .com as well.

Embed: Allow to override embed view for proxied use

---

readthedocs/projects/views/public.py
readthedocs/rtd_tests/tests/test_project_views.py

ref https://github.com/readthedocs/readthedocs.org/issues/8015

Badge: exclude duplicated builds

---

readthedocs/projects/views/private.py

We are not showing this data in the page, but it's still available when downloading

Search: don't leak data for projects with this feature disabled

---

readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_redirects.py

This is currently broken,
eg. this URL works:
https://docs.readthedocs.io/en/latest///index.html

Canonicalize all proxito slashes

---

readthedocs/oauth/models.py

Currently production code consider a project already imported if the
`Project.repo` fuzzy matches `RemoteRepository.clone_url` even if that `Project`
is not linked to any `RemoteRepository`.
This allow anyone to import a repository manually using the real GitHub URL to
"take over" that repository and avoiding the real owner of that repository to
import it from "Import Project" page because it says:
This repository has already been imported
and linking to the project that someone's else has imported.
With the changes on this PR, we are showing that message only if the `Project`
is connected to a `RemoteRepository` which is only possible to be done by owners
of the GitHub repository.
> NOTE that this PR is based on `rel` which already have #7949 merged. We can cherry-pick this commit into …

Use `RemoteRepository` releation to match already imported projects

---

docs/config-file/v2.rst

We don't support pdf for MkdDocs D:

Docs: remove pdf format in MkdDocs example

---

docs/guides/feature-flags.rst
readthedocs/api/v2/views/integrations.py
readthedocs/projects/forms.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_api.py

This is already the default in both sites.
We already migrated projects to use the project setting.

Feature flag: remove EXTERNAL_BUILD

---

readthedocs/api/v2/utils.py

When using bulk_create, the post_save signal isn't called.
The VersionSlugField relies on that https://github.com/readthedocs/readthedocs.org/blob/27b1f020a34a4fadaf93e2a1880e6b07b0aa3771/readthedocs/builds/models.py#L141-L145
Ref https://github.com/readthedocs/readthedocs.org/issues/7907#issuecomment-805298912

Versions: don't create versions in bulk

---

readthedocs/embed/tests/test_api.py
readthedocs/embed/views.py

This doesn't require any other changes in our purging code,
as this is purged when the project or version changes.

Embed: add cache tags

---

readthedocs/embed/tests/test_api.py
readthedocs/embed/urls.py

- Changed the url name to match the others and have the same name as the
proxied one.
- Divide the test so is easy to test the proxied version.

Test proxied embed API

---

readthedocs/doc_builder/environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

Small things I saw while reading this code.
combine_output and input data aren't used in our code nor in docker.
I think we can remove the non-docker implementation at some point.

Build environment: remove unused code

---

docs/commercial/single-sign-on.rst

- remove note saying that it's currently on beta
- add paragraph explaining how to enable VCS SSO
- add paragraph explaining how to enable Google SSO

SSO: add small paragraph mentioning how to enable it on commercial

---

readthedocs/api/v3/tests/responses/projects-builds-detail.json
readthedocs/api/v3/tests/responses/projects-detail.json
readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json
readthedocs/projects/urls/private.py
readthedocs/projects/views/private.py
readthedocs/rtd_tests/tests/test_views.py
readthedocs/templates/projects/project_version_submit.html

This is not currently used outside the new theme, but enables the
solution for #6238 -- latest `master` of the new theme already expects
this code.
For now, the create URL does throw and exception, because we are
rendering template code inside the version form. I'm not going to
address this as the create view is not linked and unused, and we
probably shouldn't be rendering templates inside form instantiation
anyways.
The edit version URL does change with this, to append the `/edit/`
postfix. This was done to match similar URL patterns, and to give a path
for the create view URL that does not match the edit URL pattern.

Add separate version create view and create view URL

---

docs/server-side-search.rst

The `page` and `page_size` query parameters were missing from the Server Side API documentation, so this PR should fix https://github.com/readthedocs/readthedocs.org/issues/8006

Add page and page_size to server side api documentation

---

readthedocs/doc_builder/python_environments.py

`pip` can be defined as https://github.com/LFPy/LFPy/blob/b38146fb94dc933f5c40afd872369502031b9537/doc/environment.yml#L16
Ref https://sentry.io/organizations/read-the-docs/issues/2317539725/?environment=production&project=148442&referrer=alert_email

Conda: protect against None when appending core requirements

---

docs/config-file/v2.rst

> The configuration file must be in the root directory of your project an be named `.readthedocs.yaml`.
an -> and

Docs: fix typo in config-file/v2.rst

---

readthedocs/api/v2/utils.py
readthedocs/builds/tasks.py
readthedocs/rtd_tests/tests/test_sync_versions.py

We were using this only for logging,
retrieving all versions from the db and making an string from it
may be expensive.
This may be related to the OOM error, but hard to say.
Didn't see anything else that may be causing this.

Sync versions: don't fetch/return all versions

---

docs/development/install.rst
tox.ini

- Force Python 3.6 on tox, for those using it (to avoid installation issues of dependencies and also to match the version we are currently using)
- Add more detail to MinIO instructions (do not assume that the user knows how MinIO works)
- Add post-install, verification steps
~This should be ready to go, but at the moment I am not able to complete the steps because of a local error:~ _(Edit: Figured it out, fix to follow)_

Improve contributing docs, take 2

---

docs/faq.rst
docs/guides/feature-flags.rst
docs/hosting.rst

- Clarify management of feature flags (fix #8098)
- Better document resolution strategy for 404 page (see #8089)
- Fix recommendation for relative paths in requirements (fix #8087)

Miscellaneous doc improvements

---

readthedocs/doc_builder/environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

We don't use this in production,
but we hit this in https://github.com/readthedocs/readthedocs.org/issues/8075.

BuildCommand: don't leak stacktrace to the user

---

readthedocs/api/v2/serializers.py

We were using an empty string :D

API (v2): use empty list in serializer's exclude

---

readthedocs/doc_builder/python_environments.py

- Use --pre, so all packages are listed.
- Use conda_bin_name so it works with mamba (tested it and mamba
supports list)
- Use the environment name (the version slug is used)

Build: improve list_packages_installed

---

readthedocs/api/v2/templates/restapi/footer.html

Screen readers use aria-label.
Fixes part of https://github.com/readthedocs/sphinx_rtd_theme/issues/970

Include aria-label in flyout search box

---

readthedocs/api/v2/utils.py

Using %d was causing an issue when trying to format `None`:
```
celery-web celery.redirected:227[19247]: WARNING Message: '(Sync Versions) Deleted Versions: project=%s versions_count=[%d]'
celery-web Arguments: ('***************', None)
```
This commit uses %s and defaults to 0 when no versions were deleted.

Logging: use %s to format the variable

---

readthedocs/builds/tasks.py
readthedocs/builds/tests/test_celery_task_router.py

Currently we only check the last successful builds,
but if a user changes from pip to conda like in https://github.com/readthedocs/readthedocs.org/issues/8128
then they would always keep using the normal builds.
This also matches the docstring.
Changed N_BUILDS to MIN_SUCCESSFUL_BUILDS to make it less cryptic.

Celery router: check all `n` last builds for Conda

---

readthedocs/builds/tasks.py
readthedocs/oauth/tasks.py
readthedocs/projects/tasks.py

Add some `log.info` with the local context for this task so we can debug OOM a
little more in production code.

web-celery: add logging for OOM debug on suspicious tasks

---

readthedocs/embed/tests/test_api.py
readthedocs/embed/views.py

can't wait to get rid of docnames :D
Ref https://sentry.io/organizations/read-the-docs/issues/2360423193/?environment=production&project=161479

Embed: fix paths that start with `/`

---

readthedocs/projects/models.py
readthedocs/search/api.py
readthedocs/search/tests/test_api.py

This flag has been set to true for a while now.

Search: default to search on default version of subprojects

---

docs/development/design/system-packages.rst

Related: https://github.com/readthedocs/readthedocs.org/pull/7566

Design doc: allow to install packages using apt

---

readthedocs/projects/managers.py
readthedocs/projects/querysets.py
readthedocs/rtd_tests/tests/test_project_querysets.py

- Introduce `Project.objects.for_user`.
This is to replace the `for_team_member` method from .com
- `private` isn't used in both sites, and usually what we call private is just the use of `public` passing a user. 
- Remove unused overrides.

Querysets: simplify project querysets

---

docs/custom_domains.rst

Otherwise this gets rendered as `eadthedocs.io.`

Docs: add space to bash code

---

docs/guides/cross-referencing-with-sphinx.rst

closes https://github.com/readthedocs/readthedocs.org/issues/8172

Docs: remove some lies from cross referencing guide

---

readthedocs/builds/querysets.py
readthedocs/projects/querysets.py
readthedocs/rtd_tests/tests/test_privacy.py
readthedocs/rtd_tests/tests/test_version_querysets.py

These aren't used, and I don't see them being used in the future.
- private: there isn't a part of our code were we want to list
all private versions, instead we may want to use `public(user)`.
- for_project: this was listing all versions from a project and its
translation. Not sure were we would want that, but isn't used.
The private queryset from projects is being removed in https://github.com/readthedocs/readthedocs.org/pull/8154

Querysets: remove private and for_project

---

readthedocs/projects/forms.py
readthedocs/rtd_tests/tests/test_project_views.py

Ref https://sentry.io/organizations/read-the-docs/issues/2393755976/?environment=production&project=148442

Project: use IntegerField for `remote_repository` from project form.

---

readthedocs/builds/querysets.py
readthedocs/projects/querysets.py

We use the is_superuser check in .com,
while we check for has_perm in .org.
These checks are only for the api user,
and has_perm always returns true for superusers.
I have checked and our api users are superusers,
so all good.
Also, user is always required.

QuerySets: check for .is_superuser instead of has_perm

---

readthedocs/api/v2/views/model_views.py
readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_domains.py
readthedocs/rtd_tests/tests/test_privacy_urls.py

We have experienced DOS in some opportunities when hitting these endpoints
without any kind of filter. They may require a big DB query causing the site
going down.
This commit disable all listing endpoint without removing the functionability we
are currently using:
- filter versions by project slug
- getting a specific build by commit hash
On those cases where it's disabled, we return a nice message to the user
communicating that it's disabled and APIv3 should be used instead.

APIv2: disable listing endpoints

---

readthedocs/api/v2/serializers.py

Currently we are using only `project.skip` to know if the build for this
particular project has to be skipped after the task was triggered. However, if
the if the project belongs to an organization and the organization is disabled
those builds already queued will be built.
This commit uses `is_active` for `project.skip` field in the API response, that
takes care of this case.
This helps us if we found that an organization _already_ triggered many builds
and we need to cancel all of them. With this change, just by doing
`organization.disable=True` will make kill them all at built time instead of
processing them.

Build: use `is_active` method to know if the build should be skipped

---

readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_middleware.py
readthedocs/proxito/tests/test_redirects.py
readthedocs/rtd_tests/tests/test_footer.py

This introduces one more query for normal serving, except when a custom domain is used, there the queries are the same, I think this is fine.
Closes https://github.com/readthedocs/readthedocs.org/issues/7881
We can revert https://github.com/readthedocs/readthedocs.org/pull/7880/
after releasing this.

Proxito: redirect to main project from subprojects

---

readthedocs/doc_builder/environments.py

`volumes=` argument is not required for our use case when calling
`create_container` if `host_config` is passed.
Besides, we were passing a dictionary when it a string o list is
expected (see the examples with `volumes=` and https://github.com/docker/docker-py/blob/96c12726fdb9b24e985b4de74d5c82145ccd8185/docker/api/container.py#L374-L375)
The combination of both `volumes=` (as a dict) plus calling
`create_container(host_config=..)` with `host_config` containing `binds` makes
my local environment to fail with:
ERROR (Build) [test-builds:latest] failed to create shim: OCI runtime create
failed: invalid mount {Destination:community_build-user-builds Type:bind
Source:/var/lib/docker/volumes/f86b268f8b853f2498eef2f7c5a76f68d3bb905490e3db142826c1a1bd752fe4/_data
Options:[rbind]}: mount …

Docker: remove `volumes=` argument when creating the container

---

docs/index.rst
docs/legal/dpa/index.rst
docs/legal/dpa/subprocessors.rst
docs/legal/index.rst

Slightly reorganizes some of our legal docs under a separate path, but doesn't move some of the files yet.
This is our DPA from our lawyers, pandoc reformatted to reST. We wouldn't use this for esign, but the source of an esign/click-through version would be the same as this file.
The agreement isn't necessary to review. The most helpful thing to review are the doc changes and the subprocessor list and list information.

Add DPA to legal docs in documentation

---

readthedocs/analytics/tests.py
readthedocs/api/v2/proxied_urls.py
readthedocs/proxito/middleware.py
readthedocs/rtd_tests/tests/test_footer.py

None of these need the proxito request middleware (response is needed).
The analytics api isn't listed because it depends on the unresolver,
which depends on the proxito middleware.

Proxito: don't require the middleware for proxied apis

---

readthedocs/organizations/managers.py
readthedocs/organizations/querysets.py

- `RelatedOrganizationManager` isn't used
- `TeamManager.{public,api}` aren't used. And `public` didn't make  sense, as it was listing everything by default.
- In the querysets `user` is always required.

Organizations: simplify querysets/managers

---

readthedocs/builds/querysets.py
readthedocs/projects/querysets.py
readthedocs/redirects/querysets.py
readthedocs/rtd_tests/tests/test_project_querysets.py

Get ready for sharing more code,
mainly rename `_add_user_repos` to `_add_from_user_projects` and
`_add_user_projects`.
Start accepting admin and member attributes where needed,
these aren't used here yet, but they will.
I have removed some overrides that weren't needed or weren't overridden
in .com.
And for my next trick/PR, I'd try to move some overrides into .org :D

QuerySets: refactor _add_user_repos

---

readthedocs/projects/urls/public.py
readthedocs/search/views.py
readthedocs/urls.py

This was extracted from https://github.com/readthedocs/readthedocs.org/pull/8149/
to make it easy to review.
- Separate this "shared" view into two classes, too many conditionals
otherwise.
- Remove unused `index` query param.
No changes to the logic were made, there is another PR in .com to match these changes

Search: refactor views

---

readthedocs/builds/querysets.py
readthedocs/projects/querysets.py
readthedocs/redirects/querysets.py
readthedocs/rtd_tests/tests/test_managers.py
readthedocs/rtd_tests/tests/test_version_querysets.py

This isn't used, and is always `True`

QuerySets: remove unused `detail` parameter

---

docs/code-of-conduct.rst
docs/contribute.rst

We haven't used this actively in years,
but freenode is now lost :(

Remove IRC from our docs

---

docs/contribute.rst

The old channel goes back to our old repository name, and all new Gitter
channels are under out GitHub/Gitter community namespace `readthedocs`.
There are a few channels there, but this is the most general channel.

Update gitter channel name

---

docs/api/v3.rst
readthedocs/api/v3/filters.py
readthedocs/api/v3/mixins.py
readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/responses/remoteorganizations-list.json
readthedocs/api/v3/tests/responses/remoterepositories-list.json
readthedocs/api/v3/tests/test_remoteorganizations.py
readthedocs/api/v3/tests/test_remoterepositories.py
readthedocs/api/v3/urls.py
readthedocs/api/v3/views.py

closes https://github.com/readthedocs/readthedocs.org/issues/7509

Add List API Endpoint for `RemoteRepository` and `RemoteOrganization`

---

readthedocs/proxito/views/decorators.py

Ref https://sentry.io/organizations/read-the-docs/issues/2216431985/?environment=production&project=148442&query=is%3Aunresolved+host_project_slug&statsPeriod=14d

Proxito: check if attribute exists

---

readthedocs/search/documents.py

This change decreases the number of query made to the database for indexing document to elasticsearch by around 50%

Optimize Index time database query

---

docs/downloadable-documentation.rst

Follow-up to #8135.
---
Needs confirmation that this is indeed how the downloads will be managed by RTD.
I noticed this behavior in #8135 which I did not expect (removing `formats` in a branch also removes old uploads matching that config), but that's a convenient workaround to not having a "delete" option in the dashboard to remove older downloads if they become unwanted.

Docs: Add section about deleting downloadable content

---

readthedocs/projects/views/base.py

This little one is being executed several times in several views.

Cache get_project

---

docs/api/v3.rst
readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/responses/projects-detail.json
readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json
readthedocs/api/v3/tests/responses/projects-versions-detail.json

For use in dashboard client code, having a link to the dashboard for
some resources would be helpful, and would avoid exposing the url
resolver through Django to the JS side.
Requires https://github.com/readthedocs/readthedocs.org/pull/7595

Add APIv3 version edit URL

---

docs/user-defined-redirects.rst

- Move the "Implementation" section further up as a note, so that it's
more visible (I missed it myself and spent some time trying to test
redirects on 200 which do not work).
- Add mentions to the use case of setting Exact Redirects to have
Page Redirects but applied only to a specific version. It's common
to move pages only in the `latest` branch/future stable branches,
without doing the change in older branches.
- The button to confirm a redirect is now named "Add".
----
I'm happy to amend the commit as needed if you disagree with some of the proposed changes.

Docs: Add some details to the User Defined Redirects

---

docs/intro/getting-started-with-sphinx.rst

It's super out of date,
and doesn't show markdown, etc.

Remove video from our Sphinx quickstart.

---

docs/sponsors.rst
readthedocs/templates/base.html
readthedocs/templates/homepage.html

The first commit adds a link to the sustainability page on the footer. The second commit includes some site stats on the front page so they are also more visible.

Make sustainability page more visible

---

media/css/readthedocs-doc-embed.css
readthedocs/api/v2/templates/restapi/footer.html

We shouldn't use strong tags to surround a dd tag, use css instead.
Closes https://github.com/readthedocs/readthedocs.org/issues/7903

Footer: return well formed html

---

readthedocs/builds/filters.py
readthedocs/builds/views.py
readthedocs/projects/filters.py
readthedocs/projects/views/private.py
readthedocs/projects/views/public.py

Most of these filters are currently only used in views when the new
templates are enabled. The project dashboard view context data was
replaced with a filter, which does enable sorting on the dashboard view
using request arguments (like `?sort=built_last`), but this isn't
exposed in the UI.

Add project/build filters

---

docs/legal/index.rst
docs/legal/security-policy.rst

This structure and content was inspired by Help Scout's security policy
doc: https://www.helpscout.com/company/legal/security/

Add basic security policy

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_doc_builder.py
readthedocs/vcs_support/backends/git.py

- Gitpython expands envvars by default
We execute gitpython outside the containers.
Currently there isn't a way to exploit this vulnerability
(looks like gitpython is aware of this and may change the default
to false any time https://github.com/gitpython-developers/GitPython/blob/617c09e70bfd54af1c88b4d2c892b8d287747542/git/repo/base.py#L142-L143)
- In some places we were executing git commands outside the container
(to get the commit), let's always use the current env (docker in
production).

Git: don't expand envvars in Gitpython

---

readthedocs/oauth/services/github.py
readthedocs/rtd_tests/tests/test_oauth_sync.py

When a GitHub user does not belong to a GH organization but does have access to a particular repository inside the GH organization, the `RemoteRepositoryRelation` was not being created. This commit checks for this case and allows the creation of the `RemoteRepositoryRelation`.
Also, if the GH repository was part of a GH organization and then it's moved to a GH user account, we remove the link between ``RemoteRepository`` and ``RemoteOrganization``.

Sync RemoteRepository for external collaborators

---

readthedocs/search/api.py
readthedocs/search/faceted_search.py
readthedocs/search/tests/test_api.py

- Document things
- Don't aggregate when we don't need to
- Don't duplicate single term queries,
there is no need for operators for a single term.
- Move operators to the base class.
- Do prefix search only for now till we figure out a better way to have small/faster indices

Search: small improvements

---

readthedocs/search/documents.py
readthedocs/search/faceted_search.py
readthedocs/search/serializers.py

This is a partial revert of
https://github.com/readthedocs/readthedocs.org/pull/7613.
Turns out, having more fields increase the size of the index,
and that makes all queries slower, even if they aren't using the new
field.

Search: remove additional fields

---

readthedocs/oauth/utils.py
readthedocs/rtd_tests/tests/test_project_views.py

Before we were catching the exception because the relationship was a OneToOne.
Now that it's a ForeignKey, the field could be `None` instead.
Fixes this issue: https://sentry.io/organizations/read-the-docs/issues/2470813831/

oauth webhook: check the `Project` has a `RemoteRepository`

---

readthedocs/organizations/forms.py
readthedocs/organizations/models.py
readthedocs/organizations/tests/test_forms.py

- Check for empty slugs
- Check for a max length of 32
(enforced to the form level for now)

Organizations: validate that a correct slug is generated

---

readthedocs/builds/tasks.py

Sometimes it happens that the task fail for some reason and people don't get the
PR status updated for RTD build. This commit adds a retry up to 3 times to avoid
these cases.
Closes #8177

PR build status: re-try up to 3 times if it fails for some reason

---

readthedocs/rtd_tests/fixtures/spec/v2/schema.json

* Closes https://github.com/readthedocs/readthedocs.org/issues/6363
* As soon as this is merged, I'll make the PR and get it added to the JSON Schema Store catalog.
* Closes https://github.com/readthedocs/readthedocs.org/pull/6501
Assuming I've understood the YAML Schema correctly (I did read the Yamale README), I believe they should be equivalent (or at least almost equivalent.)
I made a new PR instead of reviewing an older one, as I felt there was a lot to change.
I've tested this against the following:
* https://github.com/pytube/pytube/blob/master/.readthedocs.yml
* https://github.com/Rapptz/discord.py/blob/master/.readthedocs.yml
* https://github.com/deepmind/open_spiel/blob/master/readthedocs.yml
* https://github.com/tensorlayer/hyperpose/blob/master/.readthedocs.yml
* …

feat: add json schema

---

readthedocs/rtd_tests/fixtures/spec/v2/schema.json

This should be a number,
otherwise you are required to put `"2"`.
/cc @SethFalco

Schema: fix version type

---

readthedocs/templates/projects/project_redirects.html

Inspired by what's done on the `projects/domain_list.html` template:
https://github.com/readthedocs/readthedocs.org/blob/e0e6602b23345b65ff67478a8f2d2d4c90ea8b6b/readthedocs/templates/projects/domain_list.html#L16-L18
See https://github.com/readthedocs/readthedocs.org/issues/8264#issuecomment-871115620 for some context.

Add link to redirect docs

---

readthedocs/projects/signals.py
readthedocs/projects/tasks.py

If the API fails, we end up without a self.version.
We could check if it exists, but this signal isn't used,
so I'm removing it.
Note, this signal was used to stop the ssh agent in .com,
but we have migrated to start the ssh agent inside the container,
so the ssh agent is killed when the container is killed.
ref https://sentry.io/organizations/read-the-docs/issues/2031190901/?project=148442&query=is%3Aunresolved

Build: remove after_vcs signal

---

docs/connected-accounts.rst
docs/pull-requests.rst

This is a common issue,
so now we at least have a link to point users to.
Closes https://github.com/readthedocs/readthedocs.org/issues/7381

Add docs about setting up permissions for GH apps & orgs

---

requirements/deploy.txt
requirements/docker.txt

We upgraded to latest psycopg2 in #8293 to a version that's incompatible with
Django 2.2. This commit downgrades it to a compatible version.
Closes #8334

psycopg2: pin to a compatible version with Django 2.2

---

requirements/pip.txt

1.5.0 has an corrupted file for the ukrnian translation.
It should be fixed in 1.5.1, but just reverting to the old one
for sake of deployment.

Downgrade taggit

---

readthedocs/doc_builder/environments.py
readthedocs/projects/tasks.py
readthedocs/rtd_tests/tests/test_builds.py
readthedocs/rtd_tests/tests/test_doc_building.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/base.py

We are mutating this variable on the environment instance, and that's being passed to the next commands.
https://github.com/readthedocs/readthedocs.org/blob/babbdf058f1ae4eade27b4ef579e6b142a5dffba/readthedocs/vcs_support/base.py#L76-L76
Previous to https://github.com/readthedocs/readthedocs.org/pull/8263 we were creating a new instance (LocalBuildEnv) so this bug wasn't visible, but now we are using the same env to be able to always execute these commands inside docker (except for gitpython that still runs outside the container).
Now I have moved the env var to avoid the prompt outside git (GIT_DIR isn't needed as explained in https://github.com/readthedocs/readthedocs.org/pull/8318#pullrequestreview-704630103) and I made environment private so isn't mutated outside the class without …

Dont mutate env vars outside the BuildEnv classes

---

readthedocs/core/utils/contact.py

This setting includes the name, not just the email. We may want to change this value in our ops repos.

Use email from DEFAULT_FROM_EMAIL to contact users

---

docs/guides/commercial.rst
docs/guides/importing-private-repositories.rst
docs/guides/private-submodules.rst

This is mostly extracted from the private submodules guide,
and also includes steps for Azure DevOps.
Rendered version: 
- https://docs--8336.org.readthedocs.build/en/8336/guides/importing-private-repositories.html
- https://docs--8336.org.readthedocs.build/en/8336/guides/private-submodules.html

Guides: how to import a private project using an ssh key

---

media/css/core.css
readthedocs/notifications/urls.py
readthedocs/templates/base.html

This is fixed on the new templates too, but we still need more work before releasing them.
I'd put this on the other side, but we don't have something like a box for these notifications

UI: allow to close notifications

---

readthedocs/vcs_support/backends/git.py

We don't need to show this on the build output.

Builds: don't record git rev-parse command

---

readthedocs/templates/homepage.html

Remove the typo error on the home page in the download section.

change vieweable to viewable on  home page: issue#8346

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/config.yml

This prompts users with the following dialogue before opening a new issue on this repository:
(see it in action on my fork)
What do folks think about this?

Redirect users to appropriate support channels using template chooser

---

readthedocs/settings/proxito/base.py

This was getting set and not passed through nginx,
but with our last deploy it is now getting set.
We can optionally turn this on for docs pages,
but we don't want it on everywhere by default.

Remove clickjacking middleware for proxito

---

docs/versions.rst

Hi.
```diff
- you'll neeed to the set the :doc:`privacy level of your project </commercial/privacy-level>` to public.
+ you'll need to the set the :doc:`privacy level of your project </commercial/privacy-level>` to public.
```

Docs: fix typo in versions.rst: neeed -> need

---

docs/webhooks.rst

Following the fruitful discussion at https://github.com/readthedocs/readthedocs.org/issues/8364 I added a paragraph about setting up a webhook for Gitea projects.

Add documentation about webhooks for Gitea

---

docs/api/v3.rst
docs/commercial/sharing.rst
docs/development/design/apiv3.rst
docs/development/design/build-images.rst
docs/development/design/embed-api.rst
docs/development/search-integration.rst
docs/gsoc.rst
docs/guides/conda.rst
docs/guides/deprecating-content.rst
docs/guides/private-python-packages.rst
docs/guides/searching-with-readthedocs.rst
docs/roadmap.rst
docs/webhooks.rst

[`codespell --ignore-words-list="hel,wile" --skip="*.css,*.js,*.po" ./docs`](https://pypi.org/project/codespell)

Fix typos discovered by codespell in /docs

---

readthedocs/templates/builds/build_detail.html

"The recommended extension for files containing YAML documents is .yaml ( http://yaml.org/faq.html ) and this has been the case since at least Sep 2006 ( https://web.archive.org/web/20060924190202/http://yaml.org/faq.html )."
See #7460. Leftover from #7918

Fix YAML extension

---

docs/guides/searching-with-readthedocs.rst
docs/webhooks.rst
readthedocs/builds/managers.py
readthedocs/builds/migrations/0007_add-automation-rules.py
readthedocs/builds/models.py
readthedocs/doc_builder/config.py
readthedocs/doc_builder/python_environments.py
readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
readthedocs/rtd_tests/fixtures/spec/v2/schema.yml
readthedocs/rtd_tests/tests/projects/test_version_sorting.py
readthedocs/rtd_tests/tests/test_api.py
readthedocs/rtd_tests/tests/test_notifications.py
readthedocs/rtd_tests/tests/test_sync_versions.py

Continues #8409
[codespell --ignore-words-list="ba,configurtion,ded,hel,perfom,wile" --skip="*.css,*.fjson,*.js,*.json,*.po,*.svg" ./d* ./readthedocs/b* ./readthedocs/d* ./readthedocs/r*](https://pypi.org/project/codespell)
Also undid a deliberate misspelling `configurtion` discussed at https://github.com/readthedocs/readthedocs.org/pull/8409#pullrequestreview-731868885

codespell part 2 - Continues #8409

---

readthedocs/proxito/middleware.py

This is not super useful. I'm removing the log.info for now. It should be enough
by logging the extra headers added per-domain.

Proxito: do not log response header for each custom domain request

---

readthedocs/search/tests/test_views.py
readthedocs/settings/proxito/base.py
tox.ini

Fixes: https://github.com/readthedocs/readthedocs.org/commit/72e2ae55554e8a58c731c9ec6a82d334a0fc3b5a
[`flake8`](https://pypi.org/project/flake8) detected _undefined names_ in Python code.
The readthedocs/search/tests/test_views.py test is marked `xfail` which is why we have not seen this issue.
https://flake8.pycqa.org/en/latest/user/error-codes.html
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__psf/black__](https://github.com/psf/black) can autocorrect).  Instead these tests focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to …

Fix undefined names

---

.github/CODEOWNERS

I just learned about this feature. We can apparently default who to
delegate review to.
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

Try out codeowners

---

docs/guides/cross-referencing-with-sphinx.rst

This adds MyST (Markdown) examples to "cross-referencing with Sphinx" guide by using https://pypi.org/project/sphinx-tabs/, similarly to how we did in #8283. Basically all our reST samples are in our Sphinx guides - I started with one of them in this pull request to make reviews easier, but I can add a couple more guides. 
While I was at it, I also reworded some parts to use second person and to clarify the role of reStructuredText vs Sphinx and put it on the same ground as MyST.
Got into a couple of rabbit holes while doing it, for example https://github.com/executablebooks/mdit-py-plugins/issues/28. Also, "in-line" references are not supported at the moment, we didn't open an issue for it.

Add MyST (Markdown) examples to "cross referencing with Sphinx" guide

---

docs/faq.rst

With a small modification -- [using `dependencies:` as an alias for `packages:`](https://github.com/Anaconda-Platform/anaconda-project/issues/194) -- one can also use Anaconda Project `anaconda-project.yaml` files in place of `environment.yml` files.

Added note about how to use Anaconda Project.

---

readthedocs/api/v2/templates/restapi/footer.html

This isn't needed anymore,
since we are overriding the footer block instead.

Footer: remove auth block

---

docs/api/v3.rst
readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/test_subprojects.py
readthedocs/api/v3/views.py
readthedocs/projects/forms.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_subprojects.py

One downside is that the error message isn't specific like before, but I have changed it to be a little more friendly than the default one. The form doesn't list invalid subprojects as options, so I have removed the clean_child from there, as the form already validates that the child should be in the queryset. This doesn't require overrides in .com anymore. There are tests for organizations in .com...
Closes https://github.com/readthedocs/readthedocs.org/issues/8395

API v3 (subprojects): filter by correct owner/organization

---

docs/team.rst

Finally, I updated the Team page to better reflect the reality 🎉 
- Alignment with newly-created GitHub teams (Backend, Frontend, Avocacy, Ops)
- Update company figures
- Remove text inviting people to join to focus more on the core teams
- Add avatars
Happy to read comments about my implementation of the avatars. I have no idea why, the HTML table has uneven column widths. I added a custom class in case @readthedocs/frontend can lend a hand shrinking the columns to the content.
On the other hand, I hardcoded the avatar URLs rather than requesting them using a REST API, because I don't think they will change much and also this doesn't require any JavaScript or complex Sphinx logic.
And finally, I wanted the substitution to be a `figure` so I could include the name below, but I couldn't …

Rework Team page

---

readthedocs/search/faceted_search.py
readthedocs/search/tests/test_views.py

TLDR; show only domains that match the selected role_name.
there are `http:get` roles mixed with `http:post`  (mixed with results from top docs)
there are only domains with `http:post` in the results (mixed with results from top docs)
Long version, see the comment in the code and https://github.com/readthedocs/readthedocs.org/issues/8268#issuecomment-909630027.
Closes https://github.com/readthedocs/readthedocs.org/issues/8268

Search: show only results from the current role_name being filtered

---

docs/_static/css/custom.css
docs/conf.py

Adds a custom `.css` file with styling for the team images created with PR #8441.
**Without custom style:**
**With custom style:**

Add custom team img styling

---

docs/development/docs.rst

Probably a typo on instructions to follow a link.

Docs: Change "right-click" to "click"

---

docs/config-file/v1.rst
docs/config-file/v2.rst

Hi.
Please note that I didn't modify the names of these hyperlinks because I have no idea what their new names should be. For example, the section name of https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies is "Optional dependencies" and the name of the link should match it, but this phrase is in the section about "extra_requirements", so I think it might confuse users.
What's your opinion?

Docs: update the links to the dependency management content of setuptools docs

---

readthedocs/builds/tasks.py
readthedocs/notifications/views.py
readthedocs/oauth/services/github.py
readthedocs/projects/notifications.py
readthedocs/projects/templatetags/projects_tags.py

One step further to fully depreate the signals in .com
that add owners to a project.

Permissions: avoid using project.users, use proper permissions instead

---

requirements/pip.txt

We had it pinned because it made Travis to fail, but we are on CircleCI now.
Let's see if we can make it work with the latest version of it.
We need to update it because `cargo` is failing to install this package due that
it doesn't find some dependencies.
<details>
<summary>Click for detailed output</summary>
```
Collecting orjson==2.0.7
Using cached orjson-2.0.7.tar.gz (480 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
Preparing wheel metadata ... error
ERROR: Command errored out with exit status 1:
command: /tmp/env/bin/python3 /tmp/env/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpfqrzpjwz
cwd: /tmp/pip-install-g2bmyvoy/orjson
Complete output (43 lines):
info: syncing channel updates for …
```

Requirement: update orjson

---

docs/development/docs.rst

Prompted by a conversation with @humitos

Add virtual env instructions to local installation

---

docs/development/install.rst

Clarify that the development installation instructions are for Linux

---

readthedocs/core/templatetags/privacy_tags.py
readthedocs/core/utils/contact.py

Instead of creating custom templatetags for each email,
we can just pass a custom function.

Contact users: Allow to pass additional context to each email

---

readthedocs/profiles/views.py
readthedocs/settings/base.py

I'm using this on .com and I think it's more explicit.

Rename audit retention days setting

---

readthedocs/embed/v3/views.py
readthedocs/settings/base.py
readthedocs/settings/docker_compose.py
tox.embedapi.ini

Updates required by https://github.com/readthedocs/sphinx-hoverxref/pull/146 found while doing QA.

EmbedAPIv3: updates after QA with sphinx-hoverxref

---

readthedocs/settings/base.py

We changed this from `ubuntu20` to `ubuntu-20.04` and there was a missing change
here.

Docker: use the correct image tag

---

requirements/deploy.txt

For some reason django-redis-cache==2.1.3 breaks with:
```
@get_client(write=True)
def get_or_set(self, client, key, func, timeout=DEFAULT_TIMEOUT):
if not callable(func):
raise Exception("Must pass in a callable")
```
Looks like an older version gets installed somehow that does not contains the
code we need. So, we force it to be pinned to a git tag.

Requirement: ping django-redis-cache to git tag

---

scripts/compile_version_upload_s3.sh

`AWS_REGION` is required in production and `--endpoint-url` is not.
Besides, `AWS_BUILD_TOOLS_BUCKET_NAME` is required as well in production.

Script tools cache: fix environment variables

---

readthedocs/core/signals.py

EmbedAPIv3 supports internal and external sites.
When the site is internal, we can perform the same checks as we were doing: the
version has to be public to allow it.
On the case for external sites, we can always allow it since the site is public.

EmbedAPI: allow CORS for `/api/v3/embed/`

---

readthedocs/settings/base.py
scripts/compile_version_upload_s3.sh

Added a comment right above the `RTD_DOCKER_BUILD_SETTINGS` explaining how to
add a new tool/version and what are the steps required.
Besides, the bash script used to compile and upload the version to the cache is
updated a little bit as well.

Docs: comment about how to add a new tool/version for builders

---

docs/config-file/v2.rst

I decided to add a new section after the current keys to simplify how we present this information, but there are other alternatives.
On the other hand, I have highlighted that "this is beta", since that is my current understanding of the functionality. If this is incorrect, I'll be happy to remove the admonition.
I chose the word "new" because I assume that, at some point in the future, we will reorder this documentation and declare the current one "legacy". However, [it might be a bad idea](https://ddbeck.com/new-is-a-mark/). If we expect this to last long (and it is often the case that we don't expect things to last long, but they do), we should choose a better name.

Document new `build` specification

---

readthedocs/projects/models.py
readthedocs/projects/tasks.py

This is a temporal solution while we decide how to fix the real problem. For
now, we are installing a newer version of `ca-certificates` before starting to
clone the repository.
Reference #8555

Build: update ca-certificates before cloning

---

docs/config-file/v2.rst

The title will eventually change to not be beta, and any existing links to this
anchor will not scroll to this section, which is always confusing. Let's drop
this early, there's already an admonition below the title.

Drop beta from title of build config option

---

docs/integrations.rst

These docs were out of date with our code:
https://github.com/readthedocs/readthedocs.org/blob/d6f7347f82d7b3e210cd7e7e84d860282dd029f8/readthedocs/oauth/services/github.py#L208

Fix GitHub permissions required

---

readthedocs/organizations/forms.py
readthedocs/organizations/tests/test_views.py

Similar when adding a team member, but we don't create an invitation if the email doesn't exist.

Organizations: allow to add owners by email

---

docs/guides/reproducible-builds.rst

See https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-961883441.

Update requirements pinning

---

readthedocs/proxito/views/mixins.py
readthedocs/templates/spam.html

Return 401 - Gone when we detect a spam project and block the doc serving.

Spam: use 410 - Gone status code when blocked

---

readthedocs/projects/admin.py

When we manually use the "Ban project owner" Django admin action, we trigger the
task to check for spam rules immediately.

Spam: check for spam rules after user is banned

---

docs/conf.py
docs/faq.rst

See companion blog post https://github.com/readthedocs/blog/pull/141.
There is not enough material to warrant a separate guide, so I added this to the FAQ instead. I also considered adding a new section under the Jupyter guide, but that one is for "Jupyter notebooks on Sphinx", which is not quite related.

Add entry on Jupyter Book to the FAQ

---

dockerfiles/nginx/proxito.conf
readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_headers.py

This is mainly for .com,
to tell explicitly to the CDN to not cache things.
There are PRs on the ops/.com repos.

Proxito: add CDN-Cache-Control headers

---

docs/faq.rst

This PR adds information about using `apt` to install dependencies to the FAQ.

docs: update faq to mention apt for dependencies

---

readthedocs/projects/admin.py

Use a `gte` and `lt` applied to the spam filters so we show "_only_ projects
with score between N-M instead of >N"

Spam: make admin filters easier to understand

---

readthedocs/proxito/middleware.py

Given a hostname `slug--bug--1.org.readthedocs.build`, the current
parsing code will give a project slug of `slug` and a version slug of
`bug--1`. This was a valid slug creation pattern for a short while,
though we have changed the behavior of the slugging to not produce slugs
with consecutive dashes.
rsplit here searches for the right most instance of double slugs
Fixes #8699

Fix issue with PR build hostname parsing

---

requirements/pip.txt

They break the local installation,
and looks like some minor versions
were released yesterday for both, kombu and redis.
https://docs.celeryproject.org/en/latest/changelog.html

Downgrade celery and friends

---

docs/guides/developers.rst
docs/guides/poetry.rst

Clarifies how Poetry is supported on Read the Docs.

Add guide on Poetry

---

requirements/pip.txt

We are installing requests-oauthlib as a transitive dependency of
django-allauth. However, we are importing it directly, so we should declare it
as our own dependency.
Closes #8692

requirements: add requests-oauthlib

---

readthedocs/oauth/tasks.py
readthedocs/rtd_tests/tests/test_oauth_tasks.py

`.values_list` returns a list of id when accessing the related object. We use
that list of ids to query `Organization` model and get real organization objects instead.
Solves: https://sentry.io/organizations/read-the-docs/issues/2747536252/

oauth: sync remote repositories fix

---

readthedocs/proxito/tests/test_full.py

ref https://github.com/readthedocs/readthedocs.org/pull/8700

Test external serving for projects with `--` in slug

---

docs/builds.rst
docs/development/docs.rst
readthedocs/doc_builder/python_environments.py
readthedocs/rtd_tests/tests/test_celery.py
readthedocs/rtd_tests/tests/test_doc_building.py

See https://github.com/readthedocs/readthedocs.org/issues/8659.

Avoid future breakage of `setup.py` invokations

---

readthedocs/embed/views.py

Note that we were mixing `doct=` and `doc=`. This change will make all of them behave properly.
cc @astrojuanlu to upgrade the NR dashboard.

Logs: typo on keyname

---

readthedocs/projects/views/private.py
readthedocs/templates/projects/domain_form.html

This is so we can share the same view with .com
when switching to CF.
The steps will require to only create a CNAME record,
the value of this record will be unique per-domain on .com,
and it will continue to be static on .org.
The are PRs on .com and -ext

Custom Domain: make cname_target configurable

---

readthedocs/conftest.py

There is an error when running tests on .com
due to a cached key somewhere.
Maybe there is missing a tearDown somewhere
or it's the result of a side effect when running these tests
with the settings from .com.
But in any case, I think just making this for each test
is better instead of trying to figureout where to put
a tearDown function.
Hopefully the impact in time isn't big.

Always clear cache after each test

---

readthedocs/templates/spam.html

It was pointing to readthedocs.io instead of readthedocs.org

Spam: contact link on template

---

readthedocs/settings/base.py

Sphinx docs are hosted on RTD.
Low priority change, but came up when talking to @humitos and wanted to send a PR for it already. If I understood correctly, this should have no effect.

Remove sphinx-doc.org from external domains

---

readthedocs/projects/admin.py

Spam rules are run automatically
after the user profile is saved.

Don't run spam rules check after ban action

---

docs/guides/embedding-content.rst
docs/guides/jupyter.rst

These were the two last guides that had reStructuredText examples without MyST Markdown examples.

Add MyST Markdown examples everywhere

---

readthedocs/api/v2/views/integrations.py
readthedocs/doc_builder/environments.py
readthedocs/embed/v3/views.py
readthedocs/gold/views.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/oauth/tasks.py
readthedocs/projects/tasks.py
readthedocs/proxito/views/serve.py
readthedocs/rtd_tests/tests/test_oauth.py
readthedocs/settings/base.py

The main purpose of this PR is to reduce the log entries sent to Sentry unless they are errors that we can fix only. We were sending "GitHub webhook creating failed", and the reason was the repository was deleted for example --which is not an error on our side.
Besides, there are some tweaks and improvements to have more structured logs where we can get analytics from.

Logging: tweaks and minor improvements

---

readthedocs/organizations/forms.py
readthedocs/organizations/tests/test_views.py

This is the same behavior we have for projects
https://github.com/readthedocs/readthedocs.org/blob/b70be9f3abb1ad4f1608496de353f86701aef8e0/readthedocs/projects/forms.py#L118-L130

Skip slug check when editing an organization

---

readthedocs/api/v3/tests/mixins.py

This is to fix some tests on .com.
We already have some test for organizations on .com
(we should move them here).

API v3: explicitly test with RTD_ALLOW_ORGANIZATIONS=False

---

readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/responses/projects-subprojects-detail.json
readthedocs/api/v3/tests/responses/projects-subprojects-list.json
readthedocs/api/v3/tests/responses/projects-subprojects-list_POST.json

As explained and confirmed in
https://github.com/readthedocs/readthedocs.org/issues/8394,
subproject_of was never meant to be included,
there is a bug when using the SettingsOverrideObject instead
of using the base class, and the tests were wrong.
Closes https://github.com/readthedocs/readthedocs.org/issues/8394

API v3: don't include subproject_of on subprojects

---

readthedocs/api/v3/routers.py
readthedocs/templates/rest_framework/api.html

To use the api on the browser, there is no need to pass the auth token,
we use the user session.
Also, the token link was redirecting always to .org,
use a relative link instead.
And remove the duplication in the title.

API v3: improve message when using the API on the browser

---

docs/conf.py

Better to point the dev docs to `latest`. Continuation of #8751.

Follow up to dev docs split

---

readthedocs/doc_builder/python_environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

Continuation of #8711, see discussion at #8775.

Cap setuptools even if installed packages are ignored

---

docs/user/guides/edit-source-links-sphinx.rst

The link to the relevant section in the Sphinx documentation was changed.

Fix broken link in edit-source-links-sphinx.rst

---

requirements/pip.txt

It seems that new pip version complains about this error now and breaks the
installation process. We are pinning to the latest 3.x version of redis for now.
I think we can upgrade the django-redis-cache version once we are on Django 3.2.x
Closes #8786

Requirements: downgrade redis to 3.5.3

---

pytest.ini
readthedocs/projects/exceptions.py
readthedocs/projects/forms.py
readthedocs/projects/views/base.py
readthedocs/projects/views/mixins.py
readthedocs/projects/views/private.py
readthedocs/projects/views/public.py
readthedocs/rtd_tests/tests/test_project_forms.py
readthedocs/rtd_tests/tests/test_project_views.py
readthedocs/settings/base.py
requirements/pip.txt

Quick/Initial implementation to deny showing a project's dashboard if spam score
is above the threshold.
- the old and non-used `ProjectSpamError` that checked for an invalid
description was removed together with all its logic
- the mixin `ProjectSpamMixin` was re-purposed to check the spam score and deny
serving the dashboard
- move "disable banned user to import projects" inside the `ImportWizardView`
Note that currently we are only denying the dashboard for the project's
detail ("Overview" in our UI) view. If we want to deny other pages like
"Downloads", "Search", "Builds", "Versions" and "Admin" we need to adapt other
views as well (e.g. migrate them from function-based view to class-based view to
be able to re-use the mixin). This can be implemented in a future version.
Together with …

Spam: deny dashboard on spammy projects

---

requirements/pip.txt

We are getting an error, so we downgrade it to the previous version used until
we figure it out what is happening and how to solve it.

Requirements: downgrade celery

---

readthedocs/config/config.py
readthedocs/config/tests/test_config.py
readthedocs/rtd_tests/tests/test_config_integration.py

I created a test case to demostrate what was reported in the issue. Summarizing,
if the project uses a config file and does not define `python.system_packages`
but has `Project.use_system_packages=True` the config option is `True` which is
wrong. When a config file is used, settings at Project level should be ignored
as this messages from "Advanced settings" states:
> These settings can be configured using a configuration file. That's the
recommended way to set up your project. Settings listed here are ignored when
using a configuration file.
Reference #8782

Config file: system_site_packages overwritten from project's setting

---

docs/user/index.rst

Since we removed the dev docs in #5070 , now we have more space for the Commercial docs, which are arguably more useful for users :)

Make commercial docs more visible

---

readthedocs/oauth/services/bitbucket.py
readthedocs/rtd_tests/tests/test_oauth.py

* https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-teams-deprecation/
* https://developer.atlassian.com/cloud/bitbucket/bitbucket-api-changes-workspaces/
Note that "Filter repositories" now will show "username" (`humitos`) and
"workspace name" (`Manuel Kaufmann`) which are duplicated. The first one,
`humitos`, will not show any repository when clicked because all repositories
belong to a workspace now (mapped as `RemoteOrganization` for us)
> Along those lines, repositories, projects and snippets will no longer have an owner. They will be located within a workspace
We may want to come back to this later and remove the "personal account filter"
from the "Filter repositories" list _only_ for the Bitbucket case.
(in the image, `humitos` is my personal user and `Manuel Kaufmann` …

Bitbucket: update to match latest API changes

---

readthedocs/api/v3/permissions.py
readthedocs/api/v3/serializers.py
readthedocs/api/v3/tests/mixins.py
readthedocs/api/v3/views.py

So, conditionally setting attributes
at the class is good,
but when running tests it doesn't re-evaluate
the class, so we are stuck with the previous values.
Since no project on .org has organizations/teams
it doesn't matter exposing these fields (they return null, empty when
passed to ?expand=).

API v3: less overrides

---

docs/user/feature-flags.rst

We don't really want people using this flag anymore. They should be using
`build.os: ubuntu-20.04` with `apt_packages` instead.

Docs: remove `USE_TESTING_BUILD_IMAGE`

---

docs/user/custom_domains.rst

Clarifying note for the documentation about `<link rel="canonical">`.

Canonical can point as stable, not just latest

---

docs/user/config-file/v2.rst

I think we can stop calling it beta since it has been working pretty well for
some months already and we are happy with it.

Docs: remove beta warning from config file's `build` key

---

docs/user/choosing-a-site.rst

* Unify on "site" -> "platform"
* Remove some words for clarity and brevity
* Add some more marketing content, commercial section was dry

Update choosing a platform doc

---

docs/Makefile
docs/dev/design/in-doc-search-ui.rst
docs/dev/index.rst
docs/dev/server-side-search.rst
tox.ini

Fixed some casing issues, and made the build dir play nice with both
docsets (so we can now build each docset independently).
Closes https://github.com/readthedocs/readthedocs.org/issues/8844

Docs (dev): fix server side search

---

readthedocs/audit/models.py
readthedocs/audit/tests/test_models.py

Currently we don't have logs attached to an organization only,
so we don't need to do any type of migration.

AuditLog: always fill organization id & slug

---

docs/dev/install.rst
readthedocs/settings/docker_compose.py
requirements/pip.txt

Currently, the development environment is broken. We haven't noticed this
because it fails on creating the `staticfiles.json` file on `--init` and without
that the whole environment is broken.
By deleting my local volumes I was able to reproduce it. Now, my environment is
broken and it does not work without this patch.
Note that this commit requires a change in `common/` repository to auto-create
the buckets on S3 (MinIO) when called with `--init`. This is required because
newer version of django-storages removed support for auto-creation.
Closes #8812
Requires https://github.com/readthedocs/common/pull/101

django-storages: upgrade

---

readthedocs/builds/tasks.py

We were checking just `conda` key from the config file. This commit adds the
check for `miniconda` in `build.tools.python` too.

Task router: check new config `build.tools.python` for conda

---

readthedocs/builds/tasks.py

This is well tested already and we haven't find any problem with it. I'm leaving
only the INFO logs when we are changing the routing.

Logging: reduce logs in task router

---

readthedocs/doc_builder/python_environments.py

Latest pip version is failing wit
```
ERROR: Exception:
File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
status = run_func(*args)
File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
return func(self, options, args)
File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 389, in run
to_install = resolver.get_installation_order(requirement_set)
File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/3274/lib/python3.7/site-packages/pip/_internal/r …
```

Build: pin pip as workaround

---

dockerfiles/Dockerfile
docs/dev/tests.rst
readthedocs/api/v3/tests/mixins.py
requirements/debug.txt
requirements/docker.txt
requirements/testing.txt
tox.ini

pip is freezing when installing ipdb,
but we also shouldn't install these in our CI.
Installing them from a separate file fixes the issues
with pip's dependency resolver.

CI: Don't install debug tools when running tests

---

readthedocs/api/v2/views/integrations.py
readthedocs/audit/apps.py
readthedocs/builds/apps.py
readthedocs/builds/tasks.py
readthedocs/core/views/hooks.py
readthedocs/doc_builder/backends/sphinx.py
readthedocs/doc_builder/base.py
readthedocs/embed/v3/views.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/organizations/tasks.py
readthedocs/projects/views/mixins.py
readthedocs/rtd_tests/tests/test_oauth.py
readthedocs/subscriptions/utils.py

Make more usage of `log.debug` for things that are already well tested and we
don't usually require taking a look these logs to reduce the verbosity of them.

Logging: reduce verbosity

---

readthedocs/builds/tasks.py

Our config doesn't pass through a string, it passes through a dict that
matches:
```{"version": "1.2.3", "full_version": "1.2.3"}```

Fix issue with build task routing and config argument

---

readthedocs/doc_builder/python_environments.py

It seems the problem with pip was solved in
https://github.com/pypa/pip/pull/10867 and 22.0.3 version was released with this
fix.
Revert #8865

Builder: unpin pip

---

requirements/pip.txt
requirements/testing.txt

The ones from testing.txt look to be added to run tests in parallel, but don't think we are using that at all
https://github.com/readthedocs/readthedocs.org/commit/cbec8dda84aa9dd459a7a2f8141bc2aa17984082#diff-62e3de5fd9ea4d52eea0a93091ed9d4cb07aada53df0014ea7ab161167a66b77
And the other one looks like a `pathlib` clone, but we aren't using it anyway.
https://github.com/readthedocs/readthedocs.org/commit/f80441e42654e065ef9965b82136aa8bba630025#diff-9bbea25af9347c516732a0a88603329c321c46450a72875e8d51b961df303132

Dependencies: remove unused packages

---

readthedocs/projects/tasks/builds.py

Without an exception here, or handling the return from
`_check_concurrency_limit`, a build that hits a concurrency limit in
this method will both set a retry on the task, but will also continue
processing the current task like normal. This results in two identical
builds, then three, then four, and so on.
Untested what this does to the UI though. Edit: the UI reports the retry as I'd expect :+1:

Throw an exception from Celery retry()

---

readthedocs/doc_builder/environments.py

We updated the copy used for generic errors with the celery refactor,
but also converted a generic command failure to `BuildUserError(msg)`.
This caused the command output to always be used as the error message
shown to the user.
More error classes is probably the direction we want to go here, perhaps
even going as far as to provide more helpful errors for each step that
commonly emits the generic user error class.
Refs #8901

Reduce verbose logging on generic command failure

---

.readthedocs.yml
docs/user/config-file/index.rst
docs/user/config-file/v1.rst

People is still arriving at Config File V1 and we want to avoid that as much as
possible. However, we can't yet remove this documentation page since it's still
working and there are people already using it.
We should find a way to migrate these projects off from Config File V1 and
finally remove this documentation page. However, that requires a much bigger
amount of work.
Closes #8857

Docs: reduce visibility of Config File V1

---

readthedocs/projects/tasks/builds.py

We do not want to send notifications (email or webhook) for known exceptions:
- Duplicated build
- Project builds skipped
Closes #7177

Build: do not send notifications on known failed builds

---

readthedocs/projects/tasks/utils.py

`self.task.args` does not exists.
Solves some Sentry issues found after deploy.
We could do something else here maybe. However, I'd like to know what are the
projects hitting the timeout regularly so we have more data about this problem.

Build: access valid arguments

---

readthedocs/subscriptions/apps.py
readthedocs/subscriptions/notifications.py
readthedocs/subscriptions/tasks.py
readthedocs/subscriptions/templates/subscriptions/notifications/organization_disabled_email.html
readthedocs/subscriptions/templates/subscriptions/notifications/organization_disabled_site.html
readthedocs/subscriptions/templates/subscriptions/notifications/subscription_ended_email.html
readthedocs/subscriptions/templates/subscriptions/notifications/subscription_ended_site.html
readthedocs/subscriptions/templates/subscriptions/notifications/subscription_required_email.html
readthedocs/subscriptions/templates/subscriptions/notifications/subscription_required_site.html
readthedocs/subscriptions/templates/subscriptions/notifications/subscription_stats_email.txt
readthedocs/subscriptions/templates/subscriptions/notifications/trial_ending_email.html
readthedocs/subscriptions/templates/subscriptions/notifications/trial_ending_site.html
readthedocs/subscriptions/tests/test_daily_email.py

This code was moved from .com, we don't make use of these tasks on .org, but we run them in celery beat on .com.

Move subscription tasks

---

readthedocs/proxito/README.rst

We aren't sure where is the best place to put these, but I'm +1 on the README.rst idea.
ref https://github.com/readthedocs/readthedocs.org/pull/8896#issuecomment-1035708990

Proxito: add top-level docs

---

readthedocs/projects/tasks/builds.py

This usually happens because there is a problem with the user's repository (e.g.
the repository is private and requires a password) which is something we cannot
solve from our side. So, we ignore this exceptions from being logged in Sentry.

Sentry and Celery: do not log `RepositoryError` in Sentry

---

readthedocs/settings/base.py

Add x-hoverxref-version to CORS

---

readthedocs/doc_builder/environments.py
readthedocs/projects/models.py
readthedocs/projects/tasks/builds.py

We were _always_ using `readthedocs/build:latest` to run all the VCS steps (e.g.
`git clone`). That image had an old `ca-certificates` Ubuntu package that does
not contains the newer Lets Encrypt certificate and because of that many git
command failed.
Now, we had rebuilt the `ubuntu-20.04` image which includes a newer version of
this package and we are defining this image to be used by default in the setup
VCS step. The main goal is to avoid calling `apt-get install ca-certificate` on
each build and reduce this overhead.
Closes #8555

Build: use `ubuntu-20.04` image for setup VCS step

---

readthedocs/builds/migrations/0039_migrate_config_data.py

Use the hacked up script that we ran in place of the migration. We hit
issues with a simple `.update()` backing up queries in production, so
ended up running this script instead. Mostly just archiving this logic
in case we ever want to come back to this.

Tune build config migration

---

readthedocs/doc_builder/environments.py

Just add a comment after merging the hotfix PR in
https://github.com/readthedocs/readthedocs.org/pull/8899

Build: comment `record=False` usage

---

requirements/pip.txt

- we are using py3.8 so we don't need to ignore gitpython anymore
- upgrade to latest version because it fixes a security issue reported at
https://github.com/gitpython-developers/GitPython/issues/1409

Requirements: upgrade gitpython because of security issue

---

readthedocs/projects/tasks/builds.py
readthedocs/projects/tests/test_build_tasks.py

We need to clean up the build error previously shown to the user once the build
is retried for any reason. For example, this avoids the case that the build was
concurrency limited and shows "Concurrency limit reached (2), retrying in 5
minutes."
Then, in the next retry, even after the build is finished, the error is not
removed and we ended up with a successful build showing an error in the build's
detail page. Example: https://readthedocs.org/projects/test-builds/builds/16118772/

Build: reset build error before start building

---

readthedocs/builds/tasks.py
readthedocs/builds/tests/test_tasks.py

A couple of things I noticed:
- We were doing an extra query for each build
to retrieve the `commands` relationship.
I have used prefetch_related to fix this.
- We were serializing the whole object,
but only using the `commands` part.
I have fixed this by serializing only the commands
instead, and using `only` in the qs.
Also, now that we are using prefetch_related,
we can't use `iterator()` since that will
ignore prefetch_related.
And since we can't use iterator,
now the whole thing will be loaded into memory,
so I have reduced the limit from 5K to 2K,
I have tested this query on web extra and with 2K the
process isn't killed.
Currently, we have `285648` builds that aren't on storage

Optimize archive_builds task

---

requirements/pip.txt

PR #8853 changed the specifier from `django-storages[boto3]` to just
`django-storages`, and I believe this caused a bug with local
environments.
I tried to rebuild my local image, but then noticed an import error as
django storages was trying to load the missing module `boto3`. It seems
prior to #8853, we were installing the `boto3` depenedency using the
extras install format for django-storage.

Pin storages with boto3

---

pytest.ini

Most of them are warnings we don't have control because they are from third
party applications.

Test: remove verbose warnings

---

readthedocs/api/v2/serializers.py

When the Build object is updated via PATCH initially, it fails because the
`config` field does not accept `None`. This commit makes the `None` to work.

Build: allow NULL when updating the config

---

readthedocs/oauth/tasks.py

Users belonging to huge GH organizations, like `conda-forge`, were never syncing
their repositories because the task timed out and none of the relationships were
created.

Celery: increase timeout limit for `sync_remote_repositories` task

---

readthedocs/builds/apps.py
readthedocs/builds/tasks.py
readthedocs/builds/tests/test_tasks.py
readthedocs/builds/utils.py
readthedocs/core/apps.py
readthedocs/projects/tasks/builds.py
readthedocs/settings/base.py
requirements/pip.txt

- upgrade celery to 5.2.3
- `before_start` is now a method recognized by this version
- migrate some class-based tasks to function-based tasks to avoid bug when registering them
See https://github.com/celery/celery/discussions/7172#discussioncomment-1827682

Celery: upgrade to latest version

---

readthedocs/settings/base.py

Using `LIMIT 5000` and also `LIMIT 2000` has been causing our database to use
too much CPU. This commit changes this limit to reduce it to 500.
Quickly checking CloudWatch logs, I see that we have around 10k builds per day.
Triggering the task every 15 minutes with a limit of 500 gives us 48k builds
archived per day. If my math is correct, I think we are fine.

Celery: trigger `archive_builds` frequently with a lower limit

---

readthedocs/api/v2/mixins.py
readthedocs/core/utils/__init__.py
readthedocs/embed/tests/test_api.py
readthedocs/proxito/middleware.py
readthedocs/proxito/tests/test_full.py
readthedocs/proxito/tests/test_headers.py
readthedocs/search/tests/test_proxied_api.py

We are using `-` as separator
between the project and version slug.
Is easy to generate a collision to generate the same
tag for two or more projects.
For example:
- Project: my-project
Version: latest
Tag: my-project-latest
- Project: my
Version: project-latest
Tag: my-project-latest
A collision can happen on .org if the final tag has 3 or more `-`,
and on .com if the final tag has 4 or more `-` (since we concatenate the
org slug to each project).
This isn't a security issue,
since the cache tag is used only to purge
the cache, not as a key to cache the content.
I've solved this issue by using a character that isn't
allowed on slugs as separator (`:`).
We will need to purge the cache after deploygin this change.

CDN: avoid cache tags collision

---

readthedocs/builds/tasks.py
readthedocs/settings/base.py

That filter doesn't makes much sense since we are always using
`include_cold=False`.
Yes, this avoids iterating over builds that don't have commands,
but it makes the query really slow.
```python
max_date = timezone.now() - timezone.timedelta(days=1)
limit = 2000
queryset2 = (
Build.objects
.exclude(cold_storage=True)
.exclude(commands__isnull=True)
.filter(date__lt=max_date)
.prefetch_related('commands')
.only('date', 'cold_storage')
[:limit]
)
queryset = (
Build.objects
.exclude(cold_storage=True)
.filter(date__lt=max_date)
.prefetch_related('commands')
.only('date', 'cold_storage')
[:limit]
)
In [51]: queryset.explain()
Out[51]: "Limit  (cost=0.43..2989.01 rows=2000 width=13)\n  ->  Index Scan Backward using date_index on builds_build  (c
ost=0.43..1931896.14 rows=1292853 width=13)\n …
```

Archive builds: avoid filtering by commands__isnull

---

readthedocs/settings/base.py
requirements/pip.txt

`interest-cohort` is not a thing anymore. See
https://github.com/readthedocs/readthedocs.org/pull/8954#discussion_r816962542

Requirements: remove `django-permissions-policy`

---

readthedocs/doc_builder/backends/mkdocs.py
readthedocs/rtd_tests/tests/test_doc_builder.py

Currently we are failing the build if we find None values,
but MkDocs allows them.
Had a user report about this on .com.

MkDocs: allow None on extra_css/extra_javascript

---

readthedocs/projects/exceptions.py
readthedocs/vcs_support/backends/bzr.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/backends/svn.py
readthedocs/vcs_support/base.py

When a `RepositoryError` _without_ a message was raised we were setting the
message as `"None"` and reporting this to the user :(
This commit first checks if the exception already contains a message and use
it in that case. If the exception does not contains a message, it raises it
without a message so the generic one is added by the Celery
handler (`on_failure`).
Also, it improves the messages reported to the user to communicate a more
detailed error depending the case.
Related to the error reported in https://github.com/readthedocs/readthedocs.org/issues/8995

Build: `RepositoryError` message

---

.circleci/config.yml
.codecov.yml
tox.ini

https://docs.codecov.com/docs/codecov-uploader doesn't mention anything about the pip package... but it suggest using this an orb for circle.
After that, codecov was able to run, it wasn't able to find the files it needed to upload, this was because we are running pytest inside the readthedocs dir instead of the root dir of the repo, we could have fixed this with
https://github.com/readthedocs/readthedocs.org/pull/9006/commits/ecb84dd0706fb3dd5046f8c3d391de0869396ab2
https://github.com/readthedocs/readthedocs.org/pull/9006/commits/dc364ab85c4d6f8e10afb864edd89a5287c6360e
but I went and just changed our tox setup to run pytest from the root of the repo as they suggest in their docs.

CI: fix codecov

---

.circleci/config.yml
.codecov.yml
tox.ini

Finally, the xml format was required (the sqlite format did work on the other PR for some reason :man_shrugging:, but xml  is the recommended). Found this in their example at https://github.com/codecov/example-python/blob/master/.circleci/config.yml

CI: fix codecov again

---

readthedocs/doc_builder/director.py
readthedocs/projects/tasks/builds.py

We can't do `with self.build_environment:` twice because the context manager
kills the Docker container on `__exit__`. So, the second time we call the `with`
it will create a new container which won't have all the work done in the
previous steps.
We could avoid this by using shared volumes instead, but that's a bigger
refactor. For now, I'm moving the part that creates the build environment back
to the Celery task and executing `setup_environment` _and_ `build` steps from
there, which is not ideally, but solves the problem for now.
This problem was introduced in #9002

Build: use same build environment for setup and build

---

readthedocs/projects/tasks/builds.py

If the build worker is killed for any reason, as we are using `ACKS_LATE`, the
build task will be picked by another worker and re-executed.
When that happens, we detect that the `Build` object already has some commands
saved on it and we delete those commands to start again from scratch.
This commit just adds a log line to be aware how often this situation happens in
production and be able to make other decisions.

Build: log when a build is reset

---

readthedocs/oauth/services/base.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py

Currently, we are using the default pagination that GitHub offers, which is 30.
This commit increases the page size to 100 when fetching organization for a user
and repositories for each organizations.
Note we are already using 100 page size when fetching repositories for a user.
Related to #8979

GitHub OAuth: use bigger pages to make fewer requests

---

readthedocs/rtd_tests/tests/test_backend.py
readthedocs/rtd_tests/utils.py
readthedocs/vcs_support/backends/git.py

When a tag is annotated,
the real commit will be on the ref that ends with `^{}`.
GitPython handles this correctly,
but lsremote was returning the sha of the tag instead of the commit.
We are using GitPython to get the tags when doing a full build,
and lsremote when doing a sync.
This mismatch is causing problems, as rtd will take it as if the tags
were updated.
Fixes https://github.com/readthedocs/readthedocs.org/issues/8992

Git: fix annotated tags on lsremote

---

readthedocs/settings/base.py
scripts/compile_version_upload_s3.sh

Ubuntu 22.04 LTS is not yet released, but it's already available to use. We can
start allowing people to use this image for their builds.
To make usage of this image in production, we need to:
- `docker build` and push to Docker Hub: https://github.com/readthedocs/readthedocs-docker-images/pull/178
- update the hash for this image on https://github.com/readthedocs/readthedocs-ops/pull/1144
- run `./scripts/compile_version_upload_s3.sh` for the new image with all the `build.tools` supported

Build: allow users to use Ubuntu 22.04 LTS

---

docs/dev/design/system-packages.rst

Link to `#8058` is not rendered.  See https://dev.readthedocs.io/en/latest/design/system-packages.html#using-docker-exec

Fixes link

---

readthedocs/vcs_support/backends/hg.py

We are using Ubuntu 20.04 LTS to perform the clone
step (`readthedocs/build:ubuntu-20.04`) which comes with Mercurial v5.3.1 and
install by default the `sparse-revlog` requirement.
However, if the build is using `readthedocs/build:latest`, which comes with
Mercurial v4.5.3 and does not contain that requirement it fails:
```
hg identify --id
abort: repository requires features unknown to this Mercurial: sparserevlog!
(see https://mercurial-scm.org/wiki/MissingRequirement for more information)
```
This commit disables that requirements to make the clone compatible with the
older version of Mercurial.
Closes https://github.com/readthedocs/readthedocs.org/issues/8995

Build: Mercurial (`hg`) compatibility with old versions

---

readthedocs/doc_builder/python_environments.py

Sphinx 3.1.0 breaks Sphinx 1.8.6 projects,
so we want to avoid another major issue like with docutils breakage in the past.

    Fix jinja2 pinning on Sphinx 1.8 feature flagged projects

---

requirements/docs.txt

Dark mode on sphinx-tabs is enabled when it shouldn't, this should fix it.

Docs: update sphinx-tabs

---

readthedocs/proxito/tests/test_full.py
readthedocs/proxito/views/serve.py

Avoid serving files that are still in the storage (S3) for some reason but its
associated version was deleted or de-activated.
Closes https://github.com/readthedocs/readthedocs-ops/issues/1139

Proxito: do not serve non-existent versions

---

readthedocs/builds/constants.py
readthedocs/builds/tasks.py
readthedocs/builds/utils.py
readthedocs/projects/exceptions.py
readthedocs/projects/tasks/builds.py

Different reasons (e.g. multiple push) makes our platform to trigger
`SyncRepositoryTask` multiple times one next to the other for the same project.
This consumes a lot of resources (clone the repository, query the databse,
update the database's versions, etc) but in the end it's is useless because
there is nothing has changed so quickly in the repository to require re-syncing
the versions.
We've found projects triggernig more than 1.5k of this task in a single day or
even in less time. This has made our database's CPU to spike and reduce the
availability of our workers to execute `UpdateDocsTask`, blocking our users and
producing a worse UX to them.
This commit makes usage of a lock (based on Celery's `memcache_lock`) to execute
up to 1 task per minute per project, and discard the rest …

SyncRepositoryTask: rate limit to 1 per minute per project

---

readthedocs/config/config.py
readthedocs/config/models.py
readthedocs/config/tests/test_config.py
readthedocs/doc_builder/director.py
readthedocs/projects/tests/test_build_tasks.py

Allow people to use `build.jobs` to execute pre/post steps.
```yaml
build:
jobs:
pre_install:
- echo `date`
- python path/to/myscript.py
pre_build:
- sed -i **/*.rst -e "s|{version}|v3.5.1|g"
```
> See a full example of a working config file: https://github.com/readthedocs/test-builds/blob/build-jobs/.readthedocs.yaml
* `build.jobs` can't be used without `build.os` / `build.tools`. This is done on purpose to avoid maintaining old/deprecated features (config file v1 and v2 with `build.image`)
* CWD path is the path where the repository was cloned
* _none_ of the "internal jobs" (`checkout`, `install`, `build`, etc) can be overwritten in this initial version. We will need a defined contract (e.g. `metadata.yaml`) to allow this
* we are not escaping the commands the user wrote in the YAML. …

Build: implement `build.jobs` config file key

---

docs/user/config-file/v2.rst

Small reference documentation for `build.jobs` and all the pre/post jobs allowed.
Related #9016

Docs: `build.jobs` reference documentation

---

.github/auto_assign.yml

This bot will auto-assign any PR created to it's own author. It will help us to
manage our new Roadmap using GitHub Beta Projects in a better way.
> We can easily disable if we find it does not work as we expected.

Github: use probot auto-assign bot

---

readthedocs/redirects/models.py

We are using `re.sub` just for a simple substitution, and aren't escaping the part that is generated from the user, instead of escaping that part I'm just removing the prefix and using str.replace

Redirects: avoid using re.sub

---

readthedocs/proxito/tests/test_old_redirects.py
readthedocs/proxito/views/mixins.py
readthedocs/proxito/views/serve.py

The "bad" redirect comes from
https://github.com/readthedocs/readthedocs.org/blob/065aa152548017482e0c273697d9d4ad5aa80df4/readthedocs/proxito/views/mixins.py#L296
And that's because we are using the netloc/protocol/etc from the
result of parsing `proxito_path`, which we only need to check for infinite redirects, not to form the final redirect.
This is another place where we are using urlparse and truncating the URL at the wrong path
https://github.com/readthedocs/readthedocs.org/blob/065aa152548017482e0c273697d9d4ad5aa80df4/readthedocs/proxito/views/serve.py#L307-L308
If filename is `https://foo.com/foo`, then path will be `foo`, and that's wrong.
I'm just fixing where the problems are, but we could:
1)  Redirect URLs with those invalid chars (`/%0d/example.com` -> `//example.com` -> …

Proxito: fix URL parsing

---

readthedocs/proxito/views/serve.py

Otherwise we were checking for the version `None` literally.
Also, this saves us two storage calls for 404s outside a version :)

Proxito: only check for index files if there is a version

---

readthedocs/projects/exceptions.py
readthedocs/vcs_support/backends/bzr.py
readthedocs/vcs_support/backends/git.py
readthedocs/vcs_support/backends/hg.py
readthedocs/vcs_support/backends/svn.py

This commit converts the `@property` used to select the correct message
depending on the platform (.org or .com) by a `@classmethod` to make it simpler
to realize that we need to call it as a regular method.
In Python 3.9, we will be able to combine these two decorators and we won't need
parenthesis anymore. For now, we need to add parenthesis to make the call of the
method.

Build: bugfix `RepositoryError.CLONE_ERROR` message

---

docker-compose.override.yml
dockerfiles/Dockerfile
docs/dev/install.rst
docs/user/guides/private-python-packages.rst

GitHub changed the format of their personal tokens a while ago,
but it also changed the way they are use,
before you'll pass an empty password/user,
now you are required to pass your username with it.
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#using-a-token-on-the-command-line
If you are using the old tokens, the scripts should continue working (I think, since the GITHUB_USER will be empty)

Adapt scripts and docs to make use of the new github personal tokens

---

readthedocs/api/v2/utils.py
readthedocs/rtd_tests/tests/test_backend.py
readthedocs/rtd_tests/tests/test_sync_versions.py
readthedocs/vcs_support/backends/git.py

If two versions share the same verbose name
(a branch named 2.0 and a tag named 2.0),
then we will be updating both,
instead of just one and changing its type from branch to tag.
Later when running this same code,
it will see the branch as new, since isn't included in our queryset that
filters by type=branch.
This wasn't happening before because this check was true
https://github.com/readthedocs/readthedocs.org/blob/2e3f208c4906de649a9b5b9e33afee6cc20b86bc/readthedocs/api/v2/utils.py#L74-L74
Since a branch would never change its identifier
(origin/name), but once lsremote was enabled,
the identifier didn't included the 'origin/' part.
So, when doing a full build the branches would be changed
to (origin/name) and when doing a syn they would be changed
to (name), and so on.
Ref …

Sync versions: filter by type on update

---

readthedocs/projects/tasks/builds.py

Do not send notifications (email/webhook and VCS commit status) when a build
"fails" because it it's retried.
> While testing https://github.com/readthedocs/readthedocs.org/issues/9014#issuecomment-1091913936 I receive two notifications that I shouldn't have received and I noticed that we are not skipping this exception.

Notification: don't send it on build retry

---

.github/workflows/main.yml

Builds triggered with v1 don't have access to the context,
v2 doesn't have this restriction.

CI: use circle api v2 to trigger builds

---

readthedocs/analytics/models.py

We have old records without `full_path`,
and since `full_path` isn't in the constraints of `unique_together`
Django will try to create a new record with that value
and fail.
This isn't a problem for new page views.

Analytics: Don't use full_path in get_or_create

---

scripts/compile_version_upload_s3.sh

Avoid uploading the .tar.gz to production S3 since we will be managing this via
CircleCI and an AWS orbs. See
https://github.com/readthedocs/readthedocs-docker-images/pull/179
We need to keep the upload part for development environment, tho.

Build: do not upload `build.tool` to production S3

---

readthedocs/projects/tasks/builds.py

autoretry_for is broken,
using plain self.retry with a custom exception
works.

Builds: fix retry

---

.readthedocs.yml
docs/user/build-customization.rst
docs/user/build-default-versions.rst
docs/user/builds.rst
docs/user/config-file/v2.rst
docs/user/feature-flags.rst
docs/user/glossary.rst
docs/user/index.rst

The general idea of these changes is to walk the user through the build process
itself while recommending/suggesting how to interact with that step in
particular via the config file to extend its abilities.
Besides, link to a different page where it's explained "how to use hooks" to
customize the normal build process in case the regular build process is not enough.
Decisions made:
- Update "Build process" page (`build.rst`) to describe what happens behind the
scenes in a general way
- Link to config file keys on each step when makes sense a recommendation or a tip
- Remove paragraph and sections that are not interesting for users (Docker
images and where to find them)
- Move "default versions of dependencies" to its own page since they are not one
of the most important things users need …

Docs: feature documentation for `build.jobs`

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/models.py

Mamba can be used via `build.tools.python: mambaforge` now.
This PR removes the `CONDA_USES_MAMBA` feature flag since we already contact
most of the users and opened a PR on their repositories with the config file
required for this change and we also sent an in-site notification to all those
projects still using it.
The message said this feature flag will be removed on May 1st. So, we are all
good to merge and deploy next week (May 3rd).

Mamba: remove CONDA_USES_MAMBA feature flag

---

docs/user/guides/manage-translations-sphinx.rst

locale_dirs defaults to locales but the guide uses locale instead. If only the steps in the guide are followed, sphinx can't find the translations. Let me know if this looks good or you'd rather a different solution

add note on setting locale_dirs

---

readthedocs/search/parsers.py
readthedocs/search/tests/data/sphinx/in/page.html
readthedocs/search/tests/data/sphinx/out/page.json

Our code to detect sphinx domains is a little naive,
sphinx also doesn't make it easy to detect these.
We were removing footnotes in the process of removing domains.
Also de code that extracts domains had a bug,
but looks like we aren't using that as the source of domains, so our domains search wasn't affected by it,
we are using the ones we have in our DB.. so not really sure about why we are parsing them at all :D (maybe this was before we stored the domains in our db?)
found this while testing docutils 18.1

Search: fix parsing of footnotes

---

docs/user/config-file/v2.rst
docs/user/guides/conda.rst
docs/user/tutorial/index.rst

These were introduced in #9138, but for some reason didn't fail..

Fix links in docs from the build page refactor

---

readthedocs/proxito/tests/test_full.py
readthedocs/proxito/views/serve.py

We need to create a transform rule on cloudflare with this dynamic header on the request. I have already created that rule for a test domain.
Closes https://github.com/readthedocs/readthedocs.org/issues/9116

Analytics: skip requests from bots on 404s

---

docs/user/config-file/v2.rst

This doesn't have a good error message, we should at least note it.

Note build.jobs required other keys

---

docs/user/hosting.rst
readthedocs/core/mixins.py
readthedocs/proxito/tests/test_full.py

This uses the TYPE_CDN to enable the CDN for a user.
We'll need to update this to the DB Plans where we want it.
Fixes https://github.com/readthedocs/readthedocs-corporate/issues/1410

Initial test of adding plan to CDN

---

docs/user/config-file/v2.rst
readthedocs/rtd_tests/fixtures/spec/v2/schema.json

Add `ubuntu-22.04` as a valid option when describing `build.os` in the
documentation reference.

Docs: mention `ubuntu-22.04` as a valid option

---

readthedocs/settings/base.py
readthedocs/urls.py
requirements/pip.txt

This will allow us to run migrations,
and configure it initially in production.
FIxes https://github.com/readthedocs/readthedocs-corporate/issues/1329
This initial PR only adds the stripe models to our database. 
[DJStripe](https://dj-stripe.readthedocs.io/) is a Stripe sponsored but independent project since Aug 2020. It works by having local database models that mirror the data in Stripe. When Stripe receives changes (say a customer pays an invoice via ACH), Stripe will send a webhook to our djstripe so our local copy stays up to date. In this way, it will be possible for our application to check whether invoices have been paid or are overdue as easily as querying the database.
* Set the Stripe test key from https://dashboard.stripe.com/test/apikeys into in the `STRIPE_TEST_SECRET_KEY` …

Add a basic djstripe integration

---

readthedocs/doc_builder/environments.py
readthedocs/vcs_support/backends/git.py

This is mainly for our internal commands,
specifically for ls-remote, where a warning was getting in the
output that we parse.
We should use this option in more of our internal commands where we
parse the output.
Ref https://sentry.io/organizations/read-the-docs/issues/3227717706/?project=148442&query=is%3Aunresolved

BuildCommand: add option to merge or not stderr with stdout

---

.codecov.yml

Not a fan of these, review is really hard with these enabled. The docs
aren't super clear, but I'm going off an example from:
https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations-via-yaml
These were enabled in #9119

Disable codecov annotations

---

docs/user/pull-requests.rst

I keep helping users with the support request around webhooks missing
the pull request event, so wanted to clarify a bit here. I also took the
opportunity to add some clearer language to the rest of the page, and
resturcture a few things to improve the information flow.
I also opened #9176 to deal with this in a programmatic way, but figured
we could at least communicate the issue better for now.

Spruce up docs on pull request builds

---

readthedocs/doc_builder/environments.py

Docker returns None if there wasn't anything printed
to stdout/stderr.

Docker environment: check for None on stdout/stderr response

---

readthedocs/proxito/tests/test_full.py
readthedocs/proxito/views/mixins.py
readthedocs/proxito/views/serve.py
readthedocs/settings/base.py
readthedocs/settings/docker_compose.py
readthedocs/storage/__init__.py
readthedocs/storage/s3_storage.py

The class from Django's static files inherits from ManifestFilesMixin,
which doesn't allow serving hashed static files.
We need to add this new setting to our ops repos

Proxied static files: use its own storage class

---

docs/user/build-customization.rst

Expand our build customization page with an example for jsdoc.
See https://test-builds.readthedocs.io/en/jsdoc/ as example of usage.

Docs: jsdoc example using `build.jobs` and `build.tools`

---

docs/user/versions.rst
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_project_views.py

Currently, we are using `Project.default_branch` when it's defined and falling
back to VCS's default branch. However, with the massive rename from `master` to
`main` in GitHub, a lot of project are pointing to the wrong default branch.
Since we are storing the default branch of the GitHub repository under
`RemoteRepository.default_branch` and we are refreshing this list more
frequently now, we can use it before using VCS's default branch as fallback.
Closes #7907

Project: use `RemoteRepository` to define `default_branch`

---

readthedocs/proxito/middleware.py
readthedocs/proxito/views/mixins.py
readthedocs/proxito/views/serve.py

Based on New Relic stats these logs cover 50% of the total data logged.
As we know these features are working fine, we can reduce these logs now and
send them to debug in case we need them again while debugging.
(from New Relic dashboard)

Logging: reduce noise on working features

---

readthedocs/doc_builder/environments.py
readthedocs/rtd_tests/tests/test_doc_building.py

See https://github.com/readthedocs/readthedocs.org/pull/9238#issuecomment-1131621908
A user contacted us reporting this issue already. So, I'm including it for tomorrow's deploy.

Build: solve problem with sanitized output

---

readthedocs/settings/base.py
readthedocs/urls.py

DJStripe is overriding the api version globally,
our app isn't compatible with that version.

Disable djstripe

---

docs/dev/issue-labels.rst
docs/dev/roadmap.rst

We haven't used milestones in a long time. Mention our public roadmap
instead.
Closes #9294

Update mentions of our roadmap to be current

---

.circleci/config.yml

I'm adding this requirement so we don't trigger all the tests concurrently and
also avoid running EmbedAPI tests if there is a failure on any of the other two.
This way we will be saving some resources here.
EmbedAPI tests are _not required_ to merge a PR, so I think it's fine if they
are not always run.

Tests: make `tests-embedapi` require regular `tests` first

---

readthedocs/doc_builder/environments.py

Refs https://github.com/readthedocs/readthedocs.org/issues/9105

Truncate output that we log from commands to 10 lines

---

readthedocs/builds/tests/test_views.py

This is so I can omit the tests without orgs on .com without feeling guilty of not running them

Tests: test build views with organizations

---

docs/user/integrations.rst
readthedocs/api/v2/views/integrations.py
readthedocs/rtd_tests/tests/test_api.py

It feels _weird_ to tell the users: "If the webhook fails it means that it's
configured correctly". So, I removed that paragraph from the documentation and I
implemented an expected response for when GitHub sends us a `ping` event.

Integrations: handle `ping` event on GitHub

---

readthedocs/config/config.py

Use `job_commands` and `commands` to differentiate them.
This bug was producing the last "job command" to be saved as `build.commands`, unfortunately.

Build: avoid overwriting a variable

---

readthedocs/gold/tests/test_webhooks.py
readthedocs/gold/views.py
readthedocs/subscriptions/managers.py
readthedocs/subscriptions/tests/test_models.py

subcription.plan is deprecated in favor of subscription.items,
this is only a problem for subscriptions that have more than one product
(subscriptions.plan will be null for those cases).
On .com have only a couple of subscriptions with multiple plans/products,
the features they provide are being added manually at the moment,
so we don't need to track those in our DB yet.
Also, the whole Plan object is deprecated in favor of the Price object.
Ref https://sentry.io/organizations/read-the-docs/issues/3048896842/?environment=production&project=161479&query=stripe&statsPeriod=14d

Subscriptions: handle subscriptions with multiple products/plans/items

---

.tx/config
dockerfiles/Dockerfile
tasks.py

I tried to integrate these commands into the release/deploy process but it was complicated. The main problem is that we need to install all the Python dependencies since we need to run `django-admin` commands as part of the process. So, instead of dealing with a new Python environment for the release process, we could use the Docker image where all the other Django commands are executed to update the translations.
Once this PR is merged, the process will be:
```
inv docker.translations --pull
inv docker.translations --push
```
I'm going to update the release/deploy script to call these commands _before_ running the other commands.
Requires: https://github.com/readthedocs/common/pull/147
Reference: https://github.com/readthedocs/readthedocs-ops/issues/1195
Reference: …

Translations: integrate Transifex into our Docker tasks

---

dockerfiles/Dockerfile

Dependency of https://github.com/readthedocs/common/pull/144

Add `mc` client to `web` container

---

docs/.rstcheck.cfg
docs/conf.py
docs/dev/contribute.rst
docs/dev/roadmap.rst
docs/user/localization.rst
docs/user/security.rst
docs/user/single_version.rst

Improve scoping of two potentially overlapping Triage sections

---

dockerfiles/Dockerfile
requirements/docker.txt

We have been dealing with a problem with `watchmedo` that restart the process
when it shouldn't be restarted and it doesn't restart it when it should.
I got tired debugging `watchmedo` and I was suggested to give it a try to
`nodemon` because we are already using it in other projects. I'm not super happy
adding a node dependency to the Dockerfile, but I didn't find a better way to do it.
I did some tests with the configuration proposed and it seemed to work pretty
well. I'm sure we will find some edge cases, but we always can tune it a little
more later.
Requires: https://github.com/readthedocs/common/pull/150
Closes https://github.com/readthedocs/readthedocs.org/issues/8802

Local development: use `nodemon` to watch files instead of `watchmedo`

---

readthedocs/embed/tests/data/sphinx/latest/page-sub-title-one.html
readthedocs/embed/tests/data/sphinx/latest/page-subsub-title.html
readthedocs/embed/tests/data/sphinx/latest/page-title-one.html
readthedocs/embed/tests/test_links.py
readthedocs/embed/utils.py
readthedocs/embed/v3/views.py
readthedocs/embed/views.py

When returning the content to be injected in a tooltip, besides cleaning the
`a.href` we are also cleaning the `img.src` to make them absolute and render the
images properly.
See https://github.com/readthedocs/sphinx-hoverxref/issues/200

 EmbedAPI: clean images (`src`) properly from inside a tooltip 

---

readthedocs/core/middleware.py
readthedocs/rtd_tests/tests/test_middleware.py
readthedocs/settings/base.py

Block requests that contain "\x00" characters on their GET attributes. Raise
`SuspiciousOperation` on these cases.
----
Related to https://github.com/readthedocs/readthedocs.org/pull/9349/
Sentry issues: https://sentry.io/organizations/read-the-docs/issues/2941721921/?project=148442

Security: avoid requests with NULL characters (0x00) on GET

---

docker-compose.override.yml
dockerfiles/nginx/proxito.conf.template
dockerfiles/nginx/web.conf.template
docs/dev/install.rst
readthedocs/settings/docker_compose.py

`inv docker.up --ngrok readthedocs.ngrok.io` will allow you to access http://readthedocs.ngrok.io after executing:
```
ngrok http --subdomain=readthedocs --subdomain=test-builds.readthedocs --scheme=http 80
```
This commit renames NGINX config files to convert them into templates, so they
are replaced with the environment variables. See https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119
Closes #9030 
Closes #7982 
Requires https://github.com/readthedocs/common/pull/151

Development: allow to pass `--ngrok` when starting up

---

readthedocs/doc_builder/environments.py
readthedocs/settings/docker_compose.py

When starting up the local development with multiple builders (e.g. `inv
docker.up --scale-build=2`, or more) it's possible to find them collisioning on
the `user_builds/` path when building the same version on each builder.
This happens locally but not on production, because we are running all of them
on the same host machine using the same disk/volume for all of them.
To avoid this collision, this commit adds an extra directory with the `hostname`
of the container to the `DOCROOT` to avoid this collision.

Development: avoid path collision when running multiple builders

---

dockerfiles/Dockerfile

- remove `-s` (silent) because it takes some time to download the file and we
don't know what it's happening; I cancelled the process multiple times due to
this
- use `--disable` instead `-d` since it's more expressive

Development: remove silent and use long attribute name

---

docker-compose.override.yml

I forgot to pass the default value and `inv docker.up` is failing because of this.

Development: default value for environment variable

---

docs/user/faq.rst

We changed how we are installing Read the Docs for development and this is not
valid anymore.

Docs: remove old FAQ entry

---

readthedocs/core/middleware.py
readthedocs/rtd_tests/tests/test_middleware.py

Do not use `raise SuspiciousOperation` here because that ends up into Sentry
marked as an error logged via logger `django.security.SuspiciousOperation`.
I prefer to use regular `log.info` for these situations so they end up in NewRelic
and we can parse them nicely. They are not application errors.

Middleware: use regular `HttpResponse` and log the suspicious operation

---

readthedocs/projects/tasks/builds.py

This code wasn't in an exception,
so we have to pass the exc_info explicitly.

Properly log build exceptions in Celery

---

readthedocs/projects/tests/test_views.py

Test explicitly with/out organizations

---

docs/user/feature-flags.rst

I'm removing these because we don't want users ask for them to use in their
projects. All of the ones removed can be achieved by using `build.jobs.*` config.
Closes #9290

Docs: remove old feature flags

---

readthedocs/payments/utils.py
readthedocs/settings/base.py
readthedocs/urls.py

Reverts https://github.com/readthedocs/readthedocs.org/pull/9282

Enable djstripe again

---

readthedocs/oauth/services/base.py

This will help us a little more when debugging revoked accounts, for example.

Logging: add extra log info for oauth

---

docs/user/flyout-menu.rst

- add the Languages section
- add the Downloads section
- include some HTML comments explaining when the sections are present
Note that this is _not a real example_ since Flask does not have translations
nor downloads, but I don't think that's super important for the purpose of the
example. The most important is the structure of the HTML than the URLs included
on it.
We could use a real example if we find a good one, tho.
> Based on the content of the `restapi/footer.html` file: https://github.com/readthedocs/readthedocs.org/blob/d77cc3a70d32d7621f252ae78bf763d1ee2a34cb/readthedocs/api/v2/templates/restapi/footer.html
Related: https://github.com/readthedocs/readthedocs.org/pull/9357#issuecomment-1171729910

Docs: improve the flyout page to include a full example

---

readthedocs/oauth/services/base.py
readthedocs/oauth/services/bitbucket.py
readthedocs/oauth/services/github.py
readthedocs/oauth/services/gitlab.py
readthedocs/oauth/tasks.py

Small refactor to re-use the same message when communicating to the user. We
always need to tell them to re-connect their account.

OAuth: unify the exception used for the user message

---

readthedocs/oauth/apps.py
readthedocs/oauth/signals.py

Copy the logic from `readthedocs-corporate` to resync `RemoteRepository` each
time the user logs in. We are forcing users to re-login every 30 days minimum.
Related: https://github.com/readthedocs/readthedocs.org/pull/9402

OAuth: re-sync `RemoteRepository` on login

---

readthedocs/settings/base.py

Currently, we have a 30 days expiry time for cookies with "save on every request"
enabled. That means users won't need to re-login if they hit at least one Read
the Docs page every 30 days.
In an attempt to reduce this "infinit session time", I'm disabling the "save on
every request". This way we are forcing the users to re-login every 30 days --no
matter if they hit a Read the Docs page during that time or not.
This will help us to know what are the active users because we will be able to
check `User.last_login` and get reasonable numbers. With the current
configuration, a user that used the platform _today_ could have a pretty old
`last_login` since we are not forcing re-login at all.
Discussion: https://github.com/readthedocs/meta/discussions/31

Sessions: do not save on each request

---

readthedocs/proxito/tests/test_old_redirects.py
readthedocs/proxito/views/mixins.py

We were overriding the query parameters
instead of adding them.
I'm adding the ones from the redirect at the end
(should take precedence on some frameworks).
We could get fancy and replace them instead of adding
them, but it gets tricky when we have an array...
So I think this implementation should be fine.
Closes https://github.com/readthedocs/readthedocs.org/issues/9401

Redirects: merge query params from the redirect and original request

---

docs/user/build-customization.rst

Initial minimal mention to `docsify` as an example in our "Build customization"
section.
Related #9435

Docs: mention `docsify` on "Build customization"

---

docs/user/environment-variables.rst
docs/user/glossary.rst

A user asked about pull request builds and env vars, so figured it's a
good page to update.
* Mention value READTHEDOCS_VERSION for pull request builds
* Convert table view to definition list view
* Use envvar directive to give linkable env vars and env var roles that
resolve from other docs
* Update "slug" definition

Update env var docs

---

docs/user/build-customization.rst

There are multiple ways to install Poetry on Read the Docs and all of them have, at least,
one thing that I don't like. So, I'm recommending using the official one
described as the first option in their own page --which is not perfect, but it's
the official one :)

Docs: `poetry` example on `build.jobs` section

---

docs/user/examples.rst

Not sure how this current example table should look wrt. headline.. proposing to rename it to "List of current example projects", supposing that we might have a list of "outdated" examples or "unmaintained examples".
Before:
After:

Docs: Adds Jupyter Book to examples table

---

.github/workflows/pr-preview-links.yaml

Use https://github.com/readthedocs/readthedocs-preview/ to add a link to Pull
Request's descriptions with the link to the documentation preview.

GitHub Action: add link to Pull Request preview

---

readthedocs/oauth/services/github.py

Trying to find out why we are creating multiple `RemoteRepository` with
different `remote_id` but exact `html_url`/`full_name`.
Reference: https://github.com/readthedocs/readthedocs-corporate/issues/1447

OAuth: add logging for GitHub RemoteRepository

---

readthedocs/proxito/tests/test_old_redirects.py
readthedocs/proxito/views/mixins.py

We were comparing the proxito_path
which doesn't include query parameters with the final URL, which does
include them, causing an infinite redirect.
This same thing could happen if someone writes a redirect to
`http://`, we redirect to the https version, then the redirect will
redirect to the http version again.
----
:books: Documentation preview :books:: https://docs--9463.org.readthedocs.build/en/9463/

Redirects: check only for hostname and path for infinite redirects

---

readthedocs/templates/core/badge_markup.html

Quickfix - don't believe this needs an issue.
Current code is syntactically wrong and raises `WARNING: Explicit markup ends without a blank line; unexpected unindent.`

Fix missing indentation on reStructuredText badge code

---

.github/workflows/pr-preview-links.yaml

Read the Docs repository was renamed from `readthedocs/readthedocs-preview` to `readthedocs/actions/`. Now, the `preview` action is under `readthedocs/actions/preview` and is tagged as `v1`
----
:books: Documentation preview :books:: https://docs--9487.org.readthedocs.build/en/9487/

Use Read the Docs action v1

---

.github/workflows/pr-preview-links.yaml

We have `docs` and `dev` Read the Docs projects tied to this repository.
This PR enables the GitHub Action for `dev`.
----
:books: Documentation preview :books:: https://docs--9491.org.readthedocs.build/en/9491/

Preview: add links to `dev` documentation

---

readthedocs/projects/models.py
readthedocs/proxito/tests/test_middleware.py

The URL was missing in the custom urlconf
----
:books: Documentation preview :books:: https://docs--9496.org.readthedocs.build/en/9496/
----
:books: Documentation preview :books:: https://dev--9496.org.readthedocs.build/en/9496/

Custom urlconf: support serving static files

---

readthedocs/builds/querysets.py

----
:books: Documentation preview :books:: https://docs--9499.org.readthedocs.build/en/9499/
----
:books: Documentation preview :books:: https://dev--9499.org.readthedocs.build/en/9499/

Fix typo in build concurrency logging

---

readthedocs/organizations/forms.py
readthedocs/organizations/tests/test_orgs.py

---
- User's documentation (`docs`): https://docs--9511.org.readthedocs.build/en/9511/
- Developer's documentation (`dev`): https://dev--9511.org.readthedocs.build/en/9511/

Teams: don't send email notification when users adds themselves to a team

---

docs/dev/contribute.rst

fix #9522
---
- User's documentation (`docs`): https://docs--9531.org.readthedocs.build/en/9531/
- Developer's documentation (`dev`): https://dev--9531.org.readthedocs.build/en/9531/

Update Transifex link

---

readthedocs/telemetry/admin.py
readthedocs/telemetry/collectors.py
readthedocs/telemetry/tests/test_collectors.py
requirements/deploy.txt
requirements/docker.txt
requirements/docs.txt
requirements/lint.txt
requirements/pip.in
requirements/pip.txt
requirements/testing.txt

We are saving `packages.pip.user` that are "top level packages" --which does not
mean anything too useful for our purposes.
The original idea was to have `packages.pip.all` that list all the packages
installed in the virtual environment and `packages.pip.user` that list all the
packages installed because the user specified them in the requirements file.
This PR parses all requirements files specified by the user and saves packages'
names and versions into `packages.pip.user`. These ones are pretty useful to
know what projects are specifically defining/pinning a package.
---
- User's documentation (`docs`): https://docs--9514.org.readthedocs.build/en/9514/
- Developer's documentation (`dev`): https://dev--9514.org.readthedocs.build/en/9514/

Telemetry: collect user's requirements

---

requirements/deploy.txt
requirements/docker.txt
requirements/docs.txt
requirements/lint.txt
requirements/pip.in
requirements/pip.txt
requirements/testing.txt

Upgrading to 3.x requires some extra work:
https://django-structlog.readthedocs.io/en/latest/upgrade_guide.html#upgrading-to-3-0
---
- User's documentation (`docs`): https://docs--9535.org.readthedocs.build/en/9535/
- Developer's documentation (`dev`): https://dev--9535.org.readthedocs.build/en/9535/

Dependencies: pin django-structlog to 2.2.1

---

readthedocs/proxito/middleware.py

Doing this PR against rel, since main has changed.
---
- User's documentation (`docs`): https://docs--9540.org.readthedocs.build/en/9540/
- Developer's documentation (`dev`): https://dev--9540.org.readthedocs.build/en/9540/

Proxito: set logging to debug

---

readthedocs/core/unresolver.py

https://github.com/readthedocs/readthedocs.org/pull/9540 was
merged to rel only, I'm porting the changes to main.
---
- User's documentation (`docs`): https://docs--9542.org.readthedocs.build/en/9542/
- Developer's documentation (`dev`): https://dev--9542.org.readthedocs.build/en/9542/

Unresolver: port changes from #9540

---

readthedocs/domains/tests/test_tasks.py

So we can ignore the tests without orgs on .com.
---
- User's documentation (`docs`): https://docs--9541.org.readthedocs.build/en/9541/
- Developer's documentation (`dev`): https://dev--9541.org.readthedocs.build/en/9541/

Domains: test tasks with organizations

---

requirements/deploy.in
requirements/deploy.txt

We should not use the `requirements.txt` file from `readthedocs-ops` and use
`requirements/deploy.in` from this repository instead. This way, we can keep
track of all dependencies via pip-tools and avoid creating conflicting
environments.
---
- User's documentation (`docs`): https://docs--9537.org.readthedocs.build/en/9537/
- Developer's documentation (`dev`): https://dev--9537.org.readthedocs.build/en/9537/

Dependencies: pin deploy dependencies

---

readthedocs/builds/tests/test_trigger_build.py
readthedocs/builds/tests/test_views.py
readthedocs/builds/views.py
readthedocs/core/utils/__init__.py
readthedocs/projects/models.py

> NOTE: I split the work in different commits to make it easier to review.
This PR implements a simple logic to cancel old running builds when a new
build for the same project/version arrives:
1. look for running builds for the same project/version
2. if there are any, it cancels them all one by one via Celery's revoke method
3. trigger a new build for the current commit received
Note that this new feature is behind a feature flag (`CANCEL_OLD_BUILDS`) for
now so we can start testing it on some projects that have shown their interest
on this feature.
The current behavior for `DEDUPLICATE_BUILDS` will be replaced by this new logic
in the future. However, it was not removed in this commit since it's still
useful for projects that won't be using the new feature flag yet.
Closes …

Build: cancel old builds 

---

docs/user/science.rst

This is pending a Front endpoint for actually receiving form data.
---
- User's documentation (`docs`): https://docs--9543.org.readthedocs.build/en/9543/
- Developer's documentation (`dev`): https://dev--9543.org.readthedocs.build/en/9543/

Docs: HTML form for getting in touch with Read the Docs for Science

---

readthedocs/domains/templates/domains/notifications/pending_domain_configuration_site.html

---
- User's documentation (`docs`): https://docs--9560.org.readthedocs.build/en/9560/
- Developer's documentation (`dev`): https://dev--9560.org.readthedocs.build/en/9560/

Templates: minor typo

---

readthedocs/core/signals.py
readthedocs/rtd_tests/tests/test_middleware.py

---
- User's documentation (`docs`): https://docs--9564.org.readthedocs.build/en/9564/
- Developer's documentation (`dev`): https://dev--9564.org.readthedocs.build/en/9564/

Embed API: fix CORS check

---

readthedocs/embed/v3/tests/test_internal_pages.py
readthedocs/embed/v3/views.py

---
- User's documentation (`docs`): https://docs--9565.org.readthedocs.build/en/9565/
- Developer's documentation (`dev`): https://dev--9565.org.readthedocs.build/en/9565/

Embed API: strip leading `/` before joining path

---

dockerfiles/nginx/proxito.conf.template
dockerfiles/nginx/web.conf.template

We were using `logging.driver: none` on Docker Compose's file,
but it stopped working and I was not able to enable it again.
So, for now, I'm just disabling the logging from NGINX itself because they are
too annoying when working locally.
---
- User's documentation (`docs`): https://docs--9569.org.readthedocs.build/en/9569/
- Developer's documentation (`dev`): https://dev--9569.org.readthedocs.build/en/9569/

Development: disable NGINX logs

---

readthedocs/projects/tasks/builds.py

Start collecting how much time (in seconds) it takes to upload all the build
artifacts for each project.
Related #9448
---
- User's documentation (`docs`): https://docs--9568.org.readthedocs.build/en/9568/
- Developer's documentation (`dev`): https://dev--9568.org.readthedocs.build/en/9568/

Logging: log time spent to upload build artifacts

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/tests/test_build_tasks.py

Currently, we are installing an older version of `commonmark` that has some
problems with newer versions of Python. Upgrading it to 0.9.1 seems to solve
this problem.
See #9562 for a detailed explanation of the problem
---
- User's documentation (`docs`): https://docs--9563.org.readthedocs.build/en/9563/
- Developer's documentation (`dev`): https://dev--9563.org.readthedocs.build/en/9563/

Build: upgrade `commonmark` to 0.9.1

---

readthedocs/organizations/models.py
readthedocs/subscriptions/templates/subscriptions/subscription_detail.html
readthedocs/subscriptions/tests/test_views.py
readthedocs/subscriptions/views.py

Ref https://github.com/readthedocs/readthedocs.org/issues/9312
---
- User's documentation (`docs`): https://docs--9550.org.readthedocs.build/en/9550/
- Developer's documentation (`dev`): https://dev--9550.org.readthedocs.build/en/9550/

Subscriptions: use stripe subscriptions to show details

---

docs/user/badges.rst

Clean it up a little and re-order the content.
---
- User's documentation (`docs`): https://docs--9580.org.readthedocs.build/en/9580/
- Developer's documentation (`dev`): https://dev--9580.org.readthedocs.build/en/9580/

Docs: improve "Badges" page

---

docs/user/config-file/v2.rst

- mention `pip` is the recommended way
- mention `setuptools` is deprecated
- remove `setuptools` from the examples in favor of `pip`
Related #8659
---
- User's documentation (`docs`): https://docs--9567.org.readthedocs.build/en/9567/
- Developer's documentation (`dev`): https://dev--9567.org.readthedocs.build/en/9567/

Docs: recommend using `pip` instead of `setuptools`

---

readthedocs/invitations/apps.py
readthedocs/invitations/signals.py
readthedocs/invitations/tests/test_signals.py

GenericForeignKey doesn't have an `on_delete=CASCADE` option,
so we need to do this manually.
---
- User's documentation (`docs`): https://docs--9582.org.readthedocs.build/en/9582/
- Developer's documentation (`dev`): https://dev--9582.org.readthedocs.build/en/9582/

Invitations: delete related invitations when deleting an object

---

readthedocs/telemetry/collectors.py

Save JSON field with all keys as lowercase. Having the data normalized will help us to write simple and fast SQL queries.
---
- User's documentation (`docs`): https://docs--9587.org.readthedocs.build/en/9587/
- Developer's documentation (`dev`): https://dev--9587.org.readthedocs.build/en/9587/

Telemetry: lowercase JSON keys

---

readthedocs/oauth/services/github.py

Add extra key to differentiate when this issue happens on GH repositories that we just track, from GH repositories that are also imported in our platform.
---
- User's documentation (`docs`): https://docs--9590.org.readthedocs.build/en/9590/
- Developer's documentation (`dev`): https://dev--9590.org.readthedocs.build/en/9590/

OAuth: add logging for imported GitHub RemoteRepository

---

readthedocs/oauth/services/base.py

We aren't saving the refresh_token, this is needed to refresh expired tokens, GitLab recently set an expiration time for their tokens https://gitlab.com/gitlab-org/gitlab/-/issues/21745.
Sadly, there is no other way of getting new tokens than users manually reconnecting their accounts.
Closes https://github.com/readthedocs/readthedocs.org/issues/9548

OAuth: save refresh token

---

readthedocs/builds/querysets.py

By using the `project_id` instead the `project_slug`, we remove the `Nested Loop` and use the index `builds_buil_project_fea68c_idx` which is optimized for `(project_id, date)`.
Besides, I changed `__gte` by `__gt`.
Neither of these will gives us a lot of optimization, but since I just saw them, I'm pushing these changes.
New SQL query:
```
docs=> EXPLAIN ANALYZE SELECT *
FROM "builds_build"
INNER JOIN "projects_project"
ON ("builds_build"."project_id" = "projects_project"."id")
WHERE ("builds_build"."date" > '2022-09-14T10:10:35.123817+00:00'::timestamptz AND "projects_project"."id" = '74581')
ORDER BY "builds_build"."date" DESC;
QUERY PLAN
------------------------------------------------------------------------------------------------------------------------------------------------------ …
```

Builds: concurrency small optimization

---

.github/workflows/pip-tools.yaml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

readthedocs/redirects/tests/test_views.py

So tests pass on .com
---
- User's documentation (`docs`): https://docs--9605.org.readthedocs.build/en/9605/
- Developer's documentation (`dev`): https://dev--9605.org.readthedocs.build/en/9605/

Redirects: test with/without organizations

---

.github/workflows/pip-tools.yaml

Creating this PR as per @stsewd's comment https://github.com/readthedocs/readthedocs.org/pull/9597#issuecomment-1251275658. Please review this PR when you get a chance.
Signed-off-by: Ashish Kurmi <akurmi@stepsecurity.io>
---
- User's documentation (`docs`): https://docs--9617.org.readthedocs.build/en/9617/
- Developer's documentation (`dev`): https://dev--9617.org.readthedocs.build/en/9617/

ci: add minimum GitHub at the workflow level for pip-tools.yaml

---

docs/user/guides/authors.rst
docs/user/guides/migrate-rest-myst.md

---
- User's documentation (`docs`): https://docs--9620.org.readthedocs.build/en/9620/
- Developer's documentation (`dev`): https://dev--9620.org.readthedocs.build/en/9620/

Made some small changes to the MyST migration how-to

---

readthedocs/projects/tasks/utils.py

Limit the builds to those that are from the last day (we won't have a build length that's greater than 1 day). This will reduce the rows required to parse since we have an index there. Also, remove the "equal" part from "less than equal" from the query because it makes no sense.
This may help with some of the db problems we were facing in last weeks.
---
- User's documentation (`docs`): https://docs--9634.org.readthedocs.build/en/9634/
- Developer's documentation (`dev`): https://dev--9634.org.readthedocs.build/en/9634/

Query: minor improvement

---

docs/user/guides/authors.rst
docs/user/guides/intersphinx.rst

Uses the method laid out by @evildmp in #9620
Reviewers:
* Do you agree with the altered (Diátaxis'ized) scoping of the article? (title/navigation/intro)
* Any small text tweaks welcome
Side-note: We should track these small changes through an issue and perhaps also a Github tag.
---
- User's documentation (`docs`): https://docs--9622.org.readthedocs.build/en/9622/
- Developer's documentation (`dev`): https://dev--9622.org.readthedocs.build/en/9622/

Docs: Re-scope Intersphinx article as a how-to

---

readthedocs/organizations/querysets.py
readthedocs/settings/base.py
readthedocs/subscriptions/managers.py
readthedocs/subscriptions/signals.py
readthedocs/subscriptions/tests/test_signals.py
readthedocs/subscriptions/tests/test_views.py
readthedocs/subscriptions/utils.py

- Have a setting with the stripe id of the price instead of the slug of the Plan object.
We still need the plan object, but now this is separate from the djstripe subscription object.
- Separate the creation of our subscription object with the creation of a stripe subscription.
- Use the stripe customer object from the db instead of fetching it from stripe
to decide if we should update the customer information
- Allow updating the metadata, this is in case the org changes its slug,
we save the ID too, but is nice to have the slug updated too.
---
- User's documentation (`docs`): https://docs--9640.org.readthedocs.build/en/9640/
- Developer's documentation (`dev`): https://dev--9640.org.readthedocs.build/en/9640/

Subscriptions: use stripe price instead of relying on plan object

---

dockerfiles/settings/proxito.py
readthedocs/settings/base.py
readthedocs/settings/dev.py
readthedocs/settings/docker_compose.py
readthedocs/urls.py

Small refactor to allow the `django-debug-toolbar` on:
- Docker development instance
- web-extra instance
This will help us to debug some SQL queries and others in production using a private and protected instance.
---
- User's documentation (`docs`): https://docs--9641.org.readthedocs.build/en/9641/
- Developer's documentation (`dev`): https://dev--9641.org.readthedocs.build/en/9641/

Settings: enable `django-debug-toolbar` when Django Admin is enabled

---

readthedocs/templates/404.html

Addresses #2551 with a very simple improvement. The 404 page context is still unaware of what project it belongs to, that should follow in a different update.
TODO:
---
- User's documentation (`docs`): https://docs--9656.org.readthedocs.build/en/9656/
- Developer's documentation (`dev`): https://dev--9656.org.readthedocs.build/en/9656/

Adds more basic info to the default 404 page

---

readthedocs/subscriptions/apps.py
readthedocs/subscriptions/event_handlers.py
readthedocs/subscriptions/managers.py
readthedocs/subscriptions/tests/test_event_handlers.py
readthedocs/subscriptions/tests/test_models.py

Instead of using our own stripe webhook handler, just use djstripe.
All this logic comes from .com, but now instead of dealing with a stripe event, we have a djstripe event object and have access to all djstripe models.
I have tested this locally with stripe in testing mode.
---
- User's documentation (`docs`): https://docs--9651.org.readthedocs.build/en/9651/
- Developer's documentation (`dev`): https://dev--9651.org.readthedocs.build/en/9651/

Subscriptions: Use djstripe event handlers

---

readthedocs/templates/builds/build_detail.html

---
- User's documentation (`docs`): https://docs--9662.org.readthedocs.build/en/9662/
- Developer's documentation (`dev`): https://dev--9662.org.readthedocs.build/en/9662/

Template: fix build details page link

---

readthedocs/telemetry/collectors.py

Pretty simple implementation to track Sphinx's extensions and theme. This is not the best implementation, but I think it could be good as a first start.
The new `doctool` key added will have this shape:
```
"doctool": {
"extensions": [
"readthedocs_ext.readthedocs",
"notfound.extension",
"autoapi.extension",
"sphinx_tabs.tabs",
"sphinx-prompt",
"sphinxemoji.sphinxemoji"
],
"name": "sphinx",
"theme": "sphinx_rtd_theme"
},
```
Closes #9627
Requires: https://github.com/readthedocs/readthedocs-sphinx-ext/pull/117
---
- User's documentation (`docs`): https://docs--9639.org.readthedocs.build/en/9639/
- Developer's documentation (`dev`): https://dev--9639.org.readthedocs.build/en/9639/

Telemetry: track Sphinx `extensions` and `html_theme` variables

---

readthedocs/builds/models.py
readthedocs/projects/models.py
readthedocs/rtd_tests/tests/test_version.py

I found some of these methods confusing when writing new code. One of them seemed to do what I wanted, but it was using old tricks (find a `conf.py` instead of using `sphinx.configuration` key from the config file).
I think it's a good idea to remove them to avoid mistakes in the future. It seems they are not used anywhere and it's safe to remove them.
---
- User's documentation (`docs`): https://docs--9659.org.readthedocs.build/en/9659/
- Developer's documentation (`dev`): https://dev--9659.org.readthedocs.build/en/9659/

Clean up some old code that's not used

---

readthedocs/urls.py

The current re_path is valid, but looks werid.
---
- User's documentation (`docs`): https://docs--9646.org.readthedocs.build/en/9646/
- Developer's documentation (`dev`): https://dev--9646.org.readthedocs.build/en/9646/

Search: use path for API URL

---

docs/user/science.rst

Commented out because of form spam, can be re-introduced once the form is relevant for some event.
---
- User's documentation (`docs`): https://docs--9674.org.readthedocs.build/en/9674/
- Developer's documentation (`dev`): https://dev--9674.org.readthedocs.build/en/9674/

Docs: Comment out the science contact form

---

docs/conf.py

Writing "2010" in the Copyright notice gives a wrong impression that whatever documentation article is displayed hasn't been updated since. And many of them aren't even written in 2010, so it's also factually very wrong :)

Docs: Use current year instead of hard-coded 2010

---

readthedocs/telemetry/collectors.py

Avoid failing the collection of data if the project does not define a `conf.py` or doesn't even have one.
---
- User's documentation (`docs`): https://docs--9695.org.readthedocs.build/en/9695/
- Developer's documentation (`dev`): https://dev--9695.org.readthedocs.build/en/9695/

Telemetry: not collect Sphinx data if there is no `conf.py`

---

.github/workflows/pr-preview-links.yaml

Instead of adding a preview link for every single PR opened, the action will only be called if there is a modification in the `docs/` direction. This is only to avoid the a little the noise when there is no documentation changes.
---
- User's documentation (`docs`): https://docs--9696.org.readthedocs.build/en/9696/
- Developer's documentation (`dev`): https://dev--9696.org.readthedocs.build/en/9696/

GHA: only run the preview links action on `docs/` path

---

readthedocs/proxito/tests/test_full.py
readthedocs/proxito/urls.py
readthedocs/proxito/views/serve.py

Currently any invalid path will raise a `ParamValidationError` error (this is an error from boto3).
And currently we also accept empty paths
https://github.com/readthedocs/readthedocs.org/blob/a615beba5028702646672a7b0a62d46507c22545/readthedocs/constants.py#L13
Instead of using a re_path, use just a path with a `path` route pattern.
---
- User's documentation (`docs`): https://docs--9694.org.readthedocs.build/en/9694/
- Developer's documentation (`dev`): https://dev--9694.org.readthedocs.build/en/9694/

Static files: don't 500 on invalid paths

---

readthedocs/settings/base.py

This commit matches and requires
https://github.com/readthedocs/readthedocs-docker-images/pull/187/
It upgrades all the `build.tools` versions to their latest. Also, since Python 3.11 was released yesterday, now the `build.tools.python: "3"` will point to 3.11.
---
- User's documentation (`docs`): https://docs--9692.org.readthedocs.build/en/9692/
- Developer's documentation (`dev`): https://dev--9692.org.readthedocs.build/en/9692/

Build tools: upgrade all versions

---

readthedocs/subscriptions/managers.py
readthedocs/subscriptions/tests/test_event_handlers.py

Setting the ID to none, may break our subscription update code, since we won't have that ID in our DB anymore.
https://github.com/readthedocs/readthedocs.org/blob/a615beba5028702646672a7b0a62d46507c22545/readthedocs/subscriptions/event_handlers.py#L79-L86
This was being used as a way to identify when to allow users to buy a subscription, but now we are just checking if the status is "canceled".
---
- User's documentation (`docs`): https://docs--9693.org.readthedocs.build/en/9693/
- Developer's documentation (`dev`): https://dev--9693.org.readthedocs.build/en/9693/

Subscriptions: don't remove stripe id on canceled subscriptions

---

readthedocs/doc_builder/python_environments.py
readthedocs/projects/tests/test_build_tasks.py

With this change, builds will use version `2.2.x` which has a new feature to store extra data in telemetry database.

Build: bump `readthedocs-sphinx-ext` to `<2.3`

---

readthedocs/core/unresolver.py
readthedocs/rtd_tests/tests/test_unresolver.py

I'm passing the external version slug to the _unresolve_path method, so we can query the version from inside that function.
Also changed the prefetch_related calls to select_related, since that's what we want (prefetch_related will do a separate query instead of just one).

Unresolver: support external versions for single version projects

---

SECURITY.md
docs/user/security.rst

- Explicitly mention the supported versions that will receive security updates.
- Added a note about bug bounties (inspired by https://www.python.org/dev/security/).
- Link to our advisories instead of duplicating the same information (we could even migrate our past reports there)
- Add a SECURITY.md file so GitHub links to it nicely.
---
- User's documentation (`docs`): https://docs--9723.org.readthedocs.build/en/9723/
- Developer's documentation (`dev`): https://dev--9723.org.readthedocs.build/en/9723/

Update security policy

---

docs/user/build-customization.rst
docs/user/builds.rst

- Move the explanation about the "Cancelling builds" feature to the "Builds" page
- Keep the examples (How-To) for "Cancel a build" into the "Build customization" page
---
- User's documentation (`docs`): https://docs--9717.org.readthedocs.build/en/9717/
- Developer's documentation (`dev`): https://dev--9717.org.readthedocs.build/en/9717/

Docs: refactor "skipping a build" section

---

docs/user/build-customization.rst
docs/user/builds.rst
readthedocs/doc_builder/constants.py
readthedocs/doc_builder/environments.py
readthedocs/doc_builder/exceptions.py
readthedocs/projects/tasks/builds.py

Define a particular exit code (439) to skip a build.
If any of the commands returns this exit code, the build will be cancelled automatically and won't run any of the following commands. When this happens, the build will be marked as `cancelled` and no email/webhook notifications will be sent.
Why 439 was chosen for the exit code?
It's the word "skip" encoded in ASCII. Then it's taken the 256 modulo of it because the Unix implementation does this automatically for exit codes greater than 255
```
>>> sum(list('skip'.encode('ascii')))
439
>>> 439 % 256
183
```
----
I opened this PR in draft because there are some things to discuss and decide yet. It's just a proof of concept for now.
- Do we need a new `skipped` status?
- Should we send "build status" notification as `success`?
- Is it …

Build: skip build based on commands' exit codes

---

readthedocs/domains/querysets.py
readthedocs/domains/tests/test_querysets.py

This is going to be used in rtd-ext
to remove expired domains from CF.
---
- User's documentation (`docs`): https://docs--9667.org.readthedocs.build/en/9667/
- Developer's documentation (`dev`): https://dev--9667.org.readthedocs.build/en/9667/

Domains: add expired queryset

---

docs/user/custom-domains.rst

Closes #9729
cc @tudortimi
---
- User's documentation (`docs`): https://docs--9733.org.readthedocs.build/en/9733/
- Developer's documentation (`dev`): https://dev--9733.org.readthedocs.build/en/9733/

Docs: add an example for custom domain input

---

readthedocs/telemetry/collectors.py

I made a mistake in
https://github.com/readthedocs/readthedocs.org/commit/383e7b5036195fcc07568328b2a7d89c32a6d940#diff-fa7bf6eca268be44eaac66b32c9aacdb2b99bbe50f2aebfbdfda8f7927203d39L156 because I inverted the logic and start using `--not-required` allways, when it should not be used at all 🤦
This commit fixes that issue.
A `test-builds` **without using** `--not-required` shows all the packages
```
(Pdb++) self.run(*['python', '-m', 'pip', 'list', '--pre', '--local', '--format', 'json'])
(0, '[{"name": "alabaster", "version": "0.7.12"}, {"name": "Babel", "version":
"2.11.0"}, {"name": "certifi", "version": "2022.9.24"}, {"name":
"charset-normalizer", "version": "2.1.1"}, {"name": "commonmark", "version":
"0.9.1"}, {"name": "docutils", "version": "0.17.1"}, {"name": "idna", "version": …
```

Telemetry: include all the PyPI packages

---

readthedocs/projects/admin.py

closes https://github.com/readthedocs/readthedocs.org/issues/9687
---
- User's documentation (`docs`): https://docs--9697.org.readthedocs.build/en/9697/
- Developer's documentation (`dev`): https://dev--9697.org.readthedocs.build/en/9697/

Admin: Make `VersionInline` Read-only

---

readthedocs/search/parsers.py
readthedocs/search/tests/data/sphinx/out/page.json

We were removing all dl lists that were inside a domain in order to remove nested domains, but in doing so we were removing parameters (they are inside a dl list!).
Instead, let's reuse the method to detect sphinx domains.

Search: fix parsing of parameters inside sphinx domains

---

.readthedocs.yml
docs/user/build-customization.rst

Use the new feature to cancel builds if there are not documentation changes

Docs: cancel PR builds if there is no documentation changes

---

docs/user/build-customization.rst

Updating instructions with the [latest from the offiical docs](https://python-poetry.org/docs/#installing-with-the-official-installer).
> The previous get-poetry.py and install-poetry.py installers are deprecated.
Fix #9740 
---
- User's documentation (`docs`): https://docs--9743.org.readthedocs.build/en/9743/
- Developer's documentation (`dev`): https://dev--9743.org.readthedocs.build/en/9743/

Docs: update instructions to install deps with Poetry

---

docs/conf.py
docs/user/commercial/organizations.rst
docs/user/commercial/privacy-level.rst
docs/user/commercial/sharing.rst
docs/user/commercial/single-sign-on.rst
docs/user/shared/admonition-rtd-business.rst

In preparation for Diátaxis, we want an easy way to mix Explanation, How-tos and References so "Read the Docs for Business" features can be listed next to all other features, rather than a separate parallel structure.
The proposal here is quite simple:
* Use a DRY pattern for including the same admonition in all current RTD4B features
* We can always adjust the text later, once we see it in different contexts. I don't think we need to spend time on that now, as we cannot see how/where the admonition box will appear. But I could add an action item for Iteration 4.
Related: #9745 
---
- User's documentation (`docs`): https://docs--9754.org.readthedocs.build/en/9754/
- Developer's documentation (`dev`): https://dev--9754.org.readthedocs.build/en/9754/

Docs: Adding a pattern for reusing "Only on Read the Docs for Business" admonition (Diátaxis refactor)

---

docs/user/index.rst

Notice that this PR targets `diataxis/main`
Refs #9745
I opted to having all 4 categories at the top. That makes it easy to observe the end-result as well as grasping how much work is left (i.e. all the sections that are still left in the old categories below).

Docs: 4 diátaxis categories at the top of the navigation sidebar (Diátaxis iteration 0)

---

readthedocs/core/finders.py
readthedocs/settings/base.py

This application needs to be installed if we want to enable it later in the `web-extra` instance. Otherwise, it fails due the static files are not in the manifest.
By installing it by default, `collectstatic` will find this application and copy these static files and add them in the manifest.
Note this application will only be used if `SHOW_DEBUG_TOOLBAR=True`, which is `False` by default.

Admin: install `debug_toolbar`

---

docs/user/index.rst

Use a hidded `a` to validate the Mastodon profile.
---
- User's documentation (`docs`): https://docs--9764.org.readthedocs.build/en/9764/
- Developer's documentation (`dev`): https://dev--9764.org.readthedocs.build/en/9764/

Docs: validate Mastodon link

---

docs/dev/search-integration.rst
docs/user/index.rst

---
- User's documentation (`docs`): https://docs--9765.org.readthedocs.build/en/9765/
- Developer's documentation (`dev`): https://dev--9765.org.readthedocs.build/en/9765/

Docs: fix minor issues

---

.env
docs/dev/install.rst

This PR adds an important line in our `.env`.
The issue with Docker Compose v2 is that they decided to use `-` as a separator instead if `_`. So for instance, images are then tagged as `community-server:latest` and not `community_server:latest` etc. `COMPOSE_COMPATIBILITY=true` fixes this.
~I wrote something in the documentation about this, and I also added a troubleshooting section on Docker networking based on fresh experience.~ Removed again due to push-back.
In the future, once everyone on the team is using Docker Compose v2, we could remove the option and replace underscores with dashes.
---
- User's documentation (`docs`): https://docs--9759.org.readthedocs.build/en/9759/
- Developer's documentation (`dev`): …

Docker Compose v2 compatibility

---

docs/user/abandoned-projects.rst

There has been a lot of different suggestions up, but I think this one is the easiest to process for now.
---
- User's documentation (`docs`): https://docs--9783.org.readthedocs.build/en/9783/
- Developer's documentation (`dev`): https://dev--9783.org.readthedocs.build/en/9783/

Abandoned Projects policy: Relax reachability requirement

---

docs/user/index.rst

This is one of the easier refactors. I haven't seen any suggestions for a new title, and I think this is a good "Explanation" title.
Refs: #9746
---
- User's documentation (`docs`): https://docs--9784.org.readthedocs.build/en/9784/
- Developer's documentation (`dev`): https://dev--9784.org.readthedocs.build/en/9784/

Docs: Move "Choosing between our two platforms" to Explanation (Diátaxis)

---

.circleci/config.yml
tox.embedapi.ini
tox.ini

Since we haven't pinned tox, we will have to make adjustments quite quickly when they introduce breaking changes.
See:
https://tox.wiki/en/latest/faq.html#breaking-changes-in-tox-4
Because it took a long time to get build outputs, I did a small optimization of the order of pipeline jobs so all the node-based stuff is pushed to the end.

Fix Circle CI builds: Tox 4 compatibility, add external commands to allowlist

---

.circleci/config.yml

Adds an -f switch to force resetting the branch in cases where Circle CI had already fetched it.
I'm still not sure about the exact mechanisms of the built-in Circle CI `checkout` step. At first I introduced this in a PR where `main` wasn't found as a reference - and it worked, the branch was added and pre-commit could compare changes in the PR to `main`.
But then in a later PR after this change, I got errors when `main` already exists.
```
git branch --track main origin/main
fatal: a branch named 'main' already exists
```
https://app.circleci.com/pipelines/github/readthedocs/readthedocs.org/6345/workflows/892de4a3-b7de-4f65-80c2-d7f4643d81f3/jobs/15361
I think the `-f` switch should do the work:
```
-f, --force
Reset <branchname> to <startpoint>, even if <branchname> exists already. …
```

CI builds: Checkout main branch in a robust way

---

tox.ini

All our builds started breaking again. I hope Tox stops behaving like this.
We should start managing Tox in a `requirements_tox.txt` so version specifications can be managed instead of putting version info in Circle CI config.
Tox 4.0.6 breaks for a good reason! It breaks when a behavior changed in Tox 4 (only comma-separated lists, whitespaces not allowed) and old values of `passenv` were silently parsed wrongly.
Ref: https://github.com/tox-dev/tox/issues/2658

Fix silent, then loud failure after Tox 4 upgrade

---

docs/user/index.rst

---
- User's documentation (`docs`): https://docs--9814.org.readthedocs.build/en/9814/
- Developer's documentation (`dev`): https://dev--9814.org.readthedocs.build/en/9814/

Add link to the build notifications guide

---

docs/conf.py
docs/user/build-customization.rst

Define timeout, retries and workers.
---
- User's documentation (`docs`): https://docs--9810.org.readthedocs.build/en/9810/
- Developer's documentation (`dev`): https://dev--9810.org.readthedocs.build/en/9810/

Docs: configure linkcheck

---

docs/dev/tests.rst

---
- User's documentation (`docs`): https://docs--9817.org.readthedocs.build/en/9817/
- Developer's documentation (`dev`): https://dev--9817.org.readthedocs.build/en/9817/

Add subset of tests to testing docs

---

docs/dev/docs.rst
docs/dev/index.rst
docs/dev/style-guide.rst

This is the start of a larger style guide that we should have,
trying to capture places where we make decisions.
Lots of inspiration possible here: https://docs.pylonsproject.org/projects/docs-style-guide/
Closes readthedocs/meta#65
---
- User's documentation (`docs`): https://docs--9813.org.readthedocs.build/en/9813/
- Developer's documentation (`dev`): https://dev--9813.org.readthedocs.build/en/9813/

Break documentation style guide out into its own file

---

readthedocs/api/v2/serializers.py

Small hack to trim/normalize command paths when displaying them to the user under the build detail's page.
This is a simple hack and there are more we can do here. Probably, there are some edge cases this is not catching. However, the worst it can happens is the path not being trimmed.

Build details page: normalize/trim command paths

---

.circleci/config.yml

Not needed unless non-main branch default!
Supersedes #9825

Removes fetching of main branch

---

readthedocs/search/api/v3/views.py

The description from https://docs.readthedocs.io/_/api/v3/search/ doesn't match the one from https://readthedocs.org/api/v3/search/ because we are subclassing the view.

Search API V3: fix view description

---

readthedocs/rtd_tests/tests/test_api.py

This commit contains the test that was missing for my other PR: https://github.com/readthedocs/readthedocs.org/pull/9815
The test checks the commands' PATH are trimmed before being returned by the API.

Test: path is trimmed when returned by the API

---

docs/user/config-file/v2.rst
readthedocs/rtd_tests/fixtures/spec/v2/schema.json

- Add build.commands
- Mark deprecated attributes as such
- Mention a little more about how the schema can be used :)
If you are using https://github.com/redhat-developer/vscode-yaml, you should be able to preview this by adding this modeline at the top of your rtd.yaml file
```yaml
```
Closes https://github.com/readthedocs/readthedocs.org/issues/9822
---
- User's documentation (`docs`): https://docs--9830.org.readthedocs.build/en/9830/
- Developer's documentation (`dev`): https://dev--9830.org.readthedocs.build/en/9830/

Config file: update JSON schema

---

docs/user/index.rst
docs/user/science.rst

Refs: https://github.com/readthedocs/readthedocs.org/issues/9746
This raises two questions:
1) Can we limit the amount of changes to this?
2) Are there any follow-up actions that we can already express or is it better to just plan for a revisit
(The reason that I wanted to minimize this effort, is in anticipation of some sort of separation between what lives on https://about.readthedocs.com/ and what lives in the documentation)
---
- User's documentation (`docs`): https://docs--9832.org.readthedocs.build/en/9832/
- Developer's documentation (`dev`): https://dev--9832.org.readthedocs.build/en/9832/

Docs: Relabel the "Science" page as Explanation

---

docs/user/index.rst
docs/user/single_version.rst

This ~is~ was a WIP.
Refs: https://github.com/readthedocs/readthedocs.org/issues/9746
---
- User's documentation (`docs`): https://docs--9835.org.readthedocs.build/en/9835/
- Developer's documentation (`dev`): https://dev--9835.org.readthedocs.build/en/9835/

Docs: Relabel "Single version documentation" documentation from feature to explanation (Diátaxis)

---

readthedocs/invitations/models.py

ContentType.name is the human-readable name,
this is taken from the label, which in some models is a translatable string (https://github.com/readthedocs/readthedocs.org/blob/a00eff14643eeb1f114f6bcc6d71510e5c3d51fd/readthedocs/projects/models.py#L468-L468).
What we actually want is ContentType.model
https://docs.djangoproject.com/en/4.1/ref/contrib/contenttypes/#django.contrib.contenttypes.models.ContentType, that is the plain model name in lowercase.

Invitations: fix model name (object_type)

---

readthedocs/api/v2/serializers.py
readthedocs/api/v2/views/model_views.py

Continuation of the work done in
#9815 that didn't work as we
expected.
We weren't saving the commands properly when hitting the API since
`serializers.SerializerMethodField` is a read-only field. This commit fixes this
problem by using a different Serializer depending if it's a GET request or not,
and if it's made by an Admin or not.
It overrides the method `BuildViewSet.get_serializer_class` to manage these
different cases and return the proper serializer.
Done on top of #9827 to be sure the
tests for saving commands are passing.
Closes #9833

Build details page: normalize/trim command paths (second attempt)

---

readthedocs/api/v2/serializers.py
readthedocs/api/v2/views/model_views.py
readthedocs/rtd_tests/tests/test_api.py

I bug was introduced and our test didn't catch it because we weren't checking if the command was being saved.

API V2: test that command is actually saved

---

docs/user/api/v3.rst
readthedocs/api/v3/filters.py
readthedocs/api/v3/tests/responses/projects-list-empty.json
readthedocs/api/v3/tests/test_projects.py

I am trying to use the project API for some search and dropdown filters,
and while I can filter the local results, it's much nicer to use the API
filter for this.
This adds an icontains filter field for project name and slug, and
hopefully some accurate tests.
---
- User's documentation (`docs`): https://docs--9843.org.readthedocs.build/en/9843/
- Developer's documentation (`dev`): https://dev--9843.org.readthedocs.build/en/9843/

API: add project name/slug filters

---

docs/user/guides/git-integrations.rst

I don't see another way of fixing this because of https://github.com/readthedocs/readthedocs.org/issues/9816#issuecomment-1369913128
I'll open an issue to support referencing tabs (i.e. getting rid of the source of the ePub warnings)
---
- User's documentation (`docs`): https://docs--9866.org.readthedocs.build/en/9866/
- Developer's documentation (`dev`): https://dev--9866.org.readthedocs.build/en/9866/

Move reference labels outside of tabs

---

readthedocs/templates/base.html

I guess this is related to the jquery update from #9861, or maybe this line wasn't working and we were relying in something else?
Not sure why I didn't notice this before,
maybe my browser cache :(
Ref https://github.com/readthedocs/readthedocs.org/pull/9861

Explicitly set JQuery globals on main site

---

readthedocs/embed/v3/tests/test_internal_pages.py
readthedocs/embed/v3/views.py
readthedocs/embed/views.py

We can use encoded URLs (e.g. with %20 for white spaces) for external requests since they are valid URLs. However, when it's internal and we get it from the storage, we have to convert them to regular characters (white spaces, in this example).
We use `urllib.parse.unquote` for this before passing the filename to the S3 backend storage.
Closes #8301

EmbedAPI: decode filepath before open them from S3 storage

---

docs/user/build-customization.rst

Move `poetry install` from `post_create_environment` to `post_install`.
This ensures the Sphinx version installed from `poetry.lock` is used to build the docs, rather than the default version of Sphinx.
Closes: #9869
---
- User's documentation (`docs`): https://docs--9879.org.readthedocs.build/en/9879/
- Developer's documentation (`dev`): https://dev--9879.org.readthedocs.build/en/9879/

Docs: update build customization Poetry example

---

docs/user/build-customization.rst

Correct block type to avoid failing test such as in #9879:
```
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1
docs/user/build-customization.rst:122: code block parse error Cannot parse: 1:0: >>> sum(list('skip'.encode('ascii')))
pre-commit: exit 1 (27.71 seconds) /home/circleci/project> pre-commit run --from-ref main --to-ref HEAD pid=311
pre-commit: FAIL code 1 (32.93=setup[5.22]+cmd[27.71] seconds)
evaluation failed :( (33.28 seconds)
Exited with code exit status 1
```
---
- User's documentation (`docs`): https://docs--9880.org.readthedocs.build/en/9880/
- Developer's documentation (`dev`): https://dev--9880.org.readthedocs.build/en/9880/

Docs: correct Python console block type

---

readthedocs/projects/static-src/projects/css/admin.less
readthedocs/projects/static/projects/css/admin.css
readthedocs/templates/socialaccount/connections.html

Related to additions in #9834 
Also related: The terminology of "Git provider" to be discussed in #9840 
Example:

UI updates to Connected Accounts

---

docs/user/tutorial/index.rst

Per @humitos instructions I have removed the mention "of some required dependencies in docs/requirements.txt" from the getting started tutorial.
The reason being "it's too deep (and advanced) topic than the tutorial was thought for"
fixes #9873
---
- User's documentation (`docs`): https://docs--9902.org.readthedocs.build/en/9902/
- Developer's documentation (`dev`): https://dev--9902.org.readthedocs.build/en/9902/

rm mention of docs/requirements.txt from tutorial

---

readthedocs/templates/account/email/account_already_exists_message.html
readthedocs/templates/account/email/account_already_exists_message.txt
readthedocs/templates/account/email/account_already_exists_subject.txt
readthedocs/templates/account/email/unknown_account_message.html
readthedocs/templates/account/email/unknown_account_message.txt
readthedocs/templates/account/email/unknown_account_subject.txt

This is so we are at pair with
https://github.com/pennersr/django-allauth/tree/master/allauth/templates/account/email.
And we are requiring html versions of these templates in our adapter https://github.com/readthedocs/readthedocs.org/blob/5252be35fb12c4222f56db356af6e92be2fd04c6/readthedocs/core/adapters.py#L50-L50
We should be safe to update django-allauth after this.

Add new allauth templates

---

docs/user/faq.rst
docs/user/index.rst

Refs: #9746 
The FAQ doesn't fit that well in Diátaxis in the sense that it's a very unstructured way of delivering content. I also invites "dumping" of documentation, which is a bit of an anti-pattern. So I'll consider it "deprecated" but that we shouldn't delete it before the decision is very easy to take.
Placement as How-To: I think it's very much a how-to, since an FAQ requires the user to know the problem they want to solve and need an instruction on how to solve it. Most likely, it's because they follow an internal link.
I'll clean it up with the following pattern:
* Frequently asked questions should each consist of: A question, an answer, a reference to another documentation page
We could keep the FAQ and strip out all its instructions to actual locations in the docs (replacing …

Docs: Move and update FAQ (Diátaxis)
