readthedocs/rtd_tests/tests/test_middleware.py, readthedocs/settings/base.py
Previously, we were allowing to pass cookies in cross-site requests (because our sustainability API required it), but due to this, we are doing some checks to guarantee that these requests weren't accessing to private resources.
These checks are getting a little complex (they are at the middleware level), since there are several things that influence if the resource is public or private.
This doesn't represent a breaking change since:
- The endpoints listed bellow allow to access public resources only.
- There is no need to pass cookies for accessing public resources.
- Cookies were only allowed to be passed in cross site requests on .org.
- For .com our session cookies are set to `Lax`, so they were never included in cross-site requests.
This could break if users were passing the …
=> CORS: don't allow to pass credentials by default

docs/user/index.rst, docs/user/reference/features.rst, docs/user/server-side-search/api.rst, docs/user/server-side-search/index.rst, docs/user/server-side-search/syntax.rst
Relabling these articles. We should separate references and explanations and not gather them under domain-specific subtopics.
Aside from that, I kept changes minimal here as the articles went under a recent review.
Open question: Is "Server Side Search" to be understood as a proper noun? Or should we just say "server-side search"?
I removed the local TOCs as we haven been using that in many other places.
Refs: #9746 
---
- User's documentation (`docs`): https://docs--9897.org.readthedocs.build/en/9897/
- Developer's documentation (`dev`): https://dev--9897.org.readthedocs.build/en/9897/
=> Docs: Relabel Server Side Search

readthedocs/builds/storage.py, readthedocs/rtd_tests/tests/test_build_storage.py
Extra checks for symlinks and making sure the
directory is within the docroot directory.
THIS DOESN'T PRESENT A SECURITY VULNERABILITY FOR RTD.ORG NOR RTD.COM, since while fixing https://github.com/readthedocs/readthedocs.org/security/advisories/GHSA-368m-86q9-m99w we added checks to make sure we didn't read files outside the docroot, this limiting the attack surface, and we run one build at a time, this means that only files from the current build are exposed in the docroot directory.
=> Build storage: add additional checks for the source dir

readthedocs/builds/querysets.py
We weren't filtering by dat _all the conditions_, only together with the `project_id`. However, when translations where involved builds where not restricted to be the latest ones (starting 5hs ago).
I found this by taking a look at the raw SQL query in New Relic:
```sql
SELECT COUNT(*) FROM (
SELECT DISTINCT "builds_build"."id" AS Col1,
"builds_build"."project_id" AS Col2, "builds_build"."version_id" AS Col3,
"builds_build"."type" AS Col4, "builds_build"."state" AS Col5,
"builds_build"."status" AS Col6, "builds_build"."date" AS Col7,
"builds_build"."success" AS Col8, "builds_build"."setup" AS Col9,
"builds_build"."setup_error" AS Col10, "builds_build"."output" AS Col11,
"builds_build"."error" AS Col12, "builds_build"."exit_code" AS Col13,
"builds_build"."commit" AS Col14, …
```
=> Build: improve `concurent` queryset

readthedocs/settings/base.py, readthedocs/settings/dev.py, readthedocs/settings/docker_compose.py
We are not using them for anything,
so we are just ignoring them and not saving them.
This could help to debug the OOM received by Redis due to a bunch of: `b'5d9d02c5-02bd-3fdf-944a-7b279b8ed2cf.reply.celery.pidbox'` keys.
Related to https://github.com/readthedocs/readthedocs.org/issues/8941
=> Celery: ignore task results

docs/user/gsoc.rst, docs/user/index.rst
We can also remove it completely, but this also works.
Refs: #9746 
---
- User's documentation (`docs`): https://docs--9949.org.readthedocs.build/en/9949/
- Developer's documentation (`dev`): https://dev--9949.org.readthedocs.build/en/9949/
=> Docs: Make the GSOC page orphaned (Diátaxis)

docs/user/badges.rst, docs/user/index.rst, docs/user/reference/features.rst
* Add a syntax section
* Badges for private projects
Refs: #9746
=> Docs: Relabel badges as feature reference (Diátaxis)

readthedocs/storage/rclone.py
Related https://github.com/readthedocs/readthedocs.org/issues/9947
=> Build: rclone retries when uploading artifacts

tox.ini
Referencing troubleshooting in https://github.com/readthedocs/readthedocs.org/pull/9411#issuecomment-1381366598, I think it would be really nice to see what pre-commit detects.
Docs: https://pre-commit.com/#pre-commit-run
=> CI: Add option `--show-diff-on-failure`  to pre-commit

readthedocs/doc_builder/backends/mkdocs.py, readthedocs/projects/tests/test_build_tasks.py
After performing the standardization of output directories, we broke MkDocs builders for those projects that don't have the config file in the root of the repository.
This happens because MkDocs consider the output directory relative to where the `mkdocs.yml` file is, instead from where the command is executed.
This commit solves this problem by calculating the `--site-dir` relative to where `--config-file` is.
Closes #9935
=> MkDocs builder: use proper relative path for `--site-dir`

docs/user/commercial/subscriptions.rst
This basically just shows people how to manage and cancel their subscription,
so hopefully they don't have to email us for this.
I did this outside of the `diataxis` branch because I want to get it merged & shipped here soon if possible. I would like to add a screenshot, but didn't have a test accnt handy for it. 
Fixes https://github.com/readthedocs/readthedocs.org/issues/9520
---
- User's documentation (`docs`): https://docs--9963.org.readthedocs.build/en/9963/
- Developer's documentation (`dev`): https://dev--9963.org.readthedocs.build/en/9963/
=> Add documentation page on Commercial subscriptions

readthedocs/builds/constants.py, readthedocs/doc_builder/exceptions.py, readthedocs/projects/tasks/builds.py, readthedocs/projects/tests/test_build_tasks.py
Running `store_build_artifacts` from inside `.execute()` method
instead of from `.on_sucess()` allow us to raise any exception and handle it
properly.
We can raise a `BuildUserError` to clearly communicate the specific error to the
user, or any other exception to show the generic message: "Try again or contact
us".
Besides, this allows us to *fail the build* instead of continuing silently
without the user noticing this:
- there are more than 1 file of formats that don't support multiple files
- the output path is not a directory
- there were errors uploading the artifacts to the storage
PR based in https://github.com/readthedocs/readthedocs.org/pull/9940
Related to https://github.com/readthedocs/readthedocs.org/issues/9931
=> Build: communicate uploading errors to users

docs/conf.py
`html_theme_path` should NOT be defined and is hereby removed. tl;dr https://github.com/readthedocs/readthedocs.org/pull/9654
A really quick shortcut to see if `setup(app)` was called is to check the anchor link next to each headline. If it's a pilcrow (¶), then something is wrong! We want a " :link: "
https://github.com/readthedocs/sphinx_rtd_theme/blob/6444ca893043d8a0ca704474f7cf7d5a148f6767/sphinx_rtd_theme/__init__.py#L72-L76
---
- User's documentation (`docs`): https://docs--9923.org.readthedocs.build/en/9923/
- Developer's documentation (`dev`): https://dev--9923.org.readthedocs.build/en/9923/
=> Docs: Remove html_theme_path from conf.py

docs/user/config-file/v2.rst
This adds a warning to the [Configuration File V2, Formats](https://docs.readthedocs.io/en/stable/config-file/v2.html#formats) section, to help users like myself to evaluate why the formats seemed to be ignored while building docs in pull requests.
Rewording suggestions or moving this to (e.g.) the "note" section is welcome.
---
- User's documentation (`docs`): https://docs--9892.org.readthedocs.build/en/9892/
- Developer's documentation (`dev`): https://dev--9892.org.readthedocs.build/en/9892/
=> Docs: add warning that pull requests only build HTML and not other formats

readthedocs/core/signals.py, readthedocs/rtd_tests/tests/test_middleware.py, readthedocs/settings/base.py, readthedocs/settings/proxito/base.py
We don't need this logic anymore, we don't allow passing cookies, so just checking the list of allowed URLs is enough.
=> Remove custom CORS logic

CHANGELOG.rst, docs/user/security.rst
We missed to mention the latest security discoveries in our changelog as we have been doing.
---
- User's documentation (`docs`): https://docs--9973.org.readthedocs.build/en/9973/
- Developer's documentation (`dev`): https://dev--9973.org.readthedocs.build/en/9973/
=> Update security docs

readthedocs/wsgi.py, requirements/deploy.in, requirements/deploy.txt, requirements/docker.txt, requirements/docs.txt, requirements/lint.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Match production environment by using `gunicorn` instead of the Django development server.
It uses a previous work that @agjohnson did to reload the `web` and `proxito` processes inside Docker using `nodemon`. It requires this "common" PR: https://github.com/readthedocs/common/pull/160
- it keeps the same functionality from `manage.py runserver` (auto reload --being able to turn it on/off)
- matches environment from production
- allows handling multiple requests in a nicer way locally
- site works faster locally (maybe it's my impression, but 🤷🏼 )
=> Development: use `gunicorn` for `web` and `proxito`

docs/user/hosting.rst, readthedocs/proxito/tests/test_full.py, readthedocs/proxito/views/serve.py
With the introduction of `build.commands` we cannot use `version.documentation_type` anymore since those versions will be `generic` and we can't skip checking for this file location.
Note this commit may add and extra call to S3 API for all the 404 pages where our regular Maze will be shown. However, it removes 2 databsae calls from all the 404 requests.
We could only add this extra check on S3 for
`version.documentation_type='generic'`, but that would make the code a little more complex and we won't be removing these 2 db queries.
Reference: https://github.com/readthedocs/sphinx-notfound-page/issues/215#issuecomment-1415771549
=> Proxito: always check `404/index.hmtml`

docs/user/environment-variables.rst, readthedocs/api/v2/serializers.py, readthedocs/doc_builder/director.py, readthedocs/doc_builder/environments.py, readthedocs/doc_builder/python_environments.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/tests/test_api.py
The variable `$READTHEDOCS_VIRTUALENV_PATH` points to where Read the Docs created the virtualenv.
While working on this I found that we can use this variable to run our own commands. This way, we will be avoiding mistakes and potentially having differences path between "the real path" and the content of this variable. I changed our code to use this variable when running `/bin/python` and others.
Besides, I did the same for Conda environments and the variables `CONDA_ENV_PATHS` and `CONDA_DEFAULT_ENV` that were already defined.
This makes the code cleaner and simpler, while more standardized as well. Users can use these variables in the same way Read the Docs does and be sure the content they are expecting is going to be there.
Closes #9629
---
- …
=> Build: expose `READTHEDOCS_VIRTUALENV_PATH` variable

readthedocs/projects/filters.py
I noticed this was swapped on just the project pages, the version pages has
the correct ordering.
Changes isolated in cb7eb49ad
Closes https://github.com/readthedocs/ext-theme/issues/116
=> Fix ordering of filter for most recently built project

requirements/deploy.txt, requirements/docker.txt, requirements/lint.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
It's deprecated and it was included in `kombu` directly.
> django-kombu has now moved into Kombu core, so this repository is no longer in
use.
(from https://pypi.org/project/django-kombu/)
We are not using it directly, but as a dependency required by Celery itself.
=> Requirements: remove `django-kombu`

docs/user/guides/jupyter.rst
This Pull Request fixes indentation in [Jupyter user guide](https://docs.readthedocs.io/en/latest/guides/jupyter.html#id7) markdown code block.
It avoids users who replicate the MyST-NB example to get trough this uninformative error
```log
Exception occurred:
File ".../site-packages/myst_nb/core/read.py", line 140, in is_myst_markdown_notebook
metadata.get("jupytext", {})
AttributeError: 'NoneType' object has no attribute 'get'
```
---
- User's documentation (`docs`): https://docs--10008.org.readthedocs.build/en/10008/
- Developer's documentation (`dev`): https://dev--10008.org.readthedocs.build/en/10008/
=> Fix code block indentation in Jupyter user guide

readthedocs/rtd_tests/tests/test_middleware.py, readthedocs/settings/base.py, readthedocs/settings/proxito/base.py, requirements/deploy.txt, requirements/docker.txt, requirements/docs.txt, requirements/lint.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
May be blocked by https://github.com/adamchainz/django-cors-headers/issues/830, but we could also just have a single regex for all the allowed URLs.
=> Use new maintained django-cors-headers package

docs/user/api/cross-site-requests.rst, docs/user/api/index.rst, docs/user/api/v2.rst
Wasn't sure how technical to get here or where to put this...
---
- User's documentation (`docs`): https://docs--9999.org.readthedocs.build/en/9999/
- Developer's documentation (`dev`): https://dev--9999.org.readthedocs.build/en/9999/
=> Document about cross-site request

docs/user/glossary.rst, docs/user/guides/administrators.rst, docs/user/guides/technical-docs-seo-guide.rst, docs/user/index.rst
This is mainly documentation. The examples in here aren't really how-tos, they are still just examples.
I also put Sphinx and MkDocs examples in tabs and removed the introduction that framed this as "Sphinx-specific".
Refs: #9746 
---
- User's documentation (`docs`): https://docs--10004.org.readthedocs.build/en/10004/
- Developer's documentation (`dev`): https://dev--10004.org.readthedocs.build/en/10004/
=> Docs: Relabel SEO guide as explanation (Diátaxis)

docs/user/commercial/index.rst
RTD for Business is not just for _companies_, so we decided to be a bit more generally inclusive.
---
- User's documentation (`docs`): https://docs--10012.org.readthedocs.build/en/10012/
- Developer's documentation (`dev`): https://dev--10012.org.readthedocs.build/en/10012/
=> Docs: Very small text update

readthedocs/core/tasks.py, readthedocs/settings/base.py
Simple task to remove `pidbox` keys older than 15 minutes. This is a workaround to avoid Redis OOM for now.
We will need to find out a better solution here. There is an upstream issue opened that we should check in the near future and probably remove this
workaround: https://github.com/celery/celery/issues/6089
Related: https://github.com/readthedocs/readthedocs-ops/issues/1260
=> Celery: cleanup `pidbox` keys

docker-compose.override.yml, readthedocs/settings/docker_compose.py, requirements/deploy.in, requirements/deploy.txt, requirements/docker.in, requirements/docker.txt, requirements/lint.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Use `django-redis` instead of `django-redis-cache` and connect to Redis via password. `django-redis` allows also to connect to Redis via SSL.
Celery instances also connect to Redis using the user/password authentication method.
Requires: https://github.com/readthedocs/common/pull/164
Requires: https://github.com/readthedocs/readthedocs-ops/pull/1293
Requires: https://github.com/readthedocs/readthedocs-corporate-ops/pull/824
=> Redis: use `django-redis` and add password

readthedocs/subscriptions/event_handlers.py, readthedocs/subscriptions/tests/test_event_handlers.py
Otherwise if the customer doesn't have a rtd-organization attached (when an organization is deleted), this will raise an exception.
ref https://read-the-docs.sentry.io/issues/3729261304/?project=161479&query=is%3Aunresolved&referrer=issue-stream
=> Subscriptions: use getattr for getting related organization

readthedocs/oauth/services/github.py, readthedocs/oauth/services/gitlab.py
This is a known error and it happens because the user revoked the our grant from GitHub/GitLab UI. This commit handles this error and avoids sending it to Sentry.
=> Logging: avoid logging `invalid_grant` error in Sentry

readthedocs/core/management/commands/contact_owners.py
When organization are enabled we should use them only if we are not passing `--usernames` argument when calling the script.
=> Management: use setting as last resource

readthedocs/projects/tasks/builds.py
This protects the user to end up with half of their documentation uploaded.
=> Builds: ignore cancelling the build at "Uploading" state

readthedocs/api/v2/serializers.py, readthedocs/api/v2/utils.py, readthedocs/api/v2/views/model_views.py, readthedocs/rtd_tests/tests/test_api.py
* Update the regex by removing a `/` for Conda because it wasn't matching properly.
* Move the logic into a util function `sanitize_build_command`
* Use the helper from the serializer and also from when serving from the cold storage
=> APIv2: better build command sanitization

requirements/deploy.in, requirements/deploy.txt
I checked all the changelogs from 7.4.x and there is no breaking changes that affect us.
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-80600/
Closes https://github.com/readthedocs/readthedocs-ops/issues/1290
=> Requirements: unpin `newrelic`

docs/_static/css/custom.css, docs/_static/js/expand_tabs.js, docs/user/index.rst
Refs: https://github.com/readthedocs/readthedocs.org/pull/10026#issuecomment-1432624078
---
- User's documentation (`docs`): https://docs--10039.org.readthedocs.build/en/10039/
- Developer's documentation (`dev`): https://dev--10039.org.readthedocs.build/en/10039/
=> Docs: emojis in TOC captions, FontAwesome on external links in TOC (Diátaxis)

docs/user/config-file/v2.rst, docs/user/guides/reproducible-builds.rst
This is mostly cleaning this page up and removing some repeat concepts.
---
- User's documentation (`docs`): https://docs--10030.org.readthedocs.build/en/10030/
- Developer's documentation (`dev`): https://dev--10030.org.readthedocs.build/en/10030/
=> Docs: Refactor Reproducible Builds page (Diátaxis)

readthedocs/metrics/tasks.py
Required by https://github.com/readthedocs/readthedocs-ext/pull/534
=> Metrics: update URL for latency metric

docs/user/team.rst
---
- User's documentation (`docs`): https://docs--10056.org.readthedocs.build/en/10056/
- Developer's documentation (`dev`): https://dev--10056.org.readthedocs.build/en/10056/
=> Docs: Replace duplicate information about staff and contributors with a seealso::

docs/conf.py, docs/user/analytics.rst, docs/user/automatic-redirects.rst, docs/user/automation-rules.rst, docs/user/builds.rst, docs/user/canonical-urls.rst, docs/user/commercial/organizations.rst, docs/user/commercial/single-sign-on.rst, docs/user/config-file/v2.rst, docs/user/custom-domains.rst, docs/user/faq.rst, docs/user/guides/automation-rules.rst, docs/user/guides/deprecating-content.rst, docs/user/guides/importing-private-repositories.rst, docs/user/guides/intersphinx.rst, docs/user/guides/pull-requests.rst, docs/user/guides/technical-docs-seo-guide.rst, docs/user/intro/getting-started-with-mkdocs.rst, docs/user/intro/getting-started-with-sphinx.rst, docs/user/intro/import-guide.rst, docs/user/reference/404-not-found.rst, docs/user/reference/analytics.rst, docs/user/reference/environment-variables.rst, docs/user/tutorial/index.rst, docs/user/user-defined-redirects.rst
---
- User's documentation (`docs`): https://docs--10059.org.readthedocs.build/en/10059/
- Developer's documentation (`dev`): https://dev--10059.org.readthedocs.build/en/10059/
=> Docs: Fix undeclared labels after refactor + fix root causes

readthedocs/builds/tasks.py
This query is taking more than 30 seconds and it has been killed by our postgres config. I'm reducing the query to consider at most builds that are 90 days old. This should reduce the scope of the table and make the query to run fast.
Related to https://github.com/readthedocs/readthedocs-ops/issues/1291
=> Celery: limit `archive_builds_task` query to last 90 day ago

readthedocs/telemetry/tasks.py
Related https://github.com/readthedocs/readthedocs-ops/issues/1291
=> Celery: delete Telemetry data that's at most 3 months older

readthedocs/settings/base.py
- make email verification `mandatory`: users without a verified email will be asked to verify their address before being able to login
- rename `ACCOUNT_ACTIVATION_DAYS` since it was a setting from a Django app we don't use anymore. It's called `ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS` in Django Allauth.
- email verification is not required for development instance
This PR **requires other PRs** to work as intended:
* https://github.com/readthedocs/readthedocs-ops/pull/1271
* https://github.com/readthedocs/readthedocs-corporate/pull/1529
> NOTE that I review all the settings from https://django-allauth.readthedocs.io/en/latest/configuration.html and I think we are fine moving forward with this combination.
Context: https://github.com/readthedocs/meta/discussions/103
Closes: …
=> Account: organize allauth settings

docs/user/guides/cross-referencing-with-sphinx.rst, docs/user/guides/jupyter.rst, docs/user/guides/migrate-rest-myst.md
Issue regarding the replaced Intersphinx reference for `intro.md#installation` is reported here: https://github.com/executablebooks/MyST-Parser/issues/731
---
- User's documentation (`docs`): https://docs--10090.org.readthedocs.build/en/10090/
- Developer's documentation (`dev`): https://dev--10090.org.readthedocs.build/en/10090/
=> Fix intersphinx references to myst-parser (updated in myst-parser 0.19)

readthedocs/projects/migrations/0097_add_http_header.py
Both migrations are named 0096.
=> Fix migration

readthedocs/proxito/tests/test_middleware.py, readthedocs/proxito/tests/test_redirects.py
Ref https://github.com/readthedocs/readthedocs.org/pull/10027#discussion_r1109164160
=> Remove unused tests

readthedocs/settings/docker_compose.py
Use an environment variable defined by `invoke` command to set the logging level of our Django application.
Requires: https://github.com/readthedocs/common/pull/167
=> Development: allow to define the logging level via an env variable

docs/user/automatic-redirects.rst
RST doesn't support nested elements.
---
- User's documentation (`docs`): https://docs--10110.org.readthedocs.build/en/10110/
- Developer's documentation (`dev`): https://dev--10110.org.readthedocs.build/en/10110/
=> Docs: fix term reference

readthedocs/settings/base.py
`Organization` and `PlanFeature` weren't being cached by `cacheops` and they are used when serving documentation.
By caching these, we will be caching all the models used when serving documentation, reducing the db hits and a also a litte the response time.
With this change, we won't hit the db at all when serving documentation 👍🏼 . This has other benefits besides trying to reduce the response time.
=> Proxito: use cacheops for 2 more models

readthedocs/api/v2/views/task_views.py, readthedocs/core/utils/tasks/__init__.py, readthedocs/core/utils/tasks/public.py, readthedocs/core/utils/tasks/retrieve.py, readthedocs/rtd_tests/tests/test_api.py, readthedocs/rtd_tests/tests/test_privacy_urls.py
The frontend hits this endpoint every 1s. As we don't know when the task has finished now since we disabled the Celery result backend, we are just cheating it and return finished after 5 times the view is called with the same `task_id`.
This fixes the issue we have in the UI when clicking the circled arrows to re-sync the remote repositories.
Closes #10068
=> Celery: cheat `job_status` view to return `finished` after 5 polls

readthedocs/settings/base.py
I got confused because we are mapping a different table name. `subscriptions.models.PlanFeature` maps to `organizations_planfeature` table.
Related https://github.com/readthedocs/readthedocs.org/pull/10106
=> Proxito: cacheops right model

readthedocs/proxito/views/serve.py
In .com need to check for this.
But we don't allow users to create custom domains if they don't have the right subscription, so not sure if this is really needed.. It can be useful only if a user downgrades their subscription I guess.
=> Canonical redirects: check if the project supports custom domains

readthedocs/doc_builder/director.py, readthedocs/projects/tests/test_build_tasks.py
I'm not sure about _why_ we split the commands before sending it out our executor. The command is finally wrapper properly before being executed.
I did some locally QA after removing the split of the command and it seems these scripts work fine. So, it seems safe to move forward with this, explanding the flexibility of our config file.
The example provided by the user works fine.
> **Note**
> This example is interpreted just as a comment (since it's just _one line_ after the split) without this PR and nothing is executed. With this changes, the comment is ignored and the code is executed. However, the script is properly shown as multi-line in the UI as well.
Closes #10103
=> Build: pass shell commands directly (`build.jobs` / `build.commands)`

readthedocs/doc_builder/backends/sphinx.py, readthedocs/doc_builder/constants.py, readthedocs/doc_builder/exceptions.py, readthedocs/projects/tests/mockers.py, readthedocs/projects/tests/test_build_tasks.py
We were forcing `exit_code=0` if we detected that `Output written on (.*?)` was found in the standard output of the `latexmk` command. This was producing confusions to our users because the PDF generation failed but we were considering it successful.
Now, we are relying on the exit code itself as we do for all the other commands making sure the command succeeded before proceding with the build. Now, if the PDF command fails, we fail the build completely.
Closes #10015
=> Build: fail PDF command (`latexmk`) if exit code != 0

readthedocs/settings/base.py
We are hitting `projects_feature` table now. So, I'm adding this one to be cached as well.
=> Proxito: add another model to cacheops

readthedocs/proxito/views/serve.py
We are overriding it on .com, it probably isn't necessary since we aren't using it in the view, but I'm adding it back just for the sake of deploy.
=> Put back template_name on proxito 404 view

readthedocs/proxito/tests/test_full.py, readthedocs/proxito/views/serve.py
If the path ends with `/`, we already tried to serve the `/index.html` file and weren't able to find it, so we only need to test for the README.html in those cases, for paths that don't end with slash, we need to check for both files.
=> Proxito: don't check for index.html if the path already ends with `/`.

readthedocs/doc_builder/environments.py
Instead of prepending all the commands with the `PATH=` variable, we pass the environment variable directly to the Docker container.
This allow us to run multi-line shell script without failing with weird syntax errors. Besides, the implementation is cleaner since all the environment variables are passed to the commands in the same way.
I added some _default paths_ that I found by checking the local Docker container. I'm also passing the users' path, depending if we are working locally as root or in production.
This is not 100% complete and there may be some other issues that I'm not seeing yet, but I think it's a first step to behave in a way our users are expecting.
Closes #10103
=> Build: pass `PATH` environment variable to Docker container

readthedocs/doc_builder/backends/sphinx.py, readthedocs/doc_builder/constants.py, readthedocs/doc_builder/exceptions.py, readthedocs/projects/tests/mockers.py, readthedocs/projects/tests/test_build_tasks.py
Reverts https://github.com/readthedocs/readthedocs.org/pull/10113
=> Revert 92a7182af42e26cab01265d2cc06fc7832832689

docs/dev/front-end.rst, docs/dev/install.rst
Just some small changes for now. The library is still private for a
private beta period, but will be made public soonish.
---
- User's documentation (`docs`): https://docs--10161.org.readthedocs.build/en/10161/
- Developer's documentation (`dev`): https://dev--10161.org.readthedocs.build/en/10161/
=> Update some docs for the new dashboard templates

readthedocs/doc_builder/director.py, readthedocs/proxito/views/hosting.py
Use `safe_open` instead of global open for security reasons.
Referece: https://github.com/readthedocs/readthedocs.org/pull/10127#pullrequestreview-1348831191
=> Build: use safe_open for security reasons

docs/user/canonical-urls.rst, docs/user/custom-domains.rst, docs/user/reference/environment-variables.rst, readthedocs/api/v2/serializers.py, readthedocs/builds/models.py, readthedocs/doc_builder/director.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/tests/test_api.py
This variable communicates what's the canonical URL for the version it's running
the build. It will allow doctool/theme authors to implement the correct HTML tag
required:
```
<link rel="canonical" href="" />
```
Note the final `href` on each page will be `READTHEDOCS_CANONICAL_URL` + `page`.
Closes readthedocs/readthedocs-ops#1320
Closes #9781
Closes #8260
Closes #4820 
---
- User's documentation (`docs`): https://docs--10166.org.readthedocs.build/en/10166/
- Developer's documentation (`dev`): https://dev--10166.org.readthedocs.build/en/10166/
=> Build: export READTHEDOCS_CANONICAL_URL variable

docs/user/guides/jupyter.rst
This is currently breaking the docs.
Related: https://github.com/executablebooks/MyST-Parser/issues/731
We can also remove the Intersphinx mapping. There are 2 references in use.
---
- User's documentation (`docs`): https://docs--10176.org.readthedocs.build/en/10176/
- Developer's documentation (`dev`): https://dev--10176.org.readthedocs.build/en/10176/
=> Docs: Removal of implicit Intersphinx reference labels to MyST-based documentation

readthedocs/projects/forms.py, readthedocs/projects/models.py, readthedocs/rtd_tests/tests/test_project_views.py
This is the continuation of a soft deprecation. We already remove mentions to other VCS different than Git from our documentation.
In this step, we remove the ability to import other repositories other than Git. However, we are keeping the code around to avoid existing projects to break when building. In the future, we will remove this support completely.
Continuation of #8840
=> Project: only support Git as VCS for new projects

readthedocs/builds/filters.py, readthedocs/projects/filters.py
The changes here resolve a few bugs with these filters, mostly used in the new dashboard.
* Account for null values in date sorting. Null dates were presenting as ordering issues in listing displays.
* Always use filter annotations conditionally, depending on the sort parameter to the filter. The project list filter was always annotating the queryset, likely hurting performance.
* Reduce some of the words used in the filter text, for clarity.
* Add more filters to build and version filters, match project filters on the version filter
* Consolidate logic in the version/build filter around dates and null dates.
Linting is isolated in bfeb6f9eda67eabd5bb5a2ea37a2ceac2a8d2bce
* Closes https://github.com/readthedocs/ext-theme/issues/40
* Refs https://github.com/readthedocs/ext-theme/issues/128 …
=>  Filters: several bug fixes and some filter tuning

readthedocs/core/views/__init__.py
This page is not needed anymore, with our website. This page is unused
in our new dashboard already. Instead, redirect right to the log in
page.
Tested on both dashboards
=> Make our homepage conditional on the new dashboard

readthedocs/projects/views/public.py, readthedocs/proxito/tests/test_full.py
There is no need to use `_get_project_data_from_request` (this will be removed), since we already have all the information from the URL. And this URL is a well defined URL, isn't a doc serving URL.
=> Proxito: refactor project download view

readthedocs/builds/filters.py
These are always passed as positional arguments, never keyword
arguments. The positional split at `*` caused:
```
BuildListFilter.get_type() takes 2 positional arguments but 4 were given
```
=> Fix filter positional arguments

readthedocs/projects/views/public.py, readthedocs/proxito/views/mixins.py, readthedocs/proxito/views/serve.py
There is a PR in .com
Closes https://github.com/readthedocs/readthedocs.org/issues/10198
=> Proxito: refactor allowed_user

docs/conf.py
This is a quick experiment: I noticed that all the canonical  meta tags on [all versions of the Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/) are almost definitely wrong.. they point to /stable meaning that you cannot generate accurate link previews.
Take for instance this build: https://readthedocs.org/projects/jupyter-notebook/builds/19683327/
The solution is to use our new environment variable :tada:
=> Docs: Experiment with canonical url using READTHEDOCS_CANONICAL_URL

docs/user/reference/environment-variables.rst
Consistency among all the examples in the variables.
---
- User's documentation (`docs`): https://docs--10225.org.readthedocs.build/en/10225/
- Developer's documentation (`dev`): https://dev--10225.org.readthedocs.build/en/10225/
=> Docs: minor changes to examples for consistency

readthedocs/analytics/proxied_api.py
ref https://read-the-docs.sentry.io/issues/4066157775/?alert_rule_id=242443&alert_timestamp=1680770304794&alert_type=email&environment=production&project=161479&ref_fallback=expt&referrer=alert_email
Example https://docs.readthedocs.io/_/api/v2/analytics/?project=docs&version=stable
=> Analytics API: check if absolute_uri isn't present

docs/dev/install.rst
I'm not settled on whether this is the best place for this or not, but
it's probably _the best place we have currently_.
Not fully tested, but if these commands don't work exactly, at least
it's a clue as to what needs to happen.
---
- User's documentation (`docs`): https://docs--10230.org.readthedocs.build/en/10230/
- Developer's documentation (`dev`): https://dev--10230.org.readthedocs.build/en/10230/
=> Add notes on private repo support in our install docs

readthedocs/proxito/tests/responses/v0.json, readthedocs/proxito/tests/responses/v1.json, readthedocs/proxito/tests/responses/v2.json, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Review initial JSON response to keep consistency with APIv3 resources. It uses a small modified version of the APIv3 serializers for known resources, removing some URL fields that can't be resolved from El Proxito.
Sharing the same serializers that our APIv3 make our response a lot more consitent between the endpoints and allow us to expand the behavior by adding more fields in a structured way.
Besides, these changes include a minimal checking of the version coming from `X-RTD-Hosting-Integrations-Version` header to decide which JSON structure return, allowing us to support multiple version at the same time in case we require to do some breaking changes.
The JavaScript client is already sending this header in all of its requests. See …
=> API: hosting integrations endpoint versioning/structure

readthedocs/proxito/middleware.py
Versions using `build.commands` will start using the new Read the Docs JavaScript client.
This is still under beta testing, but we want to move forward slowly and start exposing these features to projects that don't have access currently.
Related https://github.com/readthedocs/readthedocs-client/issues/26
=> Proxito: inject hosting integration header for `build.commands`

scripts/compile_version_upload_s3.sh
Just quickly updating the script...
1) I received some error "credentials not found" until the environment variables got exported. But otherwise it worked fine :+1: 
https://github.com/readthedocs/readthedocs.org/blob/main/requirements/pip.in#L37
2) awscli has been removed from our requirements so needs to be added manually to the environment. Since it's not terribly important, I added a note that we MIGHT use mc (as the docker containers also do) in case there are issues with it.
https://github.com/readthedocs/readthedocs.org/blob/main/requirements/pip.in#L37
=> Scripts: Add export statements and instruction to fetch awscli (compile_version_upload_s3.sh)

readthedocs/proxito/middleware.py
This reverts commit 27215d29b372369e1103d4b480dace77b69ad655.
=> Revert "Proxito: inject hosting integration header for `build.commands` (#10219)"

docs/user/build-notifications.rst, docs/user/connected-accounts.rst, docs/user/faq.rst, docs/user/glossary.rst, docs/user/guides/build-notifications.rst, docs/user/guides/git-integrations.rst, docs/user/guides/reproducible-builds.rst, docs/user/tutorial/index.rst
Some of these entries were originally from #10071 
Refs: https://github.com/readthedocs/readthedocs.org/issues/9747
---
- User's documentation (`docs`): https://docs--10249.org.readthedocs.build/en/10249/
- Developer's documentation (`dev`): https://dev--10249.org.readthedocs.build/en/10249/
=> Docs: New entries to glossary

readthedocs/core/unresolver.py, readthedocs/rtd_tests/tests/test_unresolver.py
During development we use overlapping domains:
- devthedocs.org
- build.devthedocs.org
Basically now the suspicious hostname checks are done after the public and external version domains have been tried, and before resolving a custom domain.
Closes https://github.com/readthedocs/readthedocs.org/pull/10241
=> Proxito: allow overlapping public and external version domains

readthedocs/config/config.py, readthedocs/doc_builder/director.py, readthedocs/doc_builder/python_environments.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/tests/test_doc_building.py
Ref https://github.com/readthedocs/readthedocs.org/issues/8659 Closes https://github.com/readthedocs/readthedocs.org/issues/10263
=> Build: Pin setuptools only when required

docs/user/build-default-versions.rst
Ref https://github.com/readthedocs/readthedocs.org/pull/10268
---
- User's documentation (`docs`): https://docs--10270.org.readthedocs.build/en/10270/
- Developer's documentation (`dev`): https://dev--10270.org.readthedocs.build/en/10270/
=> Update docs about setuptools dependency

dockerfiles/settings/proxito.py
This is causing issues in Docker development. Not sure if it's enabled for proxito in production?
Example:
```
File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/usr/src/app/checkouts/readthedocs.org/readthedocs/core/mixins.py", line 55, in dispatch
response = super().dispatch(request, *args, **kwargs)
File …
```
=> Dev: Disable cacheops in proxito docker environment

readthedocs/proxito/tests/test_middleware.py
Had a TODO on this one to figure out if it was possible to test the "full" stack of middleware and views, using this flag for the test client.
But it's not. I think the explanation is that the test client reacts on `response.exc_info` which isn't set when there's 404s raised, those are handled differently.
=> Remove raise_for_exception=False tests

docs/user/build-customization.rst, readthedocs/config/config.py, readthedocs/config/models.py, readthedocs/config/tests/test_config.py
Fixes https://github.com/readthedocs/readthedocs.org/issues/9280
=> Allow build.commands without build.tools

readthedocs/doc_builder/python_environments.py, readthedocs/rtd_tests/tests/test_doc_building.py
The same version installed before needs to match here, otherwise for some reason pip gives you an error when installing some packages.
Fixes https://github.com/readthedocs/readthedocs.org/issues/10285
=> Build: use same version of setuptools when using `system_packages`

docs/user/config-file/v2.rst
These are not required in our configuration specification
Resolves #10302
---
- User's documentation (`docs`): https://docs--10303.org.readthedocs.build/en/10303/
- Developer's documentation (`dev`): https://dev--10303.org.readthedocs.build/en/10303/
=> Change a few configuration file options from required to not required

readthedocs/profiles/views.py, readthedocs/rtd_tests/tests/test_profile_views.py
This is basically moving the code from .com to .org, and also fixing a bug.
Fixes https://github.com/readthedocs/readthedocs-corporate/issues/1468
=> Organizations: allow users without organizations to see their own profiles

readthedocs/proxito/views/serve.py, readthedocs/templates/errors/404/no_language.html, readthedocs/templates/errors/404/no_subproject.html, readthedocs/templates/errors/404/no_version.html
Fixes https://github.com/readthedocs/readthedocs.org/issues/10292
=> Proxito: Search scope narrowed to active project (version, translation or subproject 404s)

readthedocs/doc_builder/environments.py
This is another attempt to fix this issue. It follows the suggestion posted by @bensze01 in https://github.com/readthedocs/readthedocs.org/issues/10103. It looks simple and I think it makes sense to give it a try since it doesn't seem to be harmful.
I tested it locally with the branch
https://github.com/readthedocs/test-builds/tree/build-commands-multiline and it worked fine. Note that without this PR the branch linked fails.
Related #10133
Related #10119
Related #10206
External PRs that should be solved by this one:
* https://github.com/pypi/warehouse/pull/12953
* https://github.com/pypi/warehouse/pull/12953
Closes #10103
Closes #10208
=> Build: allow multi-line commands on `build.commands`

requirements/deploy.txt, requirements/docker.txt, requirements/pip.txt, requirements/testing.txt
See https://github.com/jazzband/django-debug-toolbar/pull/1770
We hit this while doing a deploy.
=> Requirements: upgrade DDT to avoid an issue

readthedocs/settings/base.py
This will reduce the amount of emails we send and also provide a better UX to users registering in our platform.
Related https://github.com/readthedocs/readthedocs-ops/issues/1269
=> Email: trust GH and GL emails and mark them as verified

docs/user/index.rst
Fixes what I immediate could spot in #10300
A bigger related change is coming in #10071 where the explanation section is made more understandable by splitting up introduction and advanced content.
Thanks @hughesnyc :pray: 
---
- User's documentation (`docs`): https://docs--10358.org.readthedocs.build/en/10358/
- Developer's documentation (`dev`): https://dev--10358.org.readthedocs.build/en/10358/
=> Small index page tweak

readthedocs/proxito/cache.py
This line is being logged because for some responses we add the cache tags later in the middleware.
We have plenty of tests to make sure the cache tags are present, so this isn't a problem.
This is filling our logs, so we are removing it.
=> Logs: remove caching without tags log warning

docs/user/guides/jupyter.rst
MyST does not pass autosectionlabel to intersphinx - see https://github.com/executablebooks/MyST-Parser/issues/731
(doesn't look like that's gonna be fixed, neither)
---
- User's documentation (`docs`): https://docs--10382.org.readthedocs.build/en/10382/
- Developer's documentation (`dev`): https://dev--10382.org.readthedocs.build/en/10382/
=> Doc: Remove broken reference

.readthedocs.yml
I've noticed this page is hard to get search results for. I wasn't
getting search hits until mostly typing out "configuration". This seems
more a problem with word root or missing search terms on the config file
page, but I do agree that the page title should be "Configuration file"
=> Try to bump up config file search in ranking

readthedocs/projects/models.py, readthedocs/rtd_tests/tests/test_backend.py, readthedocs/rtd_tests/tests/test_backend_svn.py, readthedocs/rtd_tests/tests/test_version.py, readthedocs/vcs_support/base.py
With https://github.com/readthedocs/readthedocs.org/pull/10378/ we now need to always pass an environment,
we can't just create a default one.
=> Build: pass environment explicitly

readthedocs/doc_builder/environments.py, readthedocs/vcs_support/base.py
We aren't using the LocalEnvironment class,
only the BuildEnvironment, so there is no need to keep BaseEnvironment seperated from BuildEnvironment.
Doing this small refactors while trying to implement https://github.com/readthedocs/readthedocs.org/pull/10289/.
=> Build: merge `BaseEnvironment` with `BuildEnvironment`

docs/user/glossary.rst, docs/user/guides/setup/git-repo-automatic.rst
@agjohnson Some context: I'm adding doc links to all future Dashboard pages. The "Maintainers" page falls a bit outside of category since it's a feature that only exists on .org
Instead of posting an issue that's never gonna get fixed, I think we can just add this quick glossary item.
Review:
* Do you spot something technically incorrect?
* Welcome to pass the review to someone else :+1: 
---
- User's documentation (`docs`): https://docs--10381.org.readthedocs.build/en/10381/
- Developer's documentation (`dev`): https://dev--10381.org.readthedocs.build/en/10381/
=> Docs: Define 'maintainer' so we can reference it

docs/user/feature-flags.rst, readthedocs/doc_builder/backends/sphinx.py, readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl, readthedocs/projects/models.py
We have this feature enabled on .org and .com,
we haven't heard any complaints.
Closes https://github.com/readthedocs/readthedocs.org/issues/10293
---
- User's documentation (`docs`): https://docs--10394.org.readthedocs.build/en/10394/
- Developer's documentation (`dev`): https://dev--10394.org.readthedocs.build/en/10394/
=> Sphinx: don't override html_context by default

docs/user/glossary.rst, docs/user/guides/setup/git-repo-automatic.rst
From #10381 a few fixes missed before merging. Just a couple typos edits, but I'd also avoid introducing the term "admin" on top of user/maintainer/teams/etc.
---
- User's documentation (`docs`): https://docs--10395.org.readthedocs.build/en/10395/
- Developer's documentation (`dev`): https://dev--10395.org.readthedocs.build/en/10395/
=> Fixes on Git providers

media/css/core.css, readthedocs/templates/projects/import_config.html
This addresses some display bugs from commercial, where the nested order
of elements was swapped and there are already conflicts between usage of
`<code>` and `<pre>`.
Instead, this reverts to my suggestion from review, and uses the Pygments
wrapping element `div.highlight` to style code block content. This avoids
conflicts between code/pre use and styling and provides a better looking
border and padding for block content.
This also survives the translation to the commercial styling better and
doesn't affect any other case in the UI where `<code>` is used to style
inline content instead of block content.
There is a required PR on commercial too.
Summary of changes here:
- Change elements for code block to Pygment code block wrapper
- Some copy/UI fixes and cleanup
=> Fix display issues with project creation config page

docs/user/guides/best-practice/index.rst, docs/user/guides/content/index.rst, docs/user/guides/technical-docs-seo-guide.rst, docs/user/science.rst
A little gramma :gift: for @agjohnson :heart: 
---
- User's documentation (`docs`): https://docs--10409.org.readthedocs.build/en/10409/
- Developer's documentation (`dev`): https://dev--10409.org.readthedocs.build/en/10409/
=> Docs: Correct title case for SEO occurrences

docs/user/build-notifications.rst, docs/user/guides/build/email-notifications.rst, docs/user/guides/build/index.rst, docs/user/guides/build/webhooks.rst, docs/user/guides/setup/git-repo-manual.rst
This splits existing howtos into two separate articles:
* ~Very little text editing~ Editing a lot of the texts for clarity and smoothness
* Added cross-references
* Updated references
* Tabbed interface for Discord/Slack payload examples
Refs: #9747 
---
- User's documentation (`docs`): https://docs--10396.org.readthedocs.build/en/10396/
- Developer's documentation (`dev`): https://dev--10396.org.readthedocs.build/en/10396/
=> Docs: Split email notifications and webhook notifications into separate howtos

readthedocs/templates/projects/project_advanced_settings_helptext.html
Ref: https://github.com/readthedocs/readthedocs.org/issues/10386 https://github.com/readthedocs/readthedocs.org/issues/10352 https://github.com/readthedocs/readthedocs.org/issues/10372
=> Project: Add deprecation and removal warning to Advanced Settings

docs/user/reference/environment-variables.rst
Seems like we forgot this one :)
Refs: https://github.com/readthedocs/readthedocs.org/pull/9913
---
- User's documentation (`docs`): https://docs--10407.org.readthedocs.build/en/10407/
- Developer's documentation (`dev`): https://dev--10407.org.readthedocs.build/en/10407/
=> Docs: Add $READTHEDOCS_OUTPUT to environment variable reference

readthedocs/projects/tasks/utils.py
This commit excludes the users that already have an unread notification with this message. This is only to avoid performing db queries for users where our notification backend won't add a new notification anyways. This will improve the performance of this task making it to run faster (hopefully).
=> Deprecation: improve Celery task db query

.github/workflows/pip-tools.yaml
It has been failing with
```
Error: Unable to request reviewers. If requesting team reviewers a 'repo' scoped PAT is required.
Error: Validation Failed: "Could not resolve to a node with the global id of 'T_kwDOAAWW-c4ATMYo'."
```
I'm removing it as `team-reviewers` it's not super important here. I'm getting this notification anyways and reviewing it.
It fails at this line https://github.com/readthedocs/readthedocs.org/actions/runs/5232561948/jobs/9447343798#step:11:121
=> GitHub Action: remove `team-reviewers` because it requires a GH-PAT

readthedocs/projects/tasks/utils.py
Small fixes to generate the URL correctly.
=> Deprecation: show the project slug/link correctly on email

.github/workflows/main.yml
Same as we do with readthedocs-corporate,
there was a bug that could have been caught with this.
Also, don't think we need to hide the repo and job name, we have linked to those repos from public places already.
=> CI: trigger circleci job on readthedocs-ext on merge

docs/user/guides/manage-translations-sphinx.rst
Fixes #9767
Direct link to the changes: https://docs--10434.org.readthedocs.build/en/10434/guides/manage-translations-sphinx.html#using-transifex
---
- User's documentation (`docs`): https://docs--10434.org.readthedocs.build/en/10434/
- Developer's documentation (`dev`): https://dev--10434.org.readthedocs.build/en/10434/
=> Update instructions for using transifex client tool

readthedocs/projects/tasks/utils.py, readthedocs/templates/projects/notifications/deprecated_config_file_used_email.html, readthedocs/templates/projects/notifications/deprecated_config_file_used_email.txt
We are filtering the query to only send emails to users with projects that have a successful build in the last year.
=> Deprecation: send emails to "active projects" only

readthedocs/templates/errors/404/include_error_message.html
This responds to a concern of showing paths that are from URLs.
We are still keeping the context variable in case it's useful in later contextualized scenarios.
Note: Previously, the path was not considered a safe string and enclosed in `<code>`.
=> Do not show paths in 404s

readthedocs/config/config.py, readthedocs/doc_builder/config.py, readthedocs/doc_builder/director.py, readthedocs/templates/builds/build_detail.html
This is important for our config file migration,
so users are given feedback when they have properly configured the file.
This does two things:
* Adds a `cat <config_file>` to the build output, so users know a config is used, and which one
* Adds a small message above the build to share that the config file was used successfully. I will plan to remove this once our config file migration is over.
=> Add a `cat` command and note in the build output when a config file is properly used.

readthedocs/api/v3/tests/test_builds.py, readthedocs/rtd_tests/tests/test_core_utils.py
This makes test pass on .com,
since there all features are given by the org subscription.
=> Test with explicit number of concurrent builds

readthedocs/core/resolver.py, readthedocs/proxito/middleware.py
With this we would be able to start generating
links using the path-prefix while serving docs with the old proxito implementation.
And this also allows us to start using the new implementation with just enabling the feature flag for a project. This is, without having to unset the `urlconf` attribute. This help us to have zero downtime while migrating projects.
=> Proxito: easy migration to custom path prefixes

readthedocs/api/v3/tests/test_builds.py, readthedocs/api/v3/tests/test_environmentvariables.py, readthedocs/api/v3/tests/test_projects.py, readthedocs/api/v3/tests/test_redirects.py, readthedocs/api/v3/tests/test_remoteorganizations.py, readthedocs/api/v3/tests/test_remoterepositories.py, readthedocs/api/v3/tests/test_subprojects.py, readthedocs/api/v3/tests/test_versions.py, readthedocs/api/v3/views.py
This isn't a security vulnerability,
we were filtering by the current user.
This was just causing errors, since we were expecting a real user in some queries.
These views are used in .com only, so I have added tests there.
Also, went ahead and added tests for all other endpoints that didn't have them.
Ref https://read-the-docs.sentry.io/issues/4261898141/?alert_rule_id=242443&alert_timestamp=1687234764178&alert_type=email&environment=production&project=161479&referrer=alert_email
=> API V3: add IsAuthenticated to permissions

docs/user/commercial/subscriptions.rst, docs/user/guides/manage-read-the-docs-teams.rst, docs/user/guides/setup-single-sign-on-github-gitlab-bitbucket.rst, docs/user/guides/setup-single-sign-on-google-email.rst, docs/user/shared/organization-permissions.rst
Fixes #10403 
I noticed that we're pretty inconsistent around whether to write Click, Choose, Select, Press etc... would be nice to have something in the style guide on that.
---
- User's documentation (`docs`): https://docs--10457.org.readthedocs.build/en/10457/
- Developer's documentation (`dev`): https://dev--10457.org.readthedocs.build/en/10457/
=> Docs: Replace navigation instructions with direct URLs w/ organization chooser

readthedocs/proxito/middleware.py
We don't need the `Project` instance. We were using to check for a Feature flag, but now we are only adding the header when the project is using `build.commands`.
If we ever require the `Project` instance again, we can do a `.select_related` from the `Version` object. That way, we still keep doing 1 query only.
Closes #10458
Related #10456
=> Addons: improve db query when adding HTTP header from El Proxito

scripts/compile_version_upload_s3.sh
Just minor changes:
- increase container's sleep time to avoid failing if the compilation takes more than 5 minutes
- show `asdf` version at the beginning of the task
=> Script: build tools updates

docs/user/integrations.rst
---
- User's documentation (`docs`): https://docs--10474.org.readthedocs.build/en/10474/
- Developer's documentation (`dev`): https://dev--10474.org.readthedocs.build/en/10474/
=> Docs: Typo fix for integrations.rst

docs/user/build-customization.rst
Allow a Git repository to unshallow it even if it was already unshallowed. This avoids builds to fail.
---
- User's documentation (`docs`): https://docs--10485.org.readthedocs.build/en/10485/
- Developer's documentation (`dev`): https://dev--10485.org.readthedocs.build/en/10485/
=> Docs: do not fail when unshallow clone

docs/user/advertising/ad-blocking.rst, docs/user/advertising/ethical-advertising.rst, docs/user/advertising/index.rst, readthedocs/gold/templates/gold/subscription_detail.html, readthedocs/templates/profiles/private/advertising_profile.html
Remove from our landing pages that being a gold member or supporter makes RTD ad free. We aren't removing that capability, but the cross site cookies needed to make that work do not work on Safari or Firefox. We'll leave the functionality in for Chrome users, but we aren't going to sell it since it doesn't work widely.
Basically, the API requests from `*.readthedocs.io` or user custom domains cannot make an authenticated request to readthedocs.org.
---
- User's documentation (`docs`): https://docs--10459.org.readthedocs.build/en/10459/
- Developer's documentation (`dev`): https://dev--10459.org.readthedocs.build/en/10459/
=> Update gold docs to reflect cross-site cookie reality

readthedocs/core/management/commands/contact_owners.py, readthedocs/core/utils/contact.py
- Follow the convention we have in other notifications regarind the context: use `production_uri` instead of `domain
- Use the internal `get_context_data()` and `extra_context=` to follow the pattern stablished for the `Notification` class.
- Make the new linter to pass.
- Use structlog instead of `print()` function
=> Notification: expand management command to follow conventions

docs/user/config-file/v2.rst
The example uses the 'pip' install method but the explanation suggests it should have used 'pip'.
---
- User's documentation (`docs`): https://docs--10489.org.readthedocs.build/en/10489/
- Developer's documentation (`dev`): https://dev--10489.org.readthedocs.build/en/10489/
=> docs: Correct typo

docs/user/build-customization.rst
---
- User's documentation (`docs`): https://docs--10486.org.readthedocs.build/en/10486/
- Developer's documentation (`dev`): https://dev--10486.org.readthedocs.build/en/10486/
=> Docs: use `$READTHEDOCS_OUTPUT` variable in examples

docs/user/config-file/examples/sphinx/.readthedocs.yaml
@humitos related to https://github.com/readthedocs/readthedocs.org/pull/10478 - yet another place to manage tool versions, albeit not so critical.
---
- User's documentation (`docs`): https://docs--10481.org.readthedocs.build/en/10481/
- Developer's documentation (`dev`): https://dev--10481.org.readthedocs.build/en/10481/
=> Docs: Update example Sphinx .readthedocs.yaml

requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Requirements updated with the new `inv requirements.update -p tzdata`
Fixes https://github.com/readthedocs/readthedocs.org/issues/10453
Note to @stsewd - the invoke command generated what I assume are expected results. But it contained an error at the end. We might also wanna print the text "Warning, this command takes some minutes to finish" :)
```
WARNING: Did not find branch or tag 'b696c37', assuming revision or ref.
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [25 lines of output]
/home/user/.virtualenvs/readthedocs.org/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
warnings.warn(msg, warning_class)
running …
```
=> Images: Add tzdata as explicit requirement

readthedocs/templates/projects/integration_webhook_detail.html
We probably want people to go here firstly: https://docs.readthedocs.io/en/latest/guides/setup/git-repo-automatic.html
=> Dashboard: Update docs link

readthedocs/analytics/tasks.py, readthedocs/telemetry/tasks.py
This task was cancelled again. The query shows a SELECT first that fetchs the whole rows. I think we can reduce this time/memory by only fetching the ids.
Sentry https://read-the-docs.sentry.io/issues/4006261064/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&stream_index=9
Related https://github.com/readthedocs/readthedocs-ops/issues/1291
=> DB: do not fetch `data` and others when deleting rows

.bowerrc
I had to disable strict SSL on Bower due to an error with jQuery: https://github.com/bower/bower/issues/2608
I'm not sure if this is strictly required, but I'm creating a PR in case we need to this in production as well.
Related #10356
=> Bower: disable `strict-ssl`

readthedocs/projects/tests/mockers.py
@stsewd getting a lot of these in tests:
```
[error    ] Failed to revoke build api key. [readthedocs.projects.tasks.builds] artifacts=[] build_id=1 builder=aef5bfe565c3 commit=a1b2c3 project_slug=project status=failed version_slug=latest
File "/usr/src/app/checkouts/readthedocs.org/readthedocs/projects/tasks/builds.py", line 765, in after_return
self.data.api_client.revoke.post()
File "/usr/src/app/checkouts/readthedocs.org/.tox/py310/lib/python3.10/site-packages/slumber/__init__.py", line 167, in post
resp = self._request("POST", data=data, files=files, params=kwargs)
File "/usr/src/app/checkouts/readthedocs.org/.tox/py310/lib/python3.10/site-packages/slumber/__init__.py", line 97, in _request
resp = self._store["session"].request(method, url, …
```
=> Tests: Mock revoking build API key?

readthedocs/api/v2/permissions.py
There is some noticeable time increase when hitting our APIs using a token. We can also look into changing the hashing algorithm https://github.com/florimondmanca/djangorestframework-api-key/issues/173#issuecomment-1563165222 later.
Instead of relying on the parent method,
we just now override the whole method to have
access to the key itself.
=> Build API key: don't fetch and validate key twice

docs/user/build-customization.rst
Example using `build.jobs.pre_create_environment` to update Conda. We will link this example in the email we will be sending to users when deprecating/removing `UPDATE_CONDA_STARTUP` feature flag.
See #9779
---
- User's documentation (`docs`): https://docs--10493.org.readthedocs.build/en/10493/
- Developer's documentation (`dev`): https://dev--10493.org.readthedocs.build/en/10493/
=> Docs: update Conda to its latest available version

docs/dev/settings.rst, readthedocs/api/v2/permissions.py, readthedocs/api/v2/views/model_views.py, readthedocs/rtd_tests/tests/test_api.py, readthedocs/rtd_tests/tests/test_api_permissions.py, readthedocs/settings/base.py, readthedocs/settings/docker_compose.py, readthedocs/settings/test.py
We have access to some write operations using a build API token, we no longer need to grant access to superusers.
- All usage of super/staff users have been removed from the API, they have read-only access as any other user now.
- APIRestrictedPermission has been renamed to ReadOnlyPermission, since that's what it checks now.
---
- User's documentation (`docs`): https://docs--10498.org.readthedocs.build/en/10498/
- Developer's documentation (`dev`): https://dev--10498.org.readthedocs.build/en/10498/
=>  API V2: remove write access to superusers

readthedocs/proxito/redirects.py, readthedocs/proxito/views/mixins.py, readthedocs/proxito/views/serve.py, readthedocs/search/documents.py, readthedocs/search/faceted_search.py
This should massively reduce the amount of logs we're showing:
Chart: https://chart-embed.service.newrelic.com/herald/026e34db-4e14-4867-8bce-85845402be24?height=400px&timepicker=true
=> Reduce logging of common redirects and expected items

readthedocs/projects/tests/test_build_tasks.py
While debugging some test assertions, I noticed that this was left out. It's possible because `assert_has_calls` doesn't care if there are additional calls before or after.
=> Test: Verify "cat .readthedocs.yaml" was called

.circleci/config.yml
Circle CI spends 1 minute initializing pre-commit on every build.
Using this example from the pre-commit docs should be enough to cache the pre-commit environments across our builds.
=> CI: Use a cache for pre-commit

docs/dev/install.rst, readthedocs/doc_builder/director.py, readthedocs/doc_builder/environments.py, readthedocs/projects/models.py
Remove the feature flag to decide whether or not Docker should use `gVisor`. This is currently enabled by default to all the projects since last week, so I think we are safe to remove it since it has been working fine.
Related #9779
=> Build: always use `gvisor` Docker runtime

docs/user/build-customization.rst
---
- User's documentation (`docs`): https://docs--10509.org.readthedocs.build/en/10509/
- Developer's documentation (`dev`): https://dev--10509.org.readthedocs.build/en/10509/
=> Remove a superfluous space character

readthedocs/oauth/services/github.py, readthedocs/oauth/services/gitlab.py
There is nothing we can do in this case. So, we are logging the exception instead of sending it to Sentry as an error.
In the future we could handle this exception differently and communicate these errors to the users so they can re-install Read the Docs app in their GH accounts.
Sentry: https://read-the-docs.sentry.io/issues/3526635712/
Based on: https://github.com/readthedocs/readthedocs.org/pull/10082
=> OAuth: catch `TokenExpiredError` exception

docs/dev/search-integration.rst
---
- User's documentation (`docs`): https://docs--10518.org.readthedocs.build/en/10518/
- Developer's documentation (`dev`): https://dev--10518.org.readthedocs.build/en/10518/
=> Docs (dev): update server side search integration doc

docs/conf.py
The current title is "{page title} - Read the Docs user documentation 9.15.0 documentation"
---
- User's documentation (`docs`): https://docs--10519.org.readthedocs.build/en/10519/
- Developer's documentation (`dev`): https://dev--10519.org.readthedocs.build/en/10519/
=> Docs: set title explicitly

docs/user/build-default-versions.rst, readthedocs/doc_builder/python_environments.py, readthedocs/projects/models.py
The logic was inverted and we were installing old MkDocs version to projects with `USE_MKDOCS_LATEST` feature flag.
Closes #10402
=> MkDocs: fix `USE_MKDOCS_LATEST` feature flag logic

readthedocs/projects/models.py, readthedocs/projects/tasks/builds.py, readthedocs/projects/tasks/utils.py, readthedocs/rtd_tests/tests/test_project_forms.py
We use AWS scale-in protection to protect our instances from being scaled-in automatically while running a build. This avoids killing the build in the middle while it's running.
Besides, it could help us to be more aggressive to scale-in if we consider without degrading user experience.
Related https://github.com/readthedocs/readthedocs-ops/issues/1324
Requires: https://github.com/readthedocs/readthedocs-ops/pull/1356
=> Builds: set scale-in protection before/after each build

docs/user/build-default-versions.rst, readthedocs/doc_builder/python_environments.py, readthedocs/projects/models.py
I created a new feature flag called `INSTALL_LATEST_CORE_REQUIREMENTS` that does
not depend on any other feature flag. Its goal is to always install the latest
Python packages.
We are trying to move away from pinning the dependencies on our side and telling
users to do that on their side if they want to have reproducible builds over
time.
I think this is the best outcome for new projects since they will immediately
use the latest versions of everything instead of old (and maybe broken)
dependencies.
I propose to set a particular date for this feature flag and make new projects
to start building with all the latest dependencies. This will, at least, stop
making the problem bigger. Later, we can decide how to communicate to old
projects that we are going to install the latest requirements …
=> Build: install all the latest Python "core requirements"

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/urls.py
We are settled on "addons" as a name for all of this, so I'm renaming the endpoint to use `/_/addons/`. Note that I'm keeping the old one so we don't break anything when releasing this.
=> Addons: rename endpoint to make it nicer

readthedocs/builds/tasks.py
Avoid logging known exceptions on Sentry when it's due to a user issue.
=> Celery: handle known exceptions on `delete_closed_external_versions`

dockerfiles/nginx/proxito.conf.template, readthedocs/projects/models.py, readthedocs/proxito/views/hosting.py
Related https://github.com/readthedocs/addons/issues/4
=> Addons: rename library

readthedocs/proxito/views/hosting.py
This data is consumed by the sponsorship addons to display an ad using EthicalAds.
Related https://github.com/readthedocs/addons/issues/67
Requires: https://github.com/readthedocs/readthedocs-ext/pull/546
=> Addons: return `ethicalads` data on `/_/addons/` endpoint

readthedocs/projects/urls/public.py
On the new dashboard, the project version list view does not have the
same features as the project detail view, yet both are using the same
underlying template code.
- Planning discussion: https://github.com/readthedocs/ext-theme/issues/191
- Closes: https://github.com/readthedocs/ext-theme/issues/92
=> Add conditional logic to replace project version list view

readthedocs/doc_builder/director.py, readthedocs/settings/base.py
It also updates the image to use Ubuntu 22.04 LTS.
=> Build: use a setting to define the Docker image for the clone step

docs/user/api/v3.rst, readthedocs/api/v3/filters.py, readthedocs/api/v3/tests/test_remoterepositories.py
This allows to perform queries like:
* http://devthedocs.org/api/v3/remote/repositories/?full_name=getnikola
* http://devthedocs.org/api/v3/remote/repositories/?full_name=readthedocs&expand=projects
Closes #10513
=> API: add `?full_name=` icontains filter on RemoteRepository

readthedocs/settings/base.py
The value has a trailing `,`, this makes it a tuple, docker doesn't like this.
=> Fix docker setting

docs/dev/install.rst
Closes #9351
Requires: https://github.com/readthedocs/common/pull/183
---
- User's documentation (`docs`): https://docs--10561.org.readthedocs.build/en/10561/
- Developer's documentation (`dev`): https://dev--10561.org.readthedocs.build/en/10561/
=> Development: install Docker and Docker Compose with official guides

docs/user/config-file/v2.rst, docs/user/guides/conda.rst, readthedocs/builds/constants_docker.py, readthedocs/rtd_tests/fixtures/spec/v2/schema.json
Our latest Mamba version is pretty old and it seems that it's not updating Conda to its latest version, even if we try to force it.
Closes #10564
---
- User's documentation (`docs`): https://docs--10572.org.readthedocs.build/en/10572/
- Developer's documentation (`dev`): https://dev--10572.org.readthedocs.build/en/10572/
=> Build: add `mambaforge-22.09` as newer Python tool

scripts/compile_version_upload_s3.sh
It was running it from the host and failing on CircleCI because it's not installed there.
Also, when running it locally it was showing the asdf version from the host instead from the container, where we are compiling these versions.
=> Build tools: run `asdf version` from inside the container

docs/user/user-defined-redirects.rst
This language somehow got removed. 
---
- User's documentation (`docs`): https://docs--10577.org.readthedocs.build/en/10577/
- Developer's documentation (`dev`): https://dev--10577.org.readthedocs.build/en/10577/
=> Clarify forced redirects

readthedocs/core/context_processors.py, readthedocs/rtd_tests/tests/test_notifications.py
This copies USE_SUBDOMAIN and USE_PROMOS pattern for use in the templates when
adding features for organizations/commercial. This would supersede checks like
``PRODUCTION_DOMAIN == "readthedocs.com"`` and friends.
=> Add USE_ORGANIZATIONS context variablea

docs/user/support.rst
This addresses a few issues with the support page:
- The first section mentions Stack Overflow, but we should probably
highlight our search first
- Adds some boundaries on our user support
- Adds example questions back for user support
- Directly calls out what we don't support
- Description of our support is broken up and needed a few updates
- Mentions reponse time of 1 day, which is accurate but doesn't match
our pricing
- Mention our support hours
- Cleans up some of the language
Rendered: https://docs--10580.org.readthedocs.build/en/10580/support.html
---
- User's documentation (`docs`): https://docs--10580.org.readthedocs.build/en/10580/
- Developer's documentation (`dev`): https://dev--10580.org.readthedocs.build/en/10580/
=> Update support page

readthedocs/api/v2/serializers.py, readthedocs/projects/models.py, readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_full.py, readthedocs/proxito/views/serve.py, readthedocs/rtd_tests/tests/test_backend.py
With this we can now exclude some projects from using the new implementation while testing it more broadly
by changing the date of the feature.
When we are ready to enable it for all projects, we can remove the USE_UNRESOLVER_WITH_PROXITO, and leave the other setting while we migrate the missing projects.
To avoid introducing another DB call, I'm caching the features from a project.
=> Proxito: test new implementation more broadly

readthedocs/projects/tasks/utils.py, readthedocs/templates/projects/notifications/deprecated_config_file_used_email.html, readthedocs/templates/projects/notifications/deprecated_config_file_used_email.txt
We wanted to contact more users with the first email and then only contact those projects with a build in the last year only.
This reverts commit 3d99b0bc5944777c32760f84f067fac7d0eb58d5.
=> Revert "Contact projects with a build in the last 3 years"

readthedocs/settings/base.py
This setting was required during the Django 4.2 migration only and it can be removed now.
**Merge this PR after deploying Django 4.2 upgrade**
=> Settings: remove CSRF_COOKIE_MASKED

docs/user/guides/setup/git-repo-manual.rst
---
- User's documentation (`docs`): https://docs--10632.org.readthedocs.build/en/10632/
- Developer's documentation (`dev`): https://dev--10632.org.readthedocs.build/en/10632/
=> Small wording cleanup on Integration howto

readthedocs/api/v2/serializers.py, readthedocs/projects/models.py, readthedocs/projects/tests/test_models.py, readthedocs/rtd_tests/tests/test_api.py
This will allow us to migrate a client from .com to the new implementation, without downtime or changes in their setup. There is another PR in coporate-ops, and the steps to do the migration will be in the meta issue.
- Ref https://github.com/readthedocs/readthedocs.org/issues/10181
- Ref https://github.com/readthedocs/readthedocs.org/issues/10408
- Ref https://github.com/readthedocs/meta/issues/124
=> Proxito: allow to generate proxied API URLs with a prefix

readthedocs/settings/base.py
On Django 4.1 the cached Loader is enabled on `DEBUG=True`. This commit reverts this behavior because it makes harder to work on the new templates.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1635
=> Development: disable cached Loader on `DEBUG=True`

readthedocs/doc_builder/backends/sphinx.py, readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl, readthedocs/projects/models.py
We are not installing `sphinx-rtd-theme` automatically on new projects. However, we are setting `sphinx_rtd_theme` automatically on their `docs/conf.py`.
This PR removes that magic to auto-set the theme and leave the theme to what the user has defined.
* Related: https://github.com/readthedocs/readthedocs.org/issues/2483
* Closes: https://github.com/readthedocs/readthedocs.org/issues/10626
=> Build: do not set `sphinx_rtd_theme` theme automatically

readthedocs/projects/forms.py, readthedocs/projects/views/mixins.py, readthedocs/projects/views/private.py, readthedocs/rtd_tests/tests/test_project_forms.py, readthedocs/rtd_tests/tests/test_project_views.py
This commit removes the "Extra/Advanced" step and moves the "language" attribute to the "Basics" step -- the first one, since that field is important.
Closes #10392
=> Import: remove extra/advanced step from project import wizard

readthedocs/settings/base.py, requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
This package allows us to store the periodic Celery tasks in the database.
Hopefully, it will help us to solve the issue we are having that periodic tasks
are triggered when building the AMI and also on deploys.
Closes readthedocs/readthedocs-ops#1384
=> Celery: use django-celery-beat scheduler

docs/user/user-defined-redirects.rst
I spotted a typo when reading the "Custom and built-in redirects" page. Just a 1-character change to fix it up!
---
- User's documentation (`docs`): https://docs--10651.org.readthedocs.build/en/10651/
- Developer's documentation (`dev`): https://dev--10651.org.readthedocs.build/en/10651/
=> docs: typo fix on "Custom and built-in redirects" page

readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
This is missing from #10638
Closes #10654
=> Build: remove `using_rtd_theme` variable

.circleci/config.yml, readthedocs/embed/v3/tests/test_external_pages.py, readthedocs/embed/v3/tests/test_internal_pages.py, readthedocs/embed/v3/tests/utils.py, tox.embedapi.ini
- Test only the latest minor version of each major version
- Add newer versions we weren't testing
=> Tests: Update Sphinx test matrix for EmbedAPI

.circleci/config.yml
Pre-commit depends on this requirement file,
if it's changed, the cache key should be invalidated.
extracted from https://github.com/readthedocs/readthedocs.org/pull/10642/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47, since it's making all PRs fail.
=> CI: Add requirements/testing.txt to pre-commit cache key

readthedocs/settings/docker_compose.py
When using ngrok + https, forms are blocked
because the schema from the final URL doesn't match the one from the origin header.
Previously only the host was checked, this
was changed in 4.0
https://docs.djangoproject.com/en/4.2/releases/4.0/#csrf
ref https://docs.djangoproject.com/en/4.2/ref/settings/#secure-proxy-ssl-header
=> Set `SECURE_PROXY_SSL_HEADER` when using docker compose

readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Use the global value or `alabaster` if not defined by the user. It default to `alabaster` because it's the default value for Sphinx.
Closes #10662 
Related #10638
=> Build: define `html_theme` variable

readthedocs/doc_builder/director.py, readthedocs/settings/base.py
We only need to do this in production, it's breaking our tests.
=> Tests: don't enforce hardcoded brownouts

readthedocs/proxito/views/hosting.py
* Do not show "Versions" section when project is single version
* Handle downloads when `version=None`
Solves: https://read-the-docs.sentry.io/issues/4437207301/?project=148442
Related https://github.com/readthedocs/readthedocs.org/issues/10685
Closes #10680
=> Addons: manage single version projects

requirements/deploy.in, requirements/deploy.txt, requirements/docker.in, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Now we are on Django 4.2 we can use the latest version of psycopg.
Closes #10596
=> Requirements: use `psycopg3`

readthedocs/proxito/views/hosting.py
* Define `_get_project` and `_get_version` as individual methods because these   are required by the API permissions.
* Use `user=` attribute when performing the query for the versions to be  displayed in the flyout.
Requires https://github.com/readthedocs/readthedocs.org/pull/10704/
=> Addons: allow to be extended by corporate

readthedocs/api/v2/views/footer_views.py, readthedocs/rtd_tests/tests/test_footer.py
The current queryset includes public versions only, but this is a problem on .com, since we have private versions there.
Including the user in the queryset will include
private versions the user has access to.
=> Footer API: include current user in queryset

readthedocs/config/config.py
https://blog.readthedocs.com/use-system-packages-deprecated/ responses 404.
Is https://blog.readthedocs.com/drop-support-system-packages/ expected?
=> Fix blog post URL

docs/user/build-customization.rst, docs/user/config-file/v2.rst
This not mentions we are testing the new addons integration.
---
- User's documentation (`docs`): https://docs--10708.org.readthedocs.build/en/10708/
- Developer's documentation (`dev`): https://dev--10708.org.readthedocs.build/en/10708/
=> Docs: update `build.commands` note

readthedocs/projects/models.py, readthedocs/proxito/tests/responses/v0.json, readthedocs/proxito/views/hosting.py
Required for https://github.com/readthedocs/addons/pull/118
=> Addons: include `hotkeys` in API response

requirements/deploy.txt, requirements/docker.in, requirements/docker.txt, requirements/docs.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
This package works fine and the upgrade was transparent. However, it seems that New Relic agent is not prepared to collect data from v3.x and send it to their servers.
https://docs.newrelic.com/docs/apm/agents/python-agent/getting-started/instrumented-python-packages/#instance-details
> The Python agent should be able to track database queries for any Python
> DB-API 2.0 compliant modules
`psycopg3` is compatible with DB-API 2.0, but for some reason doesn't work. I'm reverting it for now and we can take a look later.
Note this commit also upgrades Django, due to a security issue that was reported:
https://docs.djangoproject.com/en/4.2/releases/4.2.5/
Reverts #10667
=> Requirements: revert upgrade to `psycopg==3.x`

docs/user/tutorial/index.rst
There are some users having problems with this.
It's better to make this config key explicit.
Besides, we will eventually deprecate the "auto-find" the `conf.py` file.
Follows https://github.com/readthedocs/tutorial-template/pull/53/
---
- User's documentation (`docs`): https://docs--10718.org.readthedocs.build/en/10718/
- Developer's documentation (`dev`): https://dev--10718.org.readthedocs.build/en/10718/
=> Docs: make `sphinx.configuration` in the tutorial

readthedocs/rtd_tests/tests/test_footer.py
We should not use `project.users` since it's not a reliable way to get the users for a project. We need to use `AdminPermission` which works fine in community and commercial respecting all the permissions involved.
=> FooterAPI: use `AdminPermission` when working with object users

docs/user/faq.rst
I opened multiple commits to be self-contained in case you want to review one by one.
Related https://github.com/readthedocs/readthedocs.org/issues/10692#issuecomment-1716325074
---
- User's documentation (`docs`): https://docs--10732.org.readthedocs.build/en/10732/
- Developer's documentation (`dev`): https://dev--10732.org.readthedocs.build/en/10732/
=> Docs: review and update the whole FAQ page.

readthedocs/settings/base.py
The goal here is to see if this is causing the DB slowdown, so we are running it both more frequently, and offset from the hour. 
Refs https://github.com/readthedocs/readthedocs-ops/issues/1377#issuecomment-1717993801
=> Change frequency of pageview delete code

readthedocs/proxito/views/hosting.py
Use `unresolved_url` to get the final project requested from the URL. This is needed for subproject since it's the only place where it's present.
Previously, we were getting the project from the `unresolved_domain` which does not give us the `subproject` because it's not present in the domain itself.
Tests will be added in https://github.com/readthedocs/readthedocs.org/issues/10685
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1622
=> Addons: get final project (e.g. `subproject`)

readthedocs/projects/tasks/search.py
This task was replaced in https://github.com/readthedocs/readthedocs.org/pull/10696.
We need to merge this after tomorrow's deploy.
=> Tasks: remove old fileify task

readthedocs/proxito/tests/responses/v2.json, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Move `X-RTD-Hosting-Integration-Version` header to `api-version` querystring parameter. This has some benefits:
- make links to this URL clickable (there is no need to use a browser extension to send a specific header in the request)
- easier to cache using the default strategy supported by CF
Related #10536
=> Addons: move the HTTP header to a GET parameter

readthedocs/embed/v3/tests/test_access.py, readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_headers.py, readthedocs/search/tests/test_proxied_api.py
- Only add CORS headers on community site
- Explicit host on `Access-Control-Allow-Origin`
- Only query the database if the host ends with `RTD_EXTERNAL_VERSION_DOMAIN`
- Add more tests
Continuation of #10737
=> Proxito: update CORS settings

docs/user/build-customization.rst
This PR updates documentation to add an example using the Asciidoctor toolchain.
---
- User's documentation (`docs`): https://docs--10759.org.readthedocs.build/en/10759/
- Developer's documentation (`dev`): https://dev--10759.org.readthedocs.build/en/10759/
=> Docs: add asciidoc example

docs/user/api/v3.rst, readthedocs/api/v3/serializers.py, readthedocs/api/v3/tests/responses/projects-detail.json, readthedocs/api/v3/tests/responses/projects-list.json, readthedocs/api/v3/tests/responses/projects-list_POST.json, readthedocs/api/v3/tests/responses/projects-subprojects-detail.json, readthedocs/api/v3/tests/responses/projects-subprojects-list.json, readthedocs/api/v3/tests/responses/projects-subprojects-list_POST.json, readthedocs/api/v3/tests/responses/projects-superproject.json, readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json, readthedocs/api/v3/tests/responses/remoterepositories-list.json, readthedocs/proxito/tests/responses/v0.json
For some reason we weren't returning this field in the API response. I understand there is no reason to not do it.
I added `single_version` field in the response API so we can make some decisions from the addons based on its value.
Required by https://github.com/readthedocs/addons/issues/140
---
- User's documentation (`docs`): https://docs--10758.org.readthedocs.build/en/10758/
- Developer's documentation (`dev`): https://dev--10758.org.readthedocs.build/en/10758/
=> APIv3: return `single_version` field on `Project` resource

docs/user/build-customization.rst
I created a version on `test-builds` for this and it works fine: https://test-builds.readthedocs.io/en/asciidoctor/
---
- User's documentation (`docs`): https://docs--10763.org.readthedocs.build/en/10763/
- Developer's documentation (`dev`): https://dev--10763.org.readthedocs.build/en/10763/
=> Docs: update example for AsciiDoc to simplify it a little

readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_headers.py
After testing this more thoroughly,
allowing cross-origin requests on commercial should be safe for documentation pages.
Using `*` doesn't allow credentials, and we are also not allowing cross-origin requests for private versions. Basically, we have a double protection :D.
=> Proxyto: Allow CORS on commercial on public docs pages

.circleci/config.yml
Before upgrading to 8.x, we need to upgrade to 7.17.13.
This is mainly so we can test the upgrade process
outside the ES cluster.
=> Test ES upgrade to 7.17.13

readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_headers.py
There is no need to check if the version is public, since we are setting the header to `*`,
and we aren't allowing to pass credentials.
=> Proxito: remove one query from the middleware

docs/dev/install.rst, docs/dev/settings.rst, readthedocs/api/v3/tests/mixins.py, readthedocs/core/context_processors.py, readthedocs/core/resolver.py, readthedocs/embed/tests/test_api.py, readthedocs/embed/v3/tests/test_access.py, readthedocs/embed/v3/tests/test_basics.py, readthedocs/embed/v3/tests/test_external_pages.py, readthedocs/embed/v3/tests/test_internal_pages.py, readthedocs/projects/views/private.py, readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_old_redirects.py, readthedocs/rtd_tests/tests/test_api.py, readthedocs/rtd_tests/tests/test_build_notifications.py, readthedocs/rtd_tests/tests/test_core_tags.py, readthedocs/rtd_tests/tests/test_footer.py, readthedocs/rtd_tests/tests/test_notifications.py, readthedocs/rtd_tests/tests/test_privacy.py, readthedocs/rtd_tests/tests/test_redirects.py, readthedocs/rtd_tests/tests/test_resolver.py, readthedocs/rtd_tests/tests/test_single_version.py, readthedocs/rtd_tests/tests/test_version.py, readthedocs/search/api/v3/tests/test_api.py, readthedocs/search/tests/test_api.py, readthedocs/search/tests/test_views.py, readthedocs/settings/base.py, readthedocs/settings/docker_compose.py, readthedocs/settings/proxito/base.py, readthedocs/settings/test.py
Closes https://github.com/readthedocs/readthedocs.org/issues/10767
---
- User's documentation (`docs`): https://docs--10799.org.readthedocs.build/en/10799/
- Developer's documentation (`dev`): https://dev--10799.org.readthedocs.build/en/10799/
=> Proxito: always use subdomain for serving docs

readthedocs/projects/tasks/builds.py
This allows us to have a numeric value in the output and be able to filter it using `>` and `<` symbols on New Relic queries.
=> Logs: always log documentation size in megabytes

scripts/compile_version_upload_s3.sh
Quick fix to allow pre-building `build.tools` versions successfully.
See
https://app.circleci.com/pipelines/github/readthedocs/readthedocs-docker-images/273/workflows/db4e9204-0b2e-4a1d-aff1-de4e075396da/jobs/478 to understand the issue in deep.
=> Script: compile versions for S3

readthedocs/builds/constants_docker.py
There is an error with 3.12,
till the solve that problem, we are going to rollback to 3.11 as the default version for "3".
Ref https://github.com/readthedocs/readthedocs.org/issues/10832
=> Build (python): default 3 to 3.11

docs/user/guides/best-practice/links.rst
---
- User's documentation (`docs`): https://docs--10837.org.readthedocs.build/en/10837/
- Developer's documentation (`dev`): https://dev--10837.org.readthedocs.build/en/10837/
=> Fix broken link syntax

scripts/compile_version_upload_s3.sh
We hit a problem with Python 3.12 and the outdated version of pip that we have pre-installed.
Python ships with a vendored version of pip,
and we install the latest version of pip and setuptools on each build before installing the requirements.
The only breaking change here would be for projects using build.commands, setuptools won't be available anymore, pip is vendored by Python, so that shouldn't be a problem. I think we are fine not installing setuptools,
build.commands is in beta, so we can get away with this :)
Fixes https://github.com/readthedocs/readthedocs.org/issues/10832
We may even consider not installing virtualenv on python3.x and just use venv.
=> Build: don't pre-install pip and setuptools in images

scripts/compile_version_upload_s3.sh
https://github.com/readthedocs/readthedocs.org/pull/10834 didn't solve https://github.com/readthedocs/readthedocs.org/issues/10832.
Having an outdated version of pip is still the main problem, but the outdated version of pip didn't come from the python installation, but from the virtualenv creation.
When creating the environment, virtualenv installs some specfic/outdated versions of pip/setuptools/wheels.
https://github.com/pypa/virtualenv/blob/20.7.2/src/virtualenv/seed/wheels/embed/__init__.py
=> Build: install compatible version of virtualenv in images

docs/user/user-defined-redirects.rst
The new implementation of proxito is the default now.
---
- User's documentation (`docs`): https://docs--10817.org.readthedocs.build/en/10817/
- Developer's documentation (`dev`): https://dev--10817.org.readthedocs.build/en/10817/
=> Docs: update root language redirect docs

docs/user/guides/setup-single-sign-on-github-gitlab-bitbucket.rst
Had a user ask about this, and we're checking for `admin` on the API response:
https://github.com/readthedocs/readthedocs.org/blob/14c6a9c546e096e1ebf97775e88248eb92972fde/readthedocs/oauth/services/github.py#L163-L165
---
- User's documentation (`docs`): https://docs--10822.org.readthedocs.build/en/10822/
- Developer's documentation (`dev`): https://dev--10822.org.readthedocs.build/en/10822/
=> Clarify admin permission

docs/user/advertising/index.rst
Not sure why this wasn't linked previously.
---
- User's documentation (`docs`): https://docs--10843.org.readthedocs.build/en/10843/
- Developer's documentation (`dev`): https://dev--10843.org.readthedocs.build/en/10843/
=> Keep Ad Customization in the docs

readthedocs/builds/constants_docker.py
Reverts readthedocs/readthedocs.org#10833
Builds using python 3.12 are fixed now. Ref https://github.com/readthedocs/readthedocs.org/pull/10844.
=> Revert "Build (python): default 3 to 3.11"

readthedocs/proxito/tests/test_hosting.py
In https://github.com/readthedocs/readthedocs.org/pull/10852 I forgot that we actually need to set the privacy level of the version, not the project.
=> Tests: set privacy level explicitly

readthedocs/proxito/tests/test_old_redirects.py, readthedocs/redirects/querysets.py
We were using the path (filename) to match
prefix redirects, but we should be using the full_path.
=> Redirects: fix prefix redirects

docs/user/build-customization.rst
Tools like reno depend on a complete git history. Simply unshallowing a clone is not sufficient, as we specifically fetch from the branch or tag that we are building docs for, e.g.:
git fetch origin --force --prune --prune-tags --depth 50 refs/heads/main:refs/remotes/origin/main
Add documentation describing how you can correct this if necessary.
---
- User's documentation (`docs`): https://docs--10795.org.readthedocs.build/en/10795/
- Developer's documentation (`dev`): https://dev--10795.org.readthedocs.build/en/10795/
=> docs: Document how to fetch additional branches

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Builds are sorted by `-date` by default, so we need the `.first()` instead of the `.last()`.
=> Addons: return the `.first()` object

dockerfiles/nginx/proxito.conf.template
I made a mistake and hardcoded `latest` when testing this, but it should be `$rtd_version` which is grabbed from the HTTP header sent from the app.
=> NGINX: inject the proper `readthedocs-version-slug`

readthedocs/core/unresolver.py
All projects are migrated now, we don't need this.
=> Unresolver: remove old language code compatibility

readthedocs/proxito/views/hosting.py
This small improvements reduces the db query from ~20ms to ~1ms.
Original query:
```
Limit  (cost=6753.56..6753.77 rows=21 width=24) (actual time=26.139..26.144 rows=13 loops=1)
->  HashAggregate  (cost=6753.56..6753.87 rows=31 width=24) (actual time=26.138..26.142 rows=13 loops=1)
Group Key: projects_feature.feature_id
->  Hash Right Join  (cost=1.70..6556.54 rows=78808 width=24) (actual time=0.055..26.118 rows=54 loops=1)
Hash Cond: (projects_feature_projects.feature_id = projects_feature.id)
Filter: ((projects_feature_projects.project_id = 256207) OR ((projects_feature.add_date > '2018-12-05 10:47:06.794648+00'::timestamp with time zone) AND projects_feature.default_true) OR ((projects_feature.add_date <= '2018-12-05 10:47:06.794648+00'::timestamp with time zone) AND …
```
=> Addons: improve DB query for `projects_feature` table

readthedocs/core/resolver.py, readthedocs/rtd_tests/tests/test_resolver.py
Simplify a couple of things, and we can remove the overrides from .com after this.
- _get_canonical_project and _get_canonical_project_data are basically the same, the former tries to recursively resolve the project for cases that we don't really support, and the second just checks for the cases that we do support and returns the relationship in case of a subproject. So I just renamed _get_canonical_project_data to _get_canonical_project.
- We were passing the project slug when resolving the path (this was a residual from where we were allowing `USE_SUBDOMAIN=False`).
- Resolving is now split into two steps: resolving the domain, and resolving the path.
- We were using `require_https` for .com only, this was since on .com we were using the https attribute to track the progress of a custom …
=> Resolver: refactor

readthedocs/analytics/models.py, readthedocs/api/v2/serializers.py, readthedocs/api/v3/serializers.py, readthedocs/embed/views.py, readthedocs/projects/models.py, readthedocs/projects/views/mixins.py, readthedocs/projects/views/public.py, readthedocs/proxito/views/serve.py
This may result in one queryset less in some cases, others will remain the same.
=> Resolver: use new methods to resolve documentation pages

docs/dev/design/redirects.rst
Didn't include anything about built-in redirects, should I touch that too in this document? Maybe in another one?
Ref https://github.com/readthedocs/readthedocs.org/issues/4221
---
- User's documentation (`docs`): https://docs--10825.org.readthedocs.build/en/10825/
- Developer's documentation (`dev`): https://dev--10825.org.readthedocs.build/en/10825/
=> Redirects (design doc): improving existing functionality

readthedocs/core/filters.py, readthedocs/organizations/filters.py, readthedocs/organizations/tests/test_filters.py, readthedocs/organizations/views/private.py, readthedocs/organizations/views/public.py
This filters are used for the new dashboard UI, they are not API filters.
These were a challenge to create, as django-filter is really opinionated
about the way it should work, and doesn't quite agree with use cases
that need to use filtered querysets (such as limiting the field choices
to objects the organization is related to).
I went through many permutations of this code, trying to find a pattern
that was not obtuse or awful. Unfortunately, I don't quite like the
patterns here, but because all of the django-filter magic happens at the
class level instead of at instantiation time, every direction required
hacks to obtain something reasonable.
Given the use we have for filters in our UI, I wouldn't mind making
these into a more generalized filter solution.
I think I'd like to replace …
=> Add organization view UI filters

docs/user/config-file/v2.rst
---
- User's documentation (`docs`): https://docs--10883.org.readthedocs.build/en/10883/
- Developer's documentation (`dev`): https://dev--10883.org.readthedocs.build/en/10883/
=> Make Ubuntu callout correct

readthedocs/doc_builder/director.py, readthedocs/projects/tests/test_build_tasks.py
commit_name is making use of `Project.remote_repository`, which we don't have in the API, I tried to fix it in https://github.com/readthedocs/readthedocs.org/pull/10885, but other tests are failing, and looks like we have the special case where latest has the identifier set to `None` to skip the checkout step. So I'll need to think in another solution... in the meantime I'm just reverting this change.
Reverts readthedocs/readthedocs.org#10879
=> Revert "Build: use tag name for checkout"

docs/user/versions.rst
Relates to issue: https://github.com/readthedocs/readthedocs.org/issues/8789#issuecomment-1783302709
Closes #6096
Closes #8789
This updates the *Version warning* doc section to communicate the new functionality in an upcoming addon PR (https://github.com/readthedocs/addons/pull/174) and also notes that the feature toggle is currently not visible to all projects.
---
- User's documentation (`docs`): https://docs--10877.org.readthedocs.build/en/10877/
- Developer's documentation (`dev`): https://dev--10877.org.readthedocs.build/en/10877/
=> docs: update documentation around version warning banner

readthedocs/api/v2/views/integrations.py
This also fixes https://github.com/readthedocs/readthedocs.org/issues/10902, the github event header name was missing the `X-`
=> Integrations: better error message for integrations without a secret

readthedocs/projects/tasks/search.py
Looks like some imported files have their build id set to None, probably some old data.
Ref https://read-the-docs.sentry.io/issues/4491624505/?project=148442&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=13
=> Search: check for build being None

docs/dev/design/new-notifications-system.rst
Initial design document to discuss the implementation of a new notification system.
Closes #10598 
:books: Documentation previews :books: https://dev--10890.org.readthedocs.build/en/10890/design/new-notifications-system.html
Related issues:
* https://github.com/readthedocs/readthedocs.org/issues/4226
* https://github.com/readthedocs/readthedocs.org/issues/3399
* https://github.com/readthedocs/meta/discussions/126
* https://github.com/readthedocs/readthedocs.org/issues/5909
* https://github.com/readthedocs/readthedocs.org/issues/9110
* https://github.com/readthedocs/readthedocs.org/issues/9279
* https://github.com/readthedocs/readthedocs.org/issues/4235
=> Design doc: new notification system

readthedocs/projects/tasks/search.py, readthedocs/search/utils.py
The default is 500 documents, our documents have nested objects, that can make the final document huge, and timeout ES.
closes https://github.com/readthedocs/readthedocs.org/issues/10911
Ref https://github.com/readthedocs/readthedocs.org/issues/10911#issuecomment-1819688230
=> Search: index in small chunks

readthedocs/rtd_tests/fixtures/spec/v2/schema.json
Noticed this while reading the schema.
Thanks for your work on ReadtheDocs!
=> Fix a typo in the word 'Sphinx'

readthedocs/config/config.py
When a build fails due to a missing config file, it's not always clear what action should be taken. For example: 
https://github.com/python/pythondotorg/pull/2327#issuecomment-1817764006
I suggest including a link to a webpage that explains what action is needed. Perhaps this blog post?
https://blog.readthedocs.com/migrate-configuration-v2/
=> Add link to docs in error message

readthedocs/projects/models.py, readthedocs/proxito/tests/test_full.py
Small code cleaning to continue removing old feature flags.
=> Feature flag: remove `CDN_ENABLED` which is not used anymore

docs/dev/design/new-notifications-system.rst
Endpoint to update a notification.
This will be used by the front-end to mark a notification as read, for example.
Ref: https://github.com/readthedocs/readthedocs.org/pull/10890#discussion_r1403203545
---
- User's documentation (`docs`): https://docs--10919.org.readthedocs.build/en/10919/
- Developer's documentation (`dev`): https://dev--10919.org.readthedocs.build/en/10919/
=> Design: small update to add a PATCH endpoint

readthedocs/organizations/forms.py
This allows the field/widget in the form to be empty on submit.
- Fixes #10934
=> Allow empty project list on organization team form

readthedocs/settings/docker_compose.py
This is to avoid stashing/unstashing settings and to push this towards a local .envrc file instead, where the secrets can be encrypted. Keeping unencrypted settings in stash history is a pattern to avoid.
- Requires https://github.com/readthedocs/common/pull/191
=> Allow override of env settings from host

readthedocs/templates/projects/import_config.html
=> Fix YAML indentation in example `.readthedocs.yaml`

docs/dev/subscriptions.rst, readthedocs/settings/docker_compose.py
- Mention the use of environment variables for testing
- Add a default for the stripe key (otherwise the instance won't start)
Hit this today while spinning up my dev environment
Ref https://github.com/readthedocs/readthedocs.org/pull/10959
---
- User's documentation (`docs`): https://docs--10992.org.readthedocs.build/en/10992/
- Developer's documentation (`dev`): https://dev--10992.org.readthedocs.build/en/10992/
=> Development: update steps for testing subscriptions

docs/user/build-customization.rst
---
- User's documentation (`docs`): https://docs--10997.org.readthedocs.build/en/10997/build-customization.html#override-the-build-process
- ~Developer's documentation (`dev`): https://dev--10997.org.readthedocs.build/en/10997/~
=> Fix ref to the "new addons integrations" blog post @ custom build doc

readthedocs/templates/base.html
Keep rendering regular one-time Django messages attached to the request, but remove the logic used for sticky/permanent messages from `django-messages-extends`.
Closes #10988
Related https://github.com/readthedocs/ext-theme/issues/259
=> Remove leftovers from `django-messages-extends`

requirements/deploy.txt, requirements/pip.in, requirements/pip.txt
Refs https://github.com/readthedocs/readthedocs.org/issues/10990
=> Fix structlog by downgrading it

readthedocs/notifications/messages.py, readthedocs/notifications/tests/test_messages.py, readthedocs/oauth/notifications.py, readthedocs/subscriptions/notifications.py
Related to https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440756414.
=> Notifications: small fixes found after reviewer

requirements/docker.txt, requirements/testing.txt
In #11003 we downgrade structlog, but we didn't update all the requirement files.
=> pip-compile fixes

readthedocs/doc_builder/director.py
We are ahead of the dates for these deprecations, so they became the default path now and we have to always check for them.
=> Build: remove browndates for config file

readthedocs/oauth/notifications.py, readthedocs/subscriptions/notifications.py
We need to `escape()` some of the values that are controlled by the user before being able to format them.
Related #11016
=> Notifications: use `instance.slug` instead of `instance.name`

readthedocs/projects/tasks/builds.py
Sentry issue: https://read-the-docs.sentry.io/issues/4841607731/
=> Notifications: save `format_values` when `on_retry` exception

readthedocs/oauth/tasks.py
I found this on production at
https://read-the-docs.sentry.io/issues/4838793200/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=3
=> Notification: oauth typo on URL name

readthedocs/doc_builder/environments.py
I found this on production while doing a deploy:
https://read-the-docs.sentry.io/issues/4838661275/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=8
=> Notifications: typo on constant

readthedocs/projects/tasks/builds.py
I found this on production.
https://read-the-docs.sentry.io/issues/4838648613/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=0
=> Build: typo on `on_retry`

readthedocs/organizations/models.py, readthedocs/organizations/templates/organizations/organization_detail.html
This work was missed when implementing the new notification system.
Related https://github.com/readthedocs/ext-theme/issues/260
=> Notifications: render `Organization` notifications on details page

readthedocs/config/notifications.py, readthedocs/core/notifications.py, readthedocs/domains/notifications.py, readthedocs/notifications/messages.py, readthedocs/notifications/tests/test_messages.py, readthedocs/oauth/notifications.py, readthedocs/projects/notifications.py, readthedocs/subscriptions/notifications.py
=> Notifications: use Template's Django engine to render them

readthedocs/config/config.py, readthedocs/config/exceptions.py, readthedocs/config/notifications.py, readthedocs/config/tests/test_config.py
=> Config: better validation error for `conda.environment`

readthedocs/settings/docker_compose.py
We had it set to `None` to avoid spam in our own addresses. However, it makes sense to have a valid email here so we can see templates rendered properly when doing development.
=> Development: define `SUPPORT_EMAIL` setting

readthedocs/builds/models.py, readthedocs/rtd_tests/tests/test_api.py
When the build is retried for any reason we call `build.reset()` to make sure the build is fresh. I'm adding the removal of all the notifications that were attached to the build when reseting it.
=> Build: reset notifications when reseting a build

readthedocs/projects/forms.py, readthedocs/templates/projects/project_advanced.html, readthedocs/templates/projects/project_advanced_settings_helptext.html
These settings have been disabled for 6 months already. They are useless now that we _require_ a `readthedocs.yaml` file.
Closes https://github.com/readthedocs/ext-theme/issues/159
=> Admin: remove "default settings"

readthedocs/proxito/tests/test_old_redirects.py, readthedocs/redirects/models.py
An additional check was added, we now check if to_url is a subpath of from_url.
=> Redirects: fix infinite loop detection

readthedocs/config/config.py, readthedocs/config/tests/test_config.py
Solves https://github.com/readthedocs/readthedocs.org/pull/10979#issuecomment-1896036953
=> Config: allow missing `conda.environment` when using `build.commands`

readthedocs/projects/forms.py, readthedocs/projects/models.py, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Add all the configuration options to the `AddonsConfigForm` so the user is able to enable/disable each of the addons independently.
This is the initial version of this work. We will keep adding more configuration options to each of the addons. That's why I decided to create one section per each. In the future, instead of just a regular `FieldSet` we can get more fancy and use tabs instead (creating a custom class or giving it a try to https://crispy-forms-gds.readthedocs.io/en/latest/components/tabs.html)
Closes https://github.com/readthedocs/ext-theme/issues/211
=> Addons: update form to show all the options

readthedocs/core/resolver.py, readthedocs/rtd_tests/tests/test_resolver.py
We were using .format over a user controlled string, the project prefix. This can be used to traverse to some private variables in some cases (this isn't the case here), or to cause a DoS by using an expensive format operation (`{language:>999999999999}`).
This isn't a security issue, since we don't expose the prefix to users yet.
=> Resolver: don't use str.format

readthedocs/core/utils/filesystem.py, readthedocs/projects/tests/test_build_tasks.py
This is useful outside this module.
=> Expose `assert_path_is_inside_docroot` function

docs/conf.py, docs/user/guides/jupyter.rst
Builds are failing due to a warning of a broken link.
---
- User's documentation (`docs`): https://docs--11047.org.readthedocs.build/en/11047/
- Developer's documentation (`dev`): https://dev--11047.org.readthedocs.build/en/11047/
=> Docs: remove dead example

readthedocs/api/v3/serializers.py, readthedocs/api/v3/tests/test_organizations.py, readthedocs/api/v3/views.py
This view was used on "Read the Docs for Business". See https://docs.readthedocs.io/en/stable/api/v3.html#organizations
It was deleted in
https://github.com/readthedocs/readthedocs.org/pull/11009/files#diff-1b2fcccf6a94ac362220161670adaf288aaece7381f18909cdd1da5e044d134a
I put them back here and make them extendable, so we can overwrite one of them from "Read the Docs for Business".
=> APIv3: bring back `OrganizationsViewSet` that was removed

docs/user/api/v3.rst
---
- User's documentation (`docs`): https://docs--11053.org.readthedocs.build/en/11053/
- Developer's documentation (`dev`): https://dev--11053.org.readthedocs.build/en/11053/
=> Docs: move warning from embed API to the top

readthedocs/projects/tasks/builds.py
Solves https://read-the-docs.sentry.io/issues/4850559255/events/3fd4057a003e41f0ac6fbe080e3f7d14/
=> Build: don't attach notification when build failed `before_start`

readthedocs/core/context_processors.py, readthedocs/notifications/apps.py, readthedocs/notifications/querysets.py, readthedocs/notifications/signals.py, readthedocs/notifications/tests/test_querysets.py, readthedocs/notifications/tests/test_signals.py, readthedocs/projects/views/private.py
=> Notification: cancel notifications automatically

readthedocs/embed/v3/tests/test_basics.py, readthedocs/embed/v3/tests/test_external_pages.py, readthedocs/settings/base.py, readthedocs/settings/docker_compose.py
The patterns were not ending with `$`,
so any domain that started with the allowed domain would be allowed (docs.python.org.example.com).
This isn't a security issue, since including content from a domain that isn't allowed is not differently than including content from a domain that is hosted on RTD (users shouldn't allow including content from projects they don't trust).
This is mostly to prevent abuse.
=> Embed API: fix regex patterns for allowed external domains

readthedocs/projects/forms.py, readthedocs/rtd_tests/tests/test_domains.py
We have a CNAME from our external domain to readthedocs.io, making these domains valid if they are added to a project.
This isn't a security issue, since our code won't resolve those domains because custom domains are checked last, and we have this protection in place:
https://github.com/readthedocs/readthedocs.org/blob/7daff3d6cc953898934cc80cba53403d6e0fa259/readthedocs/core/unresolver.py#L590-L594
=> Custom domain: don't allow external domain

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
When _not sending `url=` parameter_, we were returning the lastest build by date, but we need to filter it by `state=finished` and `success=True` in the same way as we are doing when sending the `url=` parameter.
I found this while working on https://github.com/readthedocs/addons/issues/88
=> Addons: `build.current` API response fix

readthedocs/analytics/models.py, readthedocs/analytics/proxied_api.py, readthedocs/analytics/tests.py, readthedocs/core/utils/requests.py, readthedocs/proxito/tests/test_full.py, readthedocs/proxito/views/serve.py
PR previews are ephemeral, they shouldn't be counted as page views.
Other changes are:
- Changed some variables to use the new naming from https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/proxito/README.rst#url-parts
- Don't record page views from suspicious requests, previously we were doing this check for 404s only.
=> Analytics: don't record page views for PR previews

docs/user/config-file/v2.rst
Closes https://github.com/readthedocs/readthedocs.org/issues/11060
---
- User's documentation (`docs`): https://docs--11076.org.readthedocs.build/en/11076/
- Developer's documentation (`dev`): https://dev--11076.org.readthedocs.build/en/11076/
=> Docs: clarify search configuration patterns

readthedocs/api/v2/views/integrations.py, readthedocs/rtd_tests/tests/test_api.py
This is just a cleanup, we already deprecated the use of webhooks without a secret.
=> Integrations: Don't allow webhooks without a secret

docs/user/examples.rst
I would like to contribute my example for AsciiDoc using Antora site generator and asciidoctor-kroki diagramming
---
- User's documentation (`docs`): https://docs--11091.org.readthedocs.build/en/11091/
- Developer's documentation (`dev`): https://dev--11091.org.readthedocs.build/en/11091/
=> add example list for showing basic asciidoc using Antora 

readthedocs/doc_builder/exceptions.py, readthedocs/notifications/exceptions.py, readthedocs/notifications/messages.py, readthedocs/notifications/models.py
This includes a few fixes and small restructuring to the notification/message classes.
- Centralize message lookup and format string population on the registry model instead of the Notification model. This change will make more sense with my next PR
- Use `copy()` when setting the format values, as to ensure thread safety, these shouldn't be set on the static instance class in the registry.
- Add a base class for notifications, for messages/notifications that fall outside doc building.
=> Some fixes for notifications

requirements/docs.in, requirements/docs.txt
Sphinx was logging that social cards were not generated because `matplotlib` not being installed.
=> Docs: build documentation with social cards

dockerfiles/Dockerfile.wrangler, dockerfiles/force-readthedocs-addons.js, dockerfiles/nginx/README.rst, dockerfiles/nginx/proxito.conf.template, dockerfiles/nginx/wrangler.conf.template, docs/dev/install.rst
Use `wrangler` (development CF Worker) to run the CF worker locally inside our development environment. This allow us to run the exact same code locally than on production, allowing us to perform tests while making modifications on this script without deploying them.
With the current code, developers shouldn't notice anything different and they don't have to do anything. Addons should just work on projects that have Addons enabled the next time they call `inv docker.up` locally.
Some decisions that I made:
* copy the js file from -ops here to be able to load the script with wrangler
* add two new NGINX location that proxy to GitHub: this allows us to run the .js file from -ops without _any_ modification
* use the pre-compiled version of `readthedocs-addons.js` script to avoid developers …
=> Development: use `wrangler` locally (update NGINX/Dockerfile config)

readthedocs/rtd_tests/tests/test_project_forms.py
On .com we default to have orgs enabled, but these tests are for when we don't use orgs
=> Fix test on .com

docs/dev/settings.rst, readthedocs/search/tests/test_views.py
Remove `INDEX_ONLY_LATEST` which has no effect.
---
- User's documentation (`docs`): https://docs--11116.org.readthedocs.build/en/11116/
- Developer's documentation (`dev`): https://dev--11116.org.readthedocs.build/en/11116/
=> Settings: remove unused

readthedocs/api/v3/views.py, readthedocs/builds/views.py, readthedocs/core/context_processors.py, readthedocs/notifications/querysets.py, readthedocs/notifications/tests/test_querysets.py, readthedocs/notifications/tests/test_signals.py, readthedocs/organizations/templates/organizations/organization_detail.html, readthedocs/organizations/views/public.py, readthedocs/projects/views/public.py, readthedocs/templates/builds/build_detail.html, readthedocs/templates/core/project_bar_base.html
Expand `.for_user()` to accept `resource=` parameter and return only the notifications attached to that resource only if the user has permissions over it. Otherwise, return an empty queryset.
Closes #11082
Closes #11113
=> Notifications: show them based on permissions

readthedocs/config/notifications.py, readthedocs/notifications/models.py
In #11094 we introduce a bug in the rendering because we stopped initializing
the Message class with the `format_values` from the `Notification` object
itself. That's why all the notifications weren't rendering these values.
=> Notifications: fix rendering

docs/user/index.rst
This is basically just pulling the main bits from the sidebar,
and putting them in the front page.
=> Refactor the index page to match the sidebar

docs/user/tutorial/index.rst
---
- User's documentation (`docs`): https://docs--11144.org.readthedocs.build/en/11144/
- Developer's documentation (`dev`): https://dev--11144.org.readthedocs.build/en/11144/
=> fix highlighting of "fail_on_warning: true" in tutorial

readthedocs/oauth/services/base.py, readthedocs/rtd_tests/tests/test_oauth_sync.py, readthedocs/settings/base.py
Allauth used to merge the settings from the file and the database, this is not the case anymore.
The actual values will be in the ops repos, this is only to fix tests, since if the settings don't have the `APPS` key, isn't considered as valid.
=> Allauth: define secrets in settings

docs/user/build-customization.rst
Fixes #11150
I believe we will make the (Python) world a better place by setting `VIRTUAL_ENV`, but this change should be evaluated before breaking other people's build for moving too hastily, so I'm making a first fix.
2 questions:
- I added a reference to the ticket, because I'm hopeful the `VIRTUAL_ENV` fix will happen. Is it right?
- Should we add a warning/notice that these instructions changed in Feb 2024, so that people experiencing the issue know they need to update it?
---
- User's documentation (`docs`): https://docs--11152.org.readthedocs.build/en/11152/
- Developer's documentation (`dev`): https://dev--11152.org.readthedocs.build/en/11152/
=> Fix Poetry instructions

readthedocs/builds/views.py
The context was updated in the wrong place.
Notifications are back:
Closes #11146
Closes #11143
=> Build: bugfix to show build notifications

readthedocs/settings/docker_compose.py
As suggested in https://github.com/readthedocs/common/pull/202#issuecomment-1963923938:
With the docker compose settings file, it is currently necessary to explicitly set RTD_DJANGO_DEBUG to a false-y value to clear the DEBUG flag.
Change the default value to False to make the setting more intuitive.
The docker invoke script in common passes RTD_DJANGO_DEBUG=t by default so the effective default behavior is unchanged.
=> Dev: Default RTD_DJANGO_DEBUG to False if not set

readthedocs/settings/base.py
It's deprecated, but we still have like 1050 tokens/users, we need to decide what to do with them later.
=> Allauth: Include Bitbucket in the list of social accounts

readthedocs/templates/account/login.html
This basically merges the CAS login (https://github.com/readthedocs/readthedocs-corporate/blob/main/readthedocsinc/corporate/templates/mama_cas/login.html) view with the allauth login view.
Is it okay to change the template on .org? Or maybe just override the template on .com? I'm changing the template here because we already do something similar with the signup template.
https://github.com/readthedocs/readthedocs.org/blob/9339163811d787fb01e71cdf49907a54b2e71767/readthedocs/templates/account/signup.html#L16-L32
Also, doesn't look like the `if allowed_providers` logic has been ported to ext-theme, for example https://readthedocs.com/accounts/signup/?organization=humitos-google vs https://beta.readthedocs.com/accounts/signup/?organization=humitos-google
ref …
=> Match login template with changes from .com

readthedocs/projects/tasks/builds.py, readthedocs/projects/tests/test_build_tasks.py
This bug was introduced in
https://github.com/readthedocs/readthedocs.org/pull/10922/files#diff-4eae6664ca2124d124dbfe04a8000483c7a23d426c3f390721d6e80fe5891064L504
by mistake.
Commit to review b62afbc6c8ffdaa9dc0c589d2e282532b40be7c9, the other one is linting.
Closes #11170
=> Build: set CANCELLED state when the build is cancelled

readthedocs/projects/forms.py, readthedocs/rtd_tests/tests/test_project.py, readthedocs/rtd_tests/tests/test_project_forms.py
We were triggering a build for the default version, but what we actually wanted to do is to trigger a build for the default branch, and latest. Default version is the one that / redirects to, but actual version may have been changed is LATEST or the default branch. Since the default version is usually LATEST, we never noticed the problem.
Closes https://github.com/readthedocs/readthedocs.org/issues/9685
=> Project: build both default and latest version when saving the project form

docs/user/guides/pull-requests.rst, docs/user/pull-requests.rst, readthedocs/projects/forms.py, readthedocs/projects/models.py, readthedocs/projects/tests/test_views.py
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1749
---
- User's documentation (`docs`): https://docs--11184.org.readthedocs.build/en/11184/
- Developer's documentation (`dev`): https://dev--11184.org.readthedocs.build/en/11184/
=> Project: force PR previews to match repo only if the repo is public

readthedocs/config/config.py, readthedocs/config/tests/test_config.py
While taking a look at #11189 I found that the rendering was broken. I found the `with` + `yield` pattern pretty complex (I have a note about this in the code) and it seems that complexity is confusing enough to make this hard to dealt with.
Anyways, I fixed the problem for now and I added a test case. We can come back to refactoring this in the future with more time.
This PR solves this problem where the choices are not shown in between brackets.
=> Notification: fix `choices` rendering for `INVALID_CHOICE`

readthedocs/core/forms.py, readthedocs/core/views/__init__.py, readthedocs/templates/support/index.html
Use a Django form and crispy filter to render the form on the support page. Also moves the logic from the template to the form itself.
Closes https://github.com/readthedocs/ext-theme/issues/296
=> Support: create a form to render it nicely in ext-theme

readthedocs/notifications/messages.py
I think I merged this too quick. The dashboard is not prepared to show other type of notifications yet and these notifications are not displayed properly. We should come back to this and implement it on the new-dashboard directly once we are ready.
Reverts readthedocs/readthedocs.org#11196
=> Revert "Notifications: show "Maxium concurrency limit reached" as `WARNING`"

readthedocs/builds/views.py, readthedocs/templates/builds/build_detail.html
This adds a notification to the corresponding beta build detail view,
and works for both community and commercial. There are two separate
patterns here as a link to the beta dashboard will 404 if the user is not logged in there yet. That is, linking to `beta.readthedocs.com/projects/foo/` will 404 instead of ask the user to sign in first.
The two URLs generated for me are:
- https://beta.devthedocs.org/projects/test-builds/builds/229/
- https://beta.devthedocs.com/accounts/login/?next=/projects/test-test-builds/builds/10/
- Refs https://github.com/readthedocs/ext-theme/issues/284
- Refs https://github.com/readthedocs/readthedocs-corporate/issues/1760
=> Add build detail view beta notification

CHANGELOG.rst, docs/conf.py, package.json, readthedocs/__init__.py, setup.cfg
---
- User's documentation (`docs`): https://docs--11211.org.readthedocs.build/en/11211/
- Developer's documentation (`dev`): https://dev--11211.org.readthedocs.build/en/11211/
=> Release 10.22.0

readthedocs/config/notifications.py
The correct filename is `.readthedocs.yaml` rather than `readthedocs.yaml`
=> Fix Read the Docs config file name in notifications

readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
This enables the stickybox placements (floating bottom right) on RTD theme docs, and never uses the footer placement.
=> Fully roll out stickybox

readthedocs/config/notifications.py, readthedocs/core/views/__init__.py, readthedocs/proxito/tests/responses/v0.json, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/urls.py, readthedocs/proxito/views/hosting.py, readthedocs/templates/core/teapot.html
This PR defines dummy dashboard URLs in El Proxito to allow calling `reverse()` for APIv3 serializers used under `/_/addons/` and return `*.urls` fields for resources.
Closes https://github.com/readthedocs/readthedocs-ops/issues/1323
=> Proxito: define dummy dashboard URLs for addons serializers

readthedocs/api/v3/filters.py
This is required by the new dashboard to filter notifications by `state__in=read,unread`.
Documentation:
https://django-filter.readthedocs.io/en/stable/guide/usage.html#generating-filters-with-meta-fields
Closes #11214
=> APIv3: add `state__in` filter for Notifications

readthedocs/core/permissions.py, readthedocs/core/tests/test_permissions.py, readthedocs/organizations/views/public.py, readthedocs/profiles/views.py, readthedocs/rtd_tests/tests/test_profile_views.py
Users shouldn't be able to see members from other teams they are not part of.
Ref https://github.com/readthedocs/readthedocs-corporate/issues/1736
Requires https://github.com/readthedocs/readthedocs-corporate/pull/1733.
=> Organizations: take into account the user when listing members

readthedocs/proxito/tests/test_old_redirects.py, readthedocs/redirects/querysets.py
The rstrip call was removing the whole path for `/`, we need to preserve the leading `/` in the path.
=> Redirects: fix root redirect (/ -> <anything>)

readthedocs/notifications/messages.py
Because of this extra `"`, the link was broken.
=> Notification: typo in message

CHANGELOG.rst, docs/conf.py, package.json, readthedocs/__init__.py, setup.cfg
---
- User's documentation (`docs`): https://docs--11281.org.readthedocs.build/en/11281/
- Developer's documentation (`dev`): https://dev--11281.org.readthedocs.build/en/11281/
=> Release 10.24.0

docs/user/build-customization.rst
Raised in https://github.com/readthedocs/readthedocs.org/issues/11289
---
- User's documentation (`docs`): https://docs--11290.org.readthedocs.build/en/11290/
- Developer's documentation (`dev`): https://dev--11290.org.readthedocs.build/en/11290/
=> Docs: explain how to use `uv` to install dependencies

readthedocs/projects/views/private.py
Small logic to decide which feature to promote.
This is pretty simple for now, but it shows the pattern we are thinking about.
Required by https://github.com/readthedocs/ext-theme/issues/103
=> Dashboard: promote features in the right bar

readthedocs/projects/version_handling.py
=> Addons: refactor sorting versions for flyout

readthedocs/api/v3/tests/test_users.py, readthedocs/api/v3/views.py
Closes https://github.com/readthedocs/readthedocs.org/issues/11260. Tests are missing.
This is required for testing https://github.com/readthedocs/readthedocs-corporate/pull/1770.
=> Notifications: allow usernames with dots

docs/user/config-file/index.rst
This confused me initially because I was looking in https://docs.readthedocs.io/en/stable/config-file/v2.html#packages for `python.install.package`, which simply doesn't exist.
Instead, this should probably be `python.install.path` which _is_ a required key (https://github.com/readthedocs/readthedocs.org/pull/11300), and defaults to `pip`.
---
- User's documentation (`docs`): https://docs--11301.org.readthedocs.build/en/11301/
- Developer's documentation (`dev`): https://dev--11301.org.readthedocs.build/en/11301/
=> Replace non-existant `python.install.package` with `python.install.path`

readthedocs/projects/views/private.py
Solve bug https://read-the-docs.sentry.io/issues/5244784623/?project=148442&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=3&utc=true
```
File "django/views/generic/list.py", line 174, in get
context = self.get_context_data()
File "readthedocs/projects/views/private.py", line 134, in get_context_data
context["promotion"] = f"projects/partials/dashboard/{template_name}"
UnboundLocalError: local variable 'template_name' referenced before assignment
```
=> Use initial value for default dashboard template name

docs/conf.py
Do not install `readthedocs-sphinx-search` extension and hook the "Search docs" input from the top right to the `readthedocs-search-show` event to trigger the addons search modal 🎉 
---
- User's documentation (`docs`): https://docs--11303.org.readthedocs.build/en/11303/
- Developer's documentation (`dev`): https://dev--11303.org.readthedocs.build/en/11303/
=> Docs: use addons search

readthedocs/projects/views/private.py
The default promotion was "Security logs", but it's not the most important one. This commit shows it only if there is no other one to show and the user is the owner of the organization.
=> Dashboard: promote "security logs" only if organization owner

dockerfiles/nginx/proxito.conf.template
Since we added `wrangler` to the equation this `$host` variable doesn't point anymore to the `*.devthedocs.org` (documentation) domain anymore, and instead it points to just `nginx`.
This is causing a problem in the redirects because our code checks `X-Forwarded-Host` as the domain where the request is from.
```
proxito_1      | [info     ] Invalid domain.                [readthedocs.core.unresolver] domain=nginx host=nginx ip=10.10.0.100 request_id=e6dd83a5-66fb-4ead-9d0d-7f40a422c294 user_id=None
```
Note that `domain=nginx` and `host=nginx`.
By removing the override of this setting here, we are sending the real domain from where the request was made, in my case `mystmd.devthedocs.org`.
This commit fixes the usage of redirects on local development.
=> Wrangler: NGINX and redirects

docs/user/reference/environment-variables.rst
As of October 2023. see https://blog.readthedocs.com/language-codes-are-now-normalized/
---
- User's documentation (`docs`): https://docs--11315.org.readthedocs.build/en/11315/
- Developer's documentation (`dev`): https://dev--11315.org.readthedocs.build/en/11315/
=> Languages code are now normalized

docs/user/build-customization.rst
See https://github.com/readthedocs/readthedocs.org/issues/11289. Hopefully this is what was requested.
---
- User's documentation (`docs`): https://docs--11322.org.readthedocs.build/en/11322/
- Developer's documentation (`dev`): https://dev--11322.org.readthedocs.build/en/11322/
=> docs: update uv instructions

docs/_templates/ethicalads.html, docs/_templates/layout.html
Instead of injecting the EthicalAd in a customized way, we will injecting it by using the addons approach.
This will be a starting test before enabling this in all the projects that are using addons.
Requires:
* https://github.com/readthedocs/addons/pull/295
---
- User's documentation (`docs`): https://docs--11318.org.readthedocs.build/en/11318/
- Developer's documentation (`dev`): https://dev--11318.org.readthedocs.build/en/11318/
=> Docs: use EthicalAd implementation from addons

readthedocs/builds/filters.py, readthedocs/builds/views.py, readthedocs/core/filters.py, readthedocs/organizations/filters.py, readthedocs/organizations/views/private.py, readthedocs/projects/filters.py, readthedocs/projects/views/private.py, readthedocs/projects/views/public.py
This moves a lot of dashboard JS/API logic into our standard FilterSet
instances:
- Project listing filter field
- Version listing filter field
- Build list version listing filter field
To accomplish this, a few helper classes were added for making the
fields easier to work with and display.
Template and JS were updated in
- https://github.com/readthedocs/ext-theme/pull/351
=> Move dashboard API filter fields to model queryset filter fields

readthedocs/analytics/models.py, readthedocs/builds/models.py, readthedocs/builds/querysets.py, readthedocs/core/models.py, readthedocs/core/querysets.py, readthedocs/integrations/models.py, readthedocs/invitations/models.py, readthedocs/notifications/querysets.py, readthedocs/oauth/models.py, readthedocs/oauth/querysets.py, readthedocs/organizations/models.py, readthedocs/organizations/querysets.py, readthedocs/projects/models.py, readthedocs/projects/querysets.py, readthedocs/redirects/querysets.py, readthedocs/rtd_tests/tests/test_footer.py, readthedocs/search/models.py, readthedocs/sso/models.py, readthedocs/subscriptions/querysets.py, readthedocs/telemetry/models.py
This commit removes some debugging functionability in favor of production DB. `__str__` and `__repr__` methods won't be so descriptive now since we are removing some information from their rendering. This is because to render them properly we need to hit the DB multiple times in the worst case --generating 500 on some user requests that need to be logged in Sentry/New Relic.
There are better ways for this: disabling logging on production and enabling it on DEBUG + Django Shell, but that requires more extra work that doesn't seems super priority right now. We can come back later and add them as we need them if we want.
Closes #10954
=> Adapt `__str__` and `__repr__` methods for DB

readthedocs/projects/tasks/builds.py, readthedocs/projects/tasks/utils.py
It seems that `CeleryTaskWrapper` from New Relic passes their own `instance=` attribute and the Celery task attributes as well as `kwargs`. This results in passing `instance` attribute twice and it breaks:
https://read-the-docs.sentry.io/issues/5385629903/?project=148442&query=is%3Aunresolved+%21message%3A%22%21message%3A%22%21message%3A%22SystemExit%22+%21message%3A%22frame-ancestors%22&referrer=issue-stream&statsPeriod=14d&stream_index=0
This commit renames `instance` argument to `builder` to avoid this.
=> Celery: user `builder` instead of `instance` as argument

readthedocs/rtd_tests/tests/test_project_forms.py
Will fix the tests from https://github.com/readthedocs/readthedocs-corporate/pull/1788
=> Tests: set provider explicitly

docs/user/support.rst
---
- User's documentation (`docs`): https://docs--11340.org.readthedocs.build/en/11340/
- Developer's documentation (`dev`): https://dev--11340.org.readthedocs.build/en/11340/
=> Docs: fix external resources link on support page

docs/user/commercial/subscriptions.rst
Small refactor of our docs explaining PO support.
---
- User's documentation (`docs`): https://docs--11335.org.readthedocs.build/en/11335/
- Developer's documentation (`dev`): https://dev--11335.org.readthedocs.build/en/11335/
=> Docs: PO only allowed on annual Pro/Enterprise plans

docs/user/tutorial/index.rst
No major changes. Edits intended to 
- simplify
- make more consistent
- streamline some instructions
---
- User's documentation (`docs`): https://docs--11316.org.readthedocs.build/en/11316/
- Developer's documentation (`dev`): https://dev--11316.org.readthedocs.build/en/11316/
=> Tighten up and refactor the tutorial WIP

docs/user/tutorial/index.rst
The additional whitespace invoked a definition list on this paragraph.
---
- User's documentation (`docs`): https://docs--11347.org.readthedocs.build/en/11347/
- Developer's documentation (`dev`): https://dev--11347.org.readthedocs.build/en/11347/
=> Fix small docs display issue on tutorial

readthedocs/builds/views.py
Related https://github.com/readthedocs/readthedocs-ops/issues/1485
=> Dashboard: use `app.` domain instead of `beta.`

readthedocs/projects/views/private.py
The normal view is an old view that splits up active/inactive versions
into two queries. It's mostly identical in function otherwise, so the
new dashboard doesn't reimplement this view. Instead, forms should have
a success URL of the normal project version listing.
See https://github.com/readthedocs/ext-theme/issues/288 for the
reasoning here.
- Refs https://github.com/readthedocs/ext-theme/issues/288
=> Set better success URL for version form views

requirements/deploy.txt, requirements/docker.txt, requirements/docs.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Fixes https://github.com/readthedocs/readthedocs.org/issues/11363.
We should upgrade the docker library we are using, there is a fix in place in the latest version.
=> Pin requests to a version compatible with docker

readthedocs/projects/filters.py
The arguments aren't passed in by keyword ever, so this argument
signature was incorrect.
- Fixes #11231
=> Fix version visibility filter method

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Return "source language project" in `projects.translations` when accessing a translation of the "source language project".
Closes #11292
=> Addons: update `projects.translations` API response

readthedocs/projects/tasks/search.py, readthedocs/proxito/views/serve.py, readthedocs/proxito/views/utils.py, readthedocs/settings/base.py
Related https://github.com/readthedocs/readthedocs.org/issues/9993
=> Proxito: browndate for redirecting `/` to `README.html`

readthedocs/invitations/templatetags/invitations.py
Because Django. This is just a wrapper for working around the lack of support for calling methods with arguments in Django templates.
- Supersedes https://github.com/readthedocs/readthedocs-corporate/pull/1793
- Supersedes https://github.com/readthedocs/readthedocs.org/pull/11351
- Needed for https://github.com/readthedocs/ext-theme/issues/354
=> Add invitation template filter

readthedocs/projects/forms.py
The messages are broken into normal strings and f-strings. While this might be successfully concatenated in the original language, this doesn't work when extracting messages for translation: Currently only the normal string is being considered, and f-string part is being ignored.
E.g., see how they are currently shown in pt_BR translation file (msgid is the source string extracted from source file):
https://github.com/readthedocs/readthedocs.org/blob/88d7c6e2bf4cc472e9cb349a7f4340160a55e4d6/readthedocs/locale/pt_BR/LC_MESSAGES/django.po#L2409-L2417
=> Unbreak strings to proper extraction for translation

scripts/compile_version_upload_s3.sh
CircleCI is failing when building `build.tools` because Ruby 3.3.2 is not yet available in the `asdf` version we have in our Ubuntu Docker image. Updating the version of `asdf` and its plugins allows us to pre-compile these versions when running the CircleCI job.
This is required by #11386
Once this PR gets merged, we need to restart the CircleCI job.
https://app.circleci.com/pipelines/github/readthedocs/readthedocs-docker-images/294/workflows/3764492d-0fd4-44a3-bb0c-fccb696dc130/jobs/514
=> Build: update `asdf` and its plugins so we can build latest versions

readthedocs/settings/docker_compose.py
I introduced this by mistake in #11377. I'm reverting this change.
=> Settings: revert `USE_PROMOS` setting

readthedocs/oauth/services/base.py, readthedocs/rtd_tests/tests/test_oauth.py
The provider was changed to be a property now
https://github.com/pennersr/django-allauth/commit/5db1b482307ab13de3db34b7395c287c495bba13
=> Oauth: Fix GitLab access token URL

docs/user/config-file/v2.rst, readthedocs/builds/constants_docker.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/fixtures/spec/v2/schema.json
Matches https://github.com/readthedocs/readthedocs-docker-images/pull/205
Closes #11350
---
- User's documentation (`docs`): https://docs--11386.org.readthedocs.build/en/11386/
- Developer's documentation (`dev`): https://dev--11386.org.readthedocs.build/en/11386/
=> Build: update all `build.tools` and add latest versions

readthedocs/core/context_processors.py, readthedocs/rtd_tests/tests/test_notifications.py, readthedocs/settings/base.py
We use this setting in some Django Templates.
See https://github.com/readthedocs/ext-theme/pull/362
=> Templates: pass `ADMIN_URL` into context

docs/user/examples.rst
Convert the table into sections and bullet list. It's a lot more readable and easy to follow. I also added "Markup language" which is important.
This page still needs some work, but baby steps.
📖 https://docs--11404.org.readthedocs.build/en/11404/examples.html
---
- User's documentation (`docs`): https://docs--11404.org.readthedocs.build/en/11404/
- Developer's documentation (`dev`): https://dev--11404.org.readthedocs.build/en/11404/
=> Docs: update "Example projects" a little

docs/user/versions.rst, readthedocs/core/notifications.py
---
- User's documentation (`docs`): https://docs--11412.org.readthedocs.build/en/11412/
- Developer's documentation (`dev`): https://dev--11412.org.readthedocs.build/en/11412/
=> New dashboard: use `app.` instead of `beta.`

docs/user/build-customization.rst, docs/user/config-file/v2.rst, readthedocs/doc_builder/director.py
Closes #11405
---
- User's documentation (`docs`): https://docs--11411.org.readthedocs.build/en/11411/
- Developer's documentation (`dev`): https://dev--11411.org.readthedocs.build/en/11411/
=> Build: remove "beta" from `build.commands`

docs/user/config-file/v2.rst, readthedocs/builds/constants_docker.py, readthedocs/rtd_tests/fixtures/spec/v2/schema.json, scripts/compile_version_upload_s3.sh
Closes #11072
Requires:
* https://github.com/readthedocs/readthedocs-docker-images/pull/207
* https://github.com/readthedocs/readthedocs-ops/pull/1494
---
- User's documentation (`docs`): https://docs--11421.org.readthedocs.build/en/11421/
- Developer's documentation (`dev`): https://dev--11421.org.readthedocs.build/en/11421/
=> Build: add support for Ubuntu 24.04 LTS

readthedocs/metrics/tasks.py
We don't have 2 different queues anymore, so there is no need to trigger 2 `time-test` builds anymore.
=> Ops: delete triggering a `time-test` build on `build-large` queue

docs/user/index.rst
Refs https://github.com/readthedocs/website/issues/286
---
- User's documentation (`docs`): https://docs--11426.org.readthedocs.build/en/11426/
- Developer's documentation (`dev`): https://dev--11426.org.readthedocs.build/en/11426/
=> Link website from docs sidebar

requirements/deploy.txt, requirements/docker.in, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
We attempt to upgrade this some time ago (in #10667) but we reverted it later since New Relic Python client wasn't compatible with it.
The newer version of New Relic that we are already using added compatibility and should log database transactions properly now.
Closes #10596
=> Requirements: upgrade `psycopg` to v3

readthedocs/proxito/middleware.py, readthedocs/proxito/tests/test_headers.py, readthedocs/proxito/tests/test_old_redirects.py
This fixes https://github.com/readthedocs/readthedocs.org/issues/11403
=> Run iri_to_uri on header values

readthedocs/notifications/messages.py
=> Notification: update copy for "No HTML content found"

docs/user/config-file/v2.rst, docs/user/guides/private-python-packages.rst
to improve readability and clarity.
---
- User's documentation (`docs`): https://docs--11395.org.readthedocs.build/en/11395/
- Developer's documentation (`dev`): https://dev--11395.org.readthedocs.build/en/11395/
=> Minor refactor of Private Python packages page

readthedocs/subscriptions/event_handlers.py, readthedocs/subscriptions/tasks.py, readthedocs/subscriptions/tests/test_event_handlers.py, readthedocs/subscriptions/tests/test_tasks.py
With this change, all organization that go to canceled, unpaid, past due or similar subscription status that are not `active`, will be immediately disabled. This means they won't be able to trigger builds anymore. However, we will still keep serving documentation for their projects.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1798
=> Organization: disable organization on non-active subscription

docs/dev/style-guide.rst
Minimal viable pre-commit docs.
---
- User's documentation (`docs`): https://docs--11445.org.readthedocs.build/en/11445/
- Developer's documentation (`dev`): https://dev--11445.org.readthedocs.build/en/11445/
=> Mention linting

docs/user/reference/environment-variables.rst, readthedocs/doc_builder/backends/sphinx.py, readthedocs/doc_builder/director.py, readthedocs/doc_builder/python_environments.py, readthedocs/projects/models.py, readthedocs/projects/tests/test_build_tasks.py
Add a feature flag called `DISABLE_SPHINX_MANIPULATION` that:
- don't install `readthedocs-sphinx-ext` Python package
- don't append anything to the Sphinx's `conf.py` file
- enable Read the Docs Addons on these versions automatically
The idea behind this is start defaulting new projects to Read the Docs Addons without breaking old projects.
This is a potential first step in favor of the full deprecation/removal of the Sphinx manipulation (as we already did for MkDocs). Once this happens, **building on Read the Docs will produce the exact same result than building locally**.
| Build page | Documentation |
| ---- | ---- |
| ![Screenshot_2024-06-27_12-01-55](https://github.com/readthedocs/readthedocs.org/assets/244656/0bab3927-f3a0-4793-915d-caebcd34f5ff) | …
=> Build: disable Sphinx manipulation

readthedocs/settings/base.py
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content
> This directive is marked as obsolete in the specification. This
> directive was previously used to prevent "optionally blockable" mixed
> content from being fetched insecurely and displayed. Content that isn't
> blocked is now always upgraded to a secure connection, so this directive
> is not needed.
=> CSP: remove obsolete block-all-mixed-content directive

docs/user/canonical-urls.rst
Users should start defining the Canonical URL manually using the `READTHEDOCS_CANONICAL_URL` environment variable.
---
- User's documentation (`docs`): https://docs--11455.org.readthedocs.build/en/11455/
- Developer's documentation (`dev`): https://dev--11455.org.readthedocs.build/en/11455/
=> Docs: tell users to set the canonical URL manually

readthedocs/subscriptions/event_handlers.py
We should write a test for this
ref https://read-the-docs.sentry.io/issues/5584105103/?project=161479&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
=> Fix slack notifications for stripe events

docs/user/sponsors.rst
Leave this page only for sponsors.
We do have another page that explains adverstising in a better way.
---
- User's documentation (`docs`): https://docs--11457.org.readthedocs.build/en/11457/
- Developer's documentation (`dev`): https://dev--11457.org.readthedocs.build/en/11457/
=> Docs: remove past sponsors and old blog post link

docs/user/guides/manage-translations-sphinx.rst
Hi, I found a typo and corrected it.
---
- User's documentation (`docs`): https://docs--11204.org.readthedocs.build/en/11204/
- Developer's documentation (`dev`): https://dev--11204.org.readthedocs.build/en/11204/
=> Correcte the tx push command

docs/dev/design.rst, docs/user/terms-of-service.rst, docs/user/user-defined-redirects.rst, readthedocs/templates/base.html
Updates the links to current brand-guidelines.readthedocs.org, fixes a typo along the way.
---
- User's documentation (`docs`): https://docs--11261.org.readthedocs.build/en/11261/
- Developer's documentation (`dev`): https://dev--11261.org.readthedocs.build/en/11261/
=> chore: Update guidelines links

docs/user/builds.rst
We are using only `build-default` now and it uses 7Gb now.
---
- User's documentation (`docs`): https://docs--11475.org.readthedocs.build/en/11475/
- Developer's documentation (`dev`): https://dev--11475.org.readthedocs.build/en/11475/
=> Docs: update build limits on community

readthedocs/doc_builder/python_environments.py
I missed this in https://github.com/readthedocs/readthedocs.org/pull/11441
=> Build: do not install our extension when building with Conda

docs/user/guides/setup/git-repo-automatic.rst
---
- User's documentation (`docs`): https://docs--11492.org.readthedocs.build/en/11492/
- Developer's documentation (`dev`): https://dev--11492.org.readthedocs.build/en/11492/
=> Docs: remove beta framing from pull request

docs/user/addons.rst, docs/user/build-customization.rst, docs/user/config-file/v2.rst, docs/user/flyout-menu.rst, readthedocs/projects/forms.py, readthedocs/projects/urls/private.py
It's now pretty stable and it will become the default soon: https://about.readthedocs.com/blog/2024/07/addons-by-default/
Closes #11453
---
- User's documentation (`docs`): https://docs--11493.org.readthedocs.build/en/11493/
- Developer's documentation (`dev`): https://dev--11493.org.readthedocs.build/en/11493/
=> Addons: remove "beta" framing around addons

readthedocs/proxito/urls.py
We are using `/_/addons/` everywhere now.
=> Proxito: remove outdated URL

readthedocs/doc_builder/backends/sphinx.py
We are installing `readthedocssinglehtmllocalmedia` Sphinx builder via our `readthedocs-sphinx-ext` extension.
I checked that code and this builder doesn't do anything super special. It only adds a CSS file that it's related with the flyout, which it's not useful anymore:
https://github.com/readthedocs/readthedocs-sphinx-ext/blob/13edf78bab374f51e314e4994c319fadbab806f2/readthedocs_ext/readthedocs.py#L81-L83
This commit runs `singlehtml` Sphinx builder (the default from Sphinx) when the `DISABLE_SPHINX_MANIPULATION` feature flag is enabled. I tested this locally using `all-formats` branch from `test-builds` and I got the same results (except from the flyout, which is not injected anymore since there is no context injected in the new behavior)
=> Build: do not use custom builder when `DISABLE_SPHINX_MANIPULATION`

docs/user/api/v3.rst, readthedocs/api/v3/serializers.py, readthedocs/api/v3/tests/responses/projects-detail.json, readthedocs/api/v3/tests/responses/projects-list.json, readthedocs/api/v3/tests/responses/projects-list_POST.json, readthedocs/api/v3/tests/responses/projects-subprojects-detail.json, readthedocs/api/v3/tests/responses/projects-subprojects-list.json, readthedocs/api/v3/tests/responses/projects-subprojects-list_POST.json, readthedocs/api/v3/tests/responses/projects-superproject.json, readthedocs/api/v3/tests/responses/projects-sync-versions.json, readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json, readthedocs/api/v3/tests/responses/remoterepositories-list.json, readthedocs/api/v3/tests/test_projects.py, readthedocs/api/v3/urls.py, readthedocs/api/v3/views.py
This will be used in the frontend,
but also available as an API.
Mostly curious if this is a good approach,
and I can get some tests together for it.
Looks like:
```
-> curl -X POST http://devthedocs.com/api/v3/projects/read-the-docs/sync_versions/ -H "Authorization: Token $TOKEN" 
{"triggered":true}
```
Refs https://github.com/readthedocs/readthedocs.org/issues/6090
=> Add an initial resync_versions API to v3

readthedocs/core/templatetags/core_tags.py
We are using django-gravatar2 for gravatar support. Also, this filter is wrong, if used, this renders the HTML as text.
=> Templates: remove unused filter

docs/user/api/v3.rst
---
- User's documentation (`docs`): https://docs--11517.org.readthedocs.build/en/11517/
- Developer's documentation (`dev`): https://dev--11517.org.readthedocs.build/en/11517/
=> Docs: update API V3 docs about authentication

docs/user/automation-rules.rst, docs/user/commercial/privacy-level.rst, docs/user/commercial/sharing.rst, docs/user/commercial/single-sign-on.rst, docs/user/guides/best-practice/links.rst, docs/user/guides/content/index.rst, docs/user/guides/pull-requests.rst, docs/user/reference/robots.rst, docs/user/server-side-search/api.rst, docs/user/tutorial/index.rst, docs/user/versions.rst
Some quick noodling on #11508 -- this makes more sense to me, but I'm happy to have another bash.
Is there a canonical link for allocating permissions? Or is that all tied in up SSO? 
---
- User's documentation (`docs`): https://docs--11512.org.readthedocs.build/en/11512/
- Developer's documentation (`dev`): https://dev--11512.org.readthedocs.build/en/11512/
=> Explore an alternative way of explaining states

docs/user/versions.rst
Post merge fixes to #11512 
---
- User's documentation (`docs`): https://docs--11530.org.readthedocs.build/en/11530/
- Developer's documentation (`dev`): https://dev--11530.org.readthedocs.build/en/11530/
=> Post merge fixes

docs/user/guides/reproducible-builds.rst
- Rephrase the `readthedocs.yaml` section since it's _mandatory_ now
- Add a small YAML that shows pinning OS and tools
- Only show `python.install.requirements` for Python dependencies section
- Remove "Good" small section since we removed the "Bad" one already
- Remove "Check list" since it's just duplicated content
---
- User's documentation (`docs`): https://docs--11535.org.readthedocs.build/en/11535/
- Developer's documentation (`dev`): https://dev--11535.org.readthedocs.build/en/11535/
=> Docs: simplify repdroducible guide

readthedocs/settings/base.py, readthedocs/settings/test.py
We need to explicitly define the hashers,
so we can append an extra hasher we are using on .com.
=> Settings: explicitly set password hashers

readthedocs/subscriptions/event_handlers.py
It was giving us 400 because we weren't sending the data as JSON.
I also add a small log line, just in case.
=> Slack: use json= to send a message using webhooks

readthedocs/templates/account/login.html
We initially had this on the new dashboard only, but the new dashboard doesn't work for granting access to docs pages yet.
=> Login: add link to SAML login

readthedocs/invitations/backends.py
The mistake has been introduced in #9440.
=> Fix a typo in "invited" in email notification subjects

readthedocs/notifications/models.py
I had this fix sitting around, I hit this while trying to work on https://github.com/readthedocs/readthedocs.org/issues/11209
- Closes #11482
=> Drop "Unknown message" notification

docs/user/guides/jupyter.rst
Since a while, `nbsphinx` doesn't depend on Sphinx-Gallery anymore and uses its own CSS (which can still be overwritten/extended by site authors), see https://github.com/spatialaudio/nbsphinx/pull/706.
---
- User's documentation (`docs`): https://docs--11545.org.readthedocs.build/en/11545/
- Developer's documentation (`dev`): https://dev--11545.org.readthedocs.build/en/11545/
=> Update instructions for Jupyter notebook galleries

readthedocs/projects/views/private.py
We are adding an extra step in Read the Docs for Business to allow users to select the Organization and Team as the first step.
Because of that, the _first_ step is not always the `basics` form and now we need to find it first.
Required by https://github.com/readthedocs/readthedocs-corporate/pull/1851
Closes #11111
=> Add project: improve way to get the `basics` form

readthedocs/projects/forms.py
This is currently using `str()` which renders the website URL. This is fine for public repositories, but private repositories use the clone_url as the project repo_url and so these two fields don't match.
With this change, the field renders the clone_url, matching the `repo_url` field above:
- Fixes #11562
=> Use clone_url for remote repository field

readthedocs/builds/tasks.py, readthedocs/settings/base.py
We have 35K external versions pending deletion...
And we are now deleting old versions first, previously this was using the default sorting (verbose name).
=> Tasks: delete closed PRs every 30 minutes

readthedocs/api/v3/tests/responses/notifications-list.json, readthedocs/api/v3/tests/responses/projects-notifications-detail.json, readthedocs/api/v3/tests/responses/projects-notifications-list.json, readthedocs/projects/notifications.py
All the builds are skipped, so I understand this should be plural.
=> Notifications: small typo

docs/user/guides/set-up-single-sign-on-saml.rst
By default Okta uses the username as the NameID,
which isn't always equal to the email address.
---
- User's documentation (`docs`): https://docs--11569.org.readthedocs.build/en/11569/
- Developer's documentation (`dev`): https://dev--11569.org.readthedocs.build/en/11569/
=> SAML: update Okta setup steps

readthedocs/sso/admin.py
We have lots of organization on .com, this slows down the admin.
=> Admin: set raw field for SSOIntegration

readthedocs/core/utils/__init__.py
`email.to` returns a list, but our task expects a single string
=> Email: use first recipient from email object

docs/user/guides/set-up-single-sign-on-saml.rst
- Re-arrange and rename some sections, so the user follows a more logical order.
- Adding detailed steps for enabling SAML on Read the Docs, leaving just the domain configuration to do it via support.
- Clarify user management and team configuration
preview at https://docs--11583.org.readthedocs.build/en/11583/guides/set-up-single-sign-on-saml.html
---
- User's documentation (`docs`): https://docs--11583.org.readthedocs.build/en/11583/
- Developer's documentation (`dev`): https://dev--11583.org.readthedocs.build/en/11583/
=> SAML: update docs

docs/user/reference/sitemaps.rst
Closes #10816
---
- User's documentation (`docs`): https://docs--11585.org.readthedocs.build/en/11585/
- Developer's documentation (`dev`): https://dev--11585.org.readthedocs.build/en/11585/
=> Docs: small updates to sitemaps page

docs/user/addons.rst
Mention the explicit date and link people to the blog post for more context.
---
- User's documentation (`docs`): https://docs--11588.org.readthedocs.build/en/11588/
- Developer's documentation (`dev`): https://dev--11588.org.readthedocs.build/en/11588/
=> Docs: final date for addons and link to blog post

docs/conf.py
This is for testing error pages more in production and can be reverted later.
---
- User's documentation (`docs`): https://docs--11596.org.readthedocs.build/en/11596/
- Developer's documentation (`dev`): https://dev--11596.org.readthedocs.build/en/11596/
=> Conditionally disabled custom 404 pages on dev docs

docs/user/versions.rst
Saw a typo.
---
- User's documentation (`docs`): https://docs--11603.org.readthedocs.build/en/11603/
- Developer's documentation (`dev`): https://dev--11603.org.readthedocs.build/en/11603/
=> Fix minor typo in "Version states"

docs/user/build-customization.rst
`git log` will wrap longer commit messages onto multiple lines, in which case a commit with `[skip ci]` will not cause a build to skip.
---
- User's documentation (`docs`): https://docs--11601.org.readthedocs.build/en/11601/
- Developer's documentation (`dev`): https://dev--11601.org.readthedocs.build/en/11601/
=> Docs: Handle long commit messages in [skip ci] example

readthedocs/gold/tests/test_views.py, readthedocs/gold/views.py
This does not seem needed, as there is no inline script src in
`subscription_detail.html`. It seems like maybe we wrote this for
`subscription_form.html`, which was old.
This conditional was breaking the view for me locally, as we don't have
any CSP directives for `script-src` locally, we only have these in
production. Because of this, there are no other `script-src` exceptions.
- Refs https://github.com/readthedocs/ext-theme/issues/407
=> Drop unnecessary CSP directives for gold view

readthedocs/projects/views/private.py
We referred to these as `promotions` here, but as "announcements" in the
templates. I think "announcements" fits better, and we already describe
in documentation advertising as "promotions".
- Refs readthedocs/ext-theme#409
=> Make terminology and paths consistent for onboarding announcements

readthedocs/builds/models.py, readthedocs/builds/querysets.py, readthedocs/projects/views/public.py
This optimizes the version listing view and removes redundant queries.
- Requires readthedocs/ext-theme#493
- Fixes readthedocs/ext-theme#463
- Fixes https://github.com/readthedocs/ext-theme/issues/60
=> Prefetch build and project on version list

readthedocs/projects/models.py, readthedocs/projects/querysets.py
We use both latest build and latest successful build in the project
listing template.
- Refs https://github.com/readthedocs/ext-theme/issues/463
- Fixes https://github.com/readthedocs/ext-theme/issues/61
=> Add support for successful build prefetch

readthedocs/projects/forms.py
Templates make usage of this field. If we remove it they break. Disabling it keeps the features and the template working as expected. We can come back later if we want to do something else here, but I'm making it to not break for now.
=> Addons: disable the field instead of remove it

readthedocs/builds/models.py, readthedocs/builds/querysets.py, readthedocs/projects/models.py, readthedocs/projects/querysets.py, readthedocs/projects/views/public.py
- Reverts #11613
- Reverts #11616
- Disables previously used prefetch on the project dashboard view
- Refs #11620
=> Try reverting prefetch changes for project/version listing views

readthedocs/search/tests/test_views.py
I think this broke with
https://github.com/readthedocs/readthedocs.org/pull/11566/, I didn't find anything obvious from their changelog, and doesn't look like something I want to spend more time on debugging...
Closes https://github.com/readthedocs/readthedocs.org/issues/11618
=> ES: fix flaky test

docs/user/reference/robots.rst
This is to fix the "Version states" link text (below) in the docs. I think this is meant to say that hidden versions are not indexed?
---
- User's documentation (`docs`): https://docs--11644.org.readthedocs.build/en/11644/
- Developer's documentation (`dev`): https://dev--11644.org.readthedocs.build/en/11644/
=> Specify that hidden versions in RTD are blocked from indexing

readthedocs/urls.py
Allauth expects a handler429 view in urls.py,
or a 429.html template in the root of the templates directory. We don't want to create symlinks, so a custom handler429 view is added.
Ref https://read-the-docs.sentry.io/issues/5835964680/?project=161479&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=19
=> Allauth: add 429 handler

readthedocs/metrics/tasks.py
Today we enabled Addons by default. That removes the `readthedocs-sphinx-ext` that generates `.json` files which are used by Embed APIv2.
Now, we are hitting the URL directly.
=> Metrics: don't rely on Embed APIv2

readthedocs/proxito/tests/test_headers.py
This header is useless now that we are fully migrated to Addons. I'm removing the only the test for now, since it's failing on all the PRs.
Related #11653
=> Proxito: remove `X-RTD-Hosting-Integrations` HTTP header

readthedocs/proxito/tests/responses/v1.json, readthedocs/proxito/views/hosting.py
I'm disabling search filters until we implement the Admin UI page to customize them.
It requires https://github.com/readthedocs/addons/pull/391
=> Addons: disable search filters for now

docs/user/build-customization.rst
Since the instructions were added in https://github.com/readthedocs/readthedocs.org/pull/11322, uv gained a new capability to run `uv sync` and `uv run` enabling some simplifications
---
- User's documentation (`docs`): https://docs--11655.org.readthedocs.build/en/11655/
- Developer's documentation (`dev`): https://dev--11655.org.readthedocs.build/en/11655/
=> Simplify instructions for installing dependencies with uv

readthedocs/projects/tasks/search.py, readthedocs/rtd_tests/tests/test_imported_file.py
Currently, we walk the entire project directory to apply two operations: index files in ES, and keep track of index/404 files. These two operations are independent, but in our code they are kind of mixed together in order to avoid walking the project directory twice.
I have abstracted the processing of the files with an "Indexer" class, which is responsible for doing an operation on a file, and at the end it can collect the results.
Why this refactor now? With the file tree diff feature coming (https://github.com/readthedocs/readthedocs.org/pull/11507/), I found it easier to just do the operation at the same time we index files for search. We can cache the file contents, so we won't need to read the file twice from storage, and also won't need an additional API to save the results from …
=> Build: refactor search indexing process

readthedocs/search/parsers.py, readthedocs/search/tests/data/sphinx/in/page.html, readthedocs/search/tests/data/sphinx/out/page.json
HTML tags can be divided in two categories: inline and block elements. Inline elements do not start on a new line, while block elements start on a new line. This gives block elements an implicit spacing that is not present in inline elements. If there are two tags next to each other, and one of them is a block element, there will be a space between them. Or if the two tags are inline elements, there will be no space between them.
Previously, we were joining the text from all tags without a space, which works well if there is a space/newline between the HTML elements, but some tools output HTML without any type of formatting (one big line). In that case, we were indexing some words joined together instead of separate, for example in this page …
=> Search: respect spacing from block elements when indexing

docs/Makefile, docs/dev/design/better-doc-urls-handling.rst, docs/dev/design/build-images.rst, docs/dev/design/file-tree-diff.rst, docs/dev/design/new-notifications-system.rst, docs/dev/design/new-search-api.rst, docs/dev/design/pr-builder.rst, docs/dev/design/redirects.rst, docs/dev/design/secure-api-access-from-builders.rst, docs/dev/search-integration.rst, docs/dev/subscriptions.rst, docs/user/api/v3.rst, docs/user/builds.rst, docs/user/faq.rst, docs/user/glossary.rst, docs/user/intro/add-project.rst, docs/user/science.rst, docs/user/server-side-search/api.rst, docs/user/tutorial/index.rst
% `codespell docs --ignore-words-list=hel,ore,wile --skip="*.po" --write-changes`
Related to:
* #11195
* #8423
* #8421
* #8420
* #8419
* #8409
https://pypi.org/project/codespell should be in `pre-commit` but sharing the same pre-commit settings file makes that difficult.
---
- User's documentation (`docs`): https://docs--11664.org.readthedocs.build/en/11664/
- Developer's documentation (`dev`): https://dev--11664.org.readthedocs.build/en/11664/
=> codespell the docs directory

readthedocs/domains/tasks.py
Allow users to dismiss this notification:
=> Notification: make "pending configuration" dismissable

docs/user/addons.rst, docs/user/commercial/index.rst, docs/user/commercial/sharing.rst, docs/user/guides/content/index.rst, docs/user/guides/technical-docs-seo-guide.rst, docs/user/index.rst, docs/user/tutorial/index.rst
Not sure how these didn't break the build..
---
- User's documentation (`docs`): https://docs--11661.org.readthedocs.build/en/11661/
- Developer's documentation (`dev`): https://dev--11661.org.readthedocs.build/en/11661/
=> Fix analytics links

readthedocs/templates/projects/project_edit_base.html
This is just using the same pattern as for versions,
but linking to another dashboard.
Could use an external icon here,
but didn't want to get too deep :)
=> Link to new dashboard Addons page in old dashboard settings.

dockerfiles/nginx/proxito.conf.template
- Fix Content type on addons in dev
- Keep caching
=> fix proxito header

readthedocs/core/middleware.py, readthedocs/rtd_tests/tests/test_middleware.py
We set the fallback cookie to work around some old browsers rejecting cookies with `SameSite=None` https://www.chromium.org/updates/same-site/incompatible-clients/. That note is from 2019, I think we should be fine without supporting those old browsers, and browsers from supported devices are already patched to support that cookie.
This is adding an additional cookie that takes some space.
=> Remove session fallback cookie

docs/conf.py
---
- User's documentation (`docs`): https://docs--11681.org.readthedocs.build/en/11681/
- Developer's documentation (`dev`): https://dev--11681.org.readthedocs.build/en/11681/
=> Docs: recover "Edit on GitHub" links

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
This at least shows the UI element if it makes sense to show.
Currently there's no way without knowing the query syntax to get subprojects,
which has caused confusion for a few of our users and broke existing behavior.
Refs https://github.com/readthedocs/readthedocs.org/pull/11638
=> Enable subproject filters for projects with subprojects

readthedocs/projects/tests/test_version_handling.py, readthedocs/projects/version_handling.py, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
We were mixing ascending and descending when listing the versions, we now always sort in descending order. Even if the version fails to parse, we still sort it in descending order as fallback.
Closes https://github.com/readthedocs/readthedocs.org/issues/11689
=> Addons: always sort versions in descending order

readthedocs/search/api/v3/executor.py
I included this by mistake in https://github.com/readthedocs/readthedocs.org/pull/11646/. It was meant as an internal note to open an issue about it (https://github.com/readthedocs/readthedocs.org/issues/11703).
=> Remove unrelated change

readthedocs/projects/tasks/search.py, readthedocs/rtd_tests/tests/test_imported_file.py, readthedocs/search/parsers.py
We were missing passing the type of the version here, we didn't notice this before since we weren't reading the files (no search indexing for PR previews), but now we need to read the content for file tree diff.
We should probably have this parameter as required... I checked all other calls, and we are good.
=> File indexers: correctly get page content from PR previews

readthedocs/embed/v3/tests/test_external_pages.py, readthedocs/embed/v3/tests/test_internal_pages.py, readthedocs/embed/v3/tests/utils.py, requirements/docs.in, requirements/docs.txt, requirements/testing.txt, tox.embedapi.ini
We were pinning sphinx because of https://github.com/readthedocs/sphinx-multiproject/issues/9 but that's solved now.
=> Docs: update sphinx

docs/user/automation-rules.rst, docs/user/versions.rst, readthedocs/builds/constants.py
Hey all, thanks for such a cool project ❤️
We at [Wagtail](https://github.com/wagtail/wagtail) use RTD for our docs, and we use `v`-prefixed names for our git tags. RTD seems to pick it up nicely, but I couldn't find any mention of the prefix in the docs. I wanted to make sure that this is the default RTD behaviour rather than something that we set up at some point and forgot about.
In https://docs.readthedocs.io/en/stable/versions.html it says that RTD follows SemVer and PEP 440 for its default versioning workflows. However, [SemVer.org](https://semver.org/#is-v123-a-semantic-version) says the following:
> **Is “v1.2.3” a semantic version?**
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version …
=> Clarify support for an optional `v`-prefix in branch and tag names

docs/user/advertising/ad-blocking.rst, docs/user/api/cross-site-requests.rst, readthedocs/settings/base.py
We are now injecting ads via addons,
which doesn't make use of the sustainability endpoint. That endpoint was used to check if the user was a Gold member, and not show ads to them.
The usage of the sustainability API was he only reason to set the `SameSite` attribute to `None`.
Using Lax is more secure, as browser will never send the cookie in a cross-site request.
---
- User's documentation (`docs`): https://docs--11721.org.readthedocs.build/en/11721/
- Developer's documentation (`dev`): https://dev--11721.org.readthedocs.build/en/11721/
=> Set session cookie `SameSite` attribute to `Lax` for main site

.readthedocs.yml, docs/dev/design/yaml-file.rst, docs/dev/install.rst, docs/user/flyout-menu.rst, docs/user/pull-requests.rst
Also enables checking for this in the future.
---
- User's documentation (`docs`): https://docs--11723.org.readthedocs.build/en/11723/
- Developer's documentation (`dev`): https://dev--11723.org.readthedocs.build/en/11723/
=> Fix docs warnings and broken links

docs/user/index.rst
---
- User's documentation (`docs`): https://docs--11705.org.readthedocs.build/en/11705/
- Developer's documentation (`dev`): https://dev--11705.org.readthedocs.build/en/11705/
=> Clean up front page copy

docs/user/api/v3.rst, readthedocs/api/v3/serializers.py, readthedocs/api/v3/tests/responses/projects-detail.json, readthedocs/api/v3/tests/test_projects.py, readthedocs/api/v3/views.py
There is no data for this field in CF, so nobody is using it.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1874
---
- User's documentation (`docs`): https://docs--11730.org.readthedocs.build/en/11730/
- Developer's documentation (`dev`): https://dev--11730.org.readthedocs.build/en/11730/
=> API v3: remove last_build expandable field

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
We always return all the active versions no matter the versioning scheme of the project. That's how `versions.active` is expected to work.
However, it seems the conditional was below where these versions are calculated. I also updated the test case that checks for the active versions on single versions projects.
Closes https://github.com/readthedocs/sphinx_rtd_theme/issues/1613
=> Addons: return all active versions on single version project

readthedocs/api/v3/serializers.py
If a project is public, we don't want to show
the organization information, but it can still be useful to see which organization the project belongs to.
Tests are in .com
=> API V3: use a restricted serializer for when showing org info from a project

.github/workflows/pip-tools.yaml
Currently, this GitHub Action creates new pull requests on the forks of all contributors.  Let's make sure that the job only creates pull requests
```yaml
if: github.repository_owner == 'readthedocs'
```
https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context
=> Do not automatically create pip-tools pull requests on forks of this repo

docs/user/api/v3.rst, readthedocs/api/v3/serializers.py, readthedocs/api/v3/tests/test_remoterepositories.py, readthedocs/api/v3/views.py
This allows us to filter by the permissions the current user has on the projects.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1876
---
- User's documentation (`docs`): https://docs--11731.org.readthedocs.build/en/11731/
- Developer's documentation (`dev`): https://dev--11731.org.readthedocs.build/en/11731/
=> API v3: always return projects when listing remote repositories

.github/workflows/pip-tools.yaml
It started adding absolute paths, instead of relatives.
Related https://github.com/jazzband/pip-tools/issues/2131
Related https://github.com/readthedocs/readthedocs.org/pull/11754
=> Pin pip for pip-tools for now

readthedocs/builds/views.py, readthedocs/core/context_processors.py, readthedocs/core/notifications.py, readthedocs/projects/views/private.py, readthedocs/rtd_tests/tests/test_notifications.py, readthedocs/settings/base.py
Notification on new dashboard:
Notification on old dashboard:
----
- Fixes #11209
- Requires https://github.com/readthedocs/ext-theme/pull/524
- Refs https://github.com/readthedocs/website/pull/335
=> Fix site-wide new dashboard notification

docs/dev/install.rst
---
- User's documentation (`docs`): https://docs--11777.org.readthedocs.build/en/11777/
- Developer's documentation (`dev`): https://dev--11777.org.readthedocs.build/en/11777/
=> Docs: update connected accounts steps to use env vars

docs/user/guides/custom-domains.rst
Closes https://github.com/readthedocs/readthedocs.org/issues/11371
ref https://github.com/readthedocs/readthedocs.org/issues/11242
https://docs--11734.org.readthedocs.build/en/11734/guides/custom-domains.html
---
- User's documentation (`docs`): https://docs--11734.org.readthedocs.build/en/11734/
- Developer's documentation (`dev`): https://dev--11734.org.readthedocs.build/en/11734/
=> Docs: update custom domains docs

readthedocs/settings/base.py
I keep hitting memory limits locally.
I wonder if we should just use the "Determine limits dynamically" in dev.
I'm not sure why that isn't better than hard limits?
=> Increase default docker limits

readthedocs/embed/views.py
Ref https://github.com/readthedocs/readthedocs.org/issues/10677
=> Set brownouts for deprecated embed API v2

docs/dev/settings.rst, readthedocs/settings/docker_compose.py
---
- User's documentation (`docs`): https://docs--11790.org.readthedocs.build/en/11790/
- Developer's documentation (`dev`): https://dev--11790.org.readthedocs.build/en/11790/
=> Support RTD_USE_PROMOS for setting USE_PROMOS in dev

readthedocs/settings/base.py
SQL and Templates panles are pretty slow to render. We are disabling them by default but still showing the panel in the toolbar, so they can be re-enabled if required from there.
=> Django Debug Toolbar: disable slow panels

dockerfiles/Dockerfile
This is a small test to `uv`. It speeds up the creation of the Docker image a lot in my case and it doesn't require changing anything else -- we keep using the exact same `docker.txt` file that we generate with `pip-tool`.
Eventually, if we feel comfortable with it, we can use it more broadly in other places as well.
=> Development: try `uv` on Docker images

dockerfiles/Dockerfile
- Install `uv` under `/usr/bin`
- Replace `pip` installation of ext-theme and -ext with `uv`
Related https://github.com/readthedocs/readthedocs-corporate/pull/1916/
=> Development: use `uv` to install everything

docs/user/api/v3.rst, docs/user/guides/embedding-content.rst, readthedocs/embed/v3/tests/test_external_pages.py, readthedocs/embed/v3/views.py
We need different CSS selectors to find the main content node depending on the documentation tool used.
This PR adds the `?selector=` attribute to the EmbedAPI to accept a specific selector for the main content of the page. This attribute will be sent by the Addons frontend code using the heuristic code we wrote there.
If this specific selector is not sent, we fallback to the default selector's value.
=> EmbedAPI: main content based on documentation tool

readthedocs/doc_builder/environments.py, readthedocs/doc_builder/exceptions.py, readthedocs/notifications/exceptions.py, readthedocs/notifications/messages.py, readthedocs/projects/tasks/builds.py
So, we were using incorrectly the exceptions, as we were passing a message to them, but they were expecting a message_id, I guess what we wanted is to have that error being show somewhere in the exception message, so I added a field for that, but the notification itself will show the generic error. And of course, there is now one message for rclone failures.
closes https://github.com/readthedocs/readthedocs.org/issues/11544
=> Build: better error message when rclone fails

readthedocs/embed/v3/views.py
Tru for the URL ending with `index.html` if the original URL doesn't exist in the storage.
This makes Sphinx HTMLDir build, Docusaurus and other documentation tools with pretty URLs to work properly.
=> EmbedAPI: support "pretty URLs"

readthedocs/projects/admin.py
This was causing the AddonsConfig admin to time out.
=> Fix AddonsConfig admin base_version.

readthedocs/projects/forms.py, readthedocs/rtd_tests/tests/test_domains.py
urlparse can throw ValueError when parsing a URL, we didn't experience this before because none of our tests were failing when calling urlparse, but there was a new release of python that now fails parsing some of our test cases https://github.com/python/cpython/issues/122792.
=> Domains: check for urlparse errors

readthedocs/api/v2/urls.py
We are not serving EthicalAds from Read the Docs anymore. We are hitting the EthicalAds server directly using Addons.
Matches https://github.com/readthedocs/readthedocs-ext/pull/563
=> Remove EthicalAd URLs

readthedocs/projects/views/private.py
I think this fixes it (at least makes .com tests green), but we don't have tests for this, so not sure if it doesn't break anything else. @humitos you may want to test it locally.
ref https://read-the-docs.sentry.io/issues/6127455073/?project=161479&query=is%3Aunresolved&referrer=issue-stream&sort=trends&statsPeriod=90d&stream_index=3
=> Fix import wizard

docs/user/commercial/single-sign-on.rst, docs/user/guides/access/index.rst, docs/user/guides/manage-read-the-docs-teams.rst, docs/user/guides/managing-maintainers.rst, docs/user/index.rst, docs/user/intro/accounts.rst
This adds two pages:
* A intro reference page on authentication methods
* A guide on managing maintainers for Community
These are just basic places to start on this content.
I wasn't 100% sure the best way to structure the Authencation methods page,
so definitely would like feedback on that one.
Fixes https://github.com/readthedocs/readthedocs.org/issues/11835
---
- User's documentation (`docs`): https://docs--11834.org.readthedocs.build/en/11834/
- Developer's documentation (`dev`): https://dev--11834.org.readthedocs.build/en/11834/
=> Add authentication documentation

docs/user/addons.rst, docs/user/index.rst, docs/user/pull-requests.rst, docs/user/visual-diff.rst
Related https://github.com/readthedocs/readthedocs.org/pull/11838
---
- User's documentation (`docs`): https://docs--11860.org.readthedocs.build/en/11860/
- Developer's documentation (`dev`): https://dev--11860.org.readthedocs.build/en/11860/
=> Docs: use "Visual diff" for marketing "Doc Diff"

readthedocs/organizations/models.py
I'm not sure why this doesn't match, but it's confusing to work with in
some templates that sometimes list `TeamMember` and other times list
`User` instances. Instead, just match these methods so it's always the
same.
- Refs readthedocs/ext-theme#546
=> Match User method in TeamMember

readthedocs/api/v2/serializers.py, readthedocs/builds/models.py, readthedocs/doc_builder/director.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/tests/test_api.py, readthedocs/rtd_tests/tests/test_project_forms.py, readthedocs/rtd_tests/tests/test_version.py, readthedocs/rtd_tests/tests/test_version_commit_name.py
A commit can point to more than one branch/tag, so using git describe/name-rev or similar doesn't work reliably. Since we already have the tag/branch name for most of the versions (verbose_name), we can just use that, there are only three special cases:
- LATEST: this is an alias for the default branch
- STABLE: this is an alias for the stable version
- External versions: we don't save the name of the base branch, just the commit and PR number, so not sure what to return here, I'm returning the commit for now. Maybe we can update the docs to mention this.
`commit_name` was doing exactly that, except for stable, so I went ahead and renamed it and refactored it (we were no longer using it) to use it in our API, so builders have access to it.
Closes …
=> Build: use actual git identifier for READTHEDOCS_GIT_IDENTIFIER

readthedocs/projects/tasks/builds.py
This is a user facing error,
but shouldn't show up in our Sentry.
=> Lower logging for user build errors

readthedocs/projects/views/private.py
**THIS VULNERABILITY CAN'T BE EXPLOITED**
- We only allow values that are a from an existing username (usernames are alphanumeric)
- The user needs to have been added to the project
- The action is from a post request, the button that triggers that action is marked as disabled when the user is the last owner.
=> Don't reflect user input in raw response

docs/user/reference/environment-variables.rst, readthedocs/builds/models.py, readthedocs/rtd_tests/tests/test_version.py, readthedocs/rtd_tests/tests/test_version_commit_name.py
Ref https://github.com/readthedocs/readthedocs.org/pull/11875
---
- User's documentation (`docs`): https://docs--11893.org.readthedocs.build/en/11893/
- Developer's documentation (`dev`): https://dev--11893.org.readthedocs.build/en/11893/
=> Environment variables: document special case for PR preview builds

docs/user/intro/mdbook.rst, docs/user/intro/mkdocs.rst
We don't need to tell the users to perform extra steps on these documentation tools because addons is going to do this by default now: https://github.com/readthedocs/addons/pull/473
---
- User's documentation (`docs`): https://docs--11897.org.readthedocs.build/en/11897/
- Developer's documentation (`dev`): https://dev--11897.org.readthedocs.build/en/11897/
=> Docs: remove CSS variables override for font-size

readthedocs/config/config.py, readthedocs/config/tests/test_config.py
Closes https://github.com/readthedocs/readthedocs.org/issues/11912
=> Don't require sphinx/mkdocs keys when using build.commands

docs/user/build-customization.rst, docs/user/builds.rst, docs/user/config-file/v2.rst, docs/user/intro/docusaurus.rst, docs/user/intro/mdbook.rst
- Document all new jobs
- Replace almost all usage of build.commands with build.jobs
- Unify examples, as they are all now part of build.jobs
Ref https://github.com/readthedocs/readthedocs-ops/issues/1582
---
- User's documentation (`docs`): https://docs--11900.org.readthedocs.build/en/11900/
- Developer's documentation (`dev`): https://dev--11900.org.readthedocs.build/en/11900/
=> Document new build jobs

docs/user/intro/markdoc.rst
The test-builds example was updated as well https://github.com/readthedocs/test-builds/tree/markdoc
---
- User's documentation (`docs`): https://docs--11929.org.readthedocs.build/en/11929/
- Developer's documentation (`dev`): https://dev--11929.org.readthedocs.build/en/11929/
=> Docs: update markdoc example to use build.jobs

docs/user/intro/markdoc.rst
---
- User's documentation (`docs`): https://docs--11932.org.readthedocs.build/en/11932/
- Developer's documentation (`dev`): https://dev--11932.org.readthedocs.build/en/11932/
=> Docs: fix markdoc example

docs/user/build-customization.rst
Ref https://github.com/readthedocs/readthedocs.org/pull/11900#pullrequestreview-2547761970
---
- User's documentation (`docs`): https://docs--11927.org.readthedocs.build/en/11927/
- Developer's documentation (`dev`): https://dev--11927.org.readthedocs.build/en/11927/
=> Docs: update build customization docs

docs/user/builds.rst
---
- User's documentation (`docs`): https://docs--11943.org.readthedocs.build/en/11943/
- Developer's documentation (`dev`): https://dev--11943.org.readthedocs.build/en/11943/
=> Note that there's a soft disk limit for doc builds

docs/user/intro/doctools.rst, docs/user/intro/vitepress.rst
I fixed the test-builds repo to work properly,
and this also links out to a user example repo, but I want to improve that probably with a logo.
Refs Refs https://github.com/readthedocs/addons/pull/503
---
- User's documentation (`docs`): https://docs--11944.org.readthedocs.build/en/11944/
- Developer's documentation (`dev`): https://dev--11944.org.readthedocs.build/en/11944/
=> Add vitepress doc page

readthedocs/projects/models.py, readthedocs/rtd_tests/tests/test_sync_versions.py
Closes https://github.com/readthedocs/readthedocs.org/issues/11939
This also discovered another problem, we are using the verbose name to check for latest/stable, but we should use the slug
https://github.com/readthedocs/readthedocs.org/blob/10d9ef95736b3106b4c5c551df57dda8ed1000e2/readthedocs/vcs_support/backends/git.py#L135-L145
Will try to fix that in another PR, as we need to pass the slug down...
=> Version sync: restore verbose_name for stable version

readthedocs/proxito/tests/responses/v1.json, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
This is required to be able to dynamically update the URLs from the versions in the flyout when the page is changed using `history` object (without reloading / SPA) as Docusaurus does.
In that scenario we cannot use the HTML META tag because it was injected with the old value by CF Worker. Note that the CF Worker is not run after the initial request on SPA.
The addons frontend will use this attribute to update those URLs accordingly when the URL changes.
Required by:
* https://github.com/readthedocs/addons/pull/504
=> Addons: expose `readthedocs.resolver.filename` in the API response

readthedocs/core/views/hooks.py, readthedocs/rtd_tests/tests/test_api.py
This is so we can better support custom queues,
but not block sync versions on them.
=> Always run sync_versions on the default queue

readthedocs/projects/admin.py
This is useful for Business where we have a lot of common names
=> Show slug on AddonsConfigAdmin

readthedocs/projects/tasks/builds.py
Trigger the task to check for spam after the build succeed. It won't run for all the projects, only for those that we suspect could be spam ;)
Requires: https://github.com/readthedocs/readthedocs-ext/pull/569
=> Run spam check after a sucessful build

readthedocs/projects/tasks/builds.py
This is so if a listener fails we still clean up
=> Be defensive with build_complete signal

readthedocs/projects/querysets.py
Use the DONT_SERVE_DOCS threshold to decide whether or not the build for this project should be triggered/skipped. This should avoid project already marked as spam to re-trigger builds and try to be re-classified as non-spam.
=> Build: don't trigger build if the project is spam

docs/user/addons.rst
We had a user asking about this,
so pulled it from the Mkdocs example to the high-level Addons docs.
---
- User's documentation (`docs`): https://docs--11984.org.readthedocs.build/en/11984/
- Developer's documentation (`dev`): https://dev--11984.org.readthedocs.build/en/11984/
=> Add a doc for how to integrate search without other customization

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
They were pinned due to a bug, but it was fixed already.
closes https://github.com/readthedocs/readthedocs.org/issues/11367
=> Requirements: unpin `requests` and `docker`

readthedocs/builds/tasks.py, readthedocs/oauth/models.py, readthedocs/oauth/services/base.py, readthedocs/oauth/services/bitbucket.py, readthedocs/oauth/services/github.py, readthedocs/oauth/services/gitlab.py, readthedocs/oauth/tasks.py, readthedocs/oauth/utils.py, readthedocs/projects/models.py, readthedocs/projects/views/mixins.py, readthedocs/projects/views/private.py, readthedocs/rtd_tests/tests/test_celery.py, readthedocs/rtd_tests/tests/test_oauth.py, readthedocs/rtd_tests/tests/test_oauth_sync.py, readthedocs/rtd_tests/tests/test_project.py, readthedocs/rtd_tests/tests/test_project_views.py
With https://github.com/readthedocs/readthedocs.org/pull/11942, a GH app is used to interact with the GH API,
a GH app is not directly tied to a user, so this assumption is not valid anymore.
For most of the operations (except for syncing repos), we don't need to know who is the user that is performing the action, we just need to know the project that is being affected.
- The base provider doesn't assume that we are always using an oauth token, that's an implementation detail of each provider. We also no longer directly depend on allauth from the base provider.
- Every provider implements the operations, no more checks for specific providers (e.g checking for BB when sending a build status).
=> Git service: depend on the project instead of users

.circleci/config.yml, dockerfiles/Dockerfile, docs/dev/install.rst, docs/dev/tests.rst, requirements/deploy.txt, requirements/docker.txt, requirements/docs.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt, tox.embedapi.ini, tox.ini
- Use Ubuntu 24.04 for our Docker images
- The application runs with Python 3.12 now
- Run tests with Python 3.12
- Update APT package names
- Install `uv` in the default directory `~/.local/bin`
- Add `uv` to the PATH
- Create a virtualenv inside the Docker image for our application. `--system` option does not work anymore with the newer `pip` versions. It fails saying that we should install Python dependencies using system package.
- Upgrade Celery dependency to be compatible with Python 3.12
- The `pickle` error we used to see with Celery does not happen anymore with the newer version + py3.12
- Remove `tzdata` because it's installed automatically now
- All the Python commands inside the Docker container needs to be prefixed with `uv run` now. Example: `uv run tox -e 312` or `uv run …
=> Upgrade to Ubuntu 24.04 for our application

readthedocs/builds/utils.py, readthedocs/projects/models.py, readthedocs/rtd_tests/tests/test_project.py, readthedocs/vcs_support/backends/git.py
Ref https://github.com/readthedocs/readthedocs.org/pull/11983/files/8e6caa3e6157a0230c0989784e8a421cacd7f7bd#r1953455261
=> Project: don't depend on the brand name

readthedocs/builds/tasks.py, readthedocs/oauth/services/base.py, readthedocs/oauth/services/github.py, readthedocs/oauth/services/gitlab.py, readthedocs/rtd_tests/tests/test_celery.py, readthedocs/rtd_tests/tests/test_oauth.py
A small refactor extracted from https://github.com/readthedocs/readthedocs.org/pull/11942
=> Service: kwargs only when sending build statuses

docs/user/visual-diff.rst
Briefly explanation about how to use visual doc diff.
Closes #12009
---
- User's documentation (`docs`): https://docs--12011.org.readthedocs.build/en/12011/
- Developer's documentation (`dev`): https://dev--12011.org.readthedocs.build/en/12011/
=> File Tree Diff: small documentation to mention the file selector

readthedocs/oauth/management/commands/reconnect_remoterepositories.py, readthedocs/oauth/services/base.py, readthedocs/oauth/tasks.py
Extracted from
https://github.com/readthedocs/readthedocs.org/pull/11942.
Instead of getting a service for the user and manually syncing the repositories, this abstracts syncing the access to the repositories in another method. This is since with GH apps, syncing the access to the repositories is done in a different way.
=> Git service: add method to sync user access to remote repositories

docs/user/intro/doctools.rst
---
- User's documentation (`docs`): https://docs--12019.org.readthedocs.build/en/12019/
- Developer's documentation (`dev`): https://dev--12019.org.readthedocs.build/en/12019/
=> Fix mkdocs link

docs/user/guides/set-up-single-sign-on-saml.rst
This updates both the data URLs that users need to use and the dashboard pointer links.
---
- User's documentation (`docs`): https://docs--12031.org.readthedocs.build/12031/
- Developer's documentation (`dev`): https://dev--12031.org.readthedocs.build/12031/
=> Update URLs for SAML to point to new dashboard

dockerfiles/Dockerfile
uv checks if there is a .venv directory in the cwd and uses it automatically, this easily collides with the virtual environment created by uv outside the container (inv, having lsp working, etc).
Closes https://github.com/readthedocs/readthedocs.org/pull/12036/
=> Explicitly define virtual environment used in Docker

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
xmlsec is a dependecy from python3-saml which is required by django-allauth. We have to pin it because the underlying `libxml2-dev` package installed at system level is incompatible with the Python version
More info https://github.com/xmlsec/python-xmlsec/issues/324
=> Requirements: pin and downgrade `xmlsec`

.github/workflows/pip-tools.yaml
Upgrade version of Python used for pip-tools.
=> pip tools: use Python 3.12

readthedocs/settings/base.py
These settings have been deprecated in 65.4.0 and 65.5.0, https://docs.allauth.org/en/latest/release-notes/recent.html.
=> Allauth: update deprecated settings

readthedocs/organizations/models.py, readthedocs/subscriptions/event_handlers.py, readthedocs/subscriptions/tests/test_event_handlers.py
- Updated the `get_stripe_subscription` method to prioritize certain subscription statuses over others, so unpaid subscriptions are still visible to the user.
- Our webhooks now respect the never_disable setting from the organization, so we don't disable some orgs automatically, we also skip sending notifications. We should mark this attribute only after being contacted by the owners, and marked as false once the issue has been resolved, so we still send notifications next time they don't pay on time.
=> Subscriptions: improve subscription detection and respect never_disable

docs/user/api/v3.rst
Had a user asking for this.
---
- User's documentation (`docs`): https://docs--12063.org.readthedocs.build/12063/
- Developer's documentation (`dev`): https://dev--12063.org.readthedocs.build/12063/
=> API v3: document rate limit and pagination

readthedocs/core/views/hooks.py
- When a PR preview is re-opened, make sure to reset its status as active
- When closing a PR we don't need to take into consideration the commit, we act based on the ID only.
Extracted from https://github.com/readthedocs/readthedocs.org/pull/11942/
=> Small improvements on PR previews handling

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
This breaks importing xmlsec again
Reverts readthedocs/readthedocs.org#12056
=> Revert "Requirements: use xmlsec with `--no-binary` option"

docs/user/guides/private-python-packages.rst
---
- User's documentation (`docs`): https://docs--12074.org.readthedocs.build/12074/
- Developer's documentation (`dev`): https://dev--12074.org.readthedocs.build/12074/
=> Docs: mention fine-grained personal access token for GitHub

dockerfiles/settings/proxito.py, readthedocs/settings/base.py, readthedocs/settings/docker_compose.py, requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
Looks like we never ended up using this dependency. Ref https://github.com/readthedocs/readthedocs.org/pull/10075.
=> Remove cacheops

docs/user/faq.rst, docs/user/versions.rst, readthedocs/builds/forms.py, readthedocs/projects/models.py, readthedocs/rtd_tests/tests/test_build_forms.py
Closes https://github.com/readthedocs/readthedocs.org/issues/11971
---
- User's documentation (`docs`): https://docs--12096.org.readthedocs.build/12096/
- Developer's documentation (`dev`): https://dev--12096.org.readthedocs.build/12096/
=> Version: document how to change the version slug and expose it to everyone

readthedocs/oauth/querysets.py
This is a better solution other than always excluding repos from the old integration or the new one. This can be safely be deployed.
=> GitHub: show repos from old or new GH integration only

readthedocs/projects/models.py, readthedocs/projects/tests/test_build_tasks.py, readthedocs/rtd_tests/tests/test_project_forms.py
We had two ways of keeping latest in sync with the default branch chosen by the user, one on project save and another one when syncing versions, they are slightly different leading to some inconsistencies. We now always use update_latest_version.
Closes https://github.com/readthedocs/readthedocs.org/issues/12029
=> Versions: always keep latest in sync with default branch/tag

requirements/deploy.txt, requirements/docker.txt, requirements/docs.txt, requirements/pip.txt, requirements/testing.txt
Reverts readthedocs/readthedocs.org#12135
This breaks .com
> E   xmlsec.Error: (100, 'lxml & xmlsec libxml2 library version mismatch')
=> Revert "Dependencies: all packages updated via pip-tools"

pytest.ini, readthedocs/oauth/models.py, requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
We need to upgrade `djstripe` first because the admin is broken otherwise.
See https://github.com/readthedocs/readthedocs.org/issues/9706
=> Downgrade to Django 4.2.x due to `djstripe`

docs/user/intro/mkdocs.rst
Closes #12032
---
- User's documentation (`docs`): https://docs--12142.org.readthedocs.build/12142/
- Developer's documentation (`dev`): https://dev--12142.org.readthedocs.build/12142/
=> Docs: handle versions when "instant loading" feature enabled

readthedocs/search/parsers.py, readthedocs/search/tests/test_parsers.py
Our search index is growing fast, mostly due that we are supporting all types of inputs, not just sphinx and mkdocs. This means that even malformed content may be indexed, resulting in us indexing invalid/long content.
=> Search: truncate contents before indexing

readthedocs/gold/tests/test_signals.py, readthedocs/subscriptions/tests/test_event_handlers.py, requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
=> Upgrade `djstripe`

readthedocs/subscriptions/event_handlers.py
Fixes https://app.circleci.com/pipelines/github/readthedocs/readthedocs-corporate/6298/workflows/2544845e-337e-452e-acac-a7852f22637b/jobs/19926/parallel-runs/0/steps/0-106
Related https://github.com/readthedocs/readthedocs.org/pull/12148
=> Update djstripe handlers (`webhook.handler` was deleted)

readthedocs/projects/apps.py
We found this while performing the deploy.
Builders do not have access to the database, and `djstripe` runs some checks
that access the database to know if there are API keys defined there.
References:
* https://github.com/dj-stripe/dj-stripe/blob/main/djstripe/checks.py#L126
* https://github.com/django/django/blob/main/django/core/checks/registry.py#L85
* https://docs.djangoproject.com/en/5.2/topics/checks/
=> Do not run `djstripe` checks on builders

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
https://github.com/readthedocs/readthedocs.org/pull/12166 breaks .com tests on CircleCI due to XML mismatch versions. This PR pins `lxml` as well to avoid that issue.
=> Downgrade `lxml` to avoid mismatch versions

readthedocs/doc_builder/environments.py, readthedocs/doc_builder/tests/test_environments.py
ref https://readthedocs.slack.com/archives/C04SS8XNB6K/p1746136083159309
NOTE: this isn't a vulnerability, as all commands that make use of this function are run inside a container.
=> Build: escape all whitespaces

requirements/pip.in, requirements/pip.txt
Downgrade to avoid redis bug, probably with our hostname hack for djstire? See #12171 for the error.
=> Downgrade Redis back to 5.2.1

docs/user/index.rst
---
- User's documentation (`docs`): https://docs--12179.org.readthedocs.build/12179/
- Developer's documentation (`dev`): https://dev--12179.org.readthedocs.build/12179/
=> Add doc tools to frontpage

docs/dev/contribute.rst
@ericholscher mentioned that it's not very active, and we can remove the mention. :)
---
- User's documentation (`docs`): https://docs--12188.org.readthedocs.build/12188/
- Developer's documentation (`dev`): https://dev--12188.org.readthedocs.build/12188/
=> Remove mention of Gitter from contributor docs

docs/user/build-customization.rst
This is another example for the build customization example gallery,
demonstrating how to use `pip` to install from a dependency group.
---
- User's documentation (`docs`): https://docs--12189.org.readthedocs.build/12189/
- Developer's documentation (`dev`): https://dev--12189.org.readthedocs.build/12189/
=> Add an example of `pip install --group`

docs/dev/docs.rst
Need to set `PROJECT=dev`, instead of `RTD_DOCSET=dev`
---
- User's documentation (`docs`): https://docs--12190.org.readthedocs.build/12190/
- Developer's documentation (`dev`): https://dev--12190.org.readthedocs.build/12190/
=> Update dev site build step

docs/dev/contribute.rst
Addresses #5676 
---
- User's documentation (`docs`): https://docs--12191.org.readthedocs.build/12191/
- Developer's documentation (`dev`): https://dev--12191.org.readthedocs.build/12191/
=> Add note about contributing to other RTD projects

docs/user/build-customization.rst
Closes https://github.com/readthedocs/readthedocs.org/issues/12161
---
- User's documentation (`docs`): https://docs--12194.org.readthedocs.build/12194/
- Developer's documentation (`dev`): https://dev--12194.org.readthedocs.build/12194/
=> Add info on generating docs in `.txt` format

readthedocs/core/adapters.py, readthedocs/core/tests/test_adapters.py
This prevents users already using the new GH app from creating another account by mistake with the old app.
=> GitHub App: block GH app users to re-connect to old OAuth app

docs/dev/aws-temporary-credentials.rst
It was decided to use this name for the role in dev.
---
- User's documentation (`docs`): https://docs--12196.org.readthedocs.build/12196/
- Developer's documentation (`dev`): https://dev--12196.org.readthedocs.build/12196/
=> Docs: update AWS temporary credentials documentation

readthedocs/core/adapters.py, readthedocs/core/tests/test_adapters.py
```
warnings.warn("allauth.exceptions is deprecated, use allauth.core.exceptions")
```
=> Remove allauth warning

readthedocs/projects/filters.py
This was missing from the queryset, causing the templates to use
`Project.get_latest_build(finished=True)`, effectively. When using
`prefetch_latest_build()`, the response from `get_latest_build` is the
first build of _any_ build state.
- Refs https://github.com/readthedocs/ext-theme/pull/607
- Refs https://github.com/readthedocs/readthedocs.org/issues/11840
=> Add Project queryset `prefetch_latest_build()` to project filter

readthedocs/oauth/services/gitlab.py, readthedocs/rtd_tests/tests/test_oauth.py
name has only the last part of the group namespace. For example, for a group under the `group/subgroup` namespace, path would be `subgroup`, and full_path would be `group/subgroup`. The slug is a charfield, so it's okay to have `/`, looks like we aren't using this field for anything important, so don't think we need to resync all organizations.
ref https://github.com/readthedocs/readthedocs.org/pull/12233
=> GitLab: Use full path for GitLab groups/organizations

readthedocs/proxito/tests/test_old_redirects.py, readthedocs/proxito/views/mixins.py
When the redirect logic is run from the 404 handler, the request actually comes from the `/_proxito_404_/path/to/file` path, so we can't compare the path from the current request to check for infinite redirects, we already pass the proper path from the request or 404 in the path parameter.
=> Redirect: fix infinite redirect in 404 view

docs/user/commercial/single-sign-on.rst, docs/user/guides/access/index.rst, docs/user/guides/manage-read-the-docs-teams.rst, docs/user/guides/set-up-single-sign-on-saml.rst, docs/user/guides/setup-single-sign-on-github-gitlab-bitbucket.rst, docs/user/guides/setup-single-sign-on-google-email.rst, docs/user/index.rst
There are a few different casing issues and punctuation styles, this
reduces down to "single sign-on" for all of our usage.
---
- User's documentation (`docs`): https://docs--12256.org.readthedocs.build/12256/
- Developer's documentation (`dev`): https://dev--12256.org.readthedocs.build/12256/
=> Normalize usage of "single sign-on"

readthedocs/settings/base.py
The `settings` attribute isn't super well documented, but it is used
from the template tag for listing providers. We can also use settings
for arbitrary values if we want.
See https://codeberg.org/allauth/django-allauth/src/commit/b74b04a8261486db8a3823c26c188820aed599aa/allauth/socialaccount/templatetags/socialaccount.py#L84
=> Use Allauth settings for app name and hiding on login/connect forms

docs/user/build-customization.rst
This adds a complete example of using [pydoctor](https://github.com/twisted/pydoctor). 
The generated docs will include links to the source code and the standard library types when relevant. 
---
- User's documentation (`docs`): https://docs--12259.org.readthedocs.build/12259/
- Developer's documentation (`dev`): https://dev--12259.org.readthedocs.build/12259/
=> Add example usage of pydoctor in the build customization page

docs/user/reference/git-integration.rst
---
- User's documentation (`docs`): https://docs--12270.org.readthedocs.build/12270/
- Developer's documentation (`dev`): https://dev--12270.org.readthedocs.build/12270/
=> Docs: fix link to blog post

readthedocs/proxito/views/hosting.py
Initial small approach to make the "Include subprojects" filter enabled by default. I'm adding a new field to the search filter to communicate if it's enabled or disabled by default. This value will be able to be changed by the user in the future from the project admin settings.
* Related https://github.com/readthedocs/addons/issues/22
=> Addons: default "Include subprojects" to true on search

readthedocs/oauth/services/githubapp.py, readthedocs/rtd_tests/tests/test_oauth.py
When an app is installed into an organization, GH will send events related to members being added/removed from repositories, even if those repositories weren't granted access to the app.. so when attempting to sync the collaborators from those repositories, there was an error from GH since we don't have access to those. This is mainly a problem with public repos, as for private repos GH will always return a 404 if the app doesn't have access.
This isn't breaking anything from our logic, just creating remote repositories we don't need and filling sentry with errors.
ref https://read-the-docs.sentry.io/issues/6701666499/events/0ef3cf2bb9554e39bc2dd9b874aef879/events/?project=148442
=> GitHub App: don't sync repositories that the app doesn't have access to

readthedocs/projects/models.py
This was only used for the email notification about the SSH  keys.
=> Project: fix regex

dockerfiles/Dockerfile
Use `ARG` in Dockerfile to invalidate the cache when this argument changes.
Requires https://github.com/readthedocs/common/pull/244
=> Development: accept `PRUNE_PACKAGE_CACHE` argument in Dockerfile

readthedocs/organizations/forms.py, readthedocs/organizations/tests/test_forms.py, readthedocs/organizations/tests/test_views.py
Found today that we introduced some bugs on the organization form,
namely we aren't validating the user provided slug, only validating the
user provided name rendered to a slug.
This also ensures we're slugging for DNS safely, as this is just
prepended to project URLs without much validation.
Closes https://github.com/readthedocs/readthedocs.org/issues/12305
=> Fix bugs with organization form and slug input

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
I tried this locally with
```python
BROKER_USE_SSL = {
'ssl_cert_reqs': ssl.CERT_NONE,
}
```
and the error reported in the issue is not present anymore but I'm not able to trigger builds 🤷🏼 
Closes #12171
=> Upgrade redis to its latest version (`6.2.0`)

readthedocs/builds/reporting.py, readthedocs/builds/tasks.py, readthedocs/builds/tests/test_tasks.py, readthedocs/oauth/services/base.py, readthedocs/oauth/services/githubapp.py, readthedocs/rtd_tests/tests/test_oauth.py
This is so we don't create comments when no files have been changed, but we still update the comment if we already reported a build with changed files.
=> Build overview: don't create comment for projects with empty diffs

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
Did some benchmarking with [django-silk
](https://github.com/jazzband/django-silk)
The main thing is that sorting introduces some overhead to the query, calling exists doesn't require sorting, so it's faster.
```
Query Plan
Limit  (cost=0.14..18.32 rows=1 width=4)
->  Limit  (cost=0.14..18.32 rows=1 width=4)
->  Nested Loop  (cost=0.14..18.32 rows=1 width=4)
Join Filter: (projects_project.id = u0.id)
->  Seq Scan on projects_project  (cost=0.00..10.15 rows=1 width=4)
Filter: ((id <> 28) AND ((privacy_level)::text = 'public'::text))
->  Index Scan using projects_project_main_language_project_id_5215229a on projects_project u0  (cost=0.14..8.15 rows=1 width=4)
Index Cond: (main_language_project_id = 28) 
```
vs
```
Unique  (cost=27.94..28.16 rows=1 width=10546)
->  Sort  (cost=27.94..27.94 …
```
=> Addons: improve performance when fetching translations

readthedocs/api/v3/serializers.py, readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
- Instead of passing the version slug to the project serializer, just pass the actual version, so we can use resolve_version, this reduces one less query.
- We were passing the resolver around some places, but doing this weird thing where removing it from kwargs, and then adding it again. This introduced a bug that was creating a new resolver for each serializer instance instead of re-using the one passed to the initializer.
This took ~10ms off locally
Note: I'm running these benchmarks in power saver mode, otherwise my computer is too fast and can't get meaningful comparisons :D
=> Addons: improve serializer performance

readthedocs/settings/base.py
This is the time Celery waits for the worker to ack the task. After this time, Celery will re-deliver this task to another worker.
```
In [1]: from readthedocs.worker import app
In [2]: app.conf.get("BROKER_TRANSPORT_OPTIONS")
Out[2]: {'visibility_timeout': 18000}
```
Closes #12317
=> Celery: increase the "visibility timeout" from 1h to 5h

readthedocs/core/utils/__init__.py, readthedocs/projects/models.py
Another attempt to run builds longer than 1h in a reliably way.
Related: #12317
=> Builds: feature flag to disable ACKS_LATE per project

readthedocs/core/utils/__init__.py
This will help us when debugging.
=> Build: log all the Celery `options` passed to the task

readthedocs/oauth/tasks.py, readthedocs/oauth/views.py
We are experiencing some delays sometimes, this should be useful to pinpoint the problem.
=> GitHub App: track debug logs as info

requirements/deploy.txt, requirements/docker.txt, requirements/pip.in, requirements/pip.txt, requirements/testing.txt
We were relying on clean_email not being called on autosignup. That was changed in the latest release, and it's not allowing users to sign up with Google/SAML.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/2029
=> Downgrade django-allauth

readthedocs/doc_builder/environments.py, readthedocs/rtd_tests/tests/test_doc_building.py
Replace the value of private variables with the first 4 chars of it and `****`. This is a protection to avoid leaking private variables by mistake.
The same pattern is used in the dashboard when listing these variables.
Closes https://github.com/readthedocs/readthedocs-corporate/issues/2004
=> Build: obfuscate private variables

readthedocs/core/utils/__init__.py, readthedocs/doc_builder/environments.py
By calling this log line _after_ `prepare_build` we will be logging more useful infomation like `build_id` on this line together with all the options passed to the task. This is useful for debug.
=> Build: log "Triggering build." with more data

readthedocs/projects/querysets.py, readthedocs/rtd_tests/tests/test_project_views.py
This used to be 35 queries. I found another optimization to make it to constant time, but will open another PR as it may produce a slow query..
=> Dashboard: optimize projects queryset

readthedocs/builds/tests/test_tasks.py, readthedocs/filetreediff/dataclasses.py, readthedocs/templates/core/build-overview.md
Implement what we discussed in
https://github.com/readthedocs/readthedocs.org/pull/12295. This is not perfect and it doesn't pretend to be, it's just one of the implementations after a few discussion iterations in the comments.
The idea of this PR is to have something a little better than what we have to be able to merge and move forward with.
Closes #12295
=> Build: shrink preview comment

readthedocs/projects/models.py, readthedocs/projects/querysets.py, readthedocs/rtd_tests/tests/test_project_views.py
This is on top of https://github.com/readthedocs/readthedocs.org/pull/12383/ as another PR in case we see a regression in performance, it would be easier to just revert this change.
Instead of pre-fetching, we annotate, so we can use exist instead of fetching the query. This allows to just make one query. But this does add some extra complexity to the query itself, which is less overhead than doing a prefetch over the queryset itself, but the pagination package we are using calls .count(), and django includes the annotation by default... which makes that query slower as well... but testing in production shows faster results still.
=> Dashboard: optimize projects queryset (constant number of queries)

readthedocs/projects/models.py
```
In [3]: dict(Feature.FEATURES)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 dict(Feature.FEATURES)
ValueError: dictionary update sequence element #2 has length 4; 2 is required
```
The object got malformed in
https://github.com/readthedocs/readthedocs.org/pull/12327
=> Features: fix `FEATURES` object

readthedocs/oauth/services/base.py, readthedocs/oauth/services/bitbucket.py, readthedocs/oauth/services/github.py, readthedocs/oauth/services/gitlab.py, readthedocs/rtd_tests/tests/test_oauth_sync.py
We were keeping all remote repos and org objects into memory, but only using its remote_id, this should help to reduce the memory footprint when syncing users with lots of repos.
=> Repo sync: don't keep all objects in memory

readthedocs/projects/views/private.py
On .org this doesn't reduce the number of queries, but it does for .com
=> Dashboard: cache get_queryset

readthedocs/projects/filters.py, readthedocs/projects/models.py, readthedocs/projects/querysets.py, readthedocs/projects/views/base.py, readthedocs/rtd_tests/tests/test_project.py, readthedocs/rtd_tests/tests/test_project_views.py
get_latest_build was doing something different than the prefetched value, looks like we never actually used this function with `finished=True`, so I went ahead and renamed it and made it a property so we can cache it.
=> Dashboard: don't prefetch latest build

readthedocs/api/v2/serializers.py, readthedocs/api/v2/views/model_views.py, readthedocs/rtd_tests/tests/test_api.py
If a version is deleted, we still keep its builds around, so we can't rely on the version being present. Ref https://read-the-docs.sentry.io/issues/3961831199/?project=148442
=> API: don't rely on the version object for builds

readthedocs/proxito/tests/test_hosting.py, readthedocs/proxito/views/hosting.py
=> Addons: make it work on invalid URLs

readthedocs/api/v2/views/model_views.py, readthedocs/rtd_tests/tests/test_api.py
We want to skip the default permsissions check here (done at `get_queryset()` method) because it filters the object by build API key and/or user access.
Since we are making an anonymous request without a build API key, we need to skip this check and base it only on the `?builder=` GET attribute.
=> Builds: healthcheck permissions

readthedocs/oauth/services/base.py, readthedocs/oauth/services/bitbucket.py, readthedocs/oauth/services/github.py, readthedocs/oauth/services/githubapp.py, readthedocs/oauth/services/gitlab.py, readthedocs/rtd_tests/tests/test_oauth.py, readthedocs/rtd_tests/tests/test_oauth_sync.py
Common changes across providers:
- A new method to just update a remote repository from the data returned by the API was added, this is in order to make it easy to re-use this method when support for updating a single repo is added (will do this in another PR on top of this one).
- We were iterating over repositories twice for GitHub and BB, once by listing all the repositories the user has access to, and then again by iterating over all the repositories from the organizations the user has access to, this was also incorrectly adding a relationship between the user and repositories the use didn't actually have access, as that endpoint will return all public repositories, even if the user doesn't belong to it.
- sync_organizations now basically just creates the user-organization relation …
=> Git services: improve sync repos

docs/user/build-customization.rst
Avoid  `:caption: .readthedocs.yaml` appearing in the UV and Poetry code block examples.
=> Clean up whitespace in build-customization.rst

docs/user/build-customization.rst
There are no reason to extract the entire archive when we only need `git-lfs` binary.
The archive also contains a `CHANGELOG.md` file, which can override the local one.
=> docs: fix git-lfs changelog overrides the local one

readthedocs/projects/tasks/builds.py
Continuation of https://github.com/readthedocs/readthedocs.org/pull/12481
=> Build: don't log `SoftTimeLimitExceeded` in Sentry

readthedocs/oauth/tasks.py
This task takes 2h 10m to complete right now. I didn't see anything in sentry about this task failing (not sure even if that will be reported there). Looks like the default time out is one hour:
https://github.com/readthedocs/readthedocs.org/blob/dcde018f1567a028cb17a2cad4990f489c0d8f8e/readthedocs/settings/base.py#L630
This would be a great use case for async python... Maybe something to explore https://stackoverflow.com/questions/72529998/how-to-use-async-function-inside-celery-task
=> Tasks: increase time limit sync_remote_repositories_from_sso_organizations

docs/user/build-customization.rst
using the same .readthedocs.yaml provided in that example, rtd used pip 23.1
<details><summary>Build raw</summary>
```
Read the Docs build information
Build id: 29787419
Project: nwb2bids
Version: 112
Commit: 0e84ccc8c749345a9af7945d514168cf435e4167
Date: 2025-10-01T17:37:54.256358Z
State: finished
Success: False
[rtd-command-info] start-time: 2025-10-01T17:37:54.772413Z, end-time: 2025-10-01T17:37:55.083275Z, duration: 0, exit-code: 0
git clone --depth 1 https://github.com/con/nwb2bids.git .
Cloning into '.'...
[rtd-command-info] start-time: 2025-10-01T17:37:55.127442Z, end-time: 2025-10-01T17:37:55.663081Z, duration: 0, exit-code: 0
git fetch origin --force --prune --prune-tags --depth 50 pull/112/head:external-112
From https://github.com/con/nwb2bids
* [new ref] …
```
=> do not claim pip 25.1 is default
